## Entorno

### Dependencias

In [ ]:
!pip install -U -q PyDrive
!pip install unidecode
!pip install ultralytics
!pip install onnx
!pip install imgaug
!pip install albumentations==1.3.0
!pip install opencv-python
!pip install pybboxes
!pip install fiftyone

Collecting unidecode
  Downloading Unidecode-1.3.8-py3-none-any.whl.metadata (13 kB)
Downloading Unidecode-1.3.8-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.5/235.5 kB 3.8 MB/s eta 0:00:00
Installing collected packages: unidecode
Successfully installed unidecode-1.3.8
Collecting ultralytics
  Downloading ultralytics-8.2.66-py3-none-any.whl.metadata (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.3/41.3 kB 1.2 MB/s eta 0:00:00
Requirement already satisfied: numpy<2.0.0,>=1.23.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (1.25.2)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (3.7.1)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (4.8.0.76)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (9.4.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (6.0.1)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (2.31.0)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (1.11.4)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (2.3.1+cu121)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (0.18.1+cu121)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (4.66.4)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.10/dist-packages (from ultralytics) (9.0.0)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (2.0.3)
Requirement already satisfied: seaborn>=0.11.0 in /usr/local/lib/python3.10/dist-packages (from ultralytics) (0.13.1)
Collecting ultralytics-thop>=2.0.0 (from ultralytics)
  Downloading ultralytics_thop-2.0.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.53.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.0->ultralytics) (24.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.4->ultralytics) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.4->ultralytics) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.23.0->ultralytics) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.23.0->ultralytics) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.23.0->ultralytics) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.23.0->ultralytics) (2024.7.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.0->ultralytics) (3.15.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.0->ultralytics) (4.12.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.0->ultralytics) (1.13.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.0->ultralytics) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.0->ultralytics) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.0->ultralytics) (2023.6.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch>=1.8.0->ultralytics)
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch>=1.8.0->ultralytics)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch>=1.8.0->ultralytics)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch>=1.8.0->ultralytics)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch>=1.8.0->ultralytics)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch>=1.8.0->ultralytics)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch>=1.8.0->ultralytics)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch>=1.8.0->ultralytics)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch>=1.8.0->ultralytics)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.20.5 (from torch>=1.8.0->ultralytics)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch>=1.8.0->ultralytics)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: triton==2.3.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.0->ultralytics) (2.3.1)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.8.0->ultralytics)
  Downloading nvidia_nvjitlink_cu12-12.5.82-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.8.0->ultralytics) (1.3.0)
Downloading ultralytics-8.2.66-py3-none-any.whl (825 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 825.5/825.5 kB 24.9 MB/s eta 0:00:00
Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
Downloading ultralytics_thop-2.0.0-py3-none-any.whl (25 kB)
Downloading nvidia_nvjitlink_cu12-12.5.82-py3-none-manylinux2014_x86_64.whl (21.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21.3 MB 18.4 MB/s eta 0:00:00
Installing collected packages: nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, ultralytics-thop, ultralytics
Successfully installed nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.20.5 nvidia-nvjitlink-cu12-12.5.82 nvidia-nvtx-cu12-12.1.105 ultralytics-8.2.66 ultralytics-thop-2.0.0
Collecting onnx
  Downloading onnx-1.16.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (16 kB)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.10/dist-packages (from onnx) (1.25.2)
Requirement already satisfied: protobuf>=3.20.2 in /usr/local/lib/python3.10/dist-packages (from onnx) (3.20.3)
Downloading onnx-1.16.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (15.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.9/15.9 MB 99.2 MB/s eta 0:00:00
Installing collected packages: onnx
Successfully installed onnx-1.16.1
Requirement already satisfied: imgaug in /usr/local/lib/python3.10/dist-packages (0.4.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from imgaug) (1.16.0)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.10/dist-packages (from imgaug) (1.25.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from imgaug) (1.11.4)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from imgaug) (9.4.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from imgaug) (3.7.1)
Requirement already satisfied: scikit-image>=0.14.2 in /usr/local/lib/python3.10/dist-packages (from imgaug) (0.19.3)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.10/dist-packages (from imgaug) (4.8.0.76)
Requirement already satisfied: imageio in /usr/local/lib/python3.10/dist-packages (from imgaug) (2.31.6)
Requirement already satisfied: Shapely in /usr/local/lib/python3.10/dist-packages (from imgaug) (2.0.5)
Requirement already satisfied: networkx>=2.2 in /usr/local/lib/python3.10/dist-packages (from scikit-image>=0.14.2->imgaug) (3.3)
Requirement already satisfied: tifffile>=2019.7.26 in /usr/local/lib/python3.10/dist-packages (from scikit-image>=0.14.2->imgaug) (2024.7.21)
Requirement already satisfied: PyWavelets>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-image>=0.14.2->imgaug) (1.6.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from scikit-image>=0.14.2->imgaug) (24.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->imgaug) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->imgaug) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->imgaug) (4.53.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->imgaug) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->imgaug) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->imgaug) (2.8.2)
Collecting albumentations==1.3.0
  Downloading albumentations-1.3.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: numpy>=1.11.1 in /usr/local/lib/python3.10/dist-packages (from albumentations==1.3.0) (1.25.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from albumentations==1.3.0) (1.11.4)
Requirement already satisfied: scikit-image>=0.16.1 in /usr/local/lib/python3.10/dist-packages (from albumentations==1.3.0) (0.19.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from albumentations==1.3.0) (6.0.1)
Requirement already satisfied: qudida>=0.0.4 in /usr/local/lib/python3.10/dist-packages (from albumentations==1.3.0) (0.0.4)
Requirement already satisfied: opencv-python-headless>=4.1.1 in /usr/local/lib/python3.10/dist-packages (from albumentations==1.3.0) (4.10.0.84)
Requirement already satisfied: scikit-learn>=0.19.1 in /usr/local/lib/python3.10/dist-packages (from qudida>=0.0.4->albumentations==1.3.0) (1.2.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from qudida>=0.0.4->albumentations==1.3.0) (4.12.2)
Requirement already satisfied: networkx>=2.2 in /usr/local/lib/python3.10/dist-packages (from scikit-image>=0.16.1->albumentations==1.3.0) (3.3)
Requirement already satisfied: pillow!=7.1.0,!=7.1.1,!=8.3.0,>=6.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-image>=0.16.1->albumentations==1.3.0) (9.4.0)
Requirement already satisfied: imageio>=2.4.1 in /usr/local/lib/python3.10/dist-packages (from scikit-image>=0.16.1->albumentations==1.3.0) (2.31.6)
Requirement already satisfied: tifffile>=2019.7.26 in /usr/local/lib/python3.10/dist-packages (from scikit-image>=0.16.1->albumentations==1.3.0) (2024.7.21)
Requirement already satisfied: PyWavelets>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-image>=0.16.1->albumentations==1.3.0) (1.6.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from scikit-image>=0.16.1->albumentations==1.3.0) (24.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations==1.3.0) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations==1.3.0) (3.5.0)
Downloading albumentations-1.3.0-py3-none-any.whl (123 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.5/123.5 kB 7.5 MB/s eta 0:00:00
Installing collected packages: albumentations
  Attempting uninstall: albumentations
    Found existing installation: albumentations 1.3.1
    Uninstalling albumentations-1.3.1:
      Successfully uninstalled albumentations-1.3.1
Successfully installed albumentations-1.3.0
Requirement already satisfied: opencv-python in /usr/local/lib/python3.10/dist-packages (4.8.0.76)
Requirement already satisfied: numpy>=1.21.2 in /usr/local/lib/python3.10/dist-packages (from opencv-python) (1.25.2)
Collecting pybboxes
  Downloading pybboxes-0.1.6-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from pybboxes) (1.25.2)
Downloading pybboxes-0.1.6-py3-none-any.whl (24 kB)
Installing collected packages: pybboxes
Successfully installed pybboxes-0.1.6
Collecting fiftyone
  Downloading fiftyone-0.24.1-py3-none-any.whl.metadata (12 kB)
Collecting aiofiles (from fiftyone)
  Downloading aiofiles-24.1.0-py3-none-any.whl.metadata (10 kB)
Collecting argcomplete (from fiftyone)
  Downloading argcomplete-3.4.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from fiftyone) (4.12.3)
Collecting boto3 (from fiftyone)
  Downloading boto3-1.34.149-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: cachetools in /usr/local/lib/python3.10/dist-packages (from fiftyone) (5.4.0)
Collecting dacite<1.8.0,>=1.6.0 (from fiftyone)
  Downloading dacite-1.7.0-py3-none-any.whl.metadata (14 kB)
Collecting Deprecated (from fiftyone)
  Downloading Deprecated-1.2.14-py2.py3-none-any.whl.metadata (5.4 kB)
Collecting ftfy (from fiftyone)
  Downloading ftfy-6.2.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: humanize in /usr/local/lib/python3.10/dist-packages (from fiftyone) (4.7.0)
Collecting hypercorn>=0.13.2 (from fiftyone)
  Downloading hypercorn-0.17.3-py3-none-any.whl.metadata (5.4 kB)
Collecting Jinja2==3.0.3 (from fiftyone)
  Downloading Jinja2-3.0.3-py3-none-any.whl.metadata (3.5 kB)
Collecting kaleido!=0.2.1.post1 (from fiftyone)
  Downloading kaleido-0.2.1-py2.py3-none-manylinux1_x86_64.whl.metadata (15 kB)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from fiftyone) (3.7.1)
Collecting mongoengine==0.24.2 (from fiftyone)
  Downloading mongoengine-0.24.2-py3-none-any.whl.metadata (6.7 kB)
Collecting motor>=2.5 (from fiftyone)
  Downloading motor-3.5.1-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from fiftyone) (1.25.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from fiftyone) (24.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from fiftyone) (2.0.3)
Requirement already satisfied: Pillow>=6.2 in /usr/local/lib/python3.10/dist-packages (from fiftyone) (9.4.0)
Requirement already satisfied: plotly>=4.14 in /usr/local/lib/python3.10/dist-packages (from fiftyone) (5.15.0)
Collecting pprintpp (from fiftyone)
  Downloading pprintpp-0.4.0-py2.py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from fiftyone) (5.9.5)
Collecting pymongo>=3.12 (from fiftyone)
  Downloading pymongo-4.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (22 kB)
Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (from fiftyone) (2023.4)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from fiftyone) (6.0.1)
Requirement already satisfied: regex in /usr/local/lib/python3.10/dist-packages (from fiftyone) (2024.5.15)
Collecting retrying (from fiftyone)
  Downloading retrying-1.3.4-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from fiftyone) (1.2.2)
Requirement already satisfied: scikit-image in /usr/local/lib/python3.10/dist-packages (from fiftyone) (0.19.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from fiftyone) (1.11.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from fiftyone) (71.0.4)
Collecting sseclient-py<2,>=1.7.2 (from fiftyone)
  Downloading sseclient_py-1.8.0-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting sse-starlette<1,>=0.10.3 (from fiftyone)
  Downloading sse_starlette-0.10.3-py3-none-any.whl.metadata (4.3 kB)
Collecting starlette>=0.24.0 (from fiftyone)
  Downloading starlette-0.38.1-py3-none-any.whl.metadata (5.9 kB)
Collecting strawberry-graphql==0.138.1 (from fiftyone)
  Downloading strawberry_graphql-0.138.1-py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: tabulate in /usr/local/lib/python3.10/dist-packages (from fiftyone) (0.9.0)
Collecting xmltodict (from fiftyone)
  Downloading xmltodict-0.13.0-py2.py3-none-any.whl.metadata (7.7 kB)
Collecting universal-analytics-python3<2,>=1.0.1 (from fiftyone)
  Downloading universal_analytics_python3-1.1.1-py3-none-any.whl.metadata (5.5 kB)

In [ ]:
import pandas as pd
import re
import unidecode
import codecs
import cv2
import torch
import glob
import locale
from collections import Counter

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from google.colab import drive as dri
from oauth2client.client import GoogleCredentials
from google_drive_downloader import GoogleDriveDownloader as gdd

import sys
import inspect
import os
import zipfile
import shutil
from tqdm import tqdm

from sklearn.model_selection import train_test_split
from ultralytics import YOLO

import seaborn as sns
import matplotlib.pyplot as plt

import fiftyone as fo
import fiftyone.zoo as foz

WARNING:root:pydrive is deprecated and no longer maintained. We recommend that you migrate your projects to pydrive2, the maintained fork of pydrive

In [ ]:
locale.getpreferredencoding = lambda: "UTF-8"
locale.getpreferredencoding = lambda x: "UTF-8"

### Autenticacion

In [ ]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

# dri.mount('/content/drive')

In [ ]:
def get_default_device():
    if torch.cuda.is_available():
        return torch.device('cuda')
    else:
        return torch.device('cpu')

def to_device(data, device):
    if isinstance(data, (list,tuple)):
        return [to_device(x, device) for x in data]
    return data.to(device, non_blocking=True)

class DeviceDataLoader():
    def __init__(self, dl, device):
        self.dl = dl
        self.device = device

    def __iter__(self):
        for b in self.dl:
            yield to_device(b, self.device)

    def __len__(self):
        return
        len(self.dl)

device = get_default_device()
device

device(type='cuda')

## Fuente principal

### Main

In [ ]:
# https://docs.google.com/spreadsheets/d/1azJrrovCMYBeRasAOwh-87nVSxQPdjRs2AfBoKy97-0/edit?gid=972313100#gid=972313100

gsheetkey = "1azJrrovCMYBeRasAOwh-87nVSxQPdjRs2AfBoKy97-0"
url=f'https://docs.google.com/spreadsheet/ccc?key={gsheetkey}&output=xlsx'

df = pd.read_excel(url)

display(df.head())

,Marca temporal,Dirección de correo electrónico,Nombre/s,Apellido,Comentarios sobre la entrega,Dirección del gdrive donde se encuentran las imágenes (debe ser público para lectura y no para escritura)
0,2024-06-06 19:27:16.912,lucasdemarre4@gmail.com,Lucas Federico,Demarré Estofan,NaN,https://drive.google.com/drive/folders/1oP843e...
1,2024-06-07 19:59:35.985,tomas.navarro13@live.com,Tomás,Navarro Miñón,"este drive está con un formato json, no con jp...",https://drive.google.com/drive/folders/1u9jEZc...
2,2024-06-10 10:06:35.341,facufontela98@gmail.com,Facundo,Fontela,NaN,https://drive.google.com/drive/u/0/folders/100...
3,2024-06-10 18:57:42.975,peroniantonioa@gmail.com,Antonio,Peroni,NaN,https://drive.google.com/drive/folders/1eglmMN...
4,2024-06-10 22:15:40.977,micaelapozzo25@gmail.com,Micaela,Pozzo,NaN,https://drive.google.com/drive/folders/13brsg_...

In [ ]:
folders = df['Dirección del gdrive donde se encuentran las imágenes (debe ser público para lectura y no para escritura)']

display(folders.head(2))
print(folders[0])

0    https://drive.google.com/drive/folders/1oP843e...
1    https://drive.google.com/drive/folders/1u9jEZc...
Name: Dirección del gdrive donde se encuentran las imágenes (debe ser público para lectura y no para escritura), dtype: object

https://drive.google.com/drive/folders/1oP843ex0ddgIU7voFZd-cuEddhrrFArR?usp=sharing

### Filtro

In [ ]:
def get_folder_id(folder_url):
    match = re.search(r'\/folders\/([a-zA-Z0-9_-]+)', folder_url)
    if match:
        folder_id = match.group(1)
        return folder_id
    else:
        raise ValueError(f"Cannot extract folder ID from URL: {folder_url}")

def list_files_in_folder(folder_id):
    file_list = drive.ListFile({'q': f"'{folder_id}' in parents and trashed=false"}).GetList()
    files = []
    for file in file_list:
        file_name = unidecode.unidecode(file['title'])
        file_url = f"https://drive.google.com/file/d/{file['id']}/view?usp=drive_link"
        files.append((file_name, file_url, file['id']))
    return files

In [ ]:
all_files = []

for folder_url in folders:
    folder_id = get_folder_id(folder_url)
    files = list_files_in_folder(folder_id)

    for file_name, file_url, file_id in files:

        if folder_url == 'https://drive.google.com/drive/u/0/folders/100KzDMdj7VEzSexbFfTci_wYDzSEawvv':
            if not file_name.startswith('37249_fontela_facundo'):
                continue

        all_files.append((folder_url, file_name, file_url, file_id))

file_df = pd.DataFrame(all_files, columns=["folder_url", "file_name", "file_url", "file_id"])

display(file_df)

,folder_url,file_name,file_url,file_id
0,https://drive.google.com/drive/folders/1oP843e...,43265_Lucas_Demarre_30.txt,https://drive.google.com/file/d/1d8thBSXKkaCsg...,1d8thBSXKkaCsgpJ6mmPgbgX3LRRsCk_e
1,https://drive.google.com/drive/folders/1oP843e...,43265_Lucas_Demarre_29.txt,https://drive.google.com/file/d/1z324Mnig7tqIj...,1z324Mnig7tqIjuz8ha4CWKcWxMsmk1kA
2,https://drive.google.com/drive/folders/1oP843e...,43265_Lucas_Demarre_28.txt,https://drive.google.com/file/d/13c6_6t7JXHPSg...,13c6_6t7JXHPSgY0e6QYEQJUf2xKDEIci
3,https://drive.google.com/drive/folders/1oP843e...,43265_Lucas_Demarre_27.txt,https://drive.google.com/file/d/1xo9SWuVfh4ftS...,1xo9SWuVfh4ftScqN8__Lv4N-lxbyrs0G
4,https://drive.google.com/drive/folders/1oP843e...,43265_Lucas_Demarre_26.txt,https://drive.google.com/file/d/1e0gtQeOs5vGTp...,1e0gtQeOs5vGTpM1CrD3E1ZvfH4yPPlWI
...,...,...,...,...
3310,https://drive.google.com/drive/folders/1sxvqCQ...,P51926_Leonel_Palermo_10.png,https://drive.google.com/file/d/1fOMKNK_X634ML...,1fOMKNK_X634MLEw0y0zZwqwf9OnAo9TC
3311,https://drive.google.com/drive/folders/1sxvqCQ...,P51926_Leonel_Palermo_23.png,https://drive.google.com/file/d/17hOHa7I6FpiDq...,17hOHa7I6FpiDqDvaxfZxN3SYS0uSK5mE
3312,https://drive.google.com/drive/folders/1sxvqCQ...,P51926_Leonel_Palermo_28.png,https://drive.google.com/file/d/1OlHlNC6OBfuKG...,1OlHlNC6OBfuKGZGC-2Kjzd2mzM0Mmp6-
3313,https://drive.google.com/drive/folders/1sxvqCQ...,P51926_Leonel_Palermo_26.png,https://drive.google.com/file/d/1XGJpkQh_ULiK8...,1XGJpkQh_ULiK8mOmA3c94QOU4OdpFAEm
3314,https://drive.google.com/drive/folders/1sxvqCQ...,P51926_Leonel_Palermo_27.png,https://drive.google.com/file/d/1-hvHOBZo82-VJ...,1-hvHOBZo82-VJJIK8N-YdAGYkN-jPGqA

### Control

In [ ]:
file_df.sort_values(by=["file_name"], inplace=True)
file_df.reset_index(inplace=True, drop=True)
display(file_df)

,folder_url,file_name,file_url,file_id
0,https://drive.google.com/drive/folders/1_LRwpr...,03531_mirian_yanez_01.jpeg,https://drive.google.com/file/d/1A4uqu_M6gWdbP...,1A4uqu_M6gWdbPB2APkn3zz8cO0PT1C2N
1,https://drive.google.com/drive/folders/1_LRwpr...,03531_mirian_yanez_01.txt,https://drive.google.com/file/d/18TX3BPnx-l5C1...,18TX3BPnx-l5C1znZG84pL65_KJyKMIkH
2,https://drive.google.com/drive/folders/1_LRwpr...,03531_mirian_yanez_02.jpeg,https://drive.google.com/file/d/1oR5PQMncMNqqJ...,1oR5PQMncMNqqJf1hhOaFpo319TD9r0qv
3,https://drive.google.com/drive/folders/1_LRwpr...,03531_mirian_yanez_02.txt,https://drive.google.com/file/d/14OUPT4ikCpHgx...,14OUPT4ikCpHgxN9DlwbFrPQ6j6opYncF
4,https://drive.google.com/drive/folders/1_LRwpr...,03531_mirian_yanez_03.jpeg,https://drive.google.com/file/d/1qYCHZPRl31kIr...,1qYCHZPRl31kIrvRnDIuflFYM8ItQYsV5
...,...,...,...,...
3310,https://drive.google.com/drive/folders/1lOclnm...,w05576_juan_wagner_31.txt,https://drive.google.com/file/d/1FQZB0tykZTJDv...,1FQZB0tykZTJDvj-H9oIz7qfStd-TflZx
3311,https://drive.google.com/drive/folders/1lOclnm...,w05576_juan_wagner_32.png,https://drive.google.com/file/d/1KNZ4WCtcva2BJ...,1KNZ4WCtcva2BJsNurUKbC-CllBuWbUzJ
3312,https://drive.google.com/drive/folders/1lOclnm...,w05576_juan_wagner_32.txt,https://drive.google.com/file/d/1GWe__Ya4d77em...,1GWe__Ya4d77emXy3w3KevLiMthxwvi28
3313,https://drive.google.com/drive/folders/1lOclnm...,w05576_juan_wagner_33.png,https://drive.google.com/file/d/1536Qvvjei_Ay4...,1536Qvvjei_Ay4oZhw2lQpN82aDzMcmd7
3314,https://drive.google.com/drive/folders/1lOclnm...,w05576_juan_wagner_33.txt,https://drive.google.com/file/d/1MoC25vxi9bLnP...,1MoC25vxi9bLnP-WuK4jjKprdkj_8D7pk

In [ ]:
# Extract base file name and extension
file_df['base_file_name'] = file_df['file_name'].apply(lambda x: x.rsplit('.', 1)[0] if len(x) > 1 else '')
file_df['file_extension'] = file_df['file_name'].apply(lambda x: x.rsplit('.', 1)[1] if '.' in x else '')

file_df

,folder_url,file_name,file_url,file_id,base_file_name,file_extension
0,https://drive.google.com/drive/folders/1_LRwpr...,03531_mirian_yanez_01.jpeg,https://drive.google.com/file/d/1A4uqu_M6gWdbP...,1A4uqu_M6gWdbPB2APkn3zz8cO0PT1C2N,03531_mirian_yanez_01,jpeg
1,https://drive.google.com/drive/folders/1_LRwpr...,03531_mirian_yanez_01.txt,https://drive.google.com/file/d/18TX3BPnx-l5C1...,18TX3BPnx-l5C1znZG84pL65_KJyKMIkH,03531_mirian_yanez_01,txt
2,https://drive.google.com/drive/folders/1_LRwpr...,03531_mirian_yanez_02.jpeg,https://drive.google.com/file/d/1oR5PQMncMNqqJ...,1oR5PQMncMNqqJf1hhOaFpo319TD9r0qv,03531_mirian_yanez_02,jpeg
3,https://drive.google.com/drive/folders/1_LRwpr...,03531_mirian_yanez_02.txt,https://drive.google.com/file/d/14OUPT4ikCpHgx...,14OUPT4ikCpHgxN9DlwbFrPQ6j6opYncF,03531_mirian_yanez_02,txt
4,https://drive.google.com/drive/folders/1_LRwpr...,03531_mirian_yanez_03.jpeg,https://drive.google.com/file/d/1qYCHZPRl31kIr...,1qYCHZPRl31kIrvRnDIuflFYM8ItQYsV5,03531_mirian_yanez_03,jpeg
...,...,...,...,...,...,...
3310,https://drive.google.com/drive/folders/1lOclnm...,w05576_juan_wagner_31.txt,https://drive.google.com/file/d/1FQZB0tykZTJDv...,1FQZB0tykZTJDvj-H9oIz7qfStd-TflZx,w05576_juan_wagner_31,txt
3311,https://drive.google.com/drive/folders/1lOclnm...,w05576_juan_wagner_32.png,https://drive.google.com/file/d/1KNZ4WCtcva2BJ...,1KNZ4WCtcva2BJsNurUKbC-CllBuWbUzJ,w05576_juan_wagner_32,png
3312,https://drive.google.com/drive/folders/1lOclnm...,w05576_juan_wagner_32.txt,https://drive.google.com/file/d/1GWe__Ya4d77em...,1GWe__Ya4d77emXy3w3KevLiMthxwvi28,w05576_juan_wagner_32,txt
3313,https://drive.google.com/drive/folders/1lOclnm...,w05576_juan_wagner_33.png,https://drive.google.com/file/d/1536Qvvjei_Ay4...,1536Qvvjei_Ay4oZhw2lQpN82aDzMcmd7,w05576_juan_wagner_33,png
3314,https://drive.google.com/drive/folders/1lOclnm...,w05576_juan_wagner_33.txt,https://drive.google.com/file/d/1MoC25vxi9bLnP...,1MoC25vxi9bLnP-WuK4jjKprdkj_8D7pk,w05576_juan_wagner_33,txt

In [ ]:
file_df.groupby('file_extension').size().reset_index(name='count')

  file_extension  count
0           jpeg    100
1            jpg    707
2            png    850
3            txt   1658

In [ ]:
allowed_extensions = ['jpeg', 'jpg', 'png', 'txt']
file_df = file_df[file_df['file_extension'].isin(allowed_extensions)]

In [ ]:
file_counts = file_df.groupby('base_file_name').size().reset_index(name='count')
file_counts[file_counts['count'] != 2].values

array([['429816_cesar_donnarumma_01', 1],
       ['429816_cesar_donnarumma_02', 1],
       ['429816_cesar_donnarumma_03', 1],
       ['429816_cesar_donnarumma_04', 1],
       ['429816_cesar_donnarumma_05', 1],
       ['429816_cesar_donnarumma_06', 1],
       ['429816_cesar_donnarumma_07', 1],
       ['429816_cesar_donnarumma_08', 1],
       ['429816_cesar_donnarumma_09', 1],
       ['429816_cesar_donnarumma_10', 1],
       ['429816_cesar_donnarumma_11', 1],
       ['429816_cesar_donnarumma_12', 1],
       ['429816_cesar_donnarumma_13', 1],
       ['429816_cesar_donnarumma_14', 1],
       ['429816_cesar_donnarumma_15', 1],
       ['429816_cesar_donnarumma_16', 1],
       ['429816_cesar_donnarumma_17', 1],
       ['429816_cesar_donnarumma_18', 1],
       ['429816_cesar_donnarumma_19', 1],
       ['429816_cesar_donnarumma_20', 1],
       ['429816_cesar_donnarumma_21', 1],
       ['429816_cesar_donnarumma_22', 1],
       ['429816_cesar_donnarumma_23', 1],
       ['429816_cesar_donnarumma_24', 1],
       ['429816_cesar_donnarumma_25', 1],
       ['429816_cesar_donnarumma_26', 1],
       ['429816_cesar_donnarumma_27', 1],
       ['429816_cesar_donnarumma_28', 1],
       ['429816_cesar_donnarumma_29', 1],
       ['429816_cesar_donnarumma_30', 1],
       ['429816_cesar_donnarumma_31', 1],
       ['classes', 1],
       ['d429816_cesar_donnarumma_01', 1],
       ['d429816_cesar_donnarumma_02', 1],
       ['d429816_cesar_donnarumma_03', 1],
       ['d429816_cesar_donnarumma_04', 1],
       ['d429816_cesar_donnarumma_05', 1],
       ['d429816_cesar_donnarumma_06', 1],
       ['d429816_cesar_donnarumma_07', 1],
       ['d429816_cesar_donnarumma_08', 1],
       ['d429816_cesar_donnarumma_09', 1],
       ['d429816_cesar_donnarumma_10', 1],
       ['d429816_cesar_donnarumma_11', 1],
       ['d429816_cesar_donnarumma_12', 1],
       ['d429816_cesar_donnarumma_13', 1],
       ['d429816_cesar_donnarumma_14', 1],
       ['d429816_cesar_donnarumma_15', 1],
       ['d429816_cesar_donnarumma_16', 1],
       ['d429816_cesar_donnarumma_17', 1],
       ['d429816_cesar_donnarumma_18', 1],
       ['d429816_cesar_donnarumma_19', 1],
       ['d429816_cesar_donnarumma_20', 1],
       ['d429816_cesar_donnarumma_21', 1],
       ['d429816_cesar_donnarumma_22', 1],
       ['d429816_cesar_donnarumma_23', 1],
       ['d429816_cesar_donnarumma_24', 1],
       ['d429816_cesar_donnarumma_25', 1],
       ['d429816_cesar_donnarumma_26', 1],
       ['d429816_cesar_donnarumma_27', 1],
       ['d429816_cesar_donnarumma_28', 1],
       ['d429816_cesar_donnarumma_29', 1],
       ['d429816_cesar_donnarumma_30', 1],
       ['d429816_cesar_donnarumma_31', 1],
       ['gravifiorino_2', 1],
       ['gravifiorino_3', 1]], dtype=object)

In [ ]:
mask = file_df['base_file_name'].str.startswith('d429816_cesar_donnarumma')
file_df.loc[mask, 'base_file_name'] = file_df.loc[mask, 'base_file_name'].str.replace('^d', '', regex=True)

In [ ]:
to_remove = file_counts[file_counts['count'] != 2]['base_file_name']
file_df = file_df[~file_df['base_file_name'].isin(to_remove)]

In [ ]:
file_df.groupby('file_extension').count()

                folder_url  file_name  file_url  file_id  base_file_name
file_extension
jpeg                    99         99        99       99              99
jpg                    707        707       707      707             707
png                    819        819       819      819             819
txt                   1625       1625      1625     1625            1625

In [ ]:
1468 == 99+438+931

True

### Splitting

In [ ]:
file_df.head(2)

,folder_url,file_name,file_url,file_id,base_file_name,file_extension
0,https://drive.google.com/drive/folders/1_LRwpr...,03531_mirian_yanez_01.jpeg,https://drive.google.com/file/d/1A4uqu_M6gWdbP...,1A4uqu_M6gWdbPB2APkn3zz8cO0PT1C2N,03531_mirian_yanez_01,jpeg
1,https://drive.google.com/drive/folders/1_LRwpr...,03531_mirian_yanez_01.txt,https://drive.google.com/file/d/18TX3BPnx-l5C1...,18TX3BPnx-l5C1znZG84pL65_KJyKMIkH,03531_mirian_yanez_01,txt

In [ ]:
file_df.shape

(3250, 6)

In [ ]:
dataset_path = '/content/dataset'
os.makedirs(dataset_path, exist_ok=True)

train_images_path = os.path.join(dataset_path, 'images/train')
val_images_path = os.path.join(dataset_path, 'images/val')
train_labels_path = os.path.join(dataset_path, 'labels/train')
val_labels_path = os.path.join(dataset_path, 'labels/val')

def clear_directory(path):
    if os.path.exists(path):
        shutil.rmtree(path)
    os.makedirs(path, exist_ok=True)

clear_directory(train_images_path)
clear_directory(val_images_path)
clear_directory(train_labels_path)
clear_directory(val_labels_path)

In [ ]:
# Split the DataFrame into images and labels based on file extension
images_df = file_df[file_df['file_extension'].isin(['jpeg', 'jpg', 'png'])]
labels_df = file_df[file_df['file_extension'] == 'txt']

# Split images into training and validation sets (70% train, 30% val)
train_images_df, val_images_df = train_test_split(images_df, test_size=0.3, random_state=42)

# Get the corresponding label files for training and validation sets
train_labels_df = labels_df[labels_df['base_file_name'].isin(train_images_df['base_file_name'])]
val_labels_df = labels_df[labels_df['base_file_name'].isin(val_images_df['base_file_name'])]

# Sample 1% of the training and validation sets
# sampled_train_images_df = train_images_df.sample(frac=0.005, random_state=42)
# sampled_val_images_df = val_images_df.sample(frac=0.005, random_state=42)

sampled_train_images_df = train_images_df.sample(frac=1, random_state=42)
sampled_val_images_df = val_images_df.sample(frac=1, random_state=42)

sampled_train_labels_df = train_labels_df[train_labels_df['base_file_name'].isin(sampled_train_images_df['base_file_name'])]
sampled_val_labels_df = val_labels_df[val_labels_df['base_file_name'].isin(sampled_val_images_df['base_file_name'])]

In [ ]:
display(sampled_train_images_df.shape)
display(sampled_val_images_df.shape)
display(sampled_train_labels_df.shape)
display(sampled_val_labels_df.shape)

(1137, 6)

(488, 6)

(1137, 6)

(488, 6)

### Descarga

In [ ]:
train_images = "/content/dataset/images/train"
train_labels = "/content/dataset/labels/train"
val_images = "/content/dataset/images/val"
val_labels = "/content/dataset/labels/val"

def clear_folder(folder_path):
    if os.path.exists(folder_path):
        for filename in os.listdir(folder_path):
            file_path = os.path.join(folder_path, filename)
            if os.path.isfile(file_path):
                os.remove(file_path)

clear_folder(train_images)
clear_folder(train_labels)
clear_folder(val_images)
clear_folder(val_labels)

In [ ]:
def download_files(df, destination_folder):
    for index, row in tqdm(df.iterrows(), total=df.shape[0]):
        file_id = row['file_id']
        file_name = row['file_name']
        file_path = os.path.join(destination_folder, file_name)
        gdd.download_file_from_google_drive(file_id=file_id,
                                            dest_path=file_path,
                                            unzip=False,
                                            overwrite=False)

download_files(sampled_train_images_df, train_images_path)
download_files(sampled_val_images_df, val_images_path)
download_files(sampled_train_labels_df, train_labels_path)
download_files(sampled_val_labels_df, val_labels_path)

  0%|          | 0/1137 [00:00<?, ?it/s]

Downloading 1Ks9-vR5PgZOq7Pqf7515MTH14jHwbVuI into /content/dataset/images/train/bf903deb0c6215564562b47fd9e4b900.png...

  0%|          | 1/1137 [00:02<55:25,  2.93s/it]

Done.
Downloading 1Iwp0bJ8I0paiYfp20ddK-DxG-NqG1EyL into /content/dataset/images/train/37524_augusto_farias_10.jpg...

  0%|          | 2/1137 [00:09<1:33:16,  4.93s/it]

Done.
Downloading 1GtzZWAdnbTVwjYb_9SMt66v8NFtqNs0u into /content/dataset/images/train/12394_escandell_ariel_14.jpg...

  0%|          | 3/1137 [00:11<1:13:25,  3.89s/it]

Done.
Downloading 1HbQd-3l4v6EwNvOWR7oQLr17jmidaITW into /content/dataset/images/train/F37605_florencia_fernandez_41.png...

  0%|          | 4/1137 [00:14<1:04:34,  3.42s/it]

Done.
Downloading 14Tp6PSzl68U4X2UYlePF0samCvV-XmVo into /content/dataset/images/train/gravifiorino_4.jpeg...

  0%|          | 5/1137 [00:16<56:41,  3.00s/it]

Done.
Downloading 1EC4j0epUQYbhLLRoReF4_ZJTsskFl46Q into /content/dataset/images/train/71846_Brisa_Menescaldi_20.png...

  1%|          | 6/1137 [00:21<1:05:56,  3.50s/it]

Done.
Downloading 1CTJlL4AuD7bv-mh54WYL1pJqHrXpWblK into /content/dataset/images/train/57096_ramiro_sagrera_10.jpg...

  1%|          | 7/1137 [00:24<1:03:21,  3.36s/it]

Done.
Downloading 1vXhh3ckPsfeIzNdm1g3tERvXqH5KyfMt into /content/dataset/images/train/43237686_Constantino_Ferrucci_20.png...

  1%|          | 8/1137 [00:27<59:26,  3.16s/it]

Done.
Downloading 1ZhdS3x8H96VwD04CGSeGlpMqzzIffq0l into /content/dataset/images/train/L32425_eugenio_lopez_28.png...

  1%|          | 9/1137 [00:32<1:10:53,  3.77s/it]

Done.
Downloading 1IPfQ9v-RG2jScqg4Imt0ip_s4oxFPxUg into /content/dataset/images/train/43237686_Constantino_Ferrucci_22.png...

  1%|          | 10/1137 [00:35<1:07:42,  3.60s/it]

Done.
Downloading 14LpABq8X4bI3tsdsJieI4wBFscnkDRMU into /content/dataset/images/train/57096_ramiro_sagrera_22.jpg...

  1%|          | 11/1137 [00:39<1:07:31,  3.60s/it]

Done.
Downloading 1CP0wlSVRdjUaqUfePi3KMyxeHGFUfm1d into /content/dataset/images/train/41932688_Simon_Revello_9.png...

  1%|          | 12/1137 [00:43<1:13:52,  3.94s/it]

Done.
Downloading 1mCvV7CnrSIppWTp5L8rm617WLn6qUG3Z into /content/dataset/images/train/43841031_Enzo_Ferrari_00.png...

  1%|          | 13/1137 [00:47<1:14:58,  4.00s/it]

Done.
Downloading 1oB_b72UGO8eYRzUFDfK8BQ5FQTkfq_BJ into /content/dataset/images/train/A45161_Fabian_Aguirre_16.png...

  1%|          | 14/1137 [00:50<1:07:20,  3.60s/it]

Done.
Downloading 1xEmuLixtvWnEq2QsLpFDpTaYgZ3TQ_uP into /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_18.jpg...

  1%|▏         | 15/1137 [00:53<1:03:16,  3.38s/it]

Done.
Downloading 1JWjNrcVc4hFGBQvInAAYC_Nu1QdGkDYv into /content/dataset/images/train/s56189_salvador_sanchez_65.jpg...

  1%|▏         | 16/1137 [00:55<57:56,  3.10s/it]

Done.
Downloading 1bqqNLQuKw0lA3QHO2vhWdXxytodQ20mW into /content/dataset/images/train/g5845_gravifiorino_9.jpeg...

  1%|▏         | 17/1137 [00:58<53:16,  2.85s/it]

Done.
Downloading 1HXAyWDzM7Dj9BJYSj7M01vavtgPqu2e1 into /content/dataset/images/train/12394_escandell_ariel_04.jpg...

  2%|▏         | 18/1137 [01:01<53:16,  2.86s/it]

Done.
Downloading 1h1tGaTuxJuMpcW-1CExJLFpSHj6070dU into /content/dataset/images/train/58491_fabio_giampaoli_18.png...

  2%|▏         | 19/1137 [01:08<1:17:50,  4.18s/it]

Done.
Downloading 1jlKPcHGvYErP0K0Yg_YQS7uCsMdXsCPP into /content/dataset/images/train/L32425_eugenio_lopez_07.png...

  2%|▏         | 20/1137 [01:11<1:12:15,  3.88s/it]

Done.
Downloading 11obXjmJ_tXAmm-lf-i81zOXMKqdbxpa- into /content/dataset/images/train/72125_miguel_mussi_01.png...

  2%|▏         | 21/1137 [01:12<56:44,  3.05s/it]

Done.
Downloading 1LUjJdCdoKNAEkQjxUxQaR6U7rSIGHbro into /content/dataset/images/train/b51e3ed9fcb3bf55ff9f61a2e0ca74b1.png...

  2%|▏         | 22/1137 [01:15<54:02,  2.91s/it]

Done.
Downloading 1DQ8TLqTaCmPI30UzbEl3MBlmwxhyJ7v2 into /content/dataset/images/train/57096_ramiro_sagrera_09.jpg...

  2%|▏         | 23/1137 [01:18<55:54,  3.01s/it]

Done.
Downloading 1qgWLae7bWRzFHZpkJGiFBuVZLV7zg6tX into /content/dataset/images/train/41932688_Simon_Revello_10.png...

  2%|▏         | 24/1137 [01:24<1:11:14,  3.84s/it]

Done.
Downloading 17ZvbXQmnRqZcDZ2OBgGyZVrY9P79xs7p into /content/dataset/images/train/41932688_Simon_Revello_14.png...

  2%|▏         | 25/1137 [01:28<1:14:10,  4.00s/it]

Done.
Downloading 1MuDifOLOuzosXOBOdFgb2konS8Zl2VJi into /content/dataset/images/train/43841031_Enzo_Ferrari_33.png...

  2%|▏         | 26/1137 [01:30<1:04:30,  3.48s/it]

Done.
Downloading 10vpvxZzM6k75-9eLfL-vw8jfIVERFIZa into /content/dataset/images/train/s56189_salvador_sanchez_17.jpg...

  2%|▏         | 27/1137 [01:33<57:27,  3.11s/it]

Done.
Downloading 1ULM3ZmfsOFFRByQG9HN6b6KeOsVcoL05 into /content/dataset/images/train/37494_gustavo_fontana_03.jpg...

  2%|▏         | 28/1137 [01:36<59:07,  3.20s/it]

Done.
Downloading 11IHEot_G0dEBKTxj7-4tw0qVnWlIOyG6 into /content/dataset/images/train/R-45489_sofiarondini_05.png...

  3%|▎         | 29/1137 [01:38<54:57,  2.98s/it]

Done.
Downloading 1ns8Z9jKhTB17vcj39cJGSTglXLjarCHY into /content/dataset/images/train/51951_pablo_pistarelli_26.png...

  3%|▎         | 30/1137 [01:43<1:05:07,  3.53s/it]

Done.
Downloading 1IuBCyWJk9SQ8FfVRs3709_vV_tPyA5b4 into /content/dataset/images/train/s56189_salvador_sanchez_59.jpg...

  3%|▎         | 31/1137 [01:46<59:26,  3.23s/it]

Done.
Downloading 1Yr2lymec42UyelC-Aw8iUlEMdLkFiZd0 into /content/dataset/images/train/52256_daniel_ponce_28.jpeg...

  3%|▎         | 32/1137 [01:48<55:49,  3.03s/it]

Done.
Downloading 1zs1HV4q4-TT3yxa_GhgEFebgV4Sc56jt into /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_21.jpg...

  3%|▎         | 33/1137 [01:51<53:03,  2.88s/it]

Done.
Downloading 1OwxyssR8YGFOxLFykRdsdEjQ_LdPiwtI into /content/dataset/images/train/s56189_salvador_sanchez_146.jpg...

  3%|▎         | 34/1137 [01:53<49:11,  2.68s/it]

Done.
Downloading 1T_RSM-WOuwMCpA_AnDWf2cCGMN8d4TjO into /content/dataset/images/train/R-45829_Abril_Rodriguez_08.png...

  3%|▎         | 35/1137 [01:56<48:52,  2.66s/it]

Done.
Downloading 1W1FEs4QnESACsHyo5mfk3EBpEr_PXYVi into /content/dataset/images/train/46094_Mateo_Rovere_18.png...

  3%|▎         | 36/1137 [02:00<57:16,  3.12s/it]

Done.
Downloading 17UHYJN5DoIetks190I3s8m9aUU6WghE_ into /content/dataset/images/train/37494_gustavo_fontana_30.jpg...

  3%|▎         | 37/1137 [02:03<59:06,  3.22s/it]

Done.
Downloading 1S2zcKMEoI0BY98RodDJHyZG7P1x8buca into /content/dataset/images/train/43237686_Constantino_Ferrucci_9.png...

  3%|▎         | 38/1137 [02:07<58:57,  3.22s/it]

Done.
Downloading 18mhCSivqtL-LM_Z_8FnISRyBjC6YPyzR into /content/dataset/images/train/43265_Lucas_Demarre_18.jpg...

  3%|▎         | 39/1137 [02:09<53:47,  2.94s/it]

Done.
Downloading 1gEHRg0zEH7fGbSnbnAsRmV_phfrjxivF into /content/dataset/images/train/d7464e01d5f7b767d61005eb2c6a0d38.png...

  4%|▎         | 40/1137 [02:12<53:39,  2.93s/it]

Done.
Downloading 1BtUQRdVrWfV5T0VE2sPsdB9T4kMwVxDT into /content/dataset/images/train/23451_guido_lorenzettibruera_06.jpg...

  4%|▎         | 41/1137 [02:16<1:01:01,  3.34s/it]

Done.
Downloading 15TcDrpUavZMZyTVuPd2cahArimUwP-nK into /content/dataset/images/train/P_51977_martin_perrone_02.png...

  4%|▎         | 42/1137 [02:19<1:00:22,  3.31s/it]

Done.
Downloading 1Z45v-AzuILioIe1sgHzblVCXA8oV_kSp into /content/dataset/images/train/S57061_Leandro_Salvana_02.png...

  4%|▍         | 43/1137 [02:22<58:27,  3.21s/it]

Done.
Downloading 1mvVdb7gHu9mqdYrI-yxOkR2TT7tBiWRY into /content/dataset/images/train/43841031_Enzo_Ferrari_36.png...

  4%|▍         | 44/1137 [02:27<1:05:12,  3.58s/it]

Done.
Downloading 1eCGvXHaEvtQK-_HgLaqHvcfYurF_o8tP into /content/dataset/images/train/43265_Lucas_Demarre_21.jpg...

  4%|▍         | 45/1137 [02:30<1:02:21,  3.43s/it]

Done.
Downloading 11VLBrmGmBCd40-hooYEmq_RsrYESL_Q- into /content/dataset/images/train/w05576_juan_wagner_10.png...

  4%|▍         | 46/1137 [02:33<58:14,  3.20s/it]

Done.
Downloading 1NfsLd9CY8ty1Gz5hAbQQa0sKSYX0wT7Z into /content/dataset/images/train/58513_isaias_garay_10.png...

  4%|▍         | 47/1137 [02:35<55:44,  3.07s/it]

Done.
Downloading 1Vo5Vg8A7omPJ5dswzxFeAvyRujV74jU5 into /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_30.jpg...

  4%|▍         | 48/1137 [02:38<54:44,  3.02s/it]

Done.
Downloading 1J-bcsOeQL8_xC24K9ArvMaTkgwr4F9lu into /content/dataset/images/train/s56189_salvador_sanchez_60.jpg...

  4%|▍         | 49/1137 [02:41<51:06,  2.82s/it]

Done.
Downloading 1Rv7axn5vMZZbcWDyD22zcyGBpSRmGAeh into /content/dataset/images/train/P_51977_martin_perrone_23.png...

  4%|▍         | 50/1137 [02:43<51:39,  2.85s/it]

Done.
Downloading 19K_kqdDr5b5-rkahAlocamzlAtGB6JBI into /content/dataset/images/train/72125_miguel_mussi_28.png...

  4%|▍         | 51/1137 [02:46<48:57,  2.70s/it]

Done.
Downloading 1M_eSf6hDgmCPQCAc304u5jphkp0uC2uf into /content/dataset/images/train/72125_miguel_mussi_20.png...

  5%|▍         | 52/1137 [02:49<49:03,  2.71s/it]

Done.
Downloading 18oRnrFSn_1r1HlYHw-5VVGHY9Yh2IDGG into /content/dataset/images/train/51659_antonio_peroni_09.jpg...

  5%|▍         | 53/1137 [02:52<50:51,  2.81s/it]

Done.
Downloading 1xGO0-gvCBnIXmhgGKztmrbc7W1W3SHTN into /content/dataset/images/train/37524_augusto_farias_18.jpg...

  5%|▍         | 54/1137 [02:55<54:54,  3.04s/it]

Done.
Downloading 1ZfpQwWSg2lNnFi6N2DOO5VRyV3BSLeQp into /content/dataset/images/train/s56189_salvador_sanchez_316.jpg...

  5%|▍         | 55/1137 [02:57<50:40,  2.81s/it]

Done.
Downloading 13gDtwnx2Uw9DDO89CIjW2rpTbmMci6Ho into /content/dataset/images/train/43841031_Enzo_Ferrari_28.png...

  5%|▍         | 56/1137 [03:02<1:01:12,  3.40s/it]

Done.
Downloading 1eN872CzahwnsYR8xAowFc_UWTDGQJB_y into /content/dataset/images/train/c894f91d437bff464f102fb0595ba4b2.png...

  5%|▌         | 57/1137 [03:05<58:26,  3.25s/it]

Done.
Downloading 1SzNkVi-o0Up8-B-XsLwyc9V6N20glQzx into /content/dataset/images/train/s56189_salvador_sanchez_205.jpg...

  5%|▌         | 58/1137 [03:07<53:28,  2.97s/it]

Done.
Downloading 1AbeKa9M0adgGoeu1HJl2PwtJgi9oWPE2 into /content/dataset/images/train/12394_escandell_ariel_06.jpg...

  5%|▌         | 59/1137 [03:11<55:00,  3.06s/it]

Done.
Downloading 14w81FjpTJc3q9IWnCTnrIjX13_ATmH5K into /content/dataset/images/train/37494_gustavo_fontana_11.jpg...

  5%|▌         | 60/1137 [03:14<57:00,  3.18s/it]

Done.
Downloading 1V4GLb7EPSzYA07XZXJN6nWKjpMwz3oiC into /content/dataset/images/train/s56189_salvador_sanchez_232.jpg...

  5%|▌         | 61/1137 [03:17<52:56,  2.95s/it]

Done.
Downloading 1DzF67-vpzznz6huCuyMhrdjqx7qGr76f into /content/dataset/images/train/51659_antonio_peroni_16.jpg...

  5%|▌         | 62/1137 [03:20<53:46,  3.00s/it]

Done.
Downloading 1tGWOhWv7wJtZuMcDlgXz0b3qajc_8GKw into /content/dataset/images/train/37494_gustavo_fontana_23.jpg...

  6%|▌         | 63/1137 [03:23<54:04,  3.02s/it]

Done.
Downloading 1DfO2OKsAeAj8fnbv3TyzzUhf0pD5gCL5 into /content/dataset/images/train/f37478_santiago_ferrero_16.jpg...

  6%|▌         | 64/1137 [03:25<51:10,  2.86s/it]

Done.
Downloading 1dNR721B5tKp9uZry5oodl1TxmgizflBi into /content/dataset/images/train/51951_pablo_pistarelli_15.png...

  6%|▌         | 65/1137 [03:29<55:15,  3.09s/it]

Done.
Downloading 1VXDono6iYTj1JicBTFNuTgw8VpcGZAfS into /content/dataset/images/train/s56189_salvador_sanchez_239.jpg...

  6%|▌         | 66/1137 [03:31<50:02,  2.80s/it]

Done.
Downloading 1cY1mFWaGljRhbVw8rgYBQ8YF7G1QJ3ov into /content/dataset/images/train/51934_pablo_pistelli_06.png...

  6%|▌         | 67/1137 [03:36<1:03:07,  3.54s/it]

Done.
Downloading 1RqV-5-TnmJRrJT9TxwhyIi_439tOctPL into /content/dataset/images/train/R-45489_sofiarondini_23.png...

  6%|▌         | 68/1137 [03:39<57:36,  3.23s/it]

Done.
Downloading 1J0a0aB3rysR30trHsStEZg1PHvVe6cmA into /content/dataset/images/train/F37605_florencia_fernandez_53.png...

  6%|▌         | 69/1137 [03:41<53:49,  3.02s/it]

Done.
Downloading 1Nxv-fNFo800L1Ofhw8uu7ORC0Rz48qKS into /content/dataset/images/train/72125_miguel_mussi_23.png...

  6%|▌         | 70/1137 [03:44<51:59,  2.92s/it]

Done.
Downloading 1_UcwfPzFVpG3Hvsn_OetS8ci_ctFAQpr into /content/dataset/images/train/g5845_gravifiorino_29.jpeg...

  6%|▌         | 71/1137 [03:46<47:56,  2.70s/it]

Done.
Downloading 1tjoMn8BLkwe9Y4gbjz3aUU44ml_zr9Io into /content/dataset/images/train/L32425_eugenio_lopez_05.png...

  6%|▋         | 72/1137 [03:49<46:11,  2.60s/it]

Done.
Downloading 1XxoNGddQOrEutxvU27gZsErApGrKKjlC into /content/dataset/images/train/s56189_salvador_sanchez_288.jpg...

  6%|▋         | 73/1137 [03:51<45:57,  2.59s/it]

Done.
Downloading 1YuaKyhevkxcbpnIAKRW6QF0PfPuX9SwK into /content/dataset/images/train/F37605_florencia_fernandez_55.png...

  7%|▋         | 74/1137 [03:54<45:54,  2.59s/it]

Done.
Downloading 1nq1PJeQnO72edoysRqUiHueo2EDl3cI8 into /content/dataset/images/train/66cf9d7f74a48caedcf01405de635c21.png...

  7%|▋         | 75/1137 [03:57<48:22,  2.73s/it]

Done.
Downloading 1YamZJ8JZgZ_BZ5NgGo4JrgTGUK4s3IH1 into /content/dataset/images/train/s56189_salvador_sanchez_297.jpg...

  7%|▋         | 76/1137 [03:59<46:20,  2.62s/it]

Done.
Downloading 1J_Z-G93Cw5WOup-gmLKYNEq0z3T7utMT into /content/dataset/images/train/s56189_salvador_sanchez_66.jpg...

  7%|▋         | 77/1137 [04:02<45:15,  2.56s/it]

Done.
Downloading 1dWCPCYRqBBJrxm_l2DCW1febcEfYRt3X into /content/dataset/images/train/L32531_santiago_loza_30.jpg...

  7%|▋         | 78/1137 [04:08<1:03:24,  3.59s/it]

Done.
Downloading 1cGh1Kq-SsJGB86Yj5A4bfp7aJRm_m8xt into /content/dataset/images/train/51659_antonio_peroni_18.jpg...

  7%|▋         | 79/1137 [04:11<1:00:23,  3.42s/it]

Done.
Downloading 162PMAPAh0YtUMF4amsKm2zFLbn9dR-2m into /content/dataset/images/train/3f3888c76dfcd3176d832be7c9d7ac23.png...

  7%|▋         | 80/1137 [04:13<57:13,  3.25s/it]

Done.
Downloading 1VbV7cMzofdJRSrJUZH-2lp5_11xTV_tx into /content/dataset/images/train/s56189_salvador_sanchez_244.jpg...

  7%|▋         | 81/1137 [04:16<51:49,  2.95s/it]

Done.
Downloading 1n0sLMPo01JsNifUHG7dVQ1JCLnK9JdeT into /content/dataset/images/train/46019_taiel_raffaeli_07.jpg...

  7%|▋         | 82/1137 [04:19<54:23,  3.09s/it]

Done.
Downloading 1_bQnPYh_Jk8BusHZaew1vnmVZH_k-wmp into /content/dataset/images/train/f37478_santiago_ferrero_24.jpg...

  7%|▋         | 83/1137 [04:22<55:39,  3.17s/it]

Done.
Downloading 1MTAftEhEb2hC1JCPU-bPz9eQwWnGIETE into /content/dataset/images/train/A45161_Fabian_Aguirre_21.png...

  7%|▋         | 84/1137 [04:25<52:33,  2.99s/it]

Done.
Downloading 1-GM8w-zBNVQ9kudg7t_C-e1-33DYWo4q into /content/dataset/images/train/R-45489_sofiarondini_33.png...

  7%|▋         | 85/1137 [04:28<51:13,  2.92s/it]

Done.
Downloading 1XbZBG4ECHzjo0d6xZb5s4kQyX6OXa553 into /content/dataset/images/train/f37478_santiago_ferrero_29.jpg...

  8%|▊         | 86/1137 [04:28<38:01,  2.17s/it]

Done.
Downloading 1KEexD_GFHjnaAi-bmYrSLr1bAbzD2lmN into /content/dataset/images/train/R-45829_Abril_Rodriguez_13.png...

  8%|▊         | 87/1137 [04:30<38:16,  2.19s/it]

Done.
Downloading 1Zy3ZoWv16OirWinDI7Cn1iUz4lVTzsMn into /content/dataset/images/train/g5845_gravifiorino_12.jpeg...

  8%|▊         | 88/1137 [04:33<38:08,  2.18s/it]

Done.
Downloading 1JZgFHURTHsG_ClXxL-wqdwxRQfQgPkUx into /content/dataset/images/train/L32531_santiago_loza_32.jpg...

  8%|▊         | 89/1137 [04:36<44:16,  2.53s/it]

Done.
Downloading 1zWBCDx9o41pvKkdRdJRRKwO45hs2vV2t into /content/dataset/images/train/43237686_Constantino_Ferrucci_36.png...

  8%|▊         | 90/1137 [04:39<48:11,  2.76s/it]

Done.
Downloading 1KVKtuUC9t7BvPa2UNWLk0MzD2pOLT6qe into /content/dataset/images/train/S57061_Leandro_Salvana_35.png...

  8%|▊         | 91/1137 [04:42<47:39,  2.73s/it]

Done.
Downloading 1xa0CVAH-B266AcWyJ0z3Ul0NVruL_5gR into /content/dataset/images/train/f37478_santiago_ferrero_39.jpg...

  8%|▊         | 92/1137 [04:44<45:48,  2.63s/it]

Done.
Downloading 1oHA-Hhd_t1lBsU2jelSKYbFpWdtR17fZ into /content/dataset/images/train/L32531_santiago_loza_17.jpg...

  8%|▊         | 93/1137 [04:47<47:12,  2.71s/it]

Done.
Downloading 1AfMHcfYlpzN1AKwz5hY6eHwSgxK-Bjzi into /content/dataset/images/train/51934_pablo_pistelli_27.png...

  8%|▊         | 94/1137 [05:18<3:11:22, 11.01s/it]

Done.
Downloading 1Xooi-HIFJ2fmh08GmOStoxUGYPVcfoUm into /content/dataset/images/train/57096_ramiro_sagrera_24.jpg...

  8%|▊         | 95/1137 [05:21<2:30:33,  8.67s/it]

Done.
Downloading 1VZa2jjelpo6FAqcyFbFqvBY9ZGq7Bv9- into /content/dataset/images/train/s56189_salvador_sanchez_238.jpg...

  8%|▊         | 96/1137 [05:23<1:58:47,  6.85s/it]

Done.
Downloading 17tzvcz4P_bLtMTJeVStswf9mdIk3hXoB into /content/dataset/images/train/57096_ramiro_sagrera_21.jpg...

  9%|▊         | 97/1137 [05:27<1:41:39,  5.87s/it]

Done.
Downloading 1D3UUU4bn_s5lnJgxvfaZ0hQtXLZj_AJN into /content/dataset/images/train/37494_gustavo_fontana_07.jpg...

  9%|▊         | 98/1137 [05:30<1:27:50,  5.07s/it]

Done.
Downloading 1aFyDpCW3XLPuFkX2KuxzLRGONKdquqqu into /content/dataset/images/train/S57061_Leandro_Salvana_32.png...

  9%|▊         | 99/1137 [05:33<1:15:12,  4.35s/it]

Done.
Downloading 1IQOnL3newgCqOKEzyS6_k_ypVie4TuiU into /content/dataset/images/train/816d6a4c1d5427d3471d5b2b727ac967.png...

  9%|▉         | 100/1137 [05:36<1:09:54,  4.04s/it]

Done.
Downloading 1UQxXQqaRdTkiOSd2fiUHixAjUjPJRZbD into /content/dataset/images/train/78c09306722441bd0c22a5902cf11e15.png...

  9%|▉         | 101/1137 [05:40<1:07:41,  3.92s/it]

Done.
Downloading 1KBYQ0_4nskhVEz1aUdb2J3LixOJHzjtl into /content/dataset/images/train/s56189_salvador_sanchez_71.jpg...

  9%|▉         | 102/1137 [05:42<59:24,  3.44s/it]

Done.
Downloading 1buJQOoAqYACM-IHer3hwiO3nZMZjgFz9 into /content/dataset/images/train/52256_daniel_ponce_29.jpeg...

  9%|▉         | 103/1137 [05:45<55:08,  3.20s/it]

Done.
Downloading 18Gew_MyFsF6o8bZtn0GY09BfH54fu71X into /content/dataset/images/train/51934_pablo_pistelli_21.png...

  9%|▉         | 104/1137 [05:50<1:08:03,  3.95s/it]

Done.
Downloading 1Sy9RRlkKG5OHPcQx9ZIuqHoiIl9zt04G into /content/dataset/images/train/s56189_salvador_sanchez_202.jpg...

  9%|▉         | 105/1137 [05:53<1:00:16,  3.50s/it]

Done.
Downloading 1bTP7J_djRADURXK2CkeTCVbUbw0II5Yw into /content/dataset/images/train/57096_ramiro_sagrera_27.jpg...

  9%|▉         | 106/1137 [05:56<57:44,  3.36s/it]

Done.
Downloading 1nhs-2d401nDzxJodQg5C_DDHMVKq02IY into /content/dataset/images/train/43237686_Constantino_Ferrucci_24.png...

  9%|▉         | 107/1137 [06:05<1:28:59,  5.18s/it]

Done.
Downloading 1lX_mlSq1OfNLFk9XkjBuXTWIquhzZd-v into /content/dataset/images/train/37494_gustavo_fontana_02.jpg...

  9%|▉         | 108/1137 [06:10<1:25:23,  4.98s/it]

Done.
Downloading 1Qn6bIc3602i0o7qQowLGuhuQSQZ8GXBi into /content/dataset/images/train/s56189_salvador_sanchez_171.jpg...

 10%|▉         | 109/1137 [06:12<1:11:27,  4.17s/it]

Done.
Downloading 1ZC_doVUuLRIKYIwhuWQh2RZyQpfqO6Fb into /content/dataset/images/train/s56189_salvador_sanchez_306.jpg...

 10%|▉         | 110/1137 [06:14<1:00:24,  3.53s/it]

Done.
Downloading 1AwoXaxJs5CZUecSd4IHHhRf8DB9zBlxF into /content/dataset/images/train/46019_taiel_raffaeli_02.jpg...

 10%|▉         | 111/1137 [06:17<57:44,  3.38s/it]

Done.
Downloading 1Bz6EElsClyIPfDjL-tnQCAraYzf8RpaW into /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_13.jpg...

 10%|▉         | 112/1137 [06:20<54:03,  3.16s/it]

Done.
Downloading 13ICkTxqDf0g1SRufvHNQsXj2GH4jjWMR into /content/dataset/images/train/43265_Lucas_Demarre_02.jpg...

 10%|▉         | 113/1137 [06:22<48:30,  2.84s/it]

Done.
Downloading 1zYWU3Idbentiv4ELjTZ-vxCPABPBt4qn into /content/dataset/images/train/58513_isaias_garay_02.png...

 10%|█         | 114/1137 [06:25<46:48,  2.75s/it]

Done.
Downloading 1JPYpfpMlt3BeK9PypeTk9kQohKqNsU0q into /content/dataset/images/train/s56189_salvador_sanchez_64.jpg...

 10%|█         | 115/1137 [06:27<43:38,  2.56s/it]

Done.
Downloading 13uXWQSp_kyTRQEyXVsMMlgmzGXN-kntP into /content/dataset/images/train/72125_miguel_mussi_18.png...

 10%|█         | 116/1137 [06:29<44:25,  2.61s/it]

Done.
Downloading 1R8Rd6Q7pIG5fx71WOmDGNsNi0Uzq4ABi into /content/dataset/images/train/R-45829_Abril_Rodriguez_02.png...

 10%|█         | 117/1137 [06:32<43:36,  2.56s/it]

Done.
Downloading 1ODfyWO6A9rwoWuYq_vg2rhsaR_9e7tkZ into /content/dataset/images/train/58912_Timoteo_Garcia_25.jpg...

 10%|█         | 118/1137 [06:35<48:58,  2.88s/it]

Done.
Downloading 1MYUxsVjJHrBb6JQfWhsR-EmGYNt64LLQ into /content/dataset/images/train/51659_antonio_peroni_07.jpg...

 10%|█         | 119/1137 [06:39<51:20,  3.03s/it]

Done.
Downloading 1RmlM3NPEpJysgzHOQOA1g2KSyhZ6M22X into /content/dataset/images/train/s56189_salvador_sanchez_186.jpg...

 11%|█         | 120/1137 [06:41<48:40,  2.87s/it]

Done.
Downloading 1ud-AKpQDeMahJEAjU8icUFn8sfM2fVm6 into /content/dataset/images/train/S57061_Leandro_Salvana_09.png...

 11%|█         | 121/1137 [06:44<46:45,  2.76s/it]

Done.
Downloading 1ftpoykSG7wMJ8vffBH3Ewuy_DinZUiYv into /content/dataset/images/train/58513_isaias_garay_06.png...

 11%|█         | 122/1137 [06:45<37:27,  2.21s/it]

Done.
Downloading 1aJhKJYuAwCuMqfIml_Ctu5_4uzWEgQaB into /content/dataset/images/train/41932688_Simon_Revello_8.png...

 11%|█         | 123/1137 [06:49<49:53,  2.95s/it]

Done.
Downloading 1mfeWvU3iIsAnqs3HJG2mzis_RqIoDt3O into /content/dataset/images/train/41932688_Simon_Revello_22.png...

 11%|█         | 124/1137 [06:54<57:51,  3.43s/it]

Done.
Downloading 171FJaCgteiOb5BPaJBlYSgEH-k9LdwIl into /content/dataset/images/train/R-45489_sofiarondini_22.png...

 11%|█         | 125/1137 [07:07<1:45:17,  6.24s/it]

Done.
Downloading 1T2zdeyOskVRmDhhPOywioV-icvvgpQXO into /content/dataset/images/train/s56189_salvador_sanchez_206.jpg...

 11%|█         | 126/1137 [07:09<1:24:39,  5.02s/it]

Done.
Downloading 1OcOxrYSycq201P4hFBacnDzWWyhl9G-7 into /content/dataset/images/train/s56189_salvador_sanchez_137.jpg...

 11%|█         | 127/1137 [07:11<1:10:20,  4.18s/it]

Done.
Downloading 17uzDqzuM5kWqxHDiXBR1fwp2QApwdDvZ into /content/dataset/images/train/43237686_Constantino_Ferrucci_12.png...

 11%|█▏        | 128/1137 [07:14<1:03:59,  3.80s/it]

Done.
Downloading 1BPevVv_5tISDzJqV75wMDvoVL_GM6arS into /content/dataset/images/train/43841031_Enzo_Ferrari_15.png...

 11%|█▏        | 129/1137 [07:18<1:06:33,  3.96s/it]

Done.
Downloading 18UkO5Y6Mnx4cX_FoidK9tIwK684w1bYw into /content/dataset/images/train/52256_daniel_ponce_19.jpeg...

 11%|█▏        | 130/1137 [07:22<1:02:18,  3.71s/it]

Done.
Downloading 11-c4mqWjkdyoU21y4YU3a94w0taCufcR into /content/dataset/images/train/s56189_salvador_sanchez_19.jpg...

 12%|█▏        | 131/1137 [07:24<55:18,  3.30s/it]

Done.
Downloading 1uLzrDyRi5tMFO2bxOAO_Ftu-aMf7jnDA into /content/dataset/images/train/43265_Lucas_Demarre_09.jpg...

 12%|█▏        | 132/1137 [07:27<52:32,  3.14s/it]

Done.
Downloading 1ZZFKSiqCxqTB6dEGAVEWgg7FzZFDhpuI into /content/dataset/images/train/s56189_salvador_sanchez_311.jpg...

 12%|█▏        | 133/1137 [07:29<47:31,  2.84s/it]

Done.
Downloading 1NNIkTyIrrKHy3QFmtOszq5iAiFHX6TYs into /content/dataset/images/train/s56189_salvador_sanchez_122.jpg...

 12%|█▏        | 134/1137 [07:31<45:01,  2.69s/it]

Done.
Downloading 1A4uqu_M6gWdbPB2APkn3zz8cO0PT1C2N into /content/dataset/images/train/03531_mirian_yanez_01.jpeg...

 12%|█▏        | 135/1137 [07:34<47:18,  2.83s/it]

Done.
Downloading 1NoynK4QCVen_cuwNnw_uvfrF1-Zoj-5h into /content/dataset/images/train/F37605_florencia_fernandez_20.png...

 12%|█▏        | 136/1137 [07:37<47:38,  2.86s/it]

Done.
Downloading 1Mr3a7Y5-vNYZtx8zEeUlwKwnjOXlfi8q into /content/dataset/images/train/37524_augusto_farias_11.jpg...

 12%|█▏        | 137/1137 [07:42<56:13,  3.37s/it]

Done.
Downloading 1C4_J8XaUPbqiYuDgo4_GMU2nIfkDvId6 into /content/dataset/images/train/51934_pablo_pistelli_26.png...

 12%|█▏        | 138/1137 [07:47<1:03:42,  3.83s/it]

Done.
Downloading 1WTa4d43sbV0NN2U89R1axKQFVlsFnhJP into /content/dataset/images/train/s56189_salvador_sanchez_261.jpg...

 12%|█▏        | 139/1137 [07:49<55:48,  3.35s/it]

Done.
Downloading 1YfMKRA2L7qtu7_7BL-owCjWkTjUHenPN into /content/dataset/images/train/s56189_salvador_sanchez_300.jpg...

 12%|█▏        | 140/1137 [07:52<53:39,  3.23s/it]

Done.
Downloading 1Ust6MQPYSfSi6vkF8GFqg9e8jSBe6ytl into /content/dataset/images/train/s56189_salvador_sanchez_231.jpg...

 12%|█▏        | 141/1137 [07:55<52:34,  3.17s/it]

Done.
Downloading 1LsAfh_xetER4uN2Vwb1lmfFSD8ltlA4d into /content/dataset/images/train/s56189_salvador_sanchez_99.jpg...

 12%|█▏        | 142/1137 [07:57<47:42,  2.88s/it]

Done.
Downloading 1YGqZi5Luz-EWVdqeW7Dl8xUHrHxfkOpr into /content/dataset/images/train/s56189_salvador_sanchez_289.jpg...

 13%|█▎        | 143/1137 [07:59<44:26,  2.68s/it]

Done.
Downloading 1eczWk53rL5Sqk8EYBBCvLSKpqduAHE0N into /content/dataset/images/train/03531_mirian_yanez_28.jpeg...

 13%|█▎        | 144/1137 [08:02<44:50,  2.71s/it]

Done.
Downloading 1cCDp4saCf6YDLgyOTr0sdHJGeVF8QTz- into /content/dataset/images/train/58491_fabio_giampaoli_21.png...

 13%|█▎        | 145/1137 [08:08<1:01:29,  3.72s/it]

Done.
Downloading 1PDcihTtLBwOvVZ8qVAq-X0PUjLvohYgy into /content/dataset/images/train/R-45829_Abril_Rodriguez_16.png...

 13%|█▎        | 146/1137 [08:11<55:24,  3.35s/it]

Done.
Downloading 1MlQ7DqvAwrTHHH_qO5zMygksJuTg_J-7 into /content/dataset/images/train/R-45829_Abril_Rodriguez_25.png...

 13%|█▎        | 147/1137 [08:13<51:28,  3.12s/it]

Done.
Downloading 19_8isBASRzWqqs9ksDCfnY8F7is21SiD into /content/dataset/images/train/46094_Mateo_Rovere_20.png...

 13%|█▎        | 148/1137 [08:16<50:12,  3.05s/it]

Done.
Downloading 1THYUyT7CQMLY554HMOiOa_nI55lwajWP into /content/dataset/images/train/s56189_salvador_sanchez_208.jpg...

 13%|█▎        | 149/1137 [08:19<47:28,  2.88s/it]

Done.
Downloading 19IrmKwX-2gfpFlHd_qySvEC1Spn3wOwK into /content/dataset/images/train/R-45829_Abril_Rodriguez_26.png...

 13%|█▎        | 150/1137 [08:21<45:56,  2.79s/it]

Done.
Downloading 1gN91vwxqsxtNrz45H5mtP7qWK004YQcq into /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_01.jpg...

 13%|█▎        | 151/1137 [08:24<44:20,  2.70s/it]

Done.
Downloading 1uwzh3rhuxPTqlDXu-uakP4uK-ZlfJFWa into /content/dataset/images/train/51659_antonio_peroni_05.jpg...

 13%|█▎        | 152/1137 [08:27<46:22,  2.83s/it]

Done.
Downloading 1o1xMIOv8TetcpPawL2oX5ewnmjHA96NZ into /content/dataset/images/train/43237686_Constantino_Ferrucci_33.png...

 13%|█▎        | 153/1137 [08:30<48:36,  2.96s/it]

Done.
Downloading 145f1vfleWsl7-PqmJEfPeQh-rsYB_iGQ into /content/dataset/images/train/gravifiorino_5.jpeg...

 14%|█▎        | 154/1137 [08:32<44:20,  2.71s/it]

Done.
Downloading 108e13IPazBDs3EoHB2XoXNB8Jy71HLPi into /content/dataset/images/train/72125_miguel_mussi_12.png...

 14%|█▎        | 155/1137 [08:35<43:59,  2.69s/it]

Done.
Downloading 1R9htUgCKQIGk5k4VOl6WPgYKvR-Inxnx into /content/dataset/images/train/s56189_salvador_sanchez_176.jpg...

 14%|█▎        | 156/1137 [08:37<42:17,  2.59s/it]

Done.
Downloading 1JpKDHvJsfDEreNTzyOaGLRdB_nc-BecT into /content/dataset/images/train/43841031_Enzo_Ferrari_25.png...

 14%|█▍        | 157/1137 [08:40<43:38,  2.67s/it]

Done.
Downloading 11P_Hq-uQ5MhtPsgFWVqE2zSMTxrZK-cA into /content/dataset/images/train/s56189_salvador_sanchez_21.jpg...

 14%|█▍        | 158/1137 [08:42<41:13,  2.53s/it]

Done.
Downloading 1kUH0osy2_peRfk-te7jvIvLAUGvq6bJM into /content/dataset/images/train/R-45829_Abril_Rodriguez_22.png...

 14%|█▍        | 159/1137 [08:45<42:52,  2.63s/it]

Done.
Downloading 1fKo4wWtxiYOHDCBOEb9F3N98iHIW-obx into /content/dataset/images/train/52256_daniel_ponce_24.jpeg...

 14%|█▍        | 160/1137 [08:48<43:38,  2.68s/it]

Done.
Downloading 1lXqLl8tkam1sRPF5c3DSmWO0iNriU3cm into /content/dataset/images/train/s56804_alexis_segui_25.png...

 14%|█▍        | 161/1137 [08:51<44:20,  2.73s/it]

Done.
Downloading 1HPnEXlnF288kNd5iWiFnbTQY2jy0C5sm into /content/dataset/images/train/46094_Mateo_Rovere_32.png...

 14%|█▍        | 162/1137 [08:54<44:31,  2.74s/it]

Done.
Downloading 1QjjyAZIZ5uszxNZyCUjN1F8PsVpwQAuK into /content/dataset/images/train/57096_ramiro_sagrera_30.jpg...

 14%|█▍        | 163/1137 [08:57<47:40,  2.94s/it]

Done.
Downloading 1wnNR5s451q2lqH8dx-xnAZWliNv1SGF7 into /content/dataset/images/train/12394_escandell_ariel_22.jpg...

 14%|█▍        | 164/1137 [09:00<47:17,  2.92s/it]

Done.
Downloading 14Thw6cuvc8dIx7WzNjQavfdDf3VzMcYz into /content/dataset/images/train/43237686_Constantino_Ferrucci_4.png...

 15%|█▍        | 165/1137 [09:03<47:48,  2.95s/it]

Done.
Downloading 1PN9b1FqkOJdPexT8tscTihqvzIT2XVxW into /content/dataset/images/train/s56189_salvador_sanchez_147.jpg...

 15%|█▍        | 166/1137 [09:05<45:03,  2.78s/it]

Done.
Downloading 19IpzAF25ZoJecMuWXORKp7TzLHRkLrgX into /content/dataset/images/train/R-45489_sofiarondini_31.png...

 15%|█▍        | 167/1137 [09:08<43:07,  2.67s/it]

Done.
Downloading 1XCTYFki6fF6ojbcOU_860kP46iyWFu2c into /content/dataset/images/train/s56189_salvador_sanchez_278.jpg...

 15%|█▍        | 168/1137 [09:10<41:56,  2.60s/it]

Done.
Downloading 1sCtSozhRoQDxD9bBhbmO5lTvDf2y75cS into /content/dataset/images/train/51951_pablo_pistarelli_22.png...

 15%|█▍        | 169/1137 [09:14<47:24,  2.94s/it]

Done.
Downloading 1tnSe6r4ng7omrqV8zOzcc6VVYhKxe-ND into /content/dataset/images/train/A45161_Fabian_Aguirre_07.png...

 15%|█▍        | 170/1137 [09:17<46:31,  2.89s/it]

Done.
Downloading 1z_ADynMS9Gc4CtSPMteLlymhTfmV_fTG into /content/dataset/images/train/46019_taiel_raffaeli_14.jpg...

 15%|█▌        | 171/1137 [09:20<47:04,  2.92s/it]

Done.
Downloading 1q0PRYpwTyNosk21ywEy-2ZNY1HESYo4i into /content/dataset/images/train/ab57adc6fb75c7cefd3b386b1b703166.png...

 15%|█▌        | 172/1137 [09:23<47:51,  2.98s/it]

Done.
Downloading 13Q3JxBINK2ofE1WoiRTY3kDrUMex5qyX into /content/dataset/images/train/A45161_Fabian_Aguirre_23.png...

 15%|█▌        | 173/1137 [09:26<47:56,  2.98s/it]

Done.
Downloading 1u6-GYQ7HeqMX_epm8Wap9xFYu6G8ykVv into /content/dataset/images/train/844bff0deb2a58dd453977f55b4d9d14.png...

 15%|█▌        | 174/1137 [09:29<47:27,  2.96s/it]

Done.
Downloading 10rAs_pjnSemkW8EHmHoyMvAKCTefYHVh into /content/dataset/images/train/51951_pablo_pistarelli_16.png...

 15%|█▌        | 175/1137 [09:33<52:05,  3.25s/it]

Done.
Downloading 1Wit5Ma_2RFj_lN3CEnobmw9EcGGH7eHa into /content/dataset/images/train/s56189_salvador_sanchez_270.jpg...

 15%|█▌        | 176/1137 [09:35<47:23,  2.96s/it]

Done.
Downloading 125GXHYUS-Q2UBsb-r7AjoDX-NMnflp_S into /content/dataset/images/train/g5845_gravifiorino_10.jpeg...

 16%|█▌        | 177/1137 [09:37<43:58,  2.75s/it]

Done.
Downloading 1XbO05JX-oi4pvSjLrn2yZhTMpiVTVgvu into /content/dataset/images/train/s56189_salvador_sanchez_280.jpg...

 16%|█▌        | 178/1137 [09:39<41:02,  2.57s/it]

Done.
Downloading 1l6JWoizHF9dNhNXMRsRQIasfuJuQYUeU into /content/dataset/images/train/S57061_Leandro_Salvana_20.png...

 16%|█▌        | 179/1137 [09:42<43:43,  2.74s/it]

Done.
Downloading 1JLl-ned5p9E_e9mPD2lf4OoLW7mlGGsq into /content/dataset/images/train/46019_taiel_raffaeli_08.jpg...

 16%|█▌        | 180/1137 [09:45<44:44,  2.81s/it]

Done.
Downloading 1pPJtF1n2ScZ5MwR75Kknmxj7vkmPi_ru into /content/dataset/images/train/41932688_Simon_Revello_23.png...

 16%|█▌        | 181/1137 [09:50<51:30,  3.23s/it]

Done.
Downloading 1WQRIfWuVBBf7bZdq_-T41sRkUxJOybTa into /content/dataset/images/train/s56189_salvador_sanchez_259.jpg...

 16%|█▌        | 182/1137 [09:52<47:34,  2.99s/it]

Done.
Downloading 1TBRRWMXIRgz_WL5L7thZrtvSJL4D7VGE into /content/dataset/images/train/F37605_florencia_fernandez_06.png...

 16%|█▌        | 183/1137 [09:55<45:35,  2.87s/it]

Done.
Downloading 1Xo2Ua_u0Q17iealXkgnXWnj_uUWP6stt into /content/dataset/images/train/s56189_salvador_sanchez_284.jpg...

 16%|█▌        | 184/1137 [09:57<42:27,  2.67s/it]

Done.
Downloading 12LWf0oAtURQNX1ZmKhpIiszwfXjK7h-k into /content/dataset/images/train/46094_Mateo_Rovere_26.png...

 16%|█▋        | 185/1137 [09:59<40:39,  2.56s/it]

Done.
Downloading 15kU72AJwsRN0qi7ugsP2VRCYRXsUxwSI into /content/dataset/images/train/bc6f1ca08f613418bb0cd9393bf85c1b.png...

 16%|█▋        | 186/1137 [10:02<44:42,  2.82s/it]

Done.
Downloading 1qom6_ApO246_fFJajLRyzoPBvbroLdkV into /content/dataset/images/train/51705_micaela_pozzo_06.png...

 16%|█▋        | 187/1137 [10:06<48:40,  3.07s/it]

Done.
Downloading 1QNj5Gylo1ZPCS96KTxnmTuZxEDly3gv3 into /content/dataset/images/train/S57061_Leandro_Salvana_46.png...

 17%|█▋        | 188/1137 [10:09<46:32,  2.94s/it]

Done.
Downloading 1YfREa91InPDtKbwTpucKH0SE2nJhcACJ into /content/dataset/images/train/58491_fabio_giampaoli_23.png...

 17%|█▋        | 189/1137 [10:13<51:48,  3.28s/it]

Done.
Downloading 1YE-socrd_oIqVW6R_Uaj6HDUUQ5dtmVc into /content/dataset/images/train/s56189_salvador_sanchez_290.jpg...

 17%|█▋        | 190/1137 [10:15<47:21,  3.00s/it]

Done.
Downloading 1ex0KiDOIvkFe3GdWxthSbhzeTx8rtFdk into /content/dataset/images/train/51951_pablo_pistarelli_21.png...

 17%|█▋        | 191/1137 [10:19<53:11,  3.37s/it]

Done.
Downloading 1NkOLwZHJpNP7dt_SbKwXXhZbiFjlO2sm into /content/dataset/images/train/46019_taiel_raffaeli_15.jpg...

 17%|█▋        | 192/1137 [10:22<51:06,  3.25s/it]

Done.
Downloading 1lQLTB3G9rQx4y3i5TitITQReeAieBmj_ into /content/dataset/images/train/g5845_gravifiorino_4.jpeg...

 17%|█▋        | 193/1137 [10:25<46:10,  2.93s/it]

Done.
Downloading 126RtuixBsAQuZhaOsaks18gxTBFyBH8y into /content/dataset/images/train/s56189_salvador_sanchez_28.jpg...

 17%|█▋        | 194/1137 [10:27<43:09,  2.75s/it]

Done.
Downloading 1xc_nkmQ30XR1awJPU3au3QVv3JkbUvh9 into /content/dataset/images/train/57096_ramiro_sagrera_16.jpg...

 17%|█▋        | 195/1137 [10:31<48:47,  3.11s/it]

Done.
Downloading 1QAVOi2fSUACAQbsubYJUACsdtt9Gy_bi into /content/dataset/images/train/51951_pablo_pistarelli_23.png...

 17%|█▋        | 196/1137 [10:35<52:10,  3.33s/it]

Done.
Downloading 1V6pT5YTH3ENBd3DG5wmlACzgoiL2_UK2 into /content/dataset/images/train/s56189_salvador_sanchez_235.jpg...

 17%|█▋        | 197/1137 [10:37<47:31,  3.03s/it]

Done.
Downloading 1EgpbhdVtvQwa9iyvR6bTlWZmUN9_yg-9 into /content/dataset/images/train/58912_Timoteo_Garcia_29.jpg...

 17%|█▋        | 198/1137 [10:41<50:58,  3.26s/it]

Done.
Downloading 1Z6GA2dPYt1ohvRumWFmqRJzdsAMbfEOJ into /content/dataset/images/train/s56189_salvador_sanchez_303.jpg...

 18%|█▊        | 199/1137 [10:43<46:05,  2.95s/it]

Done.
Downloading 1vDHhkRjtB9r3wPfe3WAdVeCFnGOY7h2K into /content/dataset/images/train/57096_ramiro_sagrera_04.jpg...

 18%|█▊        | 200/1137 [10:47<49:39,  3.18s/it]

Done.
Downloading 1ZFf8CygcpsxbkAdNfsuaC4zPrV3iPGpr into /content/dataset/images/train/s56189_salvador_sanchez_310.jpg...

 18%|█▊        | 201/1137 [10:49<45:28,  2.91s/it]

Done.
Downloading 1XykmDU-50-bY3_aeWobX4bEFvjtOgJ43 into /content/dataset/images/train/12394_escandell_ariel_05.jpg...

 18%|█▊        | 202/1137 [10:52<45:48,  2.94s/it]

Done.
Downloading 1hBb9xU-ZA2H4D89BT0FxAdp3o7_7ULam into /content/dataset/images/train/f37478_santiago_ferrero_04.jpg...

 18%|█▊        | 203/1137 [10:56<48:10,  3.09s/it]

Done.
Downloading 1XkpLVIQsl-Sl2D15t8TBVWDp4TwAyltV into /content/dataset/images/train/P_51977_martin_perrone_08.png...

 18%|█▊        | 204/1137 [10:59<49:42,  3.20s/it]

Done.
Downloading 1Ty_MPJdAxBz5qsbxiFyOhG2cOt0p12i7 into /content/dataset/images/train/s56189_salvador_sanchez_218.jpg...

 18%|█▊        | 205/1137 [11:02<47:09,  3.04s/it]

Done.
Downloading 1r5I4g2lWgtcGN268eRE4lMV0ipnJIAPz into /content/dataset/images/train/58513_isaias_garay_26.png...

 18%|█▊        | 206/1137 [11:04<43:43,  2.82s/it]

Done.
Downloading 12DQqtWLwHdkXCcIoSS2n0XBRjtJV47dq into /content/dataset/images/train/f37478_santiago_ferrero_03.jpg...

 18%|█▊        | 207/1137 [11:07<44:03,  2.84s/it]

Done.
Downloading 1aOC2B9MYBoNXGHzm6REH5D0vmjD-zkW1 into /content/dataset/images/train/A45161_Fabian_Aguirre_08.png...

 18%|█▊        | 208/1137 [11:09<42:45,  2.76s/it]

Done.
Downloading 14oMbIdHRvnbAOQeZMAuQ36InHeKKxeZF into /content/dataset/images/train/37494_gustavo_fontana_14.jpg...

 18%|█▊        | 209/1137 [11:12<44:03,  2.85s/it]

Done.
Downloading 1C1WFk0HZWr1KxBZvqpz2Bw3DI2MhwCAL into /content/dataset/images/train/51934_pablo_pistelli_16.png...

 18%|█▊        | 210/1137 [11:18<54:22,  3.52s/it]

Done.
Downloading 1yNsA-OJE6Hkp67ugHTBbBwNP_RdsKj7r into /content/dataset/images/train/L32531_santiago_loza_23.jpg...

 19%|█▊        | 211/1137 [11:20<51:04,  3.31s/it]

Done.
Downloading 1Z4JVRlqkqaH1FNZmBcddHIilCpB5GPjU into /content/dataset/images/train/L32425_eugenio_lopez_11.png...

 19%|█▊        | 212/1137 [11:24<50:59,  3.31s/it]

Done.
Downloading 1z94hT09nZw3GmdXZkXA7NivLJ5BeJwgO into /content/dataset/images/train/w05576_juan_wagner_19.png...

 19%|█▊        | 213/1137 [11:27<49:10,  3.19s/it]

Done.
Downloading 1OC-u6rwooDybq8qTNwb-MGOiTywPiYow into /content/dataset/images/train/R-45489_sofiarondini_28.png...

 19%|█▉        | 214/1137 [11:29<45:36,  2.97s/it]

Done.
Downloading 1uGYtl10yjIKaf6ElBk11PG980Vey4vJC into /content/dataset/images/train/52256_daniel_ponce_21.jpeg...

 19%|█▉        | 215/1137 [11:31<42:49,  2.79s/it]

Done.
Downloading 1-7yKO6WQhideCrpO5jDBJaxeAoe7cRhL into /content/dataset/images/train/s56189_salvador_sanchez_9.jpg...

 19%|█▉        | 216/1137 [11:34<41:25,  2.70s/it]

Done.
Downloading 1PgU-yaIHHCOJRkJJLiPDDZMan1RWnC62 into /content/dataset/images/train/58491_fabio_giampaoli_01.png...

 19%|█▉        | 217/1137 [11:42<1:04:39,  4.22s/it]

Done.
Downloading 1-No6EnJC5MAgG8evRzMMBoPlreYO035V into /content/dataset/images/train/5abbaad8b56fb4af772ee8e457175c09.png...

 19%|█▉        | 218/1137 [11:45<58:22,  3.81s/it]

Done.
Downloading 1e03dGipqdno2vmLPqhEOMn3OuHpthaW3 into /content/dataset/images/train/46019_taiel_raffaeli_06.jpg...

 19%|█▉        | 219/1137 [11:47<53:40,  3.51s/it]

Done.
Downloading 1KgeVcxo5ZTpkFab8z6ttuyqRonlVZuhs into /content/dataset/images/train/w05576_juan_wagner_15.png...

 19%|█▉        | 220/1137 [11:50<48:12,  3.15s/it]

Done.
Downloading 1o0Ljj5GcF8Jp4Ol7tTQ1SZqqG25zdXOC into /content/dataset/images/train/L32425_eugenio_lopez_14.png...

 19%|█▉        | 221/1137 [11:52<46:37,  3.05s/it]

Done.
Downloading 1XDo2zeAqJPkq-l8OkQMnNTqHxjXrjpDz into /content/dataset/images/train/s56189_salvador_sanchez_277.jpg...

 20%|█▉        | 222/1137 [11:55<42:49,  2.81s/it]

Done.
Downloading 1YA1dToCdvatuW5hJ6RfRffOaG2Vmvuco into /content/dataset/images/train/s56189_salvador_sanchez_292.jpg...

 20%|█▉        | 223/1137 [11:57<40:45,  2.68s/it]

Done.
Downloading 1iH0Y-DwdfrwAl43Y5qIBSSUeZRSQWpZP into /content/dataset/images/train/58491_fabio_giampaoli_30.png...

 20%|█▉        | 224/1137 [12:03<56:44,  3.73s/it]

Done.
Downloading 1YtfBkamqMyZpS69C_i5dh4IBTaFiW1Zx into /content/dataset/images/train/43237686_Constantino_Ferrucci_5.png...

 20%|█▉        | 225/1137 [12:07<55:01,  3.62s/it]

Done.
Downloading 1BIwzmXXo8ocPuFbaXnXDHZWpXGkRK__J into /content/dataset/images/train/03531_mirian_yanez_11.jpeg...

 20%|█▉        | 226/1137 [12:09<49:56,  3.29s/it]

Done.
Downloading 1f4VS3zsdwQwrMtNftzaa8YwEHfR-m-wR into /content/dataset/images/train/41932688_Simon_Revello_0.png...

 20%|█▉        | 227/1137 [12:13<52:56,  3.49s/it]

Done.
Downloading 1Y_IkBHu8jALFuQh_RDillkgtHfSdOhu1 into /content/dataset/images/train/s56189_salvador_sanchez_298.jpg...

 20%|██        | 228/1137 [12:15<47:57,  3.17s/it]

Done.
Downloading 1-70Nt4RQa5yEhfdMYEkwDOZV3ELvrtvV into /content/dataset/images/train/S57061_Leandro_Salvana_15.png...

 20%|██        | 229/1137 [12:18<44:11,  2.92s/it]

Done.
Downloading 1-26Tj1hp2HjMmCDuwbT5tTox90GkNKob into /content/dataset/images/train/46094_Mateo_Rovere_12.png...

 20%|██        | 230/1137 [12:21<45:06,  2.98s/it]

Done.
Downloading 1CfCmhP9lyNeRVHFz57Q65mMA6QYZEK3S into /content/dataset/images/train/R-45829_Abril_Rodriguez_30.png...

 20%|██        | 231/1137 [12:24<43:22,  2.87s/it]

Done.
Downloading 1F0uc-mtSSb5RO_BDAcBmSdPhDqUYdId7 into /content/dataset/images/train/L32531_santiago_loza_2.jpg...

 20%|██        | 232/1137 [12:27<45:00,  2.98s/it]

Done.
Downloading 1HR4oLCejhIVQjYkQADSDtdRL-PCBJEA- into /content/dataset/images/train/12394_escandell_ariel_27.jpg...

 20%|██        | 233/1137 [12:30<44:19,  2.94s/it]

Done.
Downloading 1ZCinwHZbPEdDvR1XDGKq9Q2hXZMmCNpn into /content/dataset/images/train/03531_mirian_yanez_26.jpeg...

 21%|██        | 234/1137 [12:32<41:35,  2.76s/it]

Done.
Downloading 1ojDGHamAAx74hobvptGlqgGIW0V87JaK into /content/dataset/images/train/f37478_santiago_ferrero_28.jpg...

 21%|██        | 235/1137 [12:35<40:44,  2.71s/it]

Done.
Downloading 1a4x57M4rR72XlgH-tiXD-jiPXMG7V6bH into /content/dataset/images/train/51659_antonio_peroni_22.jpg...

 21%|██        | 236/1137 [12:37<41:05,  2.74s/it]

Done.
Downloading 1SGqqZN__n3EvuZOUhzjAOZRAvWMOy-sg into /content/dataset/images/train/s56189_salvador_sanchez_195.jpg...

 21%|██        | 237/1137 [12:40<39:05,  2.61s/it]

Done.
Downloading 1A4gupSroHTKkdug-dRIz7ToaumlKyVS3 into /content/dataset/images/train/R-45489_sofiarondini_10.png...

 21%|██        | 238/1137 [12:42<38:03,  2.54s/it]

Done.
Downloading 1COevH-8-nKgnYohdku3RDE7mJlWvxwtX into /content/dataset/images/train/R-45489_sofiarondini_04.png...

 21%|██        | 239/1137 [12:45<37:53,  2.53s/it]

Done.
Downloading 1QUZUJd5JWTWaWfgJ_SAE9sgyMPJkbbKO into /content/dataset/images/train/P_51977_martin_perrone_03.png...

 21%|██        | 240/1137 [12:48<41:33,  2.78s/it]

Done.
Downloading 1oMPN6vG7aR627GWHmLVarQdXUJjomHR_ into /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_11.jpg...

 21%|██        | 241/1137 [12:51<41:47,  2.80s/it]

Done.
Downloading 14Lt8ZWUC7CtzLX5n9EwdmYejYf8Yqovl into /content/dataset/images/train/37494_gustavo_fontana_29.jpg...

 21%|██▏       | 242/1137 [12:54<43:04,  2.89s/it]

Done.
Downloading 1yStDdt3vz7uD-v2pFAoNSBeDIq4TptWY into /content/dataset/images/train/58912_Timoteo_Garcia_12.jpg...

 21%|██▏       | 243/1137 [12:57<44:44,  3.00s/it]

Done.
Downloading 1WchkNCLc4yonHZx2NCuVW6tWxY5gfc__ into /content/dataset/images/train/A45161_Fabian_Aguirre_31.png...

 21%|██▏       | 244/1137 [13:00<43:22,  2.91s/it]

Done.
Downloading 12hA5pQzE-IISNiblBR-MD4gJmWXFA4w6 into /content/dataset/images/train/P_51977_martin_perrone_32.png...

 22%|██▏       | 245/1137 [13:03<46:07,  3.10s/it]

Done.
Downloading 1WSU-yvU8Rkrv4nee5bPz-YAXlZoEd4sl into /content/dataset/images/train/S57061_Leandro_Salvana_30.png...

 22%|██▏       | 246/1137 [13:07<46:40,  3.14s/it]

Done.
Downloading 1FequrroBcczpblJoZo7ZWg3-9QJY3Yvv into /content/dataset/images/train/L32425_eugenio_lopez_17.png...

 22%|██▏       | 247/1137 [13:10<49:01,  3.31s/it]

Done.
Downloading 1E5aCWyaq8zA_HIuERRPMtKP2AdYte5pM into /content/dataset/images/train/P51926_Leonel_Palermo_29.png...

 22%|██▏       | 248/1137 [13:16<1:00:58,  4.12s/it]

Done.
Downloading 11Qudh6hdJRUcgUgK9nOcSv1fAcZA0ZNJ into /content/dataset/images/train/s56189_salvador_sanchez_20.jpg...

 22%|██▏       | 249/1137 [13:19<53:02,  3.58s/it]

Done.
Downloading 1M5xvW3jr6shgwwJdgdEYlBLY-DWCiqMd into /content/dataset/images/train/L32531_santiago_loza_42.jpg...

 22%|██▏       | 250/1137 [13:21<49:21,  3.34s/it]

Done.
Downloading 1Zj2PePX9REEGLHrjopd5T4wubzzjguAf into /content/dataset/images/train/L32531_santiago_loza_33.jpg...

 22%|██▏       | 251/1137 [13:24<47:26,  3.21s/it]

Done.
Downloading 1oa2lhLuRk07eclbElCyh2okiDc5B1O8L into /content/dataset/images/train/43841031_Enzo_Ferrari_06.png...

 22%|██▏       | 252/1137 [13:28<51:02,  3.46s/it]

Done.
Downloading 1S4vHvP7KIhhcUMYwzFELHXQ03E75AbPA into /content/dataset/images/train/A45161_Fabian_Aguirre_12.png...

 22%|██▏       | 253/1137 [13:31<46:20,  3.14s/it]

Done.
Downloading 1cPnWTVVONXWCj_PWp3qMOfyUIeW9jUMb into /content/dataset/images/train/51659_antonio_peroni_23.jpg...

 22%|██▏       | 254/1137 [13:34<44:35,  3.03s/it]

Done.
Downloading 1V7wlTqDrApSrcJ2gL5isqJNwzf79s7aU into /content/dataset/images/train/517424daa31aef6c50af72ceff7b3b92.png...

 22%|██▏       | 255/1137 [13:36<42:37,  2.90s/it]

Done.
Downloading 17Lmhc2qQbDqYvz_M08O7DWw3Y6DrrXwC into /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_14.jpg...

 23%|██▎       | 256/1137 [13:39<42:03,  2.86s/it]

Done.
Downloading 1W5rWcmYcNQFQ9xalxjowugaQbxIAEET_ into /content/dataset/images/train/L32531_santiago_loza_1.jpg...

 23%|██▎       | 257/1137 [13:43<45:45,  3.12s/it]

Done.
Downloading 1WJLQIUuP-AxU6dOWPANeWwAQVyGJDlKq into /content/dataset/images/train/s56189_salvador_sanchez_256.jpg...

 23%|██▎       | 258/1137 [13:45<42:03,  2.87s/it]

Done.
Downloading 1RP1JZx81zb8bDHao9Wpcopu0sPuUv4W6 into /content/dataset/images/train/58912_Timoteo_Garcia_11.jpg...

 23%|██▎       | 259/1137 [13:48<43:23,  2.96s/it]

Done.
Downloading 1JAf1SjkRtqywK-A2jgAtRD_BCrkX_y9x into /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_12.jpg...

 23%|██▎       | 260/1137 [13:51<44:36,  3.05s/it]

Done.
Downloading 1GBiFVuTrV_LrqrQ9cHog0YMXvSGScBPZ into /content/dataset/images/train/277a4b435b871683e37e45daca19c4f6.png...

 23%|██▎       | 261/1137 [13:54<42:25,  2.91s/it]

Done.
Downloading 1y6VMb_5TJL80p96u3qYB2tHtbTronNfT into /content/dataset/images/train/51659_antonio_peroni_06.jpg...

 23%|██▎       | 262/1137 [13:57<42:04,  2.88s/it]

Done.
Downloading 1MlMBYwlMhrEdkz8sYS6qqEpY5EfRjlhq into /content/dataset/images/train/s56189_salvador_sanchez_116.jpg...

 23%|██▎       | 263/1137 [13:59<39:51,  2.74s/it]

Done.
Downloading 1FHweMEmCkRpBNvQMZW4ml8jjXQBDz8M1 into /content/dataset/images/train/43841031_Enzo_Ferrari_18.png...

 23%|██▎       | 264/1137 [14:04<50:53,  3.50s/it]

Done.
Downloading 1gad4mtnlVE_UB4O6sHjt21wz6uMEMV67 into /content/dataset/images/train/L32531_santiago_loza_46.jpg...

 23%|██▎       | 265/1137 [14:08<49:22,  3.40s/it]

Done.
Downloading 1y8_xER6mQ5Mcf0f0glpjO6dSpKVhpnrR into /content/dataset/images/train/R-45489_sofiarondini_03.png...

 23%|██▎       | 266/1137 [14:10<45:06,  3.11s/it]

Done.
Downloading 1bOfD9fqmF6uAI63p2wXiuG_-VXsQKaMe into /content/dataset/images/train/R-45829_Abril_Rodriguez_05.png...

 23%|██▎       | 267/1137 [14:12<41:58,  2.90s/it]

Done.
Downloading 1Gk-jYmq5sG5QV5EbfGR_z0P9rfU-yH0f into /content/dataset/images/train/S57061_Leandro_Salvana_25.png...

 24%|██▎       | 268/1137 [14:15<40:27,  2.79s/it]

Done.
Downloading 1_FHqHbEYb9ieYabID_Sqcc3SIlkiZSu- into /content/dataset/images/train/23451_guido_lorenzettibruera_14.jpg...

 24%|██▎       | 269/1137 [14:20<50:43,  3.51s/it]

Done.
Downloading 1SbFDd87bx1M8YUJ6_P5dXo3M_d-imDow into /content/dataset/images/train/R-45489_sofiarondini_13.png...

 24%|██▎       | 270/1137 [14:23<45:58,  3.18s/it]

Done.
Downloading 1WrhPODJOrLL8SsLX_8YhesL3qgSzgl91 into /content/dataset/images/train/s56189_salvador_sanchez_271.jpg...

 24%|██▍       | 271/1137 [14:25<41:28,  2.87s/it]

Done.
Downloading 1MTgM3p314_Vqgk4H5accIm4quYAqhCxp into /content/dataset/images/train/s56189_salvador_sanchez_110.jpg...

 24%|██▍       | 272/1137 [14:27<38:32,  2.67s/it]

Done.
Downloading 1-ZUbUyzkq_NM7LVDhVT-nayrB1wbDsvh into /content/dataset/images/train/57096_ramiro_sagrera_18.jpg...

 24%|██▍       | 273/1137 [14:30<42:01,  2.92s/it]

Done.
Downloading 13rFN65YoYDxNPe620G4Uy_RUref0uxJ8 into /content/dataset/images/train/S57061_Leandro_Salvana_36.png...

 24%|██▍       | 274/1137 [14:33<40:18,  2.80s/it]

Done.
Downloading 1CL-QDVDrMl1QthOJ2HdWahNyFMCRTc0R into /content/dataset/images/train/s56804_alexis_segui_29.png...

 24%|██▍       | 275/1137 [14:36<39:23,  2.74s/it]

Done.
Downloading 1dOt4rwsEERIWg4VryiXu9CvoVTmIzyYi into /content/dataset/images/train/P_51977_martin_perrone_09.png...

 24%|██▍       | 276/1137 [14:39<41:49,  2.91s/it]

Done.
Downloading 1KNZ4WCtcva2BJsNurUKbC-CllBuWbUzJ into /content/dataset/images/train/w05576_juan_wagner_32.png...

 24%|██▍       | 277/1137 [14:41<39:14,  2.74s/it]

Done.
Downloading 1pvwWCiVvJTE6JAL1fyTpO5If2-JwjwF9 into /content/dataset/images/train/L32425_eugenio_lopez_03.png...

 24%|██▍       | 278/1137 [14:45<43:54,  3.07s/it]

Done.
Downloading 1QasGDJ24qKSLRqaHC9Hd-qucAlN-Bgxi into /content/dataset/images/train/s56189_salvador_sanchez_164.jpg...

 25%|██▍       | 279/1137 [14:47<39:48,  2.78s/it]

Done.
Downloading 105W21aaXvCf3UwIbFQ1fjKTDEkAJAcXf into /content/dataset/images/train/71846_Brisa_Menescaldi_08.png...

 25%|██▍       | 280/1137 [14:52<50:16,  3.52s/it]

Done.
Downloading 10y2BQxI_lczPN7VcTKJMDFPRmiCzyOvH into /content/dataset/images/train/s56189_salvador_sanchez_18.jpg...

 25%|██▍       | 281/1137 [14:55<45:13,  3.17s/it]

Done.
Downloading 1pAVVFCdVmnx5n3zx71aAJGzbmgsplg0X into /content/dataset/images/train/12394_escandell_ariel_08.jpg...

 25%|██▍       | 282/1137 [14:58<44:51,  3.15s/it]

Done.
Downloading 1_pxdavp_TyCe-j7EL1fCXwpUPeUOHcTk into /content/dataset/images/train/51934_pablo_pistelli_29.png...

 25%|██▍       | 283/1137 [15:02<49:41,  3.49s/it]

Done.
Downloading 1ii1dZaPF1YenfKttlIik57sFTZEvol8- into /content/dataset/images/train/12394_escandell_ariel_13.jpg...

 25%|██▍       | 284/1137 [15:05<46:34,  3.28s/it]

Done.
Downloading 1yV0iU5TmhNYhrfdb1OXMJ9gYt3r1N6WP into /content/dataset/images/train/f37478_santiago_ferrero_02.jpg...

 25%|██▌       | 285/1137 [15:08<47:30,  3.35s/it]

Done.
Downloading 1dKES_13nHW5_AimBy_-awD096mXUCpK_ into /content/dataset/images/train/L32425_eugenio_lopez_10.png...

 25%|██▌       | 286/1137 [15:13<50:32,  3.56s/it]

Done.
Downloading 1Azw-RTenpPww7LLP2YG7m32J3F9Xtpxm into /content/dataset/images/train/58491_fabio_giampaoli_17.png...

 25%|██▌       | 287/1137 [15:17<55:48,  3.94s/it]

Done.
Downloading 1VEJidNUpwlQ9TkidbeK_Es9JgnZSHP4f into /content/dataset/images/train/43841031_Enzo_Ferrari_39.png...

 25%|██▌       | 288/1137 [15:20<48:40,  3.44s/it]

Done.
Downloading 1_oUmgYhufcCtVrWaeTzt8MzPtrYv07ER into /content/dataset/images/train/L32531_santiago_loza_24.jpg...

 25%|██▌       | 289/1137 [15:23<47:57,  3.39s/it]

Done.
Downloading 1VWTHv3OIgRRo_9uJzdEmmZPDNgKXmlMu into /content/dataset/images/train/s56189_salvador_sanchez_240.jpg...

 26%|██▌       | 290/1137 [15:25<44:13,  3.13s/it]

Done.
Downloading 1MLygk3mxkL0vm2_2FIw9IhO_QbfEw2CC into /content/dataset/images/train/s56189_salvador_sanchez_106.jpg...

 26%|██▌       | 291/1137 [15:28<42:50,  3.04s/it]

Done.
Downloading 1rNFC784pvgLZuJv2_fmLewXmzs2FTx4z into /content/dataset/images/train/57096_ramiro_sagrera_02.jpg...

 26%|██▌       | 292/1137 [15:32<43:41,  3.10s/it]

Done.
Downloading 1XNpkCEjjWtAHPsNpFidxUYU3KTiVvreB into /content/dataset/images/train/P51926_Leonel_Palermo_15.png...

 26%|██▌       | 293/1137 [15:36<51:32,  3.66s/it]

Done.
Downloading 1_yyg0XuCbsYxAISQbuOADVr1bXepV6PQ into /content/dataset/images/train/F37605_florencia_fernandez_02.png...

 26%|██▌       | 294/1137 [15:39<47:02,  3.35s/it]

Done.
Downloading 1EmBMe5P7CK8MvEnqK6Nfz-ZzBK3uV8ZB into /content/dataset/images/train/43841031_Enzo_Ferrari_20.png...

 26%|██▌       | 295/1137 [15:43<51:19,  3.66s/it]

Done.
Downloading 1iud0LVkwGTtx8k2wseou7i0KfP0kVkOs into /content/dataset/images/train/F37605_florencia_fernandez_24.png...

 26%|██▌       | 296/1137 [15:46<46:56,  3.35s/it]

Done.
Downloading 1NdHn9Nc6fO77MQA6DGeE4_7nN36suWb_ into /content/dataset/images/train/s56189_salvador_sanchez_128.jpg...

 26%|██▌       | 297/1137 [15:49<43:33,  3.11s/it]

Done.
Downloading 1zCb6Qk6nGTDzgH97gAdhNCsyiHfQ72BI into /content/dataset/images/train/g5845_gravifiorino_11.jpeg...

 26%|██▌       | 298/1137 [15:51<39:55,  2.86s/it]

Done.
Downloading 1sqkZZyoCX1xCG0JdQlZxEv7ESNqKhv9H into /content/dataset/images/train/51659_antonio_peroni_25.jpg...

 26%|██▋       | 299/1137 [15:54<39:21,  2.82s/it]

Done.
Downloading 12W7YHb37n-4LyXvrufsDWR6vRYMpBe5j into /content/dataset/images/train/s56189_salvador_sanchez_35.jpg...

 26%|██▋       | 300/1137 [15:56<37:08,  2.66s/it]

Done.
Downloading 1GeJKc-DkldUxpG3QWf_69vHY6uGaWWXM into /content/dataset/images/train/71846_Brisa_Menescaldi_23.png...

 26%|██▋       | 301/1137 [16:00<43:44,  3.14s/it]

Done.
Downloading 1YeCGUl_qh9LwMMXWEmtYL9TCUSRx7mjF into /content/dataset/images/train/s56189_salvador_sanchez_296.jpg...

 27%|██▋       | 302/1137 [16:02<40:05,  2.88s/it]

Done.
Downloading 1oR5PQMncMNqqJf1hhOaFpo319TD9r0qv into /content/dataset/images/train/03531_mirian_yanez_02.jpeg...

 27%|██▋       | 303/1137 [16:05<39:02,  2.81s/it]

Done.
Downloading 1fUf4lzYbtLzuvwxQnv6lw3KbGj0aKe1L into /content/dataset/images/train/58912_Timoteo_Garcia_7.jpg...

 27%|██▋       | 304/1137 [16:08<39:32,  2.85s/it]

Done.
Downloading 1yVLrAAo0RxuDVoQc0hfMsg_epucvaplx into /content/dataset/images/train/51659_antonio_peroni_29.jpg...

 27%|██▋       | 305/1137 [16:11<39:51,  2.87s/it]

Done.
Downloading 17fVaTwpX8aLIIZ0BbeJm1wO-tVKszvJP into /content/dataset/images/train/L32531_santiago_loza_38.jpg...

 27%|██▋       | 306/1137 [16:14<39:36,  2.86s/it]

Done.
Downloading 1wR-OhXcYnY8MGXcNq3YQF5CakEiEHJno into /content/dataset/images/train/43237686_Constantino_Ferrucci_6.png...

 27%|██▋       | 307/1137 [16:16<37:33,  2.71s/it]

Done.
Downloading 1YI1Io3NGFqfNnILsDS2075Gl34EDum3y into /content/dataset/images/train/72125_miguel_mussi_07.png...

 27%|██▋       | 308/1137 [16:19<37:12,  2.69s/it]

Done.
Downloading 1KmOFyq_S77HYMJUVc4GleQvo3addHhrU into /content/dataset/images/train/g5845_gravifiorino_27.jpeg...

 27%|██▋       | 309/1137 [16:26<53:37,  3.89s/it]

Done.
Downloading 1R28ozKy5194xc9AWlyRFTA5AU7-C6v7r into /content/dataset/images/train/s56189_salvador_sanchez_173.jpg...

 27%|██▋       | 310/1137 [16:28<47:10,  3.42s/it]

Done.
Downloading 1ojjNRv6gMSiHf8gUCWHSgc1_jSnhm-5n into /content/dataset/images/train/63cc48e729e1d5a1c058e4ee61def331.png...

 27%|██▋       | 311/1137 [16:31<45:05,  3.28s/it]

Done.
Downloading 13P3X6z1VIbex7uPOv25mYqNq0I_7Jqxj into /content/dataset/images/train/s56189_salvador_sanchez_48.jpg...

 27%|██▋       | 312/1137 [16:33<40:19,  2.93s/it]

Done.
Downloading 1u4eJH6qKvJ-1bv9Ru9Cv-r_OrottEdjy into /content/dataset/images/train/s56804_alexis_segui_27.png...

 28%|██▊       | 313/1137 [16:35<38:08,  2.78s/it]

Done.
Downloading 1PftMM0-nmJihI8-tJWuBjVe9lIcukAHG into /content/dataset/images/train/7575bfc3a933624222b269ebc54590df.png...

 28%|██▊       | 314/1137 [16:38<39:34,  2.89s/it]

Done.
Downloading 17aI7NC3JWLNe_Ro4SXeL3JcC7FafUPfR into /content/dataset/images/train/72125_miguel_mussi_19.png...

 28%|██▊       | 315/1137 [16:41<38:42,  2.83s/it]

Done.
Downloading 1QmVLMNHO3Qm-2dcUx6Ao6EKZjhd7qncP into /content/dataset/images/train/s56189_salvador_sanchez_166.jpg...

 28%|██▊       | 316/1137 [16:44<36:43,  2.68s/it]

Done.
Downloading 1M8Xw7k9SGdh2VcOkYqbHfac7kJooX_vS into /content/dataset/images/train/s56189_salvador_sanchez_104.jpg...

 28%|██▊       | 317/1137 [16:46<34:50,  2.55s/it]

Done.
Downloading 13nQ1yTNDx-dfLF88FEB937ohSPuXzMf1 into /content/dataset/images/train/51951_pablo_pistarelli_24.png...

 28%|██▊       | 318/1137 [16:50<41:25,  3.03s/it]

Done.
Downloading 1eo79hJpJtOpnat2x-RzQvY79HRfHJP1D into /content/dataset/images/train/51705_micaela_pozzo_14.png...

 28%|██▊       | 319/1137 [16:53<39:37,  2.91s/it]

Done.
Downloading 1w0gvLKXM5gdsWVkM5dc6D3wkiyMfQ-gZ into /content/dataset/images/train/L32425_eugenio_lopez_08.png...

 28%|██▊       | 320/1137 [16:55<36:45,  2.70s/it]

Done.
Downloading 130-v1B2Tcqe-wXwS-Y2dG4FQ6PTaO3wv into /content/dataset/images/train/s56189_salvador_sanchez_42.jpg...

 28%|██▊       | 321/1137 [16:57<35:25,  2.61s/it]

Done.
Downloading 1Q8RUNWUobiMq2ZM232uarF0zjm4rW6EX into /content/dataset/images/train/s56189_salvador_sanchez_160.jpg...

 28%|██▊       | 322/1137 [16:59<33:48,  2.49s/it]

Done.
Downloading 1uiGzv7qbNPqkNTV6D_OJiquSsRbQg3ZT into /content/dataset/images/train/f37478_santiago_ferrero_11.jpg...

 28%|██▊       | 323/1137 [17:01<32:19,  2.38s/it]

Done.
Downloading 115j25oTPVon5gn5lIgs5Vqi3fveuhr5K into /content/dataset/images/train/41932688_Simon_Revello_12.png...

 28%|██▊       | 324/1137 [17:06<40:12,  2.97s/it]

Done.
Downloading 1Vq06qFIyYqps5g4O3BvIp7vaTFhswGRb into /content/dataset/images/train/s56189_salvador_sanchez_251.jpg...

 29%|██▊       | 325/1137 [17:08<36:54,  2.73s/it]

Done.
Downloading 1Mn4iKhLFevzTAposB-_zva73GDqMIC86 into /content/dataset/images/train/e2ad06c8f78c8045468cf6009289f2df.png...

 29%|██▊       | 326/1137 [17:11<37:23,  2.77s/it]

Done.
Downloading 14J8jzkt_z1teZ_AMQLFPyKA8X-GbcoWx into /content/dataset/images/train/P51951_pablo_pistarelli_04.png...

 29%|██▉       | 327/1137 [17:13<35:35,  2.64s/it]

Done.
Downloading 18wfrXrmEJqMJM1-xjH4f-91HAIM12kXe into /content/dataset/images/train/71846_Brisa_Menescaldi_04.png...

 29%|██▉       | 328/1137 [17:18<43:20,  3.21s/it]

Done.
Downloading 1jSwzCjnzoQfbBc097e_NTLmDNZRSqPWV into /content/dataset/images/train/77ab1ff6c01ac3fed7cebfe404efce8c.png...

 29%|██▉       | 329/1137 [17:20<40:48,  3.03s/it]

Done.
Downloading 1Kk3aGSowkTaEINw98Y0XaXLjFvX-Pi7W into /content/dataset/images/train/46019_taiel_raffaeli_12.jpg...

 29%|██▉       | 330/1137 [17:23<41:05,  3.05s/it]

Done.
Downloading 1EKwcmQXEzH8rwzQxS9zuXq4Yvhjc05iQ into /content/dataset/images/train/71846_Brisa_Menescaldi_22.png...

 29%|██▉       | 331/1137 [17:28<45:18,  3.37s/it]

Done.
Downloading 1Mljt_SFhS4EfvKzU62SiwDuCb2DCsJYo into /content/dataset/images/train/52256_daniel_ponce_06.jpeg...

 29%|██▉       | 332/1137 [17:30<42:49,  3.19s/it]

Done.
Downloading 1SolX80ex2F8UhAgnD44T3G1dMzcuNYqP into /content/dataset/images/train/s56189_salvador_sanchez_200.jpg...

 29%|██▉       | 333/1137 [17:32<38:33,  2.88s/it]

Done.
Downloading 14nj-PT5BqqSNzUXsNBMqArUXj6zDAS0L into /content/dataset/images/train/43265_Lucas_Demarre_11.jpg...

 29%|██▉       | 334/1137 [17:35<37:12,  2.78s/it]

Done.
Downloading 1EFMmhVxQBPsQpz2vMLpN2sIvSReL-Ad7 into /content/dataset/images/train/s56804_alexis_segui_28.png...

 29%|██▉       | 335/1137 [17:37<35:17,  2.64s/it]

Done.
Downloading 12LiqE0Egbi_aSxwvR1ap-cZMnyUUWzU- into /content/dataset/images/train/71846_Brisa_Menescaldi_26.png...

 30%|██▉       | 336/1137 [17:42<44:14,  3.31s/it]

Done.
Downloading 17L-KDKJgQbgk2bNbDqPz4qLsMs7Q8HRX into /content/dataset/images/train/43841031_Enzo_Ferrari_09.png...

 30%|██▉       | 337/1137 [17:46<47:57,  3.60s/it]

Done.
Downloading 1mdUxKkCLkuh5clraJT6pPpMU4sVvdBxD into /content/dataset/images/train/R-45489_sofiarondini_02.png...

 30%|██▉       | 338/1137 [17:49<42:31,  3.19s/it]

Done.
Downloading 18q7Swn70xEjVri_UBVgPNpSvrwINn2Rg into /content/dataset/images/train/P_51977_martin_perrone_29.png...

 30%|██▉       | 339/1137 [17:52<41:17,  3.10s/it]

Done.
Downloading 1z_wmTF7jJKFECksV8pcFWAc-eBhlm_64 into /content/dataset/images/train/F37605_florencia_fernandez_38.png...

 30%|██▉       | 340/1137 [17:54<39:23,  2.96s/it]

Done.
Downloading 1LTVRfELzfqyaeoEhCd7XC39PBVmlp3I8 into /content/dataset/images/train/s56189_salvador_sanchez_93.jpg...

 30%|██▉       | 341/1137 [17:57<37:22,  2.82s/it]

Done.
Downloading 1V8k_FIQDW3VURX1PFaclL97Be18e6-qx into /content/dataset/images/train/51934_pablo_pistelli_10.png...

 30%|███       | 342/1137 [18:01<44:40,  3.37s/it]

Done.
Downloading 1oFo5cDaWdjVHKE_FxAsJ-UKMPAJzH-mU into /content/dataset/images/train/51934_pablo_pistelli_15.png...

 30%|███       | 343/1137 [18:07<52:45,  3.99s/it]

Done.
Downloading 1K3yroU-J0vINB37gWB6Gslt9ndpiDpu8 into /content/dataset/images/train/F37605_florencia_fernandez_36.png...

 30%|███       | 344/1137 [18:09<47:02,  3.56s/it]

Done.
Downloading 1UG2hgrixjImsDmXyUws2Pae0YJlUq-DA into /content/dataset/images/train/f37478_santiago_ferrero_35.jpg...

 30%|███       | 345/1137 [18:12<42:38,  3.23s/it]

Done.
Downloading 1wM2tadVRQ8mzHY3XEBq7XHsazV43croa into /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_08.jpg...

 30%|███       | 346/1137 [18:15<41:15,  3.13s/it]

Done.
Downloading 1jSRIIzFiZ8LlYdNmIJn3mFHpGL6KUotj into /content/dataset/images/train/58912_Timoteo_Garcia_5.jpg...

 31%|███       | 347/1137 [18:18<40:01,  3.04s/it]

Done.
Downloading 1InEikS4PV9IZJ3qCDb2wgbXvpdU913fS into /content/dataset/images/train/37494_gustavo_fontana_13.jpg...

 31%|███       | 348/1137 [18:21<41:20,  3.14s/it]

Done.
Downloading 10opbSKpPHv9ilH_GpQjlQBCTaVGCjOtN into /content/dataset/images/train/51659_antonio_peroni_30.jpg...

 31%|███       | 349/1137 [18:24<41:24,  3.15s/it]

Done.
Downloading 1R1pRp-ynVzKIagDCk-In25vf-_-dF1Ho into /content/dataset/images/train/L32425_eugenio_lopez_02.png...

 31%|███       | 350/1137 [18:27<41:26,  3.16s/it]

Done.
Downloading 1Y4I-TiyoW1Gk9uLB79J35gLC-UHbcK_O into /content/dataset/images/train/g5845_gravifiorino_15.jpeg...

 31%|███       | 351/1137 [18:29<37:09,  2.84s/it]

Done.
Downloading 1hf_b1BZTooZtrkizRHXucVVpXhsBs0mX into /content/dataset/images/train/52256_daniel_ponce_05.jpeg...

 31%|███       | 352/1137 [18:32<36:11,  2.77s/it]

Done.
Downloading 1Wx78hQsf6Y9aDHpvSf_hpmhuFoMj20Y9 into /content/dataset/images/train/R-45829_Abril_Rodriguez_21.png...

 31%|███       | 353/1137 [18:35<35:35,  2.72s/it]

Done.
Downloading 11LqwVm750b7BFhGI0LIhWkKcvKqKkxK8 into /content/dataset/images/train/51934_pablo_pistelli_05.png...

 31%|███       | 354/1137 [18:39<42:42,  3.27s/it]

Done.
Downloading 1mtVc_zjKLQf2aVCCWLDJkOEsJXQ6LI72 into /content/dataset/images/train/S57061_Leandro_Salvana_37.png...

 31%|███       | 355/1137 [18:42<39:50,  3.06s/it]

Done.
Downloading 1cE6vlshpOmuGMIAQFWJZuyx4_pOnPbWN into /content/dataset/images/train/F37605_florencia_fernandez_22.png...

 31%|███▏      | 356/1137 [18:45<38:59,  3.00s/it]

Done.
Downloading 1CYgMTNjTjfuiFBvGoY4Dp-d1sxVbL6LH into /content/dataset/images/train/51951_pablo_pistarelli_14.png...

 31%|███▏      | 357/1137 [18:48<38:47,  2.98s/it]

Done.
Downloading 1wh6FwD5j2bIfOHkItySVCTSs6M9YCDpd into /content/dataset/images/train/72125_miguel_mussi_27.png...

 31%|███▏      | 358/1137 [18:50<37:25,  2.88s/it]

Done.
Downloading 1LSxVKqyldIVkbiVHGwnr3iS-wKAvUFFH into /content/dataset/images/train/s56189_salvador_sanchez_94.jpg...

 32%|███▏      | 359/1137 [18:52<35:10,  2.71s/it]

Done.
Downloading 1D2buoKTdlD7b3Tl8cDl-F7ZxfV8dij78 into /content/dataset/images/train/A45161_Fabian_Aguirre_25.png...

 32%|███▏      | 360/1137 [18:55<35:46,  2.76s/it]

Done.
Downloading 1ncBCmzCGJzGXR6jh1sb1UJlxScPPgM5u into /content/dataset/images/train/71846_Brisa_Menescaldi_18.png...

 32%|███▏      | 361/1137 [19:00<43:26,  3.36s/it]

Done.
Downloading 1Gz5mENMTdur1xlcnSK0HKLlmgs41JgyH into /content/dataset/images/train/S57061_Leandro_Salvana_24.png...

 32%|███▏      | 362/1137 [19:03<40:49,  3.16s/it]

Done.
Downloading 1il-Ds4LzlYaByp5H8RvrgVSsyJRj5sUg into /content/dataset/images/train/dc31cabeda18c33d9a852b9144f7367c.png...

 32%|███▏      | 363/1137 [19:06<40:20,  3.13s/it]

Done.
Downloading 1u4DeH7nRe3k6EgLC3yWTA4-CwJw62L0z into /content/dataset/images/train/f37478_santiago_ferrero_08.jpg...

 32%|███▏      | 364/1137 [19:08<36:56,  2.87s/it]

Done.
Downloading 1rRE2AciJSHpMB_U_uUjON6avXpSqKg9a into /content/dataset/images/train/43841031_Enzo_Ferrari_05.png...

 32%|███▏      | 365/1137 [19:13<43:53,  3.41s/it]

Done.
Downloading 1kZ_1Px3ipMImtaY_4N_xwblcWt6ZKbGb into /content/dataset/images/train/46019_taiel_raffaeli_10.jpg...

 32%|███▏      | 366/1137 [19:16<42:40,  3.32s/it]

Done.
Downloading 1zoK7o5HJF_OPFUcik6-XVA3c5QF16pci into /content/dataset/images/train/R-45829_Abril_Rodriguez_06.png...

 32%|███▏      | 367/1137 [19:18<39:45,  3.10s/it]

Done.
Downloading 1PJPpTA-BGo-UfCN4Ztb6D8nfKuweJvKd into /content/dataset/images/train/03531_mirian_yanez_23.jpeg...

 32%|███▏      | 368/1137 [19:21<37:58,  2.96s/it]

Done.
Downloading 1J4IbcFaMI8UzuZ94PtUTCOQYxUDimrx4 into /content/dataset/images/train/S57061_Leandro_Salvana_19.png...

 32%|███▏      | 369/1137 [19:25<39:57,  3.12s/it]

Done.
Downloading 1EG9Fj-4N3Llv8socHkDIHh3PRT9_w3au into /content/dataset/images/train/58912_Timoteo_Garcia_4.jpg...

 33%|███▎      | 370/1137 [19:27<38:03,  2.98s/it]

Done.
Downloading 1Ai6lxz96U6TH4-2Jw3NVvhsiufaFu1wQ into /content/dataset/images/train/51705_micaela_pozzo_19.png...

 33%|███▎      | 371/1137 [19:30<36:16,  2.84s/it]

Done.
Downloading 1OY6skKw8iGL4DxNrjxNNGmdvy3SXz_nr into /content/dataset/images/train/d49bd455ddb890f798645384267155b3.png...

 33%|███▎      | 372/1137 [19:33<37:18,  2.93s/it]

Done.
Downloading 1KhKhYfU5YZ70iFvNZO0R8vB30J5EHrbU into /content/dataset/images/train/s56189_salvador_sanchez_77.jpg...

 33%|███▎      | 373/1137 [19:35<34:35,  2.72s/it]

Done.
Downloading 1ntRq8sV3jGL7LSmYnLgciH9PZlWlLXI4 into /content/dataset/images/train/03531_mirian_yanez_20.jpeg...

 33%|███▎      | 374/1137 [19:38<33:30,  2.63s/it]

Done.
Downloading 1JtJ9c3BO_kcJcyBdTwNayG2gkz1j_BXj into /content/dataset/images/train/s56189_salvador_sanchez_69.jpg...

 33%|███▎      | 375/1137 [19:40<31:47,  2.50s/it]

Done.
Downloading 1WjlM6OP04ix64DKx8M-qmq1W6X9TjOrh into /content/dataset/images/train/F37605_florencia_fernandez_33.png...

 33%|███▎      | 376/1137 [19:42<31:22,  2.47s/it]

Done.
Downloading 1G_PJbdouBMdCFzln5-xbbIoYdjno0deh into /content/dataset/images/train/71846_Brisa_Menescaldi_14.png...

 33%|███▎      | 377/1137 [19:47<38:59,  3.08s/it]

Done.
Downloading 1GFlYaoDaZM6K7q8c4SUxAVYLMasTtZDj into /content/dataset/images/train/71846_Brisa_Menescaldi_17.png...

 33%|███▎      | 378/1137 [19:51<44:59,  3.56s/it]

Done.
Downloading 1i4WS5KZOHJ3K1SmD81TmzbAr7kBdI9kR into /content/dataset/images/train/P_51977_martin_perrone_35.png...

 33%|███▎      | 379/1137 [19:54<41:11,  3.26s/it]

Done.
Downloading 18Z23EGwLh5qcdY6Z8ET08AHRd1S0g3Ft into /content/dataset/images/train/46094_Mateo_Rovere_19.png...

 33%|███▎      | 380/1137 [19:57<38:51,  3.08s/it]

Done.
Downloading 1WAcwQyg3idgKpOOuqGdvCYkDPFuXo3ZU into /content/dataset/images/train/s56189_salvador_sanchez_255.jpg...

 34%|███▎      | 381/1137 [19:59<35:38,  2.83s/it]

Done.
Downloading 1AwMul6_BDUJqYb7T1tJSoAXVBLnEctcM into /content/dataset/images/train/P_51977_martin_perrone_18.png...

 34%|███▎      | 382/1137 [20:04<42:41,  3.39s/it]

Done.
Downloading 1JDWppuS7-hgwdezlSHOYBBf7RQ7tNRcD into /content/dataset/images/train/57096_ramiro_sagrera_01.jpg...

 34%|███▎      | 383/1137 [20:07<42:45,  3.40s/it]

Done.
Downloading 1_GpmLjEJQPAvHMi7YmN6OctztFmYI9EM into /content/dataset/images/train/293cf3fc96a4dbd5d6004436ddc39b48.png...

 34%|███▍      | 384/1137 [20:10<40:29,  3.23s/it]

Done.
Downloading 1TmFcFMiX3vciteqVYwzA4_F5xAIfL4fD into /content/dataset/images/train/37524_augusto_farias_25.jpg...

 34%|███▍      | 385/1137 [20:14<43:53,  3.50s/it]

Done.
Downloading 1i-LeAbZQXBlLL13easPH1mbZI5UQWerT into /content/dataset/images/train/03531_mirian_yanez_14.jpeg...

 34%|███▍      | 386/1137 [20:17<41:00,  3.28s/it]

Done.
Downloading 1M7C7Ex_j7YZt1_OnkACfXFkPc7iiDLdv into /content/dataset/images/train/s56189_salvador_sanchez_100.jpg...

 34%|███▍      | 387/1137 [20:19<36:50,  2.95s/it]

Done.
Downloading 1WGO1aWPMQmeYMZQNfJWpBrYkMvtUvaY9 into /content/dataset/images/train/37494_gustavo_fontana_16.jpg...

 34%|███▍      | 388/1137 [20:22<37:59,  3.04s/it]

Done.
Downloading 1OgDFe05voxV1u0wu3EXxcgLEZbUATI07 into /content/dataset/images/train/71846_Brisa_Menescaldi_10.png...

 34%|███▍      | 389/1137 [20:28<47:40,  3.82s/it]

Done.
Downloading 1Ln-blBZPqUsQGZd-MYrGY0bX85gO6DkK into /content/dataset/images/train/s56189_salvador_sanchez_97.jpg...

 34%|███▍      | 390/1137 [20:30<41:32,  3.34s/it]

Done.
Downloading 15itwz6zn6Wi0nQUCIT3KTlA3nksB9l7e into /content/dataset/images/train/s56804_alexis_segui_04.png...

 34%|███▍      | 391/1137 [20:32<38:27,  3.09s/it]

Done.
Downloading 1yCcEj7PzJFCXGntx2XbfNPAq3NEU2C1E into /content/dataset/images/train/41932688_Simon_Revello_15.png...

 34%|███▍      | 392/1137 [20:38<46:26,  3.74s/it]

Done.
Downloading 1evrSudPafJzSSH0U5oTxszSC50wLAli0 into /content/dataset/images/train/A45161_Fabian_Aguirre_28.png...

 35%|███▍      | 393/1137 [20:40<42:31,  3.43s/it]

Done.
Downloading 1-si5mfCZ5dVx42DLO1kZcviZ8Cojn1gT into /content/dataset/images/train/12394_escandell_ariel_02.jpg...

 35%|███▍      | 394/1137 [20:43<40:17,  3.25s/it]

Done.
Downloading 1Q-5Y7u-iBMAYta74QECuWblMJwsWGU_I into /content/dataset/images/train/g5845_gravifiorino_1.jpeg...

 35%|███▍      | 395/1137 [20:46<37:57,  3.07s/it]

Done.
Downloading 1RN-vhX1uiGjQiGoxjokHWa9aplYS33KE into /content/dataset/images/train/g5845_gravifiorino_28.jpeg...

 35%|███▍      | 396/1137 [20:48<35:39,  2.89s/it]

Done.
Downloading 1Ok5f97v2lR01rLp8u1KD4XcPPrZ_Txa8 into /content/dataset/images/train/s56189_salvador_sanchez_141.jpg...

 35%|███▍      | 397/1137 [20:51<33:01,  2.68s/it]

Done.
Downloading 1VbLZaBMBnjLS3q-z9NQnoDmCC0_N24oi into /content/dataset/images/train/43841031_Enzo_Ferrari_32.png...

 35%|███▌      | 398/1137 [20:55<37:39,  3.06s/it]

Done.
Downloading 1Cjo-tnY54ZWogxbP8xDNYRPoRnYxBv7g into /content/dataset/images/train/58513_isaias_garay_03.png...

 35%|███▌      | 399/1137 [20:57<34:49,  2.83s/it]

Done.
Downloading 1Kq7VhG3yYFWvzlH9x28_dfikN3InQfT8 into /content/dataset/images/train/s56189_salvador_sanchez_80.jpg...

 35%|███▌      | 400/1137 [20:59<32:56,  2.68s/it]

Done.
Downloading 1M6xZxrWRv2WmWcyUTTrMlpM9wIBidEGo into /content/dataset/images/train/A45161_Fabian_Aguirre_03.png...

 35%|███▌      | 401/1137 [21:02<32:52,  2.68s/it]

Done.
Downloading 1j1EeLDdFC-E6vP8nmsE5H2VY199ng0JV into /content/dataset/images/train/S57061_Leandro_Salvana_49.png...

 35%|███▌      | 402/1137 [21:04<32:01,  2.61s/it]

Done.
Downloading 1LFYjvPqUHt4cm9WZpOubQCJntLuCeHtT into /content/dataset/images/train/A45161_Fabian_Aguirre_20.png...

 35%|███▌      | 403/1137 [21:07<32:20,  2.64s/it]

Done.
Downloading 1kLsIG_TEK34bSahSWUcAKqXB1L2NlRVW into /content/dataset/images/train/L32425_eugenio_lopez_30.png...

 36%|███▌      | 404/1137 [21:10<33:13,  2.72s/it]

Done.
Downloading 1RGwzcbvVdxUH76nicxYECLsliWyj_4X2 into /content/dataset/images/train/S57061_Leandro_Salvana_40.png...

 36%|███▌      | 405/1137 [21:13<33:42,  2.76s/it]

Done.
Downloading 10KPox8hTbFofxFBMmZqZpHvebWpN4Spz into /content/dataset/images/train/g5845_gravifiorino_5.jpeg...

 36%|███▌      | 406/1137 [21:15<31:31,  2.59s/it]

Done.
Downloading 1DRUA5P1a_YKwyvNfYOlkUnXGmmsRUEbS into /content/dataset/images/train/71846_Brisa_Menescaldi_11.png...

 36%|███▌      | 407/1137 [21:20<41:02,  3.37s/it]

Done.
Downloading 14_q8uLN_xwWBXSgSiv_HEVzdLDwd2Pid into /content/dataset/images/train/52256_daniel_ponce_04.jpeg...

 36%|███▌      | 408/1137 [21:23<38:28,  3.17s/it]

Done.
Downloading 1lD5MOCgj-Ee9bng8RhBQs6_DJ-Xbkqun into /content/dataset/images/train/S57061_Leandro_Salvana_22.png...

 36%|███▌      | 409/1137 [21:26<39:34,  3.26s/it]

Done.
Downloading 1jRu-4zWIM6XtgJns0U2Kq_aynnj6cdo4 into /content/dataset/images/train/P51926_Leonel_Palermo_05.png...

 36%|███▌      | 410/1137 [21:31<44:06,  3.64s/it]

Done.
Downloading 18001OJpLNqPqRDJp8NI0wovhf9dJaysZ into /content/dataset/images/train/58513_isaias_garay_04.png...

 36%|███▌      | 411/1137 [21:33<40:24,  3.34s/it]

Done.
Downloading 1w7SN3jygu-oTaFo6EqrHdLtRwUCNAzMc into /content/dataset/images/train/03531_mirian_yanez_10.jpeg...

 36%|███▌      | 412/1137 [21:36<38:35,  3.19s/it]

Done.
Downloading 1rKGZKI1puAI4RHycAJF4F7QjbZ7uDelT into /content/dataset/images/train/f37478_santiago_ferrero_21.jpg...

 36%|███▋      | 413/1137 [21:39<36:36,  3.03s/it]

Done.
Downloading 11lRHjaz4GpnxdVBagp4C2CUNe9BkGeqs into /content/dataset/images/train/s56189_salvador_sanchez_25.jpg...

 36%|███▋      | 414/1137 [21:41<33:50,  2.81s/it]

Done.
Downloading 1ajCfUDgjMeKsW1Q9rpRjFBjsDY_jZton into /content/dataset/images/train/S57061_Leandro_Salvana_08.png...

 36%|███▋      | 415/1137 [21:44<33:01,  2.75s/it]

Done.
Downloading 1-LioINBeGZti8vDIYM3F1hZYVzIEtvjQ into /content/dataset/images/train/s56189_salvador_sanchez_7.jpg...

 37%|███▋      | 416/1137 [21:47<32:51,  2.73s/it]

Done.
Downloading 1KrShocLQWXqaAwuERrQ0d3nbM_Anvu0q into /content/dataset/images/train/s56189_salvador_sanchez_81.jpg...

 37%|███▋      | 417/1137 [21:49<31:19,  2.61s/it]

Done.
Downloading 1OD3bptSJOrJQwBIroCeMblXuOiw0WF6H into /content/dataset/images/train/72125_miguel_mussi_29.png...

 37%|███▋      | 418/1137 [21:52<31:15,  2.61s/it]

Done.
Downloading 1Rzc4KgQ-zIm8kjuUc504l6jxOTxFah8J into /content/dataset/images/train/23451_guido_lorenzettibruera_13.jpg...

 37%|███▋      | 419/1137 [21:56<37:30,  3.13s/it]

Done.
Downloading 1jJDtwf3zQnR-4w8La4JL0EUyA8HEnpvN into /content/dataset/images/train/L32531_santiago_loza_31.jpg...

 37%|███▋      | 420/1137 [21:59<38:18,  3.21s/it]

Done.
Downloading 1OlHlNC6OBfuKGZGC-2Kjzd2mzM0Mmp6- into /content/dataset/images/train/P51926_Leonel_Palermo_28.png...

 37%|███▋      | 421/1137 [22:03<40:41,  3.41s/it]

Done.
Downloading 1ReSKRd9uGvnzIukPjVlkRtfnCGVZnX10 into /content/dataset/images/train/43265_Lucas_Demarre_24.jpg...

 37%|███▋      | 422/1137 [22:05<36:41,  3.08s/it]

Done.
Downloading 1MIESVuYV-hDJZ2ZRdEZj8rToIKsweRvD into /content/dataset/images/train/s56189_salvador_sanchez_105.jpg...

 37%|███▋      | 423/1137 [22:08<34:34,  2.91s/it]

Done.
Downloading 1cte5rsoOHnJraDSbw_QAuRMlRCviA8Tm into /content/dataset/images/train/w05576_juan_wagner_14.png...

 37%|███▋      | 424/1137 [22:10<32:53,  2.77s/it]

Done.
Downloading 1B3kuU8kUufPeWYNpLoiicXPbQLerngG0 into /content/dataset/images/train/f37478_santiago_ferrero_26.jpg...

 37%|███▋      | 425/1137 [22:14<34:52,  2.94s/it]

Done.
Downloading 1gJB8fq7x4Co83IFypyOHQMZQo_82kqdO into /content/dataset/images/train/51659_antonio_peroni_08.jpg...

 37%|███▋      | 426/1137 [22:17<35:15,  2.98s/it]

Done.
Downloading 14uS9PurxgGyLPAjOuKr5lVBo8e7Jdr6b into /content/dataset/images/train/58491_fabio_giampaoli_02.png...

 38%|███▊      | 427/1137 [22:24<51:18,  4.34s/it]

Done.
Downloading 1lpi5q2gjm45g_1aVxHVseNLxcWOUWRBU into /content/dataset/images/train/R-45829_Abril_Rodriguez_19.png...

 38%|███▊      | 428/1137 [22:27<46:51,  3.97s/it]

Done.
Downloading 16eh_FaN_2MO_p0djx6vo36F8dsncRsDo into /content/dataset/images/train/72125_miguel_mussi_26.png...

 38%|███▊      | 429/1137 [22:30<41:21,  3.51s/it]

Done.
Downloading 1JczERRewjIw1lNocafzWOVLKy6OrvYGb into /content/dataset/images/train/s56189_salvador_sanchez_68.jpg...

 38%|███▊      | 430/1137 [22:32<37:12,  3.16s/it]

Done.
Downloading 1ACg4B7dnG-jYYlAUY7GsGmnFliNfvOuI into /content/dataset/images/train/43265_Lucas_Demarre_03.jpg...

 38%|███▊      | 431/1137 [22:34<33:22,  2.84s/it]

Done.
Downloading 1hrezpf4Y50Gm5ZsecRtWYBg3nlEG46ML into /content/dataset/images/train/R-45489_sofiarondini_16.png...

 38%|███▊      | 432/1137 [22:37<32:09,  2.74s/it]

Done.
Downloading 1Ruk8asco20wq3Zu0iiqVye4O7ALcuwWi into /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_17.jpg...

 38%|███▊      | 433/1137 [22:40<32:43,  2.79s/it]

Done.
Downloading 1nwRafP3-bdiwCNxpjsLLe-3YhOPUxadB into /content/dataset/images/train/w05576_juan_wagner_02.png...

 38%|███▊      | 434/1137 [22:42<30:42,  2.62s/it]

Done.
Downloading 11PMzXBHyKSLh7aWD_Qp3wvjIbJEW_NSq into /content/dataset/images/train/37494_gustavo_fontana_05.jpg...

 38%|███▊      | 435/1137 [22:45<32:26,  2.77s/it]

Done.
Downloading 1fLqnB00N5lNWlxJwQwJ3Oh4GFKCjsuH1 into /content/dataset/images/train/F37605_florencia_fernandez_32.png...

 38%|███▊      | 436/1137 [22:48<31:52,  2.73s/it]

Done.
Downloading 1jm4JPXjBbTjW0XfgMiU2jnlYPcCYZ1GG into /content/dataset/images/train/03531_mirian_yanez_25.jpeg...

 38%|███▊      | 437/1137 [22:51<32:58,  2.83s/it]

Done.
Downloading 1I4_uiHwkqqFXO6T1qmxRsArKS86vjcEm into /content/dataset/images/train/12394_escandell_ariel_29.jpg...

 39%|███▊      | 438/1137 [22:53<31:26,  2.70s/it]

Done.
Downloading 1-hBh-trKH51hPBF48-iO0Q9otP4UbsP1 into /content/dataset/images/train/w05576_juan_wagner_07.png...

 39%|███▊      | 439/1137 [22:56<32:39,  2.81s/it]

Done.
Downloading 1qoRKTjbvmVr4sLrfzExhiP9sARGcSNP7 into /content/dataset/images/train/P51926_Leonel_Palermo_24.png...

 39%|███▊      | 440/1137 [23:01<41:09,  3.54s/it]

Done.
Downloading 1mYqyHgQYyuJrit0v-oQzRUssBhhI_QTJ into /content/dataset/images/train/7a1990090ea52f2b726a8c6b02b5cff3.png...

 39%|███▉      | 441/1137 [23:04<37:53,  3.27s/it]

Done.
Downloading 1WgTsiuJza1KvTHpNCyiTLJqjkdrrNDP6 into /content/dataset/images/train/s56189_salvador_sanchez_268.jpg...

 39%|███▉      | 442/1137 [23:06<34:42,  3.00s/it]

Done.
Downloading 1O7Q4kctVceNnXIBdG-R7CkDSj5wC2QWf into /content/dataset/images/train/23451_guido_lorenzettibruera_29.jpg...

 39%|███▉      | 443/1137 [23:12<42:49,  3.70s/it]

Done.
Downloading 1cmKQ4KlKbMj-jZBorg7jg3QZOOHXhDm5 into /content/dataset/images/train/43841031_Enzo_Ferrari_01.png...

 39%|███▉      | 444/1137 [23:14<37:21,  3.23s/it]

Done.
Downloading 1OeeeuXuVHYh2vcrrzvE5t6hk8qw2AaLf into /content/dataset/images/train/s56189_salvador_sanchez_138.jpg...

 39%|███▉      | 445/1137 [23:16<33:34,  2.91s/it]

Done.
Downloading 1Pj8lMeWDMB3vxRFuoOlka72-zPbeHioW into /content/dataset/images/train/37524_augusto_farias_28.jpg...

 39%|███▉      | 446/1137 [23:20<36:01,  3.13s/it]

Done.
Downloading 1YAHnGuKsLZTbVjFUJy3WMyJnS6vpaHRe into /content/dataset/images/train/s56189_salvador_sanchez_291.jpg...

 39%|███▉      | 447/1137 [23:22<32:54,  2.86s/it]

Done.
Downloading 1_WICjo5Evy3vFgJoAYWzLfCm_8yH8AoT into /content/dataset/images/train/R-45489_sofiarondini_17.png...

 39%|███▉      | 448/1137 [23:24<30:47,  2.68s/it]

Done.
Downloading 1IEW9Ccr54vhxvRRPX4PkKJwUV2bEVpT9 into /content/dataset/images/train/72125_miguel_mussi_14.png...

 39%|███▉      | 449/1137 [23:27<30:53,  2.69s/it]

Done.
Downloading 1ilOgIxYpPYGnE43wNn-0hmtY1lz4F5kQ into /content/dataset/images/train/P51926_Leonel_Palermo_02.png...

 40%|███▉      | 450/1137 [23:35<49:23,  4.31s/it]

Done.
Downloading 1uaDts4MJ9S9NKNjV8ucCbuqBf9o1ZOxX into /content/dataset/images/train/P_51977_martin_perrone_07.png...

 40%|███▉      | 451/1137 [23:40<50:01,  4.38s/it]

Done.
Downloading 12aDWWoPlzrtZQQhPCucn0PWd2ejwv-cl into /content/dataset/images/train/s56189_salvador_sanchez_37.jpg...

 40%|███▉      | 452/1137 [23:42<42:53,  3.76s/it]

Done.
Downloading 1zKR9Vrq33e4xLe2MSptX0SsXVTbrawPI into /content/dataset/images/train/s56804_alexis_segui_16.png...

 40%|███▉      | 453/1137 [23:44<38:18,  3.36s/it]

Done.
Downloading 1_FFERodFnwnnFFOUQSOKsZxVntDskTlp into /content/dataset/images/train/12394_escandell_ariel_03.jpg...

 40%|███▉      | 454/1137 [23:47<36:41,  3.22s/it]

Done.
Downloading 1P7R_rQEKTDmCoZiPV6-JfvyICx6DSZfm into /content/dataset/images/train/s56189_salvador_sanchez_149.jpg...

 40%|████      | 455/1137 [23:49<33:02,  2.91s/it]

Done.
Downloading 1jzcz0LtGK84XSDB5tLDLAcqfHeX-kcv0 into /content/dataset/images/train/bc4e58ee986480992cdd8acb87b3a21c.png...

 40%|████      | 456/1137 [23:53<35:10,  3.10s/it]

Done.
Downloading 1yNqGh2wg6eyYlr7iu0rSbnZyHHF6_mtv into /content/dataset/images/train/S57061_Leandro_Salvana_21.png...

 40%|████      | 457/1137 [23:56<34:15,  3.02s/it]

Done.
Downloading 1fOMKNK_X634MLEw0y0zZwqwf9OnAo9TC into /content/dataset/images/train/P51926_Leonel_Palermo_10.png...

 40%|████      | 458/1137 [24:00<39:22,  3.48s/it]

Done.
Downloading 1L6ac6BGFUHhhrgupSgDIyQYmbtqrJyio into /content/dataset/images/train/s56189_salvador_sanchez_85.jpg...

 40%|████      | 459/1137 [24:02<34:46,  3.08s/it]

Done.
Downloading 1W9NJCRAEvdTEIvpirP0DId7pjtBgyj2o into /content/dataset/images/train/s56189_salvador_sanchez_250.jpg...

 40%|████      | 460/1137 [24:05<31:36,  2.80s/it]

Done.
Downloading 1Tg9BcLlXzZwKS9kpPhOpaJv-9g3yh24E into /content/dataset/images/train/g5845_gravifiorino_16.jpeg...

 41%|████      | 461/1137 [24:07<30:28,  2.71s/it]

Done.
Downloading 10Rp4bV9u5m-TeVYWR_8Jt9V1UZIXIQxo into /content/dataset/images/train/43237686_Constantino_Ferrucci_35.png...

 41%|████      | 462/1137 [24:10<30:19,  2.70s/it]

Done.
Downloading 1KV3W_ZxZJIHgTKaqFWKxcpQcG7CL5mH3 into /content/dataset/images/train/S57061_Leandro_Salvana_28.png...

 41%|████      | 463/1137 [24:13<30:53,  2.75s/it]

Done.
Downloading 1hctmExPwy6fDMG7TUONAXJgqK2WUQayf into /content/dataset/images/train/L32531_santiago_loza_7.jpg...

 41%|████      | 464/1137 [24:16<32:12,  2.87s/it]

Done.
Downloading 1us1otUmCW1hjonAUeG55Aw9UFmHgY5qZ into /content/dataset/images/train/f37478_santiago_ferrero_23.jpg...

 41%|████      | 465/1137 [24:18<30:32,  2.73s/it]

Done.
Downloading 1zd7VJLZvjUpvxu9zvbwV8PwQK5PCNsh5 into /content/dataset/images/train/51705_micaela_pozzo_24.png...

 41%|████      | 466/1137 [24:21<30:29,  2.73s/it]

Done.
Downloading 1hymLloqEh4Jyly2p55af7ttxr4Isq2iP into /content/dataset/images/train/L32531_santiago_loza_12.jpg...

 41%|████      | 467/1137 [24:24<31:14,  2.80s/it]

Done.
Downloading 1FAMfHllOhZNveHBPHLPbG_n9xiHvcHJa into /content/dataset/images/train/37494_gustavo_fontana_19.jpg...

 41%|████      | 468/1137 [24:27<32:25,  2.91s/it]

Done.
Downloading 1V0swToQV-SHsKMCR3ZNvyqNUaCRsnZm1 into /content/dataset/images/train/37494_gustavo_fontana_15.jpg...

 41%|████      | 469/1137 [24:30<32:53,  2.95s/it]

Done.
Downloading 1g1QsTrT4QSS9FsHAh30ZFkTMiplwLmYK into /content/dataset/images/train/46094_Mateo_Rovere_10.png...

 41%|████▏     | 470/1137 [24:33<32:30,  2.92s/it]

Done.
Downloading 1dhml2-smc5KDSBgGX_rD8OFGDO3oaUJd into /content/dataset/images/train/S57061_Leandro_Salvana_29.png...

 41%|████▏     | 471/1137 [24:35<31:12,  2.81s/it]

Done.
Downloading 1WiMtxBelilPTjKryFO099mIH4tetrsUS into /content/dataset/images/train/s56189_salvador_sanchez_267.jpg...

 42%|████▏     | 472/1137 [24:38<28:53,  2.61s/it]

Done.
Downloading 1knbVZWubpzVFmKqMla9xdneuOTKJtNZV into /content/dataset/images/train/46094_Mateo_Rovere_17.png...

 42%|████▏     | 473/1137 [24:40<28:38,  2.59s/it]

Done.
Downloading 1QXZZtalmFPVIVC5ZPf1wkqqJOfpZlnVP into /content/dataset/images/train/49cf91ad867c2d81a1eef82ebba7c4ee.png...

 42%|████▏     | 474/1137 [24:43<30:58,  2.80s/it]

Done.
Downloading 1lUZDtBAp9OpeBV7qQIeki1k6h0HTMvVQ into /content/dataset/images/train/P_51977_martin_perrone_12.png...

 42%|████▏     | 475/1137 [24:48<36:03,  3.27s/it]

Done.
Downloading 1LDWBpyuFGUdwTrCJypvg5BKIjiuLK2tu into /content/dataset/images/train/L32425_eugenio_lopez_23.png...

 42%|████▏     | 476/1137 [24:51<36:24,  3.30s/it]

Done.
Downloading 1-Af1AIRR3IiYB_-YjR1Jm82NuDhEWUJP into /content/dataset/images/train/s56189_salvador_sanchez_8.jpg...

 42%|████▏     | 477/1137 [24:53<32:53,  2.99s/it]

Done.
Downloading 1Zgn8C4ZEZZFlIjqmfQlD1PzB01jrXMMU into /content/dataset/images/train/s56189_salvador_sanchez_315.jpg...

 42%|████▏     | 478/1137 [24:56<30:56,  2.82s/it]

Done.
Downloading 1OpcYIecxPRSG6Gih-Ocnuhr96xPLqNLY into /content/dataset/images/train/s56189_salvador_sanchez_144.jpg...

 42%|████▏     | 479/1137 [24:58<28:57,  2.64s/it]

Done.
Downloading 1UiCWThfq4V3H4ayfiG2ve2Ov_2FunFbz into /content/dataset/images/train/P51926_Leonel_Palermo_06.png...

 42%|████▏     | 480/1137 [25:03<35:11,  3.21s/it]

Done.
Downloading 1_xdM3KziAf6rn4OnohCPVoYZfjTUTPs_ into /content/dataset/images/train/72125_miguel_mussi_21.png...

 42%|████▏     | 481/1137 [25:05<33:37,  3.08s/it]

Done.
Downloading 1zfKotgLvLneb5m9bfkY0mebrFvbWSL13 into /content/dataset/images/train/58491_fabio_giampaoli_11.png...

 42%|████▏     | 482/1137 [25:11<41:31,  3.80s/it]

Done.
Downloading 1XDJaUkBqV19knpB3CbP8tSvaK1QIWnQh into /content/dataset/images/train/51659_antonio_peroni_17.jpg...

 42%|████▏     | 483/1137 [25:14<38:21,  3.52s/it]

Done.
Downloading 1Kp-oKNbqejlASQ6olc_0MPxanrO7hkFQ into /content/dataset/images/train/s56189_salvador_sanchez_76.jpg...

 43%|████▎     | 484/1137 [25:16<34:49,  3.20s/it]

Done.
Downloading 14L7uI8WjeHn9HVvWm_YdJcRehjV7NblF into /content/dataset/images/train/444067f9638cc7732f454f076cf67609.png...

 43%|████▎     | 485/1137 [25:19<34:19,  3.16s/it]

Done.
Downloading 1ngpGWFofe_0Zx1S2y9Oe_lFPtJH9izFv into /content/dataset/images/train/51705_micaela_pozzo_02.png...

 43%|████▎     | 486/1137 [25:22<32:31,  3.00s/it]

Done.
Downloading 1U8TpnuX-TCvbuquC4q0PEX4FEz3IpLL2 into /content/dataset/images/train/s56189_salvador_sanchez_225.jpg...

 43%|████▎     | 487/1137 [25:24<29:48,  2.75s/it]

Done.
Downloading 1btC-9nHwbHYtrGELvIEJSpIpUZTLmU1p into /content/dataset/images/train/37524_augusto_farias_05.jpg...

 43%|████▎     | 488/1137 [25:32<44:58,  4.16s/it]

Done.
Downloading 1YsumpESSAx23VOqwV_GlXjLGUripxVGe into /content/dataset/images/train/s56189_salvador_sanchez_304.jpg...

 43%|████▎     | 489/1137 [25:34<39:04,  3.62s/it]

Done.
Downloading 1CqXdZbnhaPaqOAPWqOvAQXzD4T8_AO43 into /content/dataset/images/train/51934_pablo_pistelli_09.png...

 43%|████▎     | 490/1137 [25:38<40:28,  3.75s/it]

Done.
Downloading 1c3zWZaPYmYhXuKW81j6ypgijaTL86J_5 into /content/dataset/images/train/51659_antonio_peroni_14.jpg...

 43%|████▎     | 491/1137 [25:41<37:28,  3.48s/it]

Done.
Downloading 1KZ7q78zOBSaCt66-nyQd3vgR7yFWVIms into /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_16.jpg...

 43%|████▎     | 492/1137 [25:44<35:29,  3.30s/it]

Done.
Downloading 1RFTxTG1i34yvPSK4UN_JjGB_oFBdyguY into /content/dataset/images/train/640c8248cdba8d4a8113aa6a005d8a98.png...

 43%|████▎     | 493/1137 [25:46<33:43,  3.14s/it]

Done.
Downloading 1Rh4MW2H0uJbK22eL9WItLX7ebk8MRJf_ into /content/dataset/images/train/s56189_salvador_sanchez_187.jpg...

 43%|████▎     | 494/1137 [25:49<30:28,  2.84s/it]

Done.
Downloading 13QQ8oxOL6NkU2d-4ylENJPkFVwuPJs8e into /content/dataset/images/train/s56189_salvador_sanchez_47.jpg...

 44%|████▎     | 495/1137 [25:51<29:08,  2.72s/it]

Done.
Downloading 1YgTZ3UWqNO3m9j16ELpzS2OJXgHo7llJ into /content/dataset/images/train/12394_escandell_ariel_12.jpg...

 44%|████▎     | 496/1137 [25:54<28:37,  2.68s/it]

Done.
Downloading 1pEPm_KE6bOO8lm8DsCEo9xt2iCzcljsZ into /content/dataset/images/train/L32531_santiago_loza_22.jpg...

 44%|████▎     | 497/1137 [25:56<29:09,  2.73s/it]

Done.
Downloading 1xQ9f7DpFEtyCwQ5fmEQO99yTcz7C-DLg into /content/dataset/images/train/37494_gustavo_fontana_24.jpg...

 44%|████▍     | 498/1137 [26:00<30:03,  2.82s/it]

Done.
Downloading 1aTyKmRP_OCdNQgQcHahAm5uFFa6sXeCI into /content/dataset/images/train/P_51977_martin_perrone_40.png...

 44%|████▍     | 499/1137 [26:02<30:08,  2.83s/it]

Done.
Downloading 1-Rf6BetZHqSR2XDxGP4vfB7UEWzqreIr into /content/dataset/images/train/R-45829_Abril_Rodriguez_23.png...

 44%|████▍     | 500/1137 [26:05<30:07,  2.84s/it]

Done.
Downloading 12PSyEpsIe3oIFNnJxGmXh9lRLnBRl2G1 into /content/dataset/images/train/s56189_salvador_sanchez_34.jpg...

 44%|████▍     | 501/1137 [26:08<28:40,  2.70s/it]

Done.
Downloading 137vYg44idgg4-9VtLpHR701s3LbxUTaa into /content/dataset/images/train/R-45489_sofiarondini_18.png...

 44%|████▍     | 502/1137 [26:10<27:15,  2.58s/it]

Done.
Downloading 1WUt6T78sr3VEeqA72jgw-iDw3Koyk_aq into /content/dataset/images/train/58491_fabio_giampaoli_26.png...

 44%|████▍     | 503/1137 [26:15<34:45,  3.29s/it]

Done.
Downloading 1VopYAXg0ojWzgizu09ArJcjzmJQHMAqC into /content/dataset/images/train/s56189_salvador_sanchez_243.jpg...

 44%|████▍     | 504/1137 [26:17<31:34,  2.99s/it]

Done.
Downloading 1VQ4VBvwfghquHrA9sxcLmpJEUf6fQOmy into /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_26.jpg...

 44%|████▍     | 505/1137 [26:20<31:21,  2.98s/it]

Done.
Downloading 1VResaZwlAV6NtpShjvEIGGnmdFqo2iBH into /content/dataset/images/train/72125_miguel_mussi_17.png...

 45%|████▍     | 506/1137 [26:23<32:04,  3.05s/it]

Done.
Downloading 17PO69f0s4Evi0edq55spHs-SXBZe5kyu into /content/dataset/images/train/58513_isaias_garay_28.png...

 45%|████▍     | 507/1137 [26:26<29:51,  2.84s/it]

Done.
Downloading 1Gg8KUgjBpuJLUnuA9oAAuJOeTvmL4B0z into /content/dataset/images/train/51934_pablo_pistelli_14.png...

 45%|████▍     | 508/1137 [26:30<34:52,  3.33s/it]

Done.
Downloading 1hhMv2tO2rzOwUgcmm-j2zd9oKtoKSvW- into /content/dataset/images/train/L32425_eugenio_lopez_29.png...

 45%|████▍     | 509/1137 [26:35<39:28,  3.77s/it]

Done.
Downloading 1H0mPzIUHODQasno5uf_h8aRB9_FbD2a6 into /content/dataset/images/train/gravifiorino_7.jpeg...

 45%|████▍     | 510/1137 [26:37<34:08,  3.27s/it]

Done.
Downloading 1SIltccGvA1wBtwmQLX4I8M7Uh4cN1Jy8 into /content/dataset/images/train/s56189_salvador_sanchez_194.jpg...

 45%|████▍     | 511/1137 [26:43<43:33,  4.17s/it]

Done.
Downloading 1lBGkZ0AkEr4jKIOWLbvrXDQgoAVtKfkL into /content/dataset/images/train/R-45489_sofiarondini_01.png...

 45%|████▌     | 512/1137 [26:46<38:09,  3.66s/it]

Done.
Downloading 13p04J53K0LGu-63m8UDImz_3zXUkHGGZ into /content/dataset/images/train/F37605_florencia_fernandez_51.png...

 45%|████▌     | 513/1137 [26:48<33:32,  3.22s/it]

Done.
Downloading 1p9M07L3y6QO4wbM9DhIRFFPKkPfha6Jk into /content/dataset/images/train/L32425_eugenio_lopez_15.png...

 45%|████▌     | 514/1137 [26:51<31:58,  3.08s/it]

Done.
Downloading 1OM3Bh8uoPi2rjLFfL6tGyUXdVl2mXxsX into /content/dataset/images/train/s56189_salvador_sanchez_133.jpg...

 45%|████▌     | 515/1137 [27:14<1:33:13,  8.99s/it]

Done.
Downloading 1QKCW4rw1zZYdClCfkhpDXLHa8rC3Xt5j into /content/dataset/images/train/f5bdbc47a9fbe44482cdc1322b16c5bc.png...

 45%|████▌     | 516/1137 [27:17<1:14:35,  7.21s/it]

Done.
Downloading 1HZuAV9Wfvxy8ERo1dTiwONc1kJYIMoxv into /content/dataset/images/train/43265_Lucas_Demarre_16.jpg...

 45%|████▌     | 517/1137 [27:19<58:55,  5.70s/it]

Done.
Downloading 1UDml2O359Y7ObfqChpM4KDQ6CoMl4_8_ into /content/dataset/images/train/f37478_santiago_ferrero_34.jpg...

 46%|████▌     | 518/1137 [27:22<51:04,  4.95s/it]

Done.
Downloading 1OuHO1DyVDjTX5V1lMz5sYNsFyx-q-TXa into /content/dataset/images/train/s56189_salvador_sanchez_145.jpg...

 46%|████▌     | 519/1137 [27:24<42:23,  4.12s/it]

Done.
Downloading 1CzzZJjjIBznXwjYHolHHebLiAZRMXzSk into /content/dataset/images/train/03531_mirian_yanez_22.jpeg...

 46%|████▌     | 520/1137 [27:27<37:19,  3.63s/it]

Done.
Downloading 1WNI9rPUygC1aIUTyS0Hi9xFx8-vtqs7B into /content/dataset/images/train/s56189_salvador_sanchez_260.jpg...

 46%|████▌     | 521/1137 [27:29<32:43,  3.19s/it]

Done.
Downloading 1PAOuQLljUHNntMfU3gDvcHEZKloTDWa5 into /content/dataset/images/train/s56189_salvador_sanchez_148.jpg...

 46%|████▌     | 522/1137 [27:31<29:57,  2.92s/it]

Done.
Downloading 1h3o_Za-GIwcRqolF-XXGdHZAV4lJ6Igz into /content/dataset/images/train/A45161_Fabian_Aguirre_10.png...

 46%|████▌     | 523/1137 [27:33<28:15,  2.76s/it]

Done.
Downloading 1b-YGN1VLI0eLQ_KIIhiXsgH3D9VFARpF into /content/dataset/images/train/F37605_florencia_fernandez_21.png...

 46%|████▌     | 524/1137 [27:36<27:23,  2.68s/it]

Done.
Downloading 1f0TIM1GWHx2fX8sqPrpQUuKogPMbr8Wz into /content/dataset/images/train/f37478_santiago_ferrero_12.jpg...

 46%|████▌     | 525/1137 [27:38<26:22,  2.59s/it]

Done.
Downloading 1g0R0efpW4Hn7w3TmQWZpSpmNgjV6gEDV into /content/dataset/images/train/23451_guido_lorenzettibruera_30.jpg...

 46%|████▋     | 526/1137 [27:44<34:28,  3.39s/it]

Done.
Downloading 1_4Kpt3sOUc9hxxSsyCpxZyWnsWi7KowU into /content/dataset/images/train/52256_daniel_ponce_27.jpeg...

 46%|████▋     | 527/1137 [27:46<32:00,  3.15s/it]

Done.
Downloading 18MyUu93HsV77oa0O_A4olcsDI1PY2FN9 into /content/dataset/images/train/A45161_Fabian_Aguirre_06.png...

 46%|████▋     | 528/1137 [27:49<31:06,  3.06s/it]

Done.
Downloading 104Ql6fwkMCal6HHu5zA7La69vVB6QD0i into /content/dataset/images/train/f37478_santiago_ferrero_30.jpg...

 47%|████▋     | 529/1137 [27:52<29:51,  2.95s/it]

Done.
Downloading 1gSSKL1Wg3KB55myZkI_-mx0LLjKR87NT into /content/dataset/images/train/w05576_juan_wagner_08.png...

 47%|████▋     | 530/1137 [27:54<27:58,  2.77s/it]

Done.
Downloading 1SDNgvtEzh3ykpYQbm3tl2N-xdwmZXizH into /content/dataset/images/train/s56189_salvador_sanchez_192.jpg...

 47%|████▋     | 531/1137 [27:56<26:51,  2.66s/it]

Done.
Downloading 1bJB_SRh2mb15jpaRtIqee8-mcUtOfSZt into /content/dataset/images/train/43841031_Enzo_Ferrari_19.png...

 47%|████▋     | 532/1137 [28:03<37:29,  3.72s/it]

Done.
Downloading 1My0Ju7uu-gHQjMx7L_KA3GFUljLk4hqJ into /content/dataset/images/train/s56189_salvador_sanchez_118.jpg...

 47%|████▋     | 533/1137 [28:05<32:59,  3.28s/it]

Done.
Downloading 1hOAnx1aFfjxVpnzxGWwoiytP3Wx3a5ax into /content/dataset/images/train/L32531_santiago_loza_26.jpg...

 47%|████▋     | 534/1137 [28:08<32:25,  3.23s/it]

Done.
Downloading 1aWO_rO8mPKBcnyJny_2fSfzRdRFmPDgO into /content/dataset/images/train/P51926_Leonel_Palermo_18.png...

 47%|████▋     | 535/1137 [28:14<40:56,  4.08s/it]

Done.
Downloading 1zqoWsp33vgoi2Y4ux9jHv1OamRdv0bQ8 into /content/dataset/images/train/46094_Mateo_Rovere_3.png...

 47%|████▋     | 536/1137 [28:17<38:25,  3.84s/it]

Done.
Downloading 1_QrvGqPkZfpl4BrQC4JvXZQjAW-oQ5j9 into /content/dataset/images/train/P51926_Leonel_Palermo_25.png...

 47%|████▋     | 537/1137 [28:21<39:04,  3.91s/it]

Done.
Downloading 1yQ_Qah2DdpuNZFOaXajpPLb1yPHbwomG into /content/dataset/images/train/a8b7acca23be1e0eb16cd0d9f9b1858d.png...

 47%|████▋     | 538/1137 [28:25<37:15,  3.73s/it]

Done.
Downloading 1MSiWPtBb8OSUofKcHbeBraaOUj_gmKc8 into /content/dataset/images/train/s56189_salvador_sanchez_109.jpg...

 47%|████▋     | 539/1137 [28:27<32:48,  3.29s/it]

Done.
Downloading 1Qs3lx4NvfDxf4Gh5om5gQ6wPg4n7idHN into /content/dataset/images/train/s56189_salvador_sanchez_170.jpg...

 47%|████▋     | 540/1137 [28:29<29:32,  2.97s/it]

Done.
Downloading 1cBI_GHcAKWgigIsMmL77SwFpVWGK8JUJ into /content/dataset/images/train/41932688_Simon_Revello_2.png...

 48%|████▊     | 541/1137 [28:33<33:05,  3.33s/it]

Done.
Downloading 1dQrlbBQy-kEBr-qH9f9l5hB0vNSa9PgP into /content/dataset/images/train/43237686_Constantino_Ferrucci_16.png...

 48%|████▊     | 542/1137 [28:36<31:03,  3.13s/it]

Done.
Downloading 1LH4yQJEkl8cN3zm7crIEZMynZcG5rGCX into /content/dataset/images/train/37524_augusto_farias_19.jpg...

 48%|████▊     | 543/1137 [28:40<33:34,  3.39s/it]

Done.
Downloading 1r_SM4aJ-NGJ8qr8EdQKPPFqCcN1hpgAr into /content/dataset/images/train/58491_fabio_giampaoli_04.png...

 48%|████▊     | 544/1137 [28:45<39:22,  3.98s/it]

Done.
Downloading 1oYc-mJt-G_tPOeqcy__X1GkMt8RUzPhe into /content/dataset/images/train/704df12de98b3996baf45a004c5ae6b7.png...

 48%|████▊     | 545/1137 [28:48<36:09,  3.66s/it]

Done.
Downloading 1Gg1Iplc4-GVWkRgZdRyKYwyfKgl_wDL1 into /content/dataset/images/train/gravifiorino_6.jpeg...

 48%|████▊     | 546/1137 [28:50<31:29,  3.20s/it]

Done.
Downloading 1fk6qQM1XuQZWI5gfAzMJMFKsMbeg7CIG into /content/dataset/images/train/46019_taiel_raffaeli_16.jpg...

 48%|████▊     | 547/1137 [28:53<30:20,  3.08s/it]

Done.
Downloading 1wyfY-pltEYOoOo6rmE0ukthIe_QQCECW into /content/dataset/images/train/37524_augusto_farias_20.jpg...

 48%|████▊     | 548/1137 [28:58<34:53,  3.55s/it]

Done.
Downloading 1-3K41-CluS8Dtwao-j0VvbPY8H-I28YF into /content/dataset/images/train/58491_fabio_giampaoli_13.png...

 48%|████▊     | 549/1137 [29:03<40:03,  4.09s/it]

Done.
Downloading 11uOt7xIkoolH3B6XT67Muq4uxFBVwuNM into /content/dataset/images/train/s56189_salvador_sanchez_30.jpg...

 48%|████▊     | 550/1137 [29:05<34:15,  3.50s/it]

Done.
Downloading 1dMTawhBbyWQGve2jC9jZagF9KmmRCCZx into /content/dataset/images/train/43237686_Constantino_Ferrucci_34.png...

 48%|████▊     | 551/1137 [29:08<31:23,  3.21s/it]

Done.
Downloading 18Acm71ZiFrg5Og_IBa7Tg9zFT_fK4pdm into /content/dataset/images/train/43265_Lucas_Demarre_26.jpg...

 49%|████▊     | 552/1137 [29:11<30:26,  3.12s/it]

Done.
Downloading 1SVzO5jkuBq2TBnQQpf75xP3bjvnJZzF0 into /content/dataset/images/train/R-45489_sofiarondini_11.png...

 49%|████▊     | 553/1137 [29:14<29:06,  2.99s/it]

Done.
Downloading 1XQ0Hwq1cct5h7B3p-E9zrFG8aVUAvYdM into /content/dataset/images/train/f37478_santiago_ferrero_10.jpg...

 49%|████▊     | 554/1137 [29:16<27:07,  2.79s/it]

Done.
Downloading 1L5v_mc2NxuMFjJgFTNkj6Q-l8_uPqPY8 into /content/dataset/images/train/s56804_alexis_segui_26.png...

 49%|████▉     | 555/1137 [29:18<26:15,  2.71s/it]

Done.
Downloading 1d1pSiMp9lqH8vYYby62jWnUwC9fInc79 into /content/dataset/images/train/37494_gustavo_fontana_26.jpg...

 49%|████▉     | 556/1137 [29:22<28:03,  2.90s/it]

Done.
Downloading 1imfqhhyvL-23NhT-Sl80sIWWSNH8ckIL into /content/dataset/images/train/S57061_Leandro_Salvana_48.png...

 49%|████▉     | 557/1137 [29:24<27:19,  2.83s/it]

Done.
Downloading 1DxCkLNXG_w1ve9A7Jtxa4ZF5z5csJhY8 into /content/dataset/images/train/g5845_gravifiorino_26.jpeg...

 49%|████▉     | 558/1137 [29:26<25:14,  2.62s/it]

Done.
Downloading 13EH0VEWPD_OOgFPgKaqsY1YhGl9A10wR into /content/dataset/images/train/s56189_salvador_sanchez_46.jpg...

 49%|████▉     | 559/1137 [29:29<23:49,  2.47s/it]

Done.
Downloading 1O3uKTPhH3TTr1kMDt-Cjq0OzVepd72dp into /content/dataset/images/train/f0d56e748d2ce35cefdc7070da1d56eb.png...

 49%|████▉     | 560/1137 [29:32<26:09,  2.72s/it]

Done.
Downloading 1cleTOd3vWUjUs_FKg8gCL4oTSWiMycma into /content/dataset/images/train/46094_Mateo_Rovere_2.png...

 49%|████▉     | 561/1137 [29:35<25:43,  2.68s/it]

Done.
Downloading 1iFm5-O7aS1nhQNfgWcWOXLIbux5NKATn into /content/dataset/images/train/s56804_alexis_segui_24.png...

 49%|████▉     | 562/1137 [29:37<25:33,  2.67s/it]

Done.
Downloading 1_R4jgdw8Fx0vsi3F0xcec32X06n_ot5k into /content/dataset/images/train/w05576_juan_wagner_05.png...

 50%|████▉     | 563/1137 [29:40<25:47,  2.70s/it]

Done.
Downloading 12WTrPP-1FnvObvM6Q5BYkf4WWwvp7cq1 into /content/dataset/images/train/58491_fabio_giampaoli_28.png...

 50%|████▉     | 564/1137 [29:46<34:23,  3.60s/it]

Done.
Downloading 1RD9J4kqixbQa7_noQaQMmIkHYOt3kCbJ into /content/dataset/images/train/L32531_santiago_loza_10.jpg...

 50%|████▉     | 565/1137 [29:48<32:04,  3.36s/it]

Done.
Downloading 1sqwYMwHGOXn1QzfxsPrNF1aL9hUYlD_l into /content/dataset/images/train/P_51977_martin_perrone_17.png...

 50%|████▉     | 566/1137 [29:52<33:10,  3.49s/it]

Done.
Downloading 1X7E1ETRWuwdC0kUoSTvmv8N-UT7M4ufq into /content/dataset/images/train/s56189_salvador_sanchez_273.jpg...

 50%|████▉     | 567/1137 [29:54<29:07,  3.07s/it]

Done.
Downloading 1K2B7wu8oVL0BAyfhInhWf-5wuCxAOgCG into /content/dataset/images/train/51705_micaela_pozzo_12.png...

 50%|████▉     | 568/1137 [29:57<28:20,  2.99s/it]

Done.
Downloading 1QdURWHK1P1716WrYKPp2m1Pg2e6UNjsJ into /content/dataset/images/train/s56189_salvador_sanchez_169.jpg...

 50%|█████     | 569/1137 [29:59<26:12,  2.77s/it]

Done.
Downloading 1B8ZsDwDl2K5cKaHBydkEcm1xf9HBnsnt into /content/dataset/images/train/s56804_alexis_segui_22.png...

 50%|█████     | 570/1137 [30:02<25:02,  2.65s/it]

Done.
Downloading 1HUm0TmmtcWrm2JPJdKz8S5Qcu65yMeu_ into /content/dataset/images/train/R-45489_sofiarondini_27.png...

 50%|█████     | 571/1137 [30:04<24:02,  2.55s/it]

Done.
Downloading 1w0XQ-aixT4VRQ05sGW5BXZoOKzdZ70mR into /content/dataset/images/train/w05576_juan_wagner_22.png...

 50%|█████     | 572/1137 [30:07<23:57,  2.54s/it]

Done.
Downloading 1fG4Ou8Omi-Itn0U2e1s0bcVYAzPtMRpx into /content/dataset/images/train/e746942882758cb958e53400f52eb9c8.png...

 50%|█████     | 573/1137 [30:09<24:47,  2.64s/it]

Done.
Downloading 1T0oThqjEopnKQpGClKt1P0JF9WdDVlgx into /content/dataset/images/train/bc651e3a871021e2225e2de9702fbb72.png...

 50%|█████     | 574/1137 [30:13<26:16,  2.80s/it]

Done.
Downloading 1JNmfSMAoJU8fQBpCGzIr6zcWdZmal1lL into /content/dataset/images/train/s56189_salvador_sanchez_63.jpg...

 51%|█████     | 575/1137 [30:15<24:53,  2.66s/it]

Done.
Downloading 1EhErdIOGlEdRO3z1UdapDEXzPODMnzlE into /content/dataset/images/train/03531_mirian_yanez_05.jpeg...

 51%|█████     | 576/1137 [30:18<24:45,  2.65s/it]

Done.
Downloading 1EGZltLbmLUckQqmk9m6LWxwdQWdO-k2P into /content/dataset/images/train/L32425_eugenio_lopez_25.png...

 51%|█████     | 577/1137 [30:21<26:25,  2.83s/it]

Done.
Downloading 1HwZ4F70gMsTbouOZsU_MzGXcbKIMXfZ4 into /content/dataset/images/train/F37605_florencia_fernandez_50.png...

 51%|█████     | 578/1137 [30:24<27:20,  2.94s/it]

Done.
Downloading 1lowQAn4VZYVoAqkAcWg4erMSMMiU9J7w into /content/dataset/images/train/37524_augusto_farias_16.jpg...

 51%|█████     | 579/1137 [30:28<29:32,  3.18s/it]

Done.
Downloading 1UHLIn7ms_kd_H8-rrzZGpLZGLqSjY76v into /content/dataset/images/train/F37605_florencia_fernandez_05.png...

 51%|█████     | 580/1137 [30:30<27:10,  2.93s/it]

Done.
Downloading 1XiLpIdwDgpZreeib4sPyZS0rvRio-yFZ into /content/dataset/images/train/s56189_salvador_sanchez_282.jpg...

 51%|█████     | 581/1137 [30:33<25:48,  2.79s/it]

Done.
Downloading 1oRPktKiQyBptoZm3cm1Zw_KlNTuvo__C into /content/dataset/images/train/37524_augusto_farias_12.jpg...

 51%|█████     | 582/1137 [30:37<29:08,  3.15s/it]

Done.
Downloading 1VRTOitp2dUEms0YTIwn-mxYx1v49EakJ into /content/dataset/images/train/03531_mirian_yanez_07.jpeg...

 51%|█████▏    | 583/1137 [30:39<26:41,  2.89s/it]

Done.
Downloading 1Oul6SFyA7G08X1MSw0CNA-DWPMVVszOb into /content/dataset/images/train/37494_gustavo_fontana_09.jpg...

 51%|█████▏    | 584/1137 [30:42<27:29,  2.98s/it]

Done.
Downloading 1JyvKUj4d_h4-DFiu0C7OCVW-Qui-wnd4 into /content/dataset/images/train/s56189_salvador_sanchez_74.jpg...

 51%|█████▏    | 585/1137 [30:44<26:03,  2.83s/it]

Done.
Downloading 1oALRp8BfH80luLiXauff-wjr06qcyWLc into /content/dataset/images/train/F37605_florencia_fernandez_27.png...

 52%|█████▏    | 586/1137 [30:47<24:36,  2.68s/it]

Done.
Downloading 1Q0zV4fMR88XWBhQ6gDkuOgES_60pFHK- into /content/dataset/images/train/s56189_salvador_sanchez_157.jpg...

 52%|█████▏    | 587/1137 [30:49<24:11,  2.64s/it]

Done.
Downloading 1s02Bnk3CM4NlxxJf4M_3LJv3sssBV0Tj into /content/dataset/images/train/46019_taiel_raffaeli_21.jpg...

 52%|█████▏    | 588/1137 [30:52<24:34,  2.69s/it]

Done.
Downloading 1MiUXd4Vhc7J59kOSfUxTZPtxiABHvGoJ into /content/dataset/images/train/46094_Mateo_Rovere_4.png...

 52%|█████▏    | 589/1137 [30:55<23:56,  2.62s/it]

Done.
Downloading 10_FL6YFxEvNSjZZ3LPDw0UhcRTFbKJbD into /content/dataset/images/train/52256_daniel_ponce_26.jpeg...

 52%|█████▏    | 590/1137 [30:58<24:46,  2.72s/it]

Done.
Downloading 15qAmWB6PQ53i1sAb01M07E35lC756W9X into /content/dataset/images/train/g5845_gravifiorino_21.jpeg...

 52%|█████▏    | 591/1137 [31:00<23:36,  2.59s/it]

Done.
Downloading 1O0jbv4xDfgFfSLzc9WbuQNgw0tovnFPT into /content/dataset/images/train/s56189_salvador_sanchez_132.jpg...

 52%|█████▏    | 592/1137 [31:02<22:19,  2.46s/it]

Done.
Downloading 1c9WHjuzDnr_Jh4v3pdGt1kwJoJ5eOtaU into /content/dataset/images/train/F37605_florencia_fernandez_03.png...

 52%|█████▏    | 593/1137 [31:04<22:21,  2.47s/it]

Done.
Downloading 1Y7P09g7UIeoYf4h0_2NyRcYkYm7gIf5Y into /content/dataset/images/train/s56189_salvador_sanchez_286.jpg...

 52%|█████▏    | 594/1137 [31:07<22:09,  2.45s/it]

Done.
Downloading 1J5EG9Ezw8gAAt_di6PFcOqUGAVLAZA8p into /content/dataset/images/train/58912_Timoteo_Garcia_8.jpg...

 52%|█████▏    | 595/1137 [31:10<22:53,  2.53s/it]

Done.
Downloading 1bDURU0MjEhPD9LYGt7HB2X5CLrHoRUHK into /content/dataset/images/train/12394_escandell_ariel_31.jpg...

 52%|█████▏    | 596/1137 [31:13<23:54,  2.65s/it]

Done.
Downloading 1qlsUT5YLMhsQRJF3x-tGP-o0D5X4Qpbj into /content/dataset/images/train/w05576_juan_wagner_28.png...

 53%|█████▎    | 597/1137 [31:15<24:10,  2.69s/it]

Done.
Downloading 1XA1wpqrNqn9-0_NGxW8rl4pvpCLKiE_t into /content/dataset/images/train/03531_mirian_yanez_18.jpeg...

 53%|█████▎    | 598/1137 [31:18<23:18,  2.59s/it]

Done.
Downloading 1XXoBIWu2NnWyVavUiXoiGo83vL_3e-kC into /content/dataset/images/train/L32425_eugenio_lopez_21.png...

 53%|█████▎    | 599/1137 [31:22<28:50,  3.22s/it]

Done.
Downloading 1LGBQyV5m7PfIaFNPe7J20dD4zRW_H0uu into /content/dataset/images/train/s56189_salvador_sanchez_88.jpg...

 53%|█████▎    | 600/1137 [31:25<26:31,  2.96s/it]

Done.
Downloading 1Tkb82pXpiizW5F3SNU9GO_uiSt3dkr3P into /content/dataset/images/train/s56189_salvador_sanchez_216.jpg...

 53%|█████▎    | 601/1137 [31:27<24:34,  2.75s/it]

Done.
Downloading 1GznYlOmDi5YRMsTxV6v3X57DBbKL865S into /content/dataset/images/train/37524_augusto_farias_21.jpg...

 53%|█████▎    | 602/1137 [31:32<29:48,  3.34s/it]

Done.
Downloading 1aca7ihxCn7ACrRoA5S9UEgysZ9DglxjZ into /content/dataset/images/train/43841031_Enzo_Ferrari_38.png...

 53%|█████▎    | 603/1137 [31:35<30:30,  3.43s/it]

Done.
Downloading 1kxaOM12t_cto798HgYOUCpxC-PdiCDaO into /content/dataset/images/train/51659_antonio_peroni_03.jpg...

 53%|█████▎    | 604/1137 [31:39<30:11,  3.40s/it]

Done.
Downloading 1nkUeqc1G38GhvrA2gDXWvv_D-UPzlprf into /content/dataset/images/train/L32531_santiago_loza_36.jpg...

 53%|█████▎    | 605/1137 [31:42<28:56,  3.26s/it]

Done.
Downloading 1hYM9Sxn0C2XUz4tkbPygu21MgtP70tKh into /content/dataset/images/train/s56189_salvador_sanchez_0.jpg...

 53%|█████▎    | 606/1137 [31:44<26:24,  2.98s/it]

Done.
Downloading 12ETXq10EVaJ9n6Og_GqaoDlNCBIVFWOn into /content/dataset/images/train/s56189_salvador_sanchez_32.jpg...

 53%|█████▎    | 607/1137 [31:46<24:32,  2.78s/it]

Done.
Downloading 1vXIv7SSVf8pq-JxVHCm9fpnsnnCAbWGM into /content/dataset/images/train/51934_pablo_pistelli_03.png...

 53%|█████▎    | 608/1137 [31:51<30:02,  3.41s/it]

Done.
Downloading 1P1cD7H8HPv78S5zOyr2LUABA9HqDJKfK into /content/dataset/images/train/g5845_gravifiorino_8.jpeg...

 54%|█████▎    | 609/1137 [31:53<26:41,  3.03s/it]

Done.
Downloading 1fzFE82wP8NonOvax1RM2hTQ-kqvYmNn7 into /content/dataset/images/train/46019_taiel_raffaeli_18.jpg...

 54%|█████▎    | 610/1137 [31:56<26:49,  3.05s/it]

Done.
Downloading 1O9DDPX96K1ZpyzElmawT2Z21zDPwuE_D into /content/dataset/images/train/43237686_Constantino_Ferrucci_17.png...

 54%|█████▎    | 611/1137 [32:00<27:33,  3.14s/it]

Done.
Downloading 15uxE7onN89zjlRNHlAQ5ZwbqOi8G2i9s into /content/dataset/images/train/R-45489_sofiarondini_14.png...

 54%|█████▍    | 612/1137 [32:03<26:48,  3.06s/it]

Done.
Downloading 1VCE2npBjUsvvRQZTcg6rDWB6fz8KUYuU into /content/dataset/images/train/A45161_Fabian_Aguirre_22.png...

 54%|█████▍    | 613/1137 [32:06<27:11,  3.11s/it]

Done.
Downloading 1qev3QpCGCHo69OMCndoxxN-9P6xjYZuB into /content/dataset/images/train/L32425_eugenio_lopez_06.png...

 54%|█████▍    | 614/1137 [32:09<27:46,  3.19s/it]

Done.
Downloading 19Kea8ZQsa_rkKAIAvWNcifRO9CxzdcOj into /content/dataset/images/train/23451_guido_lorenzettibruera_18.jpg...

 54%|█████▍    | 615/1137 [32:14<30:36,  3.52s/it]

Done.
Downloading 16bl01sJu0x2KfsPqPoDy4PCkwnVM7n3j into /content/dataset/images/train/51934_pablo_pistelli_23.png...

 54%|█████▍    | 616/1137 [32:18<31:58,  3.68s/it]

Done.
Downloading 1QgWsVRIHwEZVKKLh36eyUgkuJYn8Wrkk into /content/dataset/images/train/51934_pablo_pistelli_13.png...

 54%|█████▍    | 617/1137 [32:23<35:22,  4.08s/it]

Done.
Downloading 18FnQY0dxrAmTsL7IJow0CdmEVGby0Lfb into /content/dataset/images/train/51705_micaela_pozzo_10.png...

 54%|█████▍    | 618/1137 [32:25<32:00,  3.70s/it]

Done.
Downloading 1Ib4Z8fwMvjL0D-4fNVqP-KM66XnvnGFK into /content/dataset/images/train/s56189_salvador_sanchez_50.jpg...

 54%|█████▍    | 619/1137 [32:28<28:18,  3.28s/it]

Done.
Downloading 1Ioj6DDk5zN4a4ZpIwymVLH4-YIXV7DNJ into /content/dataset/images/train/s56189_salvador_sanchez_52.jpg...

 55%|█████▍    | 620/1137 [32:30<26:15,  3.05s/it]

Done.
Downloading 14pfY3x-lGjAJhPdqy6nym345U5PkkNfM into /content/dataset/images/train/23451_guido_lorenzettibruera_21.jpg...

 55%|█████▍    | 621/1137 [32:36<32:01,  3.72s/it]

Done.
Downloading 1hYgluKYZIaLFQzNW--GetU6SRxFoNHpY into /content/dataset/images/train/71846_Brisa_Menescaldi_06.png...

 55%|█████▍    | 622/1137 [32:40<34:25,  4.01s/it]

Done.
Downloading 13QCgXetTM3b17sJBZ1NEajVMTFSwvZ6k into /content/dataset/images/train/P51951_pablo_pistarelli_02.png...

 55%|█████▍    | 623/1137 [32:43<31:41,  3.70s/it]

Done.
Downloading 16IuyKxJUBleNDetdpPt0sApU6Tbcreap into /content/dataset/images/train/41932688_Simon_Revello_21.png...

 55%|█████▍    | 624/1137 [32:53<47:12,  5.52s/it]

Done.
Downloading 1Kr11e-klbuY7QM3stXqhewUl3uBVFFNM into /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_28.jpg...

 55%|█████▍    | 625/1137 [32:56<40:46,  4.78s/it]

Done.
Downloading 1Q2ImFXAHHYrr6_qkF_VW7SYPRkdVIZQb into /content/dataset/images/train/9154c720580a0731da24f5bccb89b757.png...

 55%|█████▌    | 626/1137 [32:59<35:44,  4.20s/it]

Done.
Downloading 152ScD9BrbJlZcm8LMPrH75pvci2aMJkv into /content/dataset/images/train/58912_Timoteo_Garcia_15.jpg...

 55%|█████▌    | 627/1137 [33:02<32:44,  3.85s/it]

Done.
Downloading 1Zf0a_jha4lx74Bspb9AfPpTCbnCDPiH2 into /content/dataset/images/train/F37605_florencia_fernandez_39.png...

 55%|█████▌    | 628/1137 [33:05<30:55,  3.65s/it]

Done.
Downloading 1NQC5Fv11U9Kr6ExZ2gBh-ZCqGeEkTuTH into /content/dataset/images/train/P_51977_martin_perrone_19.png...

 55%|█████▌    | 629/1137 [33:09<31:52,  3.76s/it]

Done.
Downloading 18eXJxIao_yuc-0Tw3QVyopTRbTwXaE5A into /content/dataset/images/train/23451_guido_lorenzettibruera_11.jpg...

 55%|█████▌    | 630/1137 [33:14<35:07,  4.16s/it]

Done.
Downloading 1Ll9X9R7jWkJdo5YeDOZJOMsrqsVk2u7g into /content/dataset/images/train/L32531_santiago_loza_34.jpg...

 55%|█████▌    | 631/1137 [33:18<34:49,  4.13s/it]

Done.
Downloading 1Pw65U8ir0m9WsbVJidufyWh40miOSErZ into /content/dataset/images/train/s56189_salvador_sanchez_155.jpg...

 56%|█████▌    | 632/1137 [33:21<30:08,  3.58s/it]

Done.
Downloading 1LAITw3ylbkWYAJbGPzTKvA1r_34amqcf into /content/dataset/images/train/s56189_salvador_sanchez_82.jpg...

 56%|█████▌    | 633/1137 [33:23<26:51,  3.20s/it]

Done.
Downloading 1FunTFS7B3zA1Khm_kpc6SLTEWZnnoJCk into /content/dataset/images/train/A45161_Fabian_Aguirre_02.png...

 56%|█████▌    | 634/1137 [33:26<26:39,  3.18s/it]

Done.
Downloading 18fEaX6hiayamsWa88jCE_P0_4AwUV8MQ into /content/dataset/images/train/12394_escandell_ariel_24.jpg...

 56%|█████▌    | 635/1137 [33:29<26:35,  3.18s/it]

Done.
Downloading 1lXDXjAwg2pnEl9hrZmeleCRI5BQ81yJn into /content/dataset/images/train/12394_escandell_ariel_01.jpg...

 56%|█████▌    | 636/1137 [33:32<25:48,  3.09s/it]

Done.
Downloading 1MPr4tqEOJx9BOdrxQEc_ooqA1Irjuovv into /content/dataset/images/train/51659_antonio_peroni_15.jpg...

 56%|█████▌    | 637/1137 [33:35<25:22,  3.05s/it]

Done.
Downloading 1bQOs_Y0xIgeIoqoz3b6TGh7gxw6cCvZZ into /content/dataset/images/train/37524_augusto_farias_13.jpg...

 56%|█████▌    | 638/1137 [33:39<28:43,  3.45s/it]

Done.
Downloading 1U_jKEKj65YEA3RDDuwm4yJKIjli9tGwr into /content/dataset/images/train/71846_Brisa_Menescaldi_05.png...

 56%|█████▌    | 639/1137 [34:10<1:35:36, 11.52s/it]

Done.
Downloading 1V8cxCDgvk-7Glo1KlcApC8e-nhxnEsJG into /content/dataset/images/train/52256_daniel_ponce_22.jpeg...

 56%|█████▋    | 640/1137 [34:13<1:14:20,  8.98s/it]

Done.
Downloading 10rbYgOQEk38XW8nJ61nm2EHXs2RyvT2E into /content/dataset/images/train/12394_escandell_ariel_09.jpg...

 56%|█████▋    | 641/1137 [34:15<58:15,  7.05s/it]

Done.
Downloading 14T-nION5J2ReyMEJNMG1kWCDX0rPN2-o into /content/dataset/images/train/57096_ramiro_sagrera_12.jpg...

 56%|█████▋    | 642/1137 [34:19<49:31,  6.00s/it]

Done.
Downloading 1nBWPZamjEMi5tHqa-dQN7xerxWGa9lTA into /content/dataset/images/train/71846_Brisa_Menescaldi_03.png...

 57%|█████▋    | 643/1137 [34:19<35:47,  4.35s/it]

Done.
Downloading 1aMW9uViX6WhDG15b5TAeeEgDrxVOTvgr into /content/dataset/images/train/43841031_Enzo_Ferrari_17.png...

 57%|█████▋    | 644/1137 [34:22<32:01,  3.90s/it]

Done.
Downloading 1t2hOznuRYqLjxyVVDpfDR9jd4ku74A0n into /content/dataset/images/train/72125_miguel_mussi_08.png...

 57%|█████▋    | 645/1137 [34:54<1:41:39, 12.40s/it]

Done.
Downloading 1Vz9gXPEGGfqYCzWYirZ2bSxTANj7QyBb into /content/dataset/images/train/s56189_salvador_sanchez_247.jpg...

 57%|█████▋    | 646/1137 [34:57<1:16:28,  9.35s/it]

Done.
Downloading 1cF85zTyM3gAhGovovG4XYW6tVEnyuwB6 into /content/dataset/images/train/g5845_gravifiorino_23.jpeg...

 57%|█████▋    | 647/1137 [35:00<1:00:38,  7.43s/it]

Done.
Downloading 1goUzVZN_LM4JZC0cngI_U2Ql9_ATuOxf into /content/dataset/images/train/R-45489_sofiarondini_21.png...

 57%|█████▋    | 648/1137 [35:02<48:20,  5.93s/it]

Done.
Downloading 1QWaY7CDy4zTAaYVqexcatENVnS1EbHWt into /content/dataset/images/train/R-45829_Abril_Rodriguez_14.png...

 57%|█████▋    | 649/1137 [35:04<39:13,  4.82s/it]

Done.
Downloading 1VskeQKXNSJ0SnTk1tl6sDJ50qmfe4cq7 into /content/dataset/images/train/51659_antonio_peroni_02.jpg...

 57%|█████▋    | 650/1137 [35:07<34:59,  4.31s/it]

Done.
Downloading 1Om3RoZBXuF2RUZL8Ud3mCilohWY9bkyd into /content/dataset/images/train/s56189_salvador_sanchez_142.jpg...

 57%|█████▋    | 651/1137 [35:10<30:34,  3.78s/it]

Done.
Downloading 1fZ5SeMTZYsZRxXUt0laLYr9lnid07n33 into /content/dataset/images/train/57096_ramiro_sagrera_26.jpg...

 57%|█████▋    | 652/1137 [35:13<29:37,  3.67s/it]

Done.
Downloading 1wJsZAfsZvxWs0jO-TFyCMhlD3whT1gED into /content/dataset/images/train/L32425_eugenio_lopez_22.png...

 57%|█████▋    | 653/1137 [35:17<28:28,  3.53s/it]

Done.
Downloading 12yWmAkcHCDCceBnuGpUYxrAvVyhJPbkg into /content/dataset/images/train/s56189_salvador_sanchez_43.jpg...

 58%|█████▊    | 654/1137 [35:19<25:09,  3.13s/it]

Done.
Downloading 1RdsXSMQQX2TgoPqWo4TaTQ4X8YKEhScv into /content/dataset/images/train/58513_isaias_garay_20.png...

 58%|█████▊    | 655/1137 [35:21<23:29,  2.92s/it]

Done.
Downloading 1FncVip8Rq9EzZylRE-q4YPZICWu5r9_G into /content/dataset/images/train/58491_fabio_giampaoli_05.png...

 58%|█████▊    | 656/1137 [35:30<38:09,  4.76s/it]

Done.
Downloading 1_vcNBgexddR-rKHJbe6ivM6zZXDhcSO4 into /content/dataset/images/train/12394_escandell_ariel_19.jpg...

 58%|█████▊    | 657/1137 [35:34<35:13,  4.40s/it]

Done.
Downloading 1QRBvbftXkXJop0EeSFJoTovZJcXRwJud into /content/dataset/images/train/s56189_salvador_sanchez_161.jpg...

 58%|█████▊    | 658/1137 [35:36<30:08,  3.78s/it]

Done.
Downloading 1FvK8FX0xbqW6Vr5hrhAjJtg4-dVMbSzj into /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_10.jpg...

 58%|█████▊    | 659/1137 [35:37<22:10,  2.78s/it]

Done.
Downloading 1o_7McoT-AL6u300VnPFe_goMi38D3LOj into /content/dataset/images/train/51934_pablo_pistelli_11.png...

 58%|█████▊    | 660/1137 [35:42<28:16,  3.56s/it]

Done.
Downloading 1NxDcGSf4xalzl-NwMx9j4ELJ4ps1iqCU into /content/dataset/images/train/s56189_salvador_sanchez_130.jpg...

 58%|█████▊    | 661/1137 [35:44<24:35,  3.10s/it]

Done.
Downloading 1SFkM2okqU0_9HzPc7Iu-_HllvZwnVX79 into /content/dataset/images/train/37524_augusto_farias_24.jpg...

 58%|█████▊    | 662/1137 [35:49<28:43,  3.63s/it]

Done.
Downloading 12xWs4eYkB6RsW51r03PNCBriXEazHIAY into /content/dataset/images/train/37524_augusto_farias_23.jpg...

 58%|█████▊    | 663/1137 [35:53<30:36,  3.88s/it]

Done.
Downloading 1LN51tNNxYGm1s4MsMUIvoR53xVlkn5cH into /content/dataset/images/train/s56189_salvador_sanchez_92.jpg...

 58%|█████▊    | 664/1137 [35:56<27:07,  3.44s/it]

Done.
Downloading 1pqAWL5UBos1lwTuzA1wmCd1sqhk2sE8Z into /content/dataset/images/train/s56804_alexis_segui_17.png...

 58%|█████▊    | 665/1137 [35:58<25:27,  3.24s/it]

Done.
Downloading 1LsN7fUBMBfjGlk9b7CzM7stK24dFiKsD into /content/dataset/images/train/P_51977_martin_perrone_24.png...

 59%|█████▊    | 666/1137 [36:03<27:25,  3.49s/it]

Done.
Downloading 1WdHbUg6yR1HJEMtNgBcok8wJMnuP_8cF into /content/dataset/images/train/g5845_gravifiorino_14.jpeg...

 59%|█████▊    | 667/1137 [36:05<24:19,  3.10s/it]

Done.
Downloading 1A4WzEWuFO8by5brlwz-0P7-9PQjiu7tG into /content/dataset/images/train/A45161_Fabian_Aguirre_11.png...

 59%|█████▉    | 668/1137 [36:08<24:49,  3.18s/it]

Done.
Downloading 1ePR6IWvGnZvxf8ez_IdTFCwX9KhR2QxS into /content/dataset/images/train/51705_micaela_pozzo_04.png...

 59%|█████▉    | 669/1137 [36:11<24:16,  3.11s/it]

Done.
Downloading 1n58XXEUCXXOqkWx6A30jTqpZaUUHgmuW into /content/dataset/images/train/f37478_santiago_ferrero_37.jpg...

 59%|█████▉    | 670/1137 [36:13<22:24,  2.88s/it]

Done.
Downloading 16dfY1YOLIkF2IXlfJk3Rt8GGutJlDCSq into /content/dataset/images/train/s56189_salvador_sanchez_1.jpg...

 59%|█████▉    | 671/1137 [36:16<21:20,  2.75s/it]

Done.
Downloading 16PNk4RFlWxhxaC_3grzOJ_gPLk_wu1ok into /content/dataset/images/train/gravifiorino_10.jpeg...

 59%|█████▉    | 672/1137 [36:18<20:28,  2.64s/it]

Done.
Downloading 1Ry--wMxT5TnE1vL7r2QwM8IR5uodog-d into /content/dataset/images/train/43237686_Constantino_Ferrucci_3.png...

 59%|█████▉    | 673/1137 [36:21<20:33,  2.66s/it]

Done.
Downloading 1rWwqs7vob_VffAv013SnAQZviWErlHt1 into /content/dataset/images/train/58513_isaias_garay_12.png...

 59%|█████▉    | 674/1137 [36:23<20:13,  2.62s/it]

Done.
Downloading 1XoCvzWf21eLVtZnSiDvYLp_BxI8UW_x4 into /content/dataset/images/train/R-45829_Abril_Rodriguez_12.png...

 59%|█████▉    | 675/1137 [36:26<20:16,  2.63s/it]

Done.
Downloading 1PjHRMk1dTKgrUI_3akeQoQbk4SLWnXjO into /content/dataset/images/train/s56189_salvador_sanchez_153.jpg...

 59%|█████▉    | 676/1137 [36:27<15:09,  1.97s/it]

Done.
Downloading 1fonNVfaMnDWLOZB6HK6xR-N_OZpI0QVu into /content/dataset/images/train/43237686_Constantino_Ferrucci_26.png...

 60%|█████▉    | 677/1137 [36:30<18:30,  2.42s/it]

Done.
Downloading 15o4uXY76wvNGEFA9FVK4bhXfzG1_5rVN into /content/dataset/images/train/2321cd43cc466e7f778598d05b07889c.png...

 60%|█████▉    | 678/1137 [36:40<35:49,  4.68s/it]

Done.
Downloading 1ZVATnSfY-iDfjyjHPG06MRPTt5zVO0o3 into /content/dataset/images/train/52256_daniel_ponce_18.jpeg...

 60%|█████▉    | 679/1137 [36:45<35:40,  4.67s/it]

Done.
Downloading 1FPYW8VOtT4TVtshzCf_SsdtsJqB4wvT9 into /content/dataset/images/train/71846_Brisa_Menescaldi_19.png...

 60%|█████▉    | 680/1137 [36:49<35:41,  4.69s/it]

Done.
Downloading 1lk310aMj6wo-_TVDW-nHHuFL4QI5panr into /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_07.jpg...

 60%|█████▉    | 681/1137 [36:52<31:21,  4.13s/it]

Done.
Downloading 1dMj4GAbGRKzpss_xTnk6mXyTJeOPPIH1 into /content/dataset/images/train/f37478_santiago_ferrero_13.jpg...

 60%|█████▉    | 682/1137 [36:56<30:08,  3.98s/it]

Done.
Downloading 1VuY_gLOgSfFjsAJ5sKxbmX87wHOPkrL5 into /content/dataset/images/train/s56189_salvador_sanchez_249.jpg...

 60%|██████    | 683/1137 [36:58<26:11,  3.46s/it]

Done.
Downloading 1csjHv3dbFGArRJ_qTJnAdb9cqSmad_xv into /content/dataset/images/train/dcf7b17157fb40fa0f6f0e7ed5e6c820.png...

 60%|██████    | 684/1137 [37:01<26:00,  3.44s/it]

Done.
Downloading 1uCy4asVBabhwTxlNXD0vlCrTWKAD8_PK into /content/dataset/images/train/46019_taiel_raffaeli_27.jpg...

 60%|██████    | 685/1137 [37:04<24:47,  3.29s/it]

Done.
Downloading 1xYYzZ7VYQQ4LrfA_twmk4JtJK8pemXoB into /content/dataset/images/train/58912_Timoteo_Garcia_19.jpg...

 60%|██████    | 686/1137 [37:07<24:07,  3.21s/it]

Done.
Downloading 1jkzZ7XOk5CCTJ-ci33iEDIfvxlL6pKYk into /content/dataset/images/train/58513_isaias_garay_05.png...

 60%|██████    | 687/1137 [37:10<22:35,  3.01s/it]

Done.
Downloading 1Apv7sj_IDoNrgYYat3dPSxQ75Xx4a-YO into /content/dataset/images/train/596d7f50336efa3134c558fb532fced7.png...

 61%|██████    | 688/1137 [37:13<21:59,  2.94s/it]

Done.
Downloading 17eWW3l-BI8FUAutkC5tASGOYK0dLiWoo into /content/dataset/images/train/f37478_santiago_ferrero_06.jpg...

 61%|██████    | 689/1137 [37:13<16:11,  2.17s/it]

Done.
Downloading 1370_t1y19OyllSkxasEkSifz-M5twGyd into /content/dataset/images/train/s56189_salvador_sanchez_45.jpg...

 61%|██████    | 690/1137 [37:13<12:09,  1.63s/it]

Done.
Downloading 1tlfBt_bZxY2cXfdzMva9AbYZpmAQBgVj into /content/dataset/images/train/43841031_Enzo_Ferrari_31.png...

 61%|██████    | 691/1137 [37:18<18:48,  2.53s/it]

Done.
Downloading 1Kti3g9QTjc8kU_Gz8dQTwmBFmlSjXQtP into /content/dataset/images/train/51659_antonio_peroni_19.jpg...

 61%|██████    | 692/1137 [37:19<15:11,  2.05s/it]

Done.
Downloading 1L7TClZxjSB03Zqr3Elz3ZmejfP61UU-R into /content/dataset/images/train/s56189_salvador_sanchez_84.jpg...

 61%|██████    | 693/1137 [37:21<15:19,  2.07s/it]

Done.
Downloading 10wS5aMyJNoWQ9gMK0SwSRR12fUrIqxtt into /content/dataset/images/train/37524_augusto_farias_07.jpg...

 61%|██████    | 694/1137 [37:51<1:17:53, 10.55s/it]

Done.
Downloading 1MPsVBoSOIIRpltY23Uy8aH84vTr7Z57C into /content/dataset/images/train/23451_guido_lorenzettibruera_09.jpg...

 61%|██████    | 695/1137 [37:56<1:03:45,  8.65s/it]

Done.
Downloading 1B-iC_Vi289P-kT2yKYf5arswz0VjlLz_ into /content/dataset/images/train/372d73de811a362dc90c3d847788439f.png...

 61%|██████    | 696/1137 [37:58<50:35,  6.88s/it]

Done.
Downloading 1WsDbQ2g6pG3aP2jzymPyrA1rF25-4J-n into /content/dataset/images/train/L32531_santiago_loza_18.jpg...

 61%|██████▏   | 697/1137 [38:01<41:49,  5.70s/it]

Done.
Downloading 1i02h6em_HI5vlafWWE-g-9SHNSlV-rjJ into /content/dataset/images/train/s56189_salvador_sanchez_2.jpg...

 61%|██████▏   | 698/1137 [38:04<34:09,  4.67s/it]

Done.
Downloading 1j9LjfJ5MupcHzeulITxIkiRqrLPum6EJ into /content/dataset/images/train/P51926_Leonel_Palermo_30.png...

 61%|██████▏   | 699/1137 [38:08<32:46,  4.49s/it]

Done.
Downloading 1VCA2ecKxKrlhO4q32NwBVl2W8kXRKTqV into /content/dataset/images/train/s56189_salvador_sanchez_234.jpg...

 62%|██████▏   | 700/1137 [38:10<27:32,  3.78s/it]

Done.
Downloading 1pzvcyv0ijQSME1C23utXOhtAsmm98rp2 into /content/dataset/images/train/51705_micaela_pozzo_17.png...

 62%|██████▏   | 701/1137 [38:13<25:14,  3.47s/it]

Done.
Downloading 1FYuKBzQs30287l3xhtS92VvJCrCtX-jK into /content/dataset/images/train/w05576_juan_wagner_11.png...

 62%|██████▏   | 702/1137 [38:15<23:06,  3.19s/it]

Done.
Downloading 1KYrgehrM0zNO6CFjdSjEHowrLHl8j-t3 into /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_20.jpg...

 62%|██████▏   | 703/1137 [38:18<22:31,  3.11s/it]

Done.
Downloading 11NvrNxSKgmQvLD0fNSBjzsYb_bnq_ivP into /content/dataset/images/train/37524_augusto_farias_26.jpg...

 62%|██████▏   | 704/1137 [38:23<25:46,  3.57s/it]

Done.
Downloading 1m0vJPvR8B1ia1WP1tyzsXQLyrhwagfAr into /content/dataset/images/train/51951_pablo_pistarelli_10.png...

 62%|██████▏   | 705/1137 [38:25<23:49,  3.31s/it]

Done.
Downloading 1zw-yn8mlL-JM3DUVpaHQzz3qB9pUT4pm into /content/dataset/images/train/37524_augusto_farias_04.jpg...

 62%|██████▏   | 706/1137 [38:30<27:20,  3.81s/it]

Done.
Downloading 1TZR24jYzCWpzgIoQOIxP1199fzQsQX9s into /content/dataset/images/train/43237686_Constantino_Ferrucci_32.png...

 62%|██████▏   | 707/1137 [38:33<25:02,  3.49s/it]

Done.
Downloading 1g2A2ObvYF7sEIZReq37dHBwDmwrj9Hvg into /content/dataset/images/train/41932688_Simon_Revello_20.png...

 62%|██████▏   | 708/1137 [38:37<26:16,  3.68s/it]

Done.
Downloading 1PYRrAgyFjC_qEscOQ53P1aJ2HJCIPjOO into /content/dataset/images/train/52256_daniel_ponce_07.jpeg...

 62%|██████▏   | 709/1137 [38:40<24:30,  3.44s/it]

Done.
Downloading 1Lkuow7RztlQ5bujOEafG52nIruTnlU7b into /content/dataset/images/train/P51951_pablo_pistarelli_01.png...

 62%|██████▏   | 710/1137 [38:41<18:47,  2.64s/it]

Done.
Downloading 1nxET_Kjj1hMtAsHGWMH1Pjocv4hLl1zt into /content/dataset/images/train/41932688_Simon_Revello_29.png...

 63%|██████▎   | 711/1137 [38:47<25:02,  3.53s/it]

Done.
Downloading 1MCysccTHQjqMDthTLSIo_O3llM5g_XA0 into /content/dataset/images/train/F37605_florencia_fernandez_16.png...

 63%|██████▎   | 712/1137 [38:49<22:38,  3.20s/it]

Done.
Downloading 1qYCHZPRl31kIrvRnDIuflFYM8ItQYsV5 into /content/dataset/images/train/03531_mirian_yanez_03.jpeg...

 63%|██████▎   | 713/1137 [38:52<21:15,  3.01s/it]

Done.
Downloading 1dxdtDNavzMPNyCiKCv0oJhi6F9pDL1p_ into /content/dataset/images/train/71846_Brisa_Menescaldi_29.png...

 63%|██████▎   | 714/1137 [38:56<24:31,  3.48s/it]

Done.
Downloading 130LxCT9EAOaWA0_31Hh_r_FLN0pHwF4I into /content/dataset/images/train/R-45829_Abril_Rodriguez_18.png...

 63%|██████▎   | 715/1137 [38:59<23:17,  3.31s/it]

Done.
Downloading 15sMh0tVkFZeWi_UbFHjChxtu6OSl1D9O into /content/dataset/images/train/58513_isaias_garay_11.png...

 63%|██████▎   | 716/1137 [39:02<22:14,  3.17s/it]

Done.
Downloading 1OjTDXLO44bZd6XA_ivV6mlrbmi_jAuuv into /content/dataset/images/train/12394_escandell_ariel_17.jpg...

 63%|██████▎   | 717/1137 [39:07<27:10,  3.88s/it]

Done.
Downloading 1N0hCL6V0UPhaRopBw7HZT8_DRvCOFWRm into /content/dataset/images/train/s56189_salvador_sanchez_117.jpg...

 63%|██████▎   | 718/1137 [39:10<23:52,  3.42s/it]

Done.
Downloading 1hBbLy0V-fMUOXSe88P1H4ee0lfSaebG- into /content/dataset/images/train/57096_ramiro_sagrera_08.jpg...

 63%|██████▎   | 719/1137 [39:13<22:47,  3.27s/it]

Done.
Downloading 192gCMuXsY3snQM2dpstHMc867yFJXeGl into /content/dataset/images/train/g5845_gravifiorino_6.jpeg...

 63%|██████▎   | 720/1137 [39:15<20:31,  2.95s/it]

Done.
Downloading 1H-lNi67CqaEWX1htNNLitPupqERY9_Iv into /content/dataset/images/train/F37605_florencia_fernandez_28.png...

 63%|██████▎   | 721/1137 [39:17<19:11,  2.77s/it]

Done.
Downloading 1LsD_V_SVnVNI6PRBEo5ccZZDjhhUIJCA into /content/dataset/images/train/f37478_santiago_ferrero_31.jpg...

 64%|██████▎   | 722/1137 [39:20<18:45,  2.71s/it]

Done.
Downloading 1psOglScBN7NInscEJRBP1bg-R-dT15d1 into /content/dataset/images/train/R-45829_Abril_Rodriguez_04.png...

 64%|██████▎   | 723/1137 [39:20<14:06,  2.04s/it]

Done.
Downloading 1l_YnpI6mkCtsakLGFG4bRVT130xNaiSL into /content/dataset/images/train/bf02d4825b88da21f08c445ef0586e54.png...

 64%|██████▎   | 724/1137 [39:23<15:41,  2.28s/it]

Done.
Downloading 1px0RF-DvypoZ7OpTszi-YJUWBnJJgrPy into /content/dataset/images/train/43237686_Constantino_Ferrucci_18.png...

 64%|██████▍   | 725/1137 [39:26<17:37,  2.57s/it]

Done.
Downloading 1ND2g9xo8kOFvIZ4J1pbZWVzCJnuGUwKF into /content/dataset/images/train/P51926_Leonel_Palermo_16.png...

 64%|██████▍   | 726/1137 [39:31<22:41,  3.31s/it]

Done.
Downloading 1h7Ct4Xp39EIpvCXSS2ACXqZG4Pv_y0cH into /content/dataset/images/train/58491_fabio_giampaoli_14.png...

 64%|██████▍   | 727/1137 [39:35<22:26,  3.28s/it]

Done.
Downloading 15j7ZYy_35w9fJpeitppvkjJmkU4k-_Cf into /content/dataset/images/train/9e0b77b7670e302b216a2be3f81749a9.png...

 64%|██████▍   | 728/1137 [39:37<21:31,  3.16s/it]

Done.
Downloading 1T37mL2t_VviHFNjcWsaJ4RyyGCBSAYMm into /content/dataset/images/train/F37605_florencia_fernandez_43.png...

 64%|██████▍   | 729/1137 [39:40<19:57,  2.93s/it]

Done.
Downloading 1536Qvvjei_Ay4oZhw2lQpN82aDzMcmd7 into /content/dataset/images/train/w05576_juan_wagner_33.png...

 64%|██████▍   | 730/1137 [39:43<19:19,  2.85s/it]

Done.
Downloading 1QJaD9SWZDoMPrOe70fPyDZR80iDcHlnd into /content/dataset/images/train/s56189_salvador_sanchez_158.jpg...

 64%|██████▍   | 731/1137 [39:45<18:08,  2.68s/it]

Done.
Downloading 10LDf9ntUecb5BjCEE1rvuzLo87AuSR-A into /content/dataset/images/train/s56189_salvador_sanchez_12.jpg...

 64%|██████▍   | 732/1137 [39:47<16:56,  2.51s/it]

Done.
Downloading 1LJaNTBXrF_JeSnMgezdQPX807rlhi24a into /content/dataset/images/train/46019_taiel_raffaeli_32.jpg...

 64%|██████▍   | 733/1137 [39:50<17:53,  2.66s/it]

Done.
Downloading 10F1JCdBcslUVkYjFhsnerWrd4ZniQw3M into /content/dataset/images/train/43265_Lucas_Demarre_23.jpg...

 65%|██████▍   | 734/1137 [39:52<17:05,  2.55s/it]

Done.
Downloading 1fmpaxFYUnefn6rAJUmJbWADBWXZOAkNY into /content/dataset/images/train/71846_Brisa_Menescaldi_09.png...

 65%|██████▍   | 735/1137 [39:57<21:39,  3.23s/it]

Done.
Downloading 1kYRKX1QXIpC5glK-17OU1vCDwE1C90m2 into /content/dataset/images/train/f24e9b3e1d2527a28a7c438656036f86.png...

 65%|██████▍   | 736/1137 [40:00<21:26,  3.21s/it]

Done.
Downloading 12NlAP1PX_pUb35OlijotlXb8OVDECRuw into /content/dataset/images/train/s56189_salvador_sanchez_31.jpg...

 65%|██████▍   | 737/1137 [40:03<19:34,  2.94s/it]

Done.
Downloading 1fex9fkTST73_lzX5vRdIJreT9me1Ze4Q into /content/dataset/images/train/23451_guido_lorenzettibruera_26.jpg...

 65%|██████▍   | 738/1137 [40:09<26:29,  3.98s/it]

Done.
Downloading 15LQQWCx9nxrwPUSDyakew_AjVpwHkoyP into /content/dataset/images/train/71846_Brisa_Menescaldi_25.png...

 65%|██████▍   | 739/1137 [40:14<28:46,  4.34s/it]

Done.
Downloading 1vXU9ZdOgMGJGDCjGxr-b7CAbhLfjUy7z into /content/dataset/images/train/S57061_Leandro_Salvana_18.png...

 65%|██████▌   | 740/1137 [40:17<25:21,  3.83s/it]

Done.
Downloading 1flmYk-ChTTkmvgR3wFBRpGIIaKOgYUi8 into /content/dataset/images/train/43237686_Constantino_Ferrucci_7.png...

 65%|██████▌   | 741/1137 [40:47<1:17:43, 11.78s/it]

Done.
Downloading 1MlgiIDkYJcau4lb9ACh1Nt-npn0YxTIP into /content/dataset/images/train/51659_antonio_peroni_27.jpg...

 65%|██████▌   | 742/1137 [41:04<1:27:27, 13.28s/it]

Done.
Downloading 1zw59H2iBS5A_XARfVqkS2YQR37vpGa9L into /content/dataset/images/train/R-45489_sofiarondini_09.png...

 65%|██████▌   | 743/1137 [41:07<1:06:50, 10.18s/it]

Done.
Downloading 1fifTeeuXyM4ihEfsoQ7rYDKmYAzxV5e6 into /content/dataset/images/train/51934_pablo_pistelli_17.png...

 65%|██████▌   | 744/1137 [41:12<57:16,  8.74s/it]

Done.
Downloading 1VW9lFdXL-gH2fvQThQAvJDmc2kBB_tnC into /content/dataset/images/train/s56189_salvador_sanchez_241.jpg...

 66%|██████▌   | 745/1137 [41:14<44:11,  6.77s/it]

Done.
Downloading 1r_QkwwwFxWq7oO9n_gMIWu0vfngyO_aX into /content/dataset/images/train/R-45829_Abril_Rodriguez_28.png...

 66%|██████▌   | 746/1137 [41:18<37:25,  5.74s/it]

Done.
Downloading 1cHPrJHtmFgEtv3ULw-TyBbx5t5wXtKus into /content/dataset/images/train/41932688_Simon_Revello_4.png...

 66%|██████▌   | 747/1137 [41:24<38:13,  5.88s/it]

Done.
Downloading 1kpBd_anVoN7AGASVu1-TEf3XuePJswSm into /content/dataset/images/train/f37478_santiago_ferrero_40.jpg...

 66%|██████▌   | 748/1137 [41:27<32:31,  5.02s/it]

Done.
Downloading 1KXf-YwZMynta-Wgp3vElkF9mid25Muc3 into /content/dataset/images/train/51705_micaela_pozzo_09.png...

 66%|██████▌   | 749/1137 [41:30<29:03,  4.49s/it]

Done.
Downloading 1qUT9dApYOCVS0BIqjN3pdgJT1SaayNT4 into /content/dataset/images/train/L32425_eugenio_lopez_19.png...

 66%|██████▌   | 750/1137 [42:01<1:19:10, 12.27s/it]

Done.
Downloading 1lD_Dxd0yoLMitOcbHhlSxIgxrnBVx2h2 into /content/dataset/images/train/52256_daniel_ponce_09.jpeg...

 66%|██████▌   | 751/1137 [42:03<1:00:05,  9.34s/it]

Done.
Downloading 1k60KyW2sCIehuVxvgqm3u5jJKTSjQx2j into /content/dataset/images/train/L32531_santiago_loza_35.jpg...

 66%|██████▌   | 752/1137 [42:31<1:35:37, 14.90s/it]

Done.
Downloading 1qt9qGFD7qm8DEJ-qCQOz2SUk4acjnD1O into /content/dataset/images/train/P_51977_martin_perrone_04.png...

 66%|██████▌   | 753/1137 [42:35<1:14:11, 11.59s/it]

Done.
Downloading 1VyzswIzQlOHlat8hoAKxx3osn7MwS1Hx into /content/dataset/images/train/f37478_santiago_ferrero_22.jpg...

 66%|██████▋   | 754/1137 [42:37<56:14,  8.81s/it]

Done.
Downloading 1a6jIWkYRrgAPm5to3PIldQ3IS8a2dheO into /content/dataset/images/train/f37478_santiago_ferrero_17.jpg...

 66%|██████▋   | 755/1137 [42:39<43:24,  6.82s/it]

Done.
Downloading 1LLXKvHSqIE9gx7zwaOUnFOW6c-T-sdCU into /content/dataset/images/train/58513_isaias_garay_29.png...

 66%|██████▋   | 756/1137 [42:42<35:04,  5.52s/it]

Done.
Downloading 1a0284adKRNXci0sMnuYxc72H4f_lQ6Iz into /content/dataset/images/train/567df7320cea887c8ddf80cbb6482d54.png...

 67%|██████▋   | 757/1137 [42:45<29:45,  4.70s/it]

Done.
Downloading 1K35jORhqNS-AXqoxoAHCsnmhq6v5KldO into /content/dataset/images/train/46019_taiel_raffaeli_37.jpg...

 67%|██████▋   | 758/1137 [42:48<26:21,  4.17s/it]

Done.
Downloading 1tWcNFPwKicGaBPDxZsbMUiBOK9FC4Mry into /content/dataset/images/train/51934_pablo_pistelli_25.png...

 67%|██████▋   | 759/1137 [42:52<27:17,  4.33s/it]

Done.
Downloading 1xdVIFD_X9Vu3FyFK_NkoeUWl0NIlG_BC into /content/dataset/images/train/71846_Brisa_Menescaldi_16.png...

 67%|██████▋   | 760/1137 [42:57<27:31,  4.38s/it]

Done.
Downloading 1t64RSM0y1AaGhZpTo91OmC9HHh8I8V6C into /content/dataset/images/train/43265_Lucas_Demarre_14.jpg...

 67%|██████▋   | 761/1137 [42:59<23:06,  3.69s/it]

Done.
Downloading 1eR4j0gZwXGxMKDRQrgEMyzVygkr8vXB8 into /content/dataset/images/train/52256_daniel_ponce_16.jpeg...

 67%|██████▋   | 762/1137 [43:01<20:53,  3.34s/it]

Done.
Downloading 1049wvKuFIxrYr-qYk1PVLpr2T9YKslYg into /content/dataset/images/train/s56189_salvador_sanchez_11.jpg...

 67%|██████▋   | 763/1137 [43:04<19:09,  3.07s/it]

Done.
Downloading 193E7QJOp_EFAE0cbGdCRABwb7EA2niNU into /content/dataset/images/train/P_51977_martin_perrone_34.png...

 67%|██████▋   | 764/1137 [43:07<20:11,  3.25s/it]

Done.
Downloading 1UP5q5UQ634_o6Jp8r8--2lr0PuLqzLTz into /content/dataset/images/train/P51926_Leonel_Palermo_20.png...

 67%|██████▋   | 765/1137 [43:12<21:45,  3.51s/it]

Done.
Downloading 1b6WAF39cxIPAffZrsHg1ZvzF-U9h6RrM into /content/dataset/images/train/e3647d80d5bfa76aaa0a240fee750f3a.png...

 67%|██████▋   | 766/1137 [43:14<20:30,  3.32s/it]

Done.
Downloading 1eGSg50BW_xR7NFvVQsE0FJ3q0em2ngKX into /content/dataset/images/train/F37605_florencia_fernandez_12.png...

 67%|██████▋   | 767/1137 [43:17<19:32,  3.17s/it]

Done.
Downloading 1GZlCGTSdABDsrW_88GxCif9OyLm0QouP into /content/dataset/images/train/w05576_juan_wagner_13.png...

 68%|██████▊   | 768/1137 [43:19<17:37,  2.87s/it]

Done.
Downloading 1xr92IOHG19FQ_HjEiF_MmC84ChYZigiQ into /content/dataset/images/train/L32425_eugenio_lopez_01.png...

 68%|██████▊   | 769/1137 [43:23<18:32,  3.02s/it]

Done.
Downloading 1J3p68eBIqlV3eypn5U_ClDSYVXg3BN6K into /content/dataset/images/train/s56189_salvador_sanchez_57.jpg...

 68%|██████▊   | 770/1137 [43:25<17:12,  2.81s/it]

Done.
Downloading 1T5L_39U1bJKYGcaX9S2DaVSAEcHKvagp into /content/dataset/images/train/03531_mirian_yanez_04.jpeg...

 68%|██████▊   | 771/1137 [43:28<16:36,  2.72s/it]

Done.
Downloading 1ONyeWq0lC0vHq8ez_SJo369QJoIR30Ey into /content/dataset/images/train/8bb3952a2888975922db1708d4e68b53.png...

 68%|██████▊   | 772/1137 [43:30<16:35,  2.73s/it]

Done.
Downloading 1V_8-EbYvTFiIA3tmZpavsDE4orLzB1U7 into /content/dataset/images/train/43841031_Enzo_Ferrari_13.png...

 68%|██████▊   | 773/1137 [43:35<20:30,  3.38s/it]

Done.
Downloading 1BxTbeKZ_Wfa_GAwdorRZUmamoAG_4RaQ into /content/dataset/images/train/w05576_juan_wagner_06.png...

 68%|██████▊   | 774/1137 [43:37<18:14,  3.01s/it]

Done.
Downloading 1TBax13XDmcjYmIGNHIQ_fHMXOmraHGBz into /content/dataset/images/train/41932688_Simon_Revello_19.png...

 68%|██████▊   | 775/1137 [43:42<21:48,  3.62s/it]

Done.
Downloading 1i7bYGwx7KVeqXsoSHaIVKZ6HzkTP_7yE into /content/dataset/images/train/c46c27c46e3bf9450677896f9637ea84.png...

 68%|██████▊   | 776/1137 [44:07<59:18,  9.86s/it]

Done.
Downloading 1zi_QoI79xCUL0lcGZ6nSxDTcz0P86UPE into /content/dataset/images/train/f37478_santiago_ferrero_38.jpg...

 68%|██████▊   | 777/1137 [44:18<1:01:12, 10.20s/it]

Done.
Downloading 1MHbfeIJuHidtZxbn1XwNa3WPOo5iaQCX into /content/dataset/images/train/s56189_salvador_sanchez_102.jpg...

 68%|██████▊   | 778/1137 [44:20<46:36,  7.79s/it]

Done.
Downloading 14Jna7f40kbld9QGAdiEC3x3ZdEN9rplC into /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_02.jpg...

 69%|██████▊   | 779/1137 [44:23<37:53,  6.35s/it]

Done.
Downloading 1pJ5E6XH3klYCT6tPzDcuSJfZzIxi2CX5 into /content/dataset/images/train/43237686_Constantino_Ferrucci_14.png...

 69%|██████▊   | 780/1137 [44:27<32:36,  5.48s/it]

Done.
Downloading 1J3dDJCyKavV7nlRYcButY1J_td2ajfCP into /content/dataset/images/train/03531_mirian_yanez_09.jpeg...

 69%|██████▊   | 781/1137 [44:29<27:51,  4.70s/it]

Done.
Downloading 1ywlZp8A8heMhsvGa0sMhOQhLxkU-ViZf into /content/dataset/images/train/52256_daniel_ponce_01.jpeg...

 69%|██████▉   | 782/1137 [44:32<23:35,  3.99s/it]

Done.
Downloading 1D2JstBcigmQ1YReFJ9Y_QqS-t5rXWK4U into /content/dataset/images/train/37524_augusto_farias_27.jpg...

 69%|██████▉   | 783/1137 [44:36<24:02,  4.08s/it]

Done.
Downloading 1lhcwwKV0wV_1MtxoS36ZLzO6YxnAmPWP into /content/dataset/images/train/fed41586e4af6462681da0eab7d26de9.png...

 69%|██████▉   | 784/1137 [44:39<21:23,  3.64s/it]

Done.
Downloading 1kPDvwvNWfpuufP1Zyyi7OC8XLrwrAFxV into /content/dataset/images/train/f37478_santiago_ferrero_14.jpg...

 69%|██████▉   | 785/1137 [45:08<1:07:27, 11.50s/it]

Done.
Downloading 1ppAoC5ldeYwNOFWWg4ExRG_ZTpW3nepZ into /content/dataset/images/train/f53a4aca993ad6bf5e67c3184690eae1.png...

 69%|██████▉   | 786/1137 [45:11<52:11,  8.92s/it]

Done.
Downloading 10sFoj5l3aMmBRq9zKup44XJjSzCv1UcN into /content/dataset/images/train/58491_fabio_giampaoli_12.png...

 69%|██████▉   | 787/1137 [45:16<45:14,  7.75s/it]

Done.
Downloading 1urcD6CHofpsPKDL8uunHpijLuOfaiVPR into /content/dataset/images/train/03531_mirian_yanez_13.jpeg...

 69%|██████▉   | 788/1137 [45:19<36:35,  6.29s/it]

Done.
Downloading 1VJpzmyj-1SF4r21BOV4p0Ih7iaq2imL1 into /content/dataset/images/train/s56189_salvador_sanchez_237.jpg...

 69%|██████▉   | 789/1137 [45:22<29:39,  5.11s/it]

Done.
Downloading 1W7_-n9Ea7vy_hDnFDgGThIc6ttcLQcAD into /content/dataset/images/train/s56189_salvador_sanchez_252.jpg...

 69%|██████▉   | 790/1137 [45:24<24:34,  4.25s/it]

Done.
Downloading 1lq-Pc5CiQTjAFN-WwVX_PjLTQfJRA7Qb into /content/dataset/images/train/58513_isaias_garay_15.png...

 70%|██████▉   | 791/1137 [45:26<21:37,  3.75s/it]

Done.
Downloading 1LD_vq0ukNDYcizUhsln7Vp_aIfQkE-dH into /content/dataset/images/train/72125_miguel_mussi_24.png...

 70%|██████▉   | 792/1137 [45:30<20:42,  3.60s/it]

Done.
Downloading 12IVnyn7LSEFdm89bVMuYZKLIbRZjVyyy into /content/dataset/images/train/s56189_salvador_sanchez_33.jpg...

 70%|██████▉   | 793/1137 [45:32<18:11,  3.17s/it]

Done.
Downloading 18IUemQCKli7ZJU-gPsa1C5ohmxwkgAiL into /content/dataset/images/train/L32425_eugenio_lopez_09.png...

 70%|██████▉   | 794/1137 [45:36<19:50,  3.47s/it]

Done.
Downloading 1UtxaF3ISCLy0_8Hy2b5LXJdGeizylutJ into /content/dataset/images/train/P51926_Leonel_Palermo_04.png...

 70%|██████▉   | 795/1137 [45:41<22:42,  3.98s/it]

Done.
Downloading 17hOHa7I6FpiDqDvaxfZxN3SYS0uSK5mE into /content/dataset/images/train/P51926_Leonel_Palermo_23.png...

 70%|███████   | 796/1137 [45:45<21:47,  3.83s/it]

Done.
Downloading 1jxBsucuiX_ardXDqTtPgIjID8MUvi2i9 into /content/dataset/images/train/s56804_alexis_segui_15.png...

 70%|███████   | 797/1137 [45:47<19:29,  3.44s/it]

Done.
Downloading 1U0ojYN2Bps-XUon1QCr1izCOYO_35eCy into /content/dataset/images/train/R-45489_sofiarondini_06.png...

 70%|███████   | 798/1137 [45:50<17:42,  3.14s/it]

Done.
Downloading 1V-FsDsEphM5_LO0hHLRqZ2KDm8kMR9oQ into /content/dataset/images/train/s56189_salvador_sanchez_233.jpg...

 70%|███████   | 799/1137 [45:52<16:03,  2.85s/it]

Done.
Downloading 1CkuT_JGwUifRbx0UwdxcglTlAuZrA_6s into /content/dataset/images/train/58912_Timoteo_Garcia_26.jpg...

 70%|███████   | 800/1137 [45:56<17:48,  3.17s/it]

Done.
Downloading 1UZ7ZhAWcQRoVlKXzfN9y4-dVd1tFpwy2 into /content/dataset/images/train/P_51977_martin_perrone_13.png...

 70%|███████   | 801/1137 [45:59<18:17,  3.27s/it]

Done.
Downloading 1gGfGpLtGgeHDH8hPlj3xm_cQ5E7IX6pp into /content/dataset/images/train/R-45489_sofiarondini_20.png...

 71%|███████   | 802/1137 [46:02<17:12,  3.08s/it]

Done.
Downloading 1UTBOawBIEbppAFkoQs3Df7M_GzBcehIp into /content/dataset/images/train/s56189_salvador_sanchez_222.jpg...

 71%|███████   | 803/1137 [46:04<15:44,  2.83s/it]

Done.
Downloading 1rJgIs-QnTl5NsZht1f2Qj-axl10HVUlg into /content/dataset/images/train/58513_isaias_garay_19.png...

 71%|███████   | 804/1137 [46:07<15:46,  2.84s/it]

Done.
Downloading 1aPfq6e7pNCu0XKkp89qMeHYIU82Xi8_y into /content/dataset/images/train/57096_ramiro_sagrera_29.jpg...

 71%|███████   | 805/1137 [46:10<15:50,  2.86s/it]

Done.
Downloading 151MY3VlmR8yezPZ_sgnoAM9gl1-I1_ba into /content/dataset/images/train/72125_miguel_mussi_31.png...

 71%|███████   | 806/1137 [46:13<15:24,  2.79s/it]

Done.
Downloading 1lObwUwnb-0QNMIRSV2pSNpwxYYiuznnC into /content/dataset/images/train/e343f320e0f5075c681e604949045b72.png...

 71%|███████   | 807/1137 [46:16<16:23,  2.98s/it]

Done.
Downloading 1OU20tk-dUtHGNvq-uuWtbLXSzPoMLkIK into /content/dataset/images/train/s56189_salvador_sanchez_136.jpg...

 71%|███████   | 808/1137 [46:18<15:04,  2.75s/it]

Done.
Downloading 16EBgMj6z_k_1DCzJ2B_XGcCeSWbvtl7a into /content/dataset/images/train/76164b682bcc50ec13e45aba7d160981.png...

 71%|███████   | 809/1137 [46:21<15:27,  2.83s/it]

Done.
Downloading 10ZRlrP4zOPbE9dtuRaIbJWroOudnXxQ8 into /content/dataset/images/train/46019_taiel_raffaeli_35.jpg...

 71%|███████   | 810/1137 [46:24<15:49,  2.90s/it]

Done.
Downloading 1QN4KnOZUu8PvYVXeqBpJZtkTbBR87wqR into /content/dataset/images/train/s56189_salvador_sanchez_162.jpg...

 71%|███████▏  | 811/1137 [46:27<15:11,  2.80s/it]

Done.
Downloading 17gx6iCbmMxrviXFb2_I3r1Ya2CeLw7_T into /content/dataset/images/train/49ec2ac308d5afa8cf63345cc8267d65.png...

 71%|███████▏  | 812/1137 [46:30<15:35,  2.88s/it]

Done.
Downloading 1CGmf-H5IWAB4ojQuXHRP5lF7mjhnNbGy into /content/dataset/images/train/57096_ramiro_sagrera_06.jpg...

 72%|███████▏  | 813/1137 [46:33<15:25,  2.86s/it]

Done.
Downloading 1NMSJ-RyMAgPVE-YszguZfG8mXqMoqplT into /content/dataset/images/train/S57061_Leandro_Salvana_41.png...

 72%|███████▏  | 814/1137 [46:35<14:47,  2.75s/it]

Done.
Downloading 1oyt5gBdrCzlsnsWQxNO04Lh6RzLn-4MQ into /content/dataset/images/train/46094_Mateo_Rovere_15.png...

 72%|███████▏  | 815/1137 [46:39<16:47,  3.13s/it]

Done.
Downloading 1NlT8oSoAvnZ1FG_8TcuCfrKHMrQuHK2q into /content/dataset/images/train/33db56c3f1d54e81049c8f576f8c5a15.png...

 72%|███████▏  | 816/1137 [46:42<16:11,  3.03s/it]

Done.
Downloading 1ZKt8T49VbtFnrSccxZeTTWbIQGCrtBZq into /content/dataset/images/train/71846_Brisa_Menescaldi_28.png...

 72%|███████▏  | 817/1137 [46:46<18:26,  3.46s/it]

Done.
Downloading 1bDnFwyWCWddFK5xOX9e3laRxk1Jw0KdY into /content/dataset/images/train/A45161_Fabian_Aguirre_01.png...

 72%|███████▏  | 818/1137 [46:49<16:50,  3.17s/it]

Done.
Downloading 1wtyo4L7_TkefLY9ruynYaidGnAuHb8Uc into /content/dataset/images/train/P_51977_martin_perrone_28.png...

 72%|███████▏  | 819/1137 [46:53<17:25,  3.29s/it]

Done.
Downloading 1mVdqt3dj5Cs2w2k_LRz9aJOF1bEGMk9R into /content/dataset/images/train/51934_pablo_pistelli_04.png...

 72%|███████▏  | 820/1137 [46:57<19:47,  3.75s/it]

Done.
Downloading 1Pq3ihihaopmL_KqcQn08NhbON0WDKUWe into /content/dataset/images/train/L32531_santiago_loza_8.jpg...

 72%|███████▏  | 821/1137 [47:00<18:16,  3.47s/it]

Done.
Downloading 1KKI6QLBizkdHZWSP7vRGftibTMiDxKoo into /content/dataset/images/train/s56189_salvador_sanchez_79.jpg...

 72%|███████▏  | 822/1137 [47:02<16:21,  3.12s/it]

Done.
Downloading 15W4y_c2Cz4ZtVrGP4heZy1gdULjziRnZ into /content/dataset/images/train/03531_mirian_yanez_06.jpeg...

 72%|███████▏  | 823/1137 [47:05<15:04,  2.88s/it]

Done.
Downloading 178vA3lLeetGJbc-0xuReg44bVRS1SBJW into /content/dataset/images/train/43237686_Constantino_Ferrucci_13.png...

 72%|███████▏  | 824/1137 [47:08<15:30,  2.97s/it]

Done.
Downloading 18mamhW5hg4zcUVs6nKy-MIkIIBE5_lT8 into /content/dataset/images/train/58491_fabio_giampaoli_20.png...

 73%|███████▎  | 825/1137 [47:12<17:26,  3.36s/it]

Done.
Downloading 1n3z-IKwzM2avj2oWK2Zhy1r0CtTiTFPV into /content/dataset/images/train/03531_mirian_yanez_08.jpeg...

 73%|███████▎  | 826/1137 [47:15<16:56,  3.27s/it]

Done.
Downloading 1EmsaKxkWLtlHgkFOwvryxJFIHNGDAudD into /content/dataset/images/train/51705_micaela_pozzo_03.png...

 73%|███████▎  | 827/1137 [47:18<15:50,  3.07s/it]

Done.
Downloading 1RB8DKdHQcXvD4KGGkxVVLORm9AgHP42x into /content/dataset/images/train/s56189_salvador_sanchez_179.jpg...

 73%|███████▎  | 828/1137 [47:20<14:35,  2.83s/it]

Done.
Downloading 11RlMRfAfN22pRFwbwBlIx-1WFFWgTh7v into /content/dataset/images/train/94817a48957c610b5ec00b4d93bb7b1c.png...

 73%|███████▎  | 829/1137 [47:23<14:25,  2.81s/it]

Done.
Downloading 1UFu9RpLNWr4Xqyf5J0MehwrM8S-YZi6_ into /content/dataset/images/train/51951_pablo_pistarelli_25.png...

 73%|███████▎  | 830/1137 [47:27<16:06,  3.15s/it]

Done.
Downloading 1TnrnWKllbmmDFWY1MgWDMOeDjuNI9k2X into /content/dataset/images/train/R-45489_sofiarondini_24.png...

 73%|███████▎  | 831/1137 [47:30<15:35,  3.06s/it]

Done.
Downloading 13ADuMRP2XkxfCiEw7aaDpxcbjm2WxmnA into /content/dataset/images/train/bcf1e5a2aac0c41cf27c527613a6f704.png...

 73%|███████▎  | 832/1137 [47:32<15:01,  2.95s/it]

Done.
Downloading 12Z1zPNGg3ancV0x9CmUxWSO7OnPFFAuP into /content/dataset/images/train/s56804_alexis_segui_20.png...

 73%|███████▎  | 833/1137 [47:35<13:49,  2.73s/it]

Done.
Downloading 1lQJBF7puc5NZmWz7KqsQlTxxCot3K6hd into /content/dataset/images/train/23451_guido_lorenzettibruera_25.jpg...

 73%|███████▎  | 834/1137 [47:39<16:18,  3.23s/it]

Done.
Downloading 1gMKddXs3_sTuFAKm-JFgS6-nJ32ZBzRD into /content/dataset/images/train/P51951_pablo_pistarelli_07.png...

 73%|███████▎  | 835/1137 [47:42<15:49,  3.15s/it]

Done.
Downloading 1-lWnWYeC_nFS7jBB7nOBoTHMIzjDGoww into /content/dataset/images/train/s56804_alexis_segui_19.png...

 74%|███████▎  | 836/1137 [47:44<14:44,  2.94s/it]

Done.
Downloading 1xzDdQGISpGf4iM4qLoy5RED0kfmm83Q4 into /content/dataset/images/train/d7e76ba83d90085d1020c5f240e365de.png...

 74%|███████▎  | 837/1137 [47:47<14:08,  2.83s/it]

Done.
Downloading 1JjjNRxqyOUWxclXqzZdEYy3fDaZnteMO into /content/dataset/images/train/s56189_salvador_sanchez_67.jpg...

 74%|███████▎  | 838/1137 [47:49<13:13,  2.65s/it]

Done.
Downloading 1BNHLqx6LHHLzknk0K1H8I0atjpmdJ9G3 into /content/dataset/images/train/46019_taiel_raffaeli_13.jpg...

 74%|███████▍  | 839/1137 [47:52<13:31,  2.72s/it]

Done.
Downloading 1YYWBcXMuzsmdr9gQ5FP4dkfSpLq5dyQw into /content/dataset/images/train/s56189_salvador_sanchez_293.jpg...

 74%|███████▍  | 840/1137 [47:54<12:49,  2.59s/it]

Done.
Downloading 1Rg2nUGswMuZjHn-o70CMQqjxo0YOdEiS into /content/dataset/images/train/37524_augusto_farias_17.jpg...

 74%|███████▍  | 841/1137 [47:58<14:44,  2.99s/it]

Done.
Downloading 1WTxmHcGi5ayWvZ96oNrHc19uhj4UGvJC into /content/dataset/images/train/58912_Timoteo_Garcia_33.jpg...

 74%|███████▍  | 842/1137 [48:02<15:44,  3.20s/it]

Done.
Downloading 1jHrDSb61jVumIvu_DSCspIJec3hmV-RM into /content/dataset/images/train/f37478_santiago_ferrero_32.jpg...

 74%|███████▍  | 843/1137 [48:04<14:26,  2.95s/it]

Done.
Downloading 1-FhhQjEcfhvfO8FlENL3jKFqK5jm5LHB into /content/dataset/images/train/46094_Mateo_Rovere_9.png...

 74%|███████▍  | 844/1137 [48:08<15:01,  3.08s/it]

Done.
Downloading 1yQsTTbw2WBsszt9Kay_xnhsaz2j-LlEq into /content/dataset/images/train/R-45829_Abril_Rodriguez_17.png...

 74%|███████▍  | 845/1137 [48:10<14:01,  2.88s/it]

Done.
Downloading 1bPgY8UbrrCFiZjiMRz2dR-EpOidAHg8r into /content/dataset/images/train/51659_antonio_peroni_20.jpg...

 74%|███████▍  | 846/1137 [48:14<14:44,  3.04s/it]

Done.
Downloading 13WYRs1nZ8sxwSqQXw6mb-piGYR0K5gCk into /content/dataset/images/train/R-45829_Abril_Rodriguez_07.png...

 74%|███████▍  | 847/1137 [48:16<13:39,  2.83s/it]

Done.
Downloading 1Kx5uwJrrGvcLHI0oinEmQJZYUUYatcth into /content/dataset/images/train/23451_guido_lorenzettibruera_16.jpg...

 75%|███████▍  | 848/1137 [48:21<17:08,  3.56s/it]

Done.
Downloading 1GTXWtCMs9siQu16hdBoMf0vywAnwvHDK into /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_03.jpg...

 75%|███████▍  | 849/1137 [48:24<16:34,  3.45s/it]

Done.
Downloading 1R2P0Yy5cyn0eODiUUsRX6A0Hizgw0JMi into /content/dataset/images/train/s56189_salvador_sanchez_172.jpg...

 75%|███████▍  | 850/1137 [48:27<15:03,  3.15s/it]

Done.
Downloading 18vB1k3e4kv3xIHJsZX7cDZWjqJn34ImU into /content/dataset/images/train/R-45489_sofiarondini_12.png...

 75%|███████▍  | 851/1137 [48:29<13:57,  2.93s/it]

Done.
Downloading 1TpWtkWSlizkwLJwWYivwsdvL-Dhya5j5 into /content/dataset/images/train/s56189_salvador_sanchez_215.jpg...

 75%|███████▍  | 852/1137 [48:31<12:51,  2.71s/it]

Done.
Downloading 1oHE2i7fpgbPJUZP2ybvqTgFyTyLJfZYw into /content/dataset/images/train/23451_guido_lorenzettibruera_22.jpg...

 75%|███████▌  | 853/1137 [48:36<15:14,  3.22s/it]

Done.
Downloading 1FsK2oEPacY4ROUJqqcl24Ab2PIKFI36a into /content/dataset/images/train/F37605_florencia_fernandez_42.png...

 75%|███████▌  | 854/1137 [48:39<14:53,  3.16s/it]

Done.
Downloading 1CzZ3xeLMPm3neXspOdSHCIpQolgtD6Db into /content/dataset/images/train/71846_Brisa_Menescaldi_30.png...

 75%|███████▌  | 855/1137 [48:44<17:29,  3.72s/it]

Done.
Downloading 1wBGqgNS8xnYXihrSoN81EpDZ5oMZ1uMY into /content/dataset/images/train/10d2680f1d5794a1f9eb029351d4d59f.png...

 75%|███████▌  | 856/1137 [48:47<16:35,  3.54s/it]

Done.
Downloading 1ZoPX0L7iwdGJdd_LdLOBvIa7VdmgjcbA into /content/dataset/images/train/s56189_salvador_sanchez_313.jpg...

 75%|███████▌  | 857/1137 [48:49<14:47,  3.17s/it]

Done.
Downloading 1NdgoxHCLDTvsZmMdryO6gxzgMaHrMwug into /content/dataset/images/train/f37478_santiago_ferrero_33.jpg...

 75%|███████▌  | 858/1137 [48:52<14:33,  3.13s/it]

Done.
Downloading 1TJCnfghJFRQp4-xROmwQtGP8vur9Z1O8 into /content/dataset/images/train/s56189_salvador_sanchez_211.jpg...

 76%|███████▌  | 859/1137 [48:55<13:15,  2.86s/it]

Done.
Downloading 12gvc1JkBXZw56tK0zbcc4uflnVt2iXa8 into /content/dataset/images/train/43265_Lucas_Demarre_25.jpg...

 76%|███████▌  | 860/1137 [48:57<12:15,  2.66s/it]

Done.
Downloading 1NOXnuQOXReyEARX3kMh7F63GnQAlh5Rs into /content/dataset/images/train/s56189_salvador_sanchez_127.jpg...

 76%|███████▌  | 861/1137 [48:59<11:50,  2.57s/it]

Done.
Downloading 1SXLfL37gYvarMAtZHGKvhHpCfGs4b8-R into /content/dataset/images/train/s56189_salvador_sanchez_199.jpg...

 76%|███████▌  | 862/1137 [49:01<11:11,  2.44s/it]

Done.
Downloading 1Sm_ODO9wr93PQijx0zpVuG5HivAbBuoS into /content/dataset/images/train/s56189_salvador_sanchez_201.jpg...

 76%|███████▌  | 863/1137 [49:03<10:47,  2.36s/it]

Done.
Downloading 1DQK-T5HKeiPOKt2Lds242OjliO4n2cfp into /content/dataset/images/train/12394_escandell_ariel_07.jpg...

 76%|███████▌  | 864/1137 [49:06<11:13,  2.47s/it]

Done.
Downloading 19T370Ri7WkMyy1nnMGce5yxdhUQKplHr into /content/dataset/images/train/51705_micaela_pozzo_30.png...

 76%|███████▌  | 865/1137 [49:09<11:41,  2.58s/it]

Done.
Downloading 1e4CXVyze5XflpyBguB0Vl09XT4ncwfzp into /content/dataset/images/train/43265_Lucas_Demarre_06.jpg...

 76%|███████▌  | 866/1137 [49:11<11:16,  2.50s/it]

Done.
Downloading 1R-pO3up0xS6MBiLx2-8-HwGL2AnSl-W5 into /content/dataset/images/train/s56189_salvador_sanchez_175.jpg...

 76%|███████▋  | 867/1137 [49:14<11:02,  2.45s/it]

Done.
Downloading 1QxkDa9EvYEdY6Y_j27DYxM7NeHNFCkJg into /content/dataset/images/train/58912_Timoteo_Garcia_31.jpg...

 76%|███████▋  | 868/1137 [49:17<11:37,  2.59s/it]

Done.
Downloading 1T2bUT7kr2BYCbOyxzIOVTdLTqnudGDoD into /content/dataset/images/train/s56189_salvador_sanchez_207.jpg...

 76%|███████▋  | 869/1137 [49:19<11:03,  2.48s/it]

Done.
Downloading 1Zq0UGib2mYKcGsjtBi3LOwWhK72z_cDL into /content/dataset/images/train/s56189_salvador_sanchez_318.jpg...

 77%|███████▋  | 870/1137 [49:21<10:49,  2.43s/it]

Done.
Downloading 1QS-s6TkM4w_Wd-aoSi9VJz_YWqd7kCUX into /content/dataset/images/train/03531_mirian_yanez_29.jpeg...

 77%|███████▋  | 871/1137 [49:24<10:43,  2.42s/it]

Done.
Downloading 1ucft33spNHO4vgTzJDKT9VEbPE5iwXUO into /content/dataset/images/train/41932688_Simon_Revello_5.png...

 77%|███████▋  | 872/1137 [49:28<12:57,  2.94s/it]

Done.
Downloading 1IrslBkkzub_TD9VY43qVnSFbnUC_yhfy into /content/dataset/images/train/s56189_salvador_sanchez_62.jpg...

 77%|███████▋  | 873/1137 [49:30<11:51,  2.70s/it]

Done.
Downloading 1ysfwFjuS9Tlw82cMkXLpJHPhKPMxzfOg into /content/dataset/images/train/43841031_Enzo_Ferrari_30.png...

 77%|███████▋  | 874/1137 [49:34<13:08,  3.00s/it]

Done.
Downloading 1TuIW8ANNQfZHa6z84zzESL2iEo4aUBNn into /content/dataset/images/train/s56189_salvador_sanchez_214.jpg...

 77%|███████▋  | 875/1137 [49:36<12:06,  2.77s/it]

Done.
Downloading 12Mqz5f4LDqMZHIyg8N9hq-zr4TmaVXFn into /content/dataset/images/train/58912_Timoteo_Garcia_24.jpg...

 77%|███████▋  | 876/1137 [49:38<11:53,  2.73s/it]

Done.
Downloading 1404pIYVxgngY1Lh_KZSv33nbQw0u7jmj into /content/dataset/images/train/S57061_Leandro_Salvana_43.png...

 77%|███████▋  | 877/1137 [49:41<12:01,  2.78s/it]

Done.
Downloading 18AeOAbejO7yw2AAUMBeHLRVvIIPxDP0q into /content/dataset/images/train/f3e9723ebb2cd8f05e49ac06a3288f8e.png...

 77%|███████▋  | 878/1137 [49:45<12:41,  2.94s/it]

Done.
Downloading 13Jh_FffatVHTHFwlwXluoC7-sQ3LsIdH into /content/dataset/images/train/w05576_juan_wagner_16.png...

 77%|███████▋  | 879/1137 [49:47<11:38,  2.71s/it]

Done.
Downloading 1oRUazHTOzYvzPXkktwCdlPYhuZyL66s_ into /content/dataset/images/train/46019_taiel_raffaeli_25.jpg...

 77%|███████▋  | 880/1137 [49:50<11:43,  2.74s/it]

Done.
Downloading 1bCKCcFIGM7kMxZnAtmDFJmsnDcIRz0Dz into /content/dataset/images/train/A45161_Fabian_Aguirre_26.png...

 77%|███████▋  | 881/1137 [49:53<12:23,  2.90s/it]

Done.
Downloading 1A4vmM12PdBu3TaV6qSUSqUiauJdc1mBp into /content/dataset/images/train/58491_fabio_giampaoli_24.png...

 78%|███████▊  | 882/1137 [50:00<17:26,  4.10s/it]

Done.
Downloading 1LZDf9BU2NvFKzwru16TCDzTwXQo5k5kz into /content/dataset/images/train/23451_guido_lorenzettibruera_23.jpg...

 78%|███████▊  | 883/1137 [50:05<18:54,  4.47s/it]

Done.
Downloading 1aXdokyhRr5MTPsghV13z2xhnaOz8Q5Xo into /content/dataset/images/train/a44809f6033eb9722034c145854daf1d.png...

 78%|███████▊  | 884/1137 [50:08<17:26,  4.14s/it]

Done.
Downloading 1UyOnc-bEFbVU1mi-a63pLveHwCVRAnzz into /content/dataset/images/train/s56189_salvador_sanchez_230.jpg...

 78%|███████▊  | 885/1137 [50:11<15:06,  3.60s/it]

Done.
Downloading 1XcFUTyCFQZBeyrcPALWDZE_-YzUnL1rU into /content/dataset/images/train/s56189_salvador_sanchez_279.jpg...

 78%|███████▊  | 886/1137 [50:13<13:23,  3.20s/it]

Done.
Downloading 1bw0n3nRL9Cf8LGuic_bIwvtA8uq-GjVJ into /content/dataset/images/train/957e583cbbbf600f9ac58dd946dff10b.png...

 78%|███████▊  | 887/1137 [50:17<14:35,  3.50s/it]

Done.
Downloading 1e1gsUQBLDLF63FxxEp1U-LZnzJ6NUOpx into /content/dataset/images/train/L32531_santiago_loza_44.jpg...

 78%|███████▊  | 888/1137 [50:20<13:39,  3.29s/it]

Done.
Downloading 1XOJRH8ZuaatTe412PhwdVoKADiEmjpbu into /content/dataset/images/train/s56189_salvador_sanchez_275.jpg...

 78%|███████▊  | 889/1137 [50:22<12:17,  2.97s/it]

Done.
Downloading 1eXp0JKYP2einbCk2-t0eI7byxxt1YtFE into /content/dataset/images/train/F37605_florencia_fernandez_31.png...

 78%|███████▊  | 890/1137 [50:25<12:12,  2.96s/it]

Done.
Downloading 1c5g-aqyKW8XGEAtrxknqADJQYeyAmXlk into /content/dataset/images/train/03531_mirian_yanez_15.jpeg...

 78%|███████▊  | 891/1137 [50:28<11:45,  2.87s/it]

Done.
Downloading 1UTJMlbJuFWJBvhjEpmkXMTqkq6LTu5iC into /content/dataset/images/train/P_51977_martin_perrone_20.png...

 78%|███████▊  | 892/1137 [50:32<12:41,  3.11s/it]

Done.
Downloading 1dpNiXqne3w_6ZDL8NgB5cLMG8VrRNkbK into /content/dataset/images/train/F37605_florencia_fernandez_18.png...

 79%|███████▊  | 893/1137 [50:34<11:48,  2.90s/it]

Done.
Downloading 1w-NSFbvn72cJrTMN0Qxb54I5tZlEgQn_ into /content/dataset/images/train/43841031_Enzo_Ferrari_16.png...

 79%|███████▊  | 894/1137 [50:38<13:21,  3.30s/it]

Done.
Downloading 1M_Rufj3D_CIgIB7IJz0ckyWXdkHDL13Q into /content/dataset/images/train/s56189_salvador_sanchez_112.jpg...

 79%|███████▊  | 895/1137 [50:40<11:54,  2.95s/it]

Done.
Downloading 1VxBMzKaiQISHDod0xEB1f31bARI8cwQj into /content/dataset/images/train/s56189_salvador_sanchez_248.jpg...

 79%|███████▉  | 896/1137 [50:43<11:04,  2.76s/it]

Done.
Downloading 1YdfaZdXXxUDFhfNGAov9vXPJb999jZs1 into /content/dataset/images/train/52256_daniel_ponce_25.jpeg...

 79%|███████▉  | 897/1137 [50:45<10:36,  2.65s/it]

Done.
Downloading 1-HKtufCpLYZz-olRql4s09kC3LyLi9L8 into /content/dataset/images/train/46019_taiel_raffaeli_36.jpg...

 79%|███████▉  | 898/1137 [50:48<10:36,  2.67s/it]

Done.
Downloading 1SCN5jdHF8mcRB3tALYkKGW_SaAaRoMX1 into /content/dataset/images/train/a4f49e1d32a1c6b6455065b3efcf7854.png...

 79%|███████▉  | 899/1137 [50:51<10:42,  2.70s/it]

Done.
Downloading 1qhgrqkfL6MqIdWCp5SAFeI1EKssvGDII into /content/dataset/images/train/41932688_Simon_Revello_25.png...

 79%|███████▉  | 900/1137 [50:55<12:13,  3.09s/it]

Done.
Downloading 1PpujSLoLJWsB_HOEaegUCcKiO0FDxr41 into /content/dataset/images/train/s56189_salvador_sanchez_152.jpg...

 79%|███████▉  | 901/1137 [50:57<11:16,  2.87s/it]

Done.
Downloading 1t8Thb_XBfIHGsd-Ud-SLrHmEIfY4Ko8U into /content/dataset/images/train/71846_Brisa_Menescaldi_15.png...

 79%|███████▉  | 902/1137 [51:01<13:03,  3.34s/it]

Done.
Downloading 17TDEUX99FwvTwCilup4Jh0LRVUzTdKqx into /content/dataset/images/train/52256_daniel_ponce_20.jpeg...

 79%|███████▉  | 903/1137 [51:04<12:35,  3.23s/it]

Done.
Downloading 1-qecjf7ypP3thn8m9MzwhA3DHDjtXzvZ into /content/dataset/images/train/S57061_Leandro_Salvana_10.png...

 80%|███████▉  | 904/1137 [51:07<11:59,  3.09s/it]

Done.
Downloading 1x61VUyZLz-fDgEv0SrLkGWVSs6TrZ4oJ into /content/dataset/images/train/P_51977_martin_perrone_27.png...

 80%|███████▉  | 905/1137 [51:11<12:56,  3.35s/it]

Done.
Downloading 1W5PHXdQqKTQpvyfFyhox-56PhQZ-xocd into /content/dataset/images/train/s56189_salvador_sanchez_253.jpg...

 80%|███████▉  | 906/1137 [51:13<11:48,  3.07s/it]

Done.
Downloading 1WG9GUzWloDXyVNkwJ0v0SscJQ8JFui4a into /content/dataset/images/train/s56189_salvador_sanchez_258.jpg...

 80%|███████▉  | 907/1137 [51:16<10:39,  2.78s/it]

Done.
Downloading 1vjS8aLZZDj0tdCiqDqzLmFqZwfoZvAoV into /content/dataset/images/train/51951_pablo_pistarelli_19.png...

 80%|███████▉  | 908/1137 [51:19<11:49,  3.10s/it]

Done.
Downloading 1XGJpkQh_ULiK8mOmA3c94QOU4OdpFAEm into /content/dataset/images/train/P51926_Leonel_Palermo_26.png...

 80%|███████▉  | 909/1137 [51:23<12:55,  3.40s/it]

Done.
Downloading 118EXHhzrUCyW4QcknLoOMcqdHffkYut2 into /content/dataset/images/train/43237686_Constantino_Ferrucci_1.png...

 80%|████████  | 910/1137 [51:26<12:18,  3.25s/it]

Done.
Downloading 1Nb0tP4s7Q62cl3yWOIp2mYBVLPdk6oVF into /content/dataset/images/train/L32425_eugenio_lopez_12.png...

 80%|████████  | 911/1137 [51:29<11:04,  2.94s/it]

Done.
Downloading 1olgf_b-dwXCcwi3NqB8ysu6lLEM96-nS into /content/dataset/images/train/w05576_juan_wagner_04.png...

 80%|████████  | 912/1137 [51:31<10:15,  2.73s/it]

Done.
Downloading 1QUcEBplVI6KzAkDNA7ASwr9j1yBfAHhJ into /content/dataset/images/train/w05576_juan_wagner_18.png...

 80%|████████  | 913/1137 [51:33<09:57,  2.67s/it]

Done.
Downloading 10c-_Q1xfS-ADkeCwE73ptBH9FMeJRalA into /content/dataset/images/train/s56189_salvador_sanchez_15.jpg...

 80%|████████  | 914/1137 [51:36<09:23,  2.53s/it]

Done.
Downloading 1v6UlEYLkNinDUL3NZBbMtj96Mwj77mtQ into /content/dataset/images/train/L32531_santiago_loza_37.jpg...

 80%|████████  | 915/1137 [51:38<09:34,  2.59s/it]

Done.
Downloading 1yqMYfoD2d3st5_GmMZwzRigc5dqcrqe8 into /content/dataset/images/train/P51926_Leonel_Palermo_11.png...

 81%|████████  | 916/1137 [51:42<10:40,  2.90s/it]

Done.
Downloading 1M80iiq-P4OwlBT1AVttxC6iMhhhXNqT- into /content/dataset/images/train/43237686_Constantino_Ferrucci_27.png...

 81%|████████  | 917/1137 [51:44<10:11,  2.78s/it]

Done.
Downloading 1yJ3MftGcgwXRk43DLh3Cu5vkSGehiyJ9 into /content/dataset/images/train/23451_guido_lorenzettibruera_05.jpg...

 81%|████████  | 918/1137 [51:49<11:40,  3.20s/it]

Done.
Downloading 16gt_VoHjy-PmicZHuCadU-bftpXSZ_PR into /content/dataset/images/train/37494_gustavo_fontana_28.jpg...

 81%|████████  | 919/1137 [51:51<10:58,  3.02s/it]

Done.
Downloading 1fxl7i99UUCnY2PI90fRjRqQxOR9Aze83 into /content/dataset/images/train/41932688_Simon_Revello_7.png...

 81%|████████  | 920/1137 [51:54<11:09,  3.08s/it]

Done.
Downloading 1WfeQnhiPpDgomaGa16gqx-0gjFRr1bdB into /content/dataset/images/train/s56189_salvador_sanchez_264.jpg...

 81%|████████  | 921/1137 [51:57<10:05,  2.80s/it]

Done.
Downloading 1BQsqf3nlsfBy11ZiywjnYO1Lo7ElbJqM into /content/dataset/images/train/37494_gustavo_fontana_01.jpg...

 81%|████████  | 922/1137 [52:00<10:38,  2.97s/it]

Done.
Downloading 1UUDO6Hye-5W1niRVvQ7V8AwiBOIX8_pa into /content/dataset/images/train/s56189_salvador_sanchez_227.jpg...

 81%|████████  | 923/1137 [52:02<09:45,  2.73s/it]

Done.
Downloading 1IILOHJL1-FNACzp0u58iM_n0dq856h9q into /content/dataset/images/train/23451_guido_lorenzettibruera_19.jpg...

 81%|████████▏ | 924/1137 [52:06<11:16,  3.18s/it]

Done.
Downloading 1prRIIFdJlRXY9QgELKxlYi5wLcEIWrlB into /content/dataset/images/train/S57061_Leandro_Salvana_39.png...

 81%|████████▏ | 925/1137 [52:09<10:43,  3.03s/it]

Done.
Downloading 1B72xY8tdZtQRKkWdCB5o1L2cFfUWZbMi into /content/dataset/images/train/7673022c8d5e7e1b0696d6c9d37b7d03.png...

 81%|████████▏ | 926/1137 [52:12<10:05,  2.87s/it]

Done.
Downloading 1mlP2EIOwDPSjOp_yHFSRScqhknS-nMjE into /content/dataset/images/train/A45161_Fabian_Aguirre_27.png...

 82%|████████▏ | 927/1137 [52:14<09:47,  2.80s/it]

Done.
Downloading 1hO-UyXGzuAc38qV3rMU9TgIevagkcfto into /content/dataset/images/train/58513_isaias_garay_25.png...

 82%|████████▏ | 928/1137 [52:16<09:17,  2.67s/it]

Done.
Downloading 1gSg2CO6Pn9rplzLcuCVwgC9MtDNsjkX9 into /content/dataset/images/train/71846_Brisa_Menescaldi_01.png...

 82%|████████▏ | 929/1137 [52:21<11:14,  3.24s/it]

Done.
Downloading 1hkRyI9Sl9x5Rq6YFSdoSHR1TkR0xzMA0 into /content/dataset/images/train/F37605_florencia_fernandez_40.png...

 82%|████████▏ | 930/1137 [52:24<11:04,  3.21s/it]

Done.
Downloading 16FPgJY1rwuB_W5U41zrj0Jp0y9o3u7yW into /content/dataset/images/train/43841031_Enzo_Ferrari_27.png...

 82%|████████▏ | 931/1137 [52:29<12:08,  3.54s/it]

Done.
Downloading 1gSDuK21JghFEe_LMB6r5TCmsGvecoYX4 into /content/dataset/images/train/P_51977_martin_perrone_01.png...

 82%|████████▏ | 932/1137 [52:32<12:10,  3.56s/it]

Done.
Downloading 1SIJ95_QZYIe7lwyVUABVQqD2uQZYrqPP into /content/dataset/images/train/P_51977_martin_perrone_21.png...

 82%|████████▏ | 933/1137 [52:36<12:49,  3.77s/it]

Done.
Downloading 1Rk7QkXfi6DoQAbAQlFhGYrVO-JQxZBHI into /content/dataset/images/train/L32531_santiago_loza_14.jpg...

 82%|████████▏ | 934/1137 [52:40<12:30,  3.70s/it]

Done.
Downloading 1MsAJYBE3o8e6M_9r_kzP8eIl7BGfIXyP into /content/dataset/images/train/s56189_salvador_sanchez_119.jpg...

 82%|████████▏ | 935/1137 [52:42<10:50,  3.22s/it]

Done.
Downloading 1lYgqgJvVrOgl5mph9ZCrHGrFa2gv7Zj9 into /content/dataset/images/train/S57061_Leandro_Salvana_03.png...

 82%|████████▏ | 936/1137 [52:45<10:02,  3.00s/it]

Done.
Downloading 1Uv30d7UDyvlHYSqKBO9KbsNPLzTs-fUX into /content/dataset/images/train/w05576_juan_wagner_12.png...

 82%|████████▏ | 937/1137 [52:47<09:17,  2.79s/it]

Done.
Downloading 1DpAHlcSVv_SdbiijABWkUj6Iq11I_Qf2 into /content/dataset/images/train/g5845_gravifiorino_18.jpeg...

 82%|████████▏ | 938/1137 [52:49<08:52,  2.68s/it]

Done.
Downloading 1HJ6l6h2dLe8PVO_ivCnbYhytPoF718Fa into /content/dataset/images/train/P51926_Leonel_Palermo_07.png...

 83%|████████▎ | 939/1137 [52:54<11:20,  3.44s/it]

Done.
Downloading 1SIWQgA4WN90E0_h6w8cOuLFDMSeQwC4C into /content/dataset/images/train/F37605_florencia_fernandez_49.png...

 83%|████████▎ | 940/1137 [52:58<11:11,  3.41s/it]

Done.
Downloading 1llgP0V2HqA_-PVW2kuDnzhRXMSTtu_o8 into /content/dataset/images/train/37524_augusto_farias_22.jpg...

 83%|████████▎ | 941/1137 [53:02<11:48,  3.62s/it]

Done.
Downloading 1UFdxO1XW4SuMdSR_3i8sIoa7wtE1j5XA into /content/dataset/images/train/s56189_salvador_sanchez_223.jpg...

 83%|████████▎ | 942/1137 [53:04<10:43,  3.30s/it]

Done.
Downloading 1voEKFB14BVjSfGtRJiSpjb-CXujOK5PZ into /content/dataset/images/train/37524_augusto_farias_01.jpg...

 83%|████████▎ | 943/1137 [53:09<11:49,  3.66s/it]

Done.
Downloading 1OizsO37Was8Rb9WjpLlgMe8qE5M4I-Jj into /content/dataset/images/train/90b8cea8d4d18a4df4654b8c3e38bc5c.png...

 83%|████████▎ | 944/1137 [53:12<11:00,  3.42s/it]

Done.
Downloading 19nlE5EV7swbZfWEUYi-zTiKw3tFrPuv5 into /content/dataset/images/train/L32531_santiago_loza_41.jpg...

 83%|████████▎ | 945/1137 [53:15<10:31,  3.29s/it]

Done.
Downloading 1rzQ_miGh4Z39fI6ZVdRx_RAAK3YBkX77 into /content/dataset/images/train/46094_Mateo_Rovere_1.png...

 83%|████████▎ | 946/1137 [53:18<10:03,  3.16s/it]

Done.
Downloading 1MRXYOAyA_tsxB02iR7XthHQuRqRU2o5C into /content/dataset/images/train/s56189_salvador_sanchez_108.jpg...

 83%|████████▎ | 947/1137 [53:20<09:14,  2.92s/it]

Done.
Downloading 1MZoWVBSj_DWlyE5c6v-NJAAG5nKfHOoW into /content/dataset/images/train/93677facff05035c8575473c4a85d165.png...

 83%|████████▎ | 948/1137 [53:23<09:03,  2.87s/it]

Done.
Downloading 1lPvbClmMK6Wf3fVpkMNbcIYwXgHGCH61 into /content/dataset/images/train/L32425_eugenio_lopez_16.png...

 83%|████████▎ | 949/1137 [53:26<09:25,  3.01s/it]

Done.
Downloading 1AGqraXib-i5qLcdS7XlwimbGPMlqMaTK into /content/dataset/images/train/w05576_juan_wagner_09.png...

 84%|████████▎ | 950/1137 [53:28<08:47,  2.82s/it]

Done.
Downloading 16eFjYlutkPtJ3CKtRyqS5va4nmNJvTrI into /content/dataset/images/train/P51951_pablo_pistarelli_08.png...

 84%|████████▎ | 951/1137 [53:31<08:15,  2.66s/it]

Done.
Downloading 1MmcYTPD6h-3GD73JiWHztWLA18Ktg7J7 into /content/dataset/images/train/L32425_eugenio_lopez_04.png...

 84%|████████▎ | 952/1137 [53:34<08:32,  2.77s/it]

Done.
Downloading 1LFWjG3Ls0rmagJbT4WMR-SLrQtxxlbCa into /content/dataset/images/train/03531_mirian_yanez_21.jpeg...

 84%|████████▍ | 953/1137 [53:37<08:30,  2.78s/it]

Done.
Downloading 1XCAligKPgdUCTsMJTlv-I3iAlfeDT40C into /content/dataset/images/train/a056cbf2cd5f3d7d2bd2592760a3d306.png...

 84%|████████▍ | 954/1137 [53:39<08:24,  2.76s/it]

Done.
Downloading 1eV0hMLILfBrRz7gdFum-XSkbkhUDr6tX into /content/dataset/images/train/s56804_alexis_segui_06.png...

 84%|████████▍ | 955/1137 [53:42<08:05,  2.67s/it]

Done.
Downloading 1d3d6Ot21UlT8zWPQZ4ROR866zoZ9Oc9b into /content/dataset/images/train/71846_Brisa_Menescaldi_07.png...

 84%|████████▍ | 956/1137 [53:47<10:39,  3.53s/it]

Done.
Downloading 1sUI6SJyuNQUWimw4H4ROs_5UgTBdaISc into /content/dataset/images/train/g5845_gravifiorino_7.jpeg...

 84%|████████▍ | 957/1137 [53:50<09:23,  3.13s/it]

Done.
Downloading 10kkAcR40v13oVpRE-rWsRSZavQCwKlyt into /content/dataset/images/train/w05576_juan_wagner_31.png...

 84%|████████▍ | 958/1137 [53:52<08:36,  2.89s/it]

Done.
Downloading 1R6r_ZNMvKBC8Ea4WHwpvAgOM0DbA0dl_ into /content/dataset/images/train/s56189_salvador_sanchez_177.jpg...

 84%|████████▍ | 959/1137 [53:54<07:52,  2.65s/it]

Done.
Downloading 1o6UBH0lUma_cbn2g6pRS-ZOe1z8bNevA into /content/dataset/images/train/L32425_eugenio_lopez_27.png...

 84%|████████▍ | 960/1137 [53:56<07:31,  2.55s/it]

Done.
Downloading 12sN5VBYKMQ3foFC0xb4Vw_Q_FOpRCoT4 into /content/dataset/images/train/R-45489_sofiarondini_34.png...

 85%|████████▍ | 961/1137 [53:59<07:41,  2.62s/it]

Done.
Downloading 19q2mG6r8grsugsp9o1z5G3voWrzMejgg into /content/dataset/images/train/46094_Mateo_Rovere_27.png...

 85%|████████▍ | 962/1137 [54:02<07:41,  2.63s/it]

Done.
Downloading 1seERaFJNfCmieuTMKDeFf5WjBC_lh2We into /content/dataset/images/train/51705_micaela_pozzo_21.png...

 85%|████████▍ | 963/1137 [54:05<07:57,  2.74s/it]

Done.
Downloading 15mjeIS0t5TZ1KoCBetjUtJtJpF8UCRFh into /content/dataset/images/train/51951_pablo_pistarelli_18.png...

 85%|████████▍ | 964/1137 [54:08<08:31,  2.96s/it]

Done.
Downloading 1BA6x1I3xQZUhKRnYNP_sQydQwn_TK1QW into /content/dataset/images/train/R-45489_sofiarondini_07.png...

 85%|████████▍ | 965/1137 [54:11<08:10,  2.85s/it]

Done.
Downloading 1XNXxlFk5fUTY8JM9KH2I4iBE4sUfCmNX into /content/dataset/images/train/R-45489_sofiarondini_08.png...

 85%|████████▍ | 966/1137 [54:13<07:51,  2.75s/it]

Done.
Downloading 1pL3WN-VR6RyzPnSp1IYED_Uv1Nolx83b into /content/dataset/images/train/P51926_Leonel_Palermo_13.png...

 85%|████████▌ | 967/1137 [54:17<08:42,  3.08s/it]

Done.
Downloading 1mSDrCqWMULQ4Y8s_SOjL58yf3V_SvH4u into /content/dataset/images/train/03531_mirian_yanez_27.jpeg...

 85%|████████▌ | 968/1137 [54:20<08:27,  3.00s/it]

Done.
Downloading 1d-N2CaHD0BtWcqCcMWzyMrqWWlx6_rLZ into /content/dataset/images/train/R-45489_sofiarondini_30.png...

 85%|████████▌ | 969/1137 [54:22<08:00,  2.86s/it]

Done.
Downloading 1iRWoNAGHIAKws7iRNIisLj1ys5D2Rxmz into /content/dataset/images/train/43237686_Constantino_Ferrucci_28.png...

 85%|████████▌ | 970/1137 [54:26<08:30,  3.06s/it]

Done.
Downloading 1OYiPNcnyyzEaFNmG6PBSbRAnlNgcxy3_ into /content/dataset/images/train/s56189_salvador_sanchez_135.jpg...

 85%|████████▌ | 971/1137 [54:28<07:55,  2.86s/it]

Done.
Downloading 1Csa_QJRBz1vGmWl8KCRiknMN51elLDaH into /content/dataset/images/train/43841031_Enzo_Ferrari_21.png...

 85%|████████▌ | 972/1137 [54:33<09:03,  3.30s/it]

Done.
Downloading 1rBdaK5EdTcfyHwFBdr8f754u-jfjml_c into /content/dataset/images/train/72125_miguel_mussi_05.png...

 86%|████████▌ | 973/1137 [54:36<08:45,  3.20s/it]

Done.
Downloading 1B0IZv-bskzNNPXs4rmLbr8HNO14wkIjT into /content/dataset/images/train/58491_fabio_giampaoli_19.png...

 86%|████████▌ | 974/1137 [54:42<10:51,  4.00s/it]

Done.
Downloading 1yF4Z-L7CfzGf_ZdGcbFGg_ipDflubC3U into /content/dataset/images/train/S57061_Leandro_Salvana_07.png...

 86%|████████▌ | 975/1137 [54:44<09:52,  3.66s/it]

Done.
Downloading 1MLOymMNtvaepCDNX63Lav1UMHfaaqDbz into /content/dataset/images/train/51951_pablo_pistarelli_29.png...

 86%|████████▌ | 976/1137 [54:49<10:16,  3.83s/it]

Done.
Downloading 1N4d7OdTYxafXcXNLv2_DNgQf_FdWDuoA into /content/dataset/images/train/43841031_Enzo_Ferrari_10.png...

 86%|████████▌ | 977/1137 [54:53<10:29,  3.94s/it]

Done.
Downloading 1pVqjJq-lyXAlBa8hGBGs1O7uSKYCtEmz into /content/dataset/images/train/58491_fabio_giampaoli_29.png...

 86%|████████▌ | 978/1137 [54:59<11:55,  4.50s/it]

Done.
Downloading 1fGv3eY-6beOMJse622tlGR3AZ0YlYl20 into /content/dataset/images/train/57096_ramiro_sagrera_25.jpg...

 86%|████████▌ | 979/1137 [55:01<10:27,  3.97s/it]

Done.
Downloading 1YgZBN9XVXBD-X78kSbLM1U5Apjc7m3DE into /content/dataset/images/train/913797f0349e6ee4eee6de47aafb02ab.png...

 86%|████████▌ | 980/1137 [55:05<10:14,  3.91s/it]

Done.
Downloading 1kwDtWmPau_z7lQDidw06O6zXjAJLxSky into /content/dataset/images/train/F37605_florencia_fernandez_26.png...

 86%|████████▋ | 981/1137 [55:08<09:08,  3.51s/it]

Done.
Downloading 1BSkqZu0vWB59KMUjwI3EO670K-p8ZvVd into /content/dataset/images/train/gravifiorino_8.jpeg...

 86%|████████▋ | 982/1137 [55:10<08:06,  3.14s/it]

Done.
Downloading 1_qE2UcWlglMugKs_HJ5KgyjEWOy1J7Qu into /content/dataset/images/train/P51951_pablo_pistarelli_03.png...

 86%|████████▋ | 983/1137 [55:13<07:40,  2.99s/it]

Done.
Downloading 1xopV2Gp3p70-s9M6oAOkzaf7v36MQrKJ into /content/dataset/images/train/23451_guido_lorenzettibruera_08.jpg...

 87%|████████▋ | 984/1137 [55:18<09:38,  3.78s/it]

Done.
Downloading 1Qg_v28-NyegDYMDPlnTJPI1r6tZIWgsC into /content/dataset/images/train/s56189_salvador_sanchez_168.jpg...

 87%|████████▋ | 985/1137 [55:21<08:25,  3.33s/it]

Done.
Downloading 1GszrIexBddNFM583y1XQgmg_VvBfTq9l into /content/dataset/images/train/58491_fabio_giampaoli_08.png...

 87%|████████▋ | 986/1137 [55:26<10:02,  3.99s/it]

Done.
Downloading 1gW-pJB2KGtaDy-GYrdXktXDbrOfDF9vq into /content/dataset/images/train/51934_pablo_pistelli_28.png...

 87%|████████▋ | 987/1137 [55:30<10:10,  4.07s/it]

Done.
Downloading 115quAWxIsK7wKCKT9DIECGa5CEabXSMq into /content/dataset/images/train/58513_isaias_garay_17.png...

 87%|████████▋ | 988/1137 [55:33<09:01,  3.64s/it]

Done.
Downloading 1sBcu2XEU2UsX1bgrEgFExh0LPmuKTxtV into /content/dataset/images/train/58513_isaias_garay_18.png...

 87%|████████▋ | 989/1137 [55:35<07:54,  3.21s/it]

Done.
Downloading 11sq9QMqV0vRnKyA0yfIB3ILgnHDt-r8B into /content/dataset/images/train/S57061_Leandro_Salvana_27.png...

 87%|████████▋ | 990/1137 [55:38<07:15,  2.96s/it]

Done.
Downloading 1qtttMJyv7UJ7nz55LjRfpHdCTpKKlUKI into /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_22.jpg...

 87%|████████▋ | 991/1137 [55:40<06:53,  2.83s/it]

Done.
Downloading 1LQ37YvbyNApFzPP0Y6WoK27LV-93f6B6 into /content/dataset/images/train/s56189_salvador_sanchez_90.jpg...

 87%|████████▋ | 992/1137 [55:42<06:32,  2.71s/it]

Done.
Downloading 1eBXxmHLqLBuCm1KtvzA-y1LXCqcGatbf into /content/dataset/images/train/37494_gustavo_fontana_18.jpg...

 87%|████████▋ | 993/1137 [55:46<07:02,  2.94s/it]

Done.
Downloading 1U79uTKYpRg515IUz3WUmsxLqA8gtsGrb into /content/dataset/images/train/43265_Lucas_Demarre_20.jpg...

 87%|████████▋ | 994/1137 [55:48<06:29,  2.72s/it]

Done.
Downloading 1RSv2RemBK4p0TrrMU_PdtHr8H1_irB7M into /content/dataset/images/train/s56189_salvador_sanchez_181.jpg...

 88%|████████▊ | 995/1137 [55:50<05:58,  2.52s/it]

Done.
Downloading 1QKViCI_HvwUt5nOUEA1VRmv1CoASOFlL into /content/dataset/images/train/s56189_salvador_sanchez_163.jpg...

 88%|████████▊ | 996/1137 [55:52<05:38,  2.40s/it]

Done.
Downloading 1kIK6I2L06aKUHmkHSCE92iCCJHZzTVL- into /content/dataset/images/train/F37605_florencia_fernandez_29.png...

 88%|████████▊ | 997/1137 [55:55<05:50,  2.50s/it]

Done.
Downloading 1cI_aqCYE_3B3XHbcGWt4kWjCDvGSRYmS into /content/dataset/images/train/s56189_salvador_sanchez_3.jpg...

 88%|████████▊ | 998/1137 [55:58<05:49,  2.51s/it]

Done.
Downloading 1k4qJoVyvKjnaIa5E8rulFLWZokhk0BWm into /content/dataset/images/train/F37605_florencia_fernandez_44.png...

 88%|████████▊ | 999/1137 [56:00<05:46,  2.51s/it]

Done.
Downloading 1z4RTfASs5yZ43smsRl-FG8JiKgsJHfjU into /content/dataset/images/train/L32531_santiago_loza_9.jpg...

 88%|████████▊ | 1000/1137 [56:03<06:12,  2.72s/it]

Done.
Downloading 1XroDV7S3-xkiw8I3iISHZ4mYSG_JiBCq into /content/dataset/images/train/52256_daniel_ponce_15.jpeg...

 88%|████████▊ | 1001/1137 [56:06<06:19,  2.79s/it]

Done.
Downloading 11oDbngn6FubWLE-imDBYpSWoQf1hSyqq into /content/dataset/images/train/s56189_salvador_sanchez_24.jpg...

 88%|████████▊ | 1002/1137 [56:08<05:48,  2.58s/it]

Done.
Downloading 1ZRfPFWgG5qOnijNjU2df4kAIoMf3OK6C into /content/dataset/images/train/s56189_salvador_sanchez_308.jpg...

 88%|████████▊ | 1003/1137 [56:11<05:44,  2.57s/it]

Done.
Downloading 1K8gb_JKweACYgYd5BxoUVN25dxHRYSN5 into /content/dataset/images/train/s56189_salvador_sanchez_72.jpg...

 88%|████████▊ | 1004/1137 [56:13<05:32,  2.50s/it]

Done.
Downloading 13WGy6qKCAupt65UXCQghZ7Az1q8CmUS_ into /content/dataset/images/train/23451_guido_lorenzettibruera_27.jpg...

 88%|████████▊ | 1005/1137 [56:18<07:00,  3.19s/it]

Done.
Downloading 1pAX56im5sps7vdTcS8Z8MxeF56p0pZUY into /content/dataset/images/train/52256_daniel_ponce_08.jpeg...

 88%|████████▊ | 1006/1137 [56:20<06:23,  2.93s/it]

Done.
Downloading 1K49TahMW4E2RRHwaTLLqev72X_xCykFV into /content/dataset/images/train/w05576_juan_wagner_20.png...

 89%|████████▊ | 1007/1137 [56:23<05:59,  2.76s/it]

Done.
Downloading 1QIrCI2YGsl-CDUZlvwdmAwikjJTgDZe8 into /content/dataset/images/train/ed8095f182ef6afe56aa3e178d2fd17f.png...

 89%|████████▊ | 1008/1137 [56:26<06:03,  2.82s/it]

Done.
Downloading 1em92nVE3k_jfdw562C0tqrbBkUSathbw into /content/dataset/images/train/L32531_santiago_loza_28.jpg...

 89%|████████▊ | 1009/1137 [56:29<06:10,  2.89s/it]

Done.
Downloading 1O97Vf4NLm3uHWSWdAc0EzLNEhLXsAjgR into /content/dataset/images/train/c3f000d375ce09292e2e0ccce265f022.png...

 89%|████████▉ | 1010/1137 [56:32<06:14,  2.95s/it]

Done.
Downloading 1PfEFNpabAdz0EMFwYbRGrckkODL28tLs into /content/dataset/images/train/F37605_florencia_fernandez_01.png...

 89%|████████▉ | 1011/1137 [56:34<05:59,  2.86s/it]

Done.
Downloading 1PKbkHT32jbM-HkRjbj5kjNascmOmcDOw into /content/dataset/images/train/43265_Lucas_Demarre_28.jpg...

 89%|████████▉ | 1012/1137 [56:37<06:01,  2.89s/it]

Done.
Downloading 1Y_4PSALJgeoAcdj_oyng5-8Qa6gr7Od9 into /content/dataset/images/train/37524_augusto_farias_09.jpg...

 89%|████████▉ | 1013/1137 [56:41<06:26,  3.12s/it]

Done.
Downloading 1iCItUJsz8ovUJvMyWQMcpwqv7p2Ax_-P into /content/dataset/images/train/46019_taiel_raffaeli_03.jpg...

 89%|████████▉ | 1014/1137 [56:44<06:14,  3.05s/it]

Done.
Downloading 1g93MalUSYYFju45r1IzeZfMC2HgTTahG into /content/dataset/images/train/F37605_florencia_fernandez_15.png...

 89%|████████▉ | 1015/1137 [56:47<06:22,  3.13s/it]

Done.
Downloading 1ibY2RPqTJt931TgmKyYjE6IW3NakvnUh into /content/dataset/images/train/37524_augusto_farias_06.jpg...

 89%|████████▉ | 1016/1137 [56:52<07:06,  3.52s/it]

Done.
Downloading 1OL50Vv83JNTv7V9cqlcFqG6BrxxuVRS7 into /content/dataset/images/train/F37605_florencia_fernandez_52.png...

 89%|████████▉ | 1017/1137 [56:54<06:28,  3.24s/it]

Done.
Downloading 1sw1pjqRPkt9dOiggcRVbArxO1FDyihhY into /content/dataset/images/train/F37605_florencia_fernandez_34.png...

 90%|████████▉ | 1018/1137 [56:57<05:58,  3.02s/it]

Done.
Downloading 1feDM9dwwkKUBqyZMXdUVeP5pLvZMX2DT into /content/dataset/images/train/51705_micaela_pozzo_01.png...

 90%|████████▉ | 1019/1137 [57:00<05:48,  2.96s/it]

Done.
Downloading 1m9D4SuW2QeU-KV8VFNdJSCVcubF0Wxue into /content/dataset/images/train/ad13c986542e87aefe1e5bc621bf6c3c.png...

 90%|████████▉ | 1020/1137 [57:02<05:41,  2.92s/it]

Done.
Downloading 1atfT1q-A6qKXzEhQUyBzyeSAINQbzEXO into /content/dataset/images/train/s56189_salvador_sanchez_4.jpg...

 90%|████████▉ | 1021/1137 [57:05<05:15,  2.72s/it]

Done.
Downloading 1EzJXcMI-0ber18PyvNOjZN-3MbvJGoNZ into /content/dataset/images/train/51934_pablo_pistelli_12.png...

 90%|████████▉ | 1022/1137 [57:10<06:32,  3.41s/it]

Done.
Downloading 1QDmxqaqDGxyepe0ZrQF29t1ph9D5v8wC into /content/dataset/images/train/41932688_Simon_Revello_28.png...

 90%|████████▉ | 1023/1137 [57:14<07:05,  3.73s/it]

Done.
Downloading 1LiLoi4d9qMcPPJkgcH8sF5bDKmRD0_Mf into /content/dataset/images/train/P_51977_martin_perrone_31.png...

 90%|█████████ | 1024/1137 [57:17<06:40,  3.54s/it]

Done.
Downloading 1SvNFj-WEAJOQRAk0hN7vUaXZuiDYiaFB into /content/dataset/images/train/S57061_Leandro_Salvana_12.png...

 90%|█████████ | 1025/1137 [57:21<06:33,  3.51s/it]

Done.
Downloading 1zbY8keGejeWJsr8hLzys2WhyvnZZiOcR into /content/dataset/images/train/23451_guido_lorenzettibruera_24.jpg...

 90%|█████████ | 1026/1137 [57:25<06:50,  3.70s/it]

Done.
Downloading 1eS-hLOd_pzzznoRa7bEIMlYGC7h6wuu6 into /content/dataset/images/train/d6fa0e68cba0b4afd68d99c1c8d9c59f.png...

 90%|█████████ | 1027/1137 [57:27<06:05,  3.32s/it]

Done.
Downloading 1WUkyGgTx9PHccywPNZCLAUNw32rJWLYK into /content/dataset/images/train/s56189_salvador_sanchez_262.jpg...

 90%|█████████ | 1028/1137 [57:30<05:26,  3.00s/it]

Done.
Downloading 1xZoGRZmGwpdGFHDyKmVylIxJnxXhLBgt into /content/dataset/images/train/s56804_alexis_segui_02.png...

 91%|█████████ | 1029/1137 [57:32<05:01,  2.79s/it]

Done.
Downloading 1Ir4EqfrAeKyHItKk2b6gxLdPx-AmAWYN into /content/dataset/images/train/s56189_salvador_sanchez_51.jpg...

 91%|█████████ | 1030/1137 [57:34<04:44,  2.66s/it]

Done.
Downloading 19YqOhsVvUVWyeGxFgew0ylCqCyohX_Y1 into /content/dataset/images/train/45d7f692f3ad5a74191f2b002c00f796.png...

 91%|█████████ | 1031/1137 [57:37<04:48,  2.72s/it]

Done.
Downloading 1kiJxI1Wao6o6uSqxyOFRdPqpRzIPt4p8 into /content/dataset/images/train/52256_daniel_ponce_13.jpeg...

 91%|█████████ | 1032/1137 [57:40<04:42,  2.69s/it]

Done.
Downloading 1QzUl2-H0sh-gVIdcmnnjCP0pbm-3wxO5 into /content/dataset/images/train/s56189_salvador_sanchez_174.jpg...

 91%|█████████ | 1033/1137 [57:43<04:43,  2.72s/it]

Done.
Downloading 1u3wj8Qu-3YgRID5Ap1ewhicFLUgopZ6f into /content/dataset/images/train/43265_Lucas_Demarre_17.jpg...

 91%|█████████ | 1034/1137 [57:45<04:29,  2.62s/it]

Done.
Downloading 1CyTwkNhzBZZdDyRs09QUjbRBVw3fJwf- into /content/dataset/images/train/8fcca8d4125c078f68b3265015a1fb45.png...

 91%|█████████ | 1035/1137 [57:48<04:33,  2.68s/it]

Done.
Downloading 1LEwOSnlG9boXCprkEJuEZLQpoyUGeXBT into /content/dataset/images/train/w05576_juan_wagner_30.png...

 91%|█████████ | 1036/1137 [57:50<04:22,  2.59s/it]

Done.
Downloading 1tHQL_Svaq_LiEthzaygg74BuR2zPgdpd into /content/dataset/images/train/f37478_santiago_ferrero_20.jpg...

 91%|█████████ | 1037/1137 [57:55<05:21,  3.22s/it]

Done.
Downloading 1gOuL400Vr-9TTovb1RvHqA2cvv9Lbxm8 into /content/dataset/images/train/gravifiorino_1.jpeg...

 91%|█████████▏| 1038/1137 [57:57<04:44,  2.88s/it]

Done.
Downloading 13YB7_wEd1F6JJ30Tpha3blm6P1ywUZog into /content/dataset/images/train/12394_escandell_ariel_28.jpg...

 91%|█████████▏| 1039/1137 [57:59<04:29,  2.75s/it]

Done.
Downloading 12v7CWM6Rlqpx_aX4TRGKIPQgDbYwEPaX into /content/dataset/images/train/s56189_salvador_sanchez_41.jpg...

 91%|█████████▏| 1040/1137 [58:02<04:09,  2.57s/it]

Done.
Downloading 1xIoGt0nJ1oQCXaT33NhOyNBNiZJq9gFv into /content/dataset/images/train/A45161_Fabian_Aguirre_05.png...

 92%|█████████▏| 1041/1137 [58:04<04:01,  2.51s/it]

Done.
Downloading 1xOgQD_Jh5TYl4nevoqhsWDgyCO__4tlF into /content/dataset/images/train/R-45829_Abril_Rodriguez_27.png...

 92%|█████████▏| 1042/1137 [58:06<03:58,  2.51s/it]

Done.
Downloading 1M8Pv1ntFz3tNk3QJmMBJaCw22JLDyF0D into /content/dataset/images/train/72125_miguel_mussi_32.png...

 92%|█████████▏| 1043/1137 [58:10<04:22,  2.79s/it]

Done.
Downloading 1gfRclLtJwx0W6Jzo34kbNQ0limwm33sm into /content/dataset/images/train/03531_mirian_yanez_17.jpeg...

 92%|█████████▏| 1044/1137 [58:12<04:15,  2.74s/it]

Done.
Downloading 1T1QJA07oLEEAW1HMyCcFPLvS3Inev0pZ into /content/dataset/images/train/s56189_salvador_sanchez_204.jpg...

 92%|█████████▏| 1045/1137 [58:15<03:59,  2.60s/it]

Done.
Downloading 1gesS4_iRKycgWml8SNJKHLCMVrT_2tvo into /content/dataset/images/train/w05576_juan_wagner_26.png...

 92%|█████████▏| 1046/1137 [58:17<03:48,  2.51s/it]

Done.
Downloading 1Kt7j2IVEyzIhmS6f2e8CcekiWwtotc8F into /content/dataset/images/train/P51926_Leonel_Palermo_22.png...

 92%|█████████▏| 1047/1137 [58:21<04:22,  2.91s/it]

Done.
Downloading 1L8UC1IoFlee8QvlDEM0u1P79NDSTwqkE into /content/dataset/images/train/s56189_salvador_sanchez_83.jpg...

 92%|█████████▏| 1048/1137 [58:23<03:59,  2.70s/it]

Done.
Downloading 18h0auqLKz7sXSLJvrAoQ-2pm4Dk0sm_p into /content/dataset/images/train/43265_Lucas_Demarre_10.jpg...

 92%|█████████▏| 1049/1137 [58:25<03:44,  2.56s/it]

Done.
Downloading 1HmZf2DbDQf0Ep8BG5ibMwELAmAnZt4H8 into /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_09.jpg...

 92%|█████████▏| 1050/1137 [58:28<03:52,  2.67s/it]

Done.
Downloading 1xKAVpvcFolHbt9NugbOCjALdzl4YErPS into /content/dataset/images/train/58513_isaias_garay_07.png...

 92%|█████████▏| 1051/1137 [58:31<03:51,  2.69s/it]

Done.
Downloading 10diINpWrjuFuLYLktW3I9uZWAA83OJ-F into /content/dataset/images/train/51659_antonio_peroni_21.jpg...

 93%|█████████▎| 1052/1137 [58:34<03:54,  2.75s/it]

Done.
Downloading 1aO42F0m1tpSvxIx1nFi96J9tpsbUpcba into /content/dataset/images/train/72125_miguel_mussi_09.png...

 93%|█████████▎| 1053/1137 [58:37<03:57,  2.82s/it]

Done.
Downloading 1NcHUfcuf26yTV8NRmTrsjyd6jVuzLtwp into /content/dataset/images/train/P51926_Leonel_Palermo_08.png...

 93%|█████████▎| 1054/1137 [58:41<04:29,  3.24s/it]

Done.
Downloading 13iQFFTTjTtMLEFZmxYroX5Q0-5OLCAxt into /content/dataset/images/train/58491_fabio_giampaoli_27.png...

 93%|█████████▎| 1055/1137 [58:46<05:07,  3.75s/it]

Done.
Downloading 1zzpUVKVH6ntt5P0K5V8jS27tNjBipiAh into /content/dataset/images/train/P_51977_martin_perrone_05.png...

 93%|█████████▎| 1056/1137 [58:50<05:03,  3.75s/it]

Done.
Downloading 19mR7zqfr9gTDQsccixX0g1mVO_gN6dY3 into /content/dataset/images/train/43841031_Enzo_Ferrari_04.png...

 93%|█████████▎| 1057/1137 [58:52<04:33,  3.42s/it]

Done.
Downloading 1zKrDjsTRkU987BBBMDGNEbzP9FHF5bQR into /content/dataset/images/train/L32531_santiago_loza_13.jpg...

 93%|█████████▎| 1058/1137 [58:55<04:19,  3.28s/it]

Done.
Downloading 1cqWxSs_88ocC1HXz-dxcnwG3tEBY0I34 into /content/dataset/images/train/51659_antonio_peroni_26.jpg...

 93%|█████████▎| 1059/1137 [58:58<04:05,  3.14s/it]

Done.
Downloading 18t63jpFxux8NbJ9yttOau_bUHAvB7T1m into /content/dataset/images/train/s56804_alexis_segui_18.png...

 93%|█████████▎| 1060/1137 [59:00<03:40,  2.87s/it]

Done.
Downloading 1jsHGpoZbWJH2bN5XYE0-69kjvRQRSGC6 into /content/dataset/images/train/R-45489_sofiarondini_25.png...

 93%|█████████▎| 1061/1137 [59:03<03:31,  2.78s/it]

Done.
Downloading 1Rxkwu8z3iNkXrFrJOraPyu8ekcO9PY49 into /content/dataset/images/train/s56189_salvador_sanchez_190.jpg...

 93%|█████████▎| 1062/1137 [59:05<03:20,  2.67s/it]

Done.
Downloading 1lUH8nrRLUOoOIcT11YgHOrtSeTGZ5Aa8 into /content/dataset/images/train/L32425_eugenio_lopez_13.png...

 93%|█████████▎| 1063/1137 [59:09<03:28,  2.82s/it]

Done.
Downloading 1OOZv-gOmtUn8btTZBg_W7HqTcuC37zYI into /content/dataset/images/train/R-45489_sofiarondini_15.png...

 94%|█████████▎| 1064/1137 [59:16<05:05,  4.19s/it]

Done.
Downloading 14Hc9B0dht1TDKnbcZt6hN4CZR-kkq3N6 into /content/dataset/images/train/58513_isaias_garay_30.png...

 94%|█████████▎| 1065/1137 [59:18<04:24,  3.68s/it]

Done.
Downloading 1-ebVdY8TKZpcHKosMHolg3q2AJenK8fD into /content/dataset/images/train/51705_micaela_pozzo_07.png...

 94%|█████████▍| 1066/1137 [59:21<03:58,  3.36s/it]

Done.
Downloading 1fbk_CY2bt2H0LsE418r9UhK9E0eEQM0q into /content/dataset/images/train/46019_taiel_raffaeli_09.jpg...

 94%|█████████▍| 1067/1137 [59:24<03:49,  3.28s/it]

Done.
Downloading 1EaJDxklPCZ94WSWv7jHMjS10bVOlJ2xx into /content/dataset/images/train/58912_Timoteo_Garcia_1.jpg...

 94%|█████████▍| 1068/1137 [59:27<03:37,  3.15s/it]

Done.
Downloading 1IrbGidIhNye6pwaLTVTkY2XAuoOuK0vt into /content/dataset/images/train/43265_Lucas_Demarre_30.jpg...

 94%|█████████▍| 1069/1137 [59:29<03:14,  2.87s/it]

Done.
Downloading 1JQxxUxO4VcTRWCCOSYgVltY-FZoiNdHd into /content/dataset/images/train/37494_gustavo_fontana_22.jpg...

 94%|█████████▍| 1070/1137 [59:32<03:15,  2.92s/it]

Done.
Downloading 15Qz50IsfSxWY2CeR_KovcyJHj2R7Yhli into /content/dataset/images/train/F37605_florencia_fernandez_23.png...

 94%|█████████▍| 1071/1137 [59:35<03:07,  2.84s/it]

Done.
Downloading 1uAqtwEN6dOSsyeJi9B6rPfadleHQjsb1 into /content/dataset/images/train/37494_gustavo_fontana_17.jpg...

 94%|█████████▍| 1072/1137 [59:38<03:12,  2.96s/it]

Done.
Downloading 1tOdwMmjcjIoTZiH6MErJwlhg5aES9uBn into /content/dataset/images/train/51705_micaela_pozzo_18.png...

 94%|█████████▍| 1073/1137 [59:41<03:03,  2.86s/it]

Done.
Downloading 1JHyAmV_HRfPRS-NveSGHHU9ey0bbKsZx into /content/dataset/images/train/s56189_salvador_sanchez_56.jpg...

 94%|█████████▍| 1074/1137 [59:43<02:50,  2.70s/it]

Done.
Downloading 1qTDw1OgkCR5ohSas7bCZu0FSCo2V_5PN into /content/dataset/images/train/A45161_Fabian_Aguirre_29.png...

 95%|█████████▍| 1075/1137 [59:46<02:47,  2.71s/it]

Done.
Downloading 1IvmKyrib4u52eK3xpzowGBAVnYacLydg into /content/dataset/images/train/46094_Mateo_Rovere_5.png...

 95%|█████████▍| 1076/1137 [59:49<02:49,  2.77s/it]

Done.
Downloading 1GIE_8IDMg4-tTUeBWrQyb_kfccAa9IpC into /content/dataset/images/train/5b5103028b09e5ba6f8c888eb6323afe.png...

 95%|█████████▍| 1077/1137 [59:51<02:39,  2.66s/it]

Done.
Downloading 18XTzXkVw4qeauHVdmJwMqlzrwJQPbtwm into /content/dataset/images/train/37524_augusto_farias_03.jpg...

 95%|█████████▍| 1078/1137 [59:57<03:35,  3.65s/it]

Done.
Downloading 19hG5a95913QWEbdfJsG6na8-fCwMQ-ys into /content/dataset/images/train/P_51977_martin_perrone_38.png...

 95%|█████████▍| 1079/1137 [1:00:00<03:15,  3.37s/it]

Done.
Downloading 1VgdLj6oe88bkui2AoeDSj5hiTfg_MKP5 into /content/dataset/images/train/s56189_salvador_sanchez_245.jpg...

 95%|█████████▍| 1080/1137 [1:00:02<02:57,  3.11s/it]

Done.
Downloading 1cirrd1cVtxiWJc2hFiOEnMDwYejzhEpE into /content/dataset/images/train/23451_guido_lorenzettibruera_28.jpg...

 95%|█████████▌| 1081/1137 [1:00:07<03:19,  3.56s/it]

Done.
Downloading 1b3qISKcfNbF7gZPJiZxHt98NQ5hZmyJe into /content/dataset/images/train/58912_Timoteo_Garcia_34.jpg...

 95%|█████████▌| 1082/1137 [1:00:10<03:05,  3.37s/it]

Done.
Downloading 1ABsaxA4rlh1QBv43mcQd3lb512HKuT0e into /content/dataset/images/train/L32425_eugenio_lopez_20.png...

 95%|█████████▌| 1083/1137 [1:00:13<02:58,  3.31s/it]

Done.
Downloading 12g--yNJPMg3jwzwxJVJWErvLssEvWUUc into /content/dataset/images/train/s56189_salvador_sanchez_39.jpg...

 95%|█████████▌| 1084/1137 [1:00:15<02:38,  3.00s/it]

Done.
Downloading 1vDZ-B9kmN2BKOYU9fBy8MmMRriWYCgAH into /content/dataset/images/train/57096_ramiro_sagrera_05.jpg...

 95%|█████████▌| 1085/1137 [1:00:18<02:30,  2.90s/it]

Done.
Downloading 1XitvJmtTAgWsaCudtxDKptKoRJF-UX2a into /content/dataset/images/train/s56189_salvador_sanchez_281.jpg...

 96%|█████████▌| 1086/1137 [1:00:20<02:18,  2.72s/it]

Done.
Downloading 1Rv7JOuKFx5kHx5lAmlXhXpovzgBhllcI into /content/dataset/images/train/s56189_salvador_sanchez_188.jpg...

 96%|█████████▌| 1087/1137 [1:00:23<02:08,  2.58s/it]

Done.
Downloading 1aUNOQDotKjCrJfFZZC-DwImx4CRMPO67 into /content/dataset/images/train/F37605_florencia_fernandez_54.png...

 96%|█████████▌| 1088/1137 [1:00:26<02:13,  2.72s/it]

Done.
Downloading 1kV5mVutlDWDTSwTv5j0xR77FA2-CpNJO into /content/dataset/images/train/46094_Mateo_Rovere_28.png...

 96%|█████████▌| 1089/1137 [1:00:28<02:10,  2.72s/it]

Done.
Downloading 1c14bX9ZM9Dy90TesDabT5U6GDx_VJN0S into /content/dataset/images/train/37494_gustavo_fontana_27.jpg...

 96%|█████████▌| 1090/1137 [1:00:32<02:27,  3.14s/it]

Done.
Downloading 12S2NLCXNw4qAtkMWMV1vjL-0u1yFdsT3 into /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_27.jpg...

 96%|█████████▌| 1091/1137 [1:00:36<02:26,  3.20s/it]

Done.
Downloading 18sDXVB-gvKNlwlsx2AwsKs--WQHUPo14 into /content/dataset/images/train/51951_pablo_pistarelli_12.png...

 96%|█████████▌| 1092/1137 [1:00:39<02:21,  3.14s/it]

Done.
Downloading 1mTdRd2DYbIv7pl8xi17pK8aKlG8Kf02W into /content/dataset/images/train/s56804_alexis_segui_10.png...

 96%|█████████▌| 1093/1137 [1:00:42<02:14,  3.06s/it]

Done.
Downloading 1inYZVW01uC2q2mgd2XPAUUTZsvR6woES into /content/dataset/images/train/58912_Timoteo_Garcia_27.jpg...

 96%|█████████▌| 1094/1137 [1:00:45<02:13,  3.12s/it]

Done.
Downloading 1RcKtN1QCfobAcKVGDH3vOqwbQ9KowKvm into /content/dataset/images/train/s56189_salvador_sanchez_184.jpg...

 96%|█████████▋| 1095/1137 [1:00:47<02:00,  2.86s/it]

Done.
Downloading 1q7Uybwp67p7s405c14eeFJ-RCj7VBB1J into /content/dataset/images/train/72125_miguel_mussi_16.png...

 96%|█████████▋| 1096/1137 [1:00:50<01:53,  2.76s/it]

Done.
Downloading 1TzzU9yUnZDeLNPA4A59K0PP9dLAPQi0y into /content/dataset/images/train/s56189_salvador_sanchez_221.jpg...

 96%|█████████▋| 1097/1137 [1:00:52<01:46,  2.66s/it]

Done.
Downloading 1ewpoodU4U0STskX6k6Ko_uiuThDvo9zC into /content/dataset/images/train/72125_miguel_mussi_06.png...

 97%|█████████▋| 1098/1137 [1:00:55<01:44,  2.67s/it]

Done.
Downloading 1xXqIz3xqvNBJcInhFlFZl7JSe42Luxfm into /content/dataset/images/train/72125_miguel_mussi_22.png...

 97%|█████████▋| 1099/1137 [1:00:57<01:40,  2.65s/it]

Done.
Downloading 1ZYiayjTE2nTIO4vevmFGbcxW4xxXtk7v into /content/dataset/images/train/s56189_salvador_sanchez_312.jpg...

 97%|█████████▋| 1100/1137 [1:01:00<01:34,  2.55s/it]

Done.
Downloading 1-hvHOBZo82-VJJIK8N-YdAGYkN-jPGqA into /content/dataset/images/train/P51926_Leonel_Palermo_27.png...

 97%|█████████▋| 1101/1137 [1:01:04<01:50,  3.07s/it]

Done.
Downloading 1BBbgY2Wb40Mx0viqCMMGujB0vejmXuS0 into /content/dataset/images/train/51705_micaela_pozzo_26.png...

 97%|█████████▋| 1102/1137 [1:01:07<01:41,  2.90s/it]

Done.
Downloading 1WWJxP0S7MPpCV1YwDy7GghPL_IISMwJe into /content/dataset/images/train/03531_mirian_yanez_12.jpeg...

 97%|█████████▋| 1103/1137 [1:01:09<01:36,  2.84s/it]

Done.
Downloading 1vtLX8A7-z46W0v2ucDVHXbzwjmOWHvRo into /content/dataset/images/train/58912_Timoteo_Garcia_9.jpg...

 97%|█████████▋| 1104/1137 [1:01:12<01:32,  2.80s/it]

Done.
Downloading 19T8wcYhsVvBgmabY5lT8J4dtiujNDliq into /content/dataset/images/train/72125_miguel_mussi_02.png...

 97%|█████████▋| 1105/1137 [1:01:14<01:27,  2.73s/it]

Done.
Downloading 1RXXfduc05jlvB3S6rfg36_RXgPpksJCo into /content/dataset/images/train/s56189_salvador_sanchez_183.jpg...

 97%|█████████▋| 1106/1137 [1:01:17<01:19,  2.55s/it]

Done.
Downloading 11wq6qyhtG-OIJtlxw4JX8H2NV-d7yFzy into /content/dataset/images/train/s56189_salvador_sanchez_29.jpg...

 97%|█████████▋| 1107/1137 [1:01:19<01:12,  2.42s/it]

Done.
Downloading 1TXoBlMuaHdfdxVT1ZfcdJoYCwyg9CBrq into /content/dataset/images/train/s56189_salvador_sanchez_213.jpg...

 97%|█████████▋| 1108/1137 [1:01:21<01:09,  2.41s/it]

Done.
Downloading 1Y84xDM2LFnBV5QZFqKPgXvrGm5819DHB into /content/dataset/images/train/s56189_salvador_sanchez_285.jpg...

 98%|█████████▊| 1109/1137 [1:01:24<01:11,  2.54s/it]

Done.
Downloading 13AyRVHLQHLc5FaLAvCLaPRdIn6ZQ-Dil into /content/dataset/images/train/s56189_salvador_sanchez_44.jpg...

 98%|█████████▊| 1110/1137 [1:01:26<01:05,  2.44s/it]

Done.
Downloading 1VON_WHMI_DlP7-T-PG6DJMtsWWFf6SLe into /content/dataset/images/train/S57061_Leandro_Salvana_45.png...

 98%|█████████▊| 1111/1137 [1:01:29<01:05,  2.50s/it]

Done.
Downloading 1pXnjKXJTtl_qZXnexTtZ239173Vlxm8k into /content/dataset/images/train/A45161_Fabian_Aguirre_15.png...

 98%|█████████▊| 1112/1137 [1:01:32<01:04,  2.57s/it]

Done.
Downloading 1ZbkIscl_wulXLjVVFK9Xj0Xrcy0k0uCo into /content/dataset/images/train/41932688_Simon_Revello_1.png...

 98%|█████████▊| 1113/1137 [1:02:00<04:04, 10.20s/it]

Done.
Downloading 1NQskU5JZOqSxhCa4Kup5qIUF6LF_dudl into /content/dataset/images/train/s56189_salvador_sanchez_125.jpg...

 98%|█████████▊| 1114/1137 [1:02:02<03:01,  7.87s/it]

Done.
Downloading 17vjbrYKeoUhBRI2c7ZRWnuI3ImobC-gp into /content/dataset/images/train/12394_escandell_ariel_20.jpg...

 98%|█████████▊| 1115/1137 [1:02:06<02:24,  6.58s/it]

Done.
Downloading 15dy6SSioaus-ky6uWND9_glK6AdylqDw into /content/dataset/images/train/72125_miguel_mussi_15.png...

 98%|█████████▊| 1116/1137 [1:02:08<01:54,  5.47s/it]

Done.
Downloading 1YkM9A9sF3E4r7s_nvj3VebdxE0okbmTT into /content/dataset/images/train/s56189_salvador_sanchez_299.jpg...

 98%|█████████▊| 1117/1137 [1:02:11<01:31,  4.56s/it]

Done.
Downloading 1N9Pm8MzJOrpetMH-jlqkaj94_vaR1T9o into /content/dataset/images/train/s56189_salvador_sanchez_121.jpg...

 98%|█████████▊| 1118/1137 [1:02:13<01:14,  3.90s/it]

Done.
Downloading 1K7obCzJgfBKlSxfpjyEEMmLkryZzLKsR into /content/dataset/images/train/s56189_salvador_sanchez_73.jpg...

 98%|█████████▊| 1119/1137 [1:02:16<01:01,  3.41s/it]

Done.
Downloading 1Zq7TPHlTsS0znhoKDqxA9GPxci8rq-tV into /content/dataset/images/train/s56189_salvador_sanchez_317.jpg...

 99%|█████████▊| 1120/1137 [1:02:18<00:51,  3.02s/it]

Done.
Downloading 1MLaWsgPoXZsxBeicTeFTXWI0Aw2Na5bs into /content/dataset/images/train/s56804_alexis_segui_23.png...

 99%|█████████▊| 1121/1137 [1:02:20<00:45,  2.87s/it]

Done.
Downloading 17yAsMCXR-lYmhXdSKksb6Dl39z1t4EIN into /content/dataset/images/train/F37605_florencia_fernandez_25.png...

 99%|█████████▊| 1122/1137 [1:02:24<00:45,  3.05s/it]

Done.
Downloading 1WYqF9fvSP8ii6-BgAgkv_nnyCEfRf49G into /content/dataset/images/train/R-45829_Abril_Rodriguez_29.png...

 99%|█████████▉| 1123/1137 [1:02:26<00:40,  2.89s/it]

Done.
Downloading 1Yu5vxrnpFnXc7q7J3n4nUuE0FCmXav8_ into /content/dataset/images/train/23451_guido_lorenzettibruera_02.jpg...

 99%|█████████▉| 1124/1137 [1:02:30<00:42,  3.27s/it]

Done.
Downloading 1EHgDa6JOMZ7oLjBl7DAFfKTjsVoi5bDH into /content/dataset/images/train/43265_Lucas_Demarre_13.jpg...

 99%|█████████▉| 1125/1137 [1:02:33<00:37,  3.14s/it]

Done.
Downloading 1KEixGBHOOEkJqxQA01SEoig0PcdWa3Qw into /content/dataset/images/train/s56189_salvador_sanchez_75.jpg...

 99%|█████████▉| 1126/1137 [1:02:35<00:31,  2.86s/it]

Done.
Downloading 1U-_H5mv5Z7A3Ck5yUPt2BHmKgNFcZYWo into /content/dataset/images/train/L32531_santiago_loza_19.jpg...

 99%|█████████▉| 1127/1137 [1:02:39<00:31,  3.13s/it]

Done.
Downloading 1VOssHPEomj7dNCO49v6V1oDIufz8XWr1 into /content/dataset/images/train/s56189_salvador_sanchez_236.jpg...

 99%|█████████▉| 1128/1137 [1:02:42<00:27,  3.05s/it]

Done.
Downloading 1RewHyKyMr_-m1FXWdHhgsA6G5wBVKUP5 into /content/dataset/images/train/s56189_salvador_sanchez_185.jpg...

 99%|█████████▉| 1129/1137 [1:02:44<00:23,  2.89s/it]

Done.
Downloading 1qn5AMFlDQ3jzcZxUfBvIFIBf7ixlyOpR into /content/dataset/images/train/41932688_Simon_Revello_24.png...

 99%|█████████▉| 1130/1137 [1:02:49<00:24,  3.46s/it]

Done.
Downloading 14b0RMB-7b7ep4LUeDTH48OYwJHttSXWC into /content/dataset/images/train/51934_pablo_pistelli_18.png...

 99%|█████████▉| 1131/1137 [1:02:55<00:25,  4.27s/it]

Done.
Downloading 1AuhzQYXoihnPIHCvtTRF3ZXE1m_uc7em into /content/dataset/images/train/s56804_alexis_segui_07.png...

100%|█████████▉| 1132/1137 [1:02:58<00:18,  3.67s/it]

Done.
Downloading 1h7rWTx9T7PsXC1etcQWneKPGFNdRNW7f into /content/dataset/images/train/51934_pablo_pistelli_24.png...

100%|█████████▉| 1133/1137 [1:03:03<00:16,  4.10s/it]

Done.
Downloading 1pnv0VC7ZCsTr9nFWPhE_B16bnfDk4av- into /content/dataset/images/train/41932688_Simon_Revello_30.png...

100%|█████████▉| 1134/1137 [1:03:07<00:12,  4.02s/it]

Done.
Downloading 1_EAXz2VGUcHErCvfzUTX6j0eyNLE7IgO into /content/dataset/images/train/R-45829_Abril_Rodriguez_01.png...

100%|█████████▉| 1135/1137 [1:03:09<00:07,  3.57s/it]

Done.
Downloading 1H8x7QCDsM1aRGa5DwP5lOwA_X0sq1Ubh into /content/dataset/images/train/43237686_Constantino_Ferrucci_19.png...

100%|█████████▉| 1136/1137 [1:03:13<00:03,  3.56s/it]

Done.
Downloading 1MVW_xSs_liI2KYSvwwjKqhYJba6DB_Ti into /content/dataset/images/train/46019_taiel_raffaeli_28.jpg...

100%|██████████| 1137/1137 [1:03:16<00:00,  3.34s/it]

Done.

  0%|          | 0/488 [00:00<?, ?it/s]

Downloading 1cqedzno5dQLX0DQbSJBsh-pZXRpGf-Kp into /content/dataset/images/val/A45161_Fabian_Aguirre_09.png...

  0%|          | 1/488 [00:02<18:34,  2.29s/it]

Done.
Downloading 1_9eTEV2uhBdSeDokMM6RguSSqFMMDkKN into /content/dataset/images/val/43237686_Constantino_Ferrucci_11.png...

  0%|          | 2/488 [00:05<21:32,  2.66s/it]

Done.
Downloading 1QNZx2Zg1Hj-eJtPKtYSfu5p3aagUYxDw into /content/dataset/images/val/12394_escandell_ariel_21.jpg...

  1%|          | 3/488 [00:08<22:49,  2.82s/it]

Done.
Downloading 1h_0LnuKrHCesViZuoJnbfDa-cPuXLlau into /content/dataset/images/val/58513_isaias_garay_22.png...

  1%|          | 4/488 [00:10<20:39,  2.56s/it]

Done.
Downloading 1SPShwToOAfkHpvk-j214DNFnGJTBS_We into /content/dataset/images/val/s56189_salvador_sanchez_196.jpg...

  1%|          | 5/488 [00:12<19:09,  2.38s/it]

Done.
Downloading 105MR5Za33g67yr6Etfg5aN7HDJuayCyo into /content/dataset/images/val/58912_Timoteo_Garcia_23.jpg...

  1%|          | 6/488 [00:15<21:06,  2.63s/it]

Done.
Downloading 1NzjQg9KagoJ1hk7TwrOMwo8F36gLHt9V into /content/dataset/images/val/46019_taiel_raffaeli_11.jpg...

  1%|▏         | 7/488 [00:19<23:19,  2.91s/it]

Done.
Downloading 1lDWo9U-m6CjE0SucZ5XV6321wD5UvMil into /content/dataset/images/val/g5845_gravifiorino_30.jpeg...

  2%|▏         | 8/488 [00:21<22:39,  2.83s/it]

Done.
Downloading 1U45OGbTof9Q1pIxxwQ8PB4X2wd0Kuhie into /content/dataset/images/val/s56189_salvador_sanchez_220.jpg...

  2%|▏         | 9/488 [00:24<21:28,  2.69s/it]

Done.
Downloading 1m6G66uBpwGPxxMFapquuoFPdTSwwkmXw into /content/dataset/images/val/41932688_Simon_Revello_6.png...

  2%|▏         | 10/488 [00:28<25:53,  3.25s/it]

Done.
Downloading 1jm0iWKRImoWMRvh6LNjhpmQaDYgtc1RZ into /content/dataset/images/val/43841031_Enzo_Ferrari_08.png...

  2%|▏         | 11/488 [00:33<29:39,  3.73s/it]

Done.
Downloading 1g5Jq5nzaGfq1lhtElA-tPoFoX6hzJj4f into /content/dataset/images/val/12394_escandell_ariel_26.jpg...

  2%|▏         | 12/488 [00:36<29:12,  3.68s/it]

Done.
Downloading 1raIzq2Yk1nUpwmQqmocvjwhUtienZ8BX into /content/dataset/images/val/L32531_santiago_loza_15.jpg...

  3%|▎         | 13/488 [00:40<28:18,  3.58s/it]

Done.
Downloading 1KG9o3vQnGz3ZR7Umfoh4UPQZ2oFT4Zv9 into /content/dataset/images/val/P51926_Leonel_Palermo_17.png...

  3%|▎         | 14/488 [00:43<28:05,  3.56s/it]

Done.
Downloading 1F8f2bx1BYFBBVWLHDbZHIc1YAqJY0eNq into /content/dataset/images/val/F37605_florencia_fernandez_07.png...

  3%|▎         | 15/488 [00:46<25:32,  3.24s/it]

Done.
Downloading 13DJ-V_4OAVMJatWH-wIBK3IoHOgu6K2j into /content/dataset/images/val/52256_daniel_ponce_23.jpeg...

  3%|▎         | 16/488 [00:49<25:29,  3.24s/it]

Done.
Downloading 1AWlU1NfgIrQNC0wukiZm8iq86vfyFmah into /content/dataset/images/val/43841031_Enzo_Ferrari_24.png...

  3%|▎         | 17/488 [00:54<28:18,  3.61s/it]

Done.
Downloading 17ZQJFxzMnxK1UWqEvDG5ouy9X_s7fZA5 into /content/dataset/images/val/57096_ramiro_sagrera_15.jpg...

  4%|▎         | 18/488 [00:56<26:09,  3.34s/it]

Done.
Downloading 1QFl53GAWukhGEzQdvDxP6gIlPkCFkmf5 into /content/dataset/images/val/s56189_salvador_sanchez_159.jpg...

  4%|▍         | 19/488 [00:59<23:37,  3.02s/it]

Done.
Downloading 1ThTd9ScRcYZ7Uo-fGsm3RlmdscVsDRcc into /content/dataset/images/val/s56189_salvador_sanchez_212.jpg...

  4%|▍         | 20/488 [01:01<21:33,  2.76s/it]

Done.
Downloading 1bCzqyBdP46vwNSd56pfEOeXR6B_YkvMU into /content/dataset/images/val/51934_pablo_pistelli_01.png...

  4%|▍         | 21/488 [01:06<27:07,  3.48s/it]

Done.
Downloading 1p5ejTSPCODZ9_ha7xHtzgOpogqn_6jdl into /content/dataset/images/val/43237686_Constantino_Ferrucci_23.png...

  5%|▍         | 22/488 [01:08<25:02,  3.22s/it]

Done.
Downloading 1MavWojZnv5mcX5V2gld8F1qhqOSsweiF into /content/dataset/images/val/s56189_salvador_sanchez_113.jpg...

  5%|▍         | 23/488 [01:11<22:46,  2.94s/it]

Done.
Downloading 1mN_cMq05sR9Z1_gRonUTv56Ut0zS7oAZ into /content/dataset/images/val/P_51977_martin_perrone_22.png...

  5%|▍         | 24/488 [01:15<24:54,  3.22s/it]

Done.
Downloading 1mSWpHXO6O5jFVC-CXCwTguK1KCOjO6ny into /content/dataset/images/val/58912_Timoteo_Garcia_13.jpg...

  5%|▌         | 25/488 [01:18<25:01,  3.24s/it]

Done.
Downloading 1o_tQLlX6LZBh2TA297xkdvTHaitFypTN into /content/dataset/images/val/23451_guido_lorenzettibruera_01.jpg...

  5%|▌         | 26/488 [01:23<29:23,  3.82s/it]

Done.
Downloading 1YcR79zNvGCCOuqruM7zavnpx6r9odqZG into /content/dataset/images/val/46094_Mateo_Rovere_30.png...

  6%|▌         | 27/488 [01:27<29:57,  3.90s/it]

Done.
Downloading 1spFcMp9QuWtPLT2EKopT6GP1NxbB_A58 into /content/dataset/images/val/32d8cd3cc1799c7e150bade5617735ce.png...

  6%|▌         | 28/488 [01:30<27:49,  3.63s/it]

Done.
Downloading 1p3QYMVrtjBhyQeerksU06ifKfMYCOG3Q into /content/dataset/images/val/72125_miguel_mussi_30.png...

  6%|▌         | 29/488 [01:33<25:21,  3.32s/it]

Done.
Downloading 16iNRcOrXDNuNUlPWpMBJrPkL1447qCt3 into /content/dataset/images/val/F37605_florencia_fernandez_30.png...

  6%|▌         | 30/488 [01:35<23:14,  3.05s/it]

Done.
Downloading 1z75FjvXGRjaOcRewPIUpWUNwDikv8Rro into /content/dataset/images/val/F37605_florencia_fernandez_19.png...

  6%|▋         | 31/488 [01:38<22:33,  2.96s/it]

Done.
Downloading 1dMV0Xm8nHTlxl5TO8eiO5mdeyc81B8By into /content/dataset/images/val/c09974547d6736ab3d80f4e5ef49498b.png...

  7%|▋         | 32/488 [01:41<22:32,  2.97s/it]

Done.
Downloading 1QnCIQ4LDsX2rtkHHE2Jbk1N-UW6gBsHg into /content/dataset/images/val/58912_Timoteo_Garcia_28.jpg...

  7%|▋         | 33/488 [01:44<22:37,  2.98s/it]

Done.
Downloading 1HMuqnnrOI449rGhyJ7Tu9JDZeXwb5HHy into /content/dataset/images/val/58491_fabio_giampaoli_06.png...

  7%|▋         | 34/488 [01:48<24:31,  3.24s/it]

Done.
Downloading 1BkgzAC7p1Jgt0YTImmvoQr2ubn4vwne2 into /content/dataset/images/val/s56804_alexis_segui_09.png...

  7%|▋         | 35/488 [01:50<22:47,  3.02s/it]

Done.
Downloading 1lyZTe0mEn01-BpqIaXqzhpL5QkJyQEeo into /content/dataset/images/val/37524_augusto_farias_02.jpg...

  7%|▋         | 36/488 [01:55<25:34,  3.39s/it]

Done.
Downloading 1WIOstltt1ru5A1RK-FX_8rhGioawKeoY into /content/dataset/images/val/s56189_salvador_sanchez_257.jpg...

  8%|▊         | 37/488 [01:57<24:26,  3.25s/it]

Done.
Downloading 1vRQb-lQq63erWLwMqfYWdkFVMF491y6j into /content/dataset/images/val/23451_guido_lorenzettibruera_17.jpg...

  8%|▊         | 38/488 [02:02<26:57,  3.59s/it]

Done.
Downloading 15BWrX0kvZL0eb3SHExtQjfxwhZ3H3NQT into /content/dataset/images/val/51659_antonio_peroni_01.jpg...

  8%|▊         | 39/488 [02:05<25:34,  3.42s/it]

Done.
Downloading 1OpmkoV1ApgoW7v7-VIrcVoqyhLtS5nx2 into /content/dataset/images/val/b28e34fb755f51ab4d37d64db732151b.png...

  8%|▊         | 40/488 [02:08<25:19,  3.39s/it]

Done.
Downloading 1PuptRxy6MZxilnDOD9GOUJvljerq2oLn into /content/dataset/images/val/s56189_salvador_sanchez_154.jpg...

  8%|▊         | 41/488 [02:11<22:51,  3.07s/it]

Done.
Downloading 1N6Qsb5yxygvkqB3mpWXxQR4855zQN4k9 into /content/dataset/images/val/F37605_florencia_fernandez_14.png...

  9%|▊         | 42/488 [02:13<22:34,  3.04s/it]

Done.
Downloading 1ItMh7AgVDkdZkGjRArXZquPwlU9ObI_O into /content/dataset/images/val/s56189_salvador_sanchez_61.jpg...

  9%|▉         | 43/488 [02:16<20:52,  2.82s/it]

Done.
Downloading 1S7kUW5t2HYPkq08VyRid9xWdxAE6mwui into /content/dataset/images/val/46094_Mateo_Rovere_13.png...

  9%|▉         | 44/488 [02:20<23:38,  3.20s/it]

Done.
Downloading 1ztopEYPhjCs7g-38zI3eaOHL22ctPhuz into /content/dataset/images/val/P_51977_martin_perrone_15.png...

  9%|▉         | 45/488 [02:26<29:09,  3.95s/it]

Done.
Downloading 14lfRVFx5DTYaQPCN_BkZjxx_rXPk97D4 into /content/dataset/images/val/g5845_gravifiorino_19.jpeg...

  9%|▉         | 46/488 [02:28<25:00,  3.40s/it]

Done.
Downloading 1EKzOQknkrJKoxQW7naelYQyx1Hw7sFgU into /content/dataset/images/val/52256_daniel_ponce_17.jpeg...

 10%|▉         | 47/488 [02:30<23:16,  3.17s/it]

Done.
Downloading 1Ph9W3aA9DpGA7xtAOa9_zWMdyEa05pgm into /content/dataset/images/val/w05576_juan_wagner_27.png...

 10%|▉         | 48/488 [02:33<23:00,  3.14s/it]

Done.
Downloading 1ZefRcsPdAg4sbzM95bdP07K2Kk4MONkH into /content/dataset/images/val/g5845_gravifiorino_24.jpeg...

 10%|█         | 49/488 [02:36<21:29,  2.94s/it]

Done.
Downloading 1Ok1p0dOOlUCbf5QzsC8t5kp97YeIW49D into /content/dataset/images/val/43265_Lucas_Demarre_19.jpg...

 10%|█         | 50/488 [02:38<19:45,  2.71s/it]

Done.
Downloading 1dZnFQGparmhvVR48WbfZ_AtySWFs98oC into /content/dataset/images/val/w05576_juan_wagner_29.png...

 10%|█         | 51/488 [02:40<18:46,  2.58s/it]

Done.
Downloading 1XgkiEH8gnq23aB92WnfjKD-BQvbzuJhW into /content/dataset/images/val/f37478_santiago_ferrero_27.jpg...

 11%|█         | 52/488 [02:42<17:50,  2.46s/it]

Done.
Downloading 1LE3uVZZkDkTThnlkSMqID33DytZbVFkM into /content/dataset/images/val/s56189_salvador_sanchez_89.jpg...

 11%|█         | 53/488 [02:45<16:54,  2.33s/it]

Done.
Downloading 1_GVqwfvhEscGAPMNoiV_oyDFHOZsioyt into /content/dataset/images/val/51951_pablo_pistarelli_13.png...

 11%|█         | 54/488 [02:48<19:17,  2.67s/it]

Done.
Downloading 1wnvc3ybG-rdAwVkZ93E9ohcH4n1F8ytH into /content/dataset/images/val/23451_guido_lorenzettibruera_03.jpg...

 11%|█▏        | 55/488 [02:52<22:17,  3.09s/it]

Done.
Downloading 1OtFu9e8j1fmTIzOxhSJbzB3cn1SaGm4z into /content/dataset/images/val/s56189_salvador_sanchez_143.jpg...

 11%|█▏        | 56/488 [02:54<20:47,  2.89s/it]

Done.
Downloading 1C4kwA-zvBi6MW4wKChgHRRZnN5eCzK7a into /content/dataset/images/val/952dd7f9eb8b5068796db0410ade8a41.png...

 12%|█▏        | 57/488 [02:57<20:35,  2.87s/it]

Done.
Downloading 1DlpsbbPXRL5iYfI750ZKFGKtGUBA7L5Q into /content/dataset/images/val/51934_pablo_pistelli_22.png...

 12%|█▏        | 58/488 [03:03<26:39,  3.72s/it]

Done.
Downloading 1XIrl0q38v0ECkKEwU-ihrsA1OOz3o9iX into /content/dataset/images/val/s56189_salvador_sanchez_276.jpg...

 12%|█▏        | 59/488 [03:05<23:52,  3.34s/it]

Done.
Downloading 1A2m2ffEnVKK_eBhHOFysSBfd4NUGZ2fb into /content/dataset/images/val/P51951_pablo_pistarelli_09.png...

 12%|█▏        | 60/488 [03:09<23:40,  3.32s/it]

Done.
Downloading 11QrkA3v6b0Iyz5cHD9-05_aVABKYAARC into /content/dataset/images/val/F37605_florencia_fernandez_11.png...

 12%|█▎        | 61/488 [03:12<23:11,  3.26s/it]

Done.
Downloading 1wadxAwPVgOO-AbzDHYYXLbCM1cxFV8Jy into /content/dataset/images/val/51705_micaela_pozzo_22.png...

 13%|█▎        | 62/488 [03:15<22:08,  3.12s/it]

Done.
Downloading 1YMWL9sf5zLPd1GK5E1mlo7NibYHLrsHC into /content/dataset/images/val/s56189_salvador_sanchez_295.jpg...

 13%|█▎        | 63/488 [03:17<20:16,  2.86s/it]

Done.
Downloading 17DzfYLriI6bRxOz9MRwOUI2N8t1xLajm into /content/dataset/images/val/R-45829_Abril_Rodriguez_09.png...

 13%|█▎        | 64/488 [03:19<19:24,  2.75s/it]

Done.
Downloading 1ZixySyZKjJiPrzIoCPQNj2inuFdVcyG6 into /content/dataset/images/val/s56189_salvador_sanchez_314.jpg...

 13%|█▎        | 65/488 [03:22<19:24,  2.75s/it]

Done.
Downloading 1nosbVCfKKzgTAM18T3OzgIK3iq1utMpV into /content/dataset/images/val/52256_daniel_ponce_03.jpeg...

 14%|█▎        | 66/488 [03:25<19:33,  2.78s/it]

Done.
Downloading 1gVOIMbTr1EQYtovO0gCbzW5SBKgOKR-0 into /content/dataset/images/val/58912_Timoteo_Garcia_32.jpg...

 14%|█▎        | 67/488 [03:28<20:26,  2.91s/it]

Done.
Downloading 1gSExfmw0igdN4MVImPhHJSoIvxaswphd into /content/dataset/images/val/46094_Mateo_Rovere_6.png...

 14%|█▍        | 68/488 [03:31<20:03,  2.87s/it]

Done.
Downloading 1zbww4g4ZtTnool54UmZtCSFAoVgKbu1g into /content/dataset/images/val/S57061_Leandro_Salvana_33.png...

 14%|█▍        | 69/488 [03:34<19:49,  2.84s/it]

Done.
Downloading 11YcJdNFCP-X0cLyf9eRwOfVc7iL1_QuW into /content/dataset/images/val/s56189_salvador_sanchez_23.jpg...

 14%|█▍        | 70/488 [03:36<18:27,  2.65s/it]

Done.
Downloading 1i3G8sFAaO6Zwoeipz1Fe4uqk9TxlBuVt into /content/dataset/images/val/S57061_Leandro_Salvana_04.png...

 15%|█▍        | 71/488 [03:38<18:08,  2.61s/it]

Done.
Downloading 12ZenfbWXmXb-014bq22qDWcKDut3Zw-m into /content/dataset/images/val/58513_isaias_garay_08.png...

 15%|█▍        | 72/488 [03:41<17:12,  2.48s/it]

Done.
Downloading 1hg3gJkTKPUD5jSEFIxo_Xc7Q_9S1RPrm into /content/dataset/images/val/3a32cc04e4d840bc441431183e08d018.png...

 15%|█▍        | 73/488 [03:43<17:59,  2.60s/it]

Done.
Downloading 1Qi2JFOGrvhewYbMwhsddIaPjXby6wS0m into /content/dataset/images/val/s56189_salvador_sanchez_167.jpg...

 15%|█▌        | 74/488 [03:46<17:24,  2.52s/it]

Done.
Downloading 1T13PufHrW0qZhiIEg7jkHpEORuOQeU3B into /content/dataset/images/val/f81f9fe13e4b6e7c55be2e358056eb9a.png...

 15%|█▌        | 75/488 [03:50<19:57,  2.90s/it]

Done.
Downloading 1roVVGYQaTLmhIZpYMUMsl8hC8p0AQZWi into /content/dataset/images/val/23451_guido_lorenzettibruera_20.jpg...

 16%|█▌        | 76/488 [03:55<24:41,  3.60s/it]

Done.
Downloading 1Tw23Yi3Kp9hoAIA4Ihay7j-mnD_wMl42 into /content/dataset/images/val/s56189_salvador_sanchez_219.jpg...

 16%|█▌        | 77/488 [03:57<22:29,  3.28s/it]

Done.
Downloading 1RInJrtaRti_-A70VIAXkQOBJsouFV5ea into /content/dataset/images/val/23451_guido_lorenzettibruera_07.jpg...

 16%|█▌        | 78/488 [04:02<24:57,  3.65s/it]

Done.
Downloading 1fHAarQp2kzKRQ1pvNl6642sGhQGKU2n6 into /content/dataset/images/val/33219c585c5dac63340294dda6e34412.png...

 16%|█▌        | 79/488 [04:05<23:00,  3.38s/it]

Done.
Downloading 1RY9pcEFfa-ZmuK3H8wRQtuwKuP7swMr2 into /content/dataset/images/val/L32531_santiago_loza_39.jpg...

 16%|█▋        | 80/488 [04:08<22:07,  3.25s/it]

Done.
Downloading 1IiRv2CJFNqqvcsQxc_ikfiLKJM2CNHpa into /content/dataset/images/val/s56804_alexis_segui_03.png...

 17%|█▋        | 81/488 [04:10<21:19,  3.14s/it]

Done.
Downloading 10dnJI8gdnS107BD07G0gvEKhRp5BOGFE into /content/dataset/images/val/3cbb052c7f4127313a34629e22f95f52.png...

 17%|█▋        | 82/488 [04:13<20:50,  3.08s/it]

Done.
Downloading 1xMsKiZeQqQ0Zgdo7nZco4HsfH2FMwKKo into /content/dataset/images/val/58491_fabio_giampaoli_22.png...

 17%|█▋        | 83/488 [04:21<29:07,  4.32s/it]

Done.
Downloading 1Y6INrBINw3zf4mBYHEFBnHLLwVLZVJBs into /content/dataset/images/val/61681e0eaca430f089295c5bba12a235.png...

 17%|█▋        | 84/488 [04:23<26:05,  3.87s/it]

Done.
Downloading 10plhOWbhgwAQKXbfDJVlhJYIl-q3ApCq into /content/dataset/images/val/s56189_salvador_sanchez_16.jpg...

 17%|█▋        | 85/488 [04:26<22:43,  3.38s/it]

Done.
Downloading 1lkJnQB4Hmi9fey8YeNUDbNy1zWYQQkr3 into /content/dataset/images/val/g5845_gravifiorino_13.jpeg...

 18%|█▊        | 86/488 [04:28<20:05,  3.00s/it]

Done.
Downloading 1O_LmAd-Lwd2lIhdMvZ_7aT5K0BAXNOaj into /content/dataset/images/val/57096_ramiro_sagrera_11.jpg...

 18%|█▊        | 87/488 [04:31<19:32,  2.92s/it]

Done.
Downloading 1AF_vA51nI5cITfolWXTgYSFuiZjis9PV into /content/dataset/images/val/37494_gustavo_fontana_25.jpg...

 18%|█▊        | 88/488 [04:34<19:39,  2.95s/it]

Done.
Downloading 12oKz92QzMuJW7Z7tcNboV2_jzFbYG_74 into /content/dataset/images/val/43265_Lucas_Demarre_01.jpg...

 18%|█▊        | 89/488 [04:36<17:55,  2.69s/it]

Done.
Downloading 1VAlwUfQ5R-dOAdmw4CPlW6KjW3AGvavV into /content/dataset/images/val/43841031_Enzo_Ferrari_26.png...

 18%|█▊        | 90/488 [04:41<22:33,  3.40s/it]

Done.
Downloading 1as5d90Du9SLgg6n9H9TAtaO7okdjfs5O into /content/dataset/images/val/L32425_eugenio_lopez_24.png...

 19%|█▊        | 91/488 [04:45<23:24,  3.54s/it]

Done.
Downloading 18b2NeAFQQ6ojGOZAI5oc1AnZumsiyaJX into /content/dataset/images/val/51705_micaela_pozzo_29.png...

 19%|█▉        | 92/488 [04:47<21:45,  3.30s/it]

Done.
Downloading 1qswUiVyFBQHt0YQo6qQAoHCnXy9CQELG into /content/dataset/images/val/17211af4d041d345cb72fbf6dd0417ba.png...

 19%|█▉        | 93/488 [04:51<21:45,  3.30s/it]

Done.
Downloading 1mjPG59muT3ldx2vELxYIcw4jfOdQ6zzz into /content/dataset/images/val/46019_taiel_raffaeli_20.jpg...

 19%|█▉        | 94/488 [04:54<20:58,  3.20s/it]

Done.
Downloading 1mZKzK6lr8kNPNBoGBVMkWuG7L0j7nUlu into /content/dataset/images/val/51705_micaela_pozzo_25.png...

 19%|█▉        | 95/488 [04:56<20:14,  3.09s/it]

Done.
Downloading 11DERQ5YcHt3VmKnGOdCLmI4zmY4nx1Dc into /content/dataset/images/val/57096_ramiro_sagrera_03.jpg...

 20%|█▉        | 96/488 [04:59<19:45,  3.02s/it]

Done.
Downloading 1szRlpC9nZ_A7bXzHYZAzhKMterb9qnp_ into /content/dataset/images/val/64191_Sofia_BrizuelaCipolletti_29.jpg...

 20%|█▉        | 97/488 [05:02<19:01,  2.92s/it]

Done.
Downloading 1v5rW37zwqSDnIHCN41JLtWjBy3sxEsgv into /content/dataset/images/val/S57061_Leandro_Salvana_47.png...

 20%|██        | 98/488 [05:04<18:12,  2.80s/it]

Done.
Downloading 1IdV3Ggcent9rEuucdBoSs_lK-rO0BQz6 into /content/dataset/images/val/A45161_Fabian_Aguirre_17.png...

 20%|██        | 99/488 [05:07<17:42,  2.73s/it]

Done.
Downloading 1nnWFciRF1hlMWxsPwE-yYNKNE2exzine into /content/dataset/images/val/A45161_Fabian_Aguirre_24.png...

 20%|██        | 100/488 [05:10<18:42,  2.89s/it]

Done.
Downloading 1QBGvKM8h46evfHpojmTDHcHDLIbZYBiK into /content/dataset/images/val/51659_antonio_peroni_11.jpg...

 21%|██        | 101/488 [05:13<18:25,  2.86s/it]

Done.
Downloading 1WERlHVXAzeasy-hHxj-p58L8du1P9vcL into /content/dataset/images/val/46094_Mateo_Rovere_23.png...

 21%|██        | 102/488 [05:16<17:52,  2.78s/it]

Done.
Downloading 1m7AdgnaKFKYkz6rMJVEbRnq_u6MDRpeO into /content/dataset/images/val/w05576_juan_wagner_25.png...

 21%|██        | 103/488 [05:18<17:38,  2.75s/it]

Done.
Downloading 1jWSDbNcYeNwdBY8dDZTONDCN0Go_2TVC into /content/dataset/images/val/64191_Sofia_BrizuelaCipolletti_24.jpg...

 21%|██▏       | 104/488 [05:21<17:48,  2.78s/it]

Done.
Downloading 10gvN0q597UnaxPpqmkyMlpW1OlL_b9Pa into /content/dataset/images/val/64191_Sofia_BrizuelaCipolletti_23.jpg...

 22%|██▏       | 105/488 [05:25<18:44,  2.94s/it]

Done.
Downloading 1mOynWFQj3xWrkMUfvwNu3oluoxRiRhVN into /content/dataset/images/val/f37478_santiago_ferrero_05.jpg...

 22%|██▏       | 106/488 [05:29<21:38,  3.40s/it]

Done.
Downloading 17YOI7PfHIxXMHT9-HwGCkH0xRRqB3Que into /content/dataset/images/val/03531_mirian_yanez_19.jpeg...

 22%|██▏       | 107/488 [05:31<19:16,  3.03s/it]

Done.
Downloading 1iqRyEHQBk5q-E5WA7E8QkKrm231LSvOm into /content/dataset/images/val/43841031_Enzo_Ferrari_02.png...

 22%|██▏       | 108/488 [05:35<20:55,  3.30s/it]

Done.
Downloading 1tocZF4vGIETKxRUdPruO2LsHTN9rZAGv into /content/dataset/images/val/46019_taiel_raffaeli_17.jpg...

 22%|██▏       | 109/488 [05:38<20:14,  3.21s/it]

Done.
Downloading 1Ikg0YqZYes_VLzok-VA61B7vifj_1cFH into /content/dataset/images/val/s56189_salvador_sanchez_53.jpg...

 23%|██▎       | 110/488 [05:40<18:21,  2.91s/it]

Done.
Downloading 1JjcpJzvZeZmM0UgLf-e5xTUyei4GYn3x into /content/dataset/images/val/57096_ramiro_sagrera_07.jpg...

 23%|██▎       | 111/488 [05:44<19:17,  3.07s/it]

Done.
Downloading 1WeJx54yf62P8I1x_LWl_jtbLp_HsY4eO into /content/dataset/images/val/s56189_salvador_sanchez_265.jpg...

 23%|██▎       | 112/488 [05:46<18:12,  2.91s/it]

Done.
Downloading 1QU7Bcg4oQpv6uTejhI-VAmfBirYDIvGC into /content/dataset/images/val/51934_pablo_pistelli_02.png...

 23%|██▎       | 113/488 [05:51<21:09,  3.39s/it]

Done.
Downloading 1dSWGGNdE4M1-qQFW5WlkP_mhTlULnZLH into /content/dataset/images/val/966c6a6d6d291047dcd64c692789e432.png...

 23%|██▎       | 114/488 [05:54<19:57,  3.20s/it]

Done.
Downloading 1M318Zx6asBQ4wcF5KssckVdYJrcdgaTj into /content/dataset/images/val/8cae59752e66a9fba867409af4ba39c3.png...

 24%|██▎       | 115/488 [05:57<19:26,  3.13s/it]

Done.
Downloading 1PzRU2ptOozwAdbIGYSlwWQla8_lso-Rb into /content/dataset/images/val/43265_Lucas_Demarre_08.jpg...

 24%|██▍       | 116/488 [05:59<18:24,  2.97s/it]

Done.
Downloading 1TldxWiI1e1bJZX0mZqW5dLxxskU-hL-j into /content/dataset/images/val/58491_fabio_giampaoli_07.png...

 24%|██▍       | 117/488 [06:05<23:46,  3.84s/it]

Done.
Downloading 1tcuanYfj-2tjY5RaAem04RRllE3TrVs6 into /content/dataset/images/val/A45161_Fabian_Aguirre_19.png...

 24%|██▍       | 118/488 [06:08<21:34,  3.50s/it]

Done.
Downloading 1U73zVsVuyJRwetATCWAgEFbQRnpVUkjs into /content/dataset/images/val/46019_taiel_raffaeli_04.jpg...

 24%|██▍       | 119/488 [06:11<20:29,  3.33s/it]

Done.
Downloading 1eoRjwMJX_CrMtc1Yf3HxKkb2PFpdo6td into /content/dataset/images/val/71846_Brisa_Menescaldi_24.png...

 25%|██▍       | 120/488 [06:15<22:33,  3.68s/it]

Done.
Downloading 1UdLSsTqA_FSrDxOOKU9hX4zdPWguEPmW into /content/dataset/images/val/41932688_Simon_Revello_11.png...

 25%|██▍       | 121/488 [06:20<23:51,  3.90s/it]

Done.
Downloading 1IDaiHLZ_njJO4lUAsbe0_IrxbfVtbaSX into /content/dataset/images/val/A45161_Fabian_Aguirre_13.png...

 25%|██▌       | 122/488 [06:22<21:12,  3.48s/it]

Done.
Downloading 1_o4vuKV077EmV_J966k45m6tVuKRiyDZ into /content/dataset/images/val/52256_daniel_ponce_11.jpeg...

 25%|██▌       | 123/488 [06:25<20:11,  3.32s/it]

Done.
Downloading 1xYofN1JcsD01voS0FRoeenAQSb3GPD5o into /content/dataset/images/val/57096_ramiro_sagrera_13.jpg...

 25%|██▌       | 124/488 [06:28<19:19,  3.19s/it]

Done.
Downloading 1XrRiljlj554ZHubkhv3F2qa3X2g_ROFO into /content/dataset/images/val/s56189_salvador_sanchez_283.jpg...

 26%|██▌       | 125/488 [06:30<17:50,  2.95s/it]

Done.
Downloading 1dwEgWwgqGH98EMhSaypP3uwbxdwkAIup into /content/dataset/images/val/P_51977_martin_perrone_26.png...

 26%|██▌       | 126/488 [06:34<18:32,  3.07s/it]

Done.
Downloading 1aVETEy51FK6ARyNcL1MLs0luzC2tWFWh into /content/dataset/images/val/46094_Mateo_Rovere_11.png...

 26%|██▌       | 127/488 [06:36<17:23,  2.89s/it]

Done.
Downloading 1LXuH54_aa8tEoKnApZwSHHgDILFpx4AJ into /content/dataset/images/val/s56189_salvador_sanchez_96.jpg...

 26%|██▌       | 128/488 [06:38<16:20,  2.72s/it]

Done.
Downloading 1W19XfexPomP7ov-7Uhko_sKZ-bODB7RT into /content/dataset/images/val/s56189_salvador_sanchez_246.jpg...

 26%|██▋       | 129/488 [06:41<15:34,  2.60s/it]

Done.
Downloading 1HLGKqV8dT0Nyc01PQHwwtyClO7Uz63LV into /content/dataset/images/val/43265_Lucas_Demarre_29.jpg...

 27%|██▋       | 130/488 [06:43<15:36,  2.62s/it]

Done.
Downloading 1p-bgjgs2llnHd4gwin5rvd0mgoeJzT6Q into /content/dataset/images/val/64191_Sofia_BrizuelaCipolletti_05.jpg...

 27%|██▋       | 131/488 [06:47<16:58,  2.85s/it]

Done.
Downloading 1f4U1dJwKxn-yVJtApuQrKKKdCU-z8xc4 into /content/dataset/images/val/P_51977_martin_perrone_10.png...

 27%|██▋       | 132/488 [06:50<17:28,  2.94s/it]

Done.
Downloading 1MGPkKTVCg2VHRCIRkrSUCOt2xXnPlN94 into /content/dataset/images/val/F37605_florencia_fernandez_46.png...

 27%|██▋       | 133/488 [06:53<16:48,  2.84s/it]

Done.
Downloading 1Rw5E1dvLjlo0mxKfkXVghMH_yUAxG5rG into /content/dataset/images/val/s56189_salvador_sanchez_191.jpg...

 27%|██▋       | 134/488 [06:55<16:03,  2.72s/it]

Done.
Downloading 1bm7NVlvY35W3H8Jda8bAz5lc0hQNtyIG into /content/dataset/images/val/P51926_Leonel_Palermo_03.png...

 28%|██▊       | 135/488 [06:58<17:04,  2.90s/it]

Done.
Downloading 17fNJtO6H3XAwMj6SKwkiO-438Ljr4S7T into /content/dataset/images/val/43237686_Constantino_Ferrucci_10.png...

 28%|██▊       | 136/488 [07:01<16:40,  2.84s/it]

Done.
Downloading 1iC9_ww7yeXx0YJ4Jq35MAdM2Kmxmptaj into /content/dataset/images/val/43841031_Enzo_Ferrari_37.png...

 28%|██▊       | 137/488 [07:06<19:53,  3.40s/it]

Done.
Downloading 1-lu-XwhW5rkPQA5G4DNgqQxAVLNjnNIm into /content/dataset/images/val/s56189_salvador_sanchez_5.jpg...

 28%|██▊       | 138/488 [07:08<18:03,  3.10s/it]

Done.
Downloading 12HHwJZDHlvnUiTEiFariKwZOdfSHpoQZ into /content/dataset/images/val/F37605_florencia_fernandez_10.png...

 28%|██▊       | 139/488 [07:11<16:53,  2.90s/it]

Done.
Downloading 1uCd4-0ufTcQNgP_VvTsvrDg6O3IcgMkv into /content/dataset/images/val/S57061_Leandro_Salvana_05.png...

 29%|██▊       | 140/488 [07:14<17:03,  2.94s/it]

Done.
Downloading 18cU7cbT6yABT6ABq0_0b13QUOwy07QMc into /content/dataset/images/val/52256_daniel_ponce_12.jpeg...

 29%|██▉       | 141/488 [07:17<17:04,  2.95s/it]

Done.
Downloading 1gdDejhtSZkgHOx-4ka9KTUXBTP_bU0_o into /content/dataset/images/val/f37478_santiago_ferrero_09.jpg...

 29%|██▉       | 142/488 [07:19<16:20,  2.83s/it]

Done.
Downloading 1mF-KdWijiVRmE0beFHrDdvyUzy1_zN1I into /content/dataset/images/val/71846_Brisa_Menescaldi_02.png...

 29%|██▉       | 143/488 [07:24<19:18,  3.36s/it]

Done.
Downloading 1UHmjqLU4ycEYV6Ltf5EB1cBgGkLflfob into /content/dataset/images/val/51659_antonio_peroni_28.jpg...

 30%|██▉       | 144/488 [07:26<18:07,  3.16s/it]

Done.
Downloading 1-KdMbvQXddhwgJnKOl52rKM4TSTK3fO6 into /content/dataset/images/val/58912_Timoteo_Garcia_6.jpg...

 30%|██▉       | 145/488 [07:29<17:50,  3.12s/it]

Done.
Downloading 1ceCl63Dr5he2_tN-O16Ht_FVtZfFsJrk into /content/dataset/images/val/58912_Timoteo_Garcia_16.jpg...

 30%|██▉       | 146/488 [07:32<17:10,  3.01s/it]

Done.
Downloading 18-YM1npQwjqhUQDo1vi5782fqbEK1CIA into /content/dataset/images/val/43265_Lucas_Demarre_04.jpg...

 30%|███       | 147/488 [07:34<15:41,  2.76s/it]

Done.
Downloading 17fjW3KfMNO2UgXWQBZGv-N5iYhg9ud1Y into /content/dataset/images/val/g5845_gravifiorino_3.jpeg...

 30%|███       | 148/488 [07:37<15:15,  2.69s/it]

Done.
Downloading 1-OlQjoYt91gDQ73Ru5gYhXvPALf_Bf7e into /content/dataset/images/val/46019_taiel_raffaeli_23.jpg...

 31%|███       | 149/488 [07:40<15:23,  2.73s/it]

Done.
Downloading 1xWJguGn6yeZCMCU_muUYAnLHqhX5c9ll into /content/dataset/images/val/64191_Sofia_BrizuelaCipolletti_15.jpg...

 31%|███       | 150/488 [07:43<15:59,  2.84s/it]

Done.
Downloading 1gZAG59C57_JpSCm19Sir3NovJkul9DwD into /content/dataset/images/val/51705_micaela_pozzo_11.png...

 31%|███       | 151/488 [07:46<15:51,  2.82s/it]

Done.
Downloading 1f2gIN4BQvtgkb-u5pFT_wqkwSyv_c4Pc into /content/dataset/images/val/g5845_gravifiorino_20.jpeg...

 31%|███       | 152/488 [07:48<14:58,  2.67s/it]

Done.
Downloading 1ZDrQj7nTgieqQEFygTUacJpeyacJDwdi into /content/dataset/images/val/s56189_salvador_sanchez_305.jpg...

 31%|███▏      | 153/488 [07:50<14:01,  2.51s/it]

Done.
Downloading 1rnnHALWfF0BeiZsec6B578_vhom_ap8b into /content/dataset/images/val/51934_pablo_pistelli_08.png...

 32%|███▏      | 154/488 [07:56<20:19,  3.65s/it]

Done.
Downloading 10l9ih2zCTAmLvPDh3xN9-8VdmE5zMPay into /content/dataset/images/val/s56804_alexis_segui_12.png...

 32%|███▏      | 155/488 [07:59<18:14,  3.29s/it]

Done.
Downloading 1tkHIPBo5GQryq3ws3l537hvu7XhemxSf into /content/dataset/images/val/F37605_florencia_fernandez_48.png...

 32%|███▏      | 156/488 [08:02<18:23,  3.32s/it]

Done.
Downloading 1cJDIaWzFxT4r71JgZo_L6Y39a4GMmC4g into /content/dataset/images/val/41932688_Simon_Revello_26.png...

 32%|███▏      | 157/488 [08:06<19:26,  3.53s/it]

Done.
Downloading 1qqrq9fZGzTUogXHJiYF0m5JorAYYVlpb into /content/dataset/images/val/f1a1e60483d50907ec51fd1bf648c4dc.png...

 32%|███▏      | 158/488 [08:09<18:06,  3.29s/it]

Done.
Downloading 1SESZVRZ-DiqL3krimxPJyC__fm9vSz5V into /content/dataset/images/val/F37605_florencia_fernandez_17.png...

 33%|███▎      | 159/488 [08:11<16:19,  2.98s/it]

Done.
Downloading 1SbBml68iIsf5udPMN3m7UwkmKOQAtk6z into /content/dataset/images/val/s56189_salvador_sanchez_198.jpg...

 33%|███▎      | 160/488 [08:13<15:02,  2.75s/it]

Done.
Downloading 1w1Y6TLF_K79nuEPBGNoiXQU959tnRpyM into /content/dataset/images/val/L32531_santiago_loza_5.jpg...

 33%|███▎      | 161/488 [08:17<16:07,  2.96s/it]

Done.
Downloading 1MgXhq9cIvNIM82TBWdtLZ20jcYbA9WRb into /content/dataset/images/val/s56189_salvador_sanchez_115.jpg...

 33%|███▎      | 162/488 [08:19<14:48,  2.72s/it]

Done.
Downloading 1YTxpPH7t6s9VsvVlREuhbwkg_qfaxnvG into /content/dataset/images/val/37524_augusto_farias_08.jpg...

 33%|███▎      | 163/488 [08:24<18:11,  3.36s/it]

Done.
Downloading 1qohPDfuS3mZd1liI1QZpJ2uqIpgQQXjY into /content/dataset/images/val/51705_micaela_pozzo_23.png...

 34%|███▎      | 164/488 [08:27<17:25,  3.23s/it]

Done.
Downloading 1H9y0KhAOwpNkm37FEuJ41JxvnWVa7WAV into /content/dataset/images/val/57096_ramiro_sagrera_17.jpg...

 34%|███▍      | 165/488 [08:30<16:38,  3.09s/it]

Done.
Downloading 1TiZpM5LvQAwlR-O4XjMpda150avVO6FI into /content/dataset/images/val/s56189_salvador_sanchez_217.jpg...

 34%|███▍      | 166/488 [08:32<15:30,  2.89s/it]

Done.
Downloading 1Kz5kstrARfcMqNKNv0BvpBo9fqvZ6n2v into /content/dataset/images/val/s56189_salvador_sanchez_86.jpg...

 34%|███▍      | 167/488 [08:34<14:21,  2.68s/it]

Done.
Downloading 1ZAe0YUmgldY6QVjqhaLYIfTMEEdWFNcG into /content/dataset/images/val/R-45829_Abril_Rodriguez_31.png...

 34%|███▍      | 168/488 [08:36<13:42,  2.57s/it]

Done.
Downloading 18_pyFCPENzC1c3STwZpgNAHXWyHmUDN_ into /content/dataset/images/val/72125_miguel_mussi_25.png...

 35%|███▍      | 169/488 [08:39<13:46,  2.59s/it]

Done.
Downloading 1dEgRFZInLr1r0tRaDLgxm70_3eK88hB_ into /content/dataset/images/val/57096_ramiro_sagrera_19.jpg...

 35%|███▍      | 170/488 [08:42<14:25,  2.72s/it]

Done.
Downloading 1-WR0nAuZfyh13_W0zn8PUAhtC-zP09yL into /content/dataset/images/val/P_51977_martin_perrone_06.png...

 35%|███▌      | 171/488 [08:46<15:50,  3.00s/it]

Done.
Downloading 14HbLqYxoC6BbQLUMSkXe70e_j3dim3-l into /content/dataset/images/val/58513_isaias_garay_23.png...

 35%|███▌      | 172/488 [08:48<15:00,  2.85s/it]

Done.
Downloading 12bJ08bQYbjRgTP7nX6RDymY9JJX6LByY into /content/dataset/images/val/37494_gustavo_fontana_04.jpg...

 35%|███▌      | 173/488 [08:51<15:25,  2.94s/it]

Done.
Downloading 16WwaeNqhSY-QxdgggKjeeIiJo1Vy-RGV into /content/dataset/images/val/58513_isaias_garay_01.png...

 36%|███▌      | 174/488 [08:54<14:37,  2.80s/it]

Done.
Downloading 1t7JfPQL_OP21Zv7tGWcyKBmGiXryOsom into /content/dataset/images/val/12394_escandell_ariel_15.jpg...

 36%|███▌      | 175/488 [08:57<15:03,  2.89s/it]

Done.
Downloading 1Odt6J7N76e4Q2a1I6BSeBhJjXuVb7KJ7 into /content/dataset/images/val/s56189_salvador_sanchez_139.jpg...

 36%|███▌      | 176/488 [08:59<13:59,  2.69s/it]

Done.
Downloading 1R_w6mAFYyz1a-uz0EVzg7Nj0P2vou0d3 into /content/dataset/images/val/s56189_salvador_sanchez_182.jpg...

 36%|███▋      | 177/488 [09:01<13:08,  2.53s/it]

Done.
Downloading 1EuAqIIEqhhi2JzripO4FlYN2xhm-ZD6X into /content/dataset/images/val/f37478_santiago_ferrero_25.jpg...

 36%|███▋      | 178/488 [09:04<13:22,  2.59s/it]

Done.
Downloading 1dEzDQo2aFX3xvORdYMEZTWkBE87rNyai into /content/dataset/images/val/72125_miguel_mussi_10.png...

 37%|███▋      | 179/488 [09:07<13:06,  2.55s/it]

Done.
Downloading 1CpWrs4J4VuGh5DRkvQC0jMml4trw3pPO into /content/dataset/images/val/S57061_Leandro_Salvana_26.png...

 37%|███▋      | 180/488 [09:10<14:09,  2.76s/it]

Done.
Downloading 1g8x7LfA28hKGbYSEyTE2aAjQgXO92FM9 into /content/dataset/images/val/46094_Mateo_Rovere_25.png...

 37%|███▋      | 181/488 [09:15<17:39,  3.45s/it]

Done.
Downloading 1HFAJc40gGEZg3-b4RtftMI2uW-8FnEEp into /content/dataset/images/val/58513_isaias_garay_16.png...

 37%|███▋      | 182/488 [09:18<16:20,  3.20s/it]

Done.
Downloading 1ZLQEImBYMoXZjfd0_XYdYz44v6CdwGYb into /content/dataset/images/val/F37605_florencia_fernandez_35.png...

 38%|███▊      | 183/488 [09:20<15:41,  3.09s/it]

Done.
Downloading 1doFdRbbzAnqME-96w_RhO4vl4H1CfGWT into /content/dataset/images/val/46094_Mateo_Rovere_22.png...

 38%|███▊      | 184/488 [09:23<15:02,  2.97s/it]

Done.
Downloading 1N1xRIkLquKah2FdRlN4hkQadOxkUet8Q into /content/dataset/images/val/s56189_salvador_sanchez_120.jpg...

 38%|███▊      | 185/488 [09:25<13:54,  2.76s/it]

Done.
Downloading 148VYmdPt4u6_aw_iqTA3r9LLJQN0wyku into /content/dataset/images/val/43265_Lucas_Demarre_05.jpg...

 38%|███▊      | 186/488 [09:28<13:06,  2.60s/it]

Done.
Downloading 12laeHJ2rGeJm1oxnvCyMhNQWyXiHlEjQ into /content/dataset/images/val/s56189_salvador_sanchez_38.jpg...

 38%|███▊      | 187/488 [09:30<12:32,  2.50s/it]

Done.
Downloading 1cD0RH2xooNBRZ24wu207nRf-XP0Iwz4X into /content/dataset/images/val/43841031_Enzo_Ferrari_34.png...

 39%|███▊      | 188/488 [09:32<12:17,  2.46s/it]

Done.
Downloading 1FXy5zTI_B1iVzVdFjxnDMfwC7oHm2Cd8 into /content/dataset/images/val/72125_miguel_mussi_11.png...

 39%|███▊      | 189/488 [09:35<12:31,  2.51s/it]

Done.
Downloading 1ya_Ci7Zs2bly6vOleQzHmhkpe3i_mHc6 into /content/dataset/images/val/gravifiorino_9.jpeg...

 39%|███▉      | 190/488 [09:37<12:08,  2.44s/it]

Done.
Downloading 1k7rLzSiRzO6qIzWlYPjDkYn1JblzpQIq into /content/dataset/images/val/43841031_Enzo_Ferrari_07.png...

 39%|███▉      | 191/488 [09:42<15:35,  3.15s/it]

Done.
Downloading 1-mW02lVBuAA-dmdA8qibV2ilWUD1gSwy into /content/dataset/images/val/52256_daniel_ponce_30.jpeg...

 39%|███▉      | 192/488 [09:44<14:41,  2.98s/it]

Done.
Downloading 1WWYMXfMHBJ86OC-XNPjssR9aFSB-M-6M into /content/dataset/images/val/s56189_salvador_sanchez_263.jpg...

 40%|███▉      | 193/488 [09:47<13:41,  2.78s/it]

Done.
Downloading 1JqTd7KpozwfWQbg0BPWSw-3DUEXWHuis into /content/dataset/images/val/51951_pablo_pistarelli_28.png...

 40%|███▉      | 194/488 [09:51<16:16,  3.32s/it]

Done.
Downloading 10OfqbdPC1XcVRfiWBFWHW96OWy8QEScl into /content/dataset/images/val/s56189_salvador_sanchez_13.jpg...

 40%|███▉      | 195/488 [09:54<14:48,  3.03s/it]

Done.
Downloading 1Uk9Q7URmPoCYD46xsR11iTW2bCdVJQhP into /content/dataset/images/val/P51926_Leonel_Palermo_01.png...

 40%|████      | 196/488 [09:58<16:24,  3.37s/it]

Done.
Downloading 1pi6H9qyVN4NxrlbPP4xF9c6MqSu-iD0Z into /content/dataset/images/val/46094_Mateo_Rovere_7.png...

 40%|████      | 197/488 [10:02<17:41,  3.65s/it]

Done.
Downloading 1C47BufbfE9wiI_kkbmHqJ8uvVeKBba4G into /content/dataset/images/val/w05576_juan_wagner_21.png...

 41%|████      | 198/488 [10:05<15:47,  3.27s/it]

Done.
Downloading 1W3r3KNULfFbirZVEYV_KJuGF1oFVKEKr into /content/dataset/images/val/s56189_salvador_sanchez_254.jpg...

 41%|████      | 199/488 [10:07<14:18,  2.97s/it]

Done.
Downloading 1JDctkteOzn1DfeLfOGl-7BMNOZgQQWI- into /content/dataset/images/val/46019_taiel_raffaeli_29.jpg...

 41%|████      | 200/488 [10:10<14:14,  2.97s/it]

Done.
Downloading 1Jmdj3zv0K5c7_sqpIaasQ99VNDJpc6wK into /content/dataset/images/val/s56189_salvador_sanchez_70.jpg...

 41%|████      | 201/488 [10:12<13:02,  2.73s/it]

Done.
Downloading 1eUSP_MDCvoa4suIvU7CJF7GadYCatxfx into /content/dataset/images/val/0a1343bac8cb2b14b120bc01bff80676.png...

 41%|████▏     | 202/488 [10:15<13:11,  2.77s/it]

Done.
Downloading 1tg_xn_Qqeh2fNUyVEF-5kVBLQzSvJsP5 into /content/dataset/images/val/43841031_Enzo_Ferrari_23.png...

 42%|████▏     | 203/488 [10:21<17:21,  3.65s/it]

Done.
Downloading 1WZr-AnKE3oI7jtPD8rHsT5YGgNwfEb3R into /content/dataset/images/val/s56189_salvador_sanchez_266.jpg...

 42%|████▏     | 204/488 [10:23<15:41,  3.31s/it]

Done.
Downloading 1TGp62dtKiJjCGMlYxNN9R9ZXnqLoARDN into /content/dataset/images/val/s56189_salvador_sanchez_209.jpg...

 42%|████▏     | 205/488 [10:25<13:48,  2.93s/it]

Done.
Downloading 1wTgXhlRbJZHzPpUacjhbjMT1oJeZEgVK into /content/dataset/images/val/L32531_santiago_loza_45.jpg...

 42%|████▏     | 206/488 [10:28<13:43,  2.92s/it]

Done.
Downloading 1Fzikgim4LsHGRrjM8cSwbD7ZEx65KG45 into /content/dataset/images/val/948c12fe82cdcf22cb7b1e2cd0e24ab8.png...

 42%|████▏     | 207/488 [10:32<14:37,  3.12s/it]

Done.
Downloading 1095Gy-LlUjVg97pv6reDN3xE9OgsZWRf into /content/dataset/images/val/s56189_salvador_sanchez_10.jpg...

 43%|████▎     | 208/488 [10:34<13:34,  2.91s/it]

Done.
Downloading 12gOri7YA-DGr8WNqEMfD35jTSawsTe2n into /content/dataset/images/val/72125_miguel_mussi_33.png...

 43%|████▎     | 209/488 [10:37<13:08,  2.83s/it]

Done.
Downloading 1LC01qBklcqw2W6QyTk68n2Yu_EQ86_xU into /content/dataset/images/val/s56189_salvador_sanchez_87.jpg...

 43%|████▎     | 210/488 [10:39<11:57,  2.58s/it]

Done.
Downloading 1Yfl4yKgCSmAf3NIJGr03ErO4Vva7btIT into /content/dataset/images/val/w05576_juan_wagner_01.png...

 43%|████▎     | 211/488 [10:41<11:25,  2.48s/it]

Done.
Downloading 12cSCNJ2JmTI_lQ2KnnuIj6D9PxiCPeT_ into /content/dataset/images/val/P51951_pablo_pistarelli_05.png...

 43%|████▎     | 212/488 [10:43<11:34,  2.52s/it]

Done.
Downloading 1hZu5czqx5CnOJmhD3uPyapfZhkuVrVRe into /content/dataset/images/val/P_51977_martin_perrone_36.png...

 44%|████▎     | 213/488 [10:47<12:51,  2.80s/it]

Done.
Downloading 1Wsz2YnseSyWoyjvHn3z4GyFIDJqeVvTj into /content/dataset/images/val/s56189_salvador_sanchez_269.jpg...

 44%|████▍     | 214/488 [10:49<12:05,  2.65s/it]

Done.
Downloading 1iCCCu4TAeocRbSzvjaN6GEfDJ3tyEVMp into /content/dataset/images/val/51659_antonio_peroni_10.jpg...

 44%|████▍     | 215/488 [10:52<12:22,  2.72s/it]

Done.
Downloading 11oTq6RJAAfQt0gEiU469HaSit15JRe0D into /content/dataset/images/val/s56189_salvador_sanchez_27.jpg...

 44%|████▍     | 216/488 [10:55<11:54,  2.63s/it]

Done.
Downloading 1O1vZoDmilJjlFFJqIVd_flVRqJgZGbFh into /content/dataset/images/val/R-45829_Abril_Rodriguez_24.png...

 44%|████▍     | 217/488 [10:57<11:39,  2.58s/it]

Done.
Downloading 1UhWWmVZD-a05b2j9Gcn94cwrbKYfZhYD into /content/dataset/images/val/s56189_salvador_sanchez_229.jpg...

 45%|████▍     | 218/488 [10:59<10:59,  2.44s/it]

Done.
Downloading 1CDpUCx3HELru1x8ceDlqrPKNwOuvmieN into /content/dataset/images/val/b94b2c04f22005e33c1f73a01b968bf5.png...

 45%|████▍     | 219/488 [11:02<11:21,  2.53s/it]

Done.
Downloading 1WMG2Vczta0SeR5Y_Ut-EpPGxp-HZ6ogF into /content/dataset/images/val/58491_fabio_giampaoli_10.png...

 45%|████▌     | 220/488 [11:05<12:36,  2.82s/it]

Done.
Downloading 1Hk2Y9jO0n84Ea2UaDA_3TcqzggdbaTkV into /content/dataset/images/val/w05576_juan_wagner_03.png...

 45%|████▌     | 221/488 [11:08<11:58,  2.69s/it]

Done.
Downloading 1t0ivKgPZEaCedtUhbcgV-SMGRmtD6pus into /content/dataset/images/val/s56804_alexis_segui_05.png...

 45%|████▌     | 222/488 [11:10<11:39,  2.63s/it]

Done.
Downloading 1Pt-ThjnjDIVuuhuun4E4aM8GorFb1_OV into /content/dataset/images/val/71846_Brisa_Menescaldi_21.png...

 46%|████▌     | 223/488 [11:16<15:25,  3.49s/it]

Done.
Downloading 1W6hT82zgWaMZMVn0C7V_fKOtU7D5OHpg into /content/dataset/images/val/P_51977_martin_perrone_11.png...

 46%|████▌     | 224/488 [11:21<17:15,  3.92s/it]

Done.
Downloading 1kpIT_UYZKBCUeYFILpvtwN2Xt1GnPHRw into /content/dataset/images/val/L32531_santiago_loza_43.jpg...

 46%|████▌     | 225/488 [11:23<15:35,  3.56s/it]

Done.
Downloading 1ZKJFZsmx1vnSRVQATmycY-biJCyN6Bqh into /content/dataset/images/val/43265_Lucas_Demarre_07.jpg...

 46%|████▋     | 226/488 [11:26<14:12,  3.25s/it]

Done.
Downloading 1N3VPtZsx6jurlAoIbs0KiCf52Mm_dc7t into /content/dataset/images/val/6a137287bf186304e7922858046bba94.png...

 47%|████▋     | 227/488 [11:29<13:38,  3.14s/it]

Done.
Downloading 1R1myp0spZHJCyXSMRxnODCmk1dDuPlYh into /content/dataset/images/val/A45161_Fabian_Aguirre_04.png...

 47%|████▋     | 228/488 [11:32<13:23,  3.09s/it]

Done.
Downloading 1x4QNFjKDjPByifzF75BVU7zVynGPLbh1 into /content/dataset/images/val/R-45829_Abril_Rodriguez_20.png...

 47%|████▋     | 229/488 [11:34<12:48,  2.97s/it]

Done.
Downloading 1cuYHqZ8li3sFQpMOZSyJJbdOpsZ6No17 into /content/dataset/images/val/A45161_Fabian_Aguirre_18.png...

 47%|████▋     | 230/488 [11:37<12:05,  2.81s/it]

Done.
Downloading 1FQ9Mz2mXcD5LPt4cSahftm798a_IJBpa into /content/dataset/images/val/72125_miguel_mussi_04.png...

 47%|████▋     | 231/488 [11:39<11:45,  2.74s/it]

Done.
Downloading 1_sRnpdszdGuo-AcDx3R1vCbUpApUEGUZ into /content/dataset/images/val/46019_taiel_raffaeli_22.jpg...

 48%|████▊     | 232/488 [11:42<11:59,  2.81s/it]

Done.
Downloading 1TS67TY-ZUWkvSyQSTbxyiZ-MxnIiHBdu into /content/dataset/images/val/12394_escandell_ariel_16.jpg...

 48%|████▊     | 233/488 [11:45<11:42,  2.76s/it]

Done.
Downloading 1jTWVp_qRnfK8EhYSXMF2WLW5g7UFrGgC into /content/dataset/images/val/51934_pablo_pistelli_19.png...

 48%|████▊     | 234/488 [11:51<15:29,  3.66s/it]

Done.
Downloading 1E7_b5eM4bEzDxZvHApxJQ68rWF5TIWd7 into /content/dataset/images/val/s56804_alexis_segui_14.png...

 48%|████▊     | 235/488 [11:53<13:59,  3.32s/it]

Done.
Downloading 1zjBC_YhTKuhb2FvynJSyT3j12yvkzfgq into /content/dataset/images/val/S57061_Leandro_Salvana_38.png...

 48%|████▊     | 236/488 [11:56<13:35,  3.24s/it]

Done.
Downloading 1oKANjsNKWcOhvJOYnyzdlDDVJanhLFPN into /content/dataset/images/val/41932688_Simon_Revello_27.png...

 49%|████▊     | 237/488 [12:01<15:06,  3.61s/it]

Done.
Downloading 1bO0kUnv_ZTt9lnYGdmvF7VpFEW6sdZq8 into /content/dataset/images/val/43841031_Enzo_Ferrari_22.png...

 49%|████▉     | 238/488 [12:03<13:15,  3.18s/it]

Done.
Downloading 1Ci8boxO0A3QG87gClDJMcOzRePkE54DI into /content/dataset/images/val/58912_Timoteo_Garcia_3.jpg...

 49%|████▉     | 239/488 [12:06<13:15,  3.19s/it]

Done.
Downloading 1OlPAxFPU8larYH6aSEhkmDHsoz4-kwIN into /content/dataset/images/val/s56189_salvador_sanchez_140.jpg...

 49%|████▉     | 240/488 [12:08<11:53,  2.88s/it]

Done.
Downloading 1lH8Ray8Jh-A9Qpj8hg9hWepFdXOspo36 into /content/dataset/images/val/S57061_Leandro_Salvana_31.png...

 49%|████▉     | 241/488 [12:11<11:06,  2.70s/it]

Done.
Downloading 1UcdnE7cTDYQavKewfyLmJR547HvlfLxT into /content/dataset/images/val/s56189_salvador_sanchez_226.jpg...

 50%|████▉     | 242/488 [12:13<10:32,  2.57s/it]

Done.
Downloading 181puG_AEvORwhRsnQmQLuQHz23VZOTsY into /content/dataset/images/val/R-45829_Abril_Rodriguez_15.png...

 50%|████▉     | 243/488 [12:15<10:15,  2.51s/it]

Done.
Downloading 1ZR7MssKyFWe16LE4zrW5WClko3ULbbDG into /content/dataset/images/val/51705_micaela_pozzo_13.png...

 50%|█████     | 244/488 [12:18<10:20,  2.54s/it]

Done.
Downloading 1C_6e8bh0IRFivAafafwe_aQWONJSJ40W into /content/dataset/images/val/43237686_Constantino_Ferrucci_15.png...

 50%|█████     | 245/488 [12:22<11:47,  2.91s/it]

Done.
Downloading 1juWs88G8KObYyJfThJ8d2S6HR58vAabr into /content/dataset/images/val/51934_pablo_pistelli_07.png...

 50%|█████     | 246/488 [12:26<13:45,  3.41s/it]

Done.
Downloading 1y2OTMBVqXzyo5rCPBUM8o1Sts1E6Ptcr into /content/dataset/images/val/S57061_Leandro_Salvana_42.png...

 51%|█████     | 247/488 [12:29<12:23,  3.09s/it]

Done.
Downloading 12KW9bLF4s3zaEEskCmMPCaBtFBOEbMzs into /content/dataset/images/val/58513_isaias_garay_09.png...

 51%|█████     | 248/488 [12:31<11:53,  2.97s/it]

Done.
Downloading 1cL9BBwqQvjbqjsu_l99RI1_aTg4HOOFI into /content/dataset/images/val/P_51977_martin_perrone_33.png...

 51%|█████     | 249/488 [12:35<12:35,  3.16s/it]

Done.
Downloading 1USHlOwToQhoisT5d9gqGS1vdEAvMheQa into /content/dataset/images/val/51705_micaela_pozzo_05.png...

 51%|█████     | 250/488 [12:38<12:30,  3.15s/it]

Done.
Downloading 1KeL-DJ8n5gT1_coxblGwy_hT7CIizLeK into /content/dataset/images/val/F37605_florencia_fernandez_37.png...

 51%|█████▏    | 251/488 [12:41<12:18,  3.12s/it]

Done.
Downloading 1NRCP4uEwAmlV4gHDGBQazgHPcdgVFtrs into /content/dataset/images/val/s56189_salvador_sanchez_124.jpg...

 52%|█████▏    | 252/488 [12:43<11:04,  2.82s/it]

Done.
Downloading 11p4jEDa6L9AQRWmzFwCakh4egbYebAal into /content/dataset/images/val/cb34b326f984fcb48bf927ec3aebef0f.png...

 52%|█████▏    | 253/488 [12:46<10:37,  2.71s/it]

Done.
Downloading 1MeQpa4rgKPa9AuUOb0HatC_o55yAphIH into /content/dataset/images/val/s56189_salvador_sanchez_114.jpg...

 52%|█████▏    | 254/488 [12:48<09:54,  2.54s/it]

Done.
Downloading 1RDsclKrCypQ38puazF9yY1kMDgdGk6H3 into /content/dataset/images/val/s56189_salvador_sanchez_178.jpg...

 52%|█████▏    | 255/488 [12:50<09:41,  2.50s/it]

Done.
Downloading 15rxvFuL4UZHg3grvmAcWyK-CXY16-Lno into /content/dataset/images/val/P51926_Leonel_Palermo_09.png...

 52%|█████▏    | 256/488 [12:55<12:05,  3.13s/it]

Done.
Downloading 1NbGtkTVL7zYoVJ_TT8iS9zvPjCP-2mdG into /content/dataset/images/val/F37605_florencia_fernandez_04.png...

 53%|█████▎    | 257/488 [12:57<10:59,  2.86s/it]

Done.
Downloading 1LMZb0aVwOGF-bfSmWSo8qUZ-h8Kb5OZJ into /content/dataset/images/val/s56189_salvador_sanchez_91.jpg...

 53%|█████▎    | 258/488 [12:59<10:12,  2.66s/it]

Done.
Downloading 1_ASd9CIsHO1RnxPGcoKMJb2Yi385hyAI into /content/dataset/images/val/37494_gustavo_fontana_20.jpg...

 53%|█████▎    | 259/488 [13:02<10:42,  2.81s/it]

Done.
Downloading 1sdj6r4XP5pP4dK3TqQGX2GvsBuKUEuiL into /content/dataset/images/val/58513_isaias_garay_24.png...

 53%|█████▎    | 260/488 [13:05<10:03,  2.65s/it]

Done.
Downloading 1Y2LlE-_6a95D6SNRtugQkdWc780JeG4K into /content/dataset/images/val/s56189_salvador_sanchez_287.jpg...

 53%|█████▎    | 261/488 [13:07<09:45,  2.58s/it]

Done.
Downloading 1bCZ0_1ot_sV9lbiqBfl5iuE5-Jk6etZw into /content/dataset/images/val/P_51977_martin_perrone_16.png...

 54%|█████▎    | 262/488 [13:11<10:47,  2.86s/it]

Done.
Downloading 1-cdDAHjfD3Q_SRacPj6RaTAA0GihWyA9 into /content/dataset/images/val/s56189_salvador_sanchez_6.jpg...

 54%|█████▍    | 263/488 [13:13<10:14,  2.73s/it]

Done.
Downloading 1NpmcU0rFBPBcbt-r3QWRUQGIO4tYjB-r into /content/dataset/images/val/s56189_salvador_sanchez_129.jpg...

 54%|█████▍    | 264/488 [13:15<09:38,  2.58s/it]

Done.
Downloading 13lZktKlPbhqURpLbrfvgskfxXS79EChA into /content/dataset/images/val/f37478_santiago_ferrero_19.jpg...

 54%|█████▍    | 265/488 [13:19<11:16,  3.03s/it]

Done.
Downloading 1-jPgcawNH5Ot5KA5WCPfi-lqeP97Vjex into /content/dataset/images/val/51659_antonio_peroni_13.jpg...

 55%|█████▍    | 266/488 [13:22<10:59,  2.97s/it]

Done.
Downloading 1S50AcEP82IuDCUWqs85Pjlc6z1RNmdAJ into /content/dataset/images/val/s56189_salvador_sanchez_193.jpg...

 55%|█████▍    | 267/488 [13:25<10:21,  2.81s/it]

Done.
Downloading 1gz9-kfqB4q6fqG8Zg7BzqgstyKEbdrSH into /content/dataset/images/val/R-45489_sofiarondini_26.png...

 55%|█████▍    | 268/488 [13:27<10:13,  2.79s/it]

Done.
Downloading 1QUPkVtK-njDAuL2_LjamgQIeYVhoVl6g into /content/dataset/images/val/s56189_salvador_sanchez_165.jpg...

 55%|█████▌    | 269/488 [13:30<09:26,  2.59s/it]

Done.
Downloading 1t2jYq33GwqeAMXHHXSQBkpu2WSfnme2B into /content/dataset/images/val/S57061_Leandro_Salvana_34.png...

 55%|█████▌    | 270/488 [13:32<09:23,  2.59s/it]

Done.
Downloading 1gqkiHeqbOFb1Kx3mfI6pv8xc6TzfoWs4 into /content/dataset/images/val/g5845_gravifiorino_17.jpeg...

 56%|█████▌    | 271/488 [13:34<09:05,  2.52s/it]

Done.
Downloading 1X3Z-Xy3yUZAdGMad00i8almLVzgN2OuA into /content/dataset/images/val/s56189_salvador_sanchez_274.jpg...

 56%|█████▌    | 272/488 [13:37<08:49,  2.45s/it]

Done.
Downloading 1T4Oz6VwuBJB0mZwMYcy-30INUdg3XOzc into /content/dataset/images/val/46094_Mateo_Rovere_14.png...

 56%|█████▌    | 273/488 [13:39<08:55,  2.49s/it]

Done.
Downloading 1cx0sYid1p4LYmH-CCYFwImF5VMQjl76Y into /content/dataset/images/val/37494_gustavo_fontana_06.jpg...

 56%|█████▌    | 274/488 [13:43<09:41,  2.72s/it]

Done.
Downloading 1kD4fMOPTIGA_VjeSlcwPWjPjJFVTnID4 into /content/dataset/images/val/58513_isaias_garay_13.png...

 56%|█████▋    | 275/488 [13:45<09:28,  2.67s/it]

Done.
Downloading 12t08p-3tWv5GH8iPVNHh3iiUJ2WuKKXb into /content/dataset/images/val/s56189_salvador_sanchez_40.jpg...

 57%|█████▋    | 276/488 [13:48<09:06,  2.58s/it]

Done.
Downloading 13Ko64COARfWAYW0ZV1ZOA_SVz9E5fYOT into /content/dataset/images/val/s56189_salvador_sanchez_49.jpg...

 57%|█████▋    | 277/488 [13:50<08:33,  2.43s/it]

Done.
Downloading 13W5Ypj_U8fABqgd7QxY4aFU9V46JOURd into /content/dataset/images/val/51659_antonio_peroni_24.jpg...

 57%|█████▋    | 278/488 [13:53<09:51,  2.82s/it]

Done.
Downloading 129FnwWwLBcPlOr9S1s-8M1wzzFvOk4Cm into /content/dataset/images/val/51705_micaela_pozzo_16.png...

 57%|█████▋    | 279/488 [13:56<09:30,  2.73s/it]

Done.
Downloading 1STqdKuUsHe6I5D2pX3gymTnNy27dnx0K into /content/dataset/images/val/72125_miguel_mussi_13.png...

 57%|█████▋    | 280/488 [13:59<09:27,  2.73s/it]

Done.
Downloading 1ciIQ0W_imQwtdrsJw8YjfggC89KoWNzL into /content/dataset/images/val/S57061_Leandro_Salvana_11.png...

 58%|█████▊    | 281/488 [14:01<09:18,  2.70s/it]

Done.
Downloading 1p8WCEhwpgnq5K9RU4b21q020jAcXFMqX into /content/dataset/images/val/58513_isaias_garay_27.png...

 58%|█████▊    | 282/488 [14:03<08:44,  2.55s/it]

Done.
Downloading 1khfklZiX7k_8asp2bQOw_zkD75x-T3qA into /content/dataset/images/val/R-45489_sofiarondini_35.png...

 58%|█████▊    | 283/488 [14:06<08:37,  2.52s/it]

Done.
Downloading 1HLQa0BwfHeOm_i9DeSdapCc42PAHRbGn into /content/dataset/images/val/58912_Timoteo_Garcia_2.jpg...

 58%|█████▊    | 284/488 [14:08<08:41,  2.56s/it]

Done.
Downloading 1Wn_zeTl0q3zZ5oXdUDvejgTjzpgwlnlH into /content/dataset/images/val/s56189_salvador_sanchez_272.jpg...

 58%|█████▊    | 285/488 [14:11<08:33,  2.53s/it]

Done.
Downloading 11SORHDKETC5cGvcQUHYxLgVoxtmA9Et2 into /content/dataset/images/val/s56189_salvador_sanchez_22.jpg...

 59%|█████▊    | 286/488 [14:13<08:06,  2.41s/it]

Done.
Downloading 1uK568-_VOi4KxvUnr8KrS8ueeM-DoVxC into /content/dataset/images/val/L32531_santiago_loza_16.jpg...

 59%|█████▉    | 287/488 [14:16<08:42,  2.60s/it]

Done.
Downloading 1fyzVPuG6d1cP26G9nFbYPEOND-Kd5fDm into /content/dataset/images/val/f37478_santiago_ferrero_15.jpg...

 59%|█████▉    | 288/488 [14:18<08:19,  2.50s/it]

Done.
Downloading 1MNSHi5iRz-xYE7GY3BsTqVbGvKKK9WRt into /content/dataset/images/val/s56189_salvador_sanchez_107.jpg...

 59%|█████▉    | 289/488 [14:21<08:03,  2.43s/it]

Done.
Downloading 1xBRFMcS70gs5tjgSgWbC1CD73kjHTKxO into /content/dataset/images/val/w05576_juan_wagner_23.png...

 59%|█████▉    | 290/488 [14:23<08:04,  2.45s/it]

Done.
Downloading 1UXoSNN1xaUKmXoku-LDdDNu9YpEtHuT0 into /content/dataset/images/val/37524_augusto_farias_15.jpg...

 60%|█████▉    | 291/488 [14:27<09:30,  2.90s/it]

Done.
Downloading 1LgIEtaT4eUmwEn8_1qETLlwYaCFoDMLh into /content/dataset/images/val/s56189_salvador_sanchez_95.jpg...

 60%|█████▉    | 292/488 [14:29<08:43,  2.67s/it]

Done.
Downloading 1Puzl6pODdfkE286rxMvU16uNwg7j0QCT into /content/dataset/images/val/s56189_salvador_sanchez_156.jpg...

 60%|██████    | 293/488 [14:32<08:23,  2.58s/it]

Done.
Downloading 1J3Q5_Kk4EPaco8SywHRDx5CE_eOcCTBq into /content/dataset/images/val/s56189_salvador_sanchez_58.jpg...

 60%|██████    | 294/488 [14:34<07:59,  2.47s/it]

Done.
Downloading 1ST9UQx54NeIMaXNsgJjJ_t4JBNzTKB4U into /content/dataset/images/val/s56189_salvador_sanchez_197.jpg...

 60%|██████    | 295/488 [14:36<07:55,  2.46s/it]

Done.
Downloading 11iIN_Tm6C9a9Z0p3yPhjDP2rS_RTB245 into /content/dataset/images/val/s56189_salvador_sanchez_26.jpg...

 61%|██████    | 296/488 [14:38<07:37,  2.38s/it]

Done.
Downloading 1O8M6FveSSh90qHlECG5QiX9aBWZ8PrGQ into /content/dataset/images/val/s56189_salvador_sanchez_131.jpg...

 61%|██████    | 297/488 [14:41<07:29,  2.35s/it]

Done.
Downloading 1w5pG_bH-cvjiP6iwyaBcI6XnLjHajizE into /content/dataset/images/val/R-45489_sofiarondini_29.png...

 61%|██████    | 298/488 [14:43<07:26,  2.35s/it]

Done.
Downloading 1yLSFn8vphs9yU3uUP1FS37zBexfaPxhL into /content/dataset/images/val/23451_guido_lorenzettibruera_10.jpg...

 61%|██████▏   | 299/488 [14:48<09:23,  2.98s/it]

Done.
Downloading 19Ct_WehaboOyrK63MiW0UiwTdktr6T7q into /content/dataset/images/val/41932688_Simon_Revello_13.png...

 61%|██████▏   | 300/488 [14:52<10:22,  3.31s/it]

Done.
Downloading 1kvFHp4_EhU_ZJXnZK5GAldxVUAAyfBr4 into /content/dataset/images/val/12394_escandell_ariel_23.jpg...

 62%|██████▏   | 301/488 [14:54<09:33,  3.07s/it]

Done.
Downloading 10fgmMu_jbIc-ZJngfSSFRJx2fgis2Vx5 into /content/dataset/images/val/51951_pablo_pistarelli_11.png...

 62%|██████▏   | 302/488 [14:57<09:38,  3.11s/it]

Done.
Downloading 1wO46WqykxrN1yGN0SSxmV0xkVsYlBSl1 into /content/dataset/images/val/58912_Timoteo_Garcia_18.jpg...

 62%|██████▏   | 303/488 [15:00<09:19,  3.02s/it]

Done.
Downloading 1aHpz0Q3mzIR3lzV8f3_o6_oymuAmfkoW into /content/dataset/images/val/P_51977_martin_perrone_37.png...

 62%|██████▏   | 304/488 [15:03<09:17,  3.03s/it]

Done.
Downloading 1smtHHYB5Xd6i3qgZZ3AsVf-d-ucgj0Ne into /content/dataset/images/val/57096_ramiro_sagrera_20.jpg...

 62%|██████▎   | 305/488 [15:06<09:04,  2.98s/it]

Done.
Downloading 1usE5ie5M9ySumfLvru7hamJGWxSoTwfU into /content/dataset/images/val/S57061_Leandro_Salvana_13.png...

 63%|██████▎   | 306/488 [15:09<08:39,  2.85s/it]

Done.
Downloading 1MWvTpC8s1VrjmH2cNRwNaNHq3HZqbg-t into /content/dataset/images/val/7bf69174b70a74f09bef25b228731ef8.png...

 63%|██████▎   | 307/488 [15:11<08:23,  2.78s/it]

Done.
Downloading 19xp8tyIShAgQDu6D1Kpa4puxQZ_R-Y4Q into /content/dataset/images/val/41932688_Simon_Revello_3.png...

 63%|██████▎   | 308/488 [15:16<09:52,  3.29s/it]

Done.
Downloading 1YorvVAAaw0PxZAWfPYiWMdn_Yn7J2UQU into /content/dataset/images/val/s56189_salvador_sanchez_301.jpg...

 63%|██████▎   | 309/488 [15:18<08:52,  2.98s/it]

Done.
Downloading 1kycI3ld7uEvGr9D5yzymescgHV2S1SzO into /content/dataset/images/val/P_51977_martin_perrone_39.png...

 64%|██████▎   | 310/488 [15:21<08:44,  2.95s/it]

Done.
Downloading 153dhVIZhqGmRNRHvP1SquNPJbJzxa2p9 into /content/dataset/images/val/51705_micaela_pozzo_27.png...

 64%|██████▎   | 311/488 [15:23<08:14,  2.79s/it]

Done.
Downloading 1MqdJeADzBv7jX7bMWq5Lrh5luZq3S47k into /content/dataset/images/val/51659_antonio_peroni_04.jpg...

 64%|██████▍   | 312/488 [15:26<08:12,  2.80s/it]

Done.
Downloading 17t00sO-9F1zcWfDguryFkjUwrvWJmzqB into /content/dataset/images/val/58912_Timoteo_Garcia_14.jpg...

 64%|██████▍   | 313/488 [15:30<09:15,  3.18s/it]

Done.
Downloading 1IgR1M0wsd18DpC3jzj0LnR5LBw4vDZyb into /content/dataset/images/val/s56189_salvador_sanchez_54.jpg...

 64%|██████▍   | 314/488 [15:32<08:26,  2.91s/it]

Done.
Downloading 1d_A6kgbv5E1ppyDw9seWjjF8q-XfkQX4 into /content/dataset/images/val/P51951_pablo_pistarelli_06.png...

 65%|██████▍   | 315/488 [15:35<08:31,  2.95s/it]

Done.
Downloading 1NIVuQFakUygr6itIYIxoL_WkjSe03OD5 into /content/dataset/images/val/43237686_Constantino_Ferrucci_2.png...

 65%|██████▍   | 316/488 [15:38<07:58,  2.78s/it]

Done.
Downloading 1G25BzNH7fdkcG8Pl0vuOn2zLjVDZBHHo into /content/dataset/images/val/s56804_alexis_segui_08.png...

 65%|██████▍   | 317/488 [15:40<07:42,  2.70s/it]

Done.
Downloading 15SxVojMVhh0ZWdWZfVci5boFbQsvdKXo into /content/dataset/images/val/41932688_Simon_Revello_17.png...

 65%|██████▌   | 318/488 [15:45<08:51,  3.13s/it]

Done.
Downloading 1-vKYSEvygxKBOkd_NEeqwTBC7wu-VBgH into /content/dataset/images/val/756892fc5ee5de3db6e901f40f106937.png...

 65%|██████▌   | 319/488 [15:47<08:21,  2.96s/it]

Done.
Downloading 1JWdzQmu_l7C9HFuBr50iEO4wWoL_ulnq into /content/dataset/images/val/f37478_santiago_ferrero_07.jpg...

 66%|██████▌   | 320/488 [15:51<09:07,  3.26s/it]

Done.
Downloading 1yTCiO1nnf8P5MuKvAE2GRSzBwjlgX2uL into /content/dataset/images/val/71846_Brisa_Menescaldi_31.png...

 66%|██████▌   | 321/488 [15:55<09:42,  3.49s/it]

Done.
Downloading 1Rkkv1zhKbakh0OpP686RfyXP3KFT-QGw into /content/dataset/images/val/52256_daniel_ponce_31.jpeg...

 66%|██████▌   | 322/488 [15:58<08:49,  3.19s/it]

Done.
Downloading 1XJEUVXp5jmLaStxFAy_0hJrbbCFBOGXA into /content/dataset/images/val/64191_Sofia_BrizuelaCipolletti_25.jpg...

 66%|██████▌   | 323/488 [16:00<08:30,  3.10s/it]

Done.
Downloading 1cxqOE5FA_Jzh5tnugbTWi4xkMuZZ3K4K into /content/dataset/images/val/P51926_Leonel_Palermo_14.png...

 66%|██████▋   | 324/488 [16:05<09:26,  3.45s/it]

Done.
Downloading 183JuCty2U1lGZRubUjesGXG0in1obIop into /content/dataset/images/val/A45161_Fabian_Aguirre_30.png...

 67%|██████▋   | 325/488 [16:09<09:39,  3.56s/it]

Done.
Downloading 1OO8wbymlbA9BHWoLUljXkFUX3n_gBeaG into /content/dataset/images/val/37494_gustavo_fontana_21.jpg...

 67%|██████▋   | 326/488 [16:11<08:57,  3.32s/it]

Done.
Downloading 1WMIb6Qs94kPb0Nvq9df3Jy1Hk0yTeyUO into /content/dataset/images/val/23451_guido_lorenzettibruera_04.jpg...

 67%|██████▋   | 327/488 [16:17<10:29,  3.91s/it]

Done.
Downloading 12eyUx5GNhn52RVUwwQ69U-4KT-OHNWyz into /content/dataset/images/val/L32531_santiago_loza_21.jpg...

 67%|██████▋   | 328/488 [16:19<09:33,  3.58s/it]

Done.
Downloading 1TJBu9ePyd3kyJ50HQ3__Af1HfzWkb3cx into /content/dataset/images/val/S57061_Leandro_Salvana_16.png...

 67%|██████▋   | 329/488 [16:22<08:46,  3.31s/it]

Done.
Downloading 1TSYAF1HtQMHZUzfXl5M2lEiGzCi8pUwq into /content/dataset/images/val/s56189_salvador_sanchez_210.jpg...

 68%|██████▊   | 330/488 [16:24<07:56,  3.01s/it]

Done.
Downloading 17v0sqrlOTRFZAe8L0juDSCLgquNO4T3X into /content/dataset/images/val/64191_Sofia_BrizuelaCipolletti_19.jpg...

 68%|██████▊   | 331/488 [16:27<07:42,  2.95s/it]

Done.
Downloading 1Ji5leIpGu769OLYcT9Uxw58_D17SazaC into /content/dataset/images/val/23451_guido_lorenzettibruera_12.jpg...

 68%|██████▊   | 332/488 [16:31<08:35,  3.30s/it]

Done.
Downloading 1iRiELh6r2kFUP1KI7Pm_-M9_HN2INY3Z into /content/dataset/images/val/P51926_Leonel_Palermo_21.png...

 68%|██████▊   | 333/488 [16:35<08:39,  3.35s/it]

Done.
Downloading 1MAptNPu09JEjmaBHojWuI-AKNI-NGePi into /content/dataset/images/val/s56189_salvador_sanchez_103.jpg...

 68%|██████▊   | 334/488 [16:37<07:48,  3.04s/it]

Done.
Downloading 1-HgNEP-9FDZoq_YLuWQXJrtJ_YIlPH1v into /content/dataset/images/val/cfdf69c24bd61195285179154b612680.png...

 69%|██████▊   | 335/488 [16:40<07:37,  2.99s/it]

Done.
Downloading 1OPE8zoIzFc0sUkLd6Nz0BJk3dbqebfBh into /content/dataset/images/val/s56189_salvador_sanchez_134.jpg...

 69%|██████▉   | 336/488 [16:42<06:57,  2.74s/it]

Done.
Downloading 1VUQjXH0Yp--jsQSRUGuKwcODpybBmxu3 into /content/dataset/images/val/71846_Brisa_Menescaldi_13.png...

 69%|██████▉   | 337/488 [17:06<22:51,  9.08s/it]

Done.
Downloading 1YfBGKA95nbna6nS1WqFI5ZDt6peoLleF into /content/dataset/images/val/46094_Mateo_Rovere_31.png...

 69%|██████▉   | 338/488 [17:09<17:50,  7.14s/it]

Done.
Downloading 1sQgUGBVCrlKQLV3AGYFynNZTPp4gYzoQ into /content/dataset/images/val/72125_miguel_mussi_03.png...

 69%|██████▉   | 339/488 [17:11<14:16,  5.75s/it]

Done.
Downloading 1AczKJk9vf3cuk18c7aWcyOS9sBsqJpN1 into /content/dataset/images/val/23451_guido_lorenzettibruera_15.jpg...

 70%|██████▉   | 340/488 [17:16<13:43,  5.57s/it]

Done.
Downloading 1Q6zA5FysATv6cQVu_eC9wvhlC72Pt7fT into /content/dataset/images/val/L32425_eugenio_lopez_26.png...

 70%|██████▉   | 341/488 [17:19<11:48,  4.82s/it]

Done.
Downloading 1wpIVxmLw5ox42l0TSsR9NykniQfF1pQr into /content/dataset/images/val/F37605_florencia_fernandez_47.png...

 70%|███████   | 342/488 [17:22<10:05,  4.15s/it]

Done.
Downloading 1bD8lLW0rmN28EJscQ7vyjwppN5aXkAeE into /content/dataset/images/val/L32531_santiago_loza_29.jpg...

 70%|███████   | 343/488 [17:25<09:15,  3.83s/it]

Done.
Downloading 1BlgaeE-4KV_GrLuDLuXlLiQdMKnbvXzD into /content/dataset/images/val/51934_pablo_pistelli_20.png...

 70%|███████   | 344/488 [17:29<09:29,  3.96s/it]

Done.
Downloading 153SfkGyjBfkyCKeRZMCDBbecaySE9uky into /content/dataset/images/val/58912_Timoteo_Garcia_30.jpg...

 71%|███████   | 345/488 [17:32<08:30,  3.57s/it]

Done.
Downloading 1BCgcyQqVbYhtPOUUl4NRk8eTayF1uRvM into /content/dataset/images/val/R-45489_sofiarondini_19.png...

 71%|███████   | 346/488 [17:35<08:01,  3.39s/it]

Done.
Downloading 1HMZZMGHU8KdbHiQpGa2Rrq7UsOTf6_E0 into /content/dataset/images/val/S57061_Leandro_Salvana_44.png...

 71%|███████   | 347/488 [17:38<07:37,  3.25s/it]

Done.
Downloading 1iTMjPm8n-Fbpmu_IvoJDmsyrm5jZJ-Ku into /content/dataset/images/val/51705_micaela_pozzo_20.png...

 71%|███████▏  | 348/488 [17:41<07:16,  3.12s/it]

Done.
Downloading 1mfXGEAdq9D6GHtiFOYuF65F_KaPlNUT8 into /content/dataset/images/val/46094_Mateo_Rovere_16.png...

 72%|███████▏  | 349/488 [17:44<07:23,  3.19s/it]

Done.
Downloading 1gjQEQ_V3AkI2AxUma-drd2g2CBnWjwYn into /content/dataset/images/val/43265_Lucas_Demarre_22.jpg...

 72%|███████▏  | 350/488 [17:46<06:46,  2.95s/it]

Done.
Downloading 1f3JtRXXu3WsJ-9iA-e47RZ1pUnDYt2aB into /content/dataset/images/val/51659_antonio_peroni_12.jpg...

 72%|███████▏  | 351/488 [17:49<06:34,  2.88s/it]

Done.
Downloading 1sKFLSprq9quQgc6COARKC2Bqc2j6Es4y into /content/dataset/images/val/ca61f1c99a6baadcf670bb1611e1a577.png...

 72%|███████▏  | 352/488 [17:53<07:34,  3.34s/it]

Done.
Downloading 1fpEwXschIHDWDFDxL82J_2_qLYaEQLag into /content/dataset/images/val/43265_Lucas_Demarre_15.jpg...

 72%|███████▏  | 353/488 [17:56<06:49,  3.03s/it]

Done.
Downloading 1pkYmhEVxzZzNkslcfbfQhfvyZCIiAuuf into /content/dataset/images/val/a018948edae55bc267a596533f44ce26.png...

 73%|███████▎  | 354/488 [17:59<06:41,  3.00s/it]

Done.
Downloading 1abRY_S59K8EjkC1EV7S0LNj83Awfrsfh into /content/dataset/images/val/L32531_santiago_loza_11.jpg...

 73%|███████▎  | 355/488 [18:01<06:23,  2.88s/it]

Done.
Downloading 1Jko0NXjFB60AzrQ2UobCWMNq4YEnAQhL into /content/dataset/images/val/41932688_Simon_Revello_16.png...

 73%|███████▎  | 356/488 [18:05<07:08,  3.25s/it]

Done.
Downloading 1CXjZoesF7aeb5LA39b3W6qzqTFFG0Z7t into /content/dataset/images/val/52256_daniel_ponce_02.jpeg...

 73%|███████▎  | 357/488 [18:08<06:32,  3.00s/it]

Done.
Downloading 1j_rFZb-sGXVFhS54yc_f_dSOKQn5Z33s into /content/dataset/images/val/R-45829_Abril_Rodriguez_11.png...

 73%|███████▎  | 358/488 [18:10<06:06,  2.82s/it]

Done.
Downloading 1JI5PFpHJoyURUMgSxZh8fqISclgFazx5 into /content/dataset/images/val/s56189_salvador_sanchez_55.jpg...

 74%|███████▎  | 359/488 [18:12<05:41,  2.64s/it]

Done.
Downloading 1RVx4IY6JCjDAMemz2Kq7y7PV5fHsPRdT into /content/dataset/images/val/s56189_salvador_sanchez_180.jpg...

 74%|███████▍  | 360/488 [18:15<05:32,  2.60s/it]

Done.
Downloading 1sI2vUqBwmVpv3-hKk4HhmA-RRQi_fQbO into /content/dataset/images/val/57096_ramiro_sagrera_28.jpg...

 74%|███████▍  | 361/488 [18:18<05:34,  2.63s/it]

Done.
Downloading 1shAZSr4DTARcOzYHB8nW0Gxkdm-O9RSU into /content/dataset/images/val/46094_Mateo_Rovere_29.png...

 74%|███████▍  | 362/488 [18:20<05:27,  2.60s/it]

Done.
Downloading 1GL-DaZkbsqdj2tHXHLXAxBm1dLheQom2 into /content/dataset/images/val/f37478_santiago_ferrero_36.jpg...

 74%|███████▍  | 363/488 [18:22<05:04,  2.44s/it]

Done.
Downloading 1Sv-U1CkCzt_Zu1JEKef2Hm1xUduUTxMJ into /content/dataset/images/val/s56189_salvador_sanchez_203.jpg...

 75%|███████▍  | 364/488 [18:25<04:58,  2.40s/it]

Done.
Downloading 1DBHqT49GJARc5k19xVjmSuKSECePsnyr into /content/dataset/images/val/03531_mirian_yanez_16.jpeg...

 75%|███████▍  | 365/488 [18:27<04:58,  2.43s/it]

Done.
Downloading 1Bnn23k8N2PJthNNkpUFksOhcitfM2tTC into /content/dataset/images/val/12394_escandell_ariel_10.jpg...

 75%|███████▌  | 366/488 [18:30<05:08,  2.53s/it]

Done.
Downloading 18XsXcrHfnNN_CNmw5ZYeRS3zQGABZF8l into /content/dataset/images/val/58513_isaias_garay_21.png...

 75%|███████▌  | 367/488 [18:33<05:12,  2.58s/it]

Done.
Downloading 1oK4Iq6qJkznRQXsTYI6aCouclB_C0FYG into /content/dataset/images/val/46094_Mateo_Rovere_24.png...

 75%|███████▌  | 368/488 [18:38<07:02,  3.52s/it]

Done.
Downloading 1POcOSpTCeCDaDfcL-xiYXRPmLMN4Xe7n into /content/dataset/images/val/s56189_salvador_sanchez_150.jpg...

 76%|███████▌  | 369/488 [18:41<06:17,  3.17s/it]

Done.
Downloading 1wegJEMDLo0ZncxpJjfRTBHHrXLOD13QU into /content/dataset/images/val/43841031_Enzo_Ferrari_35.png...

 76%|███████▌  | 370/488 [18:46<07:29,  3.81s/it]

Done.
Downloading 1HV-0IQIZod6dBN-sTCn0kwcMQlzu3Xh7 into /content/dataset/images/val/51705_micaela_pozzo_08.png...

 76%|███████▌  | 371/488 [18:49<06:48,  3.49s/it]

Done.
Downloading 12CRpFe9zc0H6wbfjPAisXAq9F1cs1xk0 into /content/dataset/images/val/12394_escandell_ariel_18.jpg...

 76%|███████▌  | 372/488 [18:51<06:18,  3.26s/it]

Done.
Downloading 12Gr38M1z1PaWUavXpstg6Dq4n0nyKPoz into /content/dataset/images/val/43237686_Constantino_Ferrucci_30.png...

 76%|███████▋  | 373/488 [18:54<05:50,  3.05s/it]

Done.
Downloading 1FFI33mw5Q4JZeeduScCXcG0wOSgshTZb into /content/dataset/images/val/43237686_Constantino_Ferrucci_21.png...

 77%|███████▋  | 374/488 [18:58<06:13,  3.28s/it]

Done.
Downloading 1m9fMsPqPZjN2J4HRX-qoxIROY34R-66z into /content/dataset/images/val/L32531_santiago_loza_6.jpg...

 77%|███████▋  | 375/488 [19:01<06:25,  3.41s/it]

Done.
Downloading 1OhR-MI9k0VEh8g8m5C4Y9tqOS-1Up0IL into /content/dataset/images/val/S57061_Leandro_Salvana_17.png...

 77%|███████▋  | 376/488 [19:04<05:50,  3.13s/it]

Done.
Downloading 1MdyBx7pEfoHndJI4zFRL1uHLN1zIvDew into /content/dataset/images/val/51951_pablo_pistarelli_20.png...

 77%|███████▋  | 377/488 [19:09<06:43,  3.63s/it]

Done.
Downloading 1AxO668titYu9JreTSSyj2s0cS6TAj8v0 into /content/dataset/images/val/58491_fabio_giampaoli_03.png...

 77%|███████▋  | 378/488 [19:14<07:40,  4.18s/it]

Done.
Downloading 1KxL2SmWl7KhuFUZ8FnaVfevcUgYO3zbu into /content/dataset/images/val/43841031_Enzo_Ferrari_03.png...

 78%|███████▊  | 379/488 [19:19<07:45,  4.27s/it]

Done.
Downloading 18fx2jXYfNmpSyv1gMOjsC4BAKpv1cAWA into /content/dataset/images/val/58491_fabio_giampaoli_09.png...

 78%|███████▊  | 380/488 [19:22<06:59,  3.89s/it]

Done.
Downloading 1YktJ2ivvw15_86nV1D6EhQn4ai7wv70N into /content/dataset/images/val/s56189_salvador_sanchez_302.jpg...

 78%|███████▊  | 381/488 [19:24<06:10,  3.47s/it]

Done.
Downloading 1531duqBlMxtk5qlfGR25JDGK15J2fhaC into /content/dataset/images/val/w05576_juan_wagner_24.png...

 78%|███████▊  | 382/488 [19:26<05:29,  3.11s/it]

Done.
Downloading 114DgMfN_0qZ3c2kQaFWcgftoUal8IyAq into /content/dataset/images/val/43237686_Constantino_Ferrucci_0.png...

 78%|███████▊  | 383/488 [19:29<05:13,  2.98s/it]

Done.
Downloading 1ihFUBILCjHpHVwH-TB8lfjb6RuRaViD5 into /content/dataset/images/val/F37605_florencia_fernandez_08.png...

 79%|███████▊  | 384/488 [19:32<04:51,  2.80s/it]

Done.
Downloading 1QSjIza8k4wPJidZLpCHkJqXNXIwtVmDD into /content/dataset/images/val/46019_taiel_raffaeli_05.jpg...

 79%|███████▉  | 385/488 [19:34<04:51,  2.83s/it]

Done.
Downloading 1VKpreE03fIY3qRwJroEla60qdbZO4pEC into /content/dataset/images/val/41932688_Simon_Revello_18.png...

 79%|███████▉  | 386/488 [19:38<05:18,  3.12s/it]

Done.
Downloading 1cJB_315Zfq5FIvleoviayqqD5zp1OZmV into /content/dataset/images/val/S57061_Leandro_Salvana_06.png...

 79%|███████▉  | 387/488 [19:41<05:06,  3.03s/it]

Done.
Downloading 1N3e2zeNVqOgpdB9_owBL774RnM1z5qQW into /content/dataset/images/val/58912_Timoteo_Garcia_22.jpg...

 80%|███████▉  | 388/488 [19:44<04:58,  2.99s/it]

Done.
Downloading 1RYO3k6eNNVv0sKE7QrGPbC53zYrjHBtH into /content/dataset/images/val/f37478_santiago_ferrero_18.jpg...

 80%|███████▉  | 389/488 [19:50<06:37,  4.01s/it]

Done.
Downloading 1ysQV-uomDswz5y7CI_gVPGB50jmSOXdq into /content/dataset/images/val/g5845_gravifiorino_22.jpeg...

 80%|███████▉  | 390/488 [19:53<05:42,  3.50s/it]

Done.
Downloading 1wepLYbd2YcGcc6c4TUyvcW1oyd7BQCDZ into /content/dataset/images/val/g5845_gravifiorino_25.jpeg...

 80%|████████  | 391/488 [19:55<05:04,  3.14s/it]

Done.
Downloading 1Jt7eIMJJppCzF0iMFuo6evZphgUfYeGD into /content/dataset/images/val/43265_Lucas_Demarre_27.jpg...

 80%|████████  | 392/488 [19:57<04:33,  2.85s/it]

Done.
Downloading 1kld4GrvkIUvPwLNhHJDgJ0V7BbR6gnzL into /content/dataset/images/val/37494_gustavo_fontana_12.jpg...

 81%|████████  | 393/488 [20:00<04:35,  2.90s/it]

Done.
Downloading 1Ur6oKYc_URN4q-U5IH2k_IFNY7FTeT9z into /content/dataset/images/val/s56189_salvador_sanchez_228.jpg...

 81%|████████  | 394/488 [20:02<04:17,  2.74s/it]

Done.
Downloading 1DBaOU5Wcp6Kfj77MjhnYJebF0zdy2H74 into /content/dataset/images/val/37494_gustavo_fontana_10.jpg...

 81%|████████  | 395/488 [20:05<04:18,  2.78s/it]

Done.
Downloading 1ouRSXdtO6ro0X2MjzSVq0x1GBE-hWqYU into /content/dataset/images/val/L32531_santiago_loza_40.jpg...

 81%|████████  | 396/488 [20:09<04:30,  2.94s/it]

Done.
Downloading 1LUI7Y-mhEnYM0hcp_NA_DjAb3yAHuNxj into /content/dataset/images/val/52256_daniel_ponce_10.jpeg...

 81%|████████▏ | 397/488 [20:11<04:12,  2.77s/it]

Done.
Downloading 1UDM5wLPEu33pMdhkBefs8Tdo5JB5eUh1 into /content/dataset/images/val/s56189_salvador_sanchez_224.jpg...

 82%|████████▏ | 398/488 [20:13<03:57,  2.64s/it]

Done.
Downloading 1U0Pxkq1MjLZ6YUlQTVRM_weqx1Dt2mfj into /content/dataset/images/val/71846_Brisa_Menescaldi_27.png...

 82%|████████▏ | 399/488 [20:17<04:31,  3.05s/it]

Done.
Downloading 1O_c6WdOE-uwocNm855g4UYhmI4E5kXyi into /content/dataset/images/val/s56804_alexis_segui_21.png...

 82%|████████▏ | 400/488 [20:20<04:09,  2.83s/it]

Done.
Downloading 1CtQrGroqLLetBSFcMFR8VPAvn9YGuEEz into /content/dataset/images/val/s56804_alexis_segui_30.png...

 82%|████████▏ | 401/488 [20:22<03:53,  2.69s/it]

Done.
Downloading 1fof7yxfQMSg3ywb_54s0sM61aiu6to6y into /content/dataset/images/val/12394_escandell_ariel_11.jpg...

 82%|████████▏ | 402/488 [20:25<03:54,  2.73s/it]

Done.
Downloading 150V9Hqv6uZpIKIjaNcosnVhYb8wvTQpQ into /content/dataset/images/val/5214ca56851221cb34ae7f58d4923a40.png...

 83%|████████▎ | 403/488 [20:28<03:51,  2.72s/it]

Done.
Downloading 1KLr-ULu1dMkQXcqXPY8eELPbGicskiee into /content/dataset/images/val/L32531_santiago_loza_25.jpg...

 83%|████████▎ | 404/488 [20:30<03:50,  2.75s/it]

Done.
Downloading 1lGmW-QNzUjQSnVZz7gFpRW0lpZLMcFCx into /content/dataset/images/val/46094_Mateo_Rovere_8.png...

 83%|████████▎ | 405/488 [20:33<03:50,  2.78s/it]

Done.
Downloading 1qIaE6UicUlKhzlAKBPV86I1uz6qKUt-s into /content/dataset/images/val/58513_isaias_garay_14.png...

 83%|████████▎ | 406/488 [20:36<03:36,  2.64s/it]

Done.
Downloading 1nGoPBcwzw37v0Za0hiOqR6w_haQjtdgQ into /content/dataset/images/val/52256_daniel_ponce_14.jpeg...

 83%|████████▎ | 407/488 [20:38<03:23,  2.51s/it]

Done.
Downloading 1KljWWCA1nGEtpRQNfcc7LVIFWUoXcCgj into /content/dataset/images/val/12394_escandell_ariel_30.jpg...

 84%|████████▎ | 408/488 [20:41<03:27,  2.60s/it]

Done.
Downloading 1fpLNZpBAyOGwFQUnKn__YW-5Jb1LtFbI into /content/dataset/images/val/43841031_Enzo_Ferrari_12.png...

 84%|████████▍ | 409/488 [20:44<03:53,  2.95s/it]

Done.
Downloading 1W8kPWlA1OiVA-mSVgpoXBV6v3XHlc-B1 into /content/dataset/images/val/57096_ramiro_sagrera_23.jpg...

 84%|████████▍ | 410/488 [20:48<04:01,  3.10s/it]

Done.
Downloading 1FVDKh519617KbjzzCIYSdcsk44CK5h5g into /content/dataset/images/val/F37605_florencia_fernandez_45.png...

 84%|████████▍ | 411/488 [20:50<03:48,  2.96s/it]

Done.
Downloading 1wJ3dZcJJQUzUNIG1QRZYcVCbp8S88STh into /content/dataset/images/val/L32531_santiago_loza_27.jpg...

 84%|████████▍ | 412/488 [20:53<03:45,  2.97s/it]

Done.
Downloading 1Oq1eD91_Ph2tJYGt-noUN2JAC91YaPrd into /content/dataset/images/val/51951_pablo_pistarelli_30.png...

 85%|████████▍ | 413/488 [20:57<03:59,  3.20s/it]

Done.
Downloading 1KRBL9meFUqsGrwPwBOMpIAukhOUbjlVL into /content/dataset/images/val/s56189_salvador_sanchez_78.jpg...

 85%|████████▍ | 414/488 [21:00<03:40,  2.97s/it]

Done.
Downloading 1nK67i6_9xDq1Jn-sFuTFM9thSThZkGEU into /content/dataset/images/val/P51926_Leonel_Palermo_12.png...

 85%|████████▌ | 415/488 [21:03<03:52,  3.19s/it]

Done.
Downloading 1uHzESIjwXRk3a7fS8lpPV_vb8sHhRErO into /content/dataset/images/val/43841031_Enzo_Ferrari_11.png...

 85%|████████▌ | 416/488 [21:08<04:24,  3.68s/it]

Done.
Downloading 1yO-XiV7shU-fThS_YVcw4SeI1mM28YJf into /content/dataset/images/val/46094_Mateo_Rovere_21.png...

 85%|████████▌ | 417/488 [21:11<04:05,  3.45s/it]

Done.
Downloading 1PQczxeMnjzdZlM91KB7myYZUYLe07zSW into /content/dataset/images/val/58491_fabio_giampaoli_25.png...

 86%|████████▌ | 418/488 [21:17<05:03,  4.33s/it]

Done.
Downloading 1WZ2NP1J0fIArWdPsrscv-xWB4kVkgBq5 into /content/dataset/images/val/03531_mirian_yanez_31.jpeg...

 86%|████████▌ | 419/488 [21:20<04:22,  3.80s/it]

Done.
Downloading 1y2Qbjv5Y4Xi6fYYRa_T2yzLO_8Gi3HMd into /content/dataset/images/val/3326205021f38e32701b096ffa2e8782.png...

 86%|████████▌ | 420/488 [21:23<03:56,  3.48s/it]

Done.
Downloading 1DznyIUPQE46dMhNSbDNDdJjJrSPlhQp9 into /content/dataset/images/val/51951_pablo_pistarelli_27.png...

 86%|████████▋ | 421/488 [21:26<03:53,  3.48s/it]

Done.
Downloading 1N2c408HR5gQtZm1n5fF4RIoBRFSrVy1o into /content/dataset/images/val/64191_Sofia_BrizuelaCipolletti_06.jpg...

 86%|████████▋ | 422/488 [21:29<03:45,  3.42s/it]

Done.
Downloading 1bgfjO_75rVHK1DY0PjYe7kSPe97hfxIB into /content/dataset/images/val/F37605_florencia_fernandez_56.png...

 87%|████████▋ | 423/488 [21:32<03:19,  3.07s/it]

Done.
Downloading 10W9ysHS-sUDLKbVoPtqyLssM-xX3G7HA into /content/dataset/images/val/s56189_salvador_sanchez_14.jpg...

 87%|████████▋ | 424/488 [21:34<03:03,  2.87s/it]

Done.
Downloading 1ayjbTSaOYcq8_T0GYbbeP8AzYqyMRx4o into /content/dataset/images/val/58491_fabio_giampaoli_15.png...

 87%|████████▋ | 425/488 [21:39<03:45,  3.59s/it]

Done.
Downloading 1W0UrbKq-I6hsvnzRLDac83ON8QQQBLho into /content/dataset/images/val/43841031_Enzo_Ferrari_14.png...

 87%|████████▋ | 426/488 [21:45<04:13,  4.09s/it]

Done.
Downloading 1Hw85jGPE19biyeROpaKurQBFsPhihuOo into /content/dataset/images/val/s56804_alexis_segui_13.png...

 88%|████████▊ | 427/488 [21:48<03:47,  3.72s/it]

Done.
Downloading 1v38Q6qTO7rm7Wu9fOx2nZFGr52NaE4l0 into /content/dataset/images/val/58912_Timoteo_Garcia_10.jpg...

 88%|████████▊ | 428/488 [21:50<03:23,  3.39s/it]

Done.
Downloading 1RdKK_mvL4FIq4Jd8F2N6cfxx0FJrjas4 into /content/dataset/images/val/03531_mirian_yanez_30.jpeg...

 88%|████████▊ | 429/488 [21:53<03:14,  3.30s/it]

Done.
Downloading 1mIsZkypUL4XVH5FjUHt8obO_Fvj2IWr8 into /content/dataset/images/val/71846_Brisa_Menescaldi_12.png...

 88%|████████▊ | 430/488 [21:58<03:33,  3.67s/it]

Done.
Downloading 1YRNYOTJGAR6NNIUuO_u-nQwJ17iwla-v into /content/dataset/images/val/s56804_alexis_segui_31.png...

 88%|████████▊ | 431/488 [22:00<03:08,  3.30s/it]

Done.
Downloading 1zXkR7u67mXMzg_wC4QF0Ygpbh_05Cmen into /content/dataset/images/val/37494_gustavo_fontana_08.jpg...

 89%|████████▊ | 432/488 [22:03<02:57,  3.17s/it]

Done.
Downloading 1ee4clmH6e4SN3ZkAt26LeQ73G5dD3b_a into /content/dataset/images/val/S57061_Leandro_Salvana_01.png...

 89%|████████▊ | 433/488 [22:06<02:50,  3.11s/it]

Done.
Downloading 181QOxaV7Qy0m5NUsHBwHKkAQQetA_8zG into /content/dataset/images/val/P_51977_martin_perrone_30.png...

 89%|████████▉ | 434/488 [22:10<02:59,  3.33s/it]

Done.
Downloading 1VjCYMbCjSkascWpLViOFMMGbmfCMM8lp into /content/dataset/images/val/s56189_salvador_sanchez_242.jpg...

 89%|████████▉ | 435/488 [22:12<02:37,  2.97s/it]

Done.
Downloading 1arTqTJu5SEzKF_TaXrFIThArjfA6tVAQ into /content/dataset/images/val/37524_augusto_farias_14.jpg...

 89%|████████▉ | 436/488 [22:16<02:48,  3.24s/it]

Done.
Downloading 1NPxemqjZlEwMx5ObRIc4Pc5Vak3Pszqf into /content/dataset/images/val/s56189_salvador_sanchez_126.jpg...

 90%|████████▉ | 437/488 [22:18<02:31,  2.98s/it]

Done.
Downloading 1_2A4Lt72TOQhvuRiBpWvbzgArKSJVcHp into /content/dataset/images/val/46019_taiel_raffaeli_01.jpg...

 90%|████████▉ | 438/488 [22:21<02:26,  2.92s/it]

Done.
Downloading 1d5Lf774icU-6vuO6gu6QHh9DkPGnCvoz into /content/dataset/images/val/43237686_Constantino_Ferrucci_25.png...

 90%|████████▉ | 439/488 [22:24<02:17,  2.81s/it]

Done.
Downloading 1KVMu83KsRB2f3NBikwrxKH1wA_elkwB3 into /content/dataset/images/val/43237686_Constantino_Ferrucci_29.png...

 90%|█████████ | 440/488 [22:28<02:39,  3.31s/it]

Done.
Downloading 1kmgaHy0TKTZDNcxPkoEU01zIffUeJPvp into /content/dataset/images/val/58912_Timoteo_Garcia_20.jpg...

 90%|█████████ | 441/488 [22:31<02:27,  3.14s/it]

Done.
Downloading 1GJJW_5RVeJC-Kw3WD6xNsdH3U6ka7ZZi into /content/dataset/images/val/R-45829_Abril_Rodriguez_03.png...

 91%|█████████ | 442/488 [22:34<02:24,  3.15s/it]

Done.
Downloading 1mdC6Ik_ArBxsvDd6QLrzxVAMbu1s2kzB into /content/dataset/images/val/s56804_alexis_segui_11.png...

 91%|█████████ | 443/488 [22:36<02:11,  2.92s/it]

Done.
Downloading 1pRRe7dNvUluVXG0ZZhEQwz6CXLZAEDB9 into /content/dataset/images/val/0d4a74a58600d4a06f3738e853d315bb.png...

 91%|█████████ | 444/488 [22:39<02:04,  2.83s/it]

Done.
Downloading 1RpJKl5TjzJWKZbUaXAZyxVmE174J9Cd5 into /content/dataset/images/val/s56189_salvador_sanchez_189.jpg...

 91%|█████████ | 445/488 [22:41<01:54,  2.67s/it]

Done.
Downloading 1uXG4KTZ4wIhV3_iHY8I12HDng8IbfCZw into /content/dataset/images/val/43237686_Constantino_Ferrucci_31.png...

 91%|█████████▏| 446/488 [22:44<01:50,  2.62s/it]

Done.
Downloading 1q9nFtmOwSv7irl5hzp7kbp13IQSYF9lQ into /content/dataset/images/val/F37605_florencia_fernandez_09.png...

 92%|█████████▏| 447/488 [22:46<01:41,  2.48s/it]

Done.
Downloading 1MWjh_Hf2GI55r82RebgIUpsUZgHU46sn into /content/dataset/images/val/s56189_salvador_sanchez_111.jpg...

 92%|█████████▏| 448/488 [22:48<01:38,  2.46s/it]

Done.
Downloading 1GFlFh-bRs_V8kIq0H_O0H80AmamGlMkQ into /content/dataset/images/val/S57061_Leandro_Salvana_14.png...

 92%|█████████▏| 449/488 [22:51<01:38,  2.53s/it]

Done.
Downloading 1Dc-3BYrwEZRKiUFWWFCqpNWiMbBHiEPI into /content/dataset/images/val/R-45489_sofiarondini_32.png...

 92%|█████████▏| 450/488 [22:53<01:34,  2.49s/it]

Done.
Downloading 19Wm3Eeukf8Lcd-5o3j9UBY6rNlMHsKhY into /content/dataset/images/val/P_51977_martin_perrone_14.png...

 92%|█████████▏| 451/488 [22:57<01:39,  2.68s/it]

Done.
Downloading 1H9yulw6pSzr9QeCrsIZNnkBJ8KdaIp2R into /content/dataset/images/val/03531_mirian_yanez_24.jpeg...

 93%|█████████▎| 452/488 [22:59<01:31,  2.55s/it]

Done.
Downloading 12sLVNPd3Lkn-h5T_HzbesFm1320r11mV into /content/dataset/images/val/s56189_salvador_sanchez_36.jpg...

 93%|█████████▎| 453/488 [23:01<01:26,  2.47s/it]

Done.
Downloading 121XV0j6iegI-JhVBmznDYHfIqnnkU5q4 into /content/dataset/images/val/f37478_santiago_ferrero_01.jpg...

 93%|█████████▎| 454/488 [23:05<01:40,  2.96s/it]

Done.
Downloading 1ZCLtyhCLkGg0sF5avDXMPjMI81IeZMiX into /content/dataset/images/val/S57061_Leandro_Salvana_23.png...

 93%|█████████▎| 455/488 [23:08<01:36,  2.93s/it]

Done.
Downloading 18W9mDzb_BBmVXiJWOxq3jBOz7ZDCgv88 into /content/dataset/images/val/43265_Lucas_Demarre_12.jpg...

 93%|█████████▎| 456/488 [23:10<01:26,  2.69s/it]

Done.
Downloading 1OLFnOPuQR9whxVZ8nAzFs-py4_zM6JF2 into /content/dataset/images/val/P_51977_martin_perrone_25.png...

 94%|█████████▎| 457/488 [23:14<01:32,  2.99s/it]

Done.
Downloading 1YRIdfwL6lqnXNvLKdKj_cJ2G7O6LfVBf into /content/dataset/images/val/s56189_salvador_sanchez_294.jpg...

 94%|█████████▍| 458/488 [23:16<01:23,  2.77s/it]

Done.
Downloading 1cE01d2cghaG2fTSyu06tdL23ygDF4KjO into /content/dataset/images/val/8d0247b8948900db41f51c0145b149cb.png...

 94%|█████████▍| 459/488 [23:19<01:20,  2.77s/it]

Done.
Downloading 1nbIiaWYMovScWZw0bl9HUZ-uOqquTPbC into /content/dataset/images/val/7051717faaa066ce59778c412b3c232d.png...

 94%|█████████▍| 460/488 [23:22<01:20,  2.87s/it]

Done.
Downloading 15mENxiLXxjZ_jlAxyVnMnfDS6Fz0aSfU into /content/dataset/images/val/51d4e6083f4c60354fefe46c455ab94a.png...

 94%|█████████▍| 461/488 [23:25<01:18,  2.92s/it]

Done.
Downloading 1LvicD_wMvITgOPOugcKswTs32JNKDJSR into /content/dataset/images/val/s56189_salvador_sanchez_101.jpg...

 95%|█████████▍| 462/488 [23:28<01:13,  2.81s/it]

Done.
Downloading 1K4eTdL5rRmh85d1jRRCLeSrbU8W4LL_B into /content/dataset/images/val/43237686_Constantino_Ferrucci_8.png...

 95%|█████████▍| 463/488 [23:31<01:12,  2.90s/it]

Done.
Downloading 16o19lVYoxhr6k55tp8S9Piu8vQ58NCsL into /content/dataset/images/val/58912_Timoteo_Garcia_21.jpg...

 95%|█████████▌| 464/488 [23:34<01:09,  2.89s/it]

Done.
Downloading 1WiGBs-ZJ4zbghPwV6-71B6JXN9l83Enn into /content/dataset/images/val/6fdccd771fffdc43851975ed788e0bed.png...

 95%|█████████▌| 465/488 [23:37<01:08,  2.98s/it]

Done.
Downloading 1ZRICWS9eJtnHlFNqqnZ5rohIMlEs58rv into /content/dataset/images/val/s56189_salvador_sanchez_307.jpg...

 95%|█████████▌| 466/488 [23:39<01:01,  2.82s/it]

Done.
Downloading 1l4sjggbxMMComxaOV2uTOPiK3s7gytg4 into /content/dataset/images/val/58491_fabio_giampaoli_16.png...

 96%|█████████▌| 467/488 [23:45<01:16,  3.66s/it]

Done.
Downloading 1blqokp7-Mfo9ZSEKKwPI4JwR2NjcpT0C into /content/dataset/images/val/R-45829_Abril_Rodriguez_10.png...

 96%|█████████▌| 468/488 [23:47<01:04,  3.23s/it]

Done.
Downloading 1ZEAwsijh2WBAefkeClx9KfqkW3tbCinN into /content/dataset/images/val/s56189_salvador_sanchez_309.jpg...

 96%|█████████▌| 469/488 [23:49<00:56,  2.95s/it]

Done.
Downloading 1E_d9y26hWVI-o6Z-Ja9CGe0Ml96COGC_ into /content/dataset/images/val/57096_ramiro_sagrera_14.jpg...

 96%|█████████▋| 470/488 [23:52<00:51,  2.84s/it]

Done.
Downloading 13owFnN5wGFAac6hDuezmZMqAAoDRjhJj into /content/dataset/images/val/12394_escandell_ariel_25.jpg...

 97%|█████████▋| 471/488 [23:55<00:48,  2.85s/it]

Done.
Downloading 1uEcXwqAgTrNgMDl8wAcEZbW7hbMgBjZz into /content/dataset/images/val/P51926_Leonel_Palermo_19.png...

 97%|█████████▋| 472/488 [23:59<00:49,  3.11s/it]

Done.
Downloading 1bXgtFIz6cv4dWcw17ex_bhuMnJ0IrgbE into /content/dataset/images/val/43841031_Enzo_Ferrari_29.png...

 97%|█████████▋| 473/488 [24:03<00:51,  3.42s/it]

Done.
Downloading 1NI_euox7NdkUCq3k64T5Z_s3peHPhWFu into /content/dataset/images/val/s56189_salvador_sanchez_123.jpg...

 97%|█████████▋| 474/488 [24:05<00:44,  3.19s/it]

Done.
Downloading 1QLmkA79BPzvl14R6m5NZPEllmYV1wmRI into /content/dataset/images/val/51705_micaela_pozzo_28.png...

 97%|█████████▋| 475/488 [24:08<00:38,  2.98s/it]

Done.
Downloading 1IlIjThaCF661mhvmfVou6n1RFWHyybdS into /content/dataset/images/val/L32531_santiago_loza_20.jpg...

 98%|█████████▊| 476/488 [24:11<00:35,  2.92s/it]

Done.
Downloading 1PUefEzIUH8uJKcEyUdhu7Q1EOczBcaxf into /content/dataset/images/val/s56189_salvador_sanchez_151.jpg...

 98%|█████████▊| 477/488 [24:13<00:29,  2.69s/it]

Done.
Downloading 1-Oo9waGUqa9Lvjp-GdG7y9xAdhcBLEh8 into /content/dataset/images/val/58912_Timoteo_Garcia_17.jpg...

 98%|█████████▊| 478/488 [24:16<00:27,  2.80s/it]

Done.
Downloading 1etm8PlbRzFOA-Kyt3ORJlWnqJIQdRelC into /content/dataset/images/val/64191_Sofia_BrizuelaCipolletti_04.jpg...

 98%|█████████▊| 479/488 [24:18<00:24,  2.74s/it]

Done.
Downloading 1Qaz9Qjwrl3QvrusWN59maBwW0hKe99QB into /content/dataset/images/val/51951_pablo_pistarelli_17.png...

 98%|█████████▊| 480/488 [24:22<00:23,  2.94s/it]

Done.
Downloading 124vJWIyVdLo90Cy3ro93HSZgeMRIpST9 into /content/dataset/images/val/43841031_Enzo_Ferrari_40.png...

 99%|█████████▊| 481/488 [24:26<00:23,  3.29s/it]

Done.
Downloading 1Ll3B1GkRakEK3UZ_Ocs9P83q5VUClojT into /content/dataset/images/val/s56189_salvador_sanchez_98.jpg...

 99%|█████████▉| 482/488 [24:28<00:17,  2.97s/it]

Done.
Downloading 1b_1yDqda9OFwiBytR688pTr1PKXXGs1Z into /content/dataset/images/val/L32425_eugenio_lopez_18.png...

 99%|█████████▉| 483/488 [24:32<00:16,  3.35s/it]

Done.
Downloading 1QLHr_UB--xvZ7cJLzLeJ12x4y8UBG9d5 into /content/dataset/images/val/51705_micaela_pozzo_15.png...

 99%|█████████▉| 484/488 [24:35<00:12,  3.17s/it]

Done.
Downloading 1zm7uIrvJ1TXowoVwbb_7Tyh_ynrzL9pf into /content/dataset/images/val/46019_taiel_raffaeli_31.jpg...

 99%|█████████▉| 485/488 [24:38<00:09,  3.05s/it]

Done.
Downloading 137E9Ri2kORNdFZI17pDMd62_YMiQBhEo into /content/dataset/images/val/F37605_florencia_fernandez_13.png...

100%|█████████▉| 486/488 [24:41<00:06,  3.09s/it]

Done.
Downloading 1Xr51JZHlRzsEY8BklJipPzb3J5Z6P81S into /content/dataset/images/val/w05576_juan_wagner_17.png...

100%|█████████▉| 487/488 [24:43<00:02,  2.85s/it]

Done.
Downloading 1FctcBkcZP-k_JiSG5FVQw8vn7HDWLPDZ into /content/dataset/images/val/A45161_Fabian_Aguirre_14.png...

100%|██████████| 488/488 [24:46<00:00,  3.05s/it]

Done.

  0%|          | 0/1137 [00:00<?, ?it/s]

Downloading 18TX3BPnx-l5C1znZG84pL65_KJyKMIkH into /content/dataset/labels/train/03531_mirian_yanez_01.txt...

  0%|          | 1/1137 [00:02<47:42,  2.52s/it]

Done.
Downloading 14OUPT4ikCpHgxN9DlwbFrPQ6j6opYncF into /content/dataset/labels/train/03531_mirian_yanez_02.txt...

  0%|          | 2/1137 [00:04<46:29,  2.46s/it]

Done.
Downloading 141tsta-hMoOWQFaoH7i7s-4pyPStdrlM into /content/dataset/labels/train/03531_mirian_yanez_03.txt...

  0%|          | 3/1137 [00:07<47:55,  2.54s/it]

Done.
Downloading 1Jazo7M7h11g5KFu3hwSFj_Mhrm2IrzFn into /content/dataset/labels/train/03531_mirian_yanez_04.txt...

  0%|          | 4/1137 [00:10<47:57,  2.54s/it]

Done.
Downloading 10YLuFTVldeIwYX3bo4C30vWx9_WIO0rN into /content/dataset/labels/train/03531_mirian_yanez_05.txt...

  0%|          | 5/1137 [00:12<45:54,  2.43s/it]

Done.
Downloading 11RhqujCR4eY-R1TpujpnWhWBHIrofeeU into /content/dataset/labels/train/03531_mirian_yanez_06.txt...

  1%|          | 6/1137 [00:14<42:53,  2.28s/it]

Done.
Downloading 1cjPl2Who2iUrMsZqOZ4zpygwzw9m62m1 into /content/dataset/labels/train/03531_mirian_yanez_07.txt...

  1%|          | 7/1137 [00:16<44:49,  2.38s/it]

Done.
Downloading 1_wkJ5KF6eOz0mJR1L55xzy2F7KUwisHp into /content/dataset/labels/train/03531_mirian_yanez_08.txt...

  1%|          | 8/1137 [00:19<45:44,  2.43s/it]

Done.
Downloading 1mDfacvqYPDJh7nqQfAUbPznCaFsWGaau into /content/dataset/labels/train/03531_mirian_yanez_09.txt...

  1%|          | 9/1137 [00:21<43:40,  2.32s/it]

Done.
Downloading 1Y9lIV3QQpIYjLEIPuA6M1nPHVibspweR into /content/dataset/labels/train/03531_mirian_yanez_10.txt...

  1%|          | 10/1137 [00:23<43:04,  2.29s/it]

Done.
Downloading 1sxTBMBK-pxIbeMU5vTOvRL890WMgmj7Y into /content/dataset/labels/train/03531_mirian_yanez_11.txt...

  1%|          | 11/1137 [00:25<41:11,  2.19s/it]

Done.
Downloading 1zFO4nDYxMMDAWdWSFiujX_3Hbh9Nn8QN into /content/dataset/labels/train/03531_mirian_yanez_12.txt...

  1%|          | 12/1137 [00:28<43:12,  2.30s/it]

Done.
Downloading 1ZHO29VVvwW27xAgY4AAxb75RtqVhNGyc into /content/dataset/labels/train/03531_mirian_yanez_13.txt...

  1%|          | 13/1137 [00:30<43:28,  2.32s/it]

Done.
Downloading 1g_DS7_MH3g8VCZ-uwvRQaCXNwfhx0DbE into /content/dataset/labels/train/03531_mirian_yanez_14.txt...

  1%|          | 14/1137 [00:33<45:21,  2.42s/it]

Done.
Downloading 1X2KDzwcB4rqE2_KCpUud195eyuR8iyzr into /content/dataset/labels/train/03531_mirian_yanez_15.txt...

  1%|▏         | 15/1137 [00:35<44:30,  2.38s/it]

Done.
Downloading 1GY1Z1vwH_btGYQIUFBzih-iQ8x1q2pV5 into /content/dataset/labels/train/03531_mirian_yanez_17.txt...

  1%|▏         | 16/1137 [00:37<44:23,  2.38s/it]

Done.
Downloading 1K15bZkX0CwKCw64j1GXl1p2oBUz6gOBE into /content/dataset/labels/train/03531_mirian_yanez_18.txt...

  1%|▏         | 17/1137 [00:40<47:35,  2.55s/it]

Done.
Downloading 109FoD39sLpsD1fkwGKWbb9giwQEGtxUK into /content/dataset/labels/train/03531_mirian_yanez_20.txt...

  2%|▏         | 18/1137 [00:43<47:24,  2.54s/it]

Done.
Downloading 1FOZtRmsKmd2E9_73y0c6uY6jsloSFArZ into /content/dataset/labels/train/03531_mirian_yanez_21.txt...

  2%|▏         | 19/1137 [00:45<45:59,  2.47s/it]

Done.
Downloading 14aruNj8eu3ivlj7j5bAq_MDLMu5r3JKN into /content/dataset/labels/train/03531_mirian_yanez_22.txt...

  2%|▏         | 20/1137 [00:47<43:49,  2.35s/it]

Done.
Downloading 1YOjTCRKFwjOwAQGqZO3F3zIvZf8_Ji0s into /content/dataset/labels/train/03531_mirian_yanez_23.txt...

  2%|▏         | 21/1137 [00:49<41:58,  2.26s/it]

Done.
Downloading 1-CRtDyMAsgUfoxkVYebveCZX4XCxwN4k into /content/dataset/labels/train/03531_mirian_yanez_25.txt...

  2%|▏         | 22/1137 [00:52<41:32,  2.24s/it]

Done.
Downloading 1pQpGSozM5glIq6NO0TR5SRAAWd5W0UPF into /content/dataset/labels/train/03531_mirian_yanez_26.txt...

  2%|▏         | 23/1137 [00:54<43:46,  2.36s/it]

Done.
Downloading 12Srgo2lW5A9O4negF0RqFjLTw0VM0b97 into /content/dataset/labels/train/03531_mirian_yanez_27.txt...

  2%|▏         | 24/1137 [00:57<44:25,  2.39s/it]

Done.
Downloading 1aHCS6lnU3mpjP8i96V2Bbw5uNVBrP3dd into /content/dataset/labels/train/03531_mirian_yanez_28.txt...

  2%|▏         | 25/1137 [00:59<45:46,  2.47s/it]

Done.
Downloading 1tfKJ5YoSnXPrPcON8z-WV7E1MUWqODpY into /content/dataset/labels/train/03531_mirian_yanez_29.txt...

  2%|▏         | 26/1137 [01:02<45:48,  2.47s/it]

Done.
Downloading 1X3I33YIU_IBCnci2m20jNhko3d4cvgp3 into /content/dataset/labels/train/10d2680f1d5794a1f9eb029351d4d59f.txt...

  2%|▏         | 27/1137 [01:04<44:08,  2.39s/it]

Done.
Downloading 1yRyIg8hDPLXy-LjDoCZQhFmgZPCGMgPe into /content/dataset/labels/train/12394_escandell_ariel_01.txt...

  2%|▏         | 28/1137 [01:06<42:48,  2.32s/it]

Done.
Downloading 15Ysj8EHqfy1ony6VZ2XdERXBtK7pp8L2 into /content/dataset/labels/train/12394_escandell_ariel_02.txt...

  3%|▎         | 29/1137 [01:08<42:52,  2.32s/it]

Done.
Downloading 13g9cjlO7sX0XAtmz9dXiNBhklDDzWkE0 into /content/dataset/labels/train/12394_escandell_ariel_03.txt...

  3%|▎         | 30/1137 [01:11<42:52,  2.32s/it]

Done.
Downloading 1JG4tHKtaTCPCPRp1TeUoEL9AdbLROXz8 into /content/dataset/labels/train/12394_escandell_ariel_04.txt...

  3%|▎         | 31/1137 [01:15<55:38,  3.02s/it]

Done.
Downloading 10f6gOrBENazud0fuPG4zmNrQaoE_Mt5a into /content/dataset/labels/train/12394_escandell_ariel_05.txt...

  3%|▎         | 32/1137 [01:18<51:26,  2.79s/it]

Done.
Downloading 1DFC6aQT8KeTVTc_z8_sSoCkdvZhpxD9v into /content/dataset/labels/train/12394_escandell_ariel_06.txt...

  3%|▎         | 33/1137 [01:20<48:58,  2.66s/it]

Done.
Downloading 19nfhmPJdVAzgRWRzQ3U0_rVLhvC10Hi_ into /content/dataset/labels/train/12394_escandell_ariel_07.txt...

  3%|▎         | 34/1137 [01:23<48:13,  2.62s/it]

Done.
Downloading 1yb2yLUyU_Blf-xuuvDz3KMTzqTdZEs-4 into /content/dataset/labels/train/12394_escandell_ariel_08.txt...

  3%|▎         | 35/1137 [01:25<45:47,  2.49s/it]

Done.
Downloading 12POteyOlO3hUGtIzfYaI3vNgXazJoD5A into /content/dataset/labels/train/12394_escandell_ariel_09.txt...

  3%|▎         | 36/1137 [01:27<46:09,  2.52s/it]

Done.
Downloading 10BLGSpSrg1o7hw00PZseSlLyAbweesee into /content/dataset/labels/train/12394_escandell_ariel_12.txt...

  3%|▎         | 37/1137 [01:30<44:39,  2.44s/it]

Done.
Downloading 1_BRD3oRX20J2kWUXu2xGqszAgDmRLTbF into /content/dataset/labels/train/12394_escandell_ariel_13.txt...

  3%|▎         | 38/1137 [01:32<43:59,  2.40s/it]

Done.
Downloading 1JgZfM2tMvAbe1RRL5LqsBA7pnSVk5vFs into /content/dataset/labels/train/12394_escandell_ariel_14.txt...

  3%|▎         | 39/1137 [01:34<42:42,  2.33s/it]

Done.
Downloading 1SO1YAUxd-09s8vmj_yj-bS9vmCofTpCd into /content/dataset/labels/train/12394_escandell_ariel_17.txt...

  4%|▎         | 40/1137 [01:37<43:27,  2.38s/it]

Done.
Downloading 1-e8G-h2Q8wtMXgLq34LDIscC2ylfzpi6 into /content/dataset/labels/train/12394_escandell_ariel_19.txt...

  4%|▎         | 41/1137 [01:39<42:18,  2.32s/it]

Done.
Downloading 174FYX7oelcoOEJQxeBtMchOjlwGdlPsV into /content/dataset/labels/train/12394_escandell_ariel_20.txt...

  4%|▎         | 42/1137 [01:41<43:45,  2.40s/it]

Done.
Downloading 14HaotoLyPswROy4Yx-kRAZbuVAt8spg3 into /content/dataset/labels/train/12394_escandell_ariel_22.txt...

  4%|▍         | 43/1137 [01:43<41:43,  2.29s/it]

Done.
Downloading 12ZDEcw-9ho29CIMPCQ7tgTWmoR58OwOE into /content/dataset/labels/train/12394_escandell_ariel_24.txt...

  4%|▍         | 44/1137 [01:46<44:56,  2.47s/it]

Done.
Downloading 1-ECQpKSdBlp39XZ0bnpiLRmQiJw8xfbH into /content/dataset/labels/train/12394_escandell_ariel_27.txt...

  4%|▍         | 45/1137 [01:48<42:55,  2.36s/it]

Done.
Downloading 19qnirZYvToRUd5fg0BlQBq3P_bVSU5eY into /content/dataset/labels/train/12394_escandell_ariel_28.txt...

  4%|▍         | 46/1137 [01:50<41:29,  2.28s/it]

Done.
Downloading 12VGUCIFribPX7HvuhCPZIBFjzBHyUfMF into /content/dataset/labels/train/12394_escandell_ariel_29.txt...

  4%|▍         | 47/1137 [01:53<41:19,  2.28s/it]

Done.
Downloading 1ZXhJndHANcDA0BUveEv__Y-zBv8ErXHl into /content/dataset/labels/train/12394_escandell_ariel_31.txt...

  4%|▍         | 48/1137 [01:55<40:56,  2.26s/it]

Done.
Downloading 1W1EDqaTXsUnnI86Ri13unjSDIQBhqvr0 into /content/dataset/labels/train/2321cd43cc466e7f778598d05b07889c.txt...

  4%|▍         | 49/1137 [01:57<40:10,  2.22s/it]

Done.
Downloading 10O0pU1NH0-ofthHjKpY-pNpJdbByOTne into /content/dataset/labels/train/23451_guido_lorenzettibruera_02.txt...

  4%|▍         | 50/1137 [01:59<41:09,  2.27s/it]

Done.
Downloading 1_mdkRAWxJT8jFEE9XxBSbznki5Ev04JG into /content/dataset/labels/train/23451_guido_lorenzettibruera_05.txt...

  4%|▍         | 51/1137 [02:02<42:43,  2.36s/it]

Done.
Downloading 1SNiSGkHSEyHBokeeuSl5AoEfXcODZdX0 into /content/dataset/labels/train/23451_guido_lorenzettibruera_06.txt...

  5%|▍         | 52/1137 [02:04<41:33,  2.30s/it]

Done.
Downloading 1kAh5O6QwGM_CEmxzI1ZbsyUVOVRra4Iu into /content/dataset/labels/train/23451_guido_lorenzettibruera_08.txt...

  5%|▍         | 53/1137 [02:07<41:56,  2.32s/it]

Done.
Downloading 1O3OsP6vbKfynC8mQBroIw2MJ7-nPLxBd into /content/dataset/labels/train/23451_guido_lorenzettibruera_09.txt...

  5%|▍         | 54/1137 [02:09<40:33,  2.25s/it]

Done.
Downloading 1Finq8RZlb_24Sqqishik5tUKwLaSZEjq into /content/dataset/labels/train/23451_guido_lorenzettibruera_11.txt...

  5%|▍         | 55/1137 [02:11<40:57,  2.27s/it]

Done.
Downloading 1HRX630WXlZF6d5N-b3igeCJhKUzm1isj into /content/dataset/labels/train/23451_guido_lorenzettibruera_13.txt...

  5%|▍         | 56/1137 [02:13<39:26,  2.19s/it]

Done.
Downloading 18csm6glDJUO0OdXOKzrwMZKS6VHSyZ8C into /content/dataset/labels/train/23451_guido_lorenzettibruera_14.txt...

  5%|▌         | 57/1137 [02:15<38:17,  2.13s/it]

Done.
Downloading 1YH2aS2ToJaUqvmSGOPUFzBssB9EVbMa7 into /content/dataset/labels/train/23451_guido_lorenzettibruera_16.txt...

  5%|▌         | 58/1137 [02:17<39:21,  2.19s/it]

Done.
Downloading 1igaNz3peYtLCvdJg46vXTJ25q7J9GZkO into /content/dataset/labels/train/23451_guido_lorenzettibruera_18.txt...

  5%|▌         | 59/1137 [02:19<39:31,  2.20s/it]

Done.
Downloading 1OXxBqy88aKGxPBdbOyQTmL_l6XxwecxT into /content/dataset/labels/train/23451_guido_lorenzettibruera_19.txt...

  5%|▌         | 60/1137 [02:22<40:52,  2.28s/it]

Done.
Downloading 1bxKM1B4FBAnLXx6gmKjCnL3ap9_ETifY into /content/dataset/labels/train/23451_guido_lorenzettibruera_21.txt...

  5%|▌         | 61/1137 [02:24<39:24,  2.20s/it]

Done.
Downloading 1vnv451BgcERJPbv0oX9Y_8Yz-F4C68cQ into /content/dataset/labels/train/23451_guido_lorenzettibruera_22.txt...

  5%|▌         | 62/1137 [02:26<39:08,  2.18s/it]

Done.
Downloading 19qXMea32AmG8g6YMBADYGCodQf5UE375 into /content/dataset/labels/train/23451_guido_lorenzettibruera_23.txt...

  6%|▌         | 63/1137 [02:28<39:35,  2.21s/it]

Done.
Downloading 18VZFFIQ7UVQ3Q9W6cu40KK11lXMZ0rVO into /content/dataset/labels/train/23451_guido_lorenzettibruera_24.txt...

  6%|▌         | 64/1137 [02:30<38:49,  2.17s/it]

Done.
Downloading 1aOkfsoFp69gtxIaj9OX2m6xzj49a84V- into /content/dataset/labels/train/23451_guido_lorenzettibruera_25.txt...

  6%|▌         | 65/1137 [02:33<39:17,  2.20s/it]

Done.
Downloading 1KWuaEV-EUKi_F1_3xlwQaF3dS3oouCM1 into /content/dataset/labels/train/23451_guido_lorenzettibruera_26.txt...

  6%|▌         | 66/1137 [02:35<40:09,  2.25s/it]

Done.
Downloading 1_FkR1eZ-K-p-cmuqb1gQxiAqpvPOU6xL into /content/dataset/labels/train/23451_guido_lorenzettibruera_27.txt...

  6%|▌         | 67/1137 [02:37<40:31,  2.27s/it]

Done.
Downloading 17p2r_sOgcft45eueecGbZw0079JTUL3y into /content/dataset/labels/train/23451_guido_lorenzettibruera_28.txt...

  6%|▌         | 68/1137 [02:40<41:38,  2.34s/it]

Done.
Downloading 1OUOr33YH3vqZM5hWc2-PLpfKKHhU4Dc8 into /content/dataset/labels/train/23451_guido_lorenzettibruera_29.txt...

  6%|▌         | 69/1137 [02:42<41:32,  2.33s/it]

Done.
Downloading 1Ws1S3dz7OIKJ-S2Xb4iUWnauqX1Gh3pj into /content/dataset/labels/train/23451_guido_lorenzettibruera_30.txt...

  6%|▌         | 70/1137 [02:44<40:36,  2.28s/it]

Done.
Downloading 11c9hsKQyx9_GnbhykeBNwUUiX87vPcHX into /content/dataset/labels/train/277a4b435b871683e37e45daca19c4f6.txt...

  6%|▌         | 71/1137 [02:47<41:12,  2.32s/it]

Done.
Downloading 1cVT5kWXYoXJSusmm_3pS9E_EV8wIwplj into /content/dataset/labels/train/293cf3fc96a4dbd5d6004436ddc39b48.txt...

  6%|▋         | 72/1137 [02:49<42:56,  2.42s/it]

Done.
Downloading 1BVvYAL1QcdTAWHqTOhTqePyua0iAKRrH into /content/dataset/labels/train/33db56c3f1d54e81049c8f576f8c5a15.txt...

  6%|▋         | 73/1137 [03:20<3:11:45, 10.81s/it]

Done.
Downloading 1a7hmlldVW9Jeu39MJadseFrmPIVP0RmQ into /content/dataset/labels/train/372d73de811a362dc90c3d847788439f.txt...

  7%|▋         | 74/1137 [03:22<2:26:51,  8.29s/it]

Done.
Downloading 1Erj1rAHU2JasT6_Q1ckrwPeanmnRBth2 into /content/dataset/labels/train/37494_gustavo_fontana_01.txt...

  7%|▋         | 75/1137 [03:24<1:53:41,  6.42s/it]

Done.
Downloading 1gOVuLvY06EDL-Faa6vcsEcnHMnmgjWg4 into /content/dataset/labels/train/37494_gustavo_fontana_02.txt...

  7%|▋         | 76/1137 [03:27<1:32:28,  5.23s/it]

Done.
Downloading 1mrLzKPjvL2zLSkN2txl8I_lY9kq8s1ux into /content/dataset/labels/train/37494_gustavo_fontana_03.txt...

  7%|▋         | 77/1137 [03:29<1:15:35,  4.28s/it]

Done.
Downloading 1MWMGEPGmLUnDg7WJD7NpE9oBJTGGbmou into /content/dataset/labels/train/37494_gustavo_fontana_05.txt...

  7%|▋         | 78/1137 [03:31<1:06:21,  3.76s/it]

Done.
Downloading 1T6PT0xMjbVISGsMyu3lD_jM0pHtvhfWo into /content/dataset/labels/train/37494_gustavo_fontana_07.txt...

  7%|▋         | 79/1137 [03:33<57:21,  3.25s/it]

Done.
Downloading 1CbcKcCyDyaJGCj8Th4ei-JRYoCV_LcII into /content/dataset/labels/train/37494_gustavo_fontana_09.txt...

  7%|▋         | 80/1137 [03:36<51:13,  2.91s/it]

Done.
Downloading 1gCoaPHE2SKJ-7owZojrH03tbz-KFpOw7 into /content/dataset/labels/train/37494_gustavo_fontana_11.txt...

  7%|▋         | 81/1137 [03:38<48:51,  2.78s/it]

Done.
Downloading 12wTJeU7skIVHVbxLEsjI5K0W2Kg4SPVD into /content/dataset/labels/train/37494_gustavo_fontana_13.txt...

  7%|▋         | 82/1137 [03:40<45:21,  2.58s/it]

Done.
Downloading 1WUCoHalJT1Of9UZiqu7lrs0IPPFMrKIE into /content/dataset/labels/train/37494_gustavo_fontana_14.txt...

  7%|▋         | 83/1137 [03:42<43:17,  2.46s/it]

Done.
Downloading 1vax79mvI0FfKksrFabhToDFvypXG89sY into /content/dataset/labels/train/37494_gustavo_fontana_15.txt...

  7%|▋         | 84/1137 [03:45<42:30,  2.42s/it]

Done.
Downloading 1U5rsYD-Q4FV7HIhObdIreS_3FD0rTWix into /content/dataset/labels/train/37494_gustavo_fontana_16.txt...

  7%|▋         | 85/1137 [03:47<40:57,  2.34s/it]

Done.
Downloading 1At20ngqnC2U_lH7-2FS9eSeXANVsr6cf into /content/dataset/labels/train/37494_gustavo_fontana_17.txt...

  8%|▊         | 86/1137 [03:49<39:57,  2.28s/it]

Done.
Downloading 1_Ww-jEGDSrnUJrqwqV3GIP0K7wWN2xDo into /content/dataset/labels/train/37494_gustavo_fontana_18.txt...

  8%|▊         | 87/1137 [03:51<39:43,  2.27s/it]

Done.
Downloading 1dKMjQVHbVSk3A1P0-gz83TH_xlc0_LL7 into /content/dataset/labels/train/37494_gustavo_fontana_19.txt...

  8%|▊         | 88/1137 [03:53<39:08,  2.24s/it]

Done.
Downloading 1aTVfyOpztafSHERlkX9MGgY-gmRMZMzt into /content/dataset/labels/train/37494_gustavo_fontana_22.txt...

  8%|▊         | 89/1137 [03:56<38:39,  2.21s/it]

Done.
Downloading 1xx3QO-02UuLQk-FHY1ik8uMOgglWcrfI into /content/dataset/labels/train/37494_gustavo_fontana_23.txt...

  8%|▊         | 90/1137 [03:58<38:19,  2.20s/it]

Done.
Downloading 165zZEY3Tyissmj5YDDJjI5oY2thyiUsT into /content/dataset/labels/train/37494_gustavo_fontana_24.txt...

  8%|▊         | 91/1137 [04:00<38:40,  2.22s/it]

Done.
Downloading 1tdR60eGS3yuaW8QQSa0DkWHhTJQUDIpn into /content/dataset/labels/train/37494_gustavo_fontana_26.txt...

  8%|▊         | 92/1137 [04:02<38:14,  2.20s/it]

Done.
Downloading 1997tCkkVWiEyT6-5gg2_SiVYd0eVO5Ei into /content/dataset/labels/train/37494_gustavo_fontana_27.txt...

  8%|▊         | 93/1137 [04:05<40:16,  2.31s/it]

Done.
Downloading 1E5fi85UubjZFWLIiXt-MihAE4yMkXOmc into /content/dataset/labels/train/37494_gustavo_fontana_28.txt...

  8%|▊         | 94/1137 [04:07<38:53,  2.24s/it]

Done.
Downloading 1ZqNNI17Z1xeQQK3vYvKK0guOOu2YMVIo into /content/dataset/labels/train/37494_gustavo_fontana_29.txt...

  8%|▊         | 95/1137 [04:10<42:10,  2.43s/it]

Done.
Downloading 1hFux6a5s0ro9zkCmxrod52StftTHv5Yf into /content/dataset/labels/train/37494_gustavo_fontana_30.txt...

  8%|▊         | 96/1137 [04:12<40:07,  2.31s/it]

Done.
Downloading 1J015Gx55_ywGD5GRJgUhKW0NNB0IICzJ into /content/dataset/labels/train/37524_augusto_farias_01.txt...

  9%|▊         | 97/1137 [04:14<38:55,  2.25s/it]

Done.
Downloading 1KY_Y6VjYFpG_jE4X4Y7G8AdWLbSKb-Gg into /content/dataset/labels/train/37524_augusto_farias_03.txt...

  9%|▊         | 98/1137 [04:16<38:57,  2.25s/it]

Done.
Downloading 15SvpvHhaG9i_d5nOMV9O314lqNWSBa24 into /content/dataset/labels/train/37524_augusto_farias_04.txt...

  9%|▊         | 99/1137 [04:18<40:03,  2.32s/it]

Done.
Downloading 1Ini7I3Yczo-XfjAIU8X3s0MyIhEDS76V into /content/dataset/labels/train/37524_augusto_farias_05.txt...

  9%|▉         | 100/1137 [04:21<40:09,  2.32s/it]

Done.
Downloading 1EYazykdz5gBy74HqIf3bU7OY9-Vxwu5c into /content/dataset/labels/train/37524_augusto_farias_06.txt...

  9%|▉         | 101/1137 [04:23<39:28,  2.29s/it]

Done.
Downloading 1YRS1bdlVDgOmp5ud6S1z6LeO1O4RbpDd into /content/dataset/labels/train/37524_augusto_farias_07.txt...

  9%|▉         | 102/1137 [04:25<39:51,  2.31s/it]

Done.
Downloading 1msBwPCM0puGlExPztR66yY4ICyjYcop1 into /content/dataset/labels/train/37524_augusto_farias_09.txt...

  9%|▉         | 103/1137 [04:28<40:05,  2.33s/it]

Done.
Downloading 1xy6i01D306WaV_QqvgN5uMkdWdyS6lP7 into /content/dataset/labels/train/37524_augusto_farias_10.txt...

  9%|▉         | 104/1137 [04:30<38:03,  2.21s/it]

Done.
Downloading 1yH3fnUHMD8X05kMGJyjZNOZlfNv--Q5e into /content/dataset/labels/train/37524_augusto_farias_11.txt...

  9%|▉         | 105/1137 [04:32<37:08,  2.16s/it]

Done.
Downloading 1kBO2Tuwv8BwAHhaNztUVF7waOs8rwBBS into /content/dataset/labels/train/37524_augusto_farias_12.txt...

  9%|▉         | 106/1137 [04:34<36:52,  2.15s/it]

Done.
Downloading 1BZ_bceJZeZe2aT9795TSNALf5imJ6PfY into /content/dataset/labels/train/37524_augusto_farias_13.txt...

  9%|▉         | 107/1137 [04:36<38:40,  2.25s/it]

Done.
Downloading 1I9awau_45yUQ8bwERbIgguiC7zWfWkd1 into /content/dataset/labels/train/37524_augusto_farias_16.txt...

  9%|▉         | 108/1137 [04:39<39:04,  2.28s/it]

Done.
Downloading 1YsdRNGvhl5NxFqZs07L5dLLD0VBV2Lyz into /content/dataset/labels/train/37524_augusto_farias_17.txt...

 10%|▉         | 109/1137 [04:41<38:14,  2.23s/it]

Done.
Downloading 1ClACAMAfnON4sjNEMjgdfNf1QYLzzlqV into /content/dataset/labels/train/37524_augusto_farias_18.txt...

 10%|▉         | 110/1137 [04:44<40:53,  2.39s/it]

Done.
Downloading 1pWnsL_G8zg1zt13XNquYRHFL8MHIR1hm into /content/dataset/labels/train/37524_augusto_farias_19.txt...

 10%|▉         | 111/1137 [04:46<40:18,  2.36s/it]

Done.
Downloading 1d7CF9zokWkfGbzpV2ReCJ9t5iQ1FzdhJ into /content/dataset/labels/train/37524_augusto_farias_20.txt...

 10%|▉         | 112/1137 [04:48<38:14,  2.24s/it]

Done.
Downloading 1YE2uZpN_x_7UKv6TYJqQcAOsD-H-O9CY into /content/dataset/labels/train/37524_augusto_farias_21.txt...

 10%|▉         | 113/1137 [04:50<37:34,  2.20s/it]

Done.
Downloading 13qwQwiOOxyUuUhlGPnv7B3Tu388obaZp into /content/dataset/labels/train/37524_augusto_farias_22.txt...

 10%|█         | 114/1137 [04:52<38:02,  2.23s/it]

Done.
Downloading 1cEt6UtQfdnB7cST2j5qP5nwtWeLWne2T into /content/dataset/labels/train/37524_augusto_farias_23.txt...

 10%|█         | 115/1137 [04:55<42:22,  2.49s/it]

Done.
Downloading 1VwLMljzPpD7j3fYm52GGDQnmosty_sgs into /content/dataset/labels/train/37524_augusto_farias_24.txt...

 10%|█         | 116/1137 [04:58<43:44,  2.57s/it]

Done.
Downloading 12J2HwS0uOvbxYfn_A6XvUFFZRXsGxioq into /content/dataset/labels/train/37524_augusto_farias_25.txt...

 10%|█         | 117/1137 [05:00<42:14,  2.48s/it]

Done.
Downloading 10wmy9bRycRx7HdvX7qExLRDCOyg9gRT- into /content/dataset/labels/train/37524_augusto_farias_26.txt...

 10%|█         | 118/1137 [05:03<41:30,  2.44s/it]

Done.
Downloading 1RNy9DvNJmcY0vXI1kQvpgvyKKy9SHbXv into /content/dataset/labels/train/37524_augusto_farias_27.txt...

 10%|█         | 119/1137 [05:05<41:59,  2.47s/it]

Done.
Downloading 1pjeJPqgNU_KrysyIJS0oUMeGJVh8Xdr8 into /content/dataset/labels/train/37524_augusto_farias_28.txt...

 11%|█         | 120/1137 [05:08<42:52,  2.53s/it]

Done.
Downloading 1B-gzcfCJQ5eEH3QrLohMDOayvp86-6B1 into /content/dataset/labels/train/3f3888c76dfcd3176d832be7c9d7ac23.txt...

 11%|█         | 121/1137 [05:10<40:39,  2.40s/it]

Done.
Downloading 1dkzuJFtljrdatpxx0yJTkFfwJKX1jyKc into /content/dataset/labels/train/41932688_Simon_Revello_0.txt...

 11%|█         | 122/1137 [05:12<40:14,  2.38s/it]

Done.
Downloading 1l90wJliL8szygIksslHY-Fx7IK01Je24 into /content/dataset/labels/train/41932688_Simon_Revello_1.txt...

 11%|█         | 123/1137 [05:15<40:12,  2.38s/it]

Done.
Downloading 14PFV6tLK8Vf27pK0Jbe9MYFZ4RzkdgwW into /content/dataset/labels/train/41932688_Simon_Revello_10.txt...

 11%|█         | 124/1137 [05:17<39:34,  2.34s/it]

Done.
Downloading 1y7rZUfT7CKvKexGcPsS_cJBxTUygHIVX into /content/dataset/labels/train/41932688_Simon_Revello_12.txt...

 11%|█         | 125/1137 [05:20<41:30,  2.46s/it]

Done.
Downloading 1pFptAocHn-af9VL0Fd1cQhSEzYvxPreV into /content/dataset/labels/train/41932688_Simon_Revello_14.txt...

 11%|█         | 126/1137 [05:22<43:08,  2.56s/it]

Done.
Downloading 1cIChufwpucbKrp7BsjjN4pPh3wn2rxRH into /content/dataset/labels/train/41932688_Simon_Revello_15.txt...

 11%|█         | 127/1137 [05:25<43:43,  2.60s/it]

Done.
Downloading 1Gf9oCJo3HxzYtU5RdBBOs2_CEuwNxECf into /content/dataset/labels/train/41932688_Simon_Revello_19.txt...

 11%|█▏        | 128/1137 [05:28<43:03,  2.56s/it]

Done.
Downloading 1IyvEsiUY7PevQ_FHYP3F9Vyc0sep17rO into /content/dataset/labels/train/41932688_Simon_Revello_2.txt...

 11%|█▏        | 129/1137 [05:30<41:43,  2.48s/it]

Done.
Downloading 1WyXBgtcyrcJIQ94vRn5L9Gsm5hz6edpv into /content/dataset/labels/train/41932688_Simon_Revello_20.txt...

 11%|█▏        | 130/1137 [05:33<42:54,  2.56s/it]

Done.
Downloading 1Gt3vMMVsWcIBgCXX9fJj0gUZaYnEq2PU into /content/dataset/labels/train/41932688_Simon_Revello_21.txt...

 12%|█▏        | 131/1137 [05:35<40:36,  2.42s/it]

Done.
Downloading 1R7GApV06bJdjeDWO8FAFVDetFp4tHHCQ into /content/dataset/labels/train/41932688_Simon_Revello_22.txt...

 12%|█▏        | 132/1137 [05:37<39:06,  2.34s/it]

Done.
Downloading 1Ew9pyJa3pQV5J1OW1h5-SnSDMIwHo4ds into /content/dataset/labels/train/41932688_Simon_Revello_23.txt...

 12%|█▏        | 133/1137 [06:07<2:59:41, 10.74s/it]

Done.
Downloading 1B3wVSPjUN9Ett4ztzYdxIhDXt6iTZhKl into /content/dataset/labels/train/41932688_Simon_Revello_24.txt...

 12%|█▏        | 134/1137 [06:10<2:17:23,  8.22s/it]

Done.
Downloading 1FyeaRkOD-J-WfyaTy8NvV962pFXQGDiw into /content/dataset/labels/train/41932688_Simon_Revello_25.txt...

 12%|█▏        | 135/1137 [06:12<1:49:42,  6.57s/it]

Done.
Downloading 1VzV3-1js8JCqvQ9VNfEaOLOTRfpQMEdp into /content/dataset/labels/train/41932688_Simon_Revello_28.txt...

 12%|█▏        | 136/1137 [06:17<1:39:13,  5.95s/it]

Done.
Downloading 1mhv5jvJBpxd5rQL7EsQ72D3CB-TUobvM into /content/dataset/labels/train/41932688_Simon_Revello_29.txt...

 12%|█▏        | 137/1137 [06:19<1:20:52,  4.85s/it]

Done.
Downloading 1iQx7V5wCBr33cysYo1R1W42HkrlnxA9y into /content/dataset/labels/train/41932688_Simon_Revello_30.txt...

 12%|█▏        | 138/1137 [06:22<1:08:29,  4.11s/it]

Done.
Downloading 15p82cl_rCb3y8EltqoNhDHeeSprMDgJk into /content/dataset/labels/train/41932688_Simon_Revello_4.txt...

 12%|█▏        | 139/1137 [06:24<59:24,  3.57s/it]

Done.
Downloading 1lGF5Ck1-45ct66kYrZlU-rfHf23SeNWc into /content/dataset/labels/train/41932688_Simon_Revello_5.txt...

 12%|█▏        | 140/1137 [06:26<52:45,  3.17s/it]

Done.
Downloading 1lrme8vUPO1abMZauBz3gWpRiI8BfxRP6 into /content/dataset/labels/train/41932688_Simon_Revello_7.txt...

 12%|█▏        | 141/1137 [06:28<48:58,  2.95s/it]

Done.
Downloading 1suVJ9X4u0XgcMvcELgCKUXczFBrZEM7e into /content/dataset/labels/train/41932688_Simon_Revello_8.txt...

 12%|█▏        | 142/1137 [06:31<45:51,  2.77s/it]

Done.
Downloading 19JhKitB9qSwOg4b6CmJ16-RDAocnL3lx into /content/dataset/labels/train/41932688_Simon_Revello_9.txt...

 13%|█▎        | 143/1137 [06:31<34:30,  2.08s/it]

Done.
Downloading 1eHTl599BwUOYTiSkWjo96uRPuTqMLvRN into /content/dataset/labels/train/43237686_Constantino_Ferrucci_1.txt...

 13%|█▎        | 144/1137 [06:34<35:46,  2.16s/it]

Done.
Downloading 1hw3_OBLWK83QIk7FIeE8BIQpFoOmc_-l into /content/dataset/labels/train/43237686_Constantino_Ferrucci_12.txt...

 13%|█▎        | 145/1137 [06:34<27:35,  1.67s/it]

Done.
Downloading 1FeZe5YWTKQNeELcftj-DvdguhWhAW2nr into /content/dataset/labels/train/43237686_Constantino_Ferrucci_13.txt...

 13%|█▎        | 146/1137 [06:36<30:32,  1.85s/it]

Done.
Downloading 1HLDsFjBHqb5374e2nF-T5DgifUeBdOMB into /content/dataset/labels/train/43237686_Constantino_Ferrucci_14.txt...

 13%|█▎        | 147/1137 [06:39<32:22,  1.96s/it]

Done.
Downloading 1iOl5HDyvnRrzRQxw3DOm6AlKyVWOJZ_U into /content/dataset/labels/train/43237686_Constantino_Ferrucci_16.txt...

 13%|█▎        | 148/1137 [06:41<32:50,  1.99s/it]

Done.
Downloading 1g5GVMb2vmeT6l4_bmHKb7GelsRPNGpsD into /content/dataset/labels/train/43237686_Constantino_Ferrucci_17.txt...

 13%|█▎        | 149/1137 [06:44<36:52,  2.24s/it]

Done.
Downloading 11mj8L8jtTOBntLq3-fwqFAf-cZG8WAz7 into /content/dataset/labels/train/43237686_Constantino_Ferrucci_18.txt...

 13%|█▎        | 150/1137 [06:46<37:45,  2.30s/it]

Done.
Downloading 1dOztcXBNdfqUleT-n9rWD1CW3ovtaLFy into /content/dataset/labels/train/43237686_Constantino_Ferrucci_19.txt...

 13%|█▎        | 151/1137 [06:48<38:38,  2.35s/it]

Done.
Downloading 1K8GVu0yg6ndOqgQAduU4X_qTbp0SLgYE into /content/dataset/labels/train/43237686_Constantino_Ferrucci_20.txt...

 13%|█▎        | 152/1137 [06:51<38:48,  2.36s/it]

Done.
Downloading 1GSWWxWxI-frFK-nkf7ywAPyxi-DF8kea into /content/dataset/labels/train/43237686_Constantino_Ferrucci_22.txt...

 13%|█▎        | 153/1137 [06:53<39:23,  2.40s/it]

Done.
Downloading 1qqF7VCmpqM6VAf0wypg4yTXxDRaINHEk into /content/dataset/labels/train/43237686_Constantino_Ferrucci_24.txt...

 14%|█▎        | 154/1137 [06:56<41:03,  2.51s/it]

Done.
Downloading 14VmZDbQwsiL4TyKrQq_AE5-K7BYYWlzW into /content/dataset/labels/train/43237686_Constantino_Ferrucci_26.txt...

 14%|█▎        | 155/1137 [06:58<39:32,  2.42s/it]

Done.
Downloading 19i6AtviNphrJfSzXoL-wyy2OT2SzVKEQ into /content/dataset/labels/train/43237686_Constantino_Ferrucci_27.txt...

 14%|█▎        | 156/1137 [07:01<42:11,  2.58s/it]

Done.
Downloading 1eSuyOR3EG_tc13ZwBLPgx9a9hIrIMJkW into /content/dataset/labels/train/43237686_Constantino_Ferrucci_28.txt...

 14%|█▍        | 157/1137 [07:03<40:05,  2.45s/it]

Done.
Downloading 1xKjjl2o-Y3Xx8p926SM1Gg-SyVZLp4Hi into /content/dataset/labels/train/43237686_Constantino_Ferrucci_3.txt...

 14%|█▍        | 158/1137 [07:05<38:02,  2.33s/it]

Done.
Downloading 1yqw-rnTVslAwmj_WAHsGP5niFo-8J2uv into /content/dataset/labels/train/43237686_Constantino_Ferrucci_32.txt...

 14%|█▍        | 159/1137 [07:08<38:23,  2.36s/it]

Done.
Downloading 1yucd8HOwcQOPyWwUsw7wza4zLBUxarPz into /content/dataset/labels/train/43237686_Constantino_Ferrucci_33.txt...

 14%|█▍        | 160/1137 [07:10<39:07,  2.40s/it]

Done.
Downloading 1oBCgCVE3mV6Vt6dJqQnd3fEJvtpWr26n into /content/dataset/labels/train/43237686_Constantino_Ferrucci_34.txt...

 14%|█▍        | 161/1137 [07:13<38:05,  2.34s/it]

Done.
Downloading 1WWb8-krrD_GsOD2A2ZIJTFYgY7_pOUyg into /content/dataset/labels/train/43237686_Constantino_Ferrucci_35.txt...

 14%|█▍        | 162/1137 [07:15<38:16,  2.36s/it]

Done.
Downloading 18OHQz-HxwkclafepDiwQDSf3p_HhWmla into /content/dataset/labels/train/43237686_Constantino_Ferrucci_36.txt...

 14%|█▍        | 163/1137 [07:18<41:24,  2.55s/it]

Done.
Downloading 1RgpVmYQV0XbvlEA_H4oyTT5KsBMal2NK into /content/dataset/labels/train/43237686_Constantino_Ferrucci_4.txt...

 14%|█▍        | 164/1137 [07:20<39:57,  2.46s/it]

Done.
Downloading 1s3IMyHWUKkeMXOHm5d3ymSdSbM6fnpea into /content/dataset/labels/train/43237686_Constantino_Ferrucci_5.txt...

 15%|█▍        | 165/1137 [07:22<38:36,  2.38s/it]

Done.
Downloading 16rNRGIJ3ug2FalS9kOc0xawxUnVX6qUX into /content/dataset/labels/train/43237686_Constantino_Ferrucci_6.txt...

 15%|█▍        | 166/1137 [07:25<39:01,  2.41s/it]

Done.
Downloading 1_QAlQO3gyMkEMS6TzrbArT602yBCzGSU into /content/dataset/labels/train/43237686_Constantino_Ferrucci_7.txt...

 15%|█▍        | 167/1137 [07:27<37:59,  2.35s/it]

Done.
Downloading 1gS0GilBRjt3JnziT9DzcHUtqGlx-IyUN into /content/dataset/labels/train/43237686_Constantino_Ferrucci_9.txt...

 15%|█▍        | 168/1137 [07:29<37:56,  2.35s/it]

Done.
Downloading 15hXTeZZy9zD9tusU4nFudKn53s76v1m7 into /content/dataset/labels/train/43265_Lucas_Demarre_02.txt...

 15%|█▍        | 169/1137 [07:33<43:47,  2.71s/it]

Done.
Downloading 1DZZMUOzjjEi3qolMSGZH9UG8JKbAvxlq into /content/dataset/labels/train/43265_Lucas_Demarre_03.txt...

 15%|█▍        | 170/1137 [07:35<41:50,  2.60s/it]

Done.
Downloading 1fkJ0RQ-XwafVKVPLLsR0sEvQSy-VJfAR into /content/dataset/labels/train/43265_Lucas_Demarre_06.txt...

 15%|█▌        | 171/1137 [07:38<41:26,  2.57s/it]

Done.
Downloading 1PZqFOiagCFqIZVEQoVYHeARWNM00NOkS into /content/dataset/labels/train/43265_Lucas_Demarre_09.txt...

 15%|█▌        | 172/1137 [07:40<39:55,  2.48s/it]

Done.
Downloading 1cO-43Kzg5mnFDZ5GJB0SDCLd3Apr192u into /content/dataset/labels/train/43265_Lucas_Demarre_10.txt...

 15%|█▌        | 173/1137 [07:42<38:40,  2.41s/it]

Done.
Downloading 1O8PzXro2Y4GzuDlWPPU0wzzq6OQBAe5x into /content/dataset/labels/train/43265_Lucas_Demarre_11.txt...

 15%|█▌        | 174/1137 [07:45<38:00,  2.37s/it]

Done.
Downloading 15pFVn0FGX4KWaQSjXdRAqgKQetZ5NgYa into /content/dataset/labels/train/43265_Lucas_Demarre_13.txt...

 15%|█▌        | 175/1137 [07:47<37:58,  2.37s/it]

Done.
Downloading 1el-L0PujJ78u_HqMNBsixT0Yg2pPiSWe into /content/dataset/labels/train/43265_Lucas_Demarre_14.txt...

 15%|█▌        | 176/1137 [07:49<36:50,  2.30s/it]

Done.
Downloading 1jvnlb8ZUq_Pusb1nQD3PWMcHZ398J9QP into /content/dataset/labels/train/43265_Lucas_Demarre_16.txt...

 16%|█▌        | 177/1137 [07:51<36:12,  2.26s/it]

Done.
Downloading 1L6jnbJIP_14cjtaKq3MUSC3cJkRioXEJ into /content/dataset/labels/train/43265_Lucas_Demarre_17.txt...

 16%|█▌        | 178/1137 [07:54<36:35,  2.29s/it]

Done.
Downloading 1w2eq2lHUuyJY97-a55wkhOCidii76fPW into /content/dataset/labels/train/43265_Lucas_Demarre_18.txt...

 16%|█▌        | 179/1137 [07:54<27:45,  1.74s/it]

Done.
Downloading 1HXCQVNO0AqXbOKbbTzqln9B45f3XAqH_ into /content/dataset/labels/train/43265_Lucas_Demarre_20.txt...

 16%|█▌        | 180/1137 [07:57<31:51,  2.00s/it]

Done.
Downloading 190KjCO8fKwzW7EPil50Lw98WZyWlwXUp into /content/dataset/labels/train/43265_Lucas_Demarre_21.txt...

 16%|█▌        | 181/1137 [08:00<35:24,  2.22s/it]

Done.
Downloading 11sODAGBRk3poN1ZtWQFwA_W1x2zJvSeT into /content/dataset/labels/train/43265_Lucas_Demarre_23.txt...

 16%|█▌        | 182/1137 [08:02<35:22,  2.22s/it]

Done.
Downloading 1iB9GmQBxALLJ1ws1Xv6GP3wry--gTkpH into /content/dataset/labels/train/43265_Lucas_Demarre_24.txt...

 16%|█▌        | 183/1137 [08:04<34:55,  2.20s/it]

Done.
Downloading 1m564KQ6XKLWCPsWV54Ue6aZOS4OS3DFb into /content/dataset/labels/train/43265_Lucas_Demarre_25.txt...

 16%|█▌        | 184/1137 [08:06<34:12,  2.15s/it]

Done.
Downloading 1e0gtQeOs5vGTpM1CrD3E1ZvfH4yPPlWI into /content/dataset/labels/train/43265_Lucas_Demarre_26.txt...

 16%|█▋        | 185/1137 [08:09<36:39,  2.31s/it]

Done.
Downloading 13c6_6t7JXHPSgY0e6QYEQJUf2xKDEIci into /content/dataset/labels/train/43265_Lucas_Demarre_28.txt...

 16%|█▋        | 186/1137 [08:11<35:59,  2.27s/it]

Done.
Downloading 1d8thBSXKkaCsgpJ6mmPgbgX3LRRsCk_e into /content/dataset/labels/train/43265_Lucas_Demarre_30.txt...

 16%|█▋        | 187/1137 [08:13<36:44,  2.32s/it]

Done.
Downloading 12KrduJTYIQgLwxBg3-3T6AdxYBjKF3EW into /content/dataset/labels/train/43841031_Enzo_Ferrari_00.txt...

 17%|█▋        | 188/1137 [08:15<36:02,  2.28s/it]

Done.
Downloading 1LI5cXPf_zaHHsptB7gcG0kFCOAgqr9hg into /content/dataset/labels/train/43841031_Enzo_Ferrari_01.txt...

 17%|█▋        | 189/1137 [08:17<35:02,  2.22s/it]

Done.
Downloading 1leK0Y6zA3qzpTm7opwwwjKHguAcQe3an into /content/dataset/labels/train/43841031_Enzo_Ferrari_04.txt...

 17%|█▋        | 190/1137 [08:20<35:12,  2.23s/it]

Done.
Downloading 19KmC1fGUUZ7yLeKcEF7PPvpGxPhmfdri into /content/dataset/labels/train/43841031_Enzo_Ferrari_05.txt...

 17%|█▋        | 191/1137 [08:22<34:45,  2.20s/it]

Done.
Downloading 1p7GIfrNZrwMyIZxKWP0jJ8fWqq4-o4AP into /content/dataset/labels/train/43841031_Enzo_Ferrari_06.txt...

 17%|█▋        | 192/1137 [08:25<37:40,  2.39s/it]

Done.
Downloading 1gRVBeX86Rxh7o-PrJZvWYOa6RA2BIrNY into /content/dataset/labels/train/43841031_Enzo_Ferrari_09.txt...

 17%|█▋        | 193/1137 [08:27<36:59,  2.35s/it]

Done.
Downloading 1F6i1doXmPRVmi-f1pGZ2ZxYjCZW0PfQC into /content/dataset/labels/train/43841031_Enzo_Ferrari_10.txt...

 17%|█▋        | 194/1137 [08:29<36:37,  2.33s/it]

Done.
Downloading 1B0RaWLRhe3VNcdLQMbZ30u-EuJJ908TX into /content/dataset/labels/train/43841031_Enzo_Ferrari_13.txt...

 17%|█▋        | 195/1137 [08:31<34:59,  2.23s/it]

Done.
Downloading 1bO7O1nB635xLA5ZBrsd-ksX0prqVk9Ly into /content/dataset/labels/train/43841031_Enzo_Ferrari_15.txt...

 17%|█▋        | 196/1137 [08:33<34:57,  2.23s/it]

Done.
Downloading 1Fr_DfsRaJE2tRRwQeHyQEjyTF8WnHZWH into /content/dataset/labels/train/43841031_Enzo_Ferrari_16.txt...

 17%|█▋        | 197/1137 [08:36<34:06,  2.18s/it]

Done.
Downloading 1ej0iT3yFmWiq6tWnr-1tA_8opCfZQEkf into /content/dataset/labels/train/43841031_Enzo_Ferrari_17.txt...

 17%|█▋        | 198/1137 [08:36<26:30,  1.69s/it]

Done.
Downloading 1t7zRZi_qeDKQkymKNBSMjMWlT1k-4coC into /content/dataset/labels/train/43841031_Enzo_Ferrari_18.txt...

 18%|█▊        | 199/1137 [08:38<29:00,  1.86s/it]

Done.
Downloading 1n-CowPe1IUj1K2jjp75NkIHEkC1OAYP8 into /content/dataset/labels/train/43841031_Enzo_Ferrari_19.txt...

 18%|█▊        | 200/1137 [08:40<30:02,  1.92s/it]

Done.
Downloading 1E9f-hRsnj1Ql9vAGCL4Fl_afMHMDNgGQ into /content/dataset/labels/train/43841031_Enzo_Ferrari_20.txt...

 18%|█▊        | 201/1137 [08:43<33:33,  2.15s/it]

Done.
Downloading 1f9HtIrLE7nPKPAh5qrLSdl0knM-AD_xJ into /content/dataset/labels/train/43841031_Enzo_Ferrari_21.txt...

 18%|█▊        | 202/1137 [08:45<34:18,  2.20s/it]

Done.
Downloading 1DSINmKbECP1S42f6Vl1cQVo1nNHLAg0l into /content/dataset/labels/train/43841031_Enzo_Ferrari_25.txt...

 18%|█▊        | 203/1137 [08:47<33:46,  2.17s/it]

Done.
Downloading 1LQyWp76_zGalW-IGQrzkAOJxkJ51_F9I into /content/dataset/labels/train/43841031_Enzo_Ferrari_27.txt...

 18%|█▊        | 204/1137 [08:51<37:42,  2.43s/it]

Done.
Downloading 1W7SnLWKI1LlFZJzLZ7a4EJiCe5zlXFNu into /content/dataset/labels/train/43841031_Enzo_Ferrari_28.txt...

 18%|█▊        | 205/1137 [08:53<39:38,  2.55s/it]

Done.
Downloading 1zYGER-W33RETpZ8UGkMzKJzOcam7PQW0 into /content/dataset/labels/train/43841031_Enzo_Ferrari_30.txt...

 18%|█▊        | 206/1137 [08:56<39:22,  2.54s/it]

Done.
Downloading 14xOdaULFltA3-94iS8zIr0pL4wVid6Nn into /content/dataset/labels/train/43841031_Enzo_Ferrari_31.txt...

 18%|█▊        | 207/1137 [08:58<38:07,  2.46s/it]

Done.
Downloading 1iApO0Np1GC5qS3ThsA3AO8pdzdEPSztO into /content/dataset/labels/train/43841031_Enzo_Ferrari_32.txt...

 18%|█▊        | 208/1137 [09:00<36:45,  2.37s/it]

Done.
Downloading 1zIL-eLbnS47UAKF6qgZW7WYMw3CaJxjI into /content/dataset/labels/train/43841031_Enzo_Ferrari_33.txt...

 18%|█▊        | 209/1137 [09:03<36:24,  2.35s/it]

Done.
Downloading 1_lHcvoQ6yJeJKsB244Ji21P3fHN7sMff into /content/dataset/labels/train/43841031_Enzo_Ferrari_36.txt...

 18%|█▊        | 210/1137 [09:05<36:31,  2.36s/it]

Done.
Downloading 1XqMNoPCnw5HezBYpRxdUyRAztCGZ17s7 into /content/dataset/labels/train/43841031_Enzo_Ferrari_38.txt...

 19%|█▊        | 211/1137 [09:08<38:16,  2.48s/it]

Done.
Downloading 1Q3L3MfY0IAQXhmqqXj2Iv1FLprSNxZsb into /content/dataset/labels/train/43841031_Enzo_Ferrari_39.txt...

 19%|█▊        | 212/1137 [09:10<37:21,  2.42s/it]

Done.
Downloading 1DTYKvQMEqJqrAstWrfBMD5ZiWRCbqALw into /content/dataset/labels/train/444067f9638cc7732f454f076cf67609.txt...

 19%|█▊        | 213/1137 [09:12<35:55,  2.33s/it]

Done.
Downloading 1o5MycXNxmW5YhxK0vDkDD-IRau3bkrKr into /content/dataset/labels/train/45d7f692f3ad5a74191f2b002c00f796.txt...

 19%|█▉        | 214/1137 [09:13<27:03,  1.76s/it]

Done.
Downloading 1mRTsrsersSu7jhXg3d3pmZhReCVSDE7F into /content/dataset/labels/train/46019_taiel_raffaeli_02.txt...

 19%|█▉        | 215/1137 [09:15<30:37,  1.99s/it]

Done.
Downloading 1qH_Luj51GIzxOaIIuso6njnmoGRZHk9R into /content/dataset/labels/train/46019_taiel_raffaeli_03.txt...

 19%|█▉        | 216/1137 [09:17<31:31,  2.05s/it]

Done.
Downloading 1zQXeQJjjpjkgSDEClyzoZKYDRbWteL4C into /content/dataset/labels/train/46019_taiel_raffaeli_06.txt...

 19%|█▉        | 217/1137 [09:20<32:04,  2.09s/it]

Done.
Downloading 1T3_lylT9pdq6F3P-_HkQqgpAHnSApOQ2 into /content/dataset/labels/train/46019_taiel_raffaeli_07.txt...

 19%|█▉        | 218/1137 [09:22<32:22,  2.11s/it]

Done.
Downloading 1vcX8-TA2OuzO8H_3ghdjPkHwyIzEnEQD into /content/dataset/labels/train/46019_taiel_raffaeli_08.txt...

 19%|█▉        | 219/1137 [09:24<33:37,  2.20s/it]

Done.
Downloading 1hwXgK25OWiQILBjlSS5_oXjMVcfSctSy into /content/dataset/labels/train/46019_taiel_raffaeli_09.txt...

 19%|█▉        | 220/1137 [09:25<25:32,  1.67s/it]

Done.
Downloading 137XAH-BkGU0yUnLvs_gf8DrSXR2eSvG2 into /content/dataset/labels/train/46019_taiel_raffaeli_10.txt...

 19%|█▉        | 221/1137 [09:27<27:27,  1.80s/it]

Done.
Downloading 14IsFTkENlMWEXaY_dgfBSyM2hAFLMKh6 into /content/dataset/labels/train/46019_taiel_raffaeli_12.txt...

 20%|█▉        | 222/1137 [09:29<29:21,  1.92s/it]

Done.
Downloading 1K3sGSpxQkMe2GJSCZHBRblhF_4RVpFkx into /content/dataset/labels/train/46019_taiel_raffaeli_13.txt...

 20%|█▉        | 223/1137 [09:29<22:35,  1.48s/it]

Done.
Downloading 1G5fviEXA8rqcMVUIVKxdTtAvlkex9gMO into /content/dataset/labels/train/46019_taiel_raffaeli_14.txt...

 20%|█▉        | 224/1137 [09:32<26:46,  1.76s/it]

Done.
Downloading 1KOXJK2TPoOrxcvgyuevH9KPwB3HbQWYV into /content/dataset/labels/train/46019_taiel_raffaeli_15.txt...

 20%|█▉        | 225/1137 [09:34<30:18,  1.99s/it]

Done.
Downloading 1eTJ9zwqJ-g-1CpUml3WGZYaR7wbnt3eS into /content/dataset/labels/train/46019_taiel_raffaeli_16.txt...

 20%|█▉        | 226/1137 [09:36<30:35,  2.02s/it]

Done.
Downloading 1xBHIabNZaTYAiONi-Hc7hJn8j4kfg9xJ into /content/dataset/labels/train/46019_taiel_raffaeli_18.txt...

 20%|█▉        | 227/1137 [09:38<31:10,  2.05s/it]

Done.
Downloading 145kpOUbIGHBtB9MTDaKqOl855MjZkch4 into /content/dataset/labels/train/46019_taiel_raffaeli_21.txt...

 20%|██        | 228/1137 [09:41<31:29,  2.08s/it]

Done.
Downloading 1qsBOjPzOI-pAjfINXzsxCbuLJdZVU4Q7 into /content/dataset/labels/train/46019_taiel_raffaeli_25.txt...

 20%|██        | 229/1137 [09:43<31:24,  2.08s/it]

Done.
Downloading 1tW-SqMv8sngoMYkNINf2biqpsZmZ29n3 into /content/dataset/labels/train/46019_taiel_raffaeli_27.txt...

 20%|██        | 230/1137 [09:48<44:39,  2.95s/it]

Done.
Downloading 1nvL_KwPbbDSbggXCRedFXWzrVhMmOO41 into /content/dataset/labels/train/46019_taiel_raffaeli_28.txt...

 20%|██        | 231/1137 [09:50<40:43,  2.70s/it]

Done.
Downloading 1bMFP25j-Ki2u23tYg5w2c6wwHT3LCQ5H into /content/dataset/labels/train/46019_taiel_raffaeli_32.txt...

 20%|██        | 232/1137 [09:52<38:40,  2.56s/it]

Done.
Downloading 14m6e3RsBw8_mIbpAh-dNJ6ujAIMh-sUG into /content/dataset/labels/train/46019_taiel_raffaeli_35.txt...

 20%|██        | 233/1137 [09:54<36:51,  2.45s/it]

Done.
Downloading 1RMPmEYs5Kw4KU4N2gH6ZmH-Zlw6pqThW into /content/dataset/labels/train/46019_taiel_raffaeli_36.txt...

 21%|██        | 234/1137 [09:56<35:58,  2.39s/it]

Done.
Downloading 10LvgjzzRXyMfYBbZrRDMbbrnohZ8CcOs into /content/dataset/labels/train/46019_taiel_raffaeli_37.txt...

 21%|██        | 235/1137 [09:59<35:04,  2.33s/it]

Done.
Downloading 13_dmZ24Q9rakecI_VLveMUAnvZUwSqZU into /content/dataset/labels/train/46094_Mateo_Rovere_1.txt...

 21%|██        | 236/1137 [10:01<35:02,  2.33s/it]

Done.
Downloading 1Ms8ebihjS5DaHFfJ04wPoIKXmZ64hxwa into /content/dataset/labels/train/46094_Mateo_Rovere_10.txt...

 21%|██        | 237/1137 [10:03<35:23,  2.36s/it]

Done.
Downloading 1AcM2kXmIicvEalB122FKjBqzpoCX0Q2s into /content/dataset/labels/train/46094_Mateo_Rovere_12.txt...

 21%|██        | 238/1137 [10:06<35:11,  2.35s/it]

Done.
Downloading 1U29NRw_EmcnoIxAsLyhM-Q2LMIyOg-B7 into /content/dataset/labels/train/46094_Mateo_Rovere_15.txt...

 21%|██        | 239/1137 [10:08<35:04,  2.34s/it]

Done.
Downloading 1mWOxGUCsuZl3BCTA1lzaqZxS748Pomk6 into /content/dataset/labels/train/46094_Mateo_Rovere_17.txt...

 21%|██        | 240/1137 [10:10<34:52,  2.33s/it]

Done.
Downloading 1wCwfNjy7cz8j9yXC7XjAy6Abs-NBARIR into /content/dataset/labels/train/46094_Mateo_Rovere_18.txt...

 21%|██        | 241/1137 [10:12<33:55,  2.27s/it]

Done.
Downloading 1VBoYNnR9jcgGjg7GccC3IUpkC0Ieafyb into /content/dataset/labels/train/46094_Mateo_Rovere_19.txt...

 21%|██▏       | 242/1137 [10:13<25:45,  1.73s/it]

Done.
Downloading 1aoGvRBLOk7bYhNPRwSCkEp_WFJhEaOcT into /content/dataset/labels/train/46094_Mateo_Rovere_2.txt...

 21%|██▏       | 243/1137 [10:15<28:26,  1.91s/it]

Done.
Downloading 1UAIgzmLeXlZB8ZijThd4NzR40Uu_X2aR into /content/dataset/labels/train/46094_Mateo_Rovere_20.txt...

 21%|██▏       | 244/1137 [10:18<30:12,  2.03s/it]

Done.
Downloading 1rqqOxQowvzUDHu9zVsjKCudGSbQvM3J3 into /content/dataset/labels/train/46094_Mateo_Rovere_26.txt...

 22%|██▏       | 245/1137 [10:21<37:13,  2.50s/it]

Done.
Downloading 1tahg7fFYbLeS7M-b-5DNF8iRrqlKLmqn into /content/dataset/labels/train/46094_Mateo_Rovere_27.txt...

 22%|██▏       | 246/1137 [10:24<39:08,  2.64s/it]

Done.
Downloading 1yY2reX8NmeN6y0gGVZB6JN1nieZIXZNP into /content/dataset/labels/train/46094_Mateo_Rovere_28.txt...

 22%|██▏       | 247/1137 [10:26<37:47,  2.55s/it]

Done.
Downloading 1-wW9h-SeWbBU1HdbMVitpLLet6ZhSEeI into /content/dataset/labels/train/46094_Mateo_Rovere_3.txt...

 22%|██▏       | 248/1137 [10:29<38:34,  2.60s/it]

Done.
Downloading 1JYKAifySOfVir8WW9tLWlqlErGcV-NDK into /content/dataset/labels/train/46094_Mateo_Rovere_32.txt...

 22%|██▏       | 249/1137 [10:31<36:39,  2.48s/it]

Done.
Downloading 10-xWyirrbA8HIVKZMhMnDTwooCdCfjSI into /content/dataset/labels/train/46094_Mateo_Rovere_4.txt...

 22%|██▏       | 250/1137 [10:34<35:55,  2.43s/it]

Done.
Downloading 1pq47kvRN4PBRTOgjjUTHpdFMhWHI9yIs into /content/dataset/labels/train/46094_Mateo_Rovere_5.txt...

 22%|██▏       | 251/1137 [10:36<35:08,  2.38s/it]

Done.
Downloading 1X2_CJXtSeVLTcSxTrXm5Ni-zyY0i_cOp into /content/dataset/labels/train/46094_Mateo_Rovere_9.txt...

 22%|██▏       | 252/1137 [10:38<34:24,  2.33s/it]

Done.
Downloading 1Lk56Hutja5zDY7UQY6j0UU_Xrw1DgOIl into /content/dataset/labels/train/49cf91ad867c2d81a1eef82ebba7c4ee.txt...

 22%|██▏       | 253/1137 [10:41<34:42,  2.36s/it]

Done.
Downloading 1hsrOsx0-kXhfAMVMcmJfHvpiw2vGMNCb into /content/dataset/labels/train/49ec2ac308d5afa8cf63345cc8267d65.txt...

 22%|██▏       | 254/1137 [10:43<34:38,  2.35s/it]

Done.
Downloading 1eRhHsoWvBJ5PvOUVotqoBSWyik-B9qAQ into /content/dataset/labels/train/51659_antonio_peroni_02.txt...

 22%|██▏       | 255/1137 [10:46<35:54,  2.44s/it]

Done.
Downloading 1M6G-VTFpxfMlCEScPR6kj4LrFVxtyNH0 into /content/dataset/labels/train/51659_antonio_peroni_03.txt...

 23%|██▎       | 256/1137 [10:48<34:42,  2.36s/it]

Done.
Downloading 14NmSnAqjxyom5EVQBSOG96IjPDW624ne into /content/dataset/labels/train/51659_antonio_peroni_05.txt...

 23%|██▎       | 257/1137 [10:50<35:49,  2.44s/it]

Done.
Downloading 1savdIL5Tj6VePyEcA-kF74947TexcD4Y into /content/dataset/labels/train/51659_antonio_peroni_06.txt...

 23%|██▎       | 258/1137 [10:53<35:21,  2.41s/it]

Done.
Downloading 10ozjPiyaMi_RtOSRwVLvOFiwSVD4BkAz into /content/dataset/labels/train/51659_antonio_peroni_07.txt...

 23%|██▎       | 259/1137 [10:56<38:51,  2.66s/it]

Done.
Downloading 1PCCzXBdaYsaeH9XVOxV2SvF_gLd09hkA into /content/dataset/labels/train/51659_antonio_peroni_08.txt...

 23%|██▎       | 260/1137 [10:58<37:50,  2.59s/it]

Done.
Downloading 18vGfM-dXvtt3c0VOR3SqqFa9UOLyXUeg into /content/dataset/labels/train/51659_antonio_peroni_09.txt...

 23%|██▎       | 261/1137 [11:01<36:13,  2.48s/it]

Done.
Downloading 1Owfr9rq8XdirG0wsyDFkGYj9VTr_5QAO into /content/dataset/labels/train/51659_antonio_peroni_14.txt...

 23%|██▎       | 262/1137 [11:03<36:19,  2.49s/it]

Done.
Downloading 13lZuLJ3U9jXdDjBNMDdYfMv9t0HGS5Mc into /content/dataset/labels/train/51659_antonio_peroni_15.txt...

 23%|██▎       | 263/1137 [11:05<35:09,  2.41s/it]

Done.
Downloading 1dYxSBaCOM83WQsFExBUR8wzg4hBh26hD into /content/dataset/labels/train/51659_antonio_peroni_16.txt...

 23%|██▎       | 264/1137 [11:08<34:37,  2.38s/it]

Done.
Downloading 1DYD0lTAfHlrNjaDuJbNhU7BdzbPGQF2s into /content/dataset/labels/train/51659_antonio_peroni_17.txt...

 23%|██▎       | 265/1137 [11:10<34:22,  2.37s/it]

Done.
Downloading 1MN3cJZ-VNtNQHFvdF4wjHDEFFZPPK64C into /content/dataset/labels/train/51659_antonio_peroni_18.txt...

 23%|██▎       | 266/1137 [11:12<33:50,  2.33s/it]

Done.
Downloading 1SO8X0Pf3f0WfGFe46TX9u-oE4eXlbMFO into /content/dataset/labels/train/51659_antonio_peroni_19.txt...

 23%|██▎       | 267/1137 [11:15<34:17,  2.36s/it]

Done.
Downloading 1sO3rbA8JsszfYlMQYzH6ZQ9sZ5g1vuzx into /content/dataset/labels/train/51659_antonio_peroni_20.txt...

 24%|██▎       | 268/1137 [11:18<36:08,  2.50s/it]

Done.
Downloading 1tqWqRP9MII9B9sTFLgYNu81Yr-jX3We0 into /content/dataset/labels/train/51659_antonio_peroni_21.txt...

 24%|██▎       | 269/1137 [11:20<34:36,  2.39s/it]

Done.
Downloading 1Qb1j2PTbMpcAHCBm-y5P3pmubZx-JNYC into /content/dataset/labels/train/51659_antonio_peroni_22.txt...

 24%|██▎       | 270/1137 [11:22<33:53,  2.34s/it]

Done.
Downloading 1TCMLgNl-JzV3RAftb8n_uvdMmlEojKGB into /content/dataset/labels/train/51659_antonio_peroni_23.txt...

 24%|██▍       | 271/1137 [11:24<33:54,  2.35s/it]

Done.
Downloading 1icBM4shIw7bqz2yAGJ9WzqUjMnF7CJUb into /content/dataset/labels/train/51659_antonio_peroni_25.txt...

 24%|██▍       | 272/1137 [11:27<33:51,  2.35s/it]

Done.
Downloading 10iXRvCRVBrybZdZ8fA_oOY_3VUvrp_vY into /content/dataset/labels/train/51659_antonio_peroni_26.txt...

 24%|██▍       | 273/1137 [11:29<33:18,  2.31s/it]

Done.
Downloading 1Zjv_dd-90ZaO6Akx-PTzHm30bIQNJxKP into /content/dataset/labels/train/51659_antonio_peroni_27.txt...

 24%|██▍       | 274/1137 [11:31<33:25,  2.32s/it]

Done.
Downloading 1QXGqbQatjYAgAgbNvQWh1Q2Q4RNJurjc into /content/dataset/labels/train/51659_antonio_peroni_29.txt...

 24%|██▍       | 275/1137 [11:33<32:53,  2.29s/it]

Done.
Downloading 1AjsXugJAXRXKux3RV67TduMMd0OV6oa1 into /content/dataset/labels/train/51659_antonio_peroni_30.txt...

 24%|██▍       | 276/1137 [11:36<32:04,  2.24s/it]

Done.
Downloading 1kKJjaM4O_3DYQqM5IWgBZS_wIH6hJop7 into /content/dataset/labels/train/51705_micaela_pozzo_01.txt...

 24%|██▍       | 277/1137 [11:38<33:50,  2.36s/it]

Done.
Downloading 1fBZeiqW-TOmlrLFLXRHw72xNRnmJy0rG into /content/dataset/labels/train/51705_micaela_pozzo_02.txt...

 24%|██▍       | 278/1137 [11:41<35:19,  2.47s/it]

Done.
Downloading 15AJr9WxSZNQVYz_AarzrPtLMBT3VRjTW into /content/dataset/labels/train/51705_micaela_pozzo_03.txt...

 25%|██▍       | 279/1137 [11:43<34:31,  2.41s/it]

Done.
Downloading 1ok6TskTkFrf0n1QhVff7PfnwR3ENe1ko into /content/dataset/labels/train/51705_micaela_pozzo_04.txt...

 25%|██▍       | 280/1137 [11:46<34:41,  2.43s/it]

Done.
Downloading 1CUEM84wjL3jgKgIJXV7DXreGFdNkiunT into /content/dataset/labels/train/51705_micaela_pozzo_06.txt...

 25%|██▍       | 281/1137 [11:46<25:47,  1.81s/it]

Done.
Downloading 11UsQN87Sca0kLlOCysQwRoBkvcXWRVUf into /content/dataset/labels/train/51705_micaela_pozzo_07.txt...

 25%|██▍       | 282/1137 [11:48<27:44,  1.95s/it]

Done.
Downloading 1X0qSgzE8dL6894EqQ2lcKzxIakCfbRvd into /content/dataset/labels/train/51705_micaela_pozzo_09.txt...

 25%|██▍       | 283/1137 [11:52<35:19,  2.48s/it]

Done.
Downloading 1_Ub5gcCwQaf34nR-i2SCxtBWpU3Q0D4g into /content/dataset/labels/train/51705_micaela_pozzo_10.txt...

 25%|██▍       | 284/1137 [11:54<33:58,  2.39s/it]

Done.
Downloading 1d_PBCDk1uhrhSWwpX3UGmIZl8tbxL6VG into /content/dataset/labels/train/51705_micaela_pozzo_12.txt...

 25%|██▌       | 285/1137 [11:56<32:39,  2.30s/it]

Done.
Downloading 1nLzrD6eh2fL3QqXKGRj0k2pBXBcFtAIx into /content/dataset/labels/train/51705_micaela_pozzo_14.txt...

 25%|██▌       | 286/1137 [11:58<31:45,  2.24s/it]

Done.
Downloading 1vLrnXlEwWrQ1wKXQUnBXICGTrlpgQMSo into /content/dataset/labels/train/51705_micaela_pozzo_17.txt...

 25%|██▌       | 287/1137 [12:01<31:43,  2.24s/it]

Done.
Downloading 1Bipzc-hXUCAjbA74RJix4EsJwfhCRjor into /content/dataset/labels/train/51705_micaela_pozzo_18.txt...

 25%|██▌       | 288/1137 [12:03<32:09,  2.27s/it]

Done.
Downloading 1dEzXsBDSaVJ7CJSI5Ha006iQD3rFrK0P into /content/dataset/labels/train/51705_micaela_pozzo_19.txt...

 25%|██▌       | 289/1137 [12:05<32:53,  2.33s/it]

Done.
Downloading 1C2NEP5ds6XZswk_l6FBhebke1ulhGczo into /content/dataset/labels/train/51705_micaela_pozzo_21.txt...

 26%|██▌       | 290/1137 [12:08<33:12,  2.35s/it]

Done.
Downloading 1EU-UfLxGy1sn4TOV1fV8v2pqrhi1DGsu into /content/dataset/labels/train/51705_micaela_pozzo_24.txt...

 26%|██▌       | 291/1137 [12:10<32:11,  2.28s/it]

Done.
Downloading 1nUe6FSdgSsjF2_jlE3o4Vu5v1oDODg9T into /content/dataset/labels/train/51705_micaela_pozzo_26.txt...

 26%|██▌       | 292/1137 [12:13<33:38,  2.39s/it]

Done.
Downloading 1-WZrNPOOGbEYtAWDCld_w17s5ZNpURpL into /content/dataset/labels/train/51705_micaela_pozzo_30.txt...

 26%|██▌       | 293/1137 [12:15<33:07,  2.36s/it]

Done.
Downloading 1aS6ttmwsIZL38vJChHwhAdI_tkJ3Bp7E into /content/dataset/labels/train/517424daa31aef6c50af72ceff7b3b92.txt...

 26%|██▌       | 294/1137 [12:17<33:08,  2.36s/it]

Done.
Downloading 1hOhApzql5Db7tomvoex-KHnBZ_Xnrv-n into /content/dataset/labels/train/51934_pablo_pistelli_03.txt...

 26%|██▌       | 295/1137 [12:20<34:43,  2.47s/it]

Done.
Downloading 1rQvBCGUkZodCI7I6u2BjcLHFFLWLgB69 into /content/dataset/labels/train/51934_pablo_pistelli_04.txt...

 26%|██▌       | 296/1137 [12:22<33:10,  2.37s/it]

Done.
Downloading 1YeE3zeMmBmOMt9RsCWRZ2bYeCsAiUIIt into /content/dataset/labels/train/51934_pablo_pistelli_05.txt...

 26%|██▌       | 297/1137 [12:22<24:58,  1.78s/it]

Done.
Downloading 1Ir8YCXKhAG-eE38qcWCnUO-56HXTYjeb into /content/dataset/labels/train/51934_pablo_pistelli_06.txt...

 26%|██▌       | 298/1137 [12:25<26:31,  1.90s/it]

Done.
Downloading 1GttApRVylyLQCllJmq8Jz2u4B1kIp1QT into /content/dataset/labels/train/51934_pablo_pistelli_09.txt...

 26%|██▋       | 299/1137 [12:27<29:11,  2.09s/it]

Done.
Downloading 1yvYVosLjHzt8CU857orcDP2c55Ce-lvI into /content/dataset/labels/train/51934_pablo_pistelli_10.txt...

 26%|██▋       | 300/1137 [12:29<29:35,  2.12s/it]

Done.
Downloading 12ZGrqnt-1GHM3mctYquyZ2jBz2oRHwHE into /content/dataset/labels/train/51934_pablo_pistelli_11.txt...

 26%|██▋       | 301/1137 [12:32<30:33,  2.19s/it]

Done.
Downloading 1CvwO9l4XzpAW8A0ToOzHkIj2cIBi8-cc into /content/dataset/labels/train/51934_pablo_pistelli_12.txt...

 27%|██▋       | 302/1137 [12:34<31:22,  2.25s/it]

Done.
Downloading 12P70oqujASQySoYLlWyAu2iIXaCuyjd8 into /content/dataset/labels/train/51934_pablo_pistelli_13.txt...

 27%|██▋       | 303/1137 [12:37<31:50,  2.29s/it]

Done.
Downloading 1EyNHX3Bfz5FLQ5pmGP2m1QN6k-ZgqpQb into /content/dataset/labels/train/51934_pablo_pistelli_14.txt...

 27%|██▋       | 304/1137 [12:39<32:29,  2.34s/it]

Done.
Downloading 1cSQI-7h2wL7yL6QOZHhZv66AN0T3_yxX into /content/dataset/labels/train/51934_pablo_pistelli_15.txt...

 27%|██▋       | 305/1137 [12:41<31:47,  2.29s/it]

Done.
Downloading 1nzqQJGm1opmk1RQFMp3oR4Rb_RPHOF72 into /content/dataset/labels/train/51934_pablo_pistelli_16.txt...

 27%|██▋       | 306/1137 [12:44<32:05,  2.32s/it]

Done.
Downloading 1F_--JkfvaieUo6E9aZJUN89Mq55VCWza into /content/dataset/labels/train/51934_pablo_pistelli_17.txt...

 27%|██▋       | 307/1137 [12:46<32:59,  2.38s/it]

Done.
Downloading 19MdJfdfleq5bbxoe6YTUgMKEwBkofl3F into /content/dataset/labels/train/51934_pablo_pistelli_18.txt...

 27%|██▋       | 308/1137 [12:48<32:43,  2.37s/it]

Done.
Downloading 16nd1su_b8cvbclUSzlCt28GydgSM18It into /content/dataset/labels/train/51934_pablo_pistelli_21.txt...

 27%|██▋       | 309/1137 [12:51<32:23,  2.35s/it]

Done.
Downloading 1sYVTy6gjQ1agFxB89g7dzV2KWRRs90pc into /content/dataset/labels/train/51934_pablo_pistelli_23.txt...

 27%|██▋       | 310/1137 [12:53<31:33,  2.29s/it]

Done.
Downloading 1QC5rPIm96UQlxV-uoVCyeU0r9GA-3QEn into /content/dataset/labels/train/51934_pablo_pistelli_24.txt...

 27%|██▋       | 311/1137 [12:54<26:34,  1.93s/it]

Done.
Downloading 195tGXttyaAP76JShfURYrFZMTUENDHrn into /content/dataset/labels/train/51934_pablo_pistelli_25.txt...

 27%|██▋       | 312/1137 [12:56<27:38,  2.01s/it]

Done.
Downloading 1Ety4h1DzJhiD5QeO81ohGrpNXQbQR7s- into /content/dataset/labels/train/51934_pablo_pistelli_26.txt...

 28%|██▊       | 313/1137 [12:58<27:56,  2.04s/it]

Done.
Downloading 1HhcVhqjjMT1z-YtxIMZfR64TLx-No6I5 into /content/dataset/labels/train/51934_pablo_pistelli_27.txt...

 28%|██▊       | 314/1137 [13:00<28:21,  2.07s/it]

Done.
Downloading 1eMU4nbGIQehM4ib1PODyqF6LkScfgkBQ into /content/dataset/labels/train/51934_pablo_pistelli_28.txt...

 28%|██▊       | 315/1137 [13:03<29:28,  2.15s/it]

Done.
Downloading 1HgitLdwqwmywgr-H2B0Dzb1WnG1lICWv into /content/dataset/labels/train/51934_pablo_pistelli_29.txt...

 28%|██▊       | 316/1137 [13:05<30:32,  2.23s/it]

Done.
Downloading 1wCFPW9skFPrtWq-8NzldK41ElBlCIBQP into /content/dataset/labels/train/51951_pablo_pistarelli_10.txt...

 28%|██▊       | 317/1137 [13:08<32:25,  2.37s/it]

Done.
Downloading 1GiHC46K74dC0GLeOUqYft9LGtP5XWpgK into /content/dataset/labels/train/51951_pablo_pistarelli_12.txt...

 28%|██▊       | 318/1137 [13:11<35:10,  2.58s/it]

Done.
Downloading 1mrhJ5xZk_RPmcQh0gjvUpotv-c4rgD2l into /content/dataset/labels/train/51951_pablo_pistarelli_14.txt...

 28%|██▊       | 319/1137 [13:13<33:29,  2.46s/it]

Done.
Downloading 1OacsHNmWOzOdmvs_elz-DQpdoqDN5wiO into /content/dataset/labels/train/51951_pablo_pistarelli_15.txt...

 28%|██▊       | 320/1137 [13:16<35:56,  2.64s/it]

Done.
Downloading 1gxy4odAzzrscPSNmIz3J5XV587OvKfdE into /content/dataset/labels/train/51951_pablo_pistarelli_16.txt...

 28%|██▊       | 321/1137 [13:19<35:06,  2.58s/it]

Done.
Downloading 1L2p8_01j13jZ-87H7BF95v080MTJm9dr into /content/dataset/labels/train/51951_pablo_pistarelli_18.txt...

 28%|██▊       | 322/1137 [13:21<34:53,  2.57s/it]

Done.
Downloading 1kBdE4Tm2qkRMEGK47EToBKy0BACUPXch into /content/dataset/labels/train/51951_pablo_pistarelli_19.txt...

 28%|██▊       | 323/1137 [13:24<34:13,  2.52s/it]

Done.
Downloading 1IB8dgKQW4Z3IotMBhh4A-Uaj1VOd2Puc into /content/dataset/labels/train/51951_pablo_pistarelli_21.txt...

 28%|██▊       | 324/1137 [13:26<34:07,  2.52s/it]

Done.
Downloading 1JgTH2LhNMUeTCoqAKHkzn0ImiFkmGPg7 into /content/dataset/labels/train/51951_pablo_pistarelli_22.txt...

 29%|██▊       | 325/1137 [13:28<33:37,  2.48s/it]

Done.
Downloading 1AZke5gGGhwqS1Y8T-uXZdCmW-o-Aj75q into /content/dataset/labels/train/51951_pablo_pistarelli_23.txt...

 29%|██▊       | 326/1137 [13:31<33:04,  2.45s/it]

Done.
Downloading 1DmdQAnhQRj3uXhdNWrEN33q1mRQxW4HP into /content/dataset/labels/train/51951_pablo_pistarelli_24.txt...

 29%|██▉       | 327/1137 [13:33<31:54,  2.36s/it]

Done.
Downloading 1DhqLI6uIIfFDHk6EoXsz-alXiBBPmeq5 into /content/dataset/labels/train/51951_pablo_pistarelli_25.txt...

 29%|██▉       | 328/1137 [13:36<32:41,  2.42s/it]

Done.
Downloading 1QP0dpEBmy6_flnO_iNW68-m8_n-bng3A into /content/dataset/labels/train/51951_pablo_pistarelli_26.txt...

 29%|██▉       | 329/1137 [13:38<31:57,  2.37s/it]

Done.
Downloading 14NF7XkDcd1nA5ASRn6NRFm8Vj-m8mcSJ into /content/dataset/labels/train/51951_pablo_pistarelli_29.txt...

 29%|██▉       | 330/1137 [13:40<30:55,  2.30s/it]

Done.
Downloading 1jkmu5RgyDxWhajUpbdu3haEjdRloaONS into /content/dataset/labels/train/52256_daniel_ponce_01.txt...

 29%|██▉       | 331/1137 [13:42<29:42,  2.21s/it]

Done.
Downloading 15CT_GRyLEIA8uf-gQF2wikmBb-YN25kU into /content/dataset/labels/train/52256_daniel_ponce_04.txt...

 29%|██▉       | 332/1137 [13:45<31:51,  2.37s/it]

Done.
Downloading 18kc0yMumhnlkGxdQSDSnmaCU-GnOe7DZ into /content/dataset/labels/train/52256_daniel_ponce_05.txt...

 29%|██▉       | 333/1137 [13:47<32:19,  2.41s/it]

Done.
Downloading 1n6Hn8_bljhC6fYG9QM9QDTaCyHvauH8w into /content/dataset/labels/train/52256_daniel_ponce_06.txt...

 29%|██▉       | 334/1137 [13:50<33:07,  2.48s/it]

Done.
Downloading 1YwxUwtW3UvZN4k7pt5CgXSY6tAz1VnUl into /content/dataset/labels/train/52256_daniel_ponce_07.txt...

 29%|██▉       | 335/1137 [13:53<34:40,  2.59s/it]

Done.
Downloading 1mZxXpI-sWCgJwvkVt-bqfDu45OBfbcac into /content/dataset/labels/train/52256_daniel_ponce_08.txt...

 30%|██▉       | 336/1137 [13:55<33:01,  2.47s/it]

Done.
Downloading 1DGJtkVlypwHcbSsuErOlW7kuoHr1cg0b into /content/dataset/labels/train/52256_daniel_ponce_09.txt...

 30%|██▉       | 337/1137 [13:57<31:39,  2.37s/it]

Done.
Downloading 12_gWKoZgEKOd_W6aZgm7OsR8EnyRAf0p into /content/dataset/labels/train/52256_daniel_ponce_13.txt...

 30%|██▉       | 338/1137 [13:59<31:22,  2.36s/it]

Done.
Downloading 1i1GH8AG5cF07Qi9kg0KERY2Vo34L0r1L into /content/dataset/labels/train/52256_daniel_ponce_15.txt...

 30%|██▉       | 339/1137 [14:01<30:32,  2.30s/it]

Done.
Downloading 1JlM65cG4LCc0Ik-FtQ-HoIMc29wqIMqR into /content/dataset/labels/train/52256_daniel_ponce_16.txt...

 30%|██▉       | 340/1137 [14:04<32:21,  2.44s/it]

Done.
Downloading 1C-hPuBItl8qP7SfKSzQybcb7eEdScPyt into /content/dataset/labels/train/52256_daniel_ponce_18.txt...

 30%|██▉       | 341/1137 [14:07<33:46,  2.55s/it]

Done.
Downloading 1OakwXbNsa1ioWpzMcZ7ahu38THdLiugH into /content/dataset/labels/train/52256_daniel_ponce_19.txt...

 30%|███       | 342/1137 [14:10<34:36,  2.61s/it]

Done.
Downloading 1LAXf_Zz_VWR4_PAjbbj9bChpB3R7EMpO into /content/dataset/labels/train/52256_daniel_ponce_20.txt...

 30%|███       | 343/1137 [14:12<34:10,  2.58s/it]

Done.
Downloading 1XppESZut5eywQdQPYztqs4BUDRDQgg9S into /content/dataset/labels/train/52256_daniel_ponce_21.txt...

 30%|███       | 344/1137 [14:14<32:01,  2.42s/it]

Done.
Downloading 1FLvg8JldyBAGp7kRKcxXXrheNvyaTEjb into /content/dataset/labels/train/52256_daniel_ponce_22.txt...

 30%|███       | 345/1137 [14:17<33:58,  2.57s/it]

Done.
Downloading 1O-PvKZ-55piN8onp6vLT1mbiAyW2vq9F into /content/dataset/labels/train/52256_daniel_ponce_24.txt...

 30%|███       | 346/1137 [14:19<32:01,  2.43s/it]

Done.
Downloading 161djptKju5PD-6zDp6zM7PcknrFJquOb into /content/dataset/labels/train/52256_daniel_ponce_25.txt...

 31%|███       | 347/1137 [14:22<32:56,  2.50s/it]

Done.
Downloading 1jSuHmmESrQ2SAwyLNXbEoXmxBcgwJgBN into /content/dataset/labels/train/52256_daniel_ponce_26.txt...

 31%|███       | 348/1137 [14:24<32:07,  2.44s/it]

Done.
Downloading 10gAA5jzRMTHKa_WCqdCMJgmgGEM6ZPf7 into /content/dataset/labels/train/52256_daniel_ponce_27.txt...

 31%|███       | 349/1137 [14:27<32:41,  2.49s/it]

Done.
Downloading 1oIKc9TQLBXYR5ELSqNfSyI4qnXgJDscZ into /content/dataset/labels/train/52256_daniel_ponce_28.txt...

 31%|███       | 350/1137 [14:30<33:02,  2.52s/it]

Done.
Downloading 1S3IKFOA6eWTFLFiGmUG3uPqDaaC96wr7 into /content/dataset/labels/train/52256_daniel_ponce_29.txt...

 31%|███       | 351/1137 [14:32<32:33,  2.49s/it]

Done.
Downloading 1VZiDol7BLC90Tspf_szPK0xGbZmbEVP0 into /content/dataset/labels/train/567df7320cea887c8ddf80cbb6482d54.txt...

 31%|███       | 352/1137 [14:34<30:58,  2.37s/it]

Done.
Downloading 1QzrAFp0q-vlzxPXmSkvoCwufPfddz-vB into /content/dataset/labels/train/57096_ramiro_sagrera_01.txt...

 31%|███       | 353/1137 [14:37<32:16,  2.47s/it]

Done.
Downloading 12P8l_OAuNsCKyg0ryyxqNAIeafMkJAye into /content/dataset/labels/train/57096_ramiro_sagrera_02.txt...

 31%|███       | 354/1137 [14:39<31:56,  2.45s/it]

Done.
Downloading 12Ejghhhytz_e9yQoJp4pOdYbOTZjNIy3 into /content/dataset/labels/train/57096_ramiro_sagrera_04.txt...

 31%|███       | 355/1137 [14:42<32:58,  2.53s/it]

Done.
Downloading 1p3yab0dA9hQjrNbc8zo8bkCYyUIDIpj0 into /content/dataset/labels/train/57096_ramiro_sagrera_05.txt...

 31%|███▏      | 356/1137 [14:45<33:15,  2.56s/it]

Done.
Downloading 1iPXCe5O2m0nsZVAiADwfiVEEJRY1RprH into /content/dataset/labels/train/57096_ramiro_sagrera_06.txt...

 31%|███▏      | 357/1137 [14:47<32:47,  2.52s/it]

Done.
Downloading 1c7-B7ZcIj4QrAJwu8KA2zaHZwGlh54eD into /content/dataset/labels/train/57096_ramiro_sagrera_08.txt...

 31%|███▏      | 358/1137 [14:50<33:12,  2.56s/it]

Done.
Downloading 1IETz17GnBMa-yPqijTKr-TpPA4yvHHz- into /content/dataset/labels/train/57096_ramiro_sagrera_09.txt...

 32%|███▏      | 359/1137 [14:52<31:29,  2.43s/it]

Done.
Downloading 1pHm96vwgBqM7cpQ_yVGv6FeR1RCLUgne into /content/dataset/labels/train/57096_ramiro_sagrera_10.txt...

 32%|███▏      | 360/1137 [14:54<32:17,  2.49s/it]

Done.
Downloading 1zHov9t6KsBj6hay_emUYFRfX2AkoNJcw into /content/dataset/labels/train/57096_ramiro_sagrera_12.txt...

 32%|███▏      | 361/1137 [14:57<31:43,  2.45s/it]

Done.
Downloading 1bkwb7FEL1c05Ehos_NdY8g26ituFMgod into /content/dataset/labels/train/57096_ramiro_sagrera_16.txt...

 32%|███▏      | 362/1137 [14:59<32:26,  2.51s/it]

Done.
Downloading 1rnHm7oGo8JwTClBapQ1Zcv0qDwIL826Z into /content/dataset/labels/train/57096_ramiro_sagrera_18.txt...

 32%|███▏      | 363/1137 [15:02<32:46,  2.54s/it]

Done.
Downloading 17Zv0OwS-_mHi7MN8LpAEIWbs6uqnYxgr into /content/dataset/labels/train/57096_ramiro_sagrera_21.txt...

 32%|███▏      | 364/1137 [15:04<31:14,  2.42s/it]

Done.
Downloading 1YkCTSBaDTWjOsAHTWCirEAqmF1mF_STB into /content/dataset/labels/train/57096_ramiro_sagrera_22.txt...

 32%|███▏      | 365/1137 [15:06<30:08,  2.34s/it]

Done.
Downloading 1wXleHRO1W_m5VD26xGyrtVxblglvNAeN into /content/dataset/labels/train/57096_ramiro_sagrera_24.txt...

 32%|███▏      | 366/1137 [15:08<29:32,  2.30s/it]

Done.
Downloading 1iZptFZ1V-8jGS6uLhcy1yAq62_mDXWSD into /content/dataset/labels/train/57096_ramiro_sagrera_25.txt...

 32%|███▏      | 367/1137 [15:11<28:39,  2.23s/it]

Done.
Downloading 17-STaZPDP7UhCwdvsOAj7C_StrGXfR3J into /content/dataset/labels/train/57096_ramiro_sagrera_26.txt...

 32%|███▏      | 368/1137 [15:13<30:25,  2.37s/it]

Done.
Downloading 1i2bxXuyVd6U8__kzApVQ7It-QPvnoqGj into /content/dataset/labels/train/57096_ramiro_sagrera_27.txt...

 32%|███▏      | 369/1137 [15:16<30:01,  2.35s/it]

Done.
Downloading 1OzERszDq5dtzq5SDcXQHzmhDzluGsnX_ into /content/dataset/labels/train/57096_ramiro_sagrera_29.txt...

 33%|███▎      | 370/1137 [15:18<30:06,  2.36s/it]

Done.
Downloading 1T_4GjQ0CDa4rfXooMbF4C70U5tDakt3W into /content/dataset/labels/train/57096_ramiro_sagrera_30.txt...

 33%|███▎      | 371/1137 [15:20<30:32,  2.39s/it]

Done.
Downloading 1MzXVsaunvLVK5N_WwjhbldViAQRW8a14 into /content/dataset/labels/train/58491_fabio_giampaoli_01.txt...

 33%|███▎      | 372/1137 [15:23<29:59,  2.35s/it]

Done.
Downloading 1TwKo69QgxM_z9Ai0B1YgDPj4eSLVEzsS into /content/dataset/labels/train/58491_fabio_giampaoli_02.txt...

 33%|███▎      | 373/1137 [15:25<29:42,  2.33s/it]

Done.
Downloading 1vlj7JZrIQHBrz1WFziw9XlgdIFgry7Q0 into /content/dataset/labels/train/58491_fabio_giampaoli_04.txt...

 33%|███▎      | 374/1137 [15:27<29:24,  2.31s/it]

Done.
Downloading 1G4IP2fzzeNDvSm1YRwgbaMspR7a08un5 into /content/dataset/labels/train/58491_fabio_giampaoli_05.txt...

 33%|███▎      | 375/1137 [15:30<32:58,  2.60s/it]

Done.
Downloading 1E0jNehLORXkeV3QIdcm-K4VYipbRk2t0 into /content/dataset/labels/train/58491_fabio_giampaoli_08.txt...

 33%|███▎      | 376/1137 [15:33<32:52,  2.59s/it]

Done.
Downloading 1vyQMLj5Dv_4Qv6X0cW3qFIQ-F5Z5tp4w into /content/dataset/labels/train/58491_fabio_giampaoli_11.txt...

 33%|███▎      | 377/1137 [15:36<33:15,  2.63s/it]

Done.
Downloading 1etOyYP8dcRZ2dEqTXRZVNt0mcFfCRh7p into /content/dataset/labels/train/58491_fabio_giampaoli_12.txt...

 33%|███▎      | 378/1137 [15:38<31:49,  2.52s/it]

Done.
Downloading 13Lwoto6qPh5Mi5BQm_TvfUoeo9N-6c0_ into /content/dataset/labels/train/58491_fabio_giampaoli_13.txt...

 33%|███▎      | 379/1137 [15:40<30:51,  2.44s/it]

Done.
Downloading 11rqDO0sfJ_mEH4MSg7Lb64RrrgtEj07I into /content/dataset/labels/train/58491_fabio_giampaoli_14.txt...

 33%|███▎      | 380/1137 [15:43<30:01,  2.38s/it]

Done.
Downloading 1-cBCqx9EZCfTNhaaFes9s6zIXztjU24d into /content/dataset/labels/train/58491_fabio_giampaoli_17.txt...

 34%|███▎      | 381/1137 [15:45<29:24,  2.33s/it]

Done.
Downloading 1q-Ev4nZS-r6i-lYzwNite-Fut2ODzev_ into /content/dataset/labels/train/58491_fabio_giampaoli_18.txt...

 34%|███▎      | 382/1137 [15:47<28:27,  2.26s/it]

Done.
Downloading 1viL_Yj_b5x1eboSa56ST1QFL2XoA_Xu1 into /content/dataset/labels/train/58491_fabio_giampaoli_19.txt...

 34%|███▎      | 383/1137 [15:49<28:37,  2.28s/it]

Done.
Downloading 1_X1ib1ETjBEQIX6_c15Gnw1BbOFsc4yu into /content/dataset/labels/train/58491_fabio_giampaoli_20.txt...

 34%|███▍      | 384/1137 [15:51<27:27,  2.19s/it]

Done.
Downloading 1Lb47Y4L0zBkISXPtRWPRPXX439oDN64J into /content/dataset/labels/train/58491_fabio_giampaoli_21.txt...

 34%|███▍      | 385/1137 [15:53<28:03,  2.24s/it]

Done.
Downloading 1b7AjokAUoeHoxkxkmXJsaZOWdQfDiADe into /content/dataset/labels/train/58491_fabio_giampaoli_23.txt...

 34%|███▍      | 386/1137 [15:56<29:09,  2.33s/it]

Done.
Downloading 1BfqP0L2_g1arZEcqyaNyYrvRUA68xEaR into /content/dataset/labels/train/58491_fabio_giampaoli_24.txt...

 34%|███▍      | 387/1137 [15:58<28:50,  2.31s/it]

Done.
Downloading 1py-euMgmF-YGGtSzNcpHCqRCeBVymxCa into /content/dataset/labels/train/58491_fabio_giampaoli_26.txt...

 34%|███▍      | 388/1137 [16:00<28:11,  2.26s/it]

Done.
Downloading 1prtdCAYCLmMUOiO4aAo_19oVg2zKgLXC into /content/dataset/labels/train/58491_fabio_giampaoli_27.txt...

 34%|███▍      | 389/1137 [16:03<28:13,  2.26s/it]

Done.
Downloading 1PAUGy7GeRbQxFrzq05NvJW_XxQ3vgiSZ into /content/dataset/labels/train/58491_fabio_giampaoli_28.txt...

 34%|███▍      | 390/1137 [16:05<28:25,  2.28s/it]

Done.
Downloading 1Lp6ibYs7JGRn8ZR0HgoVryDNueReZyKw into /content/dataset/labels/train/58491_fabio_giampaoli_29.txt...

 34%|███▍      | 391/1137 [16:07<28:40,  2.31s/it]

Done.
Downloading 1NgVIQSKhhInzBvJPNjGc_XEknC5ern8A into /content/dataset/labels/train/58491_fabio_giampaoli_30.txt...

 34%|███▍      | 392/1137 [16:10<28:45,  2.32s/it]

Done.
Downloading 1lVoxs94ktfMBWjAt_7G4L_SH5ArZ-eHw into /content/dataset/labels/train/58513_isaias_garay_02.txt...

 35%|███▍      | 393/1137 [16:12<27:52,  2.25s/it]

Done.
Downloading 1t6LnrKFSqqr--xJ2Lxc4wa3dy9W7gPpY into /content/dataset/labels/train/58513_isaias_garay_03.txt...

 35%|███▍      | 394/1137 [16:14<27:33,  2.23s/it]

Done.
Downloading 14904yjEElQp-F2mO0wZzHPNU8tEAKykV into /content/dataset/labels/train/58513_isaias_garay_04.txt...

 35%|███▍      | 395/1137 [16:16<26:43,  2.16s/it]

Done.
Downloading 1iLUSGuwlIeRS7qRACCBSSshpCPhnSraB into /content/dataset/labels/train/58513_isaias_garay_05.txt...

 35%|███▍      | 396/1137 [16:19<28:55,  2.34s/it]

Done.
Downloading 1New3PeaThxDHyZP80wa6OmjHum3aq-Aq into /content/dataset/labels/train/58513_isaias_garay_06.txt...

 35%|███▍      | 397/1137 [16:21<28:07,  2.28s/it]

Done.
Downloading 1N-gYyKeECMJggG5wJDjMBs57h7OrS1UM into /content/dataset/labels/train/58513_isaias_garay_07.txt...

 35%|███▌      | 398/1137 [16:23<28:11,  2.29s/it]

Done.
Downloading 1QjqyTpOunfizFcxukLtY2RGgmi-bKXnC into /content/dataset/labels/train/58513_isaias_garay_10.txt...

 35%|███▌      | 399/1137 [16:25<27:58,  2.27s/it]

Done.
Downloading 11ZK37glTlq8T5KO-Mgxl9MrH4Kk8ZTrx into /content/dataset/labels/train/58513_isaias_garay_11.txt...

 35%|███▌      | 400/1137 [16:28<28:31,  2.32s/it]

Done.
Downloading 1gvuZmTl9XHidVdzWbPGlDXowe6uZ60iP into /content/dataset/labels/train/58513_isaias_garay_12.txt...

 35%|███▌      | 401/1137 [16:30<27:55,  2.28s/it]

Done.
Downloading 1WiqunLp7Ni6E4RvMx-PM7IGkDutvlE62 into /content/dataset/labels/train/58513_isaias_garay_15.txt...

 35%|███▌      | 402/1137 [16:33<28:44,  2.35s/it]

Done.
Downloading 1IuEJoeFxPRz2vUtTfuQ_mFPqI-Ureepf into /content/dataset/labels/train/58513_isaias_garay_17.txt...

 35%|███▌      | 403/1137 [16:35<29:29,  2.41s/it]

Done.
Downloading 1tpOTrRP0QKkyTKPuYfZgUGyxFPEC-tGy into /content/dataset/labels/train/58513_isaias_garay_18.txt...

 36%|███▌      | 404/1137 [16:37<28:33,  2.34s/it]

Done.
Downloading 1ZfMX_0zfP86xN5yHehvwDfRPooBZy8id into /content/dataset/labels/train/58513_isaias_garay_19.txt...

 36%|███▌      | 405/1137 [16:40<28:12,  2.31s/it]

Done.
Downloading 1HfxuFVrnaaUmGPihg3K_u4z1-5hGH7oq into /content/dataset/labels/train/58513_isaias_garay_20.txt...

 36%|███▌      | 406/1137 [16:42<28:02,  2.30s/it]

Done.
Downloading 10rrh0NAm45uaPhDAChhVxgKzw0JE7aoa into /content/dataset/labels/train/58513_isaias_garay_25.txt...

 36%|███▌      | 407/1137 [16:44<28:37,  2.35s/it]

Done.
Downloading 1ueHhKHJ9zD31EuPaAmN2ldotzf9r0xmQ into /content/dataset/labels/train/58513_isaias_garay_26.txt...

 36%|███▌      | 408/1137 [16:46<27:38,  2.27s/it]

Done.
Downloading 1PkaY-uHdlMYK11zHgXpGWpSQ8GHB8cGV into /content/dataset/labels/train/58513_isaias_garay_28.txt...

 36%|███▌      | 409/1137 [16:49<27:01,  2.23s/it]

Done.
Downloading 1HTdSbw_FqLByIsXGQqP_UNAXGGMg1lXv into /content/dataset/labels/train/58513_isaias_garay_29.txt...

 36%|███▌      | 410/1137 [16:51<27:07,  2.24s/it]

Done.
Downloading 1x0JMOd_OMrxIR-ZM2_Vjg7NwaQKYu1Eb into /content/dataset/labels/train/58513_isaias_garay_30.txt...

 36%|███▌      | 411/1137 [16:53<26:08,  2.16s/it]

Done.
Downloading 1ueym7q1HSuBKCHSDtCqlfMB4WeMk4Ho3 into /content/dataset/labels/train/58912_Timoteo_Garcia_1.txt...

 36%|███▌      | 412/1137 [16:55<26:40,  2.21s/it]

Done.
Downloading 1KePbvQO3G2uP37m7THD5J-nWqiP9LLjx into /content/dataset/labels/train/58912_Timoteo_Garcia_11.txt...

 36%|███▋      | 413/1137 [16:57<27:22,  2.27s/it]

Done.
Downloading 11kVpnZGH6H0S3ciwlRKSMnDykcZFy-ZO into /content/dataset/labels/train/58912_Timoteo_Garcia_12.txt...

 36%|███▋      | 414/1137 [17:00<26:31,  2.20s/it]

Done.
Downloading 15hsksSVqt3f0ASmpRYE0CXh33OpzCcR8 into /content/dataset/labels/train/58912_Timoteo_Garcia_15.txt...

 36%|███▋      | 415/1137 [17:02<27:31,  2.29s/it]

Done.
Downloading 1ZyH93x_6SYdvfQDlIKCva0ftlP-fW7l8 into /content/dataset/labels/train/58912_Timoteo_Garcia_19.txt...

 37%|███▋      | 416/1137 [17:04<27:21,  2.28s/it]

Done.
Downloading 1Ff2G3y70O6wu3DmUpLBoa0KaCeUOQCrP into /content/dataset/labels/train/58912_Timoteo_Garcia_24.txt...

 37%|███▋      | 417/1137 [17:06<26:42,  2.23s/it]

Done.
Downloading 19uTyylPrOS9Rl63p0A9pFhLMgzCBNJRD into /content/dataset/labels/train/58912_Timoteo_Garcia_25.txt...

 37%|███▋      | 418/1137 [17:09<28:09,  2.35s/it]

Done.
Downloading 1pVI4MSNYVpWpNIwOWQyEmqkFTf68gp75 into /content/dataset/labels/train/58912_Timoteo_Garcia_26.txt...

 37%|███▋      | 419/1137 [17:11<28:35,  2.39s/it]

Done.
Downloading 1ZbLLA9OIAjhmA8ZszGrR38Jj-_FW7NXz into /content/dataset/labels/train/58912_Timoteo_Garcia_27.txt...

 37%|███▋      | 420/1137 [17:14<28:19,  2.37s/it]

Done.
Downloading 1VKywBpDP-G-HjB7EePpdEGSjvYbD0UpI into /content/dataset/labels/train/58912_Timoteo_Garcia_29.txt...

 37%|███▋      | 421/1137 [17:16<27:15,  2.28s/it]

Done.
Downloading 1LRKSqdDksYIZGgmofr610n6W_RQoY-DN into /content/dataset/labels/train/58912_Timoteo_Garcia_31.txt...

 37%|███▋      | 422/1137 [17:18<26:45,  2.25s/it]

Done.
Downloading 1izRe1_ozWUIQTEmzM-JHYhwPbL0KW7XB into /content/dataset/labels/train/58912_Timoteo_Garcia_33.txt...

 37%|███▋      | 423/1137 [17:20<26:49,  2.25s/it]

Done.
Downloading 1auyn4A5zuTz8qXOVniP91SYiOcWh0Yb4 into /content/dataset/labels/train/58912_Timoteo_Garcia_34.txt...

 37%|███▋      | 424/1137 [17:23<28:41,  2.41s/it]

Done.
Downloading 1IIhleSB4voZWkvdDOzkUJ_sGbWiIeMfC into /content/dataset/labels/train/58912_Timoteo_Garcia_4.txt...

 37%|███▋      | 425/1137 [17:26<28:34,  2.41s/it]

Done.
Downloading 18DHkXE0NfTadt7Aszkns1TJZTQ7SXizt into /content/dataset/labels/train/58912_Timoteo_Garcia_5.txt...

 37%|███▋      | 426/1137 [17:28<27:54,  2.36s/it]

Done.
Downloading 16hpWjgib8IYqu8OoklbY_OQNFmTV0_OG into /content/dataset/labels/train/58912_Timoteo_Garcia_7.txt...

 38%|███▊      | 427/1137 [17:32<35:42,  3.02s/it]

Done.
Downloading 1y0xNpKg50DBFH1n5cTQZiV5ORDUMMsOS into /content/dataset/labels/train/58912_Timoteo_Garcia_8.txt...

 38%|███▊      | 428/1137 [17:35<33:08,  2.80s/it]

Done.
Downloading 1TjafT50Nidp9KPIkiR6j8ysWdNasNMQ0 into /content/dataset/labels/train/58912_Timoteo_Garcia_9.txt...

 38%|███▊      | 429/1137 [17:37<31:15,  2.65s/it]

Done.
Downloading 19w6Lyf4sfiUP8uG8FHr50h9QqPBboRSE into /content/dataset/labels/train/596d7f50336efa3134c558fb532fced7.txt...

 38%|███▊      | 430/1137 [17:39<29:26,  2.50s/it]

Done.
Downloading 1HcrRC-UhyN8eILJzRfpIx_g5HCXPExMu into /content/dataset/labels/train/5abbaad8b56fb4af772ee8e457175c09.txt...

 38%|███▊      | 431/1137 [17:41<28:31,  2.42s/it]

Done.
Downloading 1JaQKyAteOGkWMXX9OuIxBwvi_z1o9ths into /content/dataset/labels/train/5b5103028b09e5ba6f8c888eb6323afe.txt...

 38%|███▊      | 432/1137 [17:44<27:58,  2.38s/it]

Done.
Downloading 1TJ5typZ21DtosBNQZ2LdXy1IvWaWCMr8 into /content/dataset/labels/train/63cc48e729e1d5a1c058e4ee61def331.txt...

 38%|███▊      | 433/1137 [17:46<27:25,  2.34s/it]

Done.
Downloading 1ouMcpmoZdoSi7nfr5dWuLIruYzk2j8MZ into /content/dataset/labels/train/640c8248cdba8d4a8113aa6a005d8a98.txt...

 38%|███▊      | 434/1137 [17:48<27:11,  2.32s/it]

Done.
Downloading 1Q4Dht4oJTl2HpIOFWkqerL3txmHLkOOg into /content/dataset/labels/train/64191_Sofia_BrizuelaCipolletti_01.txt...

 38%|███▊      | 435/1137 [17:51<28:08,  2.41s/it]

Done.
Downloading 1F2AhV48hwSXl2ihZRTuWg6WZhRQWQIZ5 into /content/dataset/labels/train/64191_Sofia_BrizuelaCipolletti_02.txt...

 38%|███▊      | 436/1137 [17:53<27:53,  2.39s/it]

Done.
Downloading 1Wh5q8Rsk5PhJiDHcHjZb2XQkP8SNYCxq into /content/dataset/labels/train/64191_Sofia_BrizuelaCipolletti_03.txt...

 38%|███▊      | 437/1137 [17:55<27:32,  2.36s/it]

Done.
Downloading 1CYpSgo9JlHKLd4c4CYz_ma4P-CoGamw_ into /content/dataset/labels/train/64191_Sofia_BrizuelaCipolletti_07.txt...

 39%|███▊      | 438/1137 [17:58<27:09,  2.33s/it]

Done.
Downloading 1yrNC8OS_fHoCyYsekV-ijLD0edCuBdS5 into /content/dataset/labels/train/64191_Sofia_BrizuelaCipolletti_08.txt...

 39%|███▊      | 439/1137 [18:00<27:46,  2.39s/it]

Done.
Downloading 1vodABLZ79lDAyMR_z7JQ05bzFbVzZaE9 into /content/dataset/labels/train/64191_Sofia_BrizuelaCipolletti_09.txt...

 39%|███▊      | 440/1137 [18:03<28:18,  2.44s/it]

Done.
Downloading 1045HtfdYoQHz4TVxOWSsR8QUMJ2jgDJ7 into /content/dataset/labels/train/64191_Sofia_BrizuelaCipolletti_10.txt...

 39%|███▉      | 441/1137 [18:05<27:41,  2.39s/it]

Done.
Downloading 12AtL362hIrWjYAY5E9WqrTG8mqeH_m14 into /content/dataset/labels/train/64191_Sofia_BrizuelaCipolletti_11.txt...

 39%|███▉      | 442/1137 [18:07<27:12,  2.35s/it]

Done.
Downloading 1PZ_Gx32KPnbsM4Nm9fEXPxcWvQuSbN_h into /content/dataset/labels/train/64191_Sofia_BrizuelaCipolletti_12.txt...

 39%|███▉      | 443/1137 [18:10<28:04,  2.43s/it]

Done.
Downloading 1ZRWuCPKxLPEH3pWUBgmUfxbWYe03V1MO into /content/dataset/labels/train/64191_Sofia_BrizuelaCipolletti_13.txt...

 39%|███▉      | 444/1137 [18:12<27:44,  2.40s/it]

Done.
Downloading 1k2oeBO1NtpBCMj9zARhNRqkl2nlnQBSS into /content/dataset/labels/train/64191_Sofia_BrizuelaCipolletti_14.txt...

 39%|███▉      | 445/1137 [18:15<27:49,  2.41s/it]

Done.
Downloading 1qYGVQvmOtuUnnyQRqMTr9m9eKc5tQpIX into /content/dataset/labels/train/64191_Sofia_BrizuelaCipolletti_16.txt...

 39%|███▉      | 446/1137 [18:17<27:12,  2.36s/it]

Done.
Downloading 1iClEW-wJ34QPrFlQb5fH0FAGF52BA06s into /content/dataset/labels/train/64191_Sofia_BrizuelaCipolletti_17.txt...

 39%|███▉      | 447/1137 [18:19<26:32,  2.31s/it]

Done.
Downloading 1KN1zdHQX64Cqi9jYqjfGJbOqff2iSmgM into /content/dataset/labels/train/64191_Sofia_BrizuelaCipolletti_18.txt...

 39%|███▉      | 448/1137 [18:21<26:56,  2.35s/it]

Done.
Downloading 1c9Vcw9Vbpn8aaHKsr1E-3oEq9MonciD1 into /content/dataset/labels/train/64191_Sofia_BrizuelaCipolletti_20.txt...

 39%|███▉      | 449/1137 [18:24<26:17,  2.29s/it]

Done.
Downloading 1RtRXwxR82T18B8jRVnfpF8IPOyY4F20f into /content/dataset/labels/train/64191_Sofia_BrizuelaCipolletti_21.txt...

 40%|███▉      | 450/1137 [18:26<25:46,  2.25s/it]

Done.
Downloading 1KlH92Eum_8qRaDkSFo7Hsgrp0cC4wrwG into /content/dataset/labels/train/64191_Sofia_BrizuelaCipolletti_22.txt...

 40%|███▉      | 451/1137 [18:28<25:37,  2.24s/it]

Done.
Downloading 1yehv_uJks98pq_-aidghJ2Tbqjpr684C into /content/dataset/labels/train/64191_Sofia_BrizuelaCipolletti_26.txt...

 40%|███▉      | 452/1137 [18:30<25:17,  2.21s/it]

Done.
Downloading 18kNajguBdLFGzerp-A0fW4asP0vag-We into /content/dataset/labels/train/64191_Sofia_BrizuelaCipolletti_27.txt...

 40%|███▉      | 453/1137 [18:33<26:46,  2.35s/it]

Done.
Downloading 1p9HkTp3OMjNWjsy3Vk_riwJCT2dbRpAy into /content/dataset/labels/train/64191_Sofia_BrizuelaCipolletti_28.txt...

 40%|███▉      | 454/1137 [18:36<28:56,  2.54s/it]

Done.
Downloading 1xtxCsJDKBR4u1e6jJ9NeVFTe6eHIl3Ca into /content/dataset/labels/train/64191_Sofia_BrizuelaCipolletti_30.txt...

 40%|████      | 455/1137 [18:38<29:19,  2.58s/it]

Done.
Downloading 1ShE9Acrxvp9kBq_p61xj20CmhVMA0Lzb into /content/dataset/labels/train/66cf9d7f74a48caedcf01405de635c21.txt...

 40%|████      | 456/1137 [18:41<28:24,  2.50s/it]

Done.
Downloading 1ZFyJeU7iOoSXYdmGdLUAcXaii889sZ0V into /content/dataset/labels/train/704df12de98b3996baf45a004c5ae6b7.txt...

 40%|████      | 457/1137 [18:43<27:28,  2.42s/it]

Done.
Downloading 1yjkB737LhznRYa-rhoWd68NRS68Ik2n4 into /content/dataset/labels/train/71846_Brisa_Menescaldi_01.txt...

 40%|████      | 458/1137 [18:45<27:10,  2.40s/it]

Done.
Downloading 14M2mZu1kxotm9PagmeT6LaWH4Vx89qCX into /content/dataset/labels/train/71846_Brisa_Menescaldi_03.txt...

 40%|████      | 459/1137 [18:48<27:34,  2.44s/it]

Done.
Downloading 17NFnIoyNYMBcko4YeFVB5R41ncwc_nBp into /content/dataset/labels/train/71846_Brisa_Menescaldi_04.txt...

 40%|████      | 460/1137 [18:50<26:37,  2.36s/it]

Done.
Downloading 1HLUp6HBfer5JA7L8L11K3RbYnOwVqr4j into /content/dataset/labels/train/71846_Brisa_Menescaldi_05.txt...

 41%|████      | 461/1137 [18:52<26:18,  2.33s/it]

Done.
Downloading 1D8NZ1nRt9_RElj4ZJtSxzWIL_hy8uXPz into /content/dataset/labels/train/71846_Brisa_Menescaldi_06.txt...

 41%|████      | 462/1137 [18:55<25:58,  2.31s/it]

Done.
Downloading 1M7NDekbAcEdLQRzl8lm1opQvDEXardaR into /content/dataset/labels/train/71846_Brisa_Menescaldi_07.txt...

 41%|████      | 463/1137 [18:57<25:12,  2.24s/it]

Done.
Downloading 13yZzB_zPmHtwA5DuLtqr8fXbDLtLrZMy into /content/dataset/labels/train/71846_Brisa_Menescaldi_08.txt...

 41%|████      | 464/1137 [18:59<25:27,  2.27s/it]

Done.
Downloading 17qdy8-QrIpXeRUkx9t1U7XZVjwnJxCBK into /content/dataset/labels/train/71846_Brisa_Menescaldi_09.txt...

 41%|████      | 465/1137 [19:01<25:13,  2.25s/it]

Done.
Downloading 1B9AE8TW2-vLPe3yqv7t9W027eApNw28T into /content/dataset/labels/train/71846_Brisa_Menescaldi_10.txt...

 41%|████      | 466/1137 [19:04<26:18,  2.35s/it]

Done.
Downloading 1Kea_pNN2gMlwD-0FjJvKXcAI6hPK2l50 into /content/dataset/labels/train/71846_Brisa_Menescaldi_11.txt...

 41%|████      | 467/1137 [19:06<26:34,  2.38s/it]

Done.
Downloading 1on4B8nqVtNBGdTwd8Ua_eB1BRoAzfRaD into /content/dataset/labels/train/71846_Brisa_Menescaldi_14.txt...

 41%|████      | 468/1137 [19:09<26:26,  2.37s/it]

Done.
Downloading 1k8GeiCRolDvaxvkpD2orFhc2CpwXzD6u into /content/dataset/labels/train/71846_Brisa_Menescaldi_15.txt...

 41%|████      | 469/1137 [19:11<26:08,  2.35s/it]

Done.
Downloading 1gLRDhzUgSkpWtOHlIFmwSzGJiePtaoDb into /content/dataset/labels/train/71846_Brisa_Menescaldi_16.txt...

 41%|████▏     | 470/1137 [19:13<26:14,  2.36s/it]

Done.
Downloading 1tLrpovspFkCaAbDwUZ6Sls6zYvbT7c4G into /content/dataset/labels/train/71846_Brisa_Menescaldi_17.txt...

 41%|████▏     | 471/1137 [19:16<25:48,  2.33s/it]

Done.
Downloading 1knIQAAeFlQ4nnNLFeUiMOVBhCnfwDFdU into /content/dataset/labels/train/71846_Brisa_Menescaldi_18.txt...

 42%|████▏     | 472/1137 [19:18<25:19,  2.29s/it]

Done.
Downloading 1dOyMtQ_3p5qTzU5UwhS0Mhil58M62YVR into /content/dataset/labels/train/71846_Brisa_Menescaldi_19.txt...

 42%|████▏     | 473/1137 [19:20<25:07,  2.27s/it]

Done.
Downloading 1eB2yyjBHUGM1DU5A2EMNV9SLbQltmhev into /content/dataset/labels/train/71846_Brisa_Menescaldi_20.txt...

 42%|████▏     | 474/1137 [19:22<24:53,  2.25s/it]

Done.
Downloading 10lsvRSOFMh7lcU2dof8MYbTD5uEq1GMc into /content/dataset/labels/train/71846_Brisa_Menescaldi_22.txt...

 42%|████▏     | 475/1137 [19:25<25:10,  2.28s/it]

Done.
Downloading 1qhHSCABQDpu_U9YlSy07WKaNufW_NDp_ into /content/dataset/labels/train/71846_Brisa_Menescaldi_23.txt...

 42%|████▏     | 476/1137 [19:27<25:16,  2.29s/it]

Done.
Downloading 1vCwu5GbFq-v7BlCFtwrwSL7gz--hfuJN into /content/dataset/labels/train/71846_Brisa_Menescaldi_25.txt...

 42%|████▏     | 477/1137 [19:29<25:04,  2.28s/it]

Done.
Downloading 1m6Ca57oZyjP1nVQnfAZ-wx9Zk7t9toPP into /content/dataset/labels/train/71846_Brisa_Menescaldi_26.txt...

 42%|████▏     | 478/1137 [19:32<27:07,  2.47s/it]

Done.
Downloading 11VHHoCzFGCwip9AyaR2k6Gi-bHdrBTmT into /content/dataset/labels/train/71846_Brisa_Menescaldi_28.txt...

 42%|████▏     | 479/1137 [19:34<26:29,  2.42s/it]

Done.
Downloading 1QrXUkuxRcC6uhvawr1BJHkTI9A4f2uJJ into /content/dataset/labels/train/71846_Brisa_Menescaldi_29.txt...

 42%|████▏     | 480/1137 [19:37<26:34,  2.43s/it]

Done.
Downloading 1X_dDF3pX1GRoSAqcBYgardkM94_n5pg4 into /content/dataset/labels/train/71846_Brisa_Menescaldi_30.txt...

 42%|████▏     | 481/1137 [19:39<26:05,  2.39s/it]

Done.
Downloading 1brJIptLwwlyeo4qxlOUHk-mfDAXXvihm into /content/dataset/labels/train/72125_miguel_mussi_01.txt...

 42%|████▏     | 482/1137 [19:41<25:43,  2.36s/it]

Done.
Downloading 1gDivEOCEgjJ4P32HujFmg-hyDHZzI5C2 into /content/dataset/labels/train/72125_miguel_mussi_02.txt...

 42%|████▏     | 483/1137 [19:44<25:33,  2.34s/it]

Done.
Downloading 1V3sz5Vt4spm7VF0Nzr6vd5NUyMQfsQcH into /content/dataset/labels/train/72125_miguel_mussi_05.txt...

 43%|████▎     | 484/1137 [19:46<24:53,  2.29s/it]

Done.
Downloading 1iAp-LoLxdK9VPfwLPLpNqPXV7rriCx4B into /content/dataset/labels/train/72125_miguel_mussi_06.txt...

 43%|████▎     | 485/1137 [19:48<24:49,  2.28s/it]

Done.
Downloading 15i7e8DuQ40_uTw_6MPfz7sAIQ3nsKEEq into /content/dataset/labels/train/72125_miguel_mussi_07.txt...

 43%|████▎     | 486/1137 [19:51<26:43,  2.46s/it]

Done.
Downloading 110vwEYgP_dSrFvhAQVGAGmSOQDwH8VO2 into /content/dataset/labels/train/72125_miguel_mussi_08.txt...

 43%|████▎     | 487/1137 [19:53<25:59,  2.40s/it]

Done.
Downloading 1SNc-eoEkU1bHCekIBmAfMZNTpfcjycjx into /content/dataset/labels/train/72125_miguel_mussi_09.txt...

 43%|████▎     | 488/1137 [19:56<25:38,  2.37s/it]

Done.
Downloading 1xd7N0P6mZsYURnx8dk3Q-yXPl3tVdTLm into /content/dataset/labels/train/72125_miguel_mussi_12.txt...

 43%|████▎     | 489/1137 [19:58<25:23,  2.35s/it]

Done.
Downloading 1GAmjLTJLW49RJXXMc8L69iw9qI3NDsV7 into /content/dataset/labels/train/72125_miguel_mussi_14.txt...

 43%|████▎     | 490/1137 [20:00<25:23,  2.36s/it]

Done.
Downloading 1570x2qHHIs64PvPjc2MCzZXfdnUp_hqb into /content/dataset/labels/train/72125_miguel_mussi_15.txt...

 43%|████▎     | 491/1137 [20:02<25:05,  2.33s/it]

Done.
Downloading 1Iu_C-K71XJTDR40J483tZF71DJPrNN8c into /content/dataset/labels/train/72125_miguel_mussi_16.txt...

 43%|████▎     | 492/1137 [20:05<25:24,  2.36s/it]

Done.
Downloading 1IWx01ons7aTNXIPXGp1-rtMgWxObkA6G into /content/dataset/labels/train/72125_miguel_mussi_17.txt...

 43%|████▎     | 493/1137 [20:07<24:49,  2.31s/it]

Done.
Downloading 1nhs0Jh0YAU33HDSsqkvaZ_9vyFhgTYox into /content/dataset/labels/train/72125_miguel_mussi_18.txt...

 43%|████▎     | 494/1137 [20:09<24:54,  2.32s/it]

Done.
Downloading 1XIdSL95FVk3SKczaThD-X6SuixU-Iulo into /content/dataset/labels/train/72125_miguel_mussi_19.txt...

 44%|████▎     | 495/1137 [20:12<24:09,  2.26s/it]

Done.
Downloading 1lmLF47aeLZNv1jlf1GJzUaphseOMsdy2 into /content/dataset/labels/train/72125_miguel_mussi_20.txt...

 44%|████▎     | 496/1137 [20:14<24:58,  2.34s/it]

Done.
Downloading 11Mlozohxc0SLxS-cFI6QOu054hGC15OK into /content/dataset/labels/train/72125_miguel_mussi_21.txt...

 44%|████▎     | 497/1137 [20:16<24:34,  2.30s/it]

Done.
Downloading 1LLetHA6owhiJpahvIcwEiJXvf9t2TkGQ into /content/dataset/labels/train/72125_miguel_mussi_22.txt...

 44%|████▍     | 498/1137 [20:19<24:30,  2.30s/it]

Done.
Downloading 1VB6QMT4X-BcGt7LtzjgyQRsAZ-mYNyoc into /content/dataset/labels/train/72125_miguel_mussi_23.txt...

 44%|████▍     | 499/1137 [20:21<24:46,  2.33s/it]

Done.
Downloading 1mlVeOep1MWlE3R06j3S7FhDSMMu10arH into /content/dataset/labels/train/72125_miguel_mussi_24.txt...

 44%|████▍     | 500/1137 [20:24<25:26,  2.40s/it]

Done.
Downloading 1D62-wnt6LAoj2w2nL4Cq8A5GITYcZmQO into /content/dataset/labels/train/72125_miguel_mussi_26.txt...

 44%|████▍     | 501/1137 [20:26<24:37,  2.32s/it]

Done.
Downloading 1u1XXY6BYuZoxakOl21xUq-N9WlE9E4q1 into /content/dataset/labels/train/72125_miguel_mussi_27.txt...

 44%|████▍     | 502/1137 [20:28<23:59,  2.27s/it]

Done.
Downloading 1zl35QTWn9UUilvsysqHIZlNldfLkDa7D into /content/dataset/labels/train/72125_miguel_mussi_28.txt...

 44%|████▍     | 503/1137 [20:30<23:24,  2.22s/it]

Done.
Downloading 1odhgaBl573xCQbSG5nEAbKAkyQp3i1Eb into /content/dataset/labels/train/72125_miguel_mussi_29.txt...

 44%|████▍     | 504/1137 [20:32<23:32,  2.23s/it]

Done.
Downloading 1_xRmIgItxgwx4GpYe3edCY9UVIP9GdTD into /content/dataset/labels/train/72125_miguel_mussi_31.txt...

 44%|████▍     | 505/1137 [20:35<23:49,  2.26s/it]

Done.
Downloading 1UWAz2ffP1nUjyCxrWUEldjvrZkLmxREH into /content/dataset/labels/train/72125_miguel_mussi_32.txt...

 45%|████▍     | 506/1137 [20:37<23:57,  2.28s/it]

Done.
Downloading 1iCxCteP5riVExBEb_xsefW6N8F8dbg_9 into /content/dataset/labels/train/7575bfc3a933624222b269ebc54590df.txt...

 45%|████▍     | 507/1137 [20:39<23:36,  2.25s/it]

Done.
Downloading 14MpprdjZyaJPcyPxGSmhkGhVY_6lJZeM into /content/dataset/labels/train/76164b682bcc50ec13e45aba7d160981.txt...

 45%|████▍     | 508/1137 [20:41<23:44,  2.26s/it]

Done.
Downloading 1noJjiP6RCUrsFW3mNaP7Yg1FqFWYxMXY into /content/dataset/labels/train/7673022c8d5e7e1b0696d6c9d37b7d03.txt...

 45%|████▍     | 509/1137 [20:44<24:07,  2.31s/it]

Done.
Downloading 13YF74MjeCKMejqCOkOaj6HWpUBT97K0C into /content/dataset/labels/train/77ab1ff6c01ac3fed7cebfe404efce8c.txt...

 45%|████▍     | 510/1137 [20:46<24:00,  2.30s/it]

Done.
Downloading 1jIE6mDERayaxIFr1ClCzniIzifbqtEwe into /content/dataset/labels/train/78c09306722441bd0c22a5902cf11e15.txt...

 45%|████▍     | 511/1137 [20:48<23:24,  2.24s/it]

Done.
Downloading 1T4W8-nHJqoyomYMo2JelmcoP6Ncp6EJx into /content/dataset/labels/train/7a1990090ea52f2b726a8c6b02b5cff3.txt...

 45%|████▌     | 512/1137 [20:50<23:40,  2.27s/it]

Done.
Downloading 1LgIpRrCnq-BhcMfCxgArclE-LJrZESpZ into /content/dataset/labels/train/816d6a4c1d5427d3471d5b2b727ac967.txt...

 45%|████▌     | 513/1137 [20:53<23:35,  2.27s/it]

Done.
Downloading 10PuRSjecJDzKofY9IIhXnIPDDhzP7NM1 into /content/dataset/labels/train/844bff0deb2a58dd453977f55b4d9d14.txt...

 45%|████▌     | 514/1137 [20:55<23:30,  2.26s/it]

Done.
Downloading 1dxt7WzcpHl4X-CvDFWN4-vgm6uvjfelb into /content/dataset/labels/train/8bb3952a2888975922db1708d4e68b53.txt...

 45%|████▌     | 515/1137 [20:57<23:48,  2.30s/it]

Done.
Downloading 1wvnTHGP1u35I_aC0LPV5W_AOZDlmetiy into /content/dataset/labels/train/8fcca8d4125c078f68b3265015a1fb45.txt...

 45%|████▌     | 516/1137 [21:00<23:21,  2.26s/it]

Done.
Downloading 11J0bwel0ZHQEguC6N-FSxMz2R9zBImo6 into /content/dataset/labels/train/90b8cea8d4d18a4df4654b8c3e38bc5c.txt...

 45%|████▌     | 517/1137 [21:02<23:25,  2.27s/it]

Done.
Downloading 1PS5HBJ_teB7HHk0pP1s9C_vUJDi7EMeK into /content/dataset/labels/train/913797f0349e6ee4eee6de47aafb02ab.txt...

 46%|████▌     | 518/1137 [21:04<23:45,  2.30s/it]

Done.
Downloading 1D3Qcw2giF5Pm-5sdzkkp2yXqK8GPjgro into /content/dataset/labels/train/9154c720580a0731da24f5bccb89b757.txt...

 46%|████▌     | 519/1137 [21:07<24:32,  2.38s/it]

Done.
Downloading 1KORlPJZaovu69fjf3JoQQFQ4C07Nxx1C into /content/dataset/labels/train/93677facff05035c8575473c4a85d165.txt...

 46%|████▌     | 520/1137 [21:09<23:55,  2.33s/it]

Done.
Downloading 1MxwEnzB3gt5T9ttp4RZv-Pc1aMKfAc6o into /content/dataset/labels/train/94817a48957c610b5ec00b4d93bb7b1c.txt...

 46%|████▌     | 521/1137 [21:11<23:30,  2.29s/it]

Done.
Downloading 1q52DKIiiP-8AAhpzFbnHhJ7h4Y1MKown into /content/dataset/labels/train/957e583cbbbf600f9ac58dd946dff10b.txt...

 46%|████▌     | 522/1137 [21:14<23:39,  2.31s/it]

Done.
Downloading 1uKd9apHSukFI6ltrXgCejs73_GuBpTEz into /content/dataset/labels/train/9e0b77b7670e302b216a2be3f81749a9.txt...

 46%|████▌     | 523/1137 [21:16<23:16,  2.27s/it]

Done.
Downloading 1QNhyF3b2utilT2Efrhaob75fcdjEuhXt into /content/dataset/labels/train/A45161_Fabian_Aguirre_01.txt...

 46%|████▌     | 524/1137 [21:18<23:43,  2.32s/it]

Done.
Downloading 1b2SeRgp66jcluEIg0f1ajxYohiSOTKS3 into /content/dataset/labels/train/A45161_Fabian_Aguirre_02.txt...

 46%|████▌     | 525/1137 [21:20<22:48,  2.24s/it]

Done.
Downloading 18UmmOqSkiAEoW74w-RndXKw8GMtmwQvN into /content/dataset/labels/train/A45161_Fabian_Aguirre_03.txt...

 46%|████▋     | 526/1137 [21:22<22:54,  2.25s/it]

Done.
Downloading 18r4MWIB_MezlmdQ931nPaZBSpaX9RSrP into /content/dataset/labels/train/A45161_Fabian_Aguirre_05.txt...

 46%|████▋     | 527/1137 [21:25<22:53,  2.25s/it]

Done.
Downloading 1nKeSIfG9lCu6Vezr6-OEsn4kjzr_hXgP into /content/dataset/labels/train/A45161_Fabian_Aguirre_06.txt...

 46%|████▋     | 528/1137 [21:27<22:56,  2.26s/it]

Done.
Downloading 1XcHFjIWIJw8KmaQ7thjCYCFXCoW84BL6 into /content/dataset/labels/train/A45161_Fabian_Aguirre_07.txt...

 47%|████▋     | 529/1137 [21:29<22:29,  2.22s/it]

Done.
Downloading 1GvDj2ui_GEG2BnicIYFtoZ6QpPer9m36 into /content/dataset/labels/train/A45161_Fabian_Aguirre_08.txt...

 47%|████▋     | 530/1137 [21:31<22:30,  2.23s/it]

Done.
Downloading 1neJ2FvEgX6n1O-QKBzIuMpME3JU5hLa9 into /content/dataset/labels/train/A45161_Fabian_Aguirre_10.txt...

 47%|████▋     | 531/1137 [21:34<23:23,  2.32s/it]

Done.
Downloading 1IZr-LS1hQkOSR91oZcVgo3DX2qWSzN1T into /content/dataset/labels/train/A45161_Fabian_Aguirre_11.txt...

 47%|████▋     | 532/1137 [21:36<22:45,  2.26s/it]

Done.
Downloading 1WKKlj0GbfssAMV5BaMhkvkeGvlaqB6pT into /content/dataset/labels/train/A45161_Fabian_Aguirre_12.txt...

 47%|████▋     | 533/1137 [21:38<22:46,  2.26s/it]

Done.
Downloading 1SIKZy7_P1Ntwsj6zCKTLrqRMo2Q6-O_t into /content/dataset/labels/train/A45161_Fabian_Aguirre_15.txt...

 47%|████▋     | 534/1137 [21:40<22:29,  2.24s/it]

Done.
Downloading 1ODGGhPbI4v9hzxcQdMkCdZKmmv5Dw0lD into /content/dataset/labels/train/A45161_Fabian_Aguirre_16.txt...

 47%|████▋     | 535/1137 [21:43<22:21,  2.23s/it]

Done.
Downloading 1rvxxNjMeLeUhqy-9EBCouTz4OSXiIMAA into /content/dataset/labels/train/A45161_Fabian_Aguirre_20.txt...

 47%|████▋     | 536/1137 [21:45<22:23,  2.24s/it]

Done.
Downloading 15bclqZMsXsuOW5o1ETOP-7i9fX_2QEr0 into /content/dataset/labels/train/A45161_Fabian_Aguirre_21.txt...

 47%|████▋     | 537/1137 [21:47<21:39,  2.17s/it]

Done.
Downloading 1Wk01plqFiu8eJ1Lsl7rGgKgUsS2LfRfa into /content/dataset/labels/train/A45161_Fabian_Aguirre_22.txt...

 47%|████▋     | 538/1137 [21:49<21:46,  2.18s/it]

Done.
Downloading 1_kz3CB2YoqfVvCbpMp42e--9fSwRi7On into /content/dataset/labels/train/A45161_Fabian_Aguirre_23.txt...

 47%|████▋     | 539/1137 [21:51<21:44,  2.18s/it]

Done.
Downloading 1vLZ06hpq8ZJTjlkStuU9CxstA-b6mdAJ into /content/dataset/labels/train/A45161_Fabian_Aguirre_25.txt...

 47%|████▋     | 540/1137 [21:54<22:11,  2.23s/it]

Done.
Downloading 1ZMkmDqM8DoNun31JhUZ3Mp6Ws_kCbfzn into /content/dataset/labels/train/A45161_Fabian_Aguirre_26.txt...

 48%|████▊     | 541/1137 [21:56<21:45,  2.19s/it]

Done.
Downloading 1zNrw9xAPiNrolw-s5B0UcBUKGw-N9VEg into /content/dataset/labels/train/A45161_Fabian_Aguirre_27.txt...

 48%|████▊     | 542/1137 [21:58<21:43,  2.19s/it]

Done.
Downloading 1n47_-4W9bAjDexgAo0j0Ws4GuRITUD06 into /content/dataset/labels/train/A45161_Fabian_Aguirre_28.txt...

 48%|████▊     | 543/1137 [22:00<21:36,  2.18s/it]

Done.
Downloading 1sV249XIzSbYXxQ0xrL_qNPcXw-zQW3ss into /content/dataset/labels/train/A45161_Fabian_Aguirre_29.txt...

 48%|████▊     | 544/1137 [22:02<21:57,  2.22s/it]

Done.
Downloading 1HIk1kuZHO2MGpMdgGTomf7g1RSe2BDG- into /content/dataset/labels/train/A45161_Fabian_Aguirre_31.txt...

 48%|████▊     | 545/1137 [22:05<21:45,  2.20s/it]

Done.
Downloading 1tqOMvee7V5D9JIao4izfH2WVQon73znF into /content/dataset/labels/train/F37605_florencia_fernandez_01.txt...

 48%|████▊     | 546/1137 [22:07<22:11,  2.25s/it]

Done.
Downloading 10PAs1hxcnRu4xkJ_jPNx8bbIIqxSFP6O into /content/dataset/labels/train/F37605_florencia_fernandez_02.txt...

 48%|████▊     | 547/1137 [22:09<22:43,  2.31s/it]

Done.
Downloading 1Vqz-THbFZ2NkWXEKGtqBGqqz3Fhyxaks into /content/dataset/labels/train/F37605_florencia_fernandez_03.txt...

 48%|████▊     | 548/1137 [22:12<22:13,  2.26s/it]

Done.
Downloading 10c7yzjz-hBBYKVkIqYn6TAP2IMMx7vgG into /content/dataset/labels/train/F37605_florencia_fernandez_05.txt...

 48%|████▊     | 549/1137 [22:14<21:38,  2.21s/it]

Done.
Downloading 1BFjeDVbuBl-Aaco5j9aYm2AJSUYTXwQL into /content/dataset/labels/train/F37605_florencia_fernandez_06.txt...

 48%|████▊     | 550/1137 [22:16<22:17,  2.28s/it]

Done.
Downloading 1bBe-adv88f9dbcQmwBRrnyT93i9LBf4k into /content/dataset/labels/train/F37605_florencia_fernandez_12.txt...

 48%|████▊     | 551/1137 [22:18<22:12,  2.27s/it]

Done.
Downloading 1sPy7tJhh25YKxZg5FVx8juEuu-br4ZlB into /content/dataset/labels/train/F37605_florencia_fernandez_15.txt...

 49%|████▊     | 552/1137 [22:21<22:29,  2.31s/it]

Done.
Downloading 1d1jlmr1tMYBSWhBYr56EdMFepMePZ7Id into /content/dataset/labels/train/F37605_florencia_fernandez_16.txt...

 49%|████▊     | 553/1137 [22:23<22:03,  2.27s/it]

Done.
Downloading 1GwchlqRS2h8jra4NgIS3JR_E0tOZGzKe into /content/dataset/labels/train/F37605_florencia_fernandez_18.txt...

 49%|████▊     | 554/1137 [22:25<21:44,  2.24s/it]

Done.
Downloading 1NIvHU5O2Ux5Ahx7AyMdmP1E4GWSgPtCi into /content/dataset/labels/train/F37605_florencia_fernandez_20.txt...

 49%|████▉     | 555/1137 [22:27<21:23,  2.20s/it]

Done.
Downloading 1KrkjxS-thYzRTtm4sm38--XwOnZdD3Hk into /content/dataset/labels/train/F37605_florencia_fernandez_21.txt...

 49%|████▉     | 556/1137 [22:29<21:31,  2.22s/it]

Done.
Downloading 12zPmsO7yTflsmWqFeakZS0mxiAHFlMDm into /content/dataset/labels/train/F37605_florencia_fernandez_22.txt...

 49%|████▉     | 557/1137 [22:32<21:11,  2.19s/it]

Done.
Downloading 1awC43Vcb_Nio7QKJ7zfNDs4EnURsRrk7 into /content/dataset/labels/train/F37605_florencia_fernandez_23.txt...

 49%|████▉     | 558/1137 [22:34<21:18,  2.21s/it]

Done.
Downloading 1DtTVthDWrjRJS9SoL_Mem-FnmQAq52z7 into /content/dataset/labels/train/F37605_florencia_fernandez_24.txt...

 49%|████▉     | 559/1137 [22:36<20:53,  2.17s/it]

Done.
Downloading 15eII5xP1UJd6zl6SRXPkWE10xV2Ypvpt into /content/dataset/labels/train/F37605_florencia_fernandez_25.txt...

 49%|████▉     | 560/1137 [22:38<21:13,  2.21s/it]

Done.
Downloading 1ufW8eJovk4C7ZfUFc7-4NapLakt7X7yB into /content/dataset/labels/train/F37605_florencia_fernandez_26.txt...

 49%|████▉     | 561/1137 [22:41<23:42,  2.47s/it]

Done.
Downloading 1kzqDmpoIYHvp1ZWDsuqMKbDeDKHp0WC9 into /content/dataset/labels/train/F37605_florencia_fernandez_27.txt...

 49%|████▉     | 562/1137 [22:44<23:12,  2.42s/it]

Done.
Downloading 1UdLtsDRj4cRLmWf35KJuFv5ntnA0mkFa into /content/dataset/labels/train/F37605_florencia_fernandez_28.txt...

 50%|████▉     | 563/1137 [22:46<23:21,  2.44s/it]

Done.
Downloading 1hl7Dq0HhQp6p4F2pKLgXdGG0M3LGlgqU into /content/dataset/labels/train/F37605_florencia_fernandez_29.txt...

 50%|████▉     | 564/1137 [22:48<22:16,  2.33s/it]

Done.
Downloading 1tHyqvLU_ggNYgN4ApOtYPTPECbvsqz9w into /content/dataset/labels/train/F37605_florencia_fernandez_31.txt...

 50%|████▉     | 565/1137 [22:50<21:42,  2.28s/it]

Done.
Downloading 1DSKqrxOGFVh4IX2jktwTpFjrf-JDd227 into /content/dataset/labels/train/F37605_florencia_fernandez_32.txt...

 50%|████▉     | 566/1137 [22:53<21:40,  2.28s/it]

Done.
Downloading 1y3P1L2MkQUvxkXXtmM6HXG3hIirklUqJ into /content/dataset/labels/train/F37605_florencia_fernandez_33.txt...

 50%|████▉     | 567/1137 [22:55<22:04,  2.32s/it]

Done.
Downloading 1qP8iAAwxb4Kj0XgzbluiVw9bNP8GVnne into /content/dataset/labels/train/F37605_florencia_fernandez_34.txt...

 50%|████▉     | 568/1137 [22:57<21:57,  2.32s/it]

Done.
Downloading 1u13aIHPd4Hpmc7zxSKaMH-YUdRAk3Xmk into /content/dataset/labels/train/F37605_florencia_fernandez_36.txt...

 50%|█████     | 569/1137 [23:00<21:36,  2.28s/it]

Done.
Downloading 1CZ_9csVlWw9nGwP1I9qvrVSgknRJqG_7 into /content/dataset/labels/train/F37605_florencia_fernandez_38.txt...

 50%|█████     | 570/1137 [23:02<21:44,  2.30s/it]

Done.
Downloading 1SS8JYK6KhN2PsBGtxkIGJM7j3AKhddRL into /content/dataset/labels/train/F37605_florencia_fernandez_39.txt...

 50%|█████     | 571/1137 [23:04<21:13,  2.25s/it]

Done.
Downloading 1begMel7cKnEHOfzbXmGG0sAfykFLp8jf into /content/dataset/labels/train/F37605_florencia_fernandez_40.txt...

 50%|█████     | 572/1137 [23:06<20:54,  2.22s/it]

Done.
Downloading 1Bc7YVtytz57UibxoEWB_9VmkHrAonYT3 into /content/dataset/labels/train/F37605_florencia_fernandez_41.txt...

 50%|█████     | 573/1137 [23:08<20:54,  2.22s/it]

Done.
Downloading 1E4ECD-uDP6f8oIAhdbmDkojj4yiFPmvX into /content/dataset/labels/train/F37605_florencia_fernandez_42.txt...

 50%|█████     | 574/1137 [23:11<21:51,  2.33s/it]

Done.
Downloading 1mg4PbZ8y9ZOvML59oKPthsCMsLtXP8Q4 into /content/dataset/labels/train/F37605_florencia_fernandez_43.txt...

 51%|█████     | 575/1137 [23:13<21:29,  2.30s/it]

Done.
Downloading 1on6F6QfNjSEfi8ta8FFRocirjVh2SLm_ into /content/dataset/labels/train/F37605_florencia_fernandez_44.txt...

 51%|█████     | 576/1137 [23:15<21:26,  2.29s/it]

Done.
Downloading 1CiKgI9eFzaLMjJBCv3B-HjyPyZnRtODD into /content/dataset/labels/train/F37605_florencia_fernandez_49.txt...

 51%|█████     | 577/1137 [23:18<22:47,  2.44s/it]

Done.
Downloading 1_PJFmkgHiOSJx9LpxhMt4_RF52fCbuqa into /content/dataset/labels/train/F37605_florencia_fernandez_50.txt...

 51%|█████     | 578/1137 [23:21<22:54,  2.46s/it]

Done.
Downloading 1C9PrYzUn6kjuL17adt-IXu5jZ2jLWG7Y into /content/dataset/labels/train/F37605_florencia_fernandez_51.txt...

 51%|█████     | 579/1137 [23:23<21:49,  2.35s/it]

Done.
Downloading 18D0q4YpZ0Q27DKDjwkLa_cTQvqDvRsOp into /content/dataset/labels/train/F37605_florencia_fernandez_52.txt...

 51%|█████     | 580/1137 [23:25<21:42,  2.34s/it]

Done.
Downloading 17WRPiVCixAByR4BdnSCU0jw23AqSSTi- into /content/dataset/labels/train/F37605_florencia_fernandez_53.txt...

 51%|█████     | 581/1137 [23:28<22:06,  2.39s/it]

Done.
Downloading 1l_SeSGvRLWWbMzTlVmuTWyvC5unRYKal into /content/dataset/labels/train/F37605_florencia_fernandez_54.txt...

 51%|█████     | 582/1137 [23:30<21:32,  2.33s/it]

Done.
Downloading 152S1hVIU8clynXuNlpUMHTJ1mEoJaSFB into /content/dataset/labels/train/F37605_florencia_fernandez_55.txt...

 51%|█████▏    | 583/1137 [23:32<21:18,  2.31s/it]

Done.
Downloading 1emK3WonAIIPbdP24Cl7d2CWxm6OMvaz5 into /content/dataset/labels/train/L32425_eugenio_lopez_01.txt...

 51%|█████▏    | 584/1137 [23:34<20:54,  2.27s/it]

Done.
Downloading 17nLOzP1NhAEa5Q7pkrnfjnUr5eN4P9Kk into /content/dataset/labels/train/L32425_eugenio_lopez_02.txt...

 51%|█████▏    | 585/1137 [23:37<21:05,  2.29s/it]

Done.
Downloading 12LttZJIosAVuLS3dul93JpEsK7PlvIYK into /content/dataset/labels/train/L32425_eugenio_lopez_03.txt...

 52%|█████▏    | 586/1137 [23:39<20:40,  2.25s/it]

Done.
Downloading 1eYwBa9wfbxaeQHXBTK-k0fVVHVpu8oER into /content/dataset/labels/train/L32425_eugenio_lopez_04.txt...

 52%|█████▏    | 587/1137 [23:41<20:32,  2.24s/it]

Done.
Downloading 1xd8XM-w5eYKGCu0GbiLxm2A_N22l5weM into /content/dataset/labels/train/L32425_eugenio_lopez_05.txt...

 52%|█████▏    | 588/1137 [23:43<20:35,  2.25s/it]

Done.
Downloading 1wGvTFJi0DohDFx1YavUFnSlfomBhcFXs into /content/dataset/labels/train/L32425_eugenio_lopez_06.txt...

 52%|█████▏    | 589/1137 [23:46<20:35,  2.25s/it]

Done.
Downloading 1rTxuKK5KkEA1pF342N5O-WHCJqZ4MQCF into /content/dataset/labels/train/L32425_eugenio_lopez_07.txt...

 52%|█████▏    | 590/1137 [23:48<20:36,  2.26s/it]

Done.
Downloading 1GwXOnDj_ZKfi2LFcWg9xvvWs7fXmTLpP into /content/dataset/labels/train/L32425_eugenio_lopez_08.txt...

 52%|█████▏    | 591/1137 [23:50<21:24,  2.35s/it]

Done.
Downloading 1QbYP1HW4uJLwBtlVcSOHzmdNnezI5azr into /content/dataset/labels/train/L32425_eugenio_lopez_09.txt...

 52%|█████▏    | 592/1137 [23:53<21:45,  2.40s/it]

Done.
Downloading 12A7IfJL20wLT_yT3LHyG8E5XNA7MrHYR into /content/dataset/labels/train/L32425_eugenio_lopez_10.txt...

 52%|█████▏    | 593/1137 [23:55<21:17,  2.35s/it]

Done.
Downloading 1jU-fC3VPGRtauMWfnl7TW7tEjNbNJ4U5 into /content/dataset/labels/train/L32425_eugenio_lopez_11.txt...

 52%|█████▏    | 594/1137 [23:57<21:05,  2.33s/it]

Done.
Downloading 11JFRHvYnOa-dNFlBxv_c2BWIKbfE8aQa into /content/dataset/labels/train/L32425_eugenio_lopez_12.txt...

 52%|█████▏    | 595/1137 [24:00<20:39,  2.29s/it]

Done.
Downloading 1RldjJo9CHQvH3leKjRkKEQw2nBgz_732 into /content/dataset/labels/train/L32425_eugenio_lopez_13.txt...

 52%|█████▏    | 596/1137 [24:02<20:30,  2.27s/it]

Done.
Downloading 1Fa8lGtxRVJ62CesnNSS6d908E25JzsV_ into /content/dataset/labels/train/L32425_eugenio_lopez_14.txt...

 53%|█████▎    | 597/1137 [24:05<21:56,  2.44s/it]

Done.
Downloading 1p_R-4vbvQb_DeEebgaLN4k0a9J9oIoVs into /content/dataset/labels/train/L32425_eugenio_lopez_15.txt...

 53%|█████▎    | 598/1137 [24:07<21:17,  2.37s/it]

Done.
Downloading 1DBZtbWHP2McB2WtnMEzS8VRkv7js3a6X into /content/dataset/labels/train/L32425_eugenio_lopez_16.txt...

 53%|█████▎    | 599/1137 [24:09<20:34,  2.29s/it]

Done.
Downloading 1Omk44Ji6ARugveNu99s9SFrBHbZe83GG into /content/dataset/labels/train/L32425_eugenio_lopez_17.txt...

 53%|█████▎    | 600/1137 [24:11<20:02,  2.24s/it]

Done.
Downloading 1P3srGCS6F5CNZFBssVbnWe6vHWorG6Bf into /content/dataset/labels/train/L32425_eugenio_lopez_19.txt...

 53%|█████▎    | 601/1137 [24:14<20:54,  2.34s/it]

Done.
Downloading 1WZyuK8KlHR-tQj6va60472h5b050ls3j into /content/dataset/labels/train/L32425_eugenio_lopez_20.txt...

 53%|█████▎    | 602/1137 [24:16<21:40,  2.43s/it]

Done.
Downloading 16krmZjZ5kSvLa1L1Rh9VDiUJFsGg8G5H into /content/dataset/labels/train/L32425_eugenio_lopez_21.txt...

 53%|█████▎    | 603/1137 [24:19<21:22,  2.40s/it]

Done.
Downloading 1fgzIwMJtKvvpEFR9wLjF8OAG-p-jvU3v into /content/dataset/labels/train/L32425_eugenio_lopez_22.txt...

 53%|█████▎    | 604/1137 [24:21<20:58,  2.36s/it]

Done.
Downloading 1PPqSGCeblhaomsMUdJy1nyjKluvRb1lk into /content/dataset/labels/train/L32425_eugenio_lopez_23.txt...

 53%|█████▎    | 605/1137 [24:24<22:11,  2.50s/it]

Done.
Downloading 1j8tSGtateRwSByMJCHcekLXmz302wtSa into /content/dataset/labels/train/L32425_eugenio_lopez_25.txt...

 53%|█████▎    | 606/1137 [24:26<21:13,  2.40s/it]

Done.
Downloading 1KTBbG3w0IT4SQYeRsLGwcyvpvhj9R-Lq into /content/dataset/labels/train/L32425_eugenio_lopez_27.txt...

 53%|█████▎    | 607/1137 [24:28<20:57,  2.37s/it]

Done.
Downloading 1po1OIYeT8TZRR2wSE4r40NObi7qa0xax into /content/dataset/labels/train/L32425_eugenio_lopez_28.txt...

 53%|█████▎    | 608/1137 [24:31<21:11,  2.40s/it]

Done.
Downloading 1HDvGgTMSR2iXgD35YcoYFIThQQXrOPwb into /content/dataset/labels/train/L32425_eugenio_lopez_29.txt...

 54%|█████▎    | 609/1137 [24:33<20:57,  2.38s/it]

Done.
Downloading 1qSEBWXFlWc656XBf-MSVXhbD-YLyunq- into /content/dataset/labels/train/L32425_eugenio_lopez_30.txt...

 54%|█████▎    | 610/1137 [24:35<20:22,  2.32s/it]

Done.
Downloading 1o6zhAfDRImQzjzmW7gOtuVEgdzxub950 into /content/dataset/labels/train/L32531_santiago_loza_1.txt...

 54%|█████▎    | 611/1137 [24:37<19:59,  2.28s/it]

Done.
Downloading 1jFhoaNurx94GQ9smroyM-IQ-UP5G_AZO into /content/dataset/labels/train/L32531_santiago_loza_10.txt...

 54%|█████▍    | 612/1137 [24:40<19:53,  2.27s/it]

Done.
Downloading 1RyRPXvAlgLoChUN7sB3RzaXMNo0Dcnu7 into /content/dataset/labels/train/L32531_santiago_loza_12.txt...

 54%|█████▍    | 613/1137 [24:42<20:44,  2.38s/it]

Done.
Downloading 1J944l_qIhOFMdaSIdRrglIaS-BOvS6gP into /content/dataset/labels/train/L32531_santiago_loza_13.txt...

 54%|█████▍    | 614/1137 [24:44<20:13,  2.32s/it]

Done.
Downloading 1d2B7l85vjS-zw2CVIoSZ7FtHYyC6albw into /content/dataset/labels/train/L32531_santiago_loza_14.txt...

 54%|█████▍    | 615/1137 [24:47<20:00,  2.30s/it]

Done.
Downloading 1rxjAvx-vMABcjld2P9Ad6sNE3Hnk12Y4 into /content/dataset/labels/train/L32531_santiago_loza_17.txt...

 54%|█████▍    | 616/1137 [24:49<19:55,  2.29s/it]

Done.
Downloading 18vvEfQlZOLZ71zi_Ng_yQFD7p3PuFjCq into /content/dataset/labels/train/L32531_santiago_loza_18.txt...

 54%|█████▍    | 617/1137 [24:51<19:35,  2.26s/it]

Done.
Downloading 1so3h5JxU8o3L6Cej7PPQvSfywf5YhrtF into /content/dataset/labels/train/L32531_santiago_loza_19.txt...

 54%|█████▍    | 618/1137 [24:53<19:20,  2.24s/it]

Done.
Downloading 139m1pwiGhhIE9fM_NvhRYkYwkQ5LTxNw into /content/dataset/labels/train/L32531_santiago_loza_2.txt...

 54%|█████▍    | 619/1137 [24:56<19:55,  2.31s/it]

Done.
Downloading 1cakmppSLIVkds8YCxt56IQR5MNaIYykC into /content/dataset/labels/train/L32531_santiago_loza_22.txt...

 55%|█████▍    | 620/1137 [24:58<19:18,  2.24s/it]

Done.
Downloading 1vSFhXaYOPp5wi5pO3Ino52X-hTjPfWm6 into /content/dataset/labels/train/L32531_santiago_loza_23.txt...

 55%|█████▍    | 621/1137 [25:00<18:57,  2.20s/it]

Done.
Downloading 1_esHBr3ODb5PXLUvHgRWQZ4bfYF3pUNK into /content/dataset/labels/train/L32531_santiago_loza_24.txt...

 55%|█████▍    | 622/1137 [25:02<19:00,  2.21s/it]

Done.
Downloading 1i63TLvWXPvSwIVSCq4jOKTy8nbj2GVxG into /content/dataset/labels/train/L32531_santiago_loza_26.txt...

 55%|█████▍    | 623/1137 [25:04<18:45,  2.19s/it]

Done.
Downloading 139_MGIDZNx6z8wsLF0ErFNwplRnxqnuR into /content/dataset/labels/train/L32531_santiago_loza_28.txt...

 55%|█████▍    | 624/1137 [25:06<18:05,  2.12s/it]

Done.
Downloading 1KqJ3XR35cqln6-sc8f775iTX9ZXwTZGB into /content/dataset/labels/train/L32531_santiago_loza_30.txt...

 55%|█████▍    | 625/1137 [25:08<17:55,  2.10s/it]

Done.
Downloading 146MIRaxXewIEGO0EzrfDzTbxdZTs4yRi into /content/dataset/labels/train/L32531_santiago_loza_31.txt...

 55%|█████▌    | 626/1137 [25:11<18:06,  2.13s/it]

Done.
Downloading 1Jme7HW8hVs8RY6MezRQDu_Z-j28q15xY into /content/dataset/labels/train/L32531_santiago_loza_32.txt...

 55%|█████▌    | 627/1137 [25:13<18:47,  2.21s/it]

Done.
Downloading 17gpFLhW2uzzmIPzM5ZBonMf52BSgQ9di into /content/dataset/labels/train/L32531_santiago_loza_33.txt...

 55%|█████▌    | 628/1137 [25:15<19:14,  2.27s/it]

Done.
Downloading 1nxsbKWzl13KM_S7YgOaWn0mmT0sBda7M into /content/dataset/labels/train/L32531_santiago_loza_34.txt...

 55%|█████▌    | 629/1137 [25:18<18:56,  2.24s/it]

Done.
Downloading 1G0kgFcLJX_41lev6Q3QGuGDsolWqorYF into /content/dataset/labels/train/L32531_santiago_loza_35.txt...

 55%|█████▌    | 630/1137 [25:20<19:02,  2.25s/it]

Done.
Downloading 1tMthGaICOg6CHfcgGKYuy4lYgYhMfvwR into /content/dataset/labels/train/L32531_santiago_loza_36.txt...

 55%|█████▌    | 631/1137 [25:22<19:07,  2.27s/it]

Done.
Downloading 1pA3dI4PnXxTC84VPUBTvfu63zzeotIL5 into /content/dataset/labels/train/L32531_santiago_loza_37.txt...

 56%|█████▌    | 632/1137 [25:25<19:24,  2.31s/it]

Done.
Downloading 13gTUMdTISHbHyj71ooBC_MtJ0RhN7oBW into /content/dataset/labels/train/L32531_santiago_loza_38.txt...

 56%|█████▌    | 633/1137 [25:27<19:20,  2.30s/it]

Done.
Downloading 10dtvzrGfXD96UdE0hTCrUWd86yrZzdDq into /content/dataset/labels/train/L32531_santiago_loza_41.txt...

 56%|█████▌    | 634/1137 [25:29<19:26,  2.32s/it]

Done.
Downloading 1vpZJwOOne3QHfQZ2P6DMnnUAiVRzHiBf into /content/dataset/labels/train/L32531_santiago_loza_42.txt...

 56%|█████▌    | 635/1137 [25:32<19:37,  2.35s/it]

Done.
Downloading 1igj2vhsUcdziPpEHQpYgGcIi3TU7hxub into /content/dataset/labels/train/L32531_santiago_loza_44.txt...

 56%|█████▌    | 636/1137 [25:34<19:33,  2.34s/it]

Done.
Downloading 1wGLbECq12yuuwue2zNRBwR5eY1o907DW into /content/dataset/labels/train/L32531_santiago_loza_46.txt...

 56%|█████▌    | 637/1137 [25:37<20:18,  2.44s/it]

Done.
Downloading 1yoe6wpyvB5HMOdQQ5dDkdGBphfks4MTz into /content/dataset/labels/train/L32531_santiago_loza_7.txt...

 56%|█████▌    | 638/1137 [25:39<20:45,  2.50s/it]

Done.
Downloading 15MzduBhSwFIhl-2hKDDdjdTKAw_6AqBP into /content/dataset/labels/train/L32531_santiago_loza_8.txt...

 56%|█████▌    | 639/1137 [25:42<20:17,  2.44s/it]

Done.
Downloading 18pdvP1WlJ0bGSH_qc00H0yvkOKoEhYWI into /content/dataset/labels/train/L32531_santiago_loza_9.txt...

 56%|█████▋    | 640/1137 [25:44<20:23,  2.46s/it]

Done.
Downloading 15NvbCRSaRhVSYAaxeN25dSWdnA79Utwr into /content/dataset/labels/train/P51926_Leonel_Palermo_02.txt...

 56%|█████▋    | 641/1137 [25:46<19:57,  2.41s/it]

Done.
Downloading 12TT7O-TyfciTMq7HZAkL-WxGYJkF3vTh into /content/dataset/labels/train/P51926_Leonel_Palermo_04.txt...

 56%|█████▋    | 642/1137 [25:49<19:32,  2.37s/it]

Done.
Downloading 1C446Jr_fZnedtWBwudSBB82h28iO_CZl into /content/dataset/labels/train/P51926_Leonel_Palermo_05.txt...

 57%|█████▋    | 643/1137 [25:51<18:39,  2.27s/it]

Done.
Downloading 1kd89iQoaHi_wdmQgindfA41t5HTGdQol into /content/dataset/labels/train/P51926_Leonel_Palermo_06.txt...

 57%|█████▋    | 644/1137 [25:53<18:43,  2.28s/it]

Done.
Downloading 1vVmsVcUVQ1qJeqEfnGpXEfc7lMEdny-i into /content/dataset/labels/train/P51926_Leonel_Palermo_07.txt...

 57%|█████▋    | 645/1137 [25:56<19:23,  2.37s/it]

Done.
Downloading 1TLPhFy9GUk2YExlN-ScMiNdp0N5zB5Rd into /content/dataset/labels/train/P51926_Leonel_Palermo_08.txt...

 57%|█████▋    | 646/1137 [25:58<19:14,  2.35s/it]

Done.
Downloading 1rTgQJZjdSS_PiwivjC2LYoSGTfaTXFI5 into /content/dataset/labels/train/P51926_Leonel_Palermo_10.txt...

 57%|█████▋    | 647/1137 [26:00<18:57,  2.32s/it]

Done.
Downloading 1vTXSALa2uwdV4-Be5gPb8jCaVmVwNTpo into /content/dataset/labels/train/P51926_Leonel_Palermo_11.txt...

 57%|█████▋    | 648/1137 [26:03<19:43,  2.42s/it]

Done.
Downloading 1Wdkb69AaT9OguxdqjNrpxvuM0T2Uxk1O into /content/dataset/labels/train/P51926_Leonel_Palermo_13.txt...

 57%|█████▋    | 649/1137 [26:05<19:07,  2.35s/it]

Done.
Downloading 1hcY8-6d8BMvfIf8Fl0nECyj6mb2lSvpO into /content/dataset/labels/train/P51926_Leonel_Palermo_15.txt...

 57%|█████▋    | 650/1137 [26:08<19:39,  2.42s/it]

Done.
Downloading 1mQiWgyjSkMg4QpFsMlGgmc4Nkzi1aYYs into /content/dataset/labels/train/P51926_Leonel_Palermo_16.txt...

 57%|█████▋    | 651/1137 [26:10<18:56,  2.34s/it]

Done.
Downloading 1LG750aPK64Owr_ZEtXXHxd0bBWoNhYfC into /content/dataset/labels/train/P51926_Leonel_Palermo_18.txt...

 57%|█████▋    | 652/1137 [26:12<19:01,  2.35s/it]

Done.
Downloading 1o0PDnQCt5HMmaxIpgDbClONwu41daBUi into /content/dataset/labels/train/P51926_Leonel_Palermo_20.txt...

 57%|█████▋    | 653/1137 [26:15<19:30,  2.42s/it]

Done.
Downloading 1JWVT9KjMAZgTsZzxp62irgiS9ZGz9BCR into /content/dataset/labels/train/P51926_Leonel_Palermo_22.txt...

 58%|█████▊    | 654/1137 [26:17<18:38,  2.32s/it]

Done.
Downloading 1-eoUdqy841_STBYsGl0bCXAE64U-NeQv into /content/dataset/labels/train/P51926_Leonel_Palermo_23.txt...

 58%|█████▊    | 655/1137 [26:19<18:44,  2.33s/it]

Done.
Downloading 12n8O_qol1oxTmj7HsYyLkMfMbc6qed4P into /content/dataset/labels/train/P51926_Leonel_Palermo_24.txt...

 58%|█████▊    | 656/1137 [26:21<18:45,  2.34s/it]

Done.
Downloading 10pJB__9jxCIP60Vm6AnscuWkF27WudNk into /content/dataset/labels/train/P51926_Leonel_Palermo_25.txt...

 58%|█████▊    | 657/1137 [26:24<18:02,  2.26s/it]

Done.
Downloading 1-EzXK771oM5a9ONH6i8Vyakdu2piy8qZ into /content/dataset/labels/train/P51926_Leonel_Palermo_26.txt...

 58%|█████▊    | 658/1137 [26:26<18:16,  2.29s/it]

Done.
Downloading 1aWpO_WjvoS-cmjl62mItN5qLEtjLqqTr into /content/dataset/labels/train/P51926_Leonel_Palermo_27.txt...

 58%|█████▊    | 659/1137 [26:28<17:50,  2.24s/it]

Done.
Downloading 1mt9js5Oidr_3jmg43TRGb0UERaRd1jg6 into /content/dataset/labels/train/P51926_Leonel_Palermo_28.txt...

 58%|█████▊    | 660/1137 [26:31<18:48,  2.37s/it]

Done.
Downloading 19n60TtILQgg5DOcFzSuE0DAbqlIFKvjr into /content/dataset/labels/train/P51926_Leonel_Palermo_29.txt...

 58%|█████▊    | 661/1137 [26:33<18:53,  2.38s/it]

Done.
Downloading 1Pz0QRlQKgSRdK0BAYbVoxZeeedu5juUL into /content/dataset/labels/train/P51926_Leonel_Palermo_30.txt...

 58%|█████▊    | 662/1137 [26:35<18:38,  2.35s/it]

Done.
Downloading 1uP8t9MMgII4lAerxWR7ynmntS4U1-hTB into /content/dataset/labels/train/P51951_pablo_pistarelli_01.txt...

 58%|█████▊    | 663/1137 [26:38<18:26,  2.33s/it]

Done.
Downloading 1nIX_mbojHU4TdRmdKexUlvobwW2oVWuB into /content/dataset/labels/train/P51951_pablo_pistarelli_02.txt...

 58%|█████▊    | 664/1137 [26:40<18:37,  2.36s/it]

Done.
Downloading 1JusXGUcNu3BS9aFC3PMjTsyQluHbxAkG into /content/dataset/labels/train/P51951_pablo_pistarelli_03.txt...

 58%|█████▊    | 665/1137 [26:43<18:53,  2.40s/it]

Done.
Downloading 13W8sd8PHqOMC41zma1ouDkTX-Yxygv5k into /content/dataset/labels/train/P51951_pablo_pistarelli_04.txt...

 59%|█████▊    | 666/1137 [26:45<18:18,  2.33s/it]

Done.
Downloading 1OZsKl3NLNYAsaN0fUZxqZBgJdeUENAcq into /content/dataset/labels/train/P51951_pablo_pistarelli_07.txt...

 59%|█████▊    | 667/1137 [26:47<18:08,  2.32s/it]

Done.
Downloading 1yssxTOkXaxXrWggiBqYHioNTQD7ghycf into /content/dataset/labels/train/P51951_pablo_pistarelli_08.txt...

 59%|█████▉    | 668/1137 [26:49<18:06,  2.32s/it]

Done.
Downloading 1U8BMT8PAcgr-j6sd0Rd7IK3fWbFdFX4m into /content/dataset/labels/train/P_51977_martin_perrone_01.txt...

 59%|█████▉    | 669/1137 [26:51<17:31,  2.25s/it]

Done.
Downloading 188cJnyd9SzAJIluahNBkcmREc4EkLhTQ into /content/dataset/labels/train/P_51977_martin_perrone_02.txt...

 59%|█████▉    | 670/1137 [26:54<17:28,  2.24s/it]

Done.
Downloading 1RnHJ1UzA-XkmQty4sP5wc_A7-sWSnOS3 into /content/dataset/labels/train/P_51977_martin_perrone_03.txt...

 59%|█████▉    | 671/1137 [26:56<17:48,  2.29s/it]

Done.
Downloading 1fl2dePncjGCW9SAAWheE4hJeptywMKWh into /content/dataset/labels/train/P_51977_martin_perrone_04.txt...

 59%|█████▉    | 672/1137 [26:58<17:18,  2.23s/it]

Done.
Downloading 1UHMoygLL10em6VMTZTt7WVsvLF4GJ0my into /content/dataset/labels/train/P_51977_martin_perrone_05.txt...

 59%|█████▉    | 673/1137 [27:03<24:24,  3.16s/it]

Done.
Downloading 1-vAuczrqfarjbvQjAjJBFG2YF-b9Gohl into /content/dataset/labels/train/P_51977_martin_perrone_07.txt...

 59%|█████▉    | 674/1137 [27:06<22:21,  2.90s/it]

Done.
Downloading 1isCW5-6KgVrGCvU_sM15OXafi6vjcQxO into /content/dataset/labels/train/P_51977_martin_perrone_08.txt...

 59%|█████▉    | 675/1137 [27:08<21:08,  2.75s/it]

Done.
Downloading 169CjOp6LtwyTxsbpPlNbUj7FyU8vgBra into /content/dataset/labels/train/P_51977_martin_perrone_09.txt...

 59%|█████▉    | 676/1137 [27:10<19:43,  2.57s/it]

Done.
Downloading 1Bydzd5WjPaJi-NSEj6Ksazc0MkVTlzb1 into /content/dataset/labels/train/P_51977_martin_perrone_12.txt...

 60%|█████▉    | 677/1137 [27:13<18:51,  2.46s/it]

Done.
Downloading 1NH83svsrZ4eGG-d0RZXDO-vtAQp--Bbv into /content/dataset/labels/train/P_51977_martin_perrone_13.txt...

 60%|█████▉    | 678/1137 [27:15<18:15,  2.39s/it]

Done.
Downloading 1F7QyPTwu3qLsHdqUsOAc48MeLL-ySQby into /content/dataset/labels/train/P_51977_martin_perrone_17.txt...

 60%|█████▉    | 679/1137 [27:17<18:13,  2.39s/it]

Done.
Downloading 1xcCe1AfOcXRpM7tVCeZrIZKpzaIcRymS into /content/dataset/labels/train/P_51977_martin_perrone_18.txt...

 60%|█████▉    | 680/1137 [27:19<17:24,  2.29s/it]

Done.
Downloading 1XtjcOz8qkvZXaH8hmvcdRS9MuhcAvLAP into /content/dataset/labels/train/P_51977_martin_perrone_19.txt...

 60%|█████▉    | 681/1137 [27:21<17:14,  2.27s/it]

Done.
Downloading 1WDFd282vxmf6Qd4Yknm07JC90mEmEKe2 into /content/dataset/labels/train/P_51977_martin_perrone_20.txt...

 60%|█████▉    | 682/1137 [27:23<16:48,  2.22s/it]

Done.
Downloading 13LIB29gkgb15_QSfzSw1_iETMg9dRDmE into /content/dataset/labels/train/P_51977_martin_perrone_21.txt...

 60%|██████    | 683/1137 [27:26<16:57,  2.24s/it]

Done.
Downloading 12mUHLM9KwfVnVZ-prRGdArxEeiAeGZlP into /content/dataset/labels/train/P_51977_martin_perrone_23.txt...

 60%|██████    | 684/1137 [27:28<16:54,  2.24s/it]

Done.
Downloading 19Id00tn5i4I1SJnqHflk8nzv-tYEwDS6 into /content/dataset/labels/train/P_51977_martin_perrone_24.txt...

 60%|██████    | 685/1137 [27:30<17:16,  2.29s/it]

Done.
Downloading 1Szmhe-Qiy7p36rUkHPVfRDM1UoLMgEEX into /content/dataset/labels/train/P_51977_martin_perrone_27.txt...

 60%|██████    | 686/1137 [27:34<19:35,  2.61s/it]

Done.
Downloading 1u1KsoC9Jzwy6aFASgg00gxG14Ry20CtE into /content/dataset/labels/train/P_51977_martin_perrone_28.txt...

 60%|██████    | 687/1137 [27:36<18:49,  2.51s/it]

Done.
Downloading 1haWhrgcYOtHzMTBClP0yMiyr7kstF2tO into /content/dataset/labels/train/P_51977_martin_perrone_29.txt...

 61%|██████    | 688/1137 [27:38<18:23,  2.46s/it]

Done.
Downloading 1jRuc6ous1rGvhFMevREPDuVdVHKZ4Xn5 into /content/dataset/labels/train/P_51977_martin_perrone_31.txt...

 61%|██████    | 689/1137 [27:42<19:55,  2.67s/it]

Done.
Downloading 1T63Zmvx-fcRqN5E4EHo47Nb4j_eq3X_F into /content/dataset/labels/train/P_51977_martin_perrone_32.txt...

 61%|██████    | 690/1137 [27:44<18:31,  2.49s/it]

Done.
Downloading 1-0MRxqkzM3-zqrkOlGX9IxYcKbiHVLgl into /content/dataset/labels/train/P_51977_martin_perrone_34.txt...

 61%|██████    | 691/1137 [27:46<17:45,  2.39s/it]

Done.
Downloading 1885t1JGK8BYW2nbyhGhDB6bJYHKK7du2 into /content/dataset/labels/train/P_51977_martin_perrone_35.txt...

 61%|██████    | 692/1137 [27:48<17:00,  2.29s/it]

Done.
Downloading 1JmDEnNtBqRlHPMaMjgZ5yG3j5oSd7hgy into /content/dataset/labels/train/P_51977_martin_perrone_38.txt...

 61%|██████    | 693/1137 [27:50<16:47,  2.27s/it]

Done.
Downloading 1eHxv9cKgmAVb6QUGvaXYUJzP69djGt9q into /content/dataset/labels/train/P_51977_martin_perrone_40.txt...

 61%|██████    | 694/1137 [27:52<16:48,  2.28s/it]

Done.
Downloading 1ukcGdauvuKyL14DhSIl7o3-RCu7qnNRM into /content/dataset/labels/train/R-45489_sofiarondini_01.txt...

 61%|██████    | 695/1137 [27:55<16:51,  2.29s/it]

Done.
Downloading 1rj27SaQP4mUPIxsXTpff-zqyaVwB7LUP into /content/dataset/labels/train/R-45489_sofiarondini_02.txt...

 61%|██████    | 696/1137 [27:57<16:52,  2.30s/it]

Done.
Downloading 1PcJMSJBsVkMJb5_avkprpPSBBkqkQcCd into /content/dataset/labels/train/R-45489_sofiarondini_03.txt...

 61%|██████▏   | 697/1137 [27:59<17:04,  2.33s/it]

Done.
Downloading 1ZaGwbjyWhBCFIT5wcrVi1xOXBuSdTB6K into /content/dataset/labels/train/R-45489_sofiarondini_04.txt...

 61%|██████▏   | 698/1137 [28:02<16:59,  2.32s/it]

Done.
Downloading 1k2WyK_hWIz5wlFE8rhlS-6HQ9gTNii-l into /content/dataset/labels/train/R-45489_sofiarondini_05.txt...

 61%|██████▏   | 699/1137 [28:04<17:28,  2.39s/it]

Done.
Downloading 1NxWLBdIPEmUHJd0LdCuQQC58e6Y6PGrq into /content/dataset/labels/train/R-45489_sofiarondini_06.txt...

 62%|██████▏   | 700/1137 [28:06<17:00,  2.34s/it]

Done.
Downloading 1bzcAUKod4DiUAtz9XO8ftxt77TZr5J4G into /content/dataset/labels/train/R-45489_sofiarondini_07.txt...

 62%|██████▏   | 701/1137 [28:09<16:59,  2.34s/it]

Done.
Downloading 1YAHjzpMJ4b22gIAp2sCPa2HWgaM7HPXz into /content/dataset/labels/train/R-45489_sofiarondini_08.txt...

 62%|██████▏   | 702/1137 [28:11<16:26,  2.27s/it]

Done.
Downloading 1xyto2YUynbx6hZLCLGhYfGx5fPKCIXhX into /content/dataset/labels/train/R-45489_sofiarondini_09.txt...

 62%|██████▏   | 703/1137 [28:13<16:10,  2.24s/it]

Done.
Downloading 1i1J6XN43xxI-C2WpKOHDu_a6W95RURt6 into /content/dataset/labels/train/R-45489_sofiarondini_10.txt...

 62%|██████▏   | 704/1137 [28:15<16:24,  2.27s/it]

Done.
Downloading 1S04Q8oqz49OLiEZrzDlWIlbsGZ8yKUPy into /content/dataset/labels/train/R-45489_sofiarondini_11.txt...

 62%|██████▏   | 705/1137 [28:18<16:38,  2.31s/it]

Done.
Downloading 1_VKTyR4DHuLM-Csa0IUDoNmUggQWCgMc into /content/dataset/labels/train/R-45489_sofiarondini_12.txt...

 62%|██████▏   | 706/1137 [28:20<16:26,  2.29s/it]

Done.
Downloading 1PJR1cz3NScNevsWClsbacPgp9vnNe_N0 into /content/dataset/labels/train/R-45489_sofiarondini_13.txt...

 62%|██████▏   | 707/1137 [28:22<16:36,  2.32s/it]

Done.
Downloading 14KuTEpUSm0aS2CpQxruRCScied4ov1UQ into /content/dataset/labels/train/R-45489_sofiarondini_14.txt...

 62%|██████▏   | 708/1137 [28:25<16:30,  2.31s/it]

Done.
Downloading 1uwQzTq2dpModO-2rVMPsHoTADDHLVIhw into /content/dataset/labels/train/R-45489_sofiarondini_15.txt...

 62%|██████▏   | 709/1137 [28:27<16:34,  2.32s/it]

Done.
Downloading 1U_mCzpQ7HuabosEzR3q7ZrwNhcKtBdxt into /content/dataset/labels/train/R-45489_sofiarondini_16.txt...

 62%|██████▏   | 710/1137 [28:30<16:45,  2.36s/it]

Done.
Downloading 1AFEBGF23UdTdWHEVQO7Q0fCXGrmNx_yy into /content/dataset/labels/train/R-45489_sofiarondini_17.txt...

 63%|██████▎   | 711/1137 [28:32<16:20,  2.30s/it]

Done.
Downloading 1xF_GAaDT6_AaPMVSTnq8LdXQoTen7pd6 into /content/dataset/labels/train/R-45489_sofiarondini_18.txt...

 63%|██████▎   | 712/1137 [28:34<15:58,  2.25s/it]

Done.
Downloading 1cV6PQ8EDlHvM-PBSqeOeb8JjgH1t_poE into /content/dataset/labels/train/R-45489_sofiarondini_20.txt...

 63%|██████▎   | 713/1137 [28:36<16:18,  2.31s/it]

Done.
Downloading 1qA4_fWu1ogYyz-W0uAH7zW2iionbCPUf into /content/dataset/labels/train/R-45489_sofiarondini_21.txt...

 63%|██████▎   | 714/1137 [28:39<16:10,  2.29s/it]

Done.
Downloading 18rzIEdmLUzVOhQID4nIfMF8t4JBOly22 into /content/dataset/labels/train/R-45489_sofiarondini_22.txt...

 63%|██████▎   | 715/1137 [28:41<16:10,  2.30s/it]

Done.
Downloading 1r1jDev421Tjtk5lwoFwqtlKaUNc8bw3D into /content/dataset/labels/train/R-45489_sofiarondini_23.txt...

 63%|██████▎   | 716/1137 [28:43<15:35,  2.22s/it]

Done.
Downloading 128joSNRaDArIIZ6L42pp13hhfeUXJ58P into /content/dataset/labels/train/R-45489_sofiarondini_24.txt...

 63%|██████▎   | 717/1137 [28:45<15:36,  2.23s/it]

Done.
Downloading 1-jZ2e0YdFSY5JsbV0FBPcViJ9zJoepD0 into /content/dataset/labels/train/R-45489_sofiarondini_25.txt...

 63%|██████▎   | 718/1137 [28:47<15:30,  2.22s/it]

Done.
Downloading 1ETwp1ltQSMkYSC5SGP3UmePjWzQVMOoy into /content/dataset/labels/train/R-45489_sofiarondini_27.txt...

 63%|██████▎   | 719/1137 [28:50<15:32,  2.23s/it]

Done.
Downloading 1uVKLmeQP1RJTM3rMb2kHGc3ScqbvcjNA into /content/dataset/labels/train/R-45489_sofiarondini_28.txt...

 63%|██████▎   | 720/1137 [28:52<15:16,  2.20s/it]

Done.
Downloading 1oL74pYoO5NwPrsFgxVTMlSPZhYZsYrGu into /content/dataset/labels/train/R-45489_sofiarondini_30.txt...

 63%|██████▎   | 721/1137 [28:54<15:05,  2.18s/it]

Done.
Downloading 1NvIWoHWhL1k2BWyeKnxhoQ64qr3q5GO3 into /content/dataset/labels/train/R-45489_sofiarondini_31.txt...

 64%|██████▎   | 722/1137 [28:56<15:26,  2.23s/it]

Done.
Downloading 1rDjgnD8pHTKd6HqlQEiO7bWyE9YTNrmE into /content/dataset/labels/train/R-45489_sofiarondini_33.txt...

 64%|██████▎   | 723/1137 [28:59<15:39,  2.27s/it]

Done.
Downloading 1VCmgWNyuvPHflYzr8T8Z2RwrRBn5Wsy6 into /content/dataset/labels/train/R-45489_sofiarondini_34.txt...

 64%|██████▎   | 724/1137 [29:01<15:29,  2.25s/it]

Done.
Downloading 1m50_o4wdUxrm2zkLvOnw4A_Ovg-Tr6n6 into /content/dataset/labels/train/R-45829_Abril_Rodriguez_01.txt...

 64%|██████▍   | 725/1137 [29:03<16:22,  2.39s/it]

Done.
Downloading 1lmeOEtpHAPNvY89UEpmDy8oAj2zRJw9Z into /content/dataset/labels/train/R-45829_Abril_Rodriguez_02.txt...

 64%|██████▍   | 726/1137 [29:06<16:33,  2.42s/it]

Done.
Downloading 1EwvmjdDyitSqdgH-L9mjcNtOZo6rm-Bb into /content/dataset/labels/train/R-45829_Abril_Rodriguez_04.txt...

 64%|██████▍   | 727/1137 [29:09<17:02,  2.49s/it]

Done.
Downloading 1VyqLEk2Vp0LVQaibb6BvSNClfvjzzaYe into /content/dataset/labels/train/R-45829_Abril_Rodriguez_05.txt...

 64%|██████▍   | 728/1137 [29:11<16:34,  2.43s/it]

Done.
Downloading 1fybG7Vz1n2QPa_EHJjMt-GCT097_Q_pd into /content/dataset/labels/train/R-45829_Abril_Rodriguez_06.txt...

 64%|██████▍   | 729/1137 [29:14<16:51,  2.48s/it]

Done.
Downloading 1fO7Vx5pvn2hPdC0PK8JWrCzCgbNs3sSR into /content/dataset/labels/train/R-45829_Abril_Rodriguez_07.txt...

 64%|██████▍   | 730/1137 [29:16<17:04,  2.52s/it]

Done.
Downloading 1UsQgvYXPYvmUzZpb7WnVYiNBmuplNYzH into /content/dataset/labels/train/R-45829_Abril_Rodriguez_08.txt...

 64%|██████▍   | 731/1137 [29:18<16:26,  2.43s/it]

Done.
Downloading 13jaWL1DWuX4CSzLhwQ8LP1yZwFdWt2wq into /content/dataset/labels/train/R-45829_Abril_Rodriguez_12.txt...

 64%|██████▍   | 732/1137 [29:21<16:08,  2.39s/it]

Done.
Downloading 1QC4cfVLcM5Yqb1v9nTSPYVeN2Eghur1G into /content/dataset/labels/train/R-45829_Abril_Rodriguez_13.txt...

 64%|██████▍   | 733/1137 [29:23<16:01,  2.38s/it]

Done.
Downloading 1RLeM9demSmSl0hiuVVXT03RRoNrUs5wa into /content/dataset/labels/train/R-45829_Abril_Rodriguez_14.txt...

 65%|██████▍   | 734/1137 [29:26<16:22,  2.44s/it]

Done.
Downloading 1oYXAB_4QWRr_eV1DjJbx_C-Cn2Rwwyn_ into /content/dataset/labels/train/R-45829_Abril_Rodriguez_16.txt...

 65%|██████▍   | 735/1137 [29:28<16:51,  2.52s/it]

Done.
Downloading 1YY659XRAg5VUdnWoMIWsuCIupi5QpXj4 into /content/dataset/labels/train/R-45829_Abril_Rodriguez_17.txt...

 65%|██████▍   | 736/1137 [29:30<16:02,  2.40s/it]

Done.
Downloading 1IE-GQT7okh7Kq0PCOm5fQ7E14bqUwreB into /content/dataset/labels/train/R-45829_Abril_Rodriguez_18.txt...

 65%|██████▍   | 737/1137 [29:33<15:44,  2.36s/it]

Done.
Downloading 1Lza1dfSnu2fCSRfduCjqdI2mnZ6dCMjc into /content/dataset/labels/train/R-45829_Abril_Rodriguez_19.txt...

 65%|██████▍   | 738/1137 [29:35<15:11,  2.28s/it]

Done.
Downloading 11_YHHiclHwH1PZ38P1uo2gZJHL9kdOZN into /content/dataset/labels/train/R-45829_Abril_Rodriguez_21.txt...

 65%|██████▍   | 739/1137 [29:37<15:16,  2.30s/it]

Done.
Downloading 1-yxyI71eHP4KFWyNRUodSKLdc_Lt_OZD into /content/dataset/labels/train/R-45829_Abril_Rodriguez_22.txt...

 65%|██████▌   | 740/1137 [29:39<15:14,  2.30s/it]

Done.
Downloading 1SyajQC8Z_PQ4nfR-UuEMXUvCKsIlqHc8 into /content/dataset/labels/train/R-45829_Abril_Rodriguez_23.txt...

 65%|██████▌   | 741/1137 [29:52<35:50,  5.43s/it]

Done.
Downloading 1gci5WvQ8UVXdo5s6KZj4bfO2ULsm2Cta into /content/dataset/labels/train/R-45829_Abril_Rodriguez_25.txt...

 65%|██████▌   | 742/1137 [29:55<29:50,  4.53s/it]

Done.
Downloading 1eWZjKt8VEZc10K5OSxYe8lN0RuiJJY0U into /content/dataset/labels/train/R-45829_Abril_Rodriguez_26.txt...

 65%|██████▌   | 743/1137 [29:57<25:59,  3.96s/it]

Done.
Downloading 1Eusbqw9LRRoxD8_Ujb7ZwW2towx1PE29 into /content/dataset/labels/train/R-45829_Abril_Rodriguez_27.txt...

 65%|██████▌   | 744/1137 [29:59<22:25,  3.42s/it]

Done.
Downloading 16Wwt5DtGJI0WMgezAgNeWZlNUAO8p58q into /content/dataset/labels/train/R-45829_Abril_Rodriguez_28.txt...

 66%|██████▌   | 745/1137 [30:02<20:21,  3.12s/it]

Done.
Downloading 1Eq05NL6Zj8d3SYzyteV0c58xbDJae8iV into /content/dataset/labels/train/R-45829_Abril_Rodriguez_29.txt...

 66%|██████▌   | 746/1137 [30:04<19:07,  2.94s/it]

Done.
Downloading 1BIKwhWfama8WprbM5OdeoBsbBidM6y29 into /content/dataset/labels/train/R-45829_Abril_Rodriguez_30.txt...

 66%|██████▌   | 747/1137 [30:07<18:06,  2.79s/it]

Done.
Downloading 1xIDgtwq0eqlxYvbjBNiCSc5bS7cJ_A5M into /content/dataset/labels/train/S57061_Leandro_Salvana_02.txt...

 66%|██████▌   | 748/1137 [30:09<17:11,  2.65s/it]

Done.
Downloading 1FOtvkVQIdjt0zA1E-iHWbu_lhuB4A_ly into /content/dataset/labels/train/S57061_Leandro_Salvana_03.txt...

 66%|██████▌   | 749/1137 [30:11<16:32,  2.56s/it]

Done.
Downloading 15kAct0vaSwS45JZGxJpk-v9cuN1hnPzA into /content/dataset/labels/train/S57061_Leandro_Salvana_07.txt...

 66%|██████▌   | 750/1137 [30:14<15:42,  2.44s/it]

Done.
Downloading 12U45GCKpUgGJSruwROpmNvkrdpZ-KWYC into /content/dataset/labels/train/S57061_Leandro_Salvana_08.txt...

 66%|██████▌   | 751/1137 [30:16<14:54,  2.32s/it]

Done.
Downloading 1yAD5DYOyBn9gte-Cm4VR3wCCftaRzlL3 into /content/dataset/labels/train/S57061_Leandro_Salvana_09.txt...

 66%|██████▌   | 752/1137 [30:18<15:16,  2.38s/it]

Done.
Downloading 1veC7drVoXgTho9ut3quDZ0F_LSMMQS3r into /content/dataset/labels/train/S57061_Leandro_Salvana_10.txt...

 66%|██████▌   | 753/1137 [30:20<14:51,  2.32s/it]

Done.
Downloading 1eLZdb3avmC_1doK-BR7PlQc5m6qXW6yG into /content/dataset/labels/train/S57061_Leandro_Salvana_12.txt...

 66%|██████▋   | 754/1137 [30:23<15:09,  2.38s/it]

Done.
Downloading 1RYfXkDa7m47mbdWQbhOzFjUVROAQER5W into /content/dataset/labels/train/S57061_Leandro_Salvana_15.txt...

 66%|██████▋   | 755/1137 [30:25<15:02,  2.36s/it]

Done.
Downloading 1-inTbZiC5c_K7ytkK36p4sXMTS3VK4fg into /content/dataset/labels/train/S57061_Leandro_Salvana_18.txt...

 66%|██████▋   | 756/1137 [30:27<14:53,  2.35s/it]

Done.
Downloading 1324Id2voUhh9a_Zzxpw5FpBF8gSD0KNY into /content/dataset/labels/train/S57061_Leandro_Salvana_19.txt...

 67%|██████▋   | 757/1137 [30:30<14:37,  2.31s/it]

Done.
Downloading 1cFrYIxZ74EoEupuVsbiDy1SJbCiKxbxn into /content/dataset/labels/train/S57061_Leandro_Salvana_20.txt...

 67%|██████▋   | 758/1137 [30:32<14:05,  2.23s/it]

Done.
Downloading 1e1nZ0barXCd3aoqhqvc29sn2KdCTk22A into /content/dataset/labels/train/S57061_Leandro_Salvana_21.txt...

 67%|██████▋   | 759/1137 [30:34<13:36,  2.16s/it]

Done.
Downloading 1lB8e0x4IoT85vRyeUM6YZRmSs0VNcqGA into /content/dataset/labels/train/S57061_Leandro_Salvana_22.txt...

 67%|██████▋   | 760/1137 [30:36<13:29,  2.15s/it]

Done.
Downloading 1KLoLyy0tohtRiz0LBSHAjPE-anDXa-VM into /content/dataset/labels/train/S57061_Leandro_Salvana_24.txt...

 67%|██████▋   | 761/1137 [30:38<13:51,  2.21s/it]

Done.
Downloading 1XoxxJb-nt7SMVqiNV3D232yX7tcmhuwc into /content/dataset/labels/train/S57061_Leandro_Salvana_25.txt...

 67%|██████▋   | 762/1137 [30:41<14:04,  2.25s/it]

Done.
Downloading 1PdQ0043pBW4nFNPzCIo8uMVvMPzmYM1a into /content/dataset/labels/train/S57061_Leandro_Salvana_27.txt...

 67%|██████▋   | 763/1137 [30:43<14:04,  2.26s/it]

Done.
Downloading 1bbOyu209GBAf9t5lP-MXw-G6v2hF6E6t into /content/dataset/labels/train/S57061_Leandro_Salvana_28.txt...

 67%|██████▋   | 764/1137 [30:45<14:01,  2.26s/it]

Done.
Downloading 1fwdZIahC7Ni7h9bbO93z3ZP1JeETpW-e into /content/dataset/labels/train/S57061_Leandro_Salvana_29.txt...

 67%|██████▋   | 765/1137 [30:47<13:50,  2.23s/it]

Done.
Downloading 1B1xhEBAfupBjMkAfHvhF3fzXHf4IJpZ- into /content/dataset/labels/train/S57061_Leandro_Salvana_30.txt...

 67%|██████▋   | 766/1137 [30:49<13:36,  2.20s/it]

Done.
Downloading 1RSSyphk_01FjH6SSeoNTcSFdZOkdWyWO into /content/dataset/labels/train/S57061_Leandro_Salvana_32.txt...

 67%|██████▋   | 767/1137 [30:52<13:51,  2.25s/it]

Done.
Downloading 1H9vH8UO1QdWDxNqIq2WPYcGH6psG_GlU into /content/dataset/labels/train/S57061_Leandro_Salvana_35.txt...

 68%|██████▊   | 768/1137 [30:54<13:40,  2.22s/it]

Done.
Downloading 1clNEaCrx03afriMlIW4k474XX4NZE_G3 into /content/dataset/labels/train/S57061_Leandro_Salvana_36.txt...

 68%|██████▊   | 769/1137 [30:56<13:51,  2.26s/it]

Done.
Downloading 1pJPPtgUg_fb3IbNM1IjUG1OxV57AgoR- into /content/dataset/labels/train/S57061_Leandro_Salvana_37.txt...

 68%|██████▊   | 770/1137 [30:58<13:41,  2.24s/it]

Done.
Downloading 1weC-Nx_O_dtI6SGvfkUBWV4aMQ7B8jZb into /content/dataset/labels/train/S57061_Leandro_Salvana_39.txt...

 68%|██████▊   | 771/1137 [31:01<13:45,  2.25s/it]

Done.
Downloading 1eitNyJwgOBHYoOsrn3000M-NMsRKlTGu into /content/dataset/labels/train/S57061_Leandro_Salvana_40.txt...

 68%|██████▊   | 772/1137 [31:03<13:56,  2.29s/it]

Done.
Downloading 1Lxc9BcwEqwpMkRKFZPPLdkAmH7v-6Upc into /content/dataset/labels/train/S57061_Leandro_Salvana_41.txt...

 68%|██████▊   | 773/1137 [31:05<13:30,  2.23s/it]

Done.
Downloading 19ehGsZGjuUmlobyYCwtYdjPXkeJrALT5 into /content/dataset/labels/train/S57061_Leandro_Salvana_43.txt...

 68%|██████▊   | 774/1137 [31:07<13:01,  2.15s/it]

Done.
Downloading 1nHYorERfrB5kN0PcW3jiES5FTkaiYrFf into /content/dataset/labels/train/S57061_Leandro_Salvana_45.txt...

 68%|██████▊   | 775/1137 [31:09<12:39,  2.10s/it]

Done.
Downloading 1-EWXTUUbFfJfsjj2Kh_LLo9oRZb9NuBt into /content/dataset/labels/train/S57061_Leandro_Salvana_46.txt...

 68%|██████▊   | 776/1137 [31:11<12:40,  2.11s/it]

Done.
Downloading 1jzUnb52VyKKy7mXzK1X-3W2DW7t3h4my into /content/dataset/labels/train/S57061_Leandro_Salvana_48.txt...

 68%|██████▊   | 777/1137 [31:13<12:41,  2.11s/it]

Done.
Downloading 1vtrPOQrZVP9XLr39dHHMb7Lq5bLilXtS into /content/dataset/labels/train/S57061_Leandro_Salvana_49.txt...

 68%|██████▊   | 778/1137 [31:16<12:51,  2.15s/it]

Done.
Downloading 1gJOrQDWdSS1f8kKfky2Pjv_VtuB95Uvd into /content/dataset/labels/train/a056cbf2cd5f3d7d2bd2592760a3d306.txt...

 69%|██████▊   | 779/1137 [31:18<13:26,  2.25s/it]

Done.
Downloading 1zLR0Y2WsZHju9oSD1oaKIH-fTYCVjWQc into /content/dataset/labels/train/a44809f6033eb9722034c145854daf1d.txt...

 69%|██████▊   | 780/1137 [31:20<13:17,  2.23s/it]

Done.
Downloading 16QyaKqKtVnlDhKRmx1dKJJKiGVFa-9qH into /content/dataset/labels/train/a4f49e1d32a1c6b6455065b3efcf7854.txt...

 69%|██████▊   | 781/1137 [31:22<12:58,  2.19s/it]

Done.
Downloading 15yQppo35Uw6BOM-m1fg3Nbp_u6S-Cd7Q into /content/dataset/labels/train/a8b7acca23be1e0eb16cd0d9f9b1858d.txt...

 69%|██████▉   | 782/1137 [31:25<13:11,  2.23s/it]

Done.
Downloading 1q9TGQH_K4vq7-PrKhYEPVeE-ozTaCf1m into /content/dataset/labels/train/ab57adc6fb75c7cefd3b386b1b703166.txt...

 69%|██████▉   | 783/1137 [31:27<13:15,  2.25s/it]

Done.
Downloading 1w1rFvUIR8UaQyfcUR07QLNeV-o5aiB_y into /content/dataset/labels/train/ad13c986542e87aefe1e5bc621bf6c3c.txt...

 69%|██████▉   | 784/1137 [31:30<13:45,  2.34s/it]

Done.
Downloading 1-GZbdsxN0D9XEtgphfTp27D9agvBUUkP into /content/dataset/labels/train/b51e3ed9fcb3bf55ff9f61a2e0ca74b1.txt...

 69%|██████▉   | 785/1137 [31:32<13:21,  2.28s/it]

Done.
Downloading 1U1ht5F1fdwPLQUoFNUZOf7imjCplkgH5 into /content/dataset/labels/train/bc4e58ee986480992cdd8acb87b3a21c.txt...

 69%|██████▉   | 786/1137 [31:34<13:37,  2.33s/it]

Done.
Downloading 170Imn-9NjwZghFhDfer72AvyH6BYOovO into /content/dataset/labels/train/bc651e3a871021e2225e2de9702fbb72.txt...

 69%|██████▉   | 787/1137 [31:36<13:33,  2.32s/it]

Done.
Downloading 17pGmazzhFemYrPakTpq4gksv9KBBeNES into /content/dataset/labels/train/bc6f1ca08f613418bb0cd9393bf85c1b.txt...

 69%|██████▉   | 788/1137 [31:39<13:37,  2.34s/it]

Done.
Downloading 1GLB3of4ky7-Dyfs35xB_tu0kNGDYtaYp into /content/dataset/labels/train/bcf1e5a2aac0c41cf27c527613a6f704.txt...

 69%|██████▉   | 789/1137 [31:41<13:15,  2.29s/it]

Done.
Downloading 1QFFavxn5V4ZkRro1aLkaWanyPh5gvDxF into /content/dataset/labels/train/bf02d4825b88da21f08c445ef0586e54.txt...

 69%|██████▉   | 790/1137 [31:43<13:19,  2.30s/it]

Done.
Downloading 17yihlU07FZ0CnR3cECWKwtlTZjOMBflu into /content/dataset/labels/train/bf903deb0c6215564562b47fd9e4b900.txt...

 70%|██████▉   | 791/1137 [31:46<13:08,  2.28s/it]

Done.
Downloading 1ZLHompKXMpGiFUeUuVJ03HMFpeB-KB-N into /content/dataset/labels/train/c3f000d375ce09292e2e0ccce265f022.txt...

 70%|██████▉   | 792/1137 [31:48<13:14,  2.30s/it]

Done.
Downloading 1OXDdDUsUDT92PAsTqsYtXogpXG7L3jKU into /content/dataset/labels/train/c46c27c46e3bf9450677896f9637ea84.txt...

 70%|██████▉   | 793/1137 [31:50<13:18,  2.32s/it]

Done.
Downloading 1xeIx-g-1LqYO9pbIb0ze7tZeErYhABDP into /content/dataset/labels/train/c894f91d437bff464f102fb0595ba4b2.txt...

 70%|██████▉   | 794/1137 [31:53<13:12,  2.31s/it]

Done.
Downloading 1AkcQ-_ubGo32yENQEJEgJCgsH18RhFCX into /content/dataset/labels/train/d49bd455ddb890f798645384267155b3.txt...

 70%|██████▉   | 795/1137 [31:55<12:52,  2.26s/it]

Done.
Downloading 1EZfXq60RuqJgLg4Tj6xTpOE8kwAWY2ZD into /content/dataset/labels/train/d6fa0e68cba0b4afd68d99c1c8d9c59f.txt...

 70%|███████   | 796/1137 [31:57<12:53,  2.27s/it]

Done.
Downloading 1Uv0xE46DsN-Nc5QSwhGkWNbF_Ar-SWWx into /content/dataset/labels/train/d7464e01d5f7b767d61005eb2c6a0d38.txt...

 70%|███████   | 797/1137 [31:59<13:08,  2.32s/it]

Done.
Downloading 1YFm4qfAX3NP-_Kpt_FfX8AnbUBC3az3m into /content/dataset/labels/train/d7e76ba83d90085d1020c5f240e365de.txt...

 70%|███████   | 798/1137 [32:02<13:26,  2.38s/it]

Done.
Downloading 1d121vcADJ0jlXoS3z8f_t1VEs7fK3fkK into /content/dataset/labels/train/dc31cabeda18c33d9a852b9144f7367c.txt...

 70%|███████   | 799/1137 [32:04<13:37,  2.42s/it]

Done.
Downloading 16LAyJEtdINOo44KvcfZ3ROvHuoakJ5pI into /content/dataset/labels/train/dcf7b17157fb40fa0f6f0e7ed5e6c820.txt...

 70%|███████   | 800/1137 [32:07<13:17,  2.37s/it]

Done.
Downloading 1teOIsMz437ndOplmBi5UnBFtokbuTloc into /content/dataset/labels/train/e2ad06c8f78c8045468cf6009289f2df.txt...

 70%|███████   | 801/1137 [32:09<12:59,  2.32s/it]

Done.
Downloading 1tvvIV93Z2ah1nXdV7-HwEi-er_p173t0 into /content/dataset/labels/train/e343f320e0f5075c681e604949045b72.txt...

 71%|███████   | 802/1137 [32:11<12:57,  2.32s/it]

Done.
Downloading 1PkZdAofF4PusmpyCOXA2t_6xNLWvas2e into /content/dataset/labels/train/e3647d80d5bfa76aaa0a240fee750f3a.txt...

 71%|███████   | 803/1137 [32:14<13:12,  2.37s/it]

Done.
Downloading 1PSKOb6BWEOdyD8Fa_1v2JZxcQ4cnZdu0 into /content/dataset/labels/train/e746942882758cb958e53400f52eb9c8.txt...

 71%|███████   | 804/1137 [32:16<12:47,  2.30s/it]

Done.
Downloading 1pvrNoJWf-ZKA34tuXUisgdMiRozUvZof into /content/dataset/labels/train/ed8095f182ef6afe56aa3e178d2fd17f.txt...

 71%|███████   | 805/1137 [32:18<12:41,  2.29s/it]

Done.
Downloading 1b54_m22tJxZAH4advgy5FS-Z_r_254Ph into /content/dataset/labels/train/f0d56e748d2ce35cefdc7070da1d56eb.txt...

 71%|███████   | 806/1137 [32:20<12:40,  2.30s/it]

Done.
Downloading 1D5DTuWbOwZjaWv_OswaSMNdmj5O-JGHg into /content/dataset/labels/train/f24e9b3e1d2527a28a7c438656036f86.txt...

 71%|███████   | 807/1137 [32:23<12:43,  2.31s/it]

Done.
Downloading 1MppvRakVMKZCbc6Kt7891cOhlb9oefyq into /content/dataset/labels/train/f37478_santiago_ferrero_02.txt...

 71%|███████   | 808/1137 [32:25<12:24,  2.26s/it]

Done.
Downloading 1tDEYCNNv7anNUG8K3UFTMppBYnzS9Y62 into /content/dataset/labels/train/f37478_santiago_ferrero_03.txt...

 71%|███████   | 809/1137 [32:28<12:54,  2.36s/it]

Done.
Downloading 11VqXIrhJDiTDiy2h9XRFGEaHlbyYadx5 into /content/dataset/labels/train/f37478_santiago_ferrero_04.txt...

 71%|███████   | 810/1137 [32:30<12:52,  2.36s/it]

Done.
Downloading 1k_O7dLzkECYx37uRKmDMRV4JMk6Ddwrd into /content/dataset/labels/train/f37478_santiago_ferrero_06.txt...

 71%|███████▏  | 811/1137 [32:32<12:44,  2.34s/it]

Done.
Downloading 1kjokGRICqniKzskW4ZK3Wqxk8cKanJH- into /content/dataset/labels/train/f37478_santiago_ferrero_08.txt...

 71%|███████▏  | 812/1137 [32:35<12:50,  2.37s/it]

Done.
Downloading 1RUixH1fnSCZzP4HtwvbuH2n_s5PPDPym into /content/dataset/labels/train/f37478_santiago_ferrero_10.txt...

 72%|███████▏  | 813/1137 [32:37<12:27,  2.31s/it]

Done.
Downloading 1x1O4_u2yCV0hi86jykzlGQuyT312v_Cv into /content/dataset/labels/train/f37478_santiago_ferrero_11.txt...

 72%|███████▏  | 814/1137 [32:39<12:26,  2.31s/it]

Done.
Downloading 1LMFLs8E1s_YtHlhN85k4J_cNdFsblzJm into /content/dataset/labels/train/f37478_santiago_ferrero_12.txt...

 72%|███████▏  | 815/1137 [32:41<12:06,  2.26s/it]

Done.
Downloading 1bP9OC_mCMc6ylJ8qOnX4hYWBHNVOx-2N into /content/dataset/labels/train/f37478_santiago_ferrero_13.txt...

 72%|███████▏  | 816/1137 [32:43<11:43,  2.19s/it]

Done.
Downloading 1BCgFq4wzvLjLnpq83jgFkDaD6sx6Ambt into /content/dataset/labels/train/f37478_santiago_ferrero_14.txt...

 72%|███████▏  | 817/1137 [32:46<11:57,  2.24s/it]

Done.
Downloading 188trXH6EIk4-dUzdE5AGA49dAqRtNwDg into /content/dataset/labels/train/f37478_santiago_ferrero_16.txt...

 72%|███████▏  | 818/1137 [32:48<11:42,  2.20s/it]

Done.
Downloading 1o59X29WzbBON0pjmZTkf__wGpdkwH1vZ into /content/dataset/labels/train/f37478_santiago_ferrero_17.txt...

 72%|███████▏  | 819/1137 [32:50<12:24,  2.34s/it]

Done.
Downloading 1u1CGOeLSdm1Z82DxE2HhPe1SQ8a3XskP into /content/dataset/labels/train/f37478_santiago_ferrero_20.txt...

 72%|███████▏  | 820/1137 [32:53<12:00,  2.27s/it]

Done.
Downloading 1PXDaQn049J2omcsYcD1uU5Xzpy950PL6 into /content/dataset/labels/train/f37478_santiago_ferrero_21.txt...

 72%|███████▏  | 821/1137 [32:55<11:43,  2.23s/it]

Done.
Downloading 1EprBzFgGngKA-PT-hqGz20uGGrnxZGzV into /content/dataset/labels/train/f37478_santiago_ferrero_22.txt...

 72%|███████▏  | 822/1137 [32:57<11:33,  2.20s/it]

Done.
Downloading 1GtWiF7bTyttj8MYC3Dwo28rPgqmPnEjv into /content/dataset/labels/train/f37478_santiago_ferrero_23.txt...

 72%|███████▏  | 823/1137 [32:59<12:02,  2.30s/it]

Done.
Downloading 1KzBROntZcpU2z7AFDn0jQ5AHSFCxIGX4 into /content/dataset/labels/train/f37478_santiago_ferrero_24.txt...

 72%|███████▏  | 824/1137 [33:02<11:52,  2.28s/it]

Done.
Downloading 1WDVvZtrvKau-tz5C-gsoWu9wfNk751MS into /content/dataset/labels/train/f37478_santiago_ferrero_26.txt...

 73%|███████▎  | 825/1137 [33:04<11:47,  2.27s/it]

Done.
Downloading 1BJ2NXn_A3UxhM36JM6DHZTs6qr3SMbCp into /content/dataset/labels/train/f37478_santiago_ferrero_28.txt...

 73%|███████▎  | 826/1137 [33:06<11:40,  2.25s/it]

Done.
Downloading 1f-rSqEvpPNUaIfs4WsN46fdNl8YfsJAY into /content/dataset/labels/train/f37478_santiago_ferrero_29.txt...

 73%|███████▎  | 827/1137 [33:08<11:26,  2.21s/it]

Done.
Downloading 1jfjtOnMglSO3-aFjLetdZrmDuaYVGFvx into /content/dataset/labels/train/f37478_santiago_ferrero_30.txt...

 73%|███████▎  | 828/1137 [33:10<11:18,  2.20s/it]

Done.
Downloading 1dUPsgRLGMOwywase1drWej5M3b7MITGm into /content/dataset/labels/train/f37478_santiago_ferrero_31.txt...

 73%|███████▎  | 829/1137 [33:12<11:04,  2.16s/it]

Done.
Downloading 1C-HUNKrtGoB5NTFxbaOD9f3igGze7a9v into /content/dataset/labels/train/f37478_santiago_ferrero_32.txt...

 73%|███████▎  | 830/1137 [33:15<11:18,  2.21s/it]

Done.
Downloading 1m2pfx3-Ptw-n125BmikIyuKWjUvuNu0X into /content/dataset/labels/train/f37478_santiago_ferrero_33.txt...

 73%|███████▎  | 831/1137 [33:17<11:50,  2.32s/it]

Done.
Downloading 1H0Jz6TXV0smPVp6NoWpSXmSfRWHQHxjO into /content/dataset/labels/train/f37478_santiago_ferrero_34.txt...

 73%|███████▎  | 832/1137 [33:20<12:17,  2.42s/it]

Done.
Downloading 1n7jZr5BoLvqiY4hm2xVC7sR0R0pyBjZE into /content/dataset/labels/train/f37478_santiago_ferrero_35.txt...

 73%|███████▎  | 833/1137 [33:22<11:33,  2.28s/it]

Done.
Downloading 1KJItdznpBDz5YvtcHlxpGEQVrII07fEQ into /content/dataset/labels/train/f37478_santiago_ferrero_37.txt...

 73%|███████▎  | 834/1137 [33:24<11:16,  2.23s/it]

Done.
Downloading 1yofs5sVwWuRrg13BfsnGZFkxyKx1Xfdh into /content/dataset/labels/train/f37478_santiago_ferrero_38.txt...

 73%|███████▎  | 835/1137 [33:26<11:20,  2.25s/it]

Done.
Downloading 19jv3OxMPM9M9u7qwX5m7ComIqgF-2LK2 into /content/dataset/labels/train/f37478_santiago_ferrero_39.txt...

 74%|███████▎  | 836/1137 [33:28<11:01,  2.20s/it]

Done.
Downloading 1-ufjzWKdBWLFuT8bpFJ6pNWUNciYlPl_ into /content/dataset/labels/train/f37478_santiago_ferrero_40.txt...

 74%|███████▎  | 837/1137 [33:31<11:05,  2.22s/it]

Done.
Downloading 1PmUAJRkQrnGssCwf1IlJ5LZT_DNIHnW- into /content/dataset/labels/train/f3e9723ebb2cd8f05e49ac06a3288f8e.txt...

 74%|███████▎  | 838/1137 [33:33<11:11,  2.25s/it]

Done.
Downloading 1j1Z-YQpioK-ESelq3RirWjEEsikDoQgr into /content/dataset/labels/train/f53a4aca993ad6bf5e67c3184690eae1.txt...

 74%|███████▍  | 839/1137 [33:35<11:27,  2.31s/it]

Done.
Downloading 1RAen2p4ey0LCFkyUo7S7b0c3vGMmB5Vq into /content/dataset/labels/train/f5bdbc47a9fbe44482cdc1322b16c5bc.txt...

 74%|███████▍  | 840/1137 [33:38<11:53,  2.40s/it]

Done.
Downloading 15H2LLlUPGgQZ_r6vGA918RuqMZZDK39t into /content/dataset/labels/train/fed41586e4af6462681da0eab7d26de9.txt...

 74%|███████▍  | 841/1137 [33:40<11:32,  2.34s/it]

Done.
Downloading 1kEbloFIsvv_t_mi2lIoysuWxWseQYIxL into /content/dataset/labels/train/g5845_gravifiorino_1.txt...

 74%|███████▍  | 842/1137 [33:42<11:22,  2.31s/it]

Done.
Downloading 1Q3bs3AYkuK8hbA4bNH04NMlaneWkPB1j into /content/dataset/labels/train/g5845_gravifiorino_10.txt...

 74%|███████▍  | 843/1137 [33:45<11:05,  2.26s/it]

Done.
Downloading 1-TtBO-GN6eevcm5vthP8SiQ7qKJMcrFr into /content/dataset/labels/train/g5845_gravifiorino_11.txt...

 74%|███████▍  | 844/1137 [33:47<10:53,  2.23s/it]

Done.
Downloading 1xKnPwOzPFx2-z6ubX-yPDMq_tpNpo5d3 into /content/dataset/labels/train/g5845_gravifiorino_12.txt...

 74%|███████▍  | 845/1137 [33:49<10:49,  2.22s/it]

Done.
Downloading 1NyR9mi3QWI0bkDW6z4Zi9a817juDDLvv into /content/dataset/labels/train/g5845_gravifiorino_14.txt...

 74%|███████▍  | 846/1137 [33:51<10:34,  2.18s/it]

Done.
Downloading 1UQ9ZtzcDhGcjR9H8UT9xv0GXVfqDFtOX into /content/dataset/labels/train/g5845_gravifiorino_15.txt...

 74%|███████▍  | 847/1137 [33:53<10:34,  2.19s/it]

Done.
Downloading 1y016-U-gRlWhEipk8q2AuMqm7hLF0H6f into /content/dataset/labels/train/g5845_gravifiorino_16.txt...

 75%|███████▍  | 848/1137 [33:56<10:46,  2.24s/it]

Done.
Downloading 13GRzLeIqsWolh3Gw--FYfQK9vpScbhlh into /content/dataset/labels/train/g5845_gravifiorino_18.txt...

 75%|███████▍  | 849/1137 [33:58<10:39,  2.22s/it]

Done.
Downloading 1dsK-U1oTMlQiy5RZhBZV-maDFD05I3DO into /content/dataset/labels/train/g5845_gravifiorino_21.txt...

 75%|███████▍  | 850/1137 [34:00<10:40,  2.23s/it]

Done.
Downloading 1mbeHE7M_c9vKwnidKmLj1q9IRq1ePhNM into /content/dataset/labels/train/g5845_gravifiorino_23.txt...

 75%|███████▍  | 851/1137 [34:02<10:45,  2.26s/it]

Done.
Downloading 1BEG37VZGzQL6eVJMH_oF4OoGouTt301o into /content/dataset/labels/train/g5845_gravifiorino_26.txt...

 75%|███████▍  | 852/1137 [34:05<11:19,  2.39s/it]

Done.
Downloading 1e3Koan66fLIVZ7Htkjarkc2ttd8-sJkp into /content/dataset/labels/train/g5845_gravifiorino_27.txt...

 75%|███████▌  | 853/1137 [34:07<10:55,  2.31s/it]

Done.
Downloading 1Ze9v3pn-54gVMufICrxM3wvVtl27t9Na into /content/dataset/labels/train/g5845_gravifiorino_28.txt...

 75%|███████▌  | 854/1137 [34:10<10:56,  2.32s/it]

Done.
Downloading 1XnY17ayVNROsby-z0wdwtfCJetTnElMl into /content/dataset/labels/train/g5845_gravifiorino_29.txt...

 75%|███████▌  | 855/1137 [34:12<10:55,  2.32s/it]

Done.
Downloading 1askQHuQSLpVlHj0XKvnGP43FtGxsMDWh into /content/dataset/labels/train/g5845_gravifiorino_4.txt...

 75%|███████▌  | 856/1137 [34:14<11:03,  2.36s/it]

Done.
Downloading 1xtMP7M2y1KvQmPNdbAKXr_Kfp7cNEmSP into /content/dataset/labels/train/g5845_gravifiorino_5.txt...

 75%|███████▌  | 857/1137 [34:17<11:01,  2.36s/it]

Done.
Downloading 1M2KW3dQCkCL3Spw0ouJFZHWsAa4Nbq4Z into /content/dataset/labels/train/g5845_gravifiorino_6.txt...

 75%|███████▌  | 858/1137 [34:19<10:57,  2.36s/it]

Done.
Downloading 10VFJoTUe-lpjsniyvcaqw9Z2dEvCt58B into /content/dataset/labels/train/g5845_gravifiorino_7.txt...

 76%|███████▌  | 859/1137 [34:21<10:49,  2.34s/it]

Done.
Downloading 1oegzg0kH1dZKFMIyMPong0JNIb-ciqWr into /content/dataset/labels/train/g5845_gravifiorino_8.txt...

 76%|███████▌  | 860/1137 [34:23<10:32,  2.28s/it]

Done.
Downloading 1oEc9SeIRZ5sDGE220q9HPHNLNvx27z7r into /content/dataset/labels/train/g5845_gravifiorino_9.txt...

 76%|███████▌  | 861/1137 [34:26<10:29,  2.28s/it]

Done.
Downloading 12DIagcYxeaeB3KiyWBe1RABGXWmH9Le7 into /content/dataset/labels/train/gravifiorino_1.txt...

 76%|███████▌  | 862/1137 [34:28<10:06,  2.21s/it]

Done.
Downloading 1eibFxpP7oQYDitUqdcmzncK2sMPI9zCY into /content/dataset/labels/train/gravifiorino_10.txt...

 76%|███████▌  | 863/1137 [34:30<10:09,  2.22s/it]

Done.
Downloading 19-2sYw0PCAG5EMIHhAiPxPrAu83we1gL into /content/dataset/labels/train/gravifiorino_4.txt...

 76%|███████▌  | 864/1137 [34:32<09:49,  2.16s/it]

Done.
Downloading 1wHJsDMc1lawhkFPRP9OD4u2v3zrlMYVR into /content/dataset/labels/train/gravifiorino_5.txt...

 76%|███████▌  | 865/1137 [34:34<09:55,  2.19s/it]

Done.
Downloading 1N6Dga9EiNNZaq4Am-4aA5cvBMVmjmiiG into /content/dataset/labels/train/gravifiorino_6.txt...

 76%|███████▌  | 866/1137 [35:03<45:56, 10.17s/it]

Done.
Downloading 10J3cmz7eJhyxF_E_E5kOMK6aB0yWDPP5 into /content/dataset/labels/train/gravifiorino_7.txt...

 76%|███████▋  | 867/1137 [35:06<35:28,  7.88s/it]

Done.
Downloading 1fhEikzyHozi_hOpgtWBlc3apEUb2dVf9 into /content/dataset/labels/train/gravifiorino_8.txt...

 76%|███████▋  | 868/1137 [35:08<27:49,  6.21s/it]

Done.
Downloading 13thT9ucUvyuXHht9U_Ih-W_dEDwlxTVS into /content/dataset/labels/train/s56189_salvador_sanchez_0.txt...

 76%|███████▋  | 869/1137 [35:10<22:37,  5.07s/it]

Done.
Downloading 1FdMc5iym-h4KSOZ_t4SS32WICxwxRZW6 into /content/dataset/labels/train/s56189_salvador_sanchez_1.txt...

 77%|███████▋  | 870/1137 [35:13<18:58,  4.26s/it]

Done.
Downloading 1LxyCRd6v6HGZ5-IK0CQ-2SFU5CKf5XRl into /content/dataset/labels/train/s56189_salvador_sanchez_100.txt...

 77%|███████▋  | 871/1137 [35:15<16:10,  3.65s/it]

Done.
Downloading 1MBPJgiw0VWku5plzW9x_AlorQP67XVyi into /content/dataset/labels/train/s56189_salvador_sanchez_102.txt...

 77%|███████▋  | 872/1137 [35:17<14:21,  3.25s/it]

Done.
Downloading 1M86pfu0lqpLRBvBqIWehibCrO3oIU-zH into /content/dataset/labels/train/s56189_salvador_sanchez_104.txt...

 77%|███████▋  | 873/1137 [35:20<13:06,  2.98s/it]

Done.
Downloading 1MIwVMRcYhSRkjiTWesyLQ_HrzhGtBUHS into /content/dataset/labels/train/s56189_salvador_sanchez_105.txt...

 77%|███████▋  | 874/1137 [35:22<11:57,  2.73s/it]

Done.
Downloading 1MKfqODCl68teH0h4lGm5YwJ2Z57Udyds into /content/dataset/labels/train/s56189_salvador_sanchez_106.txt...

 77%|███████▋  | 875/1137 [35:24<11:29,  2.63s/it]

Done.
Downloading 1MQwDp69gRfyWC6Ki4NRjMO4BpSfz5f85 into /content/dataset/labels/train/s56189_salvador_sanchez_108.txt...

 77%|███████▋  | 876/1137 [35:26<11:03,  2.54s/it]

Done.
Downloading 1MS7e0mNsdiv3zhFIDziqVCvnD7Pt7HYD into /content/dataset/labels/train/s56189_salvador_sanchez_109.txt...

 77%|███████▋  | 877/1137 [35:29<10:40,  2.46s/it]

Done.
Downloading 10R_1qzNMsQsyNmtrnjhgXcLk4m-RILc7 into /content/dataset/labels/train/s56189_salvador_sanchez_11.txt...

 77%|███████▋  | 878/1137 [35:31<10:12,  2.36s/it]

Done.
Downloading 1MTFNN87F2UU6OwCgtl8Z-Hljo3-cK-fZ into /content/dataset/labels/train/s56189_salvador_sanchez_110.txt...

 77%|███████▋  | 879/1137 [35:33<10:01,  2.33s/it]

Done.
Downloading 1MZVpeTi7vvzNX6capNjWIoDT-FG1JnPe into /content/dataset/labels/train/s56189_salvador_sanchez_112.txt...

 77%|███████▋  | 880/1137 [35:36<10:07,  2.37s/it]

Done.
Downloading 1MhOy02VAYh24VBwPwqqaGHQRn1VRl43u into /content/dataset/labels/train/s56189_salvador_sanchez_116.txt...

 77%|███████▋  | 881/1137 [35:38<09:45,  2.29s/it]

Done.
Downloading 1N0ZN6puyiM_yM4pVkaa0ezMJCktIWx-r into /content/dataset/labels/train/s56189_salvador_sanchez_117.txt...

 78%|███████▊  | 882/1137 [35:40<09:40,  2.28s/it]

Done.
Downloading 1MxC3Iinjk0nMhVtiGSS-No7RB4abiV6b into /content/dataset/labels/train/s56189_salvador_sanchez_118.txt...

 78%|███████▊  | 883/1137 [35:42<09:21,  2.21s/it]

Done.
Downloading 1Mm_qrMX9ahykowUFojm9CQB9F3b79TDS into /content/dataset/labels/train/s56189_salvador_sanchez_119.txt...

 78%|███████▊  | 884/1137 [35:44<09:10,  2.18s/it]

Done.
Downloading 10EduwW82l8Yez7Hqs3reEh8qoNHamrLV into /content/dataset/labels/train/s56189_salvador_sanchez_12.txt...

 78%|███████▊  | 885/1137 [35:46<09:15,  2.21s/it]

Done.
Downloading 1N895rZMMtZtV6Om3sXU3_sgp43LxGdUx into /content/dataset/labels/train/s56189_salvador_sanchez_121.txt...

 78%|███████▊  | 886/1137 [35:49<09:14,  2.21s/it]

Done.
Downloading 1NMTBTCbwxDsax9X6KwPdk1r1GsEtArVZ into /content/dataset/labels/train/s56189_salvador_sanchez_122.txt...

 78%|███████▊  | 887/1137 [35:51<09:41,  2.33s/it]

Done.
Downloading 1NQ40WvB2MQVHNHeUXG-03_Jn7sobfMo9 into /content/dataset/labels/train/s56189_salvador_sanchez_125.txt...

 78%|███████▊  | 888/1137 [35:53<09:17,  2.24s/it]

Done.
Downloading 1NZaHzGU-eI9dHzZtfQhykEFufTqrzKPm into /content/dataset/labels/train/s56189_salvador_sanchez_127.txt...

 78%|███████▊  | 889/1137 [35:55<09:15,  2.24s/it]

Done.
Downloading 1N_UPILUxRjfIXTPQPKSkD0lQez-6B8rw into /content/dataset/labels/train/s56189_salvador_sanchez_128.txt...

 78%|███████▊  | 890/1137 [35:58<09:17,  2.26s/it]

Done.
Downloading 1NpolemR_jGDs8jvmW3iYVkKkPnL8w093 into /content/dataset/labels/train/s56189_salvador_sanchez_130.txt...

 78%|███████▊  | 891/1137 [36:00<09:05,  2.22s/it]

Done.
Downloading 1NxG9QKelPoqZo8qZ5eVqYk6tXGj1Yl4K into /content/dataset/labels/train/s56189_salvador_sanchez_132.txt...

 78%|███████▊  | 892/1137 [36:02<08:57,  2.19s/it]

Done.
Downloading 1OBEAflC4vwkNlFcG6pvQwqesR1LGBqXT into /content/dataset/labels/train/s56189_salvador_sanchez_133.txt...

 79%|███████▊  | 893/1137 [36:04<09:02,  2.22s/it]

Done.
Downloading 1OU8k_Mj8euNnlbITObxL-zVd6iDvc1nP into /content/dataset/labels/train/s56189_salvador_sanchez_135.txt...

 79%|███████▊  | 894/1137 [36:06<08:53,  2.20s/it]

Done.
Downloading 1ORGpI9VSBiInIaEFjz1M5FQjmiGso7vv into /content/dataset/labels/train/s56189_salvador_sanchez_136.txt...

 79%|███████▊  | 895/1137 [36:34<39:17,  9.74s/it]

Done.
Downloading 1OcJ7ZAOjKSdigbcUyHx1PD_tem3LLIVu into /content/dataset/labels/train/s56189_salvador_sanchez_137.txt...

 79%|███████▉  | 896/1137 [36:36<30:18,  7.55s/it]

Done.
Downloading 1OeSOSZZrCbpWK1LdVdDw3WpHZx71Ctba into /content/dataset/labels/train/s56189_salvador_sanchez_138.txt...

 79%|███████▉  | 897/1137 [36:39<24:42,  6.18s/it]

Done.
Downloading 1OghW2XWyFdei3SbyOLXFs5BRFnaFRwFH into /content/dataset/labels/train/s56189_salvador_sanchez_141.txt...

 79%|███████▉  | 898/1137 [36:41<19:51,  4.98s/it]

Done.
Downloading 1Omd_6fB63zRzX8SEXsvB8CCIjTz3U3_F into /content/dataset/labels/train/s56189_salvador_sanchez_142.txt...

 79%|███████▉  | 899/1137 [36:44<16:27,  4.15s/it]

Done.
Downloading 1Oo84BJaBtLrS8qwp-8sIqReYfXnUZ0f_ into /content/dataset/labels/train/s56189_salvador_sanchez_144.txt...

 79%|███████▉  | 900/1137 [36:46<14:10,  3.59s/it]

Done.
Downloading 1OtKVgOXEalCionwlAtqfj3FSOeKDivxk into /content/dataset/labels/train/s56189_salvador_sanchez_145.txt...

 79%|███████▉  | 901/1137 [36:48<12:53,  3.28s/it]

Done.
Downloading 1OvlW7PQ7-SfoBEjQWBJh_vbAjbOh-mZk into /content/dataset/labels/train/s56189_salvador_sanchez_146.txt...

 79%|███████▉  | 902/1137 [36:51<11:39,  2.98s/it]

Done.
Downloading 1PLKj6k6DoW-vYypzg3QvHPqTqAy8NPks into /content/dataset/labels/train/s56189_salvador_sanchez_147.txt...

 79%|███████▉  | 903/1137 [36:53<10:36,  2.72s/it]

Done.
Downloading 1P9Ib3x4lNaVJSuSeIY7JblJiK7UQhs8b into /content/dataset/labels/train/s56189_salvador_sanchez_148.txt...

 80%|███████▉  | 904/1137 [36:55<10:00,  2.58s/it]

Done.
Downloading 1OxkfRRotZDN_x6J3ugjghv_ZfPbKpO5z into /content/dataset/labels/train/s56189_salvador_sanchez_149.txt...

 80%|███████▉  | 905/1137 [36:57<09:22,  2.43s/it]

Done.
Downloading 10kyBjuy84pExx3AQSD8ZKtN14s0g8YjN into /content/dataset/labels/train/s56189_salvador_sanchez_15.txt...

 80%|███████▉  | 906/1137 [37:00<09:15,  2.40s/it]

Done.
Downloading 1PpQZ1HQyJzdFZBrmxCUHogL5HqJjmNFc into /content/dataset/labels/train/s56189_salvador_sanchez_152.txt...

 80%|███████▉  | 907/1137 [37:02<08:59,  2.35s/it]

Done.
Downloading 1PXIHZO9SBSTOfEHCK8BhArvDDf4PLU2k into /content/dataset/labels/train/s56189_salvador_sanchez_153.txt...

 80%|███████▉  | 908/1137 [37:04<08:37,  2.26s/it]

Done.
Downloading 1Pvsd-vF-aPwO0cv8sG0pd4-MlgrjpQY8 into /content/dataset/labels/train/s56189_salvador_sanchez_155.txt...

 80%|███████▉  | 909/1137 [37:06<08:45,  2.31s/it]

Done.
Downloading 1PztBaXUldZwrTpcrS2GVrUQoU2egCSc0 into /content/dataset/labels/train/s56189_salvador_sanchez_157.txt...

 80%|████████  | 910/1137 [37:09<08:52,  2.35s/it]

Done.
Downloading 1QJZn_q1p54_8bqv8D5Sw32HALkLlzXzI into /content/dataset/labels/train/s56189_salvador_sanchez_158.txt...

 80%|████████  | 911/1137 [37:11<08:57,  2.38s/it]

Done.
Downloading 1Q5D6-VaOG7X1FW1g7IxttAHECgYn1Zab into /content/dataset/labels/train/s56189_salvador_sanchez_160.txt...

 80%|████████  | 912/1137 [37:14<09:35,  2.56s/it]

Done.
Downloading 1QNpAJ5TmXbqV1qhRo6UUxo3q0-FuBCPr into /content/dataset/labels/train/s56189_salvador_sanchez_161.txt...

 80%|████████  | 913/1137 [37:16<09:15,  2.48s/it]

Done.
Downloading 1QKyPfGbbEUeBliOQNiF3QLINBK6AsN9D into /content/dataset/labels/train/s56189_salvador_sanchez_162.txt...

 80%|████████  | 914/1137 [37:19<09:01,  2.43s/it]

Done.
Downloading 1QJhjWMI5ySy0Ytcl2z5uPGBlCbqt6Xc1 into /content/dataset/labels/train/s56189_salvador_sanchez_163.txt...

 80%|████████  | 915/1137 [37:21<09:05,  2.46s/it]

Done.
Downloading 1QXZdQBBqy_9qFPcWL6GmnQgM4PZkVKh- into /content/dataset/labels/train/s56189_salvador_sanchez_164.txt...

 81%|████████  | 916/1137 [37:24<08:55,  2.42s/it]

Done.
Downloading 1QmA0I0NHiUmcrip8czDHlvZiEZ97cor9 into /content/dataset/labels/train/s56189_salvador_sanchez_166.txt...

 81%|████████  | 917/1137 [37:26<08:46,  2.39s/it]

Done.
Downloading 1QgX3gSgeawytJC5UeKlYQkuQpetRcbj0 into /content/dataset/labels/train/s56189_salvador_sanchez_168.txt...

 81%|████████  | 918/1137 [37:28<08:33,  2.34s/it]

Done.
Downloading 1Qbh-QF_sslTR-AE2lBBHtYa3-Ugon91S into /content/dataset/labels/train/s56189_salvador_sanchez_169.txt...

 81%|████████  | 919/1137 [37:31<09:12,  2.53s/it]

Done.
Downloading 10rQDKndYVxv4SvtpvNn6_Fg6aayi7Z4p into /content/dataset/labels/train/s56189_salvador_sanchez_17.txt...

 81%|████████  | 920/1137 [37:33<08:52,  2.45s/it]

Done.
Downloading 1QpEr-YRao9X-70sNODDb0R1tiiP-6iaB into /content/dataset/labels/train/s56189_salvador_sanchez_170.txt...

 81%|████████  | 921/1137 [37:36<08:43,  2.43s/it]

Done.
Downloading 1Qmac_E23sVKkazslFXRUdR_Qnpu1DtjW into /content/dataset/labels/train/s56189_salvador_sanchez_171.txt...

 81%|████████  | 922/1137 [37:38<08:15,  2.30s/it]

Done.
Downloading 1R1BVY_Q3nUQ04mekmCXW-VZa_GykBVN8 into /content/dataset/labels/train/s56189_salvador_sanchez_172.txt...

 81%|████████  | 923/1137 [37:40<08:00,  2.24s/it]

Done.
Downloading 1R-pRa7_UMCINHX7yFRrYGj6Ogs974nk- into /content/dataset/labels/train/s56189_salvador_sanchez_173.txt...

 81%|████████▏ | 924/1137 [37:42<08:10,  2.30s/it]

Done.
Downloading 1Qt6PQZz1TRcRrvIz-Noo0Z0zcwwyiwRM into /content/dataset/labels/train/s56189_salvador_sanchez_174.txt...

 81%|████████▏ | 925/1137 [37:45<08:11,  2.32s/it]

Done.
Downloading 1R-ShnKgCiVOs1J5TwCWogysC0xOlhgae into /content/dataset/labels/train/s56189_salvador_sanchez_175.txt...

 81%|████████▏ | 926/1137 [37:47<08:00,  2.28s/it]

Done.
Downloading 1R8nR6lkJdgZzxelqTGVOySHVvcXtXSaw into /content/dataset/labels/train/s56189_salvador_sanchez_176.txt...

 82%|████████▏ | 927/1137 [37:49<07:50,  2.24s/it]

Done.
Downloading 1R6l2J4ldWU4v-TqW_YxWb9WN8I2bT81u into /content/dataset/labels/train/s56189_salvador_sanchez_177.txt...

 82%|████████▏ | 928/1137 [37:51<07:44,  2.22s/it]

Done.
Downloading 1RALuKEDvtLufWC-31ooVeUwvjb-H5KDu into /content/dataset/labels/train/s56189_salvador_sanchez_179.txt...

 82%|████████▏ | 929/1137 [37:53<07:39,  2.21s/it]

Done.
Downloading 110jtfeKUWs_lTQdvJ6mEOuMlptygwOef into /content/dataset/labels/train/s56189_salvador_sanchez_18.txt...

 82%|████████▏ | 930/1137 [37:56<08:03,  2.34s/it]

Done.
Downloading 1RHHZyrLYwa5yaIW-Kxztp2kgLW8z-Wzt into /content/dataset/labels/train/s56189_salvador_sanchez_181.txt...

 82%|████████▏ | 931/1137 [37:59<08:25,  2.45s/it]

Done.
Downloading 1RWxDb0JT4tjeTDtqUyGXcU2bqWw-1qlm into /content/dataset/labels/train/s56189_salvador_sanchez_183.txt...

 82%|████████▏ | 932/1137 [38:01<07:58,  2.34s/it]

Done.
Downloading 1Rc2oZA7YPlGjj0o74hj5eBnXiNuMm3gJ into /content/dataset/labels/train/s56189_salvador_sanchez_184.txt...

 82%|████████▏ | 933/1137 [38:03<08:07,  2.39s/it]

Done.
Downloading 1Re29xBsPg90Q5C-aqWfnBfJsqVhvMFWW into /content/dataset/labels/train/s56189_salvador_sanchez_185.txt...

 82%|████████▏ | 934/1137 [38:06<08:00,  2.37s/it]

Done.
Downloading 1Rh5v4qLBHxUFLPEOrkip0-4vfVW4-4_P into /content/dataset/labels/train/s56189_salvador_sanchez_186.txt...

 82%|████████▏ | 935/1137 [38:08<07:40,  2.28s/it]

Done.
Downloading 1Rf-231r4ZFTxfepBxRHqZPVmFLi0vese into /content/dataset/labels/train/s56189_salvador_sanchez_187.txt...

 82%|████████▏ | 936/1137 [38:10<07:23,  2.21s/it]

Done.
Downloading 1RqSO259o7J9oZoGJkmuAzkwEuTLTNbvg into /content/dataset/labels/train/s56189_salvador_sanchez_188.txt...

 82%|████████▏ | 937/1137 [38:12<07:18,  2.19s/it]

Done.
Downloading 10zAU_iWMMy0_3FeR-UNgqH_Sd6XBcUg8 into /content/dataset/labels/train/s56189_salvador_sanchez_19.txt...

 82%|████████▏ | 938/1137 [38:14<07:14,  2.18s/it]

Done.
Downloading 1Rw9KnR1hN4eFOHphipkitqnXnTKT3B9M into /content/dataset/labels/train/s56189_salvador_sanchez_190.txt...

 83%|████████▎ | 939/1137 [38:16<07:03,  2.14s/it]

Done.
Downloading 1SA1rY_v_KYbc4s0tewtfmHcEshPGGssM into /content/dataset/labels/train/s56189_salvador_sanchez_192.txt...

 83%|████████▎ | 940/1137 [38:18<06:53,  2.10s/it]

Done.
Downloading 1SDbcEo-15xy_2DStDxcjRk-R8EHUYa0G into /content/dataset/labels/train/s56189_salvador_sanchez_194.txt...

 83%|████████▎ | 941/1137 [38:20<07:11,  2.20s/it]

Done.
Downloading 1SVD9d872zTlT02SwB1ZedV870L5E_ekR into /content/dataset/labels/train/s56189_salvador_sanchez_195.txt...

 83%|████████▎ | 942/1137 [38:23<07:07,  2.19s/it]

Done.
Downloading 1SpPCWzNWR0SOrNrD5KI6yrcfAI5HqFUR into /content/dataset/labels/train/s56189_salvador_sanchez_199.txt...

 83%|████████▎ | 943/1137 [38:48<29:18,  9.07s/it]

Done.
Downloading 1V1m2bUmzhhI-Y_mXDlK4Tvu7wnxcWyue into /content/dataset/labels/train/s56189_salvador_sanchez_2.txt...

 83%|████████▎ | 944/1137 [38:50<22:32,  7.01s/it]

Done.
Downloading 11NrM-ceMrKyTrFQaoY5xiicrMBHDXZSb into /content/dataset/labels/train/s56189_salvador_sanchez_20.txt...

 83%|████████▎ | 945/1137 [38:52<17:51,  5.58s/it]

Done.
Downloading 1SoBimomEO7BPrAiT_1BY0r8z3qr1-rH_ into /content/dataset/labels/train/s56189_salvador_sanchez_200.txt...

 83%|████████▎ | 946/1137 [38:54<14:32,  4.57s/it]

Done.
Downloading 1Sbx7U3Id-RVBBE0g5Dz1cJfQlyEmBzZd into /content/dataset/labels/train/s56189_salvador_sanchez_201.txt...

 83%|████████▎ | 947/1137 [38:57<12:13,  3.86s/it]

Done.
Downloading 1Swb3124yv4sSmSc-RxpSjs5KeYdDAbxs into /content/dataset/labels/train/s56189_salvador_sanchez_202.txt...

 83%|████████▎ | 948/1137 [38:59<10:29,  3.33s/it]

Done.
Downloading 1T-kDyPYMp8Pg0PtR-Kdfvxy2DcA80P1x into /content/dataset/labels/train/s56189_salvador_sanchez_204.txt...

 83%|████████▎ | 949/1137 [39:01<09:37,  3.07s/it]

Done.
Downloading 1SypbE7t9a-CF556Or3oRGaf4Iy5-_Si8 into /content/dataset/labels/train/s56189_salvador_sanchez_205.txt...

 84%|████████▎ | 950/1137 [39:03<08:43,  2.80s/it]

Done.
Downloading 1T2fB4SJhRdjB7SK4cBipHvAA_pTpozBL into /content/dataset/labels/train/s56189_salvador_sanchez_206.txt...

 84%|████████▎ | 951/1137 [39:06<08:04,  2.61s/it]

Done.
Downloading 1T1WutuWkmuCdAaf4hX18B60km800qN1k into /content/dataset/labels/train/s56189_salvador_sanchez_207.txt...

 84%|████████▎ | 952/1137 [39:08<07:41,  2.50s/it]

Done.
Downloading 1T3st31IlSH5X975Qm6zntYtDYo1jtGpo into /content/dataset/labels/train/s56189_salvador_sanchez_208.txt...

 84%|████████▍ | 953/1137 [39:10<07:26,  2.43s/it]

Done.
Downloading 1146CU6bm3Aqg6FkJ7sOBk9kwg_myqwia into /content/dataset/labels/train/s56189_salvador_sanchez_21.txt...

 84%|████████▍ | 954/1137 [39:12<07:05,  2.33s/it]

Done.
Downloading 1TIFqWr6oZ52PjKQMiOV9PZEym6n2HTWf into /content/dataset/labels/train/s56189_salvador_sanchez_211.txt...

 84%|████████▍ | 955/1137 [39:14<06:59,  2.31s/it]

Done.
Downloading 1TXWO5YWSYfe5Og6KjW6Msw7vbXgsCgc9 into /content/dataset/labels/train/s56189_salvador_sanchez_213.txt...

 84%|████████▍ | 956/1137 [39:17<07:07,  2.36s/it]

Done.
Downloading 1TsDAaHpFiZX1ZHMzEg4Gxs4X6lfJPA1e into /content/dataset/labels/train/s56189_salvador_sanchez_214.txt...

 84%|████████▍ | 957/1137 [39:20<07:21,  2.45s/it]

Done.
Downloading 1TnsDl4bt9HiNCOkICKEhxafcMxSrD0LQ into /content/dataset/labels/train/s56189_salvador_sanchez_215.txt...

 84%|████████▍ | 958/1137 [39:22<07:10,  2.40s/it]

Done.
Downloading 1TjrTnNTeY65tar-EmZsYn4f8ZMeTFXPJ into /content/dataset/labels/train/s56189_salvador_sanchez_216.txt...

 84%|████████▍ | 959/1137 [39:24<07:04,  2.39s/it]

Done.
Downloading 1TwOSOeDTYdxfn0kahOKtQe4m8vmK3EtD into /content/dataset/labels/train/s56189_salvador_sanchez_218.txt...

 84%|████████▍ | 960/1137 [39:26<06:58,  2.37s/it]

Done.
Downloading 1TzGzRN8L5AtA5FCB50uyHlP2ObAmhj0e into /content/dataset/labels/train/s56189_salvador_sanchez_221.txt...

 85%|████████▍ | 961/1137 [39:29<06:55,  2.36s/it]

Done.
Downloading 1UP0pKFlT5GPoPGXdBrDFZCWwLkHFyOZD into /content/dataset/labels/train/s56189_salvador_sanchez_222.txt...

 85%|████████▍ | 962/1137 [39:31<06:42,  2.30s/it]

Done.
Downloading 1UFGBWkIURipiwSKZ2nvTCZa13hB_vBLI into /content/dataset/labels/train/s56189_salvador_sanchez_223.txt...

 85%|████████▍ | 963/1137 [39:33<06:50,  2.36s/it]

Done.
Downloading 1U8IEpcZadl7UKuJRljgO5kmy1oNtYzH7 into /content/dataset/labels/train/s56189_salvador_sanchez_225.txt...

 85%|████████▍ | 964/1137 [39:36<06:32,  2.27s/it]

Done.
Downloading 1UTdoZzZuuathku2XB3nq1HOkhRHPdrD_ into /content/dataset/labels/train/s56189_salvador_sanchez_227.txt...

 85%|████████▍ | 965/1137 [39:38<06:30,  2.27s/it]

Done.
Downloading 1UwhtUexgL-asaoB2TpbB7Lx93ORt5Jaq into /content/dataset/labels/train/s56189_salvador_sanchez_230.txt...

 85%|████████▍ | 966/1137 [39:40<06:25,  2.25s/it]

Done.
Downloading 1UrlyZgp_AkKL7lT3i_o-ZX2LVzKBM5lN into /content/dataset/labels/train/s56189_salvador_sanchez_231.txt...

 85%|████████▌ | 967/1137 [39:42<06:19,  2.23s/it]

Done.
Downloading 1V37Gy6XlJ8XEisSfu3ksZoVaqbsOAbmp into /content/dataset/labels/train/s56189_salvador_sanchez_232.txt...

 85%|████████▌ | 968/1137 [39:45<06:40,  2.37s/it]

Done.
Downloading 1V-3c7mcxQOEBxo3zSMazQQwjGePX8moY into /content/dataset/labels/train/s56189_salvador_sanchez_233.txt...

 85%|████████▌ | 969/1137 [39:47<06:26,  2.30s/it]

Done.
Downloading 1V8Kn_1cpHOMcKg35s_QpRv2yj-SiT7tb into /content/dataset/labels/train/s56189_salvador_sanchez_234.txt...

 85%|████████▌ | 970/1137 [39:49<06:08,  2.21s/it]

Done.
Downloading 1V6OtEp53FIm9l8prQ5IecplKNg5iRFks into /content/dataset/labels/train/s56189_salvador_sanchez_235.txt...

 85%|████████▌ | 971/1137 [39:51<06:09,  2.23s/it]

Done.
Downloading 1VNDLg6ftHUVhdupotPsCOIg2cFi4WSdV into /content/dataset/labels/train/s56189_salvador_sanchez_236.txt...

 85%|████████▌ | 972/1137 [39:54<06:16,  2.28s/it]

Done.
Downloading 1VCUashMv7Xo8D5DeixyI2vXpzJYxgTM9 into /content/dataset/labels/train/s56189_salvador_sanchez_237.txt...

 86%|████████▌ | 973/1137 [39:56<06:30,  2.38s/it]

Done.
Downloading 1VYCboyokZwkn95jnmRtAxrw5BHe90k1P into /content/dataset/labels/train/s56189_salvador_sanchez_238.txt...

 86%|████████▌ | 974/1137 [39:59<06:23,  2.36s/it]

Done.
Downloading 1VX1-RaQQjbil3nPWclSMae8LtZwXj73z into /content/dataset/labels/train/s56189_salvador_sanchez_239.txt...

 86%|████████▌ | 975/1137 [40:01<06:23,  2.37s/it]

Done.
Downloading 11lv51dZybHM33Q-RD2_E5xKANfCEgIGH into /content/dataset/labels/train/s56189_salvador_sanchez_24.txt...

 86%|████████▌ | 976/1137 [40:03<06:21,  2.37s/it]

Done.
Downloading 1VTXnIow9mnXuBe89XeBRrfD6JeF953f6 into /content/dataset/labels/train/s56189_salvador_sanchez_240.txt...

 86%|████████▌ | 977/1137 [40:06<06:11,  2.32s/it]

Done.
Downloading 1VSyZIxIldZu0SLungMOZr7uGphAsSTg7 into /content/dataset/labels/train/s56189_salvador_sanchez_241.txt...

 86%|████████▌ | 978/1137 [40:08<06:07,  2.31s/it]

Done.
Downloading 1Vhcbbj643Lg28555q0ckhDyUSIRNAlOT into /content/dataset/labels/train/s56189_salvador_sanchez_243.txt...

 86%|████████▌ | 979/1137 [40:10<06:09,  2.34s/it]

Done.
Downloading 1VaENfCD4qbhLu13qZycNROKK91RSSrzj into /content/dataset/labels/train/s56189_salvador_sanchez_244.txt...

 86%|████████▌ | 980/1137 [40:13<06:09,  2.35s/it]

Done.
Downloading 1VdId3265roNdGdmrBJFQzwyNz-_p86-1 into /content/dataset/labels/train/s56189_salvador_sanchez_245.txt...

 86%|████████▋ | 981/1137 [40:15<06:07,  2.35s/it]

Done.
Downloading 1Vyc-3w9fqC6_pkl8xkzndjW1on0sg85m into /content/dataset/labels/train/s56189_salvador_sanchez_247.txt...

 86%|████████▋ | 982/1137 [40:17<05:58,  2.32s/it]

Done.
Downloading 1Vx7rRM5ByHUNzhDYS1H25wHwABwGtcdU into /content/dataset/labels/train/s56189_salvador_sanchez_248.txt...

 86%|████████▋ | 983/1137 [40:19<05:49,  2.27s/it]

Done.
Downloading 1Vs9C4hxm6CePD87i7beHEdYtHkOJMUyw into /content/dataset/labels/train/s56189_salvador_sanchez_249.txt...

 87%|████████▋ | 984/1137 [40:22<06:01,  2.36s/it]

Done.
Downloading 11iz3csWXNiKafyjQUqxpYhVH_guEL7HJ into /content/dataset/labels/train/s56189_salvador_sanchez_25.txt...

 87%|████████▋ | 985/1137 [40:24<05:51,  2.31s/it]

Done.
Downloading 1W8GPAbPeLHMnEldpRWWjdlaZGI9njdwr into /content/dataset/labels/train/s56189_salvador_sanchez_250.txt...

 87%|████████▋ | 986/1137 [40:26<05:44,  2.28s/it]

Done.
Downloading 1VpC3V0MopjhGE2mSFlESRcfenrir95qu into /content/dataset/labels/train/s56189_salvador_sanchez_251.txt...

 87%|████████▋ | 987/1137 [40:29<05:43,  2.29s/it]

Done.
Downloading 1W6yceNy20iGgX4MCXot-nphf_IDooqCh into /content/dataset/labels/train/s56189_salvador_sanchez_252.txt...

 87%|████████▋ | 988/1137 [40:31<05:46,  2.33s/it]

Done.
Downloading 1W5C6i6FThboid_tqtMNoO5K8MlbcoGoz into /content/dataset/labels/train/s56189_salvador_sanchez_253.txt...

 87%|████████▋ | 989/1137 [40:33<05:42,  2.31s/it]

Done.
Downloading 1WALAH2i-I-uG-F8C6fnZ3Dn2z1NvF8d1 into /content/dataset/labels/train/s56189_salvador_sanchez_255.txt...

 87%|████████▋ | 990/1137 [40:36<05:34,  2.27s/it]

Done.
Downloading 1WJ7MVoC_bQQa2O_DUaJETts2Dq9Ju15u into /content/dataset/labels/train/s56189_salvador_sanchez_256.txt...

 87%|████████▋ | 991/1137 [40:38<05:39,  2.33s/it]

Done.
Downloading 1WB988hUtO9aodt-CyZvbFq9cVCLtEsTH into /content/dataset/labels/train/s56189_salvador_sanchez_258.txt...

 87%|████████▋ | 992/1137 [40:40<05:38,  2.33s/it]

Done.
Downloading 1WQGLSF2n56pOP4xBW0F6PtMa8lebNlYB into /content/dataset/labels/train/s56189_salvador_sanchez_259.txt...

 87%|████████▋ | 993/1137 [40:43<05:47,  2.41s/it]

Done.
Downloading 1WKs0ndPXIWcLl4LIUeI8ZgZfE03ftRUN into /content/dataset/labels/train/s56189_salvador_sanchez_260.txt...

 87%|████████▋ | 994/1137 [40:45<05:48,  2.44s/it]

Done.
Downloading 1WT2lBfeTyLauZ8_vWyzKAGuPiR7wegO_ into /content/dataset/labels/train/s56189_salvador_sanchez_261.txt...

 88%|████████▊ | 995/1137 [40:48<05:32,  2.34s/it]

Done.
Downloading 1WUkHBJaTOb-1E49deEPEBTjFd9b2mXM9 into /content/dataset/labels/train/s56189_salvador_sanchez_262.txt...

 88%|████████▊ | 996/1137 [40:50<05:17,  2.25s/it]

Done.
Downloading 1WfCGV5D1RhgNrjsGXfgHwQyfR1RQZahJ into /content/dataset/labels/train/s56189_salvador_sanchez_264.txt...

 88%|████████▊ | 997/1137 [40:52<05:09,  2.21s/it]

Done.
Downloading 1WiHkTiPOld-oDjpdzMY5BibLKhxD5zfm into /content/dataset/labels/train/s56189_salvador_sanchez_267.txt...

 88%|████████▊ | 998/1137 [40:54<05:20,  2.31s/it]

Done.
Downloading 1Wg9R4E-ItNq4WI4MK33pYndAmVMEuaWy into /content/dataset/labels/train/s56189_salvador_sanchez_268.txt...

 88%|████████▊ | 999/1137 [40:57<05:20,  2.32s/it]

Done.
Downloading 1WuXYoiNgScLGmM8Ka4ee3DiH2EslLiyN into /content/dataset/labels/train/s56189_salvador_sanchez_270.txt...

 88%|████████▊ | 1000/1137 [40:59<05:25,  2.38s/it]

Done.
Downloading 1WpqANxIToDc1WNfRJcnxpwu_8c67yBrg into /content/dataset/labels/train/s56189_salvador_sanchez_271.txt...

 88%|████████▊ | 1001/1137 [41:01<05:16,  2.33s/it]

Done.
Downloading 1X5WqL-yS9mElWSBbbPg2RrbbplNsUfnR into /content/dataset/labels/train/s56189_salvador_sanchez_273.txt...

 88%|████████▊ | 1002/1137 [41:04<05:09,  2.29s/it]

Done.
Downloading 1XL64H13_J44mTDOXcQyi4413zfWltU5w into /content/dataset/labels/train/s56189_salvador_sanchez_275.txt...

 88%|████████▊ | 1003/1137 [41:06<05:15,  2.36s/it]

Done.
Downloading 1XDMOb2kw3WThVSXshgh47WEoRKkSbG8Y into /content/dataset/labels/train/s56189_salvador_sanchez_277.txt...

 88%|████████▊ | 1004/1137 [41:08<05:04,  2.29s/it]

Done.
Downloading 1X7uBFGlQRU1ywufDTFmKDWxPkVBrXK2s into /content/dataset/labels/train/s56189_salvador_sanchez_278.txt...

 88%|████████▊ | 1005/1137 [41:10<04:57,  2.26s/it]

Done.
Downloading 1XaDi3_mroJFJao28x4I3psZcmq5oqqai into /content/dataset/labels/train/s56189_salvador_sanchez_279.txt...

 88%|████████▊ | 1006/1137 [41:13<04:56,  2.26s/it]

Done.
Downloading 123TEtXbQBiV-rqimkCxMlpavdemvKQQp into /content/dataset/labels/train/s56189_salvador_sanchez_28.txt...

 89%|████████▊ | 1007/1137 [41:15<04:49,  2.23s/it]

Done.
Downloading 1XWXYL-TFK617z3xHmhH7c4D2-f0YpLOd into /content/dataset/labels/train/s56189_salvador_sanchez_280.txt...

 89%|████████▊ | 1008/1137 [41:17<04:44,  2.21s/it]

Done.
Downloading 1Xhc8IMaLSI7VeZ6meSZZB7VgeXHUQGzF into /content/dataset/labels/train/s56189_salvador_sanchez_281.txt...

 89%|████████▊ | 1009/1137 [41:19<04:50,  2.27s/it]

Done.
Downloading 1XgFtYevEhDKFfpx74T3SFjOiOU4qsvxo into /content/dataset/labels/train/s56189_salvador_sanchez_282.txt...

 89%|████████▉ | 1010/1137 [41:22<04:53,  2.31s/it]

Done.
Downloading 1XjA1bDjvosYrV6o-BR85Y7GzTKgV78uT into /content/dataset/labels/train/s56189_salvador_sanchez_284.txt...

 89%|████████▉ | 1011/1137 [41:24<04:44,  2.26s/it]

Done.
Downloading 1Y7Kd-I1I9GP_N5gUmJMhNEFWxlHFfRoF into /content/dataset/labels/train/s56189_salvador_sanchez_285.txt...

 89%|████████▉ | 1012/1137 [41:26<04:39,  2.24s/it]

Done.
Downloading 1Y6BHxPVHcz5NrFkjcJgWrSgt1qtjpOQ6 into /content/dataset/labels/train/s56189_salvador_sanchez_286.txt...

 89%|████████▉ | 1013/1137 [41:28<04:39,  2.25s/it]

Done.
Downloading 1XuSkoa39fUG4kqfFC9nLlQxNTZyKeXfp into /content/dataset/labels/train/s56189_salvador_sanchez_288.txt...

 89%|████████▉ | 1014/1137 [41:35<07:20,  3.58s/it]

Done.
Downloading 1YG-9r2crwIY8-kep8m715tWWd-XC-XEP into /content/dataset/labels/train/s56189_salvador_sanchez_289.txt...

 89%|████████▉ | 1015/1137 [41:37<06:28,  3.18s/it]

Done.
Downloading 11soxHq3-eBbFWJ7x6UvVay0-jfPsKw4L into /content/dataset/labels/train/s56189_salvador_sanchez_29.txt...

 89%|████████▉ | 1016/1137 [41:40<05:49,  2.89s/it]

Done.
Downloading 1YANeusrKO285YXygGA1sCviG54TYIAY9 into /content/dataset/labels/train/s56189_salvador_sanchez_290.txt...

 89%|████████▉ | 1017/1137 [41:42<05:30,  2.76s/it]

Done.
Downloading 1YA2t2Fl7Gn7OyhDgJVSFqMvkQYFjMSe3 into /content/dataset/labels/train/s56189_salvador_sanchez_291.txt...

 90%|████████▉ | 1018/1137 [41:45<05:22,  2.71s/it]

Done.
Downloading 1Y8N4qjEmuhPwNXMQgAXvtt8s-vdptkvS into /content/dataset/labels/train/s56189_salvador_sanchez_292.txt...

 90%|████████▉ | 1019/1137 [41:47<04:59,  2.54s/it]

Done.
Downloading 1YUoNrcQ8z3-JLShESzDtmP6Di5crLuDT into /content/dataset/labels/train/s56189_salvador_sanchez_293.txt...

 90%|████████▉ | 1020/1137 [41:49<04:43,  2.42s/it]

Done.
Downloading 1YdUvoTf0h9GE-qN9PMTnFxLsLPoWPMOd into /content/dataset/labels/train/s56189_salvador_sanchez_296.txt...

 90%|████████▉ | 1021/1137 [41:51<04:39,  2.41s/it]

Done.
Downloading 1Y_MTcF87_zy8E18gomy6e7azHH6pU77j into /content/dataset/labels/train/s56189_salvador_sanchez_297.txt...

 90%|████████▉ | 1022/1137 [41:53<04:28,  2.33s/it]

Done.
Downloading 1YZlLASvsowU7350NwfbeEQIvjKFzhyZ5 into /content/dataset/labels/train/s56189_salvador_sanchez_298.txt...

 90%|████████▉ | 1023/1137 [41:56<04:21,  2.29s/it]

Done.
Downloading 1Yfo5GJISpJ3Ym606KJm7XwTX9I9UPpnF into /content/dataset/labels/train/s56189_salvador_sanchez_299.txt...

 90%|█████████ | 1024/1137 [41:58<04:31,  2.40s/it]

Done.
Downloading 1bs0hx1PYq3c2FL0S2eDqp4b0o122o24o into /content/dataset/labels/train/s56189_salvador_sanchez_3.txt...

 90%|█████████ | 1025/1137 [42:01<04:27,  2.39s/it]

Done.
Downloading 11sVVRdvfJddC5l2a7Ic4LpK3Ie9YKFfK into /content/dataset/labels/train/s56189_salvador_sanchez_30.txt...

 90%|█████████ | 1026/1137 [42:03<04:16,  2.31s/it]

Done.
Downloading 1YeMIklD2uQeWlcF8iBnf6kwBSWwrr2J3 into /content/dataset/labels/train/s56189_salvador_sanchez_300.txt...

 90%|█████████ | 1027/1137 [42:05<04:19,  2.36s/it]

Done.
Downloading 1YyMVkL9jxEjL6qUPZI0nEg9Msh3Xe2lA into /content/dataset/labels/train/s56189_salvador_sanchez_303.txt...

 90%|█████████ | 1028/1137 [42:08<04:15,  2.34s/it]

Done.
Downloading 1YrydewvS38HBdXY327H1q6ixIklo8l4N into /content/dataset/labels/train/s56189_salvador_sanchez_304.txt...

 91%|█████████ | 1029/1137 [42:10<04:09,  2.31s/it]

Done.
Downloading 1Z6UuqBr53StPyGaHigm_E4I2zLCG2AOp into /content/dataset/labels/train/s56189_salvador_sanchez_306.txt...

 91%|█████████ | 1030/1137 [42:12<04:08,  2.32s/it]

Done.
Downloading 1ZJh39zI-naRj8m9Zuw5JKIijs2mAyAuR into /content/dataset/labels/train/s56189_salvador_sanchez_308.txt...

 91%|█████████ | 1031/1137 [42:14<04:05,  2.32s/it]

Done.
Downloading 12LzjboKS6UY-YJLQyR_G8-sNlQzCKTlp into /content/dataset/labels/train/s56189_salvador_sanchez_31.txt...

 91%|█████████ | 1032/1137 [42:17<03:59,  2.28s/it]

Done.
Downloading 1ZEbCd0fMgbKzQwD0YyAviY37DlXz9P88 into /content/dataset/labels/train/s56189_salvador_sanchez_310.txt...

 91%|█████████ | 1033/1137 [42:19<04:03,  2.34s/it]

Done.
Downloading 1ZTQwGj7NGBFLDMB79KeSiDQRPccp3ru9 into /content/dataset/labels/train/s56189_salvador_sanchez_311.txt...

 91%|█████████ | 1034/1137 [42:21<04:00,  2.34s/it]

Done.
Downloading 1ZRnECAgEC813v6mR8iMV0OGRrTKbnmwp into /content/dataset/labels/train/s56189_salvador_sanchez_312.txt...

 91%|█████████ | 1035/1137 [42:24<03:55,  2.31s/it]

Done.
Downloading 1Ziu3bKM4DPLBrQoJ-Cqb89KvVbGUjgsn into /content/dataset/labels/train/s56189_salvador_sanchez_313.txt...

 91%|█████████ | 1036/1137 [42:26<03:55,  2.34s/it]

Done.
Downloading 1ZaPCOinNs2ghkB_HktHRxp2BsacyySkm into /content/dataset/labels/train/s56189_salvador_sanchez_315.txt...

 91%|█████████ | 1037/1137 [42:28<03:48,  2.29s/it]

Done.
Downloading 1Z_VH74Jc0a1CLJxQNuyhoXHNVfwWCoTn into /content/dataset/labels/train/s56189_salvador_sanchez_316.txt...

 91%|█████████▏| 1038/1137 [42:31<03:48,  2.31s/it]

Done.
Downloading 1Zq72t_IwGOg5QX64jZ3jw9pdw06DrrrH into /content/dataset/labels/train/s56189_salvador_sanchez_317.txt...

 91%|█████████▏| 1039/1137 [42:33<03:43,  2.28s/it]

Done.
Downloading 1ZonNHuE65Wq3k55wuc52TkePMf4EFQRC into /content/dataset/labels/train/s56189_salvador_sanchez_318.txt...

 91%|█████████▏| 1040/1137 [42:35<03:41,  2.28s/it]

Done.
Downloading 12CFZZEbUAxrzxw8TpFaxRLVHoazcIahQ into /content/dataset/labels/train/s56189_salvador_sanchez_32.txt...

 92%|█████████▏| 1041/1137 [42:37<03:38,  2.27s/it]

Done.
Downloading 12HVK5raexAjBVvA94fEZ36Tun0qoWIs3 into /content/dataset/labels/train/s56189_salvador_sanchez_33.txt...

 92%|█████████▏| 1042/1137 [42:40<03:37,  2.29s/it]

Done.
Downloading 12Oy6kwpzm7Jlat3DUiURKoT0nPL46v4_ into /content/dataset/labels/train/s56189_salvador_sanchez_34.txt...

 92%|█████████▏| 1043/1137 [42:42<03:38,  2.33s/it]

Done.
Downloading 12TZR8OFoQsez4mTeCHkZU7xnSpQIzx-l into /content/dataset/labels/train/s56189_salvador_sanchez_35.txt...

 92%|█████████▏| 1044/1137 [42:44<03:31,  2.28s/it]

Done.
Downloading 12Yj7N20GIopVpYOqNml3Er4RyfmsJMZK into /content/dataset/labels/train/s56189_salvador_sanchez_37.txt...

 92%|█████████▏| 1045/1137 [42:47<03:31,  2.30s/it]

Done.
Downloading 12d3YlvqRR0YvWc-eL8GBl0HuOENEjz7g into /content/dataset/labels/train/s56189_salvador_sanchez_39.txt...

 92%|█████████▏| 1046/1137 [42:49<03:32,  2.34s/it]

Done.
Downloading 19YD_YR1Hmt4t1-P-c4ZTiGrjL8AiQyO7 into /content/dataset/labels/train/s56189_salvador_sanchez_4.txt...

 92%|█████████▏| 1047/1137 [42:51<03:29,  2.33s/it]

Done.
Downloading 12uy3UKcpWFsUh5rHbblWPFfH2JQu_2Nu into /content/dataset/labels/train/s56189_salvador_sanchez_41.txt...

 92%|█████████▏| 1048/1137 [42:54<03:22,  2.27s/it]

Done.
Downloading 12z9BFagUq6EJcjGbtIBjBwBfR4ghRpBX into /content/dataset/labels/train/s56189_salvador_sanchez_42.txt...

 92%|█████████▏| 1049/1137 [42:56<03:24,  2.33s/it]

Done.
Downloading 12vH_h5pQCFkPZDUzCaWVN28VuijjUNXd into /content/dataset/labels/train/s56189_salvador_sanchez_43.txt...

 92%|█████████▏| 1050/1137 [42:58<03:26,  2.37s/it]

Done.
Downloading 139YG8EDmty6rYyZEHEV6LZeyxmhGZTvK into /content/dataset/labels/train/s56189_salvador_sanchez_44.txt...

 92%|█████████▏| 1051/1137 [43:01<03:24,  2.38s/it]

Done.
Downloading 1306sU_uXTecNkd1JJpacH9f2ohBMUjIL into /content/dataset/labels/train/s56189_salvador_sanchez_45.txt...

 93%|█████████▎| 1052/1137 [43:03<03:16,  2.31s/it]

Done.
Downloading 13C5OhXMD2Wix9j_x-hBxDApzfmU6NSQJ into /content/dataset/labels/train/s56189_salvador_sanchez_46.txt...

 93%|█████████▎| 1053/1137 [43:05<03:11,  2.29s/it]

Done.
Downloading 13Q7-DFYA1ynh_MqLAvBjvZ3m68dzkZHN into /content/dataset/labels/train/s56189_salvador_sanchez_47.txt...

 93%|█████████▎| 1054/1137 [43:08<03:10,  2.29s/it]

Done.
Downloading 13MC8i_RIJsaKg4J6cGzMZJiKAo2pmtiM into /content/dataset/labels/train/s56189_salvador_sanchez_48.txt...

 93%|█████████▎| 1055/1137 [43:10<03:01,  2.21s/it]

Done.
Downloading 1IaT0ZjmIJroivXB74nssIb-TTCD2L7Ws into /content/dataset/labels/train/s56189_salvador_sanchez_50.txt...

 93%|█████████▎| 1056/1137 [43:12<02:59,  2.21s/it]

Done.
Downloading 1IpjC5cZB3YQHwh2UcsLG7Mg3-0zHOPl3 into /content/dataset/labels/train/s56189_salvador_sanchez_51.txt...

 93%|█████████▎| 1057/1137 [43:14<02:58,  2.23s/it]

Done.
Downloading 1ImzFB0Xq5UG1tfxAxbqHKFoXDAHxGKk6 into /content/dataset/labels/train/s56189_salvador_sanchez_52.txt...

 93%|█████████▎| 1058/1137 [43:16<02:57,  2.24s/it]

Done.
Downloading 1J5zETmdAdCw3hINR9mr0wvzIiZHVug78 into /content/dataset/labels/train/s56189_salvador_sanchez_56.txt...

 93%|█████████▎| 1059/1137 [43:19<02:56,  2.27s/it]

Done.
Downloading 1J2XQwSGS8vY9qQ78GR8NdaAPJ0J48oQn into /content/dataset/labels/train/s56189_salvador_sanchez_57.txt...

 93%|█████████▎| 1060/1137 [43:21<02:50,  2.21s/it]

Done.
Downloading 1Iu5H9mVcCkS0au1pk50QaigjjBHE81at into /content/dataset/labels/train/s56189_salvador_sanchez_59.txt...

 93%|█████████▎| 1061/1137 [43:23<02:51,  2.26s/it]

Done.
Downloading 1IuhCtNLVrplR98eLGKOTo5P0RYmQCH9t into /content/dataset/labels/train/s56189_salvador_sanchez_60.txt...

 93%|█████████▎| 1062/1137 [43:25<02:44,  2.19s/it]

Done.
Downloading 1Ir7oV_L0ZaNDfHHQI23DpBeL45buDcCI into /content/dataset/labels/train/s56189_salvador_sanchez_62.txt...

 93%|█████████▎| 1063/1137 [43:27<02:40,  2.16s/it]

Done.
Downloading 1JIUXxquXmdHDswu7gBl4frwBwzQPHwm_ into /content/dataset/labels/train/s56189_salvador_sanchez_63.txt...

 94%|█████████▎| 1064/1137 [43:29<02:37,  2.16s/it]

Done.
Downloading 1JOW_MR_QmDEAmns3JlxmSZPzjPAsuVrn into /content/dataset/labels/train/s56189_salvador_sanchez_64.txt...

 94%|█████████▎| 1065/1137 [43:32<02:37,  2.18s/it]

Done.
Downloading 1JSYG1Ybpd2moXP2RX2JNRqgquYTp3yyX into /content/dataset/labels/train/s56189_salvador_sanchez_65.txt...

 94%|█████████▍| 1066/1137 [43:34<02:42,  2.29s/it]

Done.
Downloading 1JWjwjw56er0G8Mw2bDzojqeXX-xujsm6 into /content/dataset/labels/train/s56189_salvador_sanchez_66.txt...

 94%|█████████▍| 1067/1137 [43:36<02:40,  2.29s/it]

Done.
Downloading 1JeTcXJqp8rXXrhJmzvwUxLbX9516l2k5 into /content/dataset/labels/train/s56189_salvador_sanchez_67.txt...

 94%|█████████▍| 1068/1137 [43:39<02:39,  2.31s/it]

Done.
Downloading 1JblOt1d7QmldWHiyYyd4i2VhDYodQ7AM into /content/dataset/labels/train/s56189_salvador_sanchez_68.txt...

 94%|█████████▍| 1069/1137 [43:41<02:40,  2.36s/it]

Done.
Downloading 1JoGF04dgg1xuDz43fKjc95Xv6wrlCEq2 into /content/dataset/labels/train/s56189_salvador_sanchez_69.txt...

 94%|█████████▍| 1070/1137 [43:44<02:36,  2.34s/it]

Done.
Downloading 1-IK8y872ODsdc31RJet4B8zPqj-jFhh2 into /content/dataset/labels/train/s56189_salvador_sanchez_7.txt...

 94%|█████████▍| 1071/1137 [43:46<02:34,  2.34s/it]

Done.
Downloading 1KAYuBlXGPfzasRj0-H2pqjaVzTH2CNte into /content/dataset/labels/train/s56189_salvador_sanchez_71.txt...

 94%|█████████▍| 1072/1137 [43:48<02:30,  2.32s/it]

Done.
Downloading 1K7xHONI4iXt3UHfGGYLC5f8loWj-Kl80 into /content/dataset/labels/train/s56189_salvador_sanchez_72.txt...

 94%|█████████▍| 1073/1137 [43:50<02:27,  2.31s/it]

Done.
Downloading 1K2M2QSwpCxoJxGzKWva_ys1gUETgAkHf into /content/dataset/labels/train/s56189_salvador_sanchez_73.txt...

 94%|█████████▍| 1074/1137 [43:53<02:24,  2.29s/it]

Done.
Downloading 1JxVIY2AbUyILiz_Na8Yfn4M20dl89Kl- into /content/dataset/labels/train/s56189_salvador_sanchez_74.txt...

 95%|█████████▍| 1075/1137 [43:55<02:19,  2.24s/it]

Done.
Downloading 1KCfeD5lqbrbXKCInXBSPpm4LDGynYAIp into /content/dataset/labels/train/s56189_salvador_sanchez_75.txt...

 95%|█████████▍| 1076/1137 [43:57<02:17,  2.26s/it]

Done.
Downloading 1KkxwLpKAa37tYA7hgT9_HolifoE43390 into /content/dataset/labels/train/s56189_salvador_sanchez_76.txt...

 95%|█████████▍| 1077/1137 [43:59<02:13,  2.22s/it]

Done.
Downloading 1KSyETO8RXbkIuiCxu3Ao2MiCbJo67-cE into /content/dataset/labels/train/s56189_salvador_sanchez_77.txt...

 95%|█████████▍| 1078/1137 [44:02<02:13,  2.26s/it]

Done.
Downloading 1KIIlQnb2uH6sLmIuA05lJh54zgCTb63G into /content/dataset/labels/train/s56189_salvador_sanchez_79.txt...

 95%|█████████▍| 1079/1137 [44:04<02:18,  2.39s/it]

Done.
Downloading 1-AYc1kJB_uVzzAx7w6arAIddeiZvorgL into /content/dataset/labels/train/s56189_salvador_sanchez_8.txt...

 95%|█████████▍| 1080/1137 [44:07<02:18,  2.43s/it]

Done.
Downloading 1KpNA27YNPB2uJYf7pQs9jsBoEz_IUF7n into /content/dataset/labels/train/s56189_salvador_sanchez_80.txt...

 95%|█████████▌| 1081/1137 [44:09<02:11,  2.35s/it]

Done.
Downloading 1Kr9o-vVJjTAbMt5NxbcPcXZm8aIxvqt9 into /content/dataset/labels/train/s56189_salvador_sanchez_81.txt...

 95%|█████████▌| 1082/1137 [44:11<02:09,  2.35s/it]

Done.
Downloading 1L8a9Z9QZdme8fG7asgXB1N7QzUjHJtme into /content/dataset/labels/train/s56189_salvador_sanchez_82.txt...

 95%|█████████▌| 1083/1137 [44:14<02:05,  2.33s/it]

Done.
Downloading 1L7c_7zgl3kgWFAgwn9azKnPZLAxP1Y9B into /content/dataset/labels/train/s56189_salvador_sanchez_83.txt...

 95%|█████████▌| 1084/1137 [44:16<02:04,  2.35s/it]

Done.
Downloading 1L6f_g0NCptDG0-miXuySY89bTU5EEXcl into /content/dataset/labels/train/s56189_salvador_sanchez_84.txt...

 95%|█████████▌| 1085/1137 [44:18<01:59,  2.30s/it]

Done.
Downloading 1L0XIvmXcsZuXf118WRsjRvZQ0cQhb4Wj into /content/dataset/labels/train/s56189_salvador_sanchez_85.txt...

 96%|█████████▌| 1086/1137 [44:20<01:56,  2.28s/it]

Done.
Downloading 1LG6H9QullK000-mC0zUcKT-AbkEFSlMP into /content/dataset/labels/train/s56189_salvador_sanchez_88.txt...

 96%|█████████▌| 1087/1137 [44:23<01:52,  2.26s/it]

Done.
Downloading 1-0a3zw-rbgUBhVj-pJjiE9kkjILmDPHR into /content/dataset/labels/train/s56189_salvador_sanchez_9.txt...

 96%|█████████▌| 1088/1137 [44:25<01:49,  2.23s/it]

Done.
Downloading 1LNJDJVH-kAo_m4bCjBMNDYv_Wopo0er9 into /content/dataset/labels/train/s56189_salvador_sanchez_90.txt...

 96%|█████████▌| 1089/1137 [44:27<01:49,  2.28s/it]

Done.
Downloading 1LMlcK7dNulhnkuIcx4R-ybyxTjs7Oiv4 into /content/dataset/labels/train/s56189_salvador_sanchez_92.txt...

 96%|█████████▌| 1090/1137 [44:30<01:48,  2.31s/it]

Done.
Downloading 1LTFSX9tF6dR1iW31iQQpwdvLBQFvE89C into /content/dataset/labels/train/s56189_salvador_sanchez_93.txt...

 96%|█████████▌| 1091/1137 [44:32<01:46,  2.32s/it]

Done.
Downloading 1LSVdDP-4gE8pjs8vONo65nSoBnc-tIkF into /content/dataset/labels/train/s56189_salvador_sanchez_94.txt...

 96%|█████████▌| 1092/1137 [44:34<01:45,  2.34s/it]

Done.
Downloading 1LmwW_59ui8ICK4-RgtjPnlloNtpB4Vj6 into /content/dataset/labels/train/s56189_salvador_sanchez_97.txt...

 96%|█████████▌| 1093/1137 [44:37<01:44,  2.38s/it]

Done.
Downloading 1Lo6WhTjXAP_bFh4BKx9-PCCng19FQLtC into /content/dataset/labels/train/s56189_salvador_sanchez_99.txt...

 96%|█████████▌| 1094/1137 [44:39<01:38,  2.30s/it]

Done.
Downloading 1gFRDRSIFqBxJRmmKIlqBRjtmZ9z72mrZ into /content/dataset/labels/train/s56804_alexis_segui_02.txt...

 96%|█████████▋| 1095/1137 [44:49<03:17,  4.69s/it]

Done.
Downloading 1hrKwbLQXVJtvVoPhoZpw972pEXYCEQEM into /content/dataset/labels/train/s56804_alexis_segui_04.txt...

 96%|█████████▋| 1096/1137 [44:51<02:42,  3.96s/it]

Done.
Downloading 1R0Zo7gzxfFnZGgPGMQv88go_vAVI7PnR into /content/dataset/labels/train/s56804_alexis_segui_06.txt...

 96%|█████████▋| 1097/1137 [44:53<02:14,  3.37s/it]

Done.
Downloading 1XOCLkVFWjJjr0uc7j6aEZgouEHc7LOzZ into /content/dataset/labels/train/s56804_alexis_segui_07.txt...

 97%|█████████▋| 1098/1137 [44:56<01:59,  3.05s/it]

Done.
Downloading 1AHuJW8duGjccE_2K8xmSJlBXtXOqsak9 into /content/dataset/labels/train/s56804_alexis_segui_10.txt...

 97%|█████████▋| 1099/1137 [44:58<01:45,  2.78s/it]

Done.
Downloading 1PkqpfNzZc9yTVpVHfX_3RSVfyxtq-MSb into /content/dataset/labels/train/s56804_alexis_segui_15.txt...

 97%|█████████▋| 1100/1137 [45:00<01:37,  2.62s/it]

Done.
Downloading 136K1fGFA2-Lsp0KcPAU_X1GS5ACXBHVj into /content/dataset/labels/train/s56804_alexis_segui_16.txt...

 97%|█████████▋| 1101/1137 [45:02<01:30,  2.51s/it]

Done.
Downloading 1s8YtdnxvUVZ_qo19tNero-OOo0VSzzxx into /content/dataset/labels/train/s56804_alexis_segui_17.txt...

 97%|█████████▋| 1102/1137 [45:04<01:23,  2.38s/it]

Done.
Downloading 1HTNBOZLYBpBd3zEn-IRySirYbk8GmCSv into /content/dataset/labels/train/s56804_alexis_segui_18.txt...

 97%|█████████▋| 1103/1137 [45:07<01:20,  2.37s/it]

Done.
Downloading 1xt5MNbvYJBlZyQraS1AQb6cA-xGq2jdX into /content/dataset/labels/train/s56804_alexis_segui_19.txt...

 97%|█████████▋| 1104/1137 [45:09<01:18,  2.38s/it]

Done.
Downloading 1JcH1OZBccuTQ3m8sYePXE2nvQM5RwQKj into /content/dataset/labels/train/s56804_alexis_segui_20.txt...

 97%|█████████▋| 1105/1137 [45:11<01:13,  2.29s/it]

Done.
Downloading 100LGeYPG3NdMzdPo3772qxUWsyKsXfp7 into /content/dataset/labels/train/s56804_alexis_segui_22.txt...

 97%|█████████▋| 1106/1137 [45:13<01:08,  2.22s/it]

Done.
Downloading 1RtoxU8dyEC_lXgOh9n-HOByHL8kRQnDr into /content/dataset/labels/train/s56804_alexis_segui_23.txt...

 97%|█████████▋| 1107/1137 [45:16<01:07,  2.26s/it]

Done.
Downloading 1Wxz_awP_V00M15pNo-ja7OiOd7F_8_NG into /content/dataset/labels/train/s56804_alexis_segui_24.txt...

 97%|█████████▋| 1108/1137 [45:18<01:05,  2.26s/it]

Done.
Downloading 1uq38DBGAq_LAXh6RltvzCLO9boOa2ue9 into /content/dataset/labels/train/s56804_alexis_segui_25.txt...

 98%|█████████▊| 1109/1137 [45:20<01:03,  2.28s/it]

Done.
Downloading 1ju6sX030-WOyqefZOjTxNlkmivbPwZpK into /content/dataset/labels/train/s56804_alexis_segui_26.txt...

 98%|█████████▊| 1110/1137 [45:23<01:02,  2.32s/it]

Done.
Downloading 1hrZLCVjYyOGmjOCPN92wJVSg4uPI3Mrf into /content/dataset/labels/train/s56804_alexis_segui_27.txt...

 98%|█████████▊| 1111/1137 [45:25<01:00,  2.32s/it]

Done.
Downloading 1KkVVs4_9sdWBRw1T5AT0ZQKu5rtyJEBa into /content/dataset/labels/train/s56804_alexis_segui_28.txt...

 98%|█████████▊| 1112/1137 [45:27<00:58,  2.33s/it]

Done.
Downloading 1KmbOGaY7EdittNJG5NaKwCKQHwji1eO7 into /content/dataset/labels/train/s56804_alexis_segui_29.txt...

 98%|█████████▊| 1113/1137 [45:30<00:56,  2.36s/it]

Done.
Downloading 1Ls6g_DtQw2bdD1tQpaLEKs3t2HBoMLrM into /content/dataset/labels/train/w05576_juan_wagner_02.txt...

 98%|█████████▊| 1114/1137 [45:32<00:52,  2.27s/it]

Done.
Downloading 1ASPoYY4NACCMjVG3RGgnBU_d3lfQjehw into /content/dataset/labels/train/w05576_juan_wagner_04.txt...

 98%|█████████▊| 1115/1137 [45:34<00:50,  2.30s/it]

Done.
Downloading 1XOWP3Z0zuxrz8iXinFKvDAMeloidAgoG into /content/dataset/labels/train/w05576_juan_wagner_05.txt...

 98%|█████████▊| 1116/1137 [45:37<00:49,  2.34s/it]

Done.
Downloading 1lhCVOYPCisgi-6YEMIL6qm0pTlFZzi0p into /content/dataset/labels/train/w05576_juan_wagner_06.txt...

 98%|█████████▊| 1117/1137 [45:39<00:48,  2.44s/it]

Done.
Downloading 1eo9CBXe1rrVDe2yuZXme4QyWGQ5yV1Mg into /content/dataset/labels/train/w05576_juan_wagner_07.txt...

 98%|█████████▊| 1118/1137 [45:42<00:48,  2.57s/it]

Done.
Downloading 1AZuzCs13lDXl3amYu0trk1MGvVHPftNU into /content/dataset/labels/train/w05576_juan_wagner_08.txt...

 98%|█████████▊| 1119/1137 [45:45<00:45,  2.53s/it]

Done.
Downloading 1h9H5oH14l5z1_eyKwQxSURnmUtD5szGb into /content/dataset/labels/train/w05576_juan_wagner_09.txt...

 99%|█████████▊| 1120/1137 [45:47<00:41,  2.43s/it]

Done.
Downloading 1q3ML57zawgwcv-krxWG4Vb0dQNkr5XjY into /content/dataset/labels/train/w05576_juan_wagner_10.txt...

 99%|█████████▊| 1121/1137 [45:49<00:37,  2.37s/it]

Done.
Downloading 1O2zLEkarFzQUMM_pLc0mV4z35kAV90IO into /content/dataset/labels/train/w05576_juan_wagner_11.txt...

 99%|█████████▊| 1122/1137 [45:51<00:34,  2.29s/it]

Done.
Downloading 1e0gHc9Y1TMedCDh9WsnksMdjtpWfm0SQ into /content/dataset/labels/train/w05576_juan_wagner_12.txt...

 99%|█████████▉| 1123/1137 [45:54<00:34,  2.43s/it]

Done.
Downloading 1l8IkeeVrqMm9EuuMzI16TxOnjBo6Ktwt into /content/dataset/labels/train/w05576_juan_wagner_13.txt...

 99%|█████████▉| 1124/1137 [45:56<00:31,  2.44s/it]

Done.
Downloading 1PAZbe1MufWzF-9gpJQDzRVIb5oIpxhgH into /content/dataset/labels/train/w05576_juan_wagner_14.txt...

 99%|█████████▉| 1125/1137 [45:59<00:29,  2.50s/it]

Done.
Downloading 1ql0gHK9ns6TJw8CXCBjjJitXWlBWUHRh into /content/dataset/labels/train/w05576_juan_wagner_15.txt...

 99%|█████████▉| 1126/1137 [46:01<00:26,  2.40s/it]

Done.
Downloading 13w9LDzKRFDWc5zIkZ_C0m_Njs9dDqQDd into /content/dataset/labels/train/w05576_juan_wagner_16.txt...

 99%|█████████▉| 1127/1137 [46:03<00:22,  2.29s/it]

Done.
Downloading 13R3X7pLEgCcosjUDjcHtqm9jsNbmgeeW into /content/dataset/labels/train/w05576_juan_wagner_18.txt...

 99%|█████████▉| 1128/1137 [46:06<00:20,  2.32s/it]

Done.
Downloading 1bK1bmbHxFgJ_1dO2-5HjSeE721vOQcVi into /content/dataset/labels/train/w05576_juan_wagner_19.txt...

 99%|█████████▉| 1129/1137 [46:08<00:18,  2.27s/it]

Done.
Downloading 1X0IYpzJaNXZTri_j5QUvFDyUITIjupY1 into /content/dataset/labels/train/w05576_juan_wagner_20.txt...

 99%|█████████▉| 1130/1137 [46:10<00:15,  2.22s/it]

Done.
Downloading 13qVlHZ9KlFmIlIQ88PXZP9-58oyBNVgi into /content/dataset/labels/train/w05576_juan_wagner_22.txt...

 99%|█████████▉| 1131/1137 [46:12<00:13,  2.26s/it]

Done.
Downloading 1mZlUh0Sn_aZ2mZsx1uSSlmCSYZxTjTSK into /content/dataset/labels/train/w05576_juan_wagner_26.txt...

100%|█████████▉| 1132/1137 [46:14<00:11,  2.22s/it]

Done.
Downloading 19s7cmTAgsDLIE5DdMWGNIFX4YR4UHXwE into /content/dataset/labels/train/w05576_juan_wagner_28.txt...

100%|█████████▉| 1133/1137 [46:25<00:18,  4.72s/it]

Done.
Downloading 1YJ2m23ls55r8Fz6w6IGencqQ0JkOE8oO into /content/dataset/labels/train/w05576_juan_wagner_30.txt...

100%|█████████▉| 1134/1137 [46:27<00:11,  3.98s/it]

Done.
Downloading 1FQZB0tykZTJDvj-H9oIz7qfStd-TflZx into /content/dataset/labels/train/w05576_juan_wagner_31.txt...

100%|█████████▉| 1135/1137 [46:29<00:06,  3.42s/it]

Done.
Downloading 1GWe__Ya4d77emXy3w3KevLiMthxwvi28 into /content/dataset/labels/train/w05576_juan_wagner_32.txt...

100%|█████████▉| 1136/1137 [46:32<00:03,  3.24s/it]

Done.
Downloading 1MoC25vxi9bLnP-WuK4jjKprdkj_8D7pk into /content/dataset/labels/train/w05576_juan_wagner_33.txt...

100%|██████████| 1137/1137 [46:34<00:00,  2.46s/it]

Done.

  0%|          | 0/488 [00:00<?, ?it/s]

Downloading 1SdLo2YcdH-4mCHemD8KRH2ePE3ToJJ1r into /content/dataset/labels/val/03531_mirian_yanez_16.txt...

  0%|          | 1/488 [00:02<20:31,  2.53s/it]

Done.
Downloading 1BdsN5e6fLhwN7AlPruqzywXR3irvAfvI into /content/dataset/labels/val/03531_mirian_yanez_19.txt...

  0%|          | 2/488 [00:04<19:04,  2.35s/it]

Done.
Downloading 1l3dqgtDsFyBvxfRUjpFvUS1Trt-9d1EE into /content/dataset/labels/val/03531_mirian_yanez_24.txt...

  1%|          | 3/488 [00:07<20:04,  2.48s/it]

Done.
Downloading 123--1_Iv6H4NAt22xUG0IFq9cfDzw8jA into /content/dataset/labels/val/03531_mirian_yanez_30.txt...

  1%|          | 4/488 [00:09<20:16,  2.51s/it]

Done.
Downloading 1JfDvfv7bRaqRMlAbOWht0rXKe2nRFLhl into /content/dataset/labels/val/03531_mirian_yanez_31.txt...

  1%|          | 5/488 [00:12<20:39,  2.57s/it]

Done.
Downloading 1kc2RkGcfa1BeUPO1h4i4iJKxEE-QnxjU into /content/dataset/labels/val/0a1343bac8cb2b14b120bc01bff80676.txt...

  1%|          | 6/488 [00:15<21:08,  2.63s/it]

Done.
Downloading 1ciezhJFCwjKjVMlFdliStP97XlTjMjzJ into /content/dataset/labels/val/0d4a74a58600d4a06f3738e853d315bb.txt...

  1%|▏         | 7/488 [00:17<20:31,  2.56s/it]

Done.
Downloading 1gIpk_urSURn-va6IOW7YypYFYBh8Q1Wz into /content/dataset/labels/val/12394_escandell_ariel_10.txt...

  2%|▏         | 8/488 [00:20<20:09,  2.52s/it]

Done.
Downloading 15QjQ_mx_B73dO8KqyUwega2R1YR_CEHX into /content/dataset/labels/val/12394_escandell_ariel_11.txt...

  2%|▏         | 9/488 [00:22<19:01,  2.38s/it]

Done.
Downloading 1gmB6w4hjcQ9uOFwKdESF1vlFccT5O-3u into /content/dataset/labels/val/12394_escandell_ariel_15.txt...

  2%|▏         | 10/488 [00:24<18:40,  2.34s/it]

Done.
Downloading 1FQUAN8f3sdqX9rt_zWMrVifkzX5Gum44 into /content/dataset/labels/val/12394_escandell_ariel_16.txt...

  2%|▏         | 11/488 [00:26<18:27,  2.32s/it]

Done.
Downloading 1Kh_QyGhrdgzqikE5h00HRfunDRDDu4dr into /content/dataset/labels/val/12394_escandell_ariel_18.txt...

  2%|▏         | 12/488 [00:29<18:29,  2.33s/it]

Done.
Downloading 1C5N92rs3OUW747_ICKXRc1n80zQCGsuy into /content/dataset/labels/val/12394_escandell_ariel_21.txt...

  3%|▎         | 13/488 [00:31<18:00,  2.28s/it]

Done.
Downloading 1bh9Wl8lAZCOxLZprchl7KyROuTpKMrVj into /content/dataset/labels/val/12394_escandell_ariel_23.txt...

  3%|▎         | 14/488 [00:33<18:16,  2.31s/it]

Done.
Downloading 1-EnxCj_kge8Fv9qE8HMzwzJQJrf7_3Nz into /content/dataset/labels/val/12394_escandell_ariel_25.txt...

  3%|▎         | 15/488 [00:36<19:01,  2.41s/it]

Done.
Downloading 1-BTtcUz6jghcnrqZEBnpjSgy6fhgwUkP into /content/dataset/labels/val/12394_escandell_ariel_26.txt...

  3%|▎         | 16/488 [00:38<18:34,  2.36s/it]

Done.
Downloading 1Os_gX0AN5fUw21IC4LfRRimZanm1UwjD into /content/dataset/labels/val/12394_escandell_ariel_30.txt...

  3%|▎         | 17/488 [00:41<19:03,  2.43s/it]

Done.
Downloading 1wjUbkyKH6D0_wwzcWHVIfkGjb3WT877P into /content/dataset/labels/val/17211af4d041d345cb72fbf6dd0417ba.txt...

  4%|▎         | 18/488 [00:43<18:35,  2.37s/it]

Done.
Downloading 1R5vB6VkGeQ6J3dpGj1W1wLHif_rfbhTj into /content/dataset/labels/val/23451_guido_lorenzettibruera_01.txt...

  4%|▍         | 19/488 [00:45<17:47,  2.28s/it]

Done.
Downloading 13idLq0WiwcEWk8iJ-w0xLlvP3vH6F1hk into /content/dataset/labels/val/23451_guido_lorenzettibruera_03.txt...

  4%|▍         | 20/488 [00:48<18:17,  2.35s/it]

Done.
Downloading 1wutw4UlAlbrtwOyyDB80u08FEFTY9az7 into /content/dataset/labels/val/23451_guido_lorenzettibruera_04.txt...

  4%|▍         | 21/488 [00:50<18:30,  2.38s/it]

Done.
Downloading 1nWY9dyM_wQRDyqDBFQ6d_OnIgBTaQALY into /content/dataset/labels/val/23451_guido_lorenzettibruera_07.txt...

  5%|▍         | 22/488 [00:52<17:58,  2.31s/it]

Done.
Downloading 1l5TUE3tBBIUBA6CSSeqFzpDY6TxQnt0N into /content/dataset/labels/val/23451_guido_lorenzettibruera_10.txt...

  5%|▍         | 23/488 [00:54<17:50,  2.30s/it]

Done.
Downloading 1KmlV1s2YyF-iiONkjEZnnelNbAe9aZNy into /content/dataset/labels/val/23451_guido_lorenzettibruera_12.txt...

  5%|▍         | 24/488 [00:57<17:27,  2.26s/it]

Done.
Downloading 1JV3sgDsiwRwbO0fQPvV5OMV0vn3fsDrK into /content/dataset/labels/val/23451_guido_lorenzettibruera_15.txt...

  5%|▌         | 25/488 [00:59<17:18,  2.24s/it]

Done.
Downloading 11v0VSmdRRulA_r4XLAbcMrsPQswaOdTp into /content/dataset/labels/val/23451_guido_lorenzettibruera_17.txt...

  5%|▌         | 26/488 [01:01<17:26,  2.27s/it]

Done.
Downloading 1HIzPgoGGls3vUAYZ4O6kVcfsVn-Tkg_o into /content/dataset/labels/val/23451_guido_lorenzettibruera_20.txt...

  6%|▌         | 27/488 [01:04<18:15,  2.38s/it]

Done.
Downloading 1AQelveSUxVc_VMpCFsehPx7X6e4-uJTk into /content/dataset/labels/val/32d8cd3cc1799c7e150bade5617735ce.txt...

  6%|▌         | 28/488 [01:06<17:45,  2.32s/it]

Done.
Downloading 1jquLxe-9WASn0y9yMGpJBt9vZOqSxIFy into /content/dataset/labels/val/33219c585c5dac63340294dda6e34412.txt...

  6%|▌         | 29/488 [01:08<17:45,  2.32s/it]

Done.
Downloading 1UB7ls2cK96Alox3po158d4QhypaZSSwi into /content/dataset/labels/val/3326205021f38e32701b096ffa2e8782.txt...

  6%|▌         | 30/488 [01:10<17:25,  2.28s/it]

Done.
Downloading 1bGDwWAOIEUaMe4q7-SXmj74ymrdL4jiy into /content/dataset/labels/val/37494_gustavo_fontana_04.txt...

  6%|▋         | 31/488 [01:13<17:37,  2.32s/it]

Done.
Downloading 1mELcb_f_5fQT1Gii8ExF-8P4Fut2GMa4 into /content/dataset/labels/val/37494_gustavo_fontana_06.txt...

  7%|▋         | 32/488 [01:15<17:30,  2.30s/it]

Done.
Downloading 1N7wu8SrA12jLVPkbeyKEKk7wLoeY3ED_ into /content/dataset/labels/val/37494_gustavo_fontana_08.txt...

  7%|▋         | 33/488 [01:17<16:54,  2.23s/it]

Done.
Downloading 16svuuiUIovx5zDluoC71o5eye_CVC1wC into /content/dataset/labels/val/37494_gustavo_fontana_10.txt...

  7%|▋         | 34/488 [01:19<16:39,  2.20s/it]

Done.
Downloading 1_36z3Wz6kaJnC4VpzSMQ2ZEOiUtWAgyi into /content/dataset/labels/val/37494_gustavo_fontana_12.txt...

  7%|▋         | 35/488 [01:22<16:58,  2.25s/it]

Done.
Downloading 1wJhmnCX1eFCglCs1nMWf0uPBR5L6qclJ into /content/dataset/labels/val/37494_gustavo_fontana_20.txt...

  7%|▋         | 36/488 [01:24<16:44,  2.22s/it]

Done.
Downloading 1aTkJ4yFufbJZx1hVOnMTHlC1kz98zRto into /content/dataset/labels/val/37494_gustavo_fontana_21.txt...

  8%|▊         | 37/488 [01:26<17:03,  2.27s/it]

Done.
Downloading 1U-QIxqS6qPCJTZdV24TKTZOknCSwfwNI into /content/dataset/labels/val/37494_gustavo_fontana_25.txt...

  8%|▊         | 38/488 [01:28<16:51,  2.25s/it]

Done.
Downloading 1bFlT_SgUuRjUKoXPSFde_MPQ2lU33fUW into /content/dataset/labels/val/37524_augusto_farias_02.txt...

  8%|▊         | 39/488 [01:31<16:53,  2.26s/it]

Done.
Downloading 1SO4iCi0B3__kYwd-PvDbEfX2c3xDA4a- into /content/dataset/labels/val/37524_augusto_farias_08.txt...

  8%|▊         | 40/488 [01:33<17:05,  2.29s/it]

Done.
Downloading 1GnQid-d62s7ZOvSXb5DNucYEG_-MYtMb into /content/dataset/labels/val/37524_augusto_farias_14.txt...

  8%|▊         | 41/488 [01:35<17:07,  2.30s/it]

Done.
Downloading 1eU6vS1sUtjiPauNUmL9BG_dNzIZABzjx into /content/dataset/labels/val/37524_augusto_farias_15.txt...

  9%|▊         | 42/488 [01:38<17:24,  2.34s/it]

Done.
Downloading 1MbrDGdXJsoh_zymjWg3-h1ZiilqE_rwq into /content/dataset/labels/val/3a32cc04e4d840bc441431183e08d018.txt...

  9%|▉         | 43/488 [01:40<17:21,  2.34s/it]

Done.
Downloading 1he92cUwR-7zAf68bQf0QahMBXSbop-di into /content/dataset/labels/val/3cbb052c7f4127313a34629e22f95f52.txt...

  9%|▉         | 44/488 [01:42<17:06,  2.31s/it]

Done.
Downloading 1rSG8lJ_i9BSts9OrDTMXgN0gjGQIYvwl into /content/dataset/labels/val/41932688_Simon_Revello_11.txt...

  9%|▉         | 45/488 [01:45<17:28,  2.37s/it]

Done.
Downloading 1yIKccARTNW3e-gjtoQth-iZ2Jtn_eEOd into /content/dataset/labels/val/41932688_Simon_Revello_13.txt...

  9%|▉         | 46/488 [01:47<17:12,  2.34s/it]

Done.
Downloading 1pv1hozuM_jxAiPEow7xzN_3Sty7EHGKB into /content/dataset/labels/val/41932688_Simon_Revello_16.txt...

 10%|▉         | 47/488 [01:49<16:49,  2.29s/it]

Done.
Downloading 1SOd_GW3GiY0zcPcv1G107baW1LqCz2uK into /content/dataset/labels/val/41932688_Simon_Revello_17.txt...

 10%|▉         | 48/488 [01:52<16:47,  2.29s/it]

Done.
Downloading 1FwEj2TKxHMS3fbbwpNggSPznYzVS4d1U into /content/dataset/labels/val/41932688_Simon_Revello_18.txt...

 10%|█         | 49/488 [01:54<17:14,  2.36s/it]

Done.
Downloading 1LzPxmSmY03_ndCJ3A_Q4OOraxmlwzyfo into /content/dataset/labels/val/41932688_Simon_Revello_26.txt...

 10%|█         | 50/488 [02:11<48:45,  6.68s/it]

Done.
Downloading 1MhMgpXnVhMJTUqG4OPJVEK9fXs2P7KfC into /content/dataset/labels/val/41932688_Simon_Revello_27.txt...

 10%|█         | 51/488 [02:13<39:07,  5.37s/it]

Done.
Downloading 1cjemjK3ZSVXm-w_1n8jpwtLE5pkIQB3A into /content/dataset/labels/val/41932688_Simon_Revello_3.txt...

 11%|█         | 52/488 [02:15<32:12,  4.43s/it]

Done.
Downloading 19b1yQ7_w8dL4UhRSeTYmmPzPobsU9I4U into /content/dataset/labels/val/41932688_Simon_Revello_6.txt...

 11%|█         | 53/488 [02:18<27:45,  3.83s/it]

Done.
Downloading 1JJ2z012Cacto94ajYyDpVmFsk12snjJJ into /content/dataset/labels/val/43237686_Constantino_Ferrucci_0.txt...

 11%|█         | 54/488 [02:21<25:28,  3.52s/it]

Done.
Downloading 1mqN0STTp5r0PGOV_6UqCFRf00WLz5ywr into /content/dataset/labels/val/43237686_Constantino_Ferrucci_10.txt...

 11%|█▏        | 55/488 [02:23<22:27,  3.11s/it]

Done.
Downloading 1Jvir5LT3-SgJUJyR0VLwUYIYBHoW4Z2Y into /content/dataset/labels/val/43237686_Constantino_Ferrucci_11.txt...

 11%|█▏        | 56/488 [02:25<20:15,  2.81s/it]

Done.
Downloading 1n-AaRxvL4ij0ReQlicNjpl3iY9LpC0ZR into /content/dataset/labels/val/43237686_Constantino_Ferrucci_15.txt...

 12%|█▏        | 57/488 [02:27<19:00,  2.65s/it]

Done.
Downloading 1i9xBp9plPi9kQwFu4gN_kK6aHYQ4_oQ1 into /content/dataset/labels/val/43237686_Constantino_Ferrucci_2.txt...

 12%|█▏        | 58/488 [02:29<18:08,  2.53s/it]

Done.
Downloading 1s8IJ-y-ZBFwxU-ccs5hE6SZWiubjy9aM into /content/dataset/labels/val/43237686_Constantino_Ferrucci_21.txt...

 12%|█▏        | 59/488 [02:32<18:18,  2.56s/it]

Done.
Downloading 1nl66V3wFx-2bT_BiuDgYgsfL2Nl2qr5a into /content/dataset/labels/val/43237686_Constantino_Ferrucci_23.txt...

 12%|█▏        | 60/488 [02:34<17:46,  2.49s/it]

Done.
Downloading 1vJgaelu3_n-xPWRwJmaf-KK9YccLUFD1 into /content/dataset/labels/val/43237686_Constantino_Ferrucci_25.txt...

 12%|█▎        | 61/488 [02:37<17:56,  2.52s/it]

Done.
Downloading 1WmzgSg3RxDT-tsbEExfnY-VfCxA6KIRt into /content/dataset/labels/val/43237686_Constantino_Ferrucci_29.txt...

 13%|█▎        | 62/488 [02:39<17:42,  2.49s/it]

Done.
Downloading 1RrgDgppaGbcfXskwnePAGaBXKcQxDLiF into /content/dataset/labels/val/43237686_Constantino_Ferrucci_30.txt...

 13%|█▎        | 63/488 [02:42<18:06,  2.56s/it]

Done.
Downloading 1y-xjo4pHktgeBWaYYLEmR0V-Wtm3pQa2 into /content/dataset/labels/val/43237686_Constantino_Ferrucci_31.txt...

 13%|█▎        | 64/488 [02:44<17:17,  2.45s/it]

Done.
Downloading 1K2l3DV5aj0XdBr0mAltY1CuuN-s95xaJ into /content/dataset/labels/val/43237686_Constantino_Ferrucci_8.txt...

 13%|█▎        | 65/488 [02:47<16:58,  2.41s/it]

Done.
Downloading 1YJs_ASLLaIAitaASOCrnmFBUhVn77Ohx into /content/dataset/labels/val/43265_Lucas_Demarre_01.txt...

 14%|█▎        | 66/488 [02:49<16:30,  2.35s/it]

Done.
Downloading 1CfJjHN7YUuEnynb9h7XbJVWB7E-0JIZk into /content/dataset/labels/val/43265_Lucas_Demarre_04.txt...

 14%|█▎        | 67/488 [02:51<16:21,  2.33s/it]

Done.
Downloading 1gOpX0Eej-geOpjaHR54rIFW6MSNgivzZ into /content/dataset/labels/val/43265_Lucas_Demarre_05.txt...

 14%|█▍        | 68/488 [02:53<15:55,  2.27s/it]

Done.
Downloading 1sGOTHLErdvi2D0IG9IOlUwxks3Z24eqZ into /content/dataset/labels/val/43265_Lucas_Demarre_07.txt...

 14%|█▍        | 69/488 [02:55<15:38,  2.24s/it]

Done.
Downloading 173sEYDBLlJmUib1fsDk3YjYAT6tuEW_V into /content/dataset/labels/val/43265_Lucas_Demarre_08.txt...

 14%|█▍        | 70/488 [02:58<16:51,  2.42s/it]

Done.
Downloading 1gyVd6FjTDslKZbwRfczuv59-58ZrWIMQ into /content/dataset/labels/val/43265_Lucas_Demarre_12.txt...

 15%|█▍        | 71/488 [03:01<16:59,  2.45s/it]

Done.
Downloading 1yt3kys-UWXV7G4zKqRUBxymo7_WX45Cm into /content/dataset/labels/val/43265_Lucas_Demarre_15.txt...

 15%|█▍        | 72/488 [03:04<17:33,  2.53s/it]

Done.
Downloading 1zla-PpaQApcByDIgFtLaRf7eExT90HWa into /content/dataset/labels/val/43265_Lucas_Demarre_19.txt...

 15%|█▍        | 73/488 [03:06<17:09,  2.48s/it]

Done.
Downloading 1DU_p04Sf4-pb0ZcVmdPStBZxKLkRrlES into /content/dataset/labels/val/43265_Lucas_Demarre_22.txt...

 15%|█▌        | 74/488 [03:08<16:46,  2.43s/it]

Done.
Downloading 1xo9SWuVfh4ftScqN8__Lv4N-lxbyrs0G into /content/dataset/labels/val/43265_Lucas_Demarre_27.txt...

 15%|█▌        | 75/488 [03:10<16:25,  2.39s/it]

Done.
Downloading 1z324Mnig7tqIjuz8ha4CWKcWxMsmk1kA into /content/dataset/labels/val/43265_Lucas_Demarre_29.txt...

 16%|█▌        | 76/488 [03:13<16:14,  2.36s/it]

Done.
Downloading 1mPjLgymok5F-9Wt4Odh13QEkgA7rlY-2 into /content/dataset/labels/val/43841031_Enzo_Ferrari_02.txt...

 16%|█▌        | 77/488 [03:15<15:39,  2.29s/it]

Done.
Downloading 11R9W4JQFViR-xpcKezpGXvzQ3Ax8nobe into /content/dataset/labels/val/43841031_Enzo_Ferrari_03.txt...

 16%|█▌        | 78/488 [03:17<16:04,  2.35s/it]

Done.
Downloading 1bCIGXWwHtC0DI4VwWVScK07nSaDu10Fp into /content/dataset/labels/val/43841031_Enzo_Ferrari_07.txt...

 16%|█▌        | 79/488 [03:20<15:31,  2.28s/it]

Done.
Downloading 1LYsq4QCHoSQ4kgilgDoRRwr5_SA8jFZz into /content/dataset/labels/val/43841031_Enzo_Ferrari_08.txt...

 16%|█▋        | 80/488 [03:22<15:00,  2.21s/it]

Done.
Downloading 1cbvyU4jzgs-Ea6PfCZhmericX7WNxfTG into /content/dataset/labels/val/43841031_Enzo_Ferrari_11.txt...

 17%|█▋        | 81/488 [03:24<15:19,  2.26s/it]

Done.
Downloading 1Rtm2YOcZ1LQ6azo3e9QWPaLa4fTLJofa into /content/dataset/labels/val/43841031_Enzo_Ferrari_12.txt...

 17%|█▋        | 82/488 [03:26<15:34,  2.30s/it]

Done.
Downloading 1Id_r3qmS6QU99oXzvTuP9KJXf2IVA9u0 into /content/dataset/labels/val/43841031_Enzo_Ferrari_14.txt...

 17%|█▋        | 83/488 [03:29<16:18,  2.41s/it]

Done.
Downloading 1Cz9VBGl_Djn0PhVgRQnk1ECzzep8gEYw into /content/dataset/labels/val/43841031_Enzo_Ferrari_22.txt...

 17%|█▋        | 84/488 [03:31<16:08,  2.40s/it]

Done.
Downloading 1lx_oX7HMY4UYLQDXgSqG_l_togr_KD-F into /content/dataset/labels/val/43841031_Enzo_Ferrari_23.txt...

 17%|█▋        | 85/488 [03:34<16:18,  2.43s/it]

Done.
Downloading 1Vm3_ARtu2RxSOVcBgMk87epIGcssWxDD into /content/dataset/labels/val/43841031_Enzo_Ferrari_24.txt...

 18%|█▊        | 86/488 [03:36<16:13,  2.42s/it]

Done.
Downloading 13oz3By85vh61JXM2NqWQcEZgVb4m1DoG into /content/dataset/labels/val/43841031_Enzo_Ferrari_26.txt...

 18%|█▊        | 87/488 [03:38<15:30,  2.32s/it]

Done.
Downloading 1L28Fd3YoGd2lXatN-59TKEdZd0xoGrRD into /content/dataset/labels/val/43841031_Enzo_Ferrari_29.txt...

 18%|█▊        | 88/488 [03:41<15:31,  2.33s/it]

Done.
Downloading 1HBsHdVyux1ZOF4YHNNKQ9vRF3EOjBfZJ into /content/dataset/labels/val/43841031_Enzo_Ferrari_34.txt...

 18%|█▊        | 89/488 [03:43<15:15,  2.29s/it]

Done.
Downloading 1WHHfTuOlq_1gRI5lZY55ubjiTc_WTKFq into /content/dataset/labels/val/43841031_Enzo_Ferrari_35.txt...

 18%|█▊        | 90/488 [03:45<15:40,  2.36s/it]

Done.
Downloading 18KvM7Uv7vPtzR7x8tag8sR4wBWU36sKg into /content/dataset/labels/val/43841031_Enzo_Ferrari_37.txt...

 19%|█▊        | 91/488 [03:48<15:19,  2.32s/it]

Done.
Downloading 1ZIEn3n9bsICP40HkpM5Qgyp-3FBS_Ry1 into /content/dataset/labels/val/43841031_Enzo_Ferrari_40.txt...

 19%|█▉        | 92/488 [03:50<14:59,  2.27s/it]

Done.
Downloading 14Hf8OD1qWxLSE5U7mJ6F1L4rgjNHLU-W into /content/dataset/labels/val/46019_taiel_raffaeli_01.txt...

 19%|█▉        | 93/488 [03:52<15:02,  2.28s/it]

Done.
Downloading 1tMryMZureCh_EdODJ811ytOerX9crF7e into /content/dataset/labels/val/46019_taiel_raffaeli_04.txt...

 19%|█▉        | 94/488 [03:54<14:43,  2.24s/it]

Done.
Downloading 1FmTmPiKk0LQDbzzHoBkh-V7u2Du7VvR4 into /content/dataset/labels/val/46019_taiel_raffaeli_05.txt...

 19%|█▉        | 95/488 [03:56<14:32,  2.22s/it]

Done.
Downloading 1E4_T_sl9gFWNB_gQQ7icR57UG9oOjeLE into /content/dataset/labels/val/46019_taiel_raffaeli_11.txt...

 20%|█▉        | 96/488 [03:59<14:12,  2.17s/it]

Done.
Downloading 1ZntS99lgFBQqkkZ2ffPtymU4cY0lSzP_ into /content/dataset/labels/val/46019_taiel_raffaeli_17.txt...

 20%|█▉        | 97/488 [04:01<14:16,  2.19s/it]

Done.
Downloading 1Dt0pLrZXrcLpr0D80lEsLEjq5a2dxlCW into /content/dataset/labels/val/46019_taiel_raffaeli_20.txt...

 20%|██        | 98/488 [04:03<14:30,  2.23s/it]

Done.
Downloading 148sQojm9V4D_Adm_uiSU52c2Jq3ACZC4 into /content/dataset/labels/val/46019_taiel_raffaeli_22.txt...

 20%|██        | 99/488 [04:05<14:31,  2.24s/it]

Done.
Downloading 1HSc43NRBSm1U2qNo1vpFRLiSgDIDMslN into /content/dataset/labels/val/46019_taiel_raffaeli_23.txt...

 20%|██        | 100/488 [04:08<14:39,  2.27s/it]

Done.
Downloading 1uRnNLL289zX1Q1SeEps-qeznUV8aQP6Y into /content/dataset/labels/val/46019_taiel_raffaeli_29.txt...

 21%|██        | 101/488 [04:10<14:22,  2.23s/it]

Done.
Downloading 1yCdDyiceG7Z79RZ3mvnqs11CIshWBagt into /content/dataset/labels/val/46019_taiel_raffaeli_31.txt...

 21%|██        | 102/488 [04:12<14:08,  2.20s/it]

Done.
Downloading 1dhqy5zqgkXCWA1Byu9-Bc8E3wl0qUmaS into /content/dataset/labels/val/46094_Mateo_Rovere_11.txt...

 21%|██        | 103/488 [04:15<15:23,  2.40s/it]

Done.
Downloading 1r1RdL-xzgZ5BjCprZ2z5Yhx6wRWaJpqN into /content/dataset/labels/val/46094_Mateo_Rovere_13.txt...

 21%|██▏       | 104/488 [04:17<14:51,  2.32s/it]

Done.
Downloading 1SMQ_K1RrCvZ2h1nyVCn5wrLNGuuTFr3J into /content/dataset/labels/val/46094_Mateo_Rovere_14.txt...

 22%|██▏       | 105/488 [04:19<14:55,  2.34s/it]

Done.
Downloading 1Dbs9jOl9dSC1dP2TgS8ZAe2Y7ZokVvu5 into /content/dataset/labels/val/46094_Mateo_Rovere_16.txt...

 22%|██▏       | 106/488 [04:22<14:54,  2.34s/it]

Done.
Downloading 1owKwZsveaHAyGJ5o2WfFlBa-n2CdMgya into /content/dataset/labels/val/46094_Mateo_Rovere_21.txt...

 22%|██▏       | 107/488 [04:24<14:43,  2.32s/it]

Done.
Downloading 1S6aaBnhq5-1fLWNBFLOi_1s6Nmr9xTML into /content/dataset/labels/val/46094_Mateo_Rovere_22.txt...

 22%|██▏       | 108/488 [04:26<14:44,  2.33s/it]

Done.
Downloading 11NmP-qJRLBYik15PwZV5eFuB0VbN1KkH into /content/dataset/labels/val/46094_Mateo_Rovere_23.txt...

 22%|██▏       | 109/488 [04:28<14:05,  2.23s/it]

Done.
Downloading 1fNFtglskELCmnpoP2ObieAuVTrs2_xR7 into /content/dataset/labels/val/46094_Mateo_Rovere_24.txt...

 23%|██▎       | 110/488 [04:31<14:07,  2.24s/it]

Done.
Downloading 100PwMI28ue1p4-IQaWMkhrFdTsGe5iOz into /content/dataset/labels/val/46094_Mateo_Rovere_25.txt...

 23%|██▎       | 111/488 [04:33<14:25,  2.29s/it]

Done.
Downloading 1j-Y-dK17rCjaWcDlf85j3EjHQ9DXr_cp into /content/dataset/labels/val/46094_Mateo_Rovere_29.txt...

 23%|██▎       | 112/488 [04:35<14:05,  2.25s/it]

Done.
Downloading 1SMErkkiYSp408L4JigJI1XzjeL8dvx6d into /content/dataset/labels/val/46094_Mateo_Rovere_30.txt...

 23%|██▎       | 113/488 [04:38<14:48,  2.37s/it]

Done.
Downloading 1GcNz-uXISTBa-PAg8GPzuquI1rPr6peD into /content/dataset/labels/val/46094_Mateo_Rovere_31.txt...

 23%|██▎       | 114/488 [04:40<14:03,  2.26s/it]

Done.
Downloading 1iQAsUWhAi2Hiy7FsEMILAYUvx5gOlfvd into /content/dataset/labels/val/46094_Mateo_Rovere_6.txt...

 24%|██▎       | 115/488 [04:42<14:09,  2.28s/it]

Done.
Downloading 1HeFZKjrue5YNGAXNFa_piE7hd_ZgC8OV into /content/dataset/labels/val/46094_Mateo_Rovere_7.txt...

 24%|██▍       | 116/488 [04:44<14:10,  2.29s/it]

Done.
Downloading 1L6Hxb6ZPY4FHDsCcAMF-El4lQwRZzH5c into /content/dataset/labels/val/46094_Mateo_Rovere_8.txt...

 24%|██▍       | 117/488 [04:47<14:08,  2.29s/it]

Done.
Downloading 1RfpJcTp9Xq1P8Kw4lUeRbnqknCEmilss into /content/dataset/labels/val/51659_antonio_peroni_01.txt...

 24%|██▍       | 118/488 [04:49<14:01,  2.27s/it]

Done.
Downloading 19a1qVhKwXAPtDmDmMAWFu38xPUIcqSCL into /content/dataset/labels/val/51659_antonio_peroni_04.txt...

 24%|██▍       | 119/488 [04:51<14:28,  2.35s/it]

Done.
Downloading 1nqqL9kXd62FXy6sot_Cv-lBsOUUnOujc into /content/dataset/labels/val/51659_antonio_peroni_10.txt...

 25%|██▍       | 120/488 [04:53<13:49,  2.25s/it]

Done.
Downloading 1ki7gRqqqlEEBymNlr9wqUKWCLW6fpYlN into /content/dataset/labels/val/51659_antonio_peroni_11.txt...

 25%|██▍       | 121/488 [04:56<13:52,  2.27s/it]

Done.
Downloading 1PwOrLnrEsv4Txx1e6EZiiLIyY7Ft_ABw into /content/dataset/labels/val/51659_antonio_peroni_12.txt...

 25%|██▌       | 122/488 [04:58<13:35,  2.23s/it]

Done.
Downloading 1BU9VrJfQMmfLyfRUCGzxDiv70gBxl8Re into /content/dataset/labels/val/51659_antonio_peroni_13.txt...

 25%|██▌       | 123/488 [05:00<13:27,  2.21s/it]

Done.
Downloading 1Jxy0diTBreYLSKTq6moWSLcoTlp6or_U into /content/dataset/labels/val/51659_antonio_peroni_24.txt...

 25%|██▌       | 124/488 [05:02<13:26,  2.21s/it]

Done.
Downloading 1tvztYhVK1ChFUyMdL5eUpr9R6PvELQXy into /content/dataset/labels/val/51659_antonio_peroni_28.txt...

 26%|██▌       | 125/488 [05:04<13:13,  2.19s/it]

Done.
Downloading 1Jx0CqgMjxk2OBd-9urVep75Uv6ddaOBk into /content/dataset/labels/val/51705_micaela_pozzo_05.txt...

 26%|██▌       | 126/488 [05:07<13:34,  2.25s/it]

Done.
Downloading 1jmhmwV79cSnVx9Y1ucffMLFYmP51zjj8 into /content/dataset/labels/val/51705_micaela_pozzo_08.txt...

 26%|██▌       | 127/488 [05:09<14:06,  2.35s/it]

Done.
Downloading 1TfdKxp_19z4JArSno2TXH4D8Esh4vekT into /content/dataset/labels/val/51705_micaela_pozzo_11.txt...

 26%|██▌       | 128/488 [05:11<13:29,  2.25s/it]

Done.
Downloading 1xyPtDZJzN4dHwHdrrKr32SRmawlzEloC into /content/dataset/labels/val/51705_micaela_pozzo_13.txt...

 26%|██▋       | 129/488 [05:14<13:53,  2.32s/it]

Done.
Downloading 1hufBZyhT3EzWXbXVC4KtEdOt41QKFqPa into /content/dataset/labels/val/51705_micaela_pozzo_15.txt...

 27%|██▋       | 130/488 [05:16<14:00,  2.35s/it]

Done.
Downloading 1AqZd7nYqaEZmznEWgEK3ynLC7o-Au-fQ into /content/dataset/labels/val/51705_micaela_pozzo_16.txt...

 27%|██▋       | 131/488 [05:19<13:52,  2.33s/it]

Done.
Downloading 17lw9jfJpY8P25WmEgk4e0sR_muT91b9J into /content/dataset/labels/val/51705_micaela_pozzo_20.txt...

 27%|██▋       | 132/488 [05:21<13:31,  2.28s/it]

Done.
Downloading 1cz792QKK8kW4rLeSUI-kA_yVA1wjHqF- into /content/dataset/labels/val/51705_micaela_pozzo_22.txt...

 27%|██▋       | 133/488 [05:23<13:54,  2.35s/it]

Done.
Downloading 1lNYSbZLxyVuZzPgzdxovQhbKnybK5UNA into /content/dataset/labels/val/51705_micaela_pozzo_23.txt...

 27%|██▋       | 134/488 [05:25<13:25,  2.27s/it]

Done.
Downloading 1POUYFUJv5dA_l4TgCKCs2fPC9lrI5CWJ into /content/dataset/labels/val/51705_micaela_pozzo_25.txt...

 28%|██▊       | 135/488 [05:27<12:50,  2.18s/it]

Done.
Downloading 1mhsbQjiE7Zm9u7_9qJFvBG21zzTmBZrD into /content/dataset/labels/val/51705_micaela_pozzo_27.txt...

 28%|██▊       | 136/488 [05:29<12:31,  2.14s/it]

Done.
Downloading 1_hTHdHHDK4dRLJwUoIAiMYkgIoZyvSzj into /content/dataset/labels/val/51705_micaela_pozzo_28.txt...

 28%|██▊       | 137/488 [05:32<13:28,  2.30s/it]

Done.
Downloading 1DZkksB6kFFxKQ5-axkP8jNNza93BQOVl into /content/dataset/labels/val/51705_micaela_pozzo_29.txt...

 28%|██▊       | 138/488 [05:34<12:59,  2.23s/it]

Done.
Downloading 1CrrFP0YvPcjA6ZAGm8tnOPWryvOm8Ohf into /content/dataset/labels/val/51934_pablo_pistelli_01.txt...

 28%|██▊       | 139/488 [05:37<13:20,  2.29s/it]

Done.
Downloading 1dVMBo7aYzDCRuPsUu9Hkv1VqWmKc7Ar7 into /content/dataset/labels/val/51934_pablo_pistelli_02.txt...

 29%|██▊       | 140/488 [05:39<13:44,  2.37s/it]

Done.
Downloading 1rdMddCOVn44m515yCu_ReEIhlhtUa5U2 into /content/dataset/labels/val/51934_pablo_pistelli_07.txt...

 29%|██▉       | 141/488 [05:41<13:43,  2.37s/it]

Done.
Downloading 163cfFjfi3xqDQlb0ak0zyUElnNCv6oRT into /content/dataset/labels/val/51934_pablo_pistelli_08.txt...

 29%|██▉       | 142/488 [05:44<13:37,  2.36s/it]

Done.
Downloading 1t__-uZ-PXxqc1_9BRuN_PCp0BunqvvtC into /content/dataset/labels/val/51934_pablo_pistelli_19.txt...

 29%|██▉       | 143/488 [05:46<13:27,  2.34s/it]

Done.
Downloading 1Z3dYNczkblTGCW9roN49WmahjNK3rmnY into /content/dataset/labels/val/51934_pablo_pistelli_20.txt...

 30%|██▉       | 144/488 [05:49<13:36,  2.37s/it]

Done.
Downloading 1RP9FnQm-DgnygkD6jW6M_dQuofFeyFGw into /content/dataset/labels/val/51934_pablo_pistelli_22.txt...

 30%|██▉       | 145/488 [05:51<13:21,  2.34s/it]

Done.
Downloading 1QZK9-3EoGnNMj8Nu9qBz73asX6aUkibL into /content/dataset/labels/val/51951_pablo_pistarelli_11.txt...

 30%|██▉       | 146/488 [05:53<13:41,  2.40s/it]

Done.
Downloading 1hTqK9O38d2FwXTsas3IRM0BAoq1uvJej into /content/dataset/labels/val/51951_pablo_pistarelli_13.txt...

 30%|███       | 147/488 [05:56<13:31,  2.38s/it]

Done.
Downloading 19bRmuS-KRE6WhGwfiD_ln0tHro5WycAl into /content/dataset/labels/val/51951_pablo_pistarelli_17.txt...

 30%|███       | 148/488 [05:58<13:57,  2.46s/it]

Done.
Downloading 10yyz61oU30jP_tXjxtWTJcLWDsw1USHa into /content/dataset/labels/val/51951_pablo_pistarelli_20.txt...

 31%|███       | 149/488 [06:01<14:32,  2.57s/it]

Done.
Downloading 1GMsu4eLnSlR7UAMsvCD7JUpWDw3373SG into /content/dataset/labels/val/51951_pablo_pistarelli_27.txt...

 31%|███       | 150/488 [06:04<14:16,  2.53s/it]

Done.
Downloading 1nwkV6Q73Av3ebfpdIIoQMYgSD0dtsny2 into /content/dataset/labels/val/51951_pablo_pistarelli_28.txt...

 31%|███       | 151/488 [06:06<13:33,  2.41s/it]

Done.
Downloading 1EZkalUjaLVnlr6QcFjMV6jMxXjF6PATu into /content/dataset/labels/val/51951_pablo_pistarelli_30.txt...

 31%|███       | 152/488 [06:08<13:29,  2.41s/it]

Done.
Downloading 16bOwbazLCgVw763wwPskMBlZnYWp4Z_s into /content/dataset/labels/val/51d4e6083f4c60354fefe46c455ab94a.txt...

 31%|███▏      | 153/488 [06:10<12:54,  2.31s/it]

Done.
Downloading 1AwDYZG5C65pX7pjKWhX5pjZ7Ol08pV6O into /content/dataset/labels/val/5214ca56851221cb34ae7f58d4923a40.txt...

 32%|███▏      | 154/488 [06:12<12:24,  2.23s/it]

Done.
Downloading 1cqGAD7GCzzFzS0hnR_RtJ0rhu6g1xBMF into /content/dataset/labels/val/52256_daniel_ponce_02.txt...

 32%|███▏      | 155/488 [06:15<13:15,  2.39s/it]

Done.
Downloading 1HR_xwElQSuoqxWq57EhWaCXm2yTRCXa7 into /content/dataset/labels/val/52256_daniel_ponce_03.txt...

 32%|███▏      | 156/488 [06:18<13:29,  2.44s/it]

Done.
Downloading 1rIa4Mb_YWU1TPRGgSYyZ2VJjn4uvsBFc into /content/dataset/labels/val/52256_daniel_ponce_10.txt...

 32%|███▏      | 157/488 [06:20<13:56,  2.53s/it]

Done.
Downloading 1vm5iTU1YbYlW7q-UQa37IAjMv-Fle5AF into /content/dataset/labels/val/52256_daniel_ponce_11.txt...

 32%|███▏      | 158/488 [06:23<14:13,  2.59s/it]

Done.
Downloading 1E4t3zdCB3r4h04-IdsgCgzYl9rCzZAcu into /content/dataset/labels/val/52256_daniel_ponce_12.txt...

 33%|███▎      | 159/488 [06:25<13:44,  2.51s/it]

Done.
Downloading 1gPHMU1Aq7SQS4W73Q8CSWASjv-cga6rY into /content/dataset/labels/val/52256_daniel_ponce_14.txt...

 33%|███▎      | 160/488 [06:28<14:00,  2.56s/it]

Done.
Downloading 1fFKcD9v-JYzN5mCS5WwBxFwz6zzMVvkH into /content/dataset/labels/val/52256_daniel_ponce_17.txt...

 33%|███▎      | 161/488 [06:31<13:51,  2.54s/it]

Done.
Downloading 156bIOhloGdFWNGX00f9qG78ozQ3wSXn9 into /content/dataset/labels/val/52256_daniel_ponce_23.txt...

 33%|███▎      | 162/488 [06:33<13:16,  2.44s/it]

Done.
Downloading 1JN8STRX08bR2pnW3Lsd_IDUWa1QSyyfY into /content/dataset/labels/val/52256_daniel_ponce_30.txt...

 33%|███▎      | 163/488 [06:35<12:57,  2.39s/it]

Done.
Downloading 1Pir2fP7WH4yJTM5mgi69ZmOuEDInAspV into /content/dataset/labels/val/52256_daniel_ponce_31.txt...

 34%|███▎      | 164/488 [06:37<12:40,  2.35s/it]

Done.
Downloading 1FHC6ejqV8h6FclF8EwNovBrxn2lyvOUE into /content/dataset/labels/val/57096_ramiro_sagrera_03.txt...

 34%|███▍      | 165/488 [06:40<13:00,  2.41s/it]

Done.
Downloading 1FjMlScJUDhWEB_7NamRfy-NYqsQFOIoR into /content/dataset/labels/val/57096_ramiro_sagrera_07.txt...

 34%|███▍      | 166/488 [06:42<12:44,  2.38s/it]

Done.
Downloading 1C2oy3T-P1yDzDWXkyGtE77yYNeDRf-LU into /content/dataset/labels/val/57096_ramiro_sagrera_11.txt...

 34%|███▍      | 167/488 [06:44<12:37,  2.36s/it]

Done.
Downloading 1hd_zBSs55o0zsAkCRhMr_FPX8xcLOFta into /content/dataset/labels/val/57096_ramiro_sagrera_13.txt...

 34%|███▍      | 168/488 [06:47<12:33,  2.35s/it]

Done.
Downloading 13QIhm_O-FHNkQzJpUi0qe4CkM0I0Amfy into /content/dataset/labels/val/57096_ramiro_sagrera_14.txt...

 35%|███▍      | 169/488 [06:49<12:18,  2.32s/it]

Done.
Downloading 1XOPesCaf68xa92NbdvB0Qqjy32wrCQfk into /content/dataset/labels/val/57096_ramiro_sagrera_15.txt...

 35%|███▍      | 170/488 [06:51<12:03,  2.27s/it]

Done.
Downloading 1rCsZj9LmWNCLe0xUUrT3rKtr9VsvjEg6 into /content/dataset/labels/val/57096_ramiro_sagrera_17.txt...

 35%|███▌      | 171/488 [06:53<12:02,  2.28s/it]

Done.
Downloading 1TrPJVJ9FgqD42odzB3irHJFHB_fwd1dV into /content/dataset/labels/val/57096_ramiro_sagrera_19.txt...

 35%|███▌      | 172/488 [06:56<12:29,  2.37s/it]

Done.
Downloading 1ci3YND6SKzeTCoFos0D_0TCBkLYYVeUv into /content/dataset/labels/val/57096_ramiro_sagrera_20.txt...

 35%|███▌      | 173/488 [06:58<12:12,  2.32s/it]

Done.
Downloading 1w6snQN-aVXWvmmQT56-s0U37RSxCgfKn into /content/dataset/labels/val/57096_ramiro_sagrera_23.txt...

 36%|███▌      | 174/488 [07:00<11:46,  2.25s/it]

Done.
Downloading 1mUd9-Ydv3qUdY6sMMvgDx12mHyZbkK6d into /content/dataset/labels/val/57096_ramiro_sagrera_28.txt...

 36%|███▌      | 175/488 [07:03<11:33,  2.22s/it]

Done.
Downloading 1gqjOlwuxYKvQlW9XqyuZ3zmHFevDC5KF into /content/dataset/labels/val/58491_fabio_giampaoli_03.txt...

 36%|███▌      | 176/488 [07:05<11:34,  2.22s/it]

Done.
Downloading 1WkZ2Wv63L5HHOY8YbPbSimVJITxlMRht into /content/dataset/labels/val/58491_fabio_giampaoli_06.txt...

 36%|███▋      | 177/488 [07:07<11:14,  2.17s/it]

Done.
Downloading 1vzp30BDd9JM7nu8WGTQ4nPlSN4-ctfFi into /content/dataset/labels/val/58491_fabio_giampaoli_07.txt...

 36%|███▋      | 178/488 [07:09<11:50,  2.29s/it]

Done.
Downloading 1hrHfZRzuYDxwJcvTIg5bJE1mZ-DK5gSD into /content/dataset/labels/val/58491_fabio_giampaoli_09.txt...

 37%|███▋      | 179/488 [07:12<11:50,  2.30s/it]

Done.
Downloading 1WRNjkOPHxBYMNwa0P2VS7VRTYtUQ4pvb into /content/dataset/labels/val/58491_fabio_giampaoli_10.txt...

 37%|███▋      | 180/488 [07:14<11:42,  2.28s/it]

Done.
Downloading 1zeY6i3_E1cBHtTdEnoMugrVDYaSonTRJ into /content/dataset/labels/val/58491_fabio_giampaoli_15.txt...

 37%|███▋      | 181/488 [07:16<11:43,  2.29s/it]

Done.
Downloading 1XwL2UxQnQLRLX-wuZXwGOMyuaIYzBPin into /content/dataset/labels/val/58491_fabio_giampaoli_16.txt...

 37%|███▋      | 182/488 [07:19<11:48,  2.31s/it]

Done.
Downloading 1Cb9dwHdY_7Qq25B-wlzVLuL8xONNc3Y- into /content/dataset/labels/val/58491_fabio_giampaoli_22.txt...

 38%|███▊      | 183/488 [07:21<11:20,  2.23s/it]

Done.
Downloading 1ByIubIr5IumvkbFOb_uRW6ko5wDrfbSa into /content/dataset/labels/val/58491_fabio_giampaoli_25.txt...

 38%|███▊      | 184/488 [07:23<11:53,  2.35s/it]

Done.
Downloading 1E5eMGZwY_7wex5FHoKDBqb1NxVcWNtZb into /content/dataset/labels/val/58513_isaias_garay_01.txt...

 38%|███▊      | 185/488 [07:26<12:28,  2.47s/it]

Done.
Downloading 108oxeqIRjVbk9lC106tnUm8SVPXqU_46 into /content/dataset/labels/val/58513_isaias_garay_08.txt...

 38%|███▊      | 186/488 [07:29<12:35,  2.50s/it]

Done.
Downloading 1cb4II3Uw4zWbWm74aQntuY6A7BphljL9 into /content/dataset/labels/val/58513_isaias_garay_09.txt...

 38%|███▊      | 187/488 [07:31<11:52,  2.37s/it]

Done.
Downloading 1d1sQ6JrOkJNnAQayH_yKTVyiObibuPBv into /content/dataset/labels/val/58513_isaias_garay_13.txt...

 39%|███▊      | 188/488 [07:33<11:26,  2.29s/it]

Done.
Downloading 1cdANkSatLEFqYY1jOWaXinrDbUHBWUnn into /content/dataset/labels/val/58513_isaias_garay_14.txt...

 39%|███▊      | 189/488 [07:35<11:32,  2.32s/it]

Done.
Downloading 1iFx5ZJGHnP3u8yqXBn2cGLCG6gb3tqWJ into /content/dataset/labels/val/58513_isaias_garay_16.txt...

 39%|███▉      | 190/488 [07:38<12:01,  2.42s/it]

Done.
Downloading 1k1C3sKVQVfYrM-glAgMDvnKfHuLHYDz5 into /content/dataset/labels/val/58513_isaias_garay_21.txt...

 39%|███▉      | 191/488 [07:40<12:08,  2.45s/it]

Done.
Downloading 1wrwvbZwPawAfH68548Nx_1b60EaiWMfn into /content/dataset/labels/val/58513_isaias_garay_22.txt...

 39%|███▉      | 192/488 [07:43<11:57,  2.42s/it]

Done.
Downloading 1bD-_v8qSQWpruuD05an8II2UIWTK3fq2 into /content/dataset/labels/val/58513_isaias_garay_23.txt...

 40%|███▉      | 193/488 [07:45<11:53,  2.42s/it]

Done.
Downloading 1_cXuPqAwz0ekMW0nyl_UheRThWt2jsPn into /content/dataset/labels/val/58513_isaias_garay_24.txt...

 40%|███▉      | 194/488 [07:47<11:17,  2.30s/it]

Done.
Downloading 1Tut69J-XZTZEV5mIUVHKS_Ae_buYSl7q into /content/dataset/labels/val/58513_isaias_garay_27.txt...

 40%|███▉      | 195/488 [07:49<11:19,  2.32s/it]

Done.
Downloading 1UV6HUwgpgqPX0BLs2btTOygG46tYfgK1 into /content/dataset/labels/val/58912_Timoteo_Garcia_10.txt...

 40%|████      | 196/488 [07:52<11:11,  2.30s/it]

Done.
Downloading 1aEsQqVcrmaplHTUDwSayHps6Co72D0PT into /content/dataset/labels/val/58912_Timoteo_Garcia_13.txt...

 40%|████      | 197/488 [07:54<11:00,  2.27s/it]

Done.
Downloading 18Ss69EwfbN1EVOKJzpGwgRiT5-VY2AcR into /content/dataset/labels/val/58912_Timoteo_Garcia_14.txt...

 41%|████      | 198/488 [07:56<10:48,  2.24s/it]

Done.
Downloading 1NW9gKjtsRqQXD6f8CTS5QBVBo-4uMDyN into /content/dataset/labels/val/58912_Timoteo_Garcia_16.txt...

 41%|████      | 199/488 [07:58<10:27,  2.17s/it]

Done.
Downloading 1qOGXeuMTkXC6gAhge-6qCzfs8etchdnz into /content/dataset/labels/val/58912_Timoteo_Garcia_17.txt...

 41%|████      | 200/488 [08:01<11:12,  2.34s/it]

Done.
Downloading 1g8wPizWyTZ4MzOtBP3JXz2k8j1cmVCgY into /content/dataset/labels/val/58912_Timoteo_Garcia_18.txt...

 41%|████      | 201/488 [08:03<10:59,  2.30s/it]

Done.
Downloading 1AEO7TT2bv_ZTDkFYuqJ31hWMR16d8Lkr into /content/dataset/labels/val/58912_Timoteo_Garcia_2.txt...

 41%|████▏     | 202/488 [08:05<10:41,  2.24s/it]

Done.
Downloading 1SF8dFbT01Icq1D9dHcz_sq8-M-I8ncDG into /content/dataset/labels/val/58912_Timoteo_Garcia_20.txt...

 42%|████▏     | 203/488 [08:07<10:36,  2.23s/it]

Done.
Downloading 1047yqq8ivmqpJZKBg3u2My4pf81BF1bS into /content/dataset/labels/val/58912_Timoteo_Garcia_21.txt...

 42%|████▏     | 204/488 [08:10<10:46,  2.28s/it]

Done.
Downloading 1zCGvrDpdzfWq9f6rdB0TckGPY-_s4dLd into /content/dataset/labels/val/58912_Timoteo_Garcia_22.txt...

 42%|████▏     | 205/488 [08:12<10:45,  2.28s/it]

Done.
Downloading 1rTZVBDVaRH_Jc0MsBWFW8USi6IBE2rlZ into /content/dataset/labels/val/58912_Timoteo_Garcia_23.txt...

 42%|████▏     | 206/488 [08:14<10:44,  2.28s/it]

Done.
Downloading 1B0QQf40bFO-cG2_kga0PY_EnwLGQ8387 into /content/dataset/labels/val/58912_Timoteo_Garcia_28.txt...

 42%|████▏     | 207/488 [08:16<10:18,  2.20s/it]

Done.
Downloading 15RbkGxX6Dy7VOE03BbgX4feSUqodv-aX into /content/dataset/labels/val/58912_Timoteo_Garcia_3.txt...

 43%|████▎     | 208/488 [08:19<10:17,  2.21s/it]

Done.
Downloading 1VWKQHm8o6nxtCkrzi2xaiTCxGXVtDFSn into /content/dataset/labels/val/58912_Timoteo_Garcia_30.txt...

 43%|████▎     | 209/488 [08:21<10:27,  2.25s/it]

Done.
Downloading 1AcZpLURPbCyDpOxZPkIK-Lf_NrhVkw_O into /content/dataset/labels/val/58912_Timoteo_Garcia_32.txt...

 43%|████▎     | 210/488 [08:23<10:19,  2.23s/it]

Done.
Downloading 1DkldsSgkcimS5AyYArNj6W86GaF7rXD0 into /content/dataset/labels/val/58912_Timoteo_Garcia_6.txt...

 43%|████▎     | 211/488 [08:25<10:20,  2.24s/it]

Done.
Downloading 1g3kNLuycIP0YSuYvi_aGGvGJwok9AeEi into /content/dataset/labels/val/61681e0eaca430f089295c5bba12a235.txt...

 43%|████▎     | 212/488 [08:27<10:03,  2.19s/it]

Done.
Downloading 1NlrQEVNy1wtzLhSKoBpBMZgFs4ZMFnzA into /content/dataset/labels/val/64191_Sofia_BrizuelaCipolletti_04.txt...

 44%|████▎     | 213/488 [08:30<10:07,  2.21s/it]

Done.
Downloading 12FCXUpd5mRjQUH8HFIdwI1BXgbIhXbJc into /content/dataset/labels/val/64191_Sofia_BrizuelaCipolletti_05.txt...

 44%|████▍     | 214/488 [08:32<10:04,  2.21s/it]

Done.
Downloading 1ldoKefd_S2ljhkx_v94greQWvfD_Efou into /content/dataset/labels/val/64191_Sofia_BrizuelaCipolletti_06.txt...

 44%|████▍     | 215/488 [08:35<10:37,  2.33s/it]

Done.
Downloading 1H_661TllSBoDAtSaB2Kw2uUv6Pye1gLy into /content/dataset/labels/val/64191_Sofia_BrizuelaCipolletti_15.txt...

 44%|████▍     | 216/488 [08:37<10:57,  2.42s/it]

Done.
Downloading 1uhOoHTwMYjRutoi5f8eIpMV2SbDmbA0d into /content/dataset/labels/val/64191_Sofia_BrizuelaCipolletti_19.txt...

 44%|████▍     | 217/488 [08:39<10:22,  2.30s/it]

Done.
Downloading 1m2ARQtVPt5r5Ixrjog6tgi6JQX6zaxT5 into /content/dataset/labels/val/64191_Sofia_BrizuelaCipolletti_23.txt...

 45%|████▍     | 218/488 [08:42<10:59,  2.44s/it]

Done.
Downloading 1YZOk0wNok7fQCjUgxcNy4kVhKLzkH49h into /content/dataset/labels/val/64191_Sofia_BrizuelaCipolletti_24.txt...

 45%|████▍     | 219/488 [08:44<10:32,  2.35s/it]

Done.
Downloading 1_41plOOqUxvi2MKaVNcgR_zITNjiPjP4 into /content/dataset/labels/val/64191_Sofia_BrizuelaCipolletti_25.txt...

 45%|████▌     | 220/488 [08:46<10:13,  2.29s/it]

Done.
Downloading 11q1mGQGjud2DM9Qi2CQv1BCWXlaIc2-G into /content/dataset/labels/val/64191_Sofia_BrizuelaCipolletti_29.txt...

 45%|████▌     | 221/488 [08:49<10:41,  2.40s/it]

Done.
Downloading 1K8VOu9m-NDHGg21jZz9wa_6ZzJe0SgQv into /content/dataset/labels/val/6a137287bf186304e7922858046bba94.txt...

 45%|████▌     | 222/488 [08:51<10:34,  2.39s/it]

Done.
Downloading 1kordkP7xqAcQxLv6_RigZHp6ImALEm3F into /content/dataset/labels/val/6fdccd771fffdc43851975ed788e0bed.txt...

 46%|████▌     | 223/488 [08:54<10:40,  2.42s/it]

Done.
Downloading 10uHDcfCbiAhuUhMwmExee-V_zVOOWEsR into /content/dataset/labels/val/7051717faaa066ce59778c412b3c232d.txt...

 46%|████▌     | 224/488 [08:56<10:47,  2.45s/it]

Done.
Downloading 1-L0efDbRJSvvr3yFbSP9XD5_-4UPD7DL into /content/dataset/labels/val/71846_Brisa_Menescaldi_02.txt...

 46%|████▌     | 225/488 [08:59<10:51,  2.48s/it]

Done.
Downloading 17uSlE_KI0_k5dmKbbgNTMmbTwSLvH9NO into /content/dataset/labels/val/71846_Brisa_Menescaldi_12.txt...

 46%|████▋     | 226/488 [09:01<10:28,  2.40s/it]

Done.
Downloading 1G9jbvbolFQk9yvF3cQQ9m0klWUgSJXfI into /content/dataset/labels/val/71846_Brisa_Menescaldi_13.txt...

 47%|████▋     | 227/488 [09:03<10:08,  2.33s/it]

Done.
Downloading 1ZlMik3NZq70tscs-pwwxw1HpT22pmbIh into /content/dataset/labels/val/71846_Brisa_Menescaldi_21.txt...

 47%|████▋     | 228/488 [09:06<10:10,  2.35s/it]

Done.
Downloading 1Oy8JHec307W99_0m0xcC7x9_do4yO7u3 into /content/dataset/labels/val/71846_Brisa_Menescaldi_24.txt...

 47%|████▋     | 229/488 [09:08<10:10,  2.36s/it]

Done.
Downloading 1Ceq-ZI-FydVULPALkxOE3JHsVF8a66AV into /content/dataset/labels/val/71846_Brisa_Menescaldi_27.txt...

 47%|████▋     | 230/488 [09:10<10:07,  2.35s/it]

Done.
Downloading 1kG-GLMlDN_uzaKry2h9Wn7YnEGLw3V50 into /content/dataset/labels/val/71846_Brisa_Menescaldi_31.txt...

 47%|████▋     | 231/488 [09:13<09:58,  2.33s/it]

Done.
Downloading 1WsvPcYwNYOr4zKq50wcARZyxNMaBYj4b into /content/dataset/labels/val/72125_miguel_mussi_03.txt...

 48%|████▊     | 232/488 [09:15<10:05,  2.37s/it]

Done.
Downloading 1p29QcBDgUIsjdewJMF_zKF8mjL9UcRNO into /content/dataset/labels/val/72125_miguel_mussi_04.txt...

 48%|████▊     | 233/488 [09:18<10:21,  2.44s/it]

Done.
Downloading 1KMPoq0ClEdRvuJZWERLwuiDwS460XB0W into /content/dataset/labels/val/72125_miguel_mussi_10.txt...

 48%|████▊     | 234/488 [09:20<10:02,  2.37s/it]

Done.
Downloading 1Bouu8HNt6z_bOJhLRqpuO51aZxPKXor5 into /content/dataset/labels/val/72125_miguel_mussi_11.txt...

 48%|████▊     | 235/488 [09:22<10:00,  2.37s/it]

Done.
Downloading 1SA90VMMPAWFpfV16iJYtQPEWNiZGNkQW into /content/dataset/labels/val/72125_miguel_mussi_13.txt...

 48%|████▊     | 236/488 [09:25<09:56,  2.37s/it]

Done.
Downloading 1mjnSbfE1eJ7jb5a_-U1AoaBRXaEUAqAK into /content/dataset/labels/val/72125_miguel_mussi_25.txt...

 49%|████▊     | 237/488 [09:28<10:40,  2.55s/it]

Done.
Downloading 1qFID9Fxns0EgNpoJzxZAqDGdAJrIYU3q into /content/dataset/labels/val/72125_miguel_mussi_30.txt...

 49%|████▉     | 238/488 [09:30<10:24,  2.50s/it]

Done.
Downloading 1X296tXbPI9_KRstgEWyFEbv1xTfRSKfT into /content/dataset/labels/val/72125_miguel_mussi_33.txt...

 49%|████▉     | 239/488 [09:32<10:10,  2.45s/it]

Done.
Downloading 1_kzeMN9I4TyNmftLaRdIuMLUbIo-BMT6 into /content/dataset/labels/val/756892fc5ee5de3db6e901f40f106937.txt...

 49%|████▉     | 240/488 [09:35<10:03,  2.43s/it]

Done.
Downloading 1SX5t7q2J2bR6t6Jpsuf0tUljAbntDQhh into /content/dataset/labels/val/7bf69174b70a74f09bef25b228731ef8.txt...

 49%|████▉     | 241/488 [09:37<10:01,  2.44s/it]

Done.
Downloading 1oLzjqT1Q2F25wVAOGuNMSN-rONAH5ks9 into /content/dataset/labels/val/8cae59752e66a9fba867409af4ba39c3.txt...

 50%|████▉     | 242/488 [09:39<09:45,  2.38s/it]

Done.
Downloading 1gFO5cDnRsIQPd1xsUyz0uUcgujaI2BSJ into /content/dataset/labels/val/8d0247b8948900db41f51c0145b149cb.txt...

 50%|████▉     | 243/488 [09:42<10:11,  2.50s/it]

Done.
Downloading 1YeyrMIjxKpo9OTvpBqShReWPnkxdpkpA into /content/dataset/labels/val/948c12fe82cdcf22cb7b1e2cd0e24ab8.txt...

 50%|█████     | 244/488 [09:44<09:48,  2.41s/it]

Done.
Downloading 1knBvJWxyLgy3g1-GdDosaOnHpE6WE0G9 into /content/dataset/labels/val/952dd7f9eb8b5068796db0410ade8a41.txt...

 50%|█████     | 245/488 [09:47<09:55,  2.45s/it]

Done.
Downloading 1ZFn4aEH3s9lQ9xu_SL90v0p6k985dS1- into /content/dataset/labels/val/966c6a6d6d291047dcd64c692789e432.txt...

 50%|█████     | 246/488 [09:49<09:40,  2.40s/it]

Done.
Downloading 1yz3N5vIr_yVq5lQsnKYGtzLZoDqqJb8u into /content/dataset/labels/val/A45161_Fabian_Aguirre_04.txt...

 51%|█████     | 247/488 [09:52<09:35,  2.39s/it]

Done.
Downloading 1UKjjZd7EQhBRvTNO24aloYetoLcF6sb_ into /content/dataset/labels/val/A45161_Fabian_Aguirre_09.txt...

 51%|█████     | 248/488 [09:54<09:21,  2.34s/it]

Done.
Downloading 1Cm8ALCHClQZ30bRDJGCeu1KrcDXdGgn1 into /content/dataset/labels/val/A45161_Fabian_Aguirre_13.txt...

 51%|█████     | 249/488 [09:56<09:37,  2.41s/it]

Done.
Downloading 1yZUKp0ocVi-_RkD5PmWDPrmhVJczP4pN into /content/dataset/labels/val/A45161_Fabian_Aguirre_14.txt...

 51%|█████     | 250/488 [09:59<09:27,  2.38s/it]

Done.
Downloading 1pG5Yb7BdwUnNM4r2QBmPzvMnSUFuO7p6 into /content/dataset/labels/val/A45161_Fabian_Aguirre_17.txt...

 51%|█████▏    | 251/488 [10:01<09:13,  2.33s/it]

Done.
Downloading 1tcbsT_qMdJeLaLZFqyiHWnQ4yTJZgEJv into /content/dataset/labels/val/A45161_Fabian_Aguirre_18.txt...

 52%|█████▏    | 252/488 [10:03<09:11,  2.34s/it]

Done.
Downloading 1jY24_Oe0bzJBZ4yDaKbNpwDv4D6fjFPq into /content/dataset/labels/val/A45161_Fabian_Aguirre_19.txt...

 52%|█████▏    | 253/488 [10:06<09:22,  2.39s/it]

Done.
Downloading 1LMoI1if4h1GyWJcqUmH945HgcRUyvkoJ into /content/dataset/labels/val/A45161_Fabian_Aguirre_24.txt...

 52%|█████▏    | 254/488 [10:08<08:55,  2.29s/it]

Done.
Downloading 16B3YqLx2zRdFEVqNTlYGrT8M-edZIXUb into /content/dataset/labels/val/A45161_Fabian_Aguirre_30.txt...

 52%|█████▏    | 255/488 [10:10<08:40,  2.23s/it]

Done.
Downloading 1zYqaHFtBfSIEFXdulp3bMPJun6Jr67a6 into /content/dataset/labels/val/F37605_florencia_fernandez_04.txt...

 52%|█████▏    | 256/488 [10:12<08:37,  2.23s/it]

Done.
Downloading 1ievfpeSnKbl3ycb6wm3E16hPeyBmYtGH into /content/dataset/labels/val/F37605_florencia_fernandez_07.txt...

 53%|█████▎    | 257/488 [10:14<08:40,  2.26s/it]

Done.
Downloading 1W0PpCW0nfiO_2mD1fsDrUs1w0AAXQV8h into /content/dataset/labels/val/F37605_florencia_fernandez_08.txt...

 53%|█████▎    | 258/488 [10:17<08:28,  2.21s/it]

Done.
Downloading 1oooeaF74aLYRhC5iyYyEp-d72gdRsuo5 into /content/dataset/labels/val/F37605_florencia_fernandez_09.txt...

 53%|█████▎    | 259/488 [10:19<08:28,  2.22s/it]

Done.
Downloading 1Yenopx_PPjiJ5eWz6uiNvRdzvTtKHeJn into /content/dataset/labels/val/F37605_florencia_fernandez_10.txt...

 53%|█████▎    | 260/488 [10:21<08:46,  2.31s/it]

Done.
Downloading 1jrZZVcs3bi0YsfXoCX_0i--Vo8TnKQw_ into /content/dataset/labels/val/F37605_florencia_fernandez_11.txt...

 53%|█████▎    | 261/488 [10:24<09:05,  2.40s/it]

Done.
Downloading 1PWG5ziMGKIIBmWwMNRprZT8CamaAwQnF into /content/dataset/labels/val/F37605_florencia_fernandez_13.txt...

 54%|█████▎    | 262/488 [10:26<08:43,  2.32s/it]

Done.
Downloading 1NV_XelwiWGfEtzophpC1YBCY0u7UGNX- into /content/dataset/labels/val/F37605_florencia_fernandez_14.txt...

 54%|█████▍    | 263/488 [10:28<08:25,  2.25s/it]

Done.
Downloading 1vIzbJmrEKU_cZwiuG2J6RYQ01iwqrY5n into /content/dataset/labels/val/F37605_florencia_fernandez_17.txt...

 54%|█████▍    | 264/488 [10:31<08:39,  2.32s/it]

Done.
Downloading 1NelX1MydP2mWeAOKXoeZtnrO05rIFO3C into /content/dataset/labels/val/F37605_florencia_fernandez_19.txt...

 54%|█████▍    | 265/488 [10:33<08:46,  2.36s/it]

Done.
Downloading 1H05bc_QemdbvKRYEfVJg4WsuCXDNvpz6 into /content/dataset/labels/val/F37605_florencia_fernandez_30.txt...

 55%|█████▍    | 266/488 [10:35<08:29,  2.30s/it]

Done.
Downloading 1WfLGdy8lEI5qTCMDJT8X6s7zzzRuPPjL into /content/dataset/labels/val/F37605_florencia_fernandez_35.txt...

 55%|█████▍    | 267/488 [10:38<08:36,  2.34s/it]

Done.
Downloading 1paY4S-Exb-8AOQVnciMFZnl3XsCaNJwk into /content/dataset/labels/val/F37605_florencia_fernandez_37.txt...

 55%|█████▍    | 268/488 [10:40<08:38,  2.36s/it]

Done.
Downloading 1fW0OTGYrcr7WjEw_VVpREuMVAlt5lYGX into /content/dataset/labels/val/F37605_florencia_fernandez_45.txt...

 55%|█████▌    | 269/488 [10:42<08:27,  2.32s/it]

Done.
Downloading 1bPGl3JuYwnPHSEWs0dmLLlSToHPSV5GY into /content/dataset/labels/val/F37605_florencia_fernandez_46.txt...

 55%|█████▌    | 270/488 [10:45<08:36,  2.37s/it]

Done.
Downloading 1gJSsemBSd7oAUIrCoIXW4EsSJZiTaokc into /content/dataset/labels/val/F37605_florencia_fernandez_47.txt...

 56%|█████▌    | 271/488 [10:47<08:42,  2.41s/it]

Done.
Downloading 1LGuX9nPpC9CpCq75D4xYIEwomT8kw1QE into /content/dataset/labels/val/F37605_florencia_fernandez_48.txt...

 56%|█████▌    | 272/488 [10:50<08:47,  2.44s/it]

Done.
Downloading 1pM4TnAx14wwHe1LOgnZIKF93v4vcWtR0 into /content/dataset/labels/val/F37605_florencia_fernandez_56.txt...

 56%|█████▌    | 273/488 [10:52<08:33,  2.39s/it]

Done.
Downloading 1P_uKXv9_JTT--bnOGJ0B4sjoqg4bHiQb into /content/dataset/labels/val/L32425_eugenio_lopez_18.txt...

 56%|█████▌    | 274/488 [10:55<09:24,  2.64s/it]

Done.
Downloading 1ApXA81zizM0NK0Kkw9jdZupwGmT4Z5eG into /content/dataset/labels/val/L32425_eugenio_lopez_24.txt...

 56%|█████▋    | 275/488 [10:58<09:02,  2.55s/it]

Done.
Downloading 1ydc3_zFbgSydQJbMNt3n0oes4MSUAQ8c into /content/dataset/labels/val/L32425_eugenio_lopez_26.txt...

 57%|█████▋    | 276/488 [11:00<08:23,  2.37s/it]

Done.
Downloading 1LPOVCs1zZ6eQtXgsulrJmx4wVGc4VejE into /content/dataset/labels/val/L32531_santiago_loza_11.txt...

 57%|█████▋    | 277/488 [11:02<08:50,  2.52s/it]

Done.
Downloading 1hAIiL9GVE5cFNcvJvofF3Pl76QwauEFh into /content/dataset/labels/val/L32531_santiago_loza_15.txt...

 57%|█████▋    | 278/488 [11:05<08:56,  2.55s/it]

Done.
Downloading 1eD3Ehqgg9NZKc5HS3oLxk_7DcIp1IUJU into /content/dataset/labels/val/L32531_santiago_loza_16.txt...

 57%|█████▋    | 279/488 [11:08<09:05,  2.61s/it]

Done.
Downloading 1m_EaxDBpk3e3Rig3DVg8RMxUaKL-ByBO into /content/dataset/labels/val/L32531_santiago_loza_20.txt...

 57%|█████▋    | 280/488 [11:10<08:32,  2.46s/it]

Done.
Downloading 1pN9TXB6a3EbVQtEHY-_BnrfbDaslMf3S into /content/dataset/labels/val/L32531_santiago_loza_21.txt...

 58%|█████▊    | 281/488 [11:12<08:06,  2.35s/it]

Done.
Downloading 1WQP90j7abup5SxC0DG7JbMDdMah3RLEO into /content/dataset/labels/val/L32531_santiago_loza_25.txt...

 58%|█████▊    | 282/488 [11:14<08:05,  2.35s/it]

Done.
Downloading 1UQoccozTWGswJyxBCu88v8czE-eBz-BK into /content/dataset/labels/val/L32531_santiago_loza_27.txt...

 58%|█████▊    | 283/488 [11:16<07:45,  2.27s/it]

Done.
Downloading 1JurpQRTI_Da3TPdFD8delmfY79FizfxL into /content/dataset/labels/val/L32531_santiago_loza_29.txt...

 58%|█████▊    | 284/488 [11:20<08:45,  2.58s/it]

Done.
Downloading 11bHi2U7IPq11Iww1pFtOUWt-eABnVLxz into /content/dataset/labels/val/L32531_santiago_loza_39.txt...

 58%|█████▊    | 285/488 [11:22<08:26,  2.50s/it]

Done.
Downloading 1jt0RK5g07kSuzDwm7cRofjmGDSe-0i7S into /content/dataset/labels/val/L32531_santiago_loza_40.txt...

 59%|█████▊    | 286/488 [11:24<08:05,  2.40s/it]

Done.
Downloading 1uQQFDKPmzag0YAaZCfmzTYcljWzUukxQ into /content/dataset/labels/val/L32531_santiago_loza_43.txt...

 59%|█████▉    | 287/488 [11:27<07:59,  2.39s/it]

Done.
Downloading 1icoAjoe8HqhE4OVMmeVhXuDmYlvJGbF9 into /content/dataset/labels/val/L32531_santiago_loza_45.txt...

 59%|█████▉    | 288/488 [11:29<07:40,  2.30s/it]

Done.
Downloading 1Wj4vEgDwkHUBSjjy9OfRvDx2iPCWppbo into /content/dataset/labels/val/L32531_santiago_loza_5.txt...

 59%|█████▉    | 289/488 [11:31<07:32,  2.27s/it]

Done.
Downloading 1MYitbig1JjaLxPjiEM6F90YqXZrO8OTD into /content/dataset/labels/val/L32531_santiago_loza_6.txt...

 59%|█████▉    | 290/488 [11:33<07:34,  2.29s/it]

Done.
Downloading 1Tsb83eAeLv27_OPzaCMVXKxA7lHD-yNZ into /content/dataset/labels/val/P51926_Leonel_Palermo_01.txt...

 60%|█████▉    | 291/488 [11:35<07:20,  2.24s/it]

Done.
Downloading 1ijLxxe1QS4EtG9FQeE9a884Zhm-xJB9m into /content/dataset/labels/val/P51926_Leonel_Palermo_03.txt...

 60%|█████▉    | 292/488 [11:38<07:35,  2.33s/it]

Done.
Downloading 1u9uwc8hC27Jbq2-8kRcEgH5l9uufXz3K into /content/dataset/labels/val/P51926_Leonel_Palermo_09.txt...

 60%|██████    | 293/488 [11:40<07:26,  2.29s/it]

Done.
Downloading 1JAQkcIgfYbI9jmvCD0wY_WfwWbzn-jXk into /content/dataset/labels/val/P51926_Leonel_Palermo_12.txt...

 60%|██████    | 294/488 [11:42<07:20,  2.27s/it]

Done.
Downloading 1TdvXzXaUP3sxoN6GxXE8nCRv4oNsdxvd into /content/dataset/labels/val/P51926_Leonel_Palermo_14.txt...

 60%|██████    | 295/488 [11:45<07:39,  2.38s/it]

Done.
Downloading 1egiciCNs-PL7YHxiOpIaXK06dVzAo8u_ into /content/dataset/labels/val/P51926_Leonel_Palermo_17.txt...

 61%|██████    | 296/488 [11:47<07:26,  2.33s/it]

Done.
Downloading 1djg5KcNWs4N_CXjuCeZP9OCJeYz5JMwM into /content/dataset/labels/val/P51926_Leonel_Palermo_19.txt...

 61%|██████    | 297/488 [11:50<07:31,  2.36s/it]

Done.
Downloading 1ZONKISwPwEp1NxLtPigqD_eEZAPP8ZIZ into /content/dataset/labels/val/P51926_Leonel_Palermo_21.txt...

 61%|██████    | 298/488 [11:52<07:23,  2.33s/it]

Done.
Downloading 1mHadSYrLCN7huZsGKcou2VV-4IrB19hl into /content/dataset/labels/val/P51951_pablo_pistarelli_05.txt...

 61%|██████▏   | 299/488 [11:55<07:56,  2.52s/it]

Done.
Downloading 198-INUrvgHh92wsP8_0aiy1jPXgemEDk into /content/dataset/labels/val/P51951_pablo_pistarelli_06.txt...

 61%|██████▏   | 300/488 [11:57<07:43,  2.46s/it]

Done.
Downloading 18jvmSTxl5OVgBduhQllQlSruUS3ANpyB into /content/dataset/labels/val/P51951_pablo_pistarelli_09.txt...

 62%|██████▏   | 301/488 [11:59<07:34,  2.43s/it]

Done.
Downloading 1yP0xI-AT736ISwBXnV7nrC0ZdAzW44pR into /content/dataset/labels/val/P_51977_martin_perrone_06.txt...

 62%|██████▏   | 302/488 [12:02<07:15,  2.34s/it]

Done.
Downloading 188VgiV8CXkOG29jAQARUagW9ymUlT2kH into /content/dataset/labels/val/P_51977_martin_perrone_10.txt...

 62%|██████▏   | 303/488 [12:04<07:17,  2.36s/it]

Done.
Downloading 18WbnJEGgpUWWxW_TIFZbuJr4q7VrBpmn into /content/dataset/labels/val/P_51977_martin_perrone_11.txt...

 62%|██████▏   | 304/488 [12:07<07:21,  2.40s/it]

Done.
Downloading 1znVKjGPqgcDU_drGJDxFU_IoEiD1YFGU into /content/dataset/labels/val/P_51977_martin_perrone_14.txt...

 62%|██████▎   | 305/488 [12:09<07:09,  2.34s/it]

Done.
Downloading 1mSW5mUliVctHSSfndCW4hPFC0lZDhFs_ into /content/dataset/labels/val/P_51977_martin_perrone_15.txt...

 63%|██████▎   | 306/488 [12:11<07:06,  2.34s/it]

Done.
Downloading 1YYKSbqqPaD6GI-_chUfgeA8RPKzD8njl into /content/dataset/labels/val/P_51977_martin_perrone_16.txt...

 63%|██████▎   | 307/488 [12:13<07:05,  2.35s/it]

Done.
Downloading 12Yp4rteB0hNsOcKIYdDzRnr_V9-iApMu into /content/dataset/labels/val/P_51977_martin_perrone_22.txt...

 63%|██████▎   | 308/488 [12:16<07:05,  2.37s/it]

Done.
Downloading 13o3PMq-U47YxpAf3Wnh9qr3KxS6_SJGl into /content/dataset/labels/val/P_51977_martin_perrone_25.txt...

 63%|██████▎   | 309/488 [12:18<06:57,  2.33s/it]

Done.
Downloading 11yo_9lbqU_EgvlV2_xm3n7ykI7B8SvC5 into /content/dataset/labels/val/P_51977_martin_perrone_26.txt...

 64%|██████▎   | 310/488 [12:20<06:50,  2.31s/it]

Done.
Downloading 1GyNmz9z5EINCesOALtlZZG_bdLtEbW4A into /content/dataset/labels/val/P_51977_martin_perrone_30.txt...

 64%|██████▎   | 311/488 [12:23<06:46,  2.30s/it]

Done.
Downloading 1cQ1PTduWkHCFz1UrBgOvi4aOy8vc27YG into /content/dataset/labels/val/P_51977_martin_perrone_33.txt...

 64%|██████▍   | 312/488 [12:25<06:47,  2.32s/it]

Done.
Downloading 1hlsge1LI-JFAdchH8iU7C8O3sZFbdZv9 into /content/dataset/labels/val/P_51977_martin_perrone_36.txt...

 64%|██████▍   | 313/488 [12:27<06:40,  2.29s/it]

Done.
Downloading 1woySPpgmF5LTSI1hbZz2D7AKBhjGVqco into /content/dataset/labels/val/P_51977_martin_perrone_37.txt...

 64%|██████▍   | 314/488 [12:30<06:38,  2.29s/it]

Done.
Downloading 14-XdKBiebH0CW1DWwlrjL0NlDD3SFqKt into /content/dataset/labels/val/P_51977_martin_perrone_39.txt...

 65%|██████▍   | 315/488 [12:32<06:44,  2.34s/it]

Done.
Downloading 1rn8judWLqGbLSIfGOCowxUaJvSj5AY5l into /content/dataset/labels/val/R-45489_sofiarondini_19.txt...

 65%|██████▍   | 316/488 [12:34<06:49,  2.38s/it]

Done.
Downloading 1_xSsYQqcsgMC7k_N9YisHNAxOFdD37Sc into /content/dataset/labels/val/R-45489_sofiarondini_26.txt...

 65%|██████▍   | 317/488 [12:37<06:41,  2.35s/it]

Done.
Downloading 1bWenPu0VUG6UExZ_y0vYNoTkRf6uRkb5 into /content/dataset/labels/val/R-45489_sofiarondini_29.txt...

 65%|██████▌   | 318/488 [12:39<06:48,  2.40s/it]

Done.
Downloading 1ezkl-b0o5G4JFL_dq6xLGJ-gyAB2Rj4i into /content/dataset/labels/val/R-45489_sofiarondini_32.txt...

 65%|██████▌   | 319/488 [12:41<06:38,  2.36s/it]

Done.
Downloading 1L1OjtVgBeFrjD0jXw39Jtcwm4Rr0xkKy into /content/dataset/labels/val/R-45489_sofiarondini_35.txt...

 66%|██████▌   | 320/488 [12:44<06:35,  2.35s/it]

Done.
Downloading 1Qwt-Aeoy4UYMk-WHzAsNQLeslfgJtNW6 into /content/dataset/labels/val/R-45829_Abril_Rodriguez_03.txt...

 66%|██████▌   | 321/488 [12:46<06:24,  2.30s/it]

Done.
Downloading 147Sh_slDcv-FgmQoa89tBtpU-GiyfzGn into /content/dataset/labels/val/R-45829_Abril_Rodriguez_09.txt...

 66%|██████▌   | 322/488 [12:49<06:34,  2.38s/it]

Done.
Downloading 18MPny1Jcs32fl0McMmDXeaJdzMQRo_CX into /content/dataset/labels/val/R-45829_Abril_Rodriguez_10.txt...

 66%|██████▌   | 323/488 [12:51<06:29,  2.36s/it]

Done.
Downloading 1DS26Uu-l1uZG1enGf3mb6ijDEwQIt8fr into /content/dataset/labels/val/R-45829_Abril_Rodriguez_11.txt...

 66%|██████▋   | 324/488 [12:53<06:27,  2.36s/it]

Done.
Downloading 1sGfYbOOAHRhTC491Pew69gNWQ_MA5oIs into /content/dataset/labels/val/R-45829_Abril_Rodriguez_15.txt...

 67%|██████▋   | 325/488 [12:56<06:22,  2.35s/it]

Done.
Downloading 1CJXOTnHwJzXTnm_mRrGWcfoHjDNUmRFH into /content/dataset/labels/val/R-45829_Abril_Rodriguez_20.txt...

 67%|██████▋   | 326/488 [12:58<06:14,  2.31s/it]

Done.
Downloading 1QkH6vNDIaXIebIjF_x5ZIGhBZX2LiHBv into /content/dataset/labels/val/R-45829_Abril_Rodriguez_24.txt...

 67%|██████▋   | 327/488 [13:00<06:13,  2.32s/it]

Done.
Downloading 1dtTGu0hk6_W0TP2CnsC5xnwFzFhOVKv_ into /content/dataset/labels/val/R-45829_Abril_Rodriguez_31.txt...

 67%|██████▋   | 328/488 [13:02<06:08,  2.30s/it]

Done.
Downloading 151EpLT3ZQrfbqT9oe4tYrSTgOenx0Hae into /content/dataset/labels/val/S57061_Leandro_Salvana_01.txt...

 67%|██████▋   | 329/488 [13:05<06:07,  2.31s/it]

Done.
Downloading 1iyfBi3jCvT0j-0j0Pya9cCTvujdC7RKH into /content/dataset/labels/val/S57061_Leandro_Salvana_04.txt...

 68%|██████▊   | 330/488 [13:07<05:59,  2.27s/it]

Done.
Downloading 1c6zYW8C2PPdEwsVC1DLUvWm_RPR1px8z into /content/dataset/labels/val/S57061_Leandro_Salvana_05.txt...

 68%|██████▊   | 331/488 [13:09<06:09,  2.35s/it]

Done.
Downloading 17A9DLrhHd-dWkN3POl4wYgUUKe-weG6B into /content/dataset/labels/val/S57061_Leandro_Salvana_06.txt...

 68%|██████▊   | 332/488 [13:12<06:05,  2.34s/it]

Done.
Downloading 1U2YCslD-8PZMUsZ03zOO0695k7HAvwH2 into /content/dataset/labels/val/S57061_Leandro_Salvana_11.txt...

 68%|██████▊   | 333/488 [13:14<06:01,  2.33s/it]

Done.
Downloading 1SybD5TNwfEecER71YvViRIiIy2x9y0TM into /content/dataset/labels/val/S57061_Leandro_Salvana_13.txt...

 68%|██████▊   | 334/488 [13:16<05:51,  2.28s/it]

Done.
Downloading 1MPIt0CVmd-iHrGNF7fg5E-FFB55-WHdk into /content/dataset/labels/val/S57061_Leandro_Salvana_14.txt...

 69%|██████▊   | 335/488 [13:18<05:47,  2.27s/it]

Done.
Downloading 1JMfyZ13j5v4jYMds_0dl6mfvBa37cv5r into /content/dataset/labels/val/S57061_Leandro_Salvana_16.txt...

 69%|██████▉   | 336/488 [13:21<05:53,  2.33s/it]

Done.
Downloading 16vKlpLKeMJFcmRfmkIHCW92d_PVp0hh5 into /content/dataset/labels/val/S57061_Leandro_Salvana_17.txt...

 69%|██████▉   | 337/488 [13:23<05:40,  2.25s/it]

Done.
Downloading 1xVDdWlkA-NhWudblqaibFQvUMBiGfdjQ into /content/dataset/labels/val/S57061_Leandro_Salvana_23.txt...

 69%|██████▉   | 338/488 [13:25<05:32,  2.21s/it]

Done.
Downloading 18rSore-Rt36u4eDmk4Qe62zOrUhHbCII into /content/dataset/labels/val/S57061_Leandro_Salvana_26.txt...

 69%|██████▉   | 339/488 [13:27<05:26,  2.19s/it]

Done.
Downloading 183gAZkrAiLiY0oztUjAgU-GzHobuxgY0 into /content/dataset/labels/val/S57061_Leandro_Salvana_31.txt...

 70%|██████▉   | 340/488 [13:30<05:44,  2.33s/it]

Done.
Downloading 1A1bQYfnBCx_jg2zhYMI6OHgNRwqn2qlr into /content/dataset/labels/val/S57061_Leandro_Salvana_33.txt...

 70%|██████▉   | 341/488 [13:32<05:35,  2.28s/it]

Done.
Downloading 1QSQdIU34NqoxEepDWKo9TbtrvVukQ5bl into /content/dataset/labels/val/S57061_Leandro_Salvana_34.txt...

 70%|███████   | 342/488 [13:34<05:26,  2.24s/it]

Done.
Downloading 1vlcp4j5KgnfpmmKMv0aX9lSemoGIALLP into /content/dataset/labels/val/S57061_Leandro_Salvana_38.txt...

 70%|███████   | 343/488 [13:36<05:16,  2.18s/it]

Done.
Downloading 1lvSuclrG7tYaGW9tAiSm1yB8_T-uMomA into /content/dataset/labels/val/S57061_Leandro_Salvana_42.txt...

 70%|███████   | 344/488 [13:39<05:19,  2.22s/it]

Done.
Downloading 14TC6ICE_owMyFhxLD1WpmdGZW5rrhQlO into /content/dataset/labels/val/S57061_Leandro_Salvana_44.txt...

 71%|███████   | 345/488 [13:41<05:20,  2.24s/it]

Done.
Downloading 1qubev1NrUhGKlxP06d2k7gSUKh1y-ILR into /content/dataset/labels/val/S57061_Leandro_Salvana_47.txt...

 71%|███████   | 346/488 [13:43<05:17,  2.24s/it]

Done.
Downloading 1VEQrzC28j73x-Mkrbr8f7fCvik8Wnilc into /content/dataset/labels/val/a018948edae55bc267a596533f44ce26.txt...

 71%|███████   | 347/488 [13:46<05:33,  2.37s/it]

Done.
Downloading 1cCUxgYqL7dIwItkT7V50vybz-ElyGgiN into /content/dataset/labels/val/b28e34fb755f51ab4d37d64db732151b.txt...

 71%|███████▏  | 348/488 [13:48<05:24,  2.32s/it]

Done.
Downloading 1oM-J2alUAIWqwAP9RcANOBkIF1EelVA5 into /content/dataset/labels/val/b94b2c04f22005e33c1f73a01b968bf5.txt...

 72%|███████▏  | 349/488 [13:50<05:29,  2.37s/it]

Done.
Downloading 18kWmpxwUPmjRfFdzmB-kixNqcU9IlOJH into /content/dataset/labels/val/c09974547d6736ab3d80f4e5ef49498b.txt...

 72%|███████▏  | 350/488 [13:53<05:21,  2.33s/it]

Done.
Downloading 1R3feVBqs67U4DCqMGzOjSQlXQdCqhnnY into /content/dataset/labels/val/ca61f1c99a6baadcf670bb1611e1a577.txt...

 72%|███████▏  | 351/488 [13:55<05:23,  2.36s/it]

Done.
Downloading 1BQ8jYwraTK_JV8CEGHBNrVQGNH05E5vC into /content/dataset/labels/val/cb34b326f984fcb48bf927ec3aebef0f.txt...

 72%|███████▏  | 352/488 [13:58<05:29,  2.42s/it]

Done.
Downloading 1UGs_Qs85qcHDBW747yUnByTccgcu8-EZ into /content/dataset/labels/val/cfdf69c24bd61195285179154b612680.txt...

 72%|███████▏  | 353/488 [14:00<05:22,  2.39s/it]

Done.
Downloading 1mBoonGu_JDrEsRHiIw5Icf2u4zkoh3CP into /content/dataset/labels/val/f1a1e60483d50907ec51fd1bf648c4dc.txt...

 73%|███████▎  | 354/488 [14:02<05:09,  2.31s/it]

Done.
Downloading 1vvauyPKLicmu_65B7YTTI-8pFo8Hq7Dt into /content/dataset/labels/val/f37478_santiago_ferrero_01.txt...

 73%|███████▎  | 355/488 [14:04<04:54,  2.22s/it]

Done.
Downloading 1C4Q7Gt0gEoeWeWR2CYJQ4H-1nAQB-PSD into /content/dataset/labels/val/f37478_santiago_ferrero_05.txt...

 73%|███████▎  | 356/488 [14:06<04:50,  2.20s/it]

Done.
Downloading 1bs-yV5QWXpelutnQRt4UD8_y3iPq5Tc1 into /content/dataset/labels/val/f37478_santiago_ferrero_07.txt...

 73%|███████▎  | 357/488 [14:09<05:04,  2.33s/it]

Done.
Downloading 1KrUDyHgcSkel1pBrr3ucxO798HlmZpdO into /content/dataset/labels/val/f37478_santiago_ferrero_09.txt...

 73%|███████▎  | 358/488 [14:11<05:00,  2.31s/it]

Done.
Downloading 16OTHhjftortw6h4ZVMTd5S_IsDNDZGGB into /content/dataset/labels/val/f37478_santiago_ferrero_15.txt...

 74%|███████▎  | 359/488 [14:13<04:49,  2.24s/it]

Done.
Downloading 1C2YtF5TOC-sCOKdtQB_45zuapnwowpEu into /content/dataset/labels/val/f37478_santiago_ferrero_18.txt...

 74%|███████▍  | 360/488 [14:15<04:40,  2.19s/it]

Done.
Downloading 11ogCThOmKp2Hwi54Uir5iAL7xv85mAd1 into /content/dataset/labels/val/f37478_santiago_ferrero_19.txt...

 74%|███████▍  | 361/488 [14:17<04:31,  2.14s/it]

Done.
Downloading 1SYwKpbPrM0LrEYNwJDr7ZFgrqqZJNNXN into /content/dataset/labels/val/f37478_santiago_ferrero_25.txt...

 74%|███████▍  | 362/488 [14:19<04:25,  2.11s/it]

Done.
Downloading 1OeIo779VrwuSWe8HmgrnmTPGazZ4nAUo into /content/dataset/labels/val/f37478_santiago_ferrero_27.txt...

 74%|███████▍  | 363/488 [14:22<04:27,  2.14s/it]

Done.
Downloading 1Nu6dWbD9xUXPFID_6-Ov1L0mGaBLBrWJ into /content/dataset/labels/val/f37478_santiago_ferrero_36.txt...

 75%|███████▍  | 364/488 [14:24<04:47,  2.32s/it]

Done.
Downloading 10ndqIs5I8f3SQpzIrb-UvOTz0P1E53Tm into /content/dataset/labels/val/f81f9fe13e4b6e7c55be2e358056eb9a.txt...

 75%|███████▍  | 365/488 [14:27<04:41,  2.29s/it]

Done.
Downloading 1i9PVT2ITHkxb_wAJSSqbus7MsXfKd1eF into /content/dataset/labels/val/g5845_gravifiorino_13.txt...

 75%|███████▌  | 366/488 [14:29<04:38,  2.29s/it]

Done.
Downloading 1UP5B9x_m9j8yuc6_mwcuoLRz3S97Ax5h into /content/dataset/labels/val/g5845_gravifiorino_17.txt...

 75%|███████▌  | 367/488 [14:31<04:36,  2.29s/it]

Done.
Downloading 1tm70_7ahRh7nvHONjvDtabh7kmdLrs1X into /content/dataset/labels/val/g5845_gravifiorino_19.txt...

 75%|███████▌  | 368/488 [14:34<04:50,  2.42s/it]

Done.
Downloading 1oQC_Yh5JGkFj3mDGqe8RQxUHj53HN_Gu into /content/dataset/labels/val/g5845_gravifiorino_20.txt...

 76%|███████▌  | 369/488 [14:36<04:51,  2.45s/it]

Done.
Downloading 1jyfnxlc6uQVsI_65Ld62jAi1naWkM_YS into /content/dataset/labels/val/g5845_gravifiorino_22.txt...

 76%|███████▌  | 370/488 [14:39<04:51,  2.47s/it]

Done.
Downloading 1MkWLAVCUslNJqltjFUaYKHqnpYHPzLBf into /content/dataset/labels/val/g5845_gravifiorino_24.txt...

 76%|███████▌  | 371/488 [14:41<04:38,  2.38s/it]

Done.
Downloading 17BH1EbF33wk-R-GlZLkY19-WLRNCUpTm into /content/dataset/labels/val/g5845_gravifiorino_25.txt...

 76%|███████▌  | 372/488 [14:43<04:25,  2.29s/it]

Done.
Downloading 1V48YVbt7RBWZCmNx-Dte8Tn94lTXM5F8 into /content/dataset/labels/val/g5845_gravifiorino_3.txt...

 76%|███████▋  | 373/488 [14:46<04:25,  2.31s/it]

Done.
Downloading 1Rr_PyAUROcTHOvlKDHTeOsnTnFGkKoAP into /content/dataset/labels/val/g5845_gravifiorino_30.txt...

 77%|███████▋  | 374/488 [14:48<04:26,  2.33s/it]

Done.
Downloading 1BLgnE6oVHlcFmuIkiAgMxmv7MNPzkblB into /content/dataset/labels/val/gravifiorino_9.txt...

 77%|███████▋  | 375/488 [14:50<04:19,  2.29s/it]

Done.
Downloading 107gN-0C1pEp5owulQOa2DOQ97sh6zx6i into /content/dataset/labels/val/s56189_salvador_sanchez_10.txt...

 77%|███████▋  | 376/488 [14:53<04:32,  2.43s/it]

Done.
Downloading 1LvaFZsnoRj5GKJvmIBFF9U5_MJHXejlY into /content/dataset/labels/val/s56189_salvador_sanchez_101.txt...

 77%|███████▋  | 377/488 [14:55<04:31,  2.45s/it]

Done.
Downloading 1MALaBdeW4shTDDyyNAva--St90_PC9vf into /content/dataset/labels/val/s56189_salvador_sanchez_103.txt...

 77%|███████▋  | 378/488 [14:58<04:23,  2.39s/it]

Done.
Downloading 1MNDnqBrAKABFY5fjTq0uU1IojZJVaO04 into /content/dataset/labels/val/s56189_salvador_sanchez_107.txt...

 78%|███████▊  | 379/488 [15:00<04:17,  2.36s/it]

Done.
Downloading 1MUbRLlrwl1WaeK98tboEZpL1XaCHENev into /content/dataset/labels/val/s56189_salvador_sanchez_111.txt...

 78%|███████▊  | 380/488 [15:02<04:06,  2.28s/it]

Done.
Downloading 1Ma4CaCNq0WXrPNnBbnWKrAX6qsUcI8-7 into /content/dataset/labels/val/s56189_salvador_sanchez_113.txt...

 78%|███████▊  | 381/488 [15:04<04:04,  2.28s/it]

Done.
Downloading 1Mb2dgB4jo6om5Tc_8yZJO5An-e50Ozu0 into /content/dataset/labels/val/s56189_salvador_sanchez_114.txt...

 78%|███████▊  | 382/488 [15:07<04:03,  2.29s/it]

Done.
Downloading 1MewFG7y8iAYEXUwmrhtQfxoEy5D1qXxA into /content/dataset/labels/val/s56189_salvador_sanchez_115.txt...

 78%|███████▊  | 383/488 [15:09<03:53,  2.23s/it]

Done.
Downloading 1NG92r6YZDca96M-8FV_aFP4waLn4YBAN into /content/dataset/labels/val/s56189_salvador_sanchez_120.txt...

 79%|███████▊  | 384/488 [15:11<03:54,  2.25s/it]

Done.
Downloading 1NGY88QYzQvnN5X6kA7UJs3KxVwY1UgX6 into /content/dataset/labels/val/s56189_salvador_sanchez_123.txt...

 79%|███████▉  | 385/488 [15:13<03:45,  2.19s/it]

Done.
Downloading 1NQHwwrddvaxjFhc6OCsrK8qj7p3ChViT into /content/dataset/labels/val/s56189_salvador_sanchez_124.txt...

 79%|███████▉  | 386/488 [15:15<03:39,  2.15s/it]

Done.
Downloading 1NTf2lEKjH9ISQmiAHr5lgkmdLoCMQTln into /content/dataset/labels/val/s56189_salvador_sanchez_126.txt...

 79%|███████▉  | 387/488 [15:17<03:40,  2.18s/it]

Done.
Downloading 1NlWnH8RbMvchYg9Bw7Zfyg96X6DWV8L8 into /content/dataset/labels/val/s56189_salvador_sanchez_129.txt...

 80%|███████▉  | 388/488 [15:19<03:35,  2.16s/it]

Done.
Downloading 10L0M5g9jY4sdCp-V6zaCu9Byuplysmyb into /content/dataset/labels/val/s56189_salvador_sanchez_13.txt...

 80%|███████▉  | 389/488 [15:22<03:37,  2.19s/it]

Done.
Downloading 1O2rLcPWJyCwWlXCtwsU-e0wbJ10avZrL into /content/dataset/labels/val/s56189_salvador_sanchez_131.txt...

 80%|███████▉  | 390/488 [15:24<03:40,  2.25s/it]

Done.
Downloading 1ONlTe_-9B_857TVz1SS9nm_J6MqjHkw_ into /content/dataset/labels/val/s56189_salvador_sanchez_134.txt...

 80%|████████  | 391/488 [15:26<03:35,  2.22s/it]

Done.
Downloading 1Ocx-2UygWhgBNAoilXTJTjDMW81GZvgE into /content/dataset/labels/val/s56189_salvador_sanchez_139.txt...

 80%|████████  | 392/488 [15:29<03:40,  2.30s/it]

Done.
Downloading 10jxH06p8riWQ8k7Z6yUt-OobMfup3OsH into /content/dataset/labels/val/s56189_salvador_sanchez_14.txt...

 81%|████████  | 393/488 [15:31<03:44,  2.36s/it]

Done.
Downloading 1OkA0k3CHGivJwEm1L1ggYQEyISrOplff into /content/dataset/labels/val/s56189_salvador_sanchez_140.txt...

 81%|████████  | 394/488 [15:33<03:34,  2.28s/it]

Done.
Downloading 1OrOvftxJZAGhrlBYCsKUG73FNK4cZ0Bl into /content/dataset/labels/val/s56189_salvador_sanchez_143.txt...

 81%|████████  | 395/488 [15:36<03:50,  2.48s/it]

Done.
Downloading 1PNArz6CfcfWAjMvKPjgVMMsBfTmTOjFi into /content/dataset/labels/val/s56189_salvador_sanchez_150.txt...

 81%|████████  | 396/488 [15:38<03:39,  2.39s/it]

Done.
Downloading 1PQ8jGdKIFJWCXNDMXiLPno-_15WLxiZ3 into /content/dataset/labels/val/s56189_salvador_sanchez_151.txt...

 81%|████████▏ | 397/488 [15:45<05:22,  3.54s/it]

Done.
Downloading 1PsRagHqN6xIpczMrKz84aFI6iD_gYRYq into /content/dataset/labels/val/s56189_salvador_sanchez_154.txt...

 82%|████████▏ | 398/488 [15:47<04:45,  3.17s/it]

Done.
Downloading 1Puq596p3WwlO4rGc_jz2xXi4ykdgCGO4 into /content/dataset/labels/val/s56189_salvador_sanchez_156.txt...

 82%|████████▏ | 399/488 [15:50<04:26,  2.99s/it]

Done.
Downloading 1QF4alvE_zviPbf-Tk8jkEgTDz6SyrCVO into /content/dataset/labels/val/s56189_salvador_sanchez_159.txt...

 82%|████████▏ | 400/488 [15:52<04:03,  2.77s/it]

Done.
Downloading 10lokZQpAEaEbORoqbZBj7IZGqkyOp2f8 into /content/dataset/labels/val/s56189_salvador_sanchez_16.txt...

 82%|████████▏ | 401/488 [15:54<03:44,  2.58s/it]

Done.
Downloading 1QRs4KW33t5GMDQQfCZc-B7t5X5rLxxSR into /content/dataset/labels/val/s56189_salvador_sanchez_165.txt...

 82%|████████▏ | 402/488 [15:56<03:39,  2.56s/it]

Done.
Downloading 1QgzqSR7kVti7CXATeJHWVkf3dBmXFwpQ into /content/dataset/labels/val/s56189_salvador_sanchez_167.txt...

 83%|████████▎ | 403/488 [15:59<03:32,  2.50s/it]

Done.
Downloading 1RCXREm_u4EarnWQobFeQzX1BByPRoIiV into /content/dataset/labels/val/s56189_salvador_sanchez_178.txt...

 83%|████████▎ | 404/488 [16:01<03:23,  2.42s/it]

Done.
Downloading 1RNz0C-KbNwcmlZZhz7zMfjYnrK5hlqqo into /content/dataset/labels/val/s56189_salvador_sanchez_180.txt...

 83%|████████▎ | 405/488 [16:03<03:17,  2.38s/it]

Done.
Downloading 1RZqcprvN6OOgKRrJ5NjZ0oHTieg0ch3H into /content/dataset/labels/val/s56189_salvador_sanchez_182.txt...

 83%|████████▎ | 406/488 [16:06<03:14,  2.37s/it]

Done.
Downloading 1RnOx0OxFt7ruj_qNFm2qum66AGxoLmWx into /content/dataset/labels/val/s56189_salvador_sanchez_189.txt...

 83%|████████▎ | 407/488 [16:08<03:06,  2.31s/it]

Done.
Downloading 1RvjgfRVUPMtiASRzpNKs0uLgGctLjBsW into /content/dataset/labels/val/s56189_salvador_sanchez_191.txt...

 84%|████████▎ | 408/488 [16:10<03:03,  2.29s/it]

Done.
Downloading 1S3suNyB-Dvss1GumgvGSkjl5tAJootCe into /content/dataset/labels/val/s56189_salvador_sanchez_193.txt...

 84%|████████▍ | 409/488 [16:13<03:02,  2.31s/it]

Done.
Downloading 1SKbcXicBKcQINU92gwJ25iEAUP_AEfWx into /content/dataset/labels/val/s56189_salvador_sanchez_196.txt...

 84%|████████▍ | 410/488 [16:15<03:07,  2.41s/it]

Done.
Downloading 1SSPjtBgL2vTrbo8a6GD5OglTd01ldjlK into /content/dataset/labels/val/s56189_salvador_sanchez_197.txt...

 84%|████████▍ | 411/488 [16:18<03:07,  2.43s/it]

Done.
Downloading 1SaD6jVi5vGmSW7itzQFElHGS8Vygp3V3 into /content/dataset/labels/val/s56189_salvador_sanchez_198.txt...

 84%|████████▍ | 412/488 [16:20<03:01,  2.39s/it]

Done.
Downloading 1Stee2732hb8MQOAnvJObtJ9rLUnb1kaR into /content/dataset/labels/val/s56189_salvador_sanchez_203.txt...

 85%|████████▍ | 413/488 [16:22<02:53,  2.31s/it]

Done.
Downloading 1TDZ7p3ezIquN8kW0h34DnJ7gZy0OCQPz into /content/dataset/labels/val/s56189_salvador_sanchez_209.txt...

 85%|████████▍ | 414/488 [16:24<02:49,  2.29s/it]

Done.
Downloading 1TOPZlafRiaxnU4E8ywf4wfLi51AxALAE into /content/dataset/labels/val/s56189_salvador_sanchez_210.txt...

 85%|████████▌ | 415/488 [16:27<02:49,  2.32s/it]

Done.
Downloading 1TZVaqv89f4PAVkpMKNBX3lFzEPHm_Itq into /content/dataset/labels/val/s56189_salvador_sanchez_212.txt...

 85%|████████▌ | 416/488 [16:29<02:45,  2.30s/it]

Done.
Downloading 1ThU2QHI479s2q5p_yryDI2FHw2iT3kEl into /content/dataset/labels/val/s56189_salvador_sanchez_217.txt...

 85%|████████▌ | 417/488 [16:31<02:48,  2.37s/it]

Done.
Downloading 1TvhBAl7DXHibtb6Qdg9Ex63kHdTQw11G into /content/dataset/labels/val/s56189_salvador_sanchez_219.txt...

 86%|████████▌ | 418/488 [16:34<02:43,  2.34s/it]

Done.
Downloading 11RMAm5AhoGoU5k4hd3ax4t2Yi5U-cJi4 into /content/dataset/labels/val/s56189_salvador_sanchez_22.txt...

 86%|████████▌ | 419/488 [16:36<02:37,  2.28s/it]

Done.
Downloading 1U2yus1wsT1jIzVwycjJdvDcDGFtigsLN into /content/dataset/labels/val/s56189_salvador_sanchez_220.txt...

 86%|████████▌ | 420/488 [16:38<02:31,  2.23s/it]

Done.
Downloading 1UA1wegA2tVdDFFyWLpULzs3v9RCWzrFd into /content/dataset/labels/val/s56189_salvador_sanchez_224.txt...

 86%|████████▋ | 421/488 [16:41<02:36,  2.34s/it]

Done.
Downloading 1UXEmY904uQwAra01voy4M1u1rkfLo5gY into /content/dataset/labels/val/s56189_salvador_sanchez_226.txt...

 86%|████████▋ | 422/488 [16:43<02:35,  2.36s/it]

Done.
Downloading 1Um5joUkMxlWBY1Gmj6fgO8UAUTtfIReN into /content/dataset/labels/val/s56189_salvador_sanchez_228.txt...

 87%|████████▋ | 423/488 [16:45<02:33,  2.36s/it]

Done.
Downloading 1UgdF8LY2mSG1xPN15uDmIaB5OYml4I1C into /content/dataset/labels/val/s56189_salvador_sanchez_229.txt...

 87%|████████▋ | 424/488 [16:47<02:25,  2.28s/it]

Done.
Downloading 11W1_lam1exUK2w3WxSmKsZegxA6W1h2U into /content/dataset/labels/val/s56189_salvador_sanchez_23.txt...

 87%|████████▋ | 425/488 [16:50<02:23,  2.28s/it]

Done.
Downloading 1VhbEAScoL9nvjGlxC0jDtQZCH17hANdQ into /content/dataset/labels/val/s56189_salvador_sanchez_242.txt...

 87%|████████▋ | 426/488 [16:52<02:18,  2.24s/it]

Done.
Downloading 1VztaVpN0Gkzu8s_ql67tnQ0GQNlw7Qhl into /content/dataset/labels/val/s56189_salvador_sanchez_246.txt...

 88%|████████▊ | 427/488 [16:54<02:21,  2.32s/it]

Done.
Downloading 1W1MO8JnKbzrFwasq9W-6YMfVOH-XC8fC into /content/dataset/labels/val/s56189_salvador_sanchez_254.txt...

 88%|████████▊ | 428/488 [16:57<02:19,  2.32s/it]

Done.
Downloading 1WGu9Bx9T4mc_ukJ7lHpAd-_aPgjhE-yI into /content/dataset/labels/val/s56189_salvador_sanchez_257.txt...

 88%|████████▊ | 429/488 [16:59<02:15,  2.30s/it]

Done.
Downloading 11ei_u9iVWl8gageGULnAsDPXwvEj6Qbi into /content/dataset/labels/val/s56189_salvador_sanchez_26.txt...

 88%|████████▊ | 430/488 [17:01<02:12,  2.28s/it]

Done.
Downloading 1WVbQhy4lW8l9a_rOlafy-Avr901raJNR into /content/dataset/labels/val/s56189_salvador_sanchez_263.txt...

 88%|████████▊ | 431/488 [17:04<02:13,  2.34s/it]

Done.
Downloading 1WccVcfN2OOAcpJoeaMdCKyI8EBEPTuBI into /content/dataset/labels/val/s56189_salvador_sanchez_265.txt...

 89%|████████▊ | 432/488 [17:06<02:13,  2.38s/it]

Done.
Downloading 1WZq_9nl7a9JRVU4CDj4OzuGZotoUy3Tr into /content/dataset/labels/val/s56189_salvador_sanchez_266.txt...

 89%|████████▊ | 433/488 [17:08<02:06,  2.30s/it]

Done.
Downloading 1Wri_-OYy4JDMVjPYfmcsPHf8DYlvw--A into /content/dataset/labels/val/s56189_salvador_sanchez_269.txt...

 89%|████████▉ | 434/488 [17:11<02:05,  2.33s/it]

Done.
Downloading 12AkDhTpLdb7-cbt9qFsyXbzqKEdSOXKe into /content/dataset/labels/val/s56189_salvador_sanchez_27.txt...

 89%|████████▉ | 435/488 [17:13<02:01,  2.29s/it]

Done.
Downloading 1WjJaFuN7dM7U_66YpfbfDYCzWoK-EU7G into /content/dataset/labels/val/s56189_salvador_sanchez_272.txt...

 89%|████████▉ | 436/488 [17:15<01:56,  2.24s/it]

Done.
Downloading 1X3CFjJkjH9prMIRvYkEAzq7HvndfHskV into /content/dataset/labels/val/s56189_salvador_sanchez_274.txt...

 90%|████████▉ | 437/488 [17:17<01:55,  2.26s/it]

Done.
Downloading 1XIHdpyQ9QvkKiF5Q_LTlA6W1KX7hDwCK into /content/dataset/labels/val/s56189_salvador_sanchez_276.txt...

 90%|████████▉ | 438/488 [17:20<01:52,  2.26s/it]

Done.
Downloading 1XpocwgRGtgpvnK1CST-Uw7m6Lo29HX_V into /content/dataset/labels/val/s56189_salvador_sanchez_283.txt...

 90%|████████▉ | 439/488 [17:22<01:50,  2.25s/it]

Done.
Downloading 1XyEu16whdmT4Nrg1NpV9jE1701ewv3qi into /content/dataset/labels/val/s56189_salvador_sanchez_287.txt...

 90%|█████████ | 440/488 [17:24<01:49,  2.29s/it]

Done.
Downloading 1YR1WtBLbbVt8-SHbez0OO9vfXi6WnRbK into /content/dataset/labels/val/s56189_salvador_sanchez_294.txt...

 90%|█████████ | 441/488 [17:42<05:25,  6.91s/it]

Done.
Downloading 1YHxUnT0T5vIK37l1wHCmGty8SCNnQFgK into /content/dataset/labels/val/s56189_salvador_sanchez_295.txt...

 91%|█████████ | 442/488 [17:44<04:14,  5.53s/it]

Done.
Downloading 1YlhWhqkAK0yhSUd0yfwVGNUcPvfPlYvZ into /content/dataset/labels/val/s56189_salvador_sanchez_301.txt...

 91%|█████████ | 443/488 [17:46<03:24,  4.55s/it]

Done.
Downloading 1YknDBmvoteHaxqWDhD3v6s4UGiZINjT4 into /content/dataset/labels/val/s56189_salvador_sanchez_302.txt...

 91%|█████████ | 444/488 [17:49<02:49,  3.84s/it]

Done.
Downloading 1Z9KTzbKrRBrWNtCWmJw8Zs-ydc_V6J0C into /content/dataset/labels/val/s56189_salvador_sanchez_305.txt...

 91%|█████████ | 445/488 [17:51<02:26,  3.40s/it]

Done.
Downloading 1ZIvbDHspESoI02hrBYA0KKd0cWoej-GB into /content/dataset/labels/val/s56189_salvador_sanchez_307.txt...

 91%|█████████▏| 446/488 [17:53<02:08,  3.06s/it]

Done.
Downloading 1ZE5tD3ZK7qx_TwYB9XFVuR2tL6oqlLZz into /content/dataset/labels/val/s56189_salvador_sanchez_309.txt...

 92%|█████████▏| 447/488 [17:56<01:57,  2.86s/it]

Done.
Downloading 1ZiGrpO-PqCZQfVNp_pn_wjnyqAAg3pnJ into /content/dataset/labels/val/s56189_salvador_sanchez_314.txt...

 92%|█████████▏| 448/488 [17:58<01:49,  2.74s/it]

Done.
Downloading 12q1DV3A23uh1W2yWvHZxueJyyXmvQBId into /content/dataset/labels/val/s56189_salvador_sanchez_36.txt...

 92%|█████████▏| 449/488 [18:00<01:42,  2.64s/it]

Done.
Downloading 12kX_oh2YaIdf6aOBVhIc0RbTVd_Lhszd into /content/dataset/labels/val/s56189_salvador_sanchez_38.txt...

 92%|█████████▏| 450/488 [18:03<01:34,  2.48s/it]

Done.
Downloading 12sWbvZAdUcnRZoUtYOfT1OvvOJO2h-FH into /content/dataset/labels/val/s56189_salvador_sanchez_40.txt...

 92%|█████████▏| 451/488 [18:05<01:30,  2.44s/it]

Done.
Downloading 13JT0HO2w8wIYvXXjkTXeIHYpN4qZDosQ into /content/dataset/labels/val/s56189_salvador_sanchez_49.txt...

 93%|█████████▎| 452/488 [18:07<01:25,  2.37s/it]

Done.
Downloading 1-hzakcXsHCCMBfkSqb3cnUJr0d_eyG27 into /content/dataset/labels/val/s56189_salvador_sanchez_5.txt...

 93%|█████████▎| 453/488 [18:09<01:19,  2.28s/it]

Done.
Downloading 1Ie1A-XPhz5pYBGrLmOls6XI6ZVYGRU8p into /content/dataset/labels/val/s56189_salvador_sanchez_53.txt...

 93%|█████████▎| 454/488 [18:12<01:17,  2.28s/it]

Done.
Downloading 1IdA4rZ8Nfk7SBqxYJMSF-p4y9ZKXjK5u into /content/dataset/labels/val/s56189_salvador_sanchez_54.txt...

 93%|█████████▎| 455/488 [18:14<01:16,  2.33s/it]

Done.
Downloading 1JGFZeeDP_5tNThdGGEhTXs1iVxikakDx into /content/dataset/labels/val/s56189_salvador_sanchez_55.txt...

 93%|█████████▎| 456/488 [18:16<01:12,  2.26s/it]

Done.
Downloading 1J-tTNQ2O2Ougzv3drB8nElXR4EsNDnKm into /content/dataset/labels/val/s56189_salvador_sanchez_58.txt...

 94%|█████████▎| 457/488 [18:18<01:11,  2.31s/it]

Done.
Downloading 1-__EbApwNSPJ4E6tNrAl2aIpNk3B9-IF into /content/dataset/labels/val/s56189_salvador_sanchez_6.txt...

 94%|█████████▍| 458/488 [18:21<01:10,  2.34s/it]

Done.
Downloading 1Ishbf1xIEW3npZW2fh1hPfI3_w5HBw1Z into /content/dataset/labels/val/s56189_salvador_sanchez_61.txt...

 94%|█████████▍| 459/488 [18:23<01:09,  2.39s/it]

Done.
Downloading 1Jjx5yqQMpiyyTN2DGnlbzIVqoN7JLr0R into /content/dataset/labels/val/s56189_salvador_sanchez_70.txt...

 94%|█████████▍| 460/488 [18:26<01:06,  2.37s/it]

Done.
Downloading 1KMFm76mhnKcgQKvHS11TiiNOpU4ss566 into /content/dataset/labels/val/s56189_salvador_sanchez_78.txt...

 94%|█████████▍| 461/488 [18:28<01:03,  2.34s/it]

Done.
Downloading 1KxjjY11ujiIwbOB_12FfBJ-NXXXe2dqH into /content/dataset/labels/val/s56189_salvador_sanchez_86.txt...

 95%|█████████▍| 462/488 [18:30<01:00,  2.32s/it]

Done.
Downloading 1LApbJrjl7HnEGc_U4cYRk5nQ_tC0Bbm- into /content/dataset/labels/val/s56189_salvador_sanchez_87.txt...

 95%|█████████▍| 463/488 [18:32<00:56,  2.27s/it]

Done.
Downloading 1LD2Yl6AFZz9oPSmlDccVnFWFYap8wKeT into /content/dataset/labels/val/s56189_salvador_sanchez_89.txt...

 95%|█████████▌| 464/488 [18:35<00:55,  2.32s/it]

Done.
Downloading 1LL4GxeYBC_Wr_Wv_QJv14lGbtLaFzPVN into /content/dataset/labels/val/s56189_salvador_sanchez_91.txt...

 95%|█████████▌| 465/488 [18:37<00:53,  2.31s/it]

Done.
Downloading 1LejL9z0zgwiOzL2IoGllLrVjxinFfgy9 into /content/dataset/labels/val/s56189_salvador_sanchez_95.txt...

 95%|█████████▌| 466/488 [18:39<00:49,  2.25s/it]

Done.
Downloading 1LVblDmkTlo20UNraOP8kxydoi_T5Md4l into /content/dataset/labels/val/s56189_salvador_sanchez_96.txt...

 96%|█████████▌| 467/488 [18:42<00:48,  2.29s/it]

Done.
Downloading 1LgoFGebzzxFOSInDFZce7KO7SrCcCftD into /content/dataset/labels/val/s56189_salvador_sanchez_98.txt...

 96%|█████████▌| 468/488 [18:44<00:45,  2.27s/it]

Done.
Downloading 1TlGg97U_B7od4UPi4G6KtC0HP4RxYM-J into /content/dataset/labels/val/s56804_alexis_segui_03.txt...

 96%|█████████▌| 469/488 [18:46<00:43,  2.27s/it]

Done.
Downloading 1XH8xPw6-sIzRNDb63-Q-hUZVcVW14Uq_ into /content/dataset/labels/val/s56804_alexis_segui_05.txt...

 96%|█████████▋| 470/488 [18:49<00:41,  2.32s/it]

Done.
Downloading 1WMjsk-msM9ia6jAyJWeu35nWfS_Ntwga into /content/dataset/labels/val/s56804_alexis_segui_08.txt...

 97%|█████████▋| 471/488 [18:51<00:38,  2.29s/it]

Done.
Downloading 1jk5x4-W4xQUFAC-sFn1lKuG5aApS02BH into /content/dataset/labels/val/s56804_alexis_segui_09.txt...

 97%|█████████▋| 472/488 [18:54<00:38,  2.42s/it]

Done.
Downloading 1WPPnhg6b9-U9vnGU98JYa7qDo3AQSLB5 into /content/dataset/labels/val/s56804_alexis_segui_11.txt...

 97%|█████████▋| 473/488 [18:56<00:34,  2.32s/it]

Done.
Downloading 1yJy4RsonnKnqeB_vebuXngj-S8ZhZzEE into /content/dataset/labels/val/s56804_alexis_segui_12.txt...

 97%|█████████▋| 474/488 [19:16<01:47,  7.70s/it]

Done.
Downloading 1-3EP9j1fpYcC6nGlqRsmqqUvtV8SDWRh into /content/dataset/labels/val/s56804_alexis_segui_13.txt...

 97%|█████████▋| 475/488 [19:18<01:18,  6.03s/it]

Done.
Downloading 1cZlkf6umWgtwg31BIc-P464fVbamT8dK into /content/dataset/labels/val/s56804_alexis_segui_14.txt...

 98%|█████████▊| 476/488 [19:20<00:58,  4.89s/it]

Done.
Downloading 1jryK2Hl8qdDcps0sYmxJFfpxrULSOBuY into /content/dataset/labels/val/s56804_alexis_segui_21.txt...

 98%|█████████▊| 477/488 [19:22<00:45,  4.10s/it]

Done.
Downloading 1UKDcLYZlEEwrvG5YkGjA68b52mXC5jDT into /content/dataset/labels/val/s56804_alexis_segui_30.txt...

 98%|█████████▊| 478/488 [19:25<00:36,  3.61s/it]

Done.
Downloading 1SRozHIUKv9LSYenAAQKknfwLv6W_QtRR into /content/dataset/labels/val/s56804_alexis_segui_31.txt...

 98%|█████████▊| 479/488 [19:27<00:28,  3.18s/it]

Done.
Downloading 1ssk5U6CFE2JKWqKgOG_mN7pp7NghPB2j into /content/dataset/labels/val/w05576_juan_wagner_01.txt...

 98%|█████████▊| 480/488 [19:29<00:23,  2.90s/it]

Done.
Downloading 1K77lz0M58x1jjgEg_ipd24CY1b6kQTao into /content/dataset/labels/val/w05576_juan_wagner_03.txt...

 99%|█████████▊| 481/488 [19:32<00:19,  2.78s/it]

Done.
Downloading 1vOI4qeecuN2ZYjtvhxOqeAFW_k2680wB into /content/dataset/labels/val/w05576_juan_wagner_17.txt...

 99%|█████████▉| 482/488 [19:34<00:16,  2.73s/it]

Done.
Downloading 1YnF3ofsN6wYL_yLuqIOKvhITsojECngf into /content/dataset/labels/val/w05576_juan_wagner_21.txt...

 99%|█████████▉| 483/488 [19:37<00:13,  2.62s/it]

Done.
Downloading 1bB6ylutGfF0QB-dlXYIyTk2I17N-w3O4 into /content/dataset/labels/val/w05576_juan_wagner_23.txt...

 99%|█████████▉| 484/488 [19:39<00:10,  2.62s/it]

Done.
Downloading 1zh_kysUJWjSKlkTk0G8guraYSvVxeZcH into /content/dataset/labels/val/w05576_juan_wagner_24.txt...

 99%|█████████▉| 485/488 [19:42<00:07,  2.51s/it]

Done.
Downloading 1WWxFh0GM40aPyK6y5y74K4mGm1uaIzqQ into /content/dataset/labels/val/w05576_juan_wagner_25.txt...

100%|█████████▉| 486/488 [19:42<00:03,  1.90s/it]

Done.
Downloading 1ytKch08hpNd67h8FDZtUlHf7jIvsP7Bx into /content/dataset/labels/val/w05576_juan_wagner_27.txt...

100%|█████████▉| 487/488 [19:44<00:01,  1.97s/it]

Done.
Downloading 1ASiquTihypahGJNHS7s_su1DW_-InKQF into /content/dataset/labels/val/w05576_juan_wagner_29.txt...

100%|██████████| 488/488 [19:47<00:00,  2.43s/it]

Done.

### Formato

In [ ]:
def convert_segment_to_bbox(segment_annotation):
    try:
        coords = list(map(float, segment_annotation.split()[1:]))  # Skip the first value (class)
        x_coords = coords[0::2]
        y_coords = coords[1::2]

        min_x = min(x_coords)
        max_x = max(x_coords)
        min_y = min(y_coords)
        max_y = max(y_coords)

        x_center = (min_x + max_x) / 2
        y_center = (min_y + max_y) / 2
        width = max_x - min_x
        height = max_y - min_y

        return f"{segment_annotation.split()[0]} {x_center} {y_center} {width} {height}"

    except ValueError as e:
        print(f"Error converting segment to bbox: {e}, in annotation: {segment_annotation}")
        return None

def process_annotation_file(file_path):
    with codecs.open(file_path, 'r', encoding='ascii', errors='ignore') as file:
        lines = file.readlines()

    new_lines = []
    for line in lines:
        if len(line.split()) > 5:  # Assuming segment annotations have more than 5 values
            new_line = convert_segment_to_bbox(line.strip())
            if new_line:
                new_lines.append(new_line)
        else:
            new_lines.append(line.strip())  # already in bbox format

    with open(file_path, 'w') as file:
        file.write("\n".join(new_lines) + "\n")

def process_annotations_folder(folder_path):
    for filename in os.listdir(folder_path):
        if filename.endswith(".txt"):
            process_annotation_file(os.path.join(folder_path, filename))

process_annotations_folder(train_labels_path)
process_annotations_folder(val_labels_path)

Error converting segment to bbox: could not convert string to float: 'html><html><head><title>Google', in annotation: <!DOCTYPE html><html><head><title>Google Drive - Virus scan warning</title><meta http-equiv="content-type" content="text/html; charset=utf-8"/><style nonce="735CpI24rV599iHSBROGmQ">.goog-link-button{position:relative;color:#15c;text-decoration:underline;cursor:pointer}.goog-link-button-disabled{color:#ccc;text-decoration:none;cursor:default}body{color:#222;font:normal 13px/1.4 arial,sans-serif;margin:0}.grecaptcha-badge{visibility:hidden}.uc-main{padding-top:50px;text-align:center}#uc-dl-icon{display:inline-block;margin-top:16px;padding-right:1em;vertical-align:top}#uc-text{display:inline-block;max-width:68ex;text-align:left}.uc-error-caption,.uc-warning-caption{color:#222;font-size:16px}#uc-download-link{text-decoration:none}.uc-name-size a{color:#15c;text-decoration:none}.uc-name-size a:visited{color:#61c;text-decoration:none}.uc-name-size a:active{color:#d14836;text-decoration:none}.uc-footer{color:#777;font-size:11px;padding-bottom:5ex;padding-top:5ex;text-align:center}.uc-footer a{color:#15c}.uc-footer a:visited{color:#61c}.uc-footer a:active{color:#d14836}.uc-footer-divider{color:#ccc;width:100%}.goog-inline-block{position:relative;display:-moz-inline-box;display:inline-block}* html .goog-inline-block{display:inline}*:first-child+html .goog-inline-block{display:inline}sentinel{}</style><link rel="icon" href="//ssl.gstatic.com/docs/doclist/images/drive_2022q3_32dp.png"/></head><body><div class="uc-main"><div id="uc-dl-icon" class="image-container"><div class="drive-sprite-aux-download-file"></div></div><div id="uc-text"><p class="uc-warning-caption">Google Drive can't scan this file for viruses.</p><p class="uc-warning-subcaption">We are experiencing technical difficulties. Would you still like to download this file? <span class="uc-name-size"><a href="/open?id=1Ew9pyJa3pQV5J1OW1h5-SnSDMIwHo4ds">41932688_Simon_Revello_23.txt</a> (749)</span></p><form id="download-form" action="https://drive.usercontent.google.com/download" method="get"><input type="submit" id="uc-download-link" class="goog-inline-block jfk-button jfk-button-action" value="Download anyway"/><input type="hidden" name="id" value="1Ew9pyJa3pQV5J1OW1h5-SnSDMIwHo4ds"><input type="hidden" name="export" value="download"><input type="hidden" name="confirm" value="t"><input type="hidden" name="uuid" value="b2ff92d8-fcb9-4dad-9507-c06a70b4b874"></form></div></div><div class="uc-footer"><hr class="uc-footer-divider"></div></body></html>
Error converting segment to bbox: could not convert string to float: 'html><html><head><title>Google', in annotation: <!DOCTYPE html><html><head><title>Google Drive - Virus scan warning</title><meta http-equiv="content-type" content="text/html; charset=utf-8"/><style nonce="_3Xb9CR0oBjoL_Xy8kq2tA">.goog-link-button{position:relative;color:#15c;text-decoration:underline;cursor:pointer}.goog-link-button-disabled{color:#ccc;text-decoration:none;cursor:default}body{color:#222;font:normal 13px/1.4 arial,sans-serif;margin:0}.grecaptcha-badge{visibility:hidden}.uc-main{padding-top:50px;text-align:center}#uc-dl-icon{display:inline-block;margin-top:16px;padding-right:1em;vertical-align:top}#uc-text{display:inline-block;max-width:68ex;text-align:left}.uc-error-caption,.uc-warning-caption{color:#222;font-size:16px}#uc-download-link{text-decoration:none}.uc-name-size a{color:#15c;text-decoration:none}.uc-name-size a:visited{color:#61c;text-decoration:none}.uc-name-size a:active{color:#d14836;text-decoration:none}.uc-footer{color:#777;font-size:11px;padding-bottom:5ex;padding-top:5ex;text-align:center}.uc-footer a{color:#15c}.uc-footer a:visited{color:#61c}.uc-footer a:active{color:#d14836}.uc-footer-divider{color:#ccc;width:100%}.goog-inline-block{position:relative;display:-moz-inline-box;display:inline-block}* html .goog-inline-block{display:inline}*:first-child+html .goog-inline-block{display:inline}sentinel{}</style><link rel="icon" href="//ssl.gstatic.com/docs/doclist/images/drive_2022q3_32dp.png"/></head><body><div class="uc-main"><div id="uc-dl-icon" class="image-container"><div class="drive-sprite-aux-download-file"></div></div><div id="uc-text"><p class="uc-warning-caption">Google Drive can't scan this file for viruses.</p><p class="uc-warning-subcaption">We are experiencing technical difficulties. Would you still like to download this file? <span class="uc-name-size"><a href="/open?id=19JhKitB9qSwOg4b6CmJ16-RDAocnL3lx">41932688_Simon_Revello_9.txt</a> (747)</span></p><form id="download-form" action="https://drive.usercontent.google.com/download" method="get"><input type="submit" id="uc-download-link" class="goog-inline-block jfk-button jfk-button-action" value="Download anyway"/><input type="hidden" name="id" value="19JhKitB9qSwOg4b6CmJ16-RDAocnL3lx"><input type="hidden" name="export" value="download"><input type="hidden" name="confirm" value="t"><input type="hidden" name="uuid" value="b41dba15-58bb-42bb-aabb-4ff7303ac98a"></form></div></div><div class="uc-footer"><hr class="uc-footer-divider"></div></body></html>
Error converting segment to bbox: could not convert string to float: 'html><html><head><title>Google', in annotation: <!DOCTYPE html><html><head><title>Google Drive - Virus scan warning</title><meta http-equiv="content-type" content="text/html; charset=utf-8"/><style nonce="CKp6bDe5WqqlCnPX0rH9AQ">.goog-link-button{position:relative;color:#15c;text-decoration:underline;cursor:pointer}.goog-link-button-disabled{color:#ccc;text-decoration:none;cursor:default}body{color:#222;font:normal 13px/1.4 arial,sans-serif;margin:0}.grecaptcha-badge{visibility:hidden}.uc-main{padding-top:50px;text-align:center}#uc-dl-icon{display:inline-block;margin-top:16px;padding-right:1em;vertical-align:top}#uc-text{display:inline-block;max-width:68ex;text-align:left}.uc-error-caption,.uc-warning-caption{color:#222;font-size:16px}#uc-download-link{text-decoration:none}.uc-name-size a{color:#15c;text-decoration:none}.uc-name-size a:visited{color:#61c;text-decoration:none}.uc-name-size a:active{color:#d14836;text-decoration:none}.uc-footer{color:#777;font-size:11px;padding-bottom:5ex;padding-top:5ex;text-align:center}.uc-footer a{color:#15c}.uc-footer a:visited{color:#61c}.uc-footer a:active{color:#d14836}.uc-footer-divider{color:#ccc;width:100%}.goog-inline-block{position:relative;display:-moz-inline-box;display:inline-block}* html .goog-inline-block{display:inline}*:first-child+html .goog-inline-block{display:inline}sentinel{}</style><link rel="icon" href="//ssl.gstatic.com/docs/doclist/images/drive_2022q3_32dp.png"/></head><body><div class="uc-main"><div id="uc-dl-icon" class="image-container"><div class="drive-sprite-aux-download-file"></div></div><div id="uc-text"><p class="uc-warning-caption">Google Drive can't scan this file for viruses.</p><p class="uc-warning-subcaption">We are experiencing technical difficulties. Would you still like to download this file? <span class="uc-name-size"><a href="/open?id=1w2eq2lHUuyJY97-a55wkhOCidii76fPW">43265_Lucas_Demarr_18.txt</a> (309)</span></p><form id="download-form" action="https://drive.usercontent.google.com/download" method="get"><input type="submit" id="uc-download-link" class="goog-inline-block jfk-button jfk-button-action" value="Download anyway"/><input type="hidden" name="id" value="1w2eq2lHUuyJY97-a55wkhOCidii76fPW"><input type="hidden" name="export" value="download"><input type="hidden" name="confirm" value="t"><input type="hidden" name="uuid" value="9a2f7a74-f246-4f50-a0bd-c8c0b8d565e7"></form></div></div><div class="uc-footer"><hr class="uc-footer-divider"></div></body></html>
Error converting segment to bbox: could not convert string to float: 'html><html><head><title>Google', in annotation: <!DOCTYPE html><html><head><title>Google Drive - Virus scan warning</title><meta http-equiv="content-type" content="text/html; charset=utf-8"/><style nonce="AbriuDKV1TfCuGhm2_iVwA">.goog-link-button{position:relative;color:#15c;text-decoration:underline;cursor:pointer}.goog-link-button-disabled{color:#ccc;text-decoration:none;cursor:default}body{color:#222;font:normal 13px/1.4 arial,sans-serif;margin:0}.grecaptcha-badge{visibility:hidden}.uc-main{padding-top:50px;text-align:center}#uc-dl-icon{display:inline-block;margin-top:16px;padding-right:1em;vertical-align:top}#uc-text{display:inline-block;max-width:68ex;text-align:left}.uc-error-caption,.uc-warning-caption{color:#222;font-size:16px}#uc-download-link{text-decoration:none}.uc-name-size a{color:#15c;text-decoration:none}.uc-name-size a:visited{color:#61c;text-decoration:none}.uc-name-size a:active{color:#d14836;text-decoration:none}.uc-footer{color:#777;font-size:11px;padding-bottom:5ex;padding-top:5ex;text-align:center}.uc-footer a{color:#15c}.uc-footer a:visited{color:#61c}.uc-footer a:active{color:#d14836}.uc-footer-divider{color:#ccc;width:100%}.goog-inline-block{position:relative;display:-moz-inline-box;display:inline-block}* html .goog-inline-block{display:inline}*:first-child+html .goog-inline-block{display:inline}sentinel{}</style><link rel="icon" href="//ssl.gstatic.com/docs/doclist/images/drive_2022q3_32dp.png"/></head><body><div class="uc-main"><div id="uc-dl-icon" class="image-container"><div class="drive-sprite-aux-download-file"></div></div><div id="uc-text"><p class="uc-warning-caption">Google Drive can't scan this file for viruses.</p><p class="uc-warning-subcaption">We are experiencing technical difficulties. Would you still like to download this file? <span class="uc-name-size"><a href="/open?id=1QC5rPIm96UQlxV-uoVCyeU0r9GA-3QEn">51934_pablo_pistelli_24.txt</a> (1.1k)</span></p><form id="download-form" action="https://drive.usercontent.google.com/download" method="get"><input type="submit" id="uc-download-link" class="goog-inline-block jfk-button jfk-button-action" value="Download anyway"/><input type="hidden" name="id" value="1QC5rPIm96UQlxV-uoVCyeU0r9GA-3QEn"><input type="hidden" name="export" value="download"><input type="hidden" name="confirm" value="t"><input type="hidden" name="uuid" value="ac05bfdb-ca3b-4d4e-bcd4-d820f9cd3b31"></form></div></div><div class="uc-footer"><hr class="uc-footer-divider"></div></body></html>
Error converting segment to bbox: could not convert string to float: 'html><html><head><title>Google', in annotation: <!DOCTYPE html><html><head><title>Google Drive - Virus scan warning</title><meta http-equiv="content-type" content="text/html; charset=utf-8"/><style nonce="aUovJNxVYvGSxIqNVv-1PQ">.goog-link-button{position:relative;color:#15c;text-decoration:underline;cursor:pointer}.goog-link-button-disabled{color:#ccc;text-decoration:none;cursor:default}body{color:#222;font:normal 13px/1.4 arial,sans-serif;margin:0}.grecaptcha-badge{visibility:hidden}.uc-main{padding-top:50px;text-align:center}#uc-dl-icon{display:inline-block;margin-top:16px;padding-right:1em;vertical-align:top}#uc-text{display:inline-block;max-width:68ex;text-align:left}.uc-error-caption,.uc-warning-caption{color:#222;font-size:16px}#uc-download-link{text-decoration:none}.uc-name-size a{color:#15c;text-decoration:none}.uc-name-size a:visited{color:#61c;text-decoration:none}.uc-name-size a:active{color:#d14836;text-decoration:none}.uc-footer{color:#777;font-size:11px;padding-bottom:5ex;padding-top:5ex;text-align:center}.uc-footer a{color:#15c}.uc-footer a:visited{color:#61c}.uc-footer a:active{color:#d14836}.uc-footer-divider{color:#ccc;width:100%}.goog-inline-block{position:relative;display:-moz-inline-box;display:inline-block}* html .goog-inline-block{display:inline}*:first-child+html .goog-inline-block{display:inline}sentinel{}</style><link rel="icon" href="//ssl.gstatic.com/docs/doclist/images/drive_2022q3_32dp.png"/></head><body><div class="uc-main"><div id="uc-dl-icon" class="image-container"><div class="drive-sprite-aux-download-file"></div></div><div id="uc-text"><p class="uc-warning-caption">Google Drive can't scan this file for viruses.</p><p class="uc-warning-subcaption">We are experiencing technical difficulties. Would you still like to download this file? <span class="uc-name-size"><a href="/open?id=1K3sGSpxQkMe2GJSCZHBRblhF_4RVpFkx">46019_taiel_raffaeli_13.txt</a> (942)</span></p><form id="download-form" action="https://drive.usercontent.google.com/download" method="get"><input type="submit" id="uc-download-link" class="goog-inline-block jfk-button jfk-button-action" value="Download anyway"/><input type="hidden" name="id" value="1K3sGSpxQkMe2GJSCZHBRblhF_4RVpFkx"><input type="hidden" name="export" value="download"><input type="hidden" name="confirm" value="t"><input type="hidden" name="uuid" value="2e7c030f-7934-4673-9ad5-614f9e76784b"></form></div></div><div class="uc-footer"><hr class="uc-footer-divider"></div></body></html>
Error converting segment to bbox: could not convert string to float: 'html><html><head><title>Google', in annotation: <!DOCTYPE html><html><head><title>Google Drive - Virus scan warning</title><meta http-equiv="content-type" content="text/html; charset=utf-8"/><style nonce="4oBUWOChUF7BzKh2ePOuUg">.goog-link-button{position:relative;color:#15c;text-decoration:underline;cursor:pointer}.goog-link-button-disabled{color:#ccc;text-decoration:none;cursor:default}body{color:#222;font:normal 13px/1.4 arial,sans-serif;margin:0}.grecaptcha-badge{visibility:hidden}.uc-main{padding-top:50px;text-align:center}#uc-dl-icon{display:inline-block;margin-top:16px;padding-right:1em;vertical-align:top}#uc-text{display:inline-block;max-width:68ex;text-align:left}.uc-error-caption,.uc-warning-caption{color:#222;font-size:16px}#uc-download-link{text-decoration:none}.uc-name-size a{color:#15c;text-decoration:none}.uc-name-size a:visited{color:#61c;text-decoration:none}.uc-name-size a:active{color:#d14836;text-decoration:none}.uc-footer{color:#777;font-size:11px;padding-bottom:5ex;padding-top:5ex;text-align:center}.uc-footer a{color:#15c}.uc-footer a:visited{color:#61c}.uc-footer a:active{color:#d14836}.uc-footer-divider{color:#ccc;width:100%}.goog-inline-block{position:relative;display:-moz-inline-box;display:inline-block}* html .goog-inline-block{display:inline}*:first-child+html .goog-inline-block{display:inline}sentinel{}</style><link rel="icon" href="//ssl.gstatic.com/docs/doclist/images/drive_2022q3_32dp.png"/></head><body><div class="uc-main"><div id="uc-dl-icon" class="image-container"><div class="drive-sprite-aux-download-file"></div></div><div id="uc-text"><p class="uc-warning-caption">Google Drive can't scan this file for viruses.</p><p class="uc-warning-subcaption">We are experiencing technical difficulties. Would you still like to download this file? <span class="uc-name-size"><a href="/open?id=1hwXgK25OWiQILBjlSS5_oXjMVcfSctSy">46019_taiel_raffaeli_09.txt</a> (940)</span></p><form id="download-form" action="https://drive.usercontent.google.com/download" method="get"><input type="submit" id="uc-download-link" class="goog-inline-block jfk-button jfk-button-action" value="Download anyway"/><input type="hidden" name="id" value="1hwXgK25OWiQILBjlSS5_oXjMVcfSctSy"><input type="hidden" name="export" value="download"><input type="hidden" name="confirm" value="t"><input type="hidden" name="uuid" value="6526b5a4-324f-4cde-a887-e2d8192ceec3"></form></div></div><div class="uc-footer"><hr class="uc-footer-divider"></div></body></html>
Error converting segment to bbox: could not convert string to float: 'html><html><head><title>Google', in annotation: <!DOCTYPE html><html><head><title>Google Drive - Virus scan warning</title><meta http-equiv="content-type" content="text/html; charset=utf-8"/><style nonce="ChZznPjcbYg1lmph4gdmlQ">.goog-link-button{position:relative;color:#15c;text-decoration:underline;cursor:pointer}.goog-link-button-disabled{color:#ccc;text-decoration:none;cursor:default}body{color:#222;font:normal 13px/1.4 arial,sans-serif;margin:0}.grecaptcha-badge{visibility:hidden}.uc-main{padding-top:50px;text-align:center}#uc-dl-icon{display:inline-block;margin-top:16px;padding-right:1em;vertical-align:top}#uc-text{display:inline-block;max-width:68ex;text-align:left}.uc-error-caption,.uc-warning-caption{color:#222;font-size:16px}#uc-download-link{text-decoration:none}.uc-name-size a{color:#15c;text-decoration:none}.uc-name-size a:visited{color:#61c;text-decoration:none}.uc-name-size a:active{color:#d14836;text-decoration:none}.uc-footer{color:#777;font-size:11px;padding-bottom:5ex;padding-top:5ex;text-align:center}.uc-footer a{color:#15c}.uc-footer a:visited{color:#61c}.uc-footer a:active{color:#d14836}.uc-footer-divider{color:#ccc;width:100%}.goog-inline-block{position:relative;display:-moz-inline-box;display:inline-block}* html .goog-inline-block{display:inline}*:first-child+html .goog-inline-block{display:inline}sentinel{}</style><link rel="icon" href="//ssl.gstatic.com/docs/doclist/images/drive_2022q3_32dp.png"/></head><body><div class="uc-main"><div id="uc-dl-icon" class="image-container"><div class="drive-sprite-aux-download-file"></div></div><div id="uc-text"><p class="uc-warning-caption">Google Drive can't scan this file for viruses.</p><p class="uc-warning-subcaption">We are experiencing technical difficulties. Would you still like to download this file? <span class="uc-name-size"><a href="/open?id=1YeE3zeMmBmOMt9RsCWRZ2bYeCsAiUIIt">51934_pablo_pistelli_05.txt</a> (1.2k)</span></p><form id="download-form" action="https://drive.usercontent.google.com/download" method="get"><input type="submit" id="uc-download-link" class="goog-inline-block jfk-button jfk-button-action" value="Download anyway"/><input type="hidden" name="id" value="1YeE3zeMmBmOMt9RsCWRZ2bYeCsAiUIIt"><input type="hidden" name="export" value="download"><input type="hidden" name="confirm" value="t"><input type="hidden" name="uuid" value="0737c2d8-6c83-4a6c-969d-c3b1c444be43"></form></div></div><div class="uc-footer"><hr class="uc-footer-divider"></div></body></html>

### Extensiones

In [ ]:
def normalize_images(input_dir):
    for filename in os.listdir(input_dir):
        if filename.lower().endswith(('.png', '.jpg', '.jpeg')):

            file_path = os.path.join(input_dir, filename)

            # Check if the image file exists and is readable
            if not os.path.exists(file_path):
                print(f"Error: Image file not found: {file_path}")
                continue

            image = cv2.imread(file_path)

            # Check if the image was loaded successfully
            if image is None:
                print(f"Error: Could not read image file: {file_path}")
                continue

            base_filename, _ = os.path.splitext(filename)
            output_filename = base_filename + '.png'
            output_path = os.path.join(input_dir, output_filename)

            cv2.imwrite(output_path, image)

            if not filename.lower().endswith('.png'):
                os.remove(file_path)

normalize_images(train_images_path)
normalize_images(val_images_path)

Error: Could not read image file: /content/dataset/images/train/R-45829_Abril_Rodriguez_04.png
Error: Could not read image file: /content/dataset/images/train/64191_Sofia_BrizuelaCipolletti_10.jpg
Error: Could not read image file: /content/dataset/images/train/s56189_salvador_sanchez_45.jpg
Error: Could not read image file: /content/dataset/images/train/f37478_santiago_ferrero_06.jpg
Error: Could not read image file: /content/dataset/images/train/s56189_salvador_sanchez_153.jpg
Error: Could not read image file: /content/dataset/images/train/71846_Brisa_Menescaldi_05.png
Error: Could not read image file: /content/dataset/images/train/51934_pablo_pistelli_27.png
Error: Could not read image file: /content/dataset/images/train/51659_antonio_peroni_19.jpg
Error: Could not read image file: /content/dataset/images/train/P51951_pablo_pistarelli_01.png
Error: Could not read image file: /content/dataset/images/train/71846_Brisa_Menescaldi_03.png
Error: Could not read image file: /content/dataset/images/train/37524_augusto_farias_07.jpg
Error: Could not read image file: /content/dataset/images/train/L32425_eugenio_lopez_19.png
Error: Could not read image file: /content/dataset/images/train/f37478_santiago_ferrero_29.jpg
Error: Could not read image file: /content/dataset/images/train/43237686_Constantino_Ferrucci_7.png

## Descarga

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
folder_path = '/content/dataset'
zip_path = '/content/drive/MyDrive/carta_base.zip'

# Create a zip file from the folder
shutil.make_archive(base_name=zip_path.replace('.zip', ''), format='zip', root_dir=folder_path)

print(f"Folder has been zipped and saved to {zip_path}")

# List files in the destination directory to verify
destination_directory = '/content/drive/MyDrive'
print("Files in destination directory:")
for file_name in os.listdir(destination_directory):
    print(file_name)

Folder has been zipped and saved to /content/drive/MyDrive/carta_base.zip
Files in destination directory:
carta_base.zip